<?php
/**
 * Healthcheck - Analysis: Environmental Impact
 */

/* @var $phpWord PHPWord */
$phpWord = $this->phpword;

/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs               = $healthcheckViewModel->getGraphs();


$section->addPageBreak();
$section->addTitle("Analysis: Environmental Impact", 1);
$section->addTitle('Forest and Water Consumption', 2);
$section->addText(sprintf('Did you know that it takes one average-sized tree to produce %2$s pages of standard 20lb office paper? Paper production also uses a tremendous amount of water and other solvents to produce traditional white copy paper. Based on your annual page volume we estimate the following tree and water requirements to produce documents for %1$s:', $healthcheckViewModel->healthcheck->getClient()->companyName, number_format(Healthcheck_ViewModel_Healthcheck::PAGES_PER_TREE)));
$cellWidths  = array(
    350,
    1500
);
$imageWidth  = 100;
$imageHeight = 170;
$imageTable  = $section->addTable($this->styles->tables->tripleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell($cellWidths[0], $this->styles->tables->tripleimage->cell1)->addImage(PUBLIC_PATH . "/img/reports/health-check/tree.jpg", array('width' => $imageWidth, 'height' => $imageHeight));
$imageTable->addCell($cellWidths[0], $this->styles->tables->tripleimage->cell1)->addImage(PUBLIC_PATH . "/img/reports/health-check/tree.jpg", array('width' => $imageWidth, 'height' => $imageHeight));
$imageTable->addCell($cellWidths[1], $this->styles->tables->tripleimage->cell1)->addText(sprintf(' %1$s trees', number_format($healthcheckViewModel->calculateNumberOfTreesUsed())), "forestWaterFont", array('align' => 'center', 'valign' => 'center'));
$imageTable->addCell($cellWidths[0], $this->styles->tables->tripleimage->cell1)->addImage(PUBLIC_PATH . "/img/reports/health-check/droplet.jpg", array('width' => $imageWidth, 'height' => $imageHeight));
$imageTable->addCell($cellWidths[0], $this->styles->tables->tripleimage->cell1)->addImage(PUBLIC_PATH . "/img/reports/health-check/droplet.jpg", array('width' => $imageWidth, 'height' => $imageHeight));
$imageTable->addCell($cellWidths[0], $this->styles->tables->tripleimage->cell1)->addText(sprintf(' %1$s gallons water', number_format($healthcheckViewModel->calculateNumberOfGallonsWaterUsed())), "forestWaterFont");


$section->addTitle('Energy Consumption', 2);
$section->addText(sprintf('You are currently using an estimated average of %1$s kilowatt hours (kWh) per month to operate printing devices at an estimated monthly cost of $%2$s, assuming a cost of $%3$s per kWh.', number_format($healthcheckViewModel->getAveragePowerUsagePerMonth()), number_format($healthcheckViewModel->getAveragePowerCostPerMonth()), number_format($healthcheckViewModel->healthcheck->getHealthcheckSettings()->kilowattsPerHour, 2)));
$section->addText('The following lists the devices with the highest average power consumption per month.');

$cellWidths = array(
    2657,
    1857,
    2457,
    2057
);

$highEnergyTable = $section->addTable($this->styles->tables->highenergy->tablestyle);
$highEnergyTable->addRow($this->styles->tables->highriskdevices->rowheight);
$highEnergyTable->addCell($cellWidths [0], $this->styles->tables->utilization->cellHeader)->addText('High Risk Devices', 'bold_text', 'nospacing_centeralign');
$highEnergyTable->addCell($cellWidths [1], $this->styles->tables->utilization->cellHeader)->addText('Serial No.', 'bold_text', 'nospacing_centeralign');
$highEnergyTable->addCell($cellWidths [2], $this->styles->tables->utilization->cellHeader)->addText('Avg. kWh Consumption Per Month Count', 'bold_text', 'nospacing_centeralign');
$highEnergyTable->addCell($cellWidths [3], $this->styles->tables->utilization->cellHeader)->addText('Avg. Power Cost per Month', 'bold_text', 'nospacing_centeralign');
/* @var $device Proposalgen_Model_DeviceInstance */
$rowCount = 0;
foreach ($healthcheckViewModel->getHighPowerConsumptionDevices() as $device)
{
    $highEnergyTable->addRow();
    $highEnergyTable->addCell($cellWidths [0], $this->styles->tables->highriskdevices->cell1)->addText($device->getDeviceName(), null, 'nospacing');
    $highEnergyTable->addCell($cellWidths [1], $this->styles->tables->highriskdevices->cell2)->addText(($device->serialNumber) ? : "Unknown", null, 'nospacing_centeralign');
    $highEnergyTable->addCell($cellWidths [2], $this->styles->tables->highriskdevices->cell3)->addText(number_format($device->getAverageMonthlyPowerConsumption()) . ' kWh', null, 'nospacing_centeralign');
    $highEnergyTable->addCell($cellWidths [3], $this->styles->tables->highriskdevices->cell4)->addText($this->currency($device->getAverageMonthlyPowerCost()), null, 'nospacing_centeralign');
    $rowCount++;
    if ($rowCount >= 3)
    {
        break;
    }
}

$section->addTextBreak();

$section->addTitle('Green Features: Duplex Printing and Scanning', 2);

$section->addText('If you printed every document on both sides of the page, you could use up to 50% less paper than you would by only printing on one side. You could further reduce your paper consumption by using a scanner and e-mailing documents instead of printing copies for distribution.');
$textrun = $section->createTextRun();
$textrun->addText('By printing 25% more documents on both sides of the page than you are now, you could save ');
$textrun->addText(sprintf('%1$s trees and %2$s gallons of water used in paper production per year.', number_format($healthcheckViewModel->calculateQuarterOfNumberOfTreesUsed()), number_format($healthcheckViewModel->calculateQuarterOfNumberOfGallonsWaterUsed())));
$section->addText('The following charts show how many of your printing devices have duplex printing and scanning capabilities:');

$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($graphs ['faxCapableBar']);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($graphs [14]);

$section->addTextBreak();
$cellWidths = array(
    2275,
    2275,
    2275,
    2275,
);

$scanAndFaxTable = $section->addTable($this->styles->tables->utilization->tablestyle);
$scanAndFaxTable->addRow();
$scanAndFaxTable->addCell($cellWidths [0], $this->styles->tables->utilization->cellHeader)->addText('Device Name', 'bold_text', 'nospacing_centeralign');
$scanAndFaxTable->addCell($cellWidths [1], $this->styles->tables->utilization->cellHeader)->addText('Serial No.', 'bold_text', 'nospacing_centeralign');
$scanAndFaxTable->addCell($cellWidths [2], $this->styles->tables->utilization->cellHeader)->addText('Average Monthly Volume', 'bold_text', 'nospacing_centeralign');
$scanAndFaxTable->addCell($cellWidths [3], $this->styles->tables->utilization->cellHeader)->addText('Average Monthly Scan Pages', 'bold_text', 'nospacing_centeralign');
$scanAndFaxTable->addCell($cellWidths [3], $this->styles->tables->utilization->cellHeader)->addText('Average Monthly Faxed Pages', 'bold_text', 'nospacing_centeralign');
/* @var $device Proposalgen_Model_DeviceInstance */
foreach ($healthcheckViewModel->getFaxAndScanTableDevices() as $device)
{
    $deviceName = str_replace("Hewlett-Packard", "HP", $device->getDeviceName());
    $scanAndFaxTable->addRow($this->styles->tables->utilization->rowheight);
    $scanAndFaxTable->addCell($cellWidths [0], $this->styles->tables->utilization->cell1)->addText($deviceName, null, 'nospacing_centeralign');
    $scanAndFaxTable->addCell($cellWidths [1], $this->styles->tables->utilization->cell2)->addText(($device->serialNumber) ? : "Unknown", null, 'nospacing_centeralign');
    $scanAndFaxTable->addCell($cellWidths [2], $this->styles->tables->utilization->cell3)->addText($this->formatPageVolume($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_rightalign');
    $scanAndFaxTable->addCell($cellWidths [3], $this->styles->tables->utilization->cell4)->addText(($device->getMasterDevice()->isCopier) ? $this->formatPageVolume($device->getPageCounts()->getScanPageCount()->getMonthly()) : '-', null, 'nospacing_rightalign');
    $scanAndFaxTable->addCell($cellWidths [3], $this->styles->tables->utilization->cell4)->addText(($device->getMasterDevice()->isFax) ? $this->formatPageVolume($device->getPageCounts()->getFaxPageCount()->getMonthly()) : '-', null, 'nospacing_rightalign');
}
$section->addTextBreak();