<?php
/**
 * Healthcheck - Analysis: Technology Reliability and User Productivity
 */
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs               = $healthcheckViewModel->getGraphs();

$section->addPageBreak();
$section->addTitle("Analysis: Technology Reliability and User Productivity", 1);
$section->addTitle('Age of Printing Devices', 2);
$section->addText(sprintf('We estimate the average age of your printing devices is %1$s year(s); a good industry average is 3 years. Devices over 5 years old receive, on average, one repair per year.', number_format($healthcheckViewModel->getAverageAgeOfDevices(), 1)));
$section->addText("The breakdown of the age of your printing devices is shown below.");

$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(5010, $this->styles->tables->tripleimage->cell1)->addImage($graphs ['PrintIQAgePieGraph']);
$imageTable->addCell(5010, $this->styles->tables->tripleimage->cell2)->addImage($graphs ['PrintIQPagesPrintedByAgeBarGraph']);
$section->addTitle('Technology Features and Functionality', 2);
$section->addText('The ability to scan and fax documents from convenient locations helps to improve document workflow and productivity, and scanning can also help reduce the number of pages printed. Color printing capabilities are important if you are generating client-facing or other important documents in-house.');
$section->addText('The charts below show the percentage of your printing devices that are capable of copying, duplex printing, and color printing.');

$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell1)->addImage($graphs ['CopyCapableDevicesGraph']);
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell2)->addImage($graphs ['DuplexCapableDevicesGraph']);
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell3)->addImage($graphs ['colorCapablePieChart']);

$section->addTextBreak();
$section->addText(sprintf('If you are in need of additional features and functionality to improve workflow and print quality, %1$s has a variety of printing devices that can meet your specific business needs. If you already have capable equipment, we can manage the printing assets you have.', $this->companyName));

$section->addTitle('A3 Functionality', 2);

$section->addText("Do you have too much invested in larger, more expensive hardware? Many centralized MFP's are built for large volumes, in excess of 10,000 pages per month. In addition, they can print on larger paper sizes such as A3 (11 x 17 inch) formats. This section outlines the number of A3 Compatible devices you have.");
$section->addText(sprintf('You currently have %1$s devices in your fleet, and of those, %2$s are A3 Compatible. Of the %3$s total pages printed, %4$s are A3 pages, or %5$s%%. You should also consider A3 devices where AMPV\'s are low as candidates for replacement or movement.',
    $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount(),
    count($healthcheckViewModel->getDevices()->a3DeviceInstances->getDeviceInstances()),
    $this->formatPageVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()),
    $this->formatPageVolume($healthcheckViewModel->getDevices()->a3DeviceInstances->getPageCounts()->getPrintA3CombinedPageCount()->getMonthly()),
    number_format($healthcheckViewModel->calculatePercentageA3Pages() * 100, 0)
));

$section->addText(sprintf('While analyzing your paper usage we noted that you have purchased %1$s%% of A3 paper over the past month.'),
    number_format($healthcheckViewModel->calculatePercentageA3Pages() * 100, 0)
);

$section->addText("The following are A3 designated devices with a low page volume. Going forward we can look at moving from A3 back to A4 to save you money.");


$cellWidths = array(
    2275,
    2275,
    2275,
    2275,
);

$lowestA3UtilizationTable = $section->addTable($this->styles->tables->utilization->tablestyle);
$lowestA3UtilizationTable->addRow(null, $this->styles->tables->rowheader);
$lowestA3UtilizationTable->addCell($cellWidths [0], $this->styles->tables->utilization->cellHeader)->addText('Device Name', 'bold_text', 'nospacing_centeralign');
$lowestA3UtilizationTable->addCell($cellWidths [1], $this->styles->tables->utilization->cellHeader)->addText('Serial No.', 'bold_text', 'nospacing_centeralign');
$lowestA3UtilizationTable->addCell($cellWidths [2], $this->styles->tables->utilization->cellHeader)->addText('Average Monthly Volume', 'bold_text', 'nospacing_centeralign');
$lowestA3UtilizationTable->addCell($cellWidths [3], $this->styles->tables->utilization->cellHeader)->addText('Average Monthly A3 Volume', 'bold_text', 'nospacing_centeralign');
/* @var $device DeviceInstanceModel */
$ctr = 0;
foreach ($healthcheckViewModel->getUnderutilizedA3Devices() as $device)
{
    $lowestA3UtilizationTable->addRow($this->styles->tables->utilization->rowheight, $this->styles->tables->rowstyle);
    $lowestA3UtilizationTable->addCell($cellWidths [0], $this->styles->tables->utilization->cell1)->addText($device->getDeviceName(), null, 'nospacing_centeralign');
    $lowestA3UtilizationTable->addCell($cellWidths [1], $this->styles->tables->utilization->cell2)->addText(($device->serialNumber) ?: "Unknown", null, 'nospacing_centeralign');
    $lowestA3UtilizationTable->addCell($cellWidths [2], $this->styles->tables->utilization->cell3)->addText($this->formatPageVolume($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_centeralign');
    $lowestA3UtilizationTable->addCell($cellWidths [3], $this->styles->tables->utilization->cell4)->addText($this->formatPageVolume($device->getPageCounts()->getPrintA3CombinedPageCount()->getMonthly()), null, 'nospacing_centeralign');

    if (++$ctr >= 3)
    {
        break;
    }
}
$section->addTextBreak();


$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell1)->addImage($graphs ['a3CapablePieChart']);
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell2)->addImage($graphs ['a3PagePercent']);
