<?php
/**
 * Healthcheck Title Page
 */
/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;

/* @var $titlePage \PhpOffice\PhpWord\Element\Section */
$titlePage = $this->section;
/**
 * Right aligned logo
 */
$detailsTable = $titlePage->addTable(['cellMarginRight' => 900]);
$detailsTable->addRow(4090);
$imageCell = $detailsTable->addCell(12240);
$imageCell->addText(' ');

/**
 * Report Title + Client Name
 */
$detailsTable->addRow(4070);
$textCell = $detailsTable->addCell(12240);
$textCell->addText(My_Brand::getDealerBranding()->healthCheckTitle, 'titlepage_title', 'nospacing_rightalign');
$textCell->addText('Prepared For: ', 'titlepage_subtitle_italic', 'rightalign');
$textCell->addText(sprintf('%1$s', $healthcheckViewModel->healthcheck->getClient()->companyName), 'titlepage_subtitle', [
    'align'       => 'right',
    'spaceBefore' => 200,
]);

$addressModel = $healthcheckViewModel->healthcheck->getClient()->getAddress();

$textCell->addText($addressModel->addressLine1, 'titlepage_subtitle', 'rightalign');
$textCell->addText($addressModel->addressLine2, 'titlepage_subtitle', 'rightalign');
$textCell->addText(sprintf('%s, %s', $addressModel->city, $addressModel->region), 'titlepage_subtitle', 'rightalign');
$textCell->addText($addressModel->getCountry()->name, 'titlepage_subtitle', 'rightalign');

$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText("\tTogether, we'll identify how our world-class", 'titlepage_text', 'titleTextStyle1');
$titlePage->addText("\tManaged Print Services can meet all of your print", 'titlepage_text', 'titleTextStyle1');
$titlePage->addText("\trequirements, create a cost-efficient print environment and", 'titlepage_text', 'titleTextStyle1');
$titlePage->addText("\timpact your bottom line. We can offer:", 'titlepage_text', 'titleTextStyle1');
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText("\t- A dedicated account team ready to help", 'titlepage_listtext', 'titleTextStyle2');
$titlePage->addText("\t- Highly trained, managed print specialists to help ensure maximum productivity", 'titlepage_listtext', 'titleTextStyle2');
$titlePage->addText("\t- Professional partnerships with OEM brands", 'titlepage_listtext', 'titleTextStyle2');
$titlePage->addText("\t- Best-in-class solutions to save you time and money", 'titlepage_listtext', 'titleTextStyle2');
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText('', null, 'titleStyleSmallLine');