<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$fh = fopen($this->savePath, "w+");

/**
 * TODO lrobert: Convert to PHP Excel when possible
 */
fputcsv($fh, array("GROSS MARGIN REPORT"));
fputcsv($fh, array("AMPV = Average Monthly Page Volume"));
fputcsv($fh, array());
fputcsv($fh, array(My_Brand::getDealerBranding()->mpsProgramName . " Black And White CPP:", $this->PrintIQ_Black_And_White_CPP, "", "", "", "", "Total Cost:", $this->Total_Cost));
fputcsv($fh, array(My_Brand::getDealerBranding()->mpsProgramName . " Color CPP:", $this->PrintIQ_Color_CPP, "", "", "", "", "Total Revenue:", $this->Total_Revenue));
fputcsv($fh, array("Weighted Black And White CPP:", $this->Weighted_Black_And_White_CPP, "", "", "", "", "Monthly Profit:", $this->Monthly_Profit));
fputcsv($fh, array("Weighted Color CPP:", $this->Weighted_Color_CPP, "", "", "", "", "Overall Margin:", $this->Overall_Margin));
fputcsv($fh, array("Black And White Margin:", $this->Black_And_White_Margin, "", "", "", "", "Color Margin:", $this->Color_Margin));
fputcsv($fh, array());
fputcsv($fh, $this->fieldTitlesLvl1);
fputcsv($fh, $this->fieldTitlesLvl2);
foreach ($this->fieldList as $line)
{
    fputcsv($fh, $line);
}
fputcsv($fh, array());
fputcsv($fh, $this->fieldTotals);

fclose($fh);
echo $this->baseUrl($this->publicFileName);
