<?php 
	/* @var $form Quotegen_Form_Quote_Group */
	$form = $this->element;
	$quote = $form->getQuote();
	$addDeviceToGroupSubform = $form->getSubForm('addDeviceToGroup');
	$deviceQuantitySubform = $form->getSubForm('deviceQuantity');
	$addGroupSubform = $form->getSubForm('addGroup');
	
	$deleteDeviceButton = $deviceQuantitySubform->getElement('deleteDeviceFromGroup');
	
	// Get elements in the form 
	$deviceElement = $addDeviceToGroupSubform->getElement('quoteDeviceId');
	$quantityElement = $addDeviceToGroupSubform->getElement('quantity');
	$groupElement = $addDeviceToGroupSubform->getElement('quoteDeviceGroupId');
?>

<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
    
    <?php foreach ($quote->getQuoteDeviceGroups() as $quoteDeviceGroup) : /* @var $quoteDeviceGroup Quotegen_Model_QuoteDeviceGroup */ ?>
    <h3><?php echo $quoteDeviceGroup->getName(); ?></h3>
    <table class="table table-condensed table-striped table-bordered">
        <tr>
            <th>Item</th>
            <th style="width: 120px;">SKU</th>
            <th style="width: 120px;">Cost</th>
            <th style="width: 50px;">Margin</th>
            <th style="width: 100px;">Price</th>
            <th style="width: 80px;">Quantity</th>
            <th style="width: 100px;">Subtotal</th>
        </tr>
        <?php foreach ($quoteDeviceGroup->getQuoteDeviceGroupDevices() as $quoteDeviceGroupDevice) : /* @var $quoteDeviceGroupDevice Quotegen_Model_QuoteDeviceGroupDevice */ ?>
        <tr>
            <td><?php echo $quoteDeviceGroupDevice->getQuoteDevice()->getName() ?></td>
    		<td><?php echo $quoteDeviceGroupDevice->getQuoteDevice()->getSku() ?></td>
    		<td><?php echo $this->currency($quoteDeviceGroupDevice->getQuoteDevice()->calculatePackageCost()); ?></td>
    		<td><?php echo number_format($quoteDeviceGroupDevice->getQuoteDevice()->getMargin()); ?>%</td>
    		<td><?php echo $this->currency($quoteDeviceGroupDevice->getQuoteDevice()->getPackagePrice()); ?></td>
    		<td><?php echo number_format($quoteDeviceGroupDevice->getQuantity()); ?></td>
    		<td><?php echo $this->currency($quoteDeviceGroupDevice->calculateSubtotal()); ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php endforeach; ?>

    
    <?php echo $form->getDisplayGroup('actions')->render(); ?>
</form>