<?php 
	/* @var $form Quotegen_Form_Quote_Group */
	$form = $this->element;
	$quote = $form->getQuote();
	$isLeased = ($quote->getQuoteType() === Quotegen_Model_Quote::QUOTE_TYPE_LEASED);
?>


<table class="table table-condensed table-striped table-bordered">
    <tr>
        <th>Item</th>
        <th style="width: 75px;">Cost</th>
        <th style="width: 80px;">Markup ($)</th>
        <th style="width: 80px;">Margin (%)</th>
        <th style="width: 100px;">Price Per Unit</th>
        <th style="width: 60px;">Quantity</th>
        <th style="width: 100px;">Price</th>
        <?php if ($isLeased) : ?>
        <th style="width: 100px;">Monthly Subtotal</th>
        <?php endif; ?>
    </tr>
    <?php foreach ($quote->getQuoteDevices() as $quoteDevice) : /* @var $quoteDevice Quotegen_Model_QuoteDevice */ ?>
    <tr>
        <td><h5><?php echo $quoteDevice->getName() ?><br/><small><?php echo $quoteDevice->getSku() ?></small></h5></td>
		<td><?php echo $this->currency($quoteDevice->calculatePackageCost()); ?></td>
		<td><?php echo $form->getElement("packageMarkup_{$quoteDevice->getId()}"); ?></td>
		<td><?php echo $form->getElement("margin_{$quoteDevice->getId()}"); ?></td>
		<td><?php echo $this->currency( (float) $quoteDevice->calculatePackagePrice() ); ?></td>
		<td><?php echo number_format($quoteDevice->calculateTotalQuantity()); ?></td>
		<td><?php echo $this->currency( (float) $quoteDevice->calculateTotalPrice() ); ?></td>
		<?php if ($isLeased) : ?>
		<td><?php echo $this->currency( (float) $quoteDevice->calculateTotalMonthlyLeasePrice() ); ?></td>
		<?php endif; ?>
    </tr>
    <?php endforeach; ?>
    <tr>
        <th colspan="6" style="text-align: right">Totals:</th>
        <th><?php echo $this->currency((float) $quote->calculateTotalPrice() ); ?></th>
        <?php if ($isLeased) : ?>
        <th><?php echo $this->currency((float) $quote->calculateTotalMonthlyLeasePrice() ); ?></th>
        <?php endif; ?>
    </tr>
</table>




<?php echo $form->getDisplayGroup('actions')->render(); ?>
