<?php
/* @var $phpWord PHPWord */
$phpWord = $this->phpword;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

// Initialize some properties
$properties = $phpWord->getProperties();
$properties->setCreator('MPS Assessment Software');
$properties->setCompany('MPS Assessment Software');
$properties->setCategory('Customer Report');
$properties->setTitle('Customer Cost Analysis');
$properties->setLastModifiedBy('MPS Assessment Software');
$properties->setCreated(time());
$properties->setModified(time());
$properties->setSubject('MPS Assessment Software');

/**
 * Define the different Sections
 */

// This section is landscape with 0.5" margins insead of 1"
$mainSection = $phpWord->createSection(array(
    'orientation'  => 'portrait',
    'marginLeft'   => 720,
    'marginRight'  => 720,
    'marginTop'    => 720,
    'marginBottom' => 720
));


$phpWord->addTitleStyle(1, array(
    "bold"  => true,
    "size"  => 15,
    "color" => My_Brand::$reportHeadingColor,
    array(
        'borderBottomSize' => 1,
    )
));


/* Tables for the device layouts */
$widthTwips       = 11111;
$header_color     = $this->wordStyles->default->tableHeaderBackgroundColor;
$sub_header_color = "0096A6";
$even_color       = "EFEFEF";
$odd_color        = "FCFCFC";
$footer_color     = "b8cce3";
$highlight_color  = "ebc7a4";

$standard_cell = (object)array(
    "even"           => array(
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
    ),
    "odd"            => array(
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'right'
    )
);

$standard_cell_left = (object)array(
    "even"             => array(
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "odd"              => array(
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "fontStyle"        => null,
    "paragraphStyle"   => array(
        'spaceAfter' => 0,
        'align'      => 'left'
    ),
    "manufacturerName" => (object)array(
            "fontStyle"      => array('italic' => true),
            "paragraphStyle" => array(
                'spaceAfter' => 0,
                'align'      => 'left'
            ),
        ),
    "modelName"        => (object)array(
            "fontStyle"      => array('bold' => true),
            "paragraphStyle" => array(
                'spaceAfter' => 0,
                'align'      => 'left'
            ),
        ),
);

$standard_cell_no_right_border = (object)array(
    "even"           => array(
        "bgColor" => $even_color,
    ),
    "odd"            => array(
        "bgColor" => $odd_color,
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'right'
    )
);

$standard_header = (object)array(
    "cellStyle"      => array(
        'bgColor' => $header_color
    ),
    "fontStyle"      => array(
        'bold' => true
    ),
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'center'
    )
);

$costAnalysis = (object)array(
    "tablestyle" => array(
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ),
    "col1Width"  => $widthTwips * 0.20,
    "col2Width"  => $widthTwips * 0.1333,
    "col3Width"  => $widthTwips * 0.1333,
    "col4Width"  => $widthTwips * 0.1333,
    "col5Width"  => $widthTwips * 0.1333,
    "col6Width"  => $widthTwips * 0.1333,
    "col7Width"  => $widthTwips * 0.1333,
    "body"       => (object)array(
            "rowheight" => null,
            "cell1"     => $standard_cell_left,
            "cell2"     => $standard_cell,
            "cell3"     => $standard_cell,
            "cell4"     => $standard_cell,
            "cell5"     => $standard_cell,
            "cell6"     => $standard_cell,
            "cell7"     => $standard_cell_no_right_border
        ),
    "header"     => (object)array(
            'header'     => $standard_header,
            'sub_header' => $standard_sub_header,
        ),
);

/**
 * Here we put all our table styles into an object that gets passed to each of the view scripts
 */
$styles = (object)array(
    "tables" => (object)array(
            "costanalysis" => $costAnalysis,
        )
);

/**
 * An array of view variables to pass to the partial scripts
 */
$data = array(
    "phpword"             => $this->phpword,
    "assessmentViewModel" => $assessmentViewModel,
    "section"             => $mainSection,
    "styles"              => $styles,
);

/**
 * Render each of the view scripts for different parts of the document
 */
$this->partial("report/costanalysis/docx/01_header.phtml", $data);
$this->partial("report/costanalysis/docx/02_maintable.phtml", $data);

$objWriter = PHPWord_IOFactory::createWriter($this->phpword, 'Word2007');
$objWriter->save($this->savePath);

/**
 * Finally we write out the url to the file we just generated.
 */
echo $this->baseUrl($this->publicFileName);