<?php
/**
 * Cost Analysis - Header information
 *
 * This script contains everything that comes before the big table of
 * information in the cost analysis.
 */
/* @var $section PHPWord_Section */
$section = $this->section;
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$section->addTitle('Customer Cost Analysis');

$textRun = $section->createTextRun();
$textRun->addText("Average Monochrome CPP: ", array("bold" => true));
$textRun->addText($this->currency($assessmentViewModel->calculateCustomerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage, array("precision" => 4)));

$textRun = $section->createTextRun();
$textRun->addText("Average Color CPP: ", array("bold" => true));
$textRun->addText($this->currency($assessmentViewModel->calculateCustomerWeightedAverageMonthlyCostPerPage()->colorCostPerPage, array("precision" => 4)));
