<?php
/**
 * Cost Analysis - Header information
 *
 * This script contains everything that comes before the big table of
 * information in the cost analysis.
 */
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$section->addTitle('Customer Cost Analysis');

$textRun = $section->addTextRun();
$textRun->addText("Average Monochrome CPP: ", array("bold" => true));
$textRun->addText($this->formatCostPerPage($assessmentViewModel->calculateCustomerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage));

$textRun = $section->addTextRun();
$textRun->addText("Average Color CPP: ", array("bold" => true));
$textRun->addText($this->formatCostPerPage($assessmentViewModel->calculateCustomerWeightedAverageMonthlyCostPerPage()->colorCostPerPage));
