<?php 
	/* @var $form Quotegen_Form_Quote_Group */
	$form = $this->element;
	
	/* @var $quote Quotegen_Model_Quote  */
	$quote = $form->getQuote();
?>
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <h4><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse1"> Page Settings </a></h4>
        </div>
        <div id="collapse1" class="accordion-body in">
            <div class="accordion-inner">
            	<?php echo $form->getElement('adminCostPerPage'); ?>
            	<?php echo $form->getElement('serviceCostPerPage'); ?>
            	<?php echo $form->getElement('pageCoverageColor'); ?>
            	<?php echo $form->getElement('pageCoverageMonochrome'); ?>
            	<?php echo $form->getElement('pricingConfigId'); ?>  
            </div>
        </div>
    </div>
</div>
	
<?php 
	/* @var $quoteDeviceGroup Quotegen_Model_QuoteDeviceGroup */
	foreach ($quote->getQuoteDeviceGroups() as $quoteDeviceGroup ) : ?>
	<h3><?php echo $quoteDeviceGroup->name; ?></h3>
	<table class='table table-bordered table-striped table-condensed'>
		<tr class='header-row'>
			<th style='width: 225px;'>Device</th>
			<th >Sku</th>
			<th style='width: 50px;'> Quantity </th>
			<th style='width: 100px;'> Black CPP</th>
			<th style='width: 80px;'> Black Pages Per Device</th>
			<th style='width: 100px;'> Color CPP </th>
			<th style='width: 80px;'> Color Pages Per Device</th>
		</tr>
		<tr>		<?php 
		    /* @var $quoteDeviceGroupDevice Quotegen_Model_QuoteDeviceGroupDevice */
		    foreach ( $quoteDeviceGroup->getQuoteDeviceGroupDevices() as $quoteDeviceGroupDevice ) : ?>
		    <?php $quoteDevice = $quoteDeviceGroupDevice->getQuoteDevice(); ?>
		    <td><?php echo $quoteDevice->name; ?></td>
		    <td><?php echo $quoteDevice->oemSku; ?></td>
		    <td><?php echo $quoteDeviceGroupDevice->quantity?>
		    <td><?php echo $this->currency($quoteDevice->calculateMonochromeCostPerPage(), array('precision' => 4)); ?></td>
			<td><?php echo $form->getElement('quantity_monochrome_' . $quoteDeviceGroup->id . '_' . $quoteDeviceGroupDevice->quoteDeviceId) ;?> </td>
			<td><?php echo (($quoteDeviceGroupDevice->getQuoteDevice()->isColorCapable()) ? $this->currency($quoteDevice->calculateColorCostPerPage(), array('precision' => 4)) : 'N/A' ); ?></td>
			<td><?php echo $form->getElement('quantity_color_' . $quoteDeviceGroup->id . '_' . $quoteDeviceGroupDevice->quoteDeviceId) ;?> </td>
		</tr>
		<?php endforeach;?>
	</table>
		<?php endforeach;?>
		
	<div class="row-fluid">
		<div class="span6">
			<h3> Included Pages </h3>
			<table class="table table-condensed table-bordered">
				<tr>
					<th></th>
					<th>Monochrome</th>
					<th>Color</th>
				</tr>
				<tr>
					<th>Quantity</th>
					<td> <?php echo $quote->calculateTotalMonochromePages();?>  </td>
					<td> <?php echo $quote->calculateTotalColorPages();?>  </td>
				</tr>
				<tr>
					<th>Est. CPP</th>
					<td> <?php echo $this->currency($quote->calculateMonochromeCostPerPage(), array('precision' => 4)); ?>  </td>
					<td> <?php echo $this->currency($quote->calculateColorCostPerPage(), array('precision' => 4)); ?>  </td>
				</tr>
				<tr>
					<th>Margin (%)</th>
					<td> <?php echo $form->getElement('monochromePageMargin'); ?> </td>
					<td> <?php echo $form->getElement('colorPageMargin'); ?> </td>
				</tr>
				<tr>
					<th>Price Per Page</th>
					<td> <?php echo $this->currency($quote->calculateMonochromePricePerPage(), array('precision' => 4)); ?></td>
					<td> <?php echo $this->currency($quote->calculateColorPricePerPage(),array('precision' => 4)); ?></td>
				</tr>
				<tr>
					<th>Monthly Cost</th>
					<td> <?php echo $this->currency($quote->calculateMonochromePageCost(),array('precision' => 2)); ?></td>
					<td> <?php echo $this->currency($quote->calculateColorPageCost(), array('precision' => 2)) ;?></td>
				</tr>
				<tr>
					<th>Monthly Revenue</th>
					<td> <?php echo $this->currency($quote->calculateMonochromePageRevenue(),array('precision' => 2)); ?></td>
					<td> <?php echo $this->currency($quote->calculateColorPageRevenue(),array('precision' => 2)); ?></td>
				</tr>
				<tr>
					<th>Monthly Profit</th>
					<td> <?php echo $this->currency($quote->calculateMonochromePageProfit(), array('precision' => 2)); ?></td>
					<td> <?php echo $this->currency($quote->calculateColorPageProfit(),array('precision' => 2)); ?></td>
				</tr>
			</table>
		</div>
		<div class="span6">
			<h3> Overage Pages </h3>
			<table class="table table-condensed table-bordered">
				<tr>
					<th></th>
					<th>Monochrome</th>
					<th>Color</th>
				</tr>
				<tr>
					<th>Est. CPP</th>
					<td> <?php echo $this->currency($quote->calculateMonochromeCostPerPage(), array('precision' => 4)); ?>  </td>
					<td> <?php echo $this->currency($quote->calculateColorCostPerPage(), array('precision' => 4)); ?>  </td>
				</tr>
				<tr>
					<th>Margin (%)</th>
					<td><?php echo $form->getElement('monochromeOverageMargin'); ?></td>
					<td><?php echo $form->getElement('colorOverageMargin'); ?></td>
				</tr>
				<tr>
					<th>Overage Rate Per Page</th>
					<td> <?php echo $this->currency($quote->calculateMonochromeOverageRatePerPage(), array('precision' => 3)); ?></td>
					<td> <?php echo $this->currency($quote->calculateColorOverageRatePerPage(), array('precision' => 3)); ?></td>
				</tr>
			</table>	
		</div>
	</div>
	<?php echo $form->getDisplayGroup('actions')->render(); ?>
</form>