<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$fh = fopen($this->savePath, "w+");


// Please note that is is a hacked way around things. This should be done more properly with PHPExcel or fputcsv.
fputs($fh, $this->appendix_titles);
fputs($fh, "\n");
fputs($fh, $this->appendix_values);

fclose($fh);

if (Zend_Controller_Front::getInstance()->getRequest()->isXmlHttpRequest()) echo $this->baseUrl($this->publicFileName);
else header('Location: '.$this->baseUrl($this->publicFileName));
