<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
<div class="clearfix">
    <h1>All Options</h1>
    <a class="btn btn-success btn-small pull-right" href="<?php echo $this->url(array('action' => 'create')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
</div>
<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Sku</th>
            <th>Categories</th>
            <th style="width: 120px;">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator->getCurrentItems() as $option) : /* @var $option Quotegen_Model_Option */ ?>
        <tr>
            <td><?php echo $option->getName(); ?></td>
            <td><?php echo $option->getDescription(); ?></td>
            <td><?php echo Zend_Locale_Format::toNumber($option->getCost(), array ('precision' => 2));?></td>
            <td><?php echo $option->getSku();?></td>
            <?php if (count($option->getCategories()) > 0 ) :
				$categoryNames = array();
            ?>
            <td>
            <?php foreach ($option->getCategories() as $category) : /* @var $category Quotegen_Model_Category */?>
            	<?php $categoryNames [] = $category->getName(); ?>
            <?php endforeach; ?>
            <?php echo implode(', ', $categoryNames);?>
            </td>
            <?php else : ?>
            	<td></td>
            <?php endif; ?>
            <td>
                <div class="btn-group">
                	<a class="btn btn-info" title="View" href="<?php echo $this->url( array ( 'action' => 'view', 'id' =>  $option->getId())); ?>"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-warning" title="Edit" href="<?php echo $this->url(array ( 'action' => 'edit', 'id' =>  $option->getId())); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-danger" title="Delete" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' =>  $option->getId())); ?>"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>        
<?php else : ?>
<div class='well'>
	<a class="btn btn-success btn-small pull-right" href="<?php echo $this->url(array('action' => 'create')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
	<h1>There are no options</h1>
</div>
<?php endif; ?>
