<div class="page-header">
        <h1>Hardware Library - <small>All Options</small></h1>
</div>
<div class="clearfix">
    <a class="btn btn-success pull-right btn-small create-button" href="<?php echo $this->url(array('action' => 'create')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
</div>
<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th style="width: 85px;">Cost</th>
            <th style="width: 85px;">Sku</th>
            <th>Categories</th>
            <th style="width: 55px;">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator->getCurrentItems() as $option) : /* @var $option Quotegen_Model_Option */ ?>
        <tr>
            <td><?php echo $option->name; ?></td>
            <td><?php echo $option->description; ?></td>
            <td style="text-align: right"><?php echo $this->currency($option->cost);?></td>
            <td><?php echo $option->oemSku;?></td>
            <?php if (count($option->getCategories()) > 0 ) :
				$categoryNames = array();
            ?>
            <td>
            <?php foreach ($option->getCategories() as $category) : /* @var $category Quotegen_Model_Category */?>
            	<?php $categoryNames [] = $category->name; ?>
            <?php endforeach; ?>
            <?php echo implode(', ', $categoryNames);?>
            </td>
            <?php else : ?>
            	<td></td>
            <?php endif; ?>
            <td>
                <div class="btn-group">
                    <a class="btn btn-mini btn-warning" title="Edit" href="<?php echo $this->url(array ( 'action' => 'edit', 'id' =>  $option->id)); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-mini btn-danger" title="Delete" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' =>  $option->id)); ?>"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>        
<?php else : ?>
<div class='well'>
	<h1>There are no options</h1>
</div>
<?php endif; ?>
