<?php /* @var $option Quotegen_Model_Option */ $option = $this->option; ?>
<div class="page-header">
    <h1>Option Management</h1>
</div>
<div class="well">
    <dl class="dl-horizontal">
        <dt>Name</dt><dd><?php echo $option->getName(); ?></dd>
        <dt>Description</dt><dd><?php echo $option->getDescription(); ?></dd>
        <dt>Sku</dt><dd><?php echo $option->getOemSku() ?></dd>
        <dt>Price</dt><dd><?php echo $option->getCost() ?></dd>
        <dt>Options</dt>
        
        <?php /* @var $category Quotegen_Model_Category */ foreach ($option->getCategories() as $category) : ?>
        	<dd><?php echo $category->name ?></dd>
        <?php endforeach ?>
        
    </dl>
</div>