<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\OptionModel;

/* @var $option OptionModel */
$option = $this->option;
?>
<div class="container">
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd><?= $option->name; ?></dd>
        <dt>Description</dt>
        <dd><?= $option->description; ?></dd>
        <dt>SKU</dt>
        <dd><?= $option->oemSku ?></dd>
        <dt>Price</dt>
        <dd><?= $option->cost ?></dd>
        <dt>Options</dt>
        <?php foreach ($option->getCategories() as $category) : ?>
            <dd><?= $category->name ?></dd>
        <?php endforeach ?>
    </dl>
</div>