<?php /* @var $client Quotegen_Model_Client */ $client = $this->client; ?>
<div class="page-header">
    <h1>Client Management</h1>
</div>
<div class="well">
    <dl class="dl-horizontal">
        <dt>Name</dt><dd><?php echo $client->getCompanyName(); ?></dd>
        <dt>Legal Name</dt><dd><?php echo nl2br($client->getLegalName())  . '&nbsp'; ?></dd>
        <dt>Country</dt><dd><?php echo nl2br($client->getCompanyCountry()); ?></dd>
        <dt>State or Province</dt><dd><?php echo nl2br($client->getCompanyStateOrProv()); ?></dd>
        <dt>City</dt><dd><?php echo nl2br($client->getCompanyCity()); ?></dd>
        <dt>Address 1</dt><dd><?php echo nl2br($client->getCompanyAddress1()); ?></dd>
        <dt>Address 2</dt><dd><?php echo nl2br($client->getCompanyAddress2()) . '&nbsp'; ?></dd>
        <dt>Zip or Postal Code</dt><dd><?php echo nl2br($client->getCompanyZipOrPostalCode()); ?></dd>
        <dt>Contact First Name</dt><dd><?php echo nl2br($client->getContactFirstName()); ?></dd>
        <dt>Contact Last Name</dt><dd><?php echo nl2br($client->getContactLastName()); ?></dd>
        <dt>Phone Number</dt><dd><?php echo nl2br($client->getContactPhone()); ?></dd>
    </dl>
</div>