<?php /* @var $client Quotegen_Model_Client */ $client = $this->client; ?>
<div class="page-header">
    <h1>Client Management</h1>
</div>
<div class="well">
    <dl class="dl-horizontal">
        <dt>Name</dt><dd><?php echo $client->getName(); ?></dd>
        <dt>Phone Number</dt><dd><?php echo $client->getPhoneNumber(); ?></dd>
        <dt>Address</dt><dd><?php echo nl2br($client->getAddress()); ?></dd>
    </dl>
</div>