<?php 
/* @var $form Proposalgen_Form_Survey_General */
$form = $this->element;

$rank1 = $form->getElement('rank1');
$rank2 = $form->getElement('rank2');
$rank3 = $form->getElement('rank3');
$rank4 = $form->getElement('rank4');
$rank5 = $form->getElement('rank5');

$this->headScript()->captureStart(); ?>
$(document).ready(function() {
    $(':radio').click(function() {
        $(this).parent().parent().siblings().children().children(':radio').attr('checked', false);
    });
});
<?php $this->headScript()->captureEnd(); ?>

<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
<?php echo $form->getElement('numb_employees'); ?>

<table class="table table-bordered table-striped table-condensed" style="width: 600px;">
    <tr>
        <td style="width: 450px;"><strong>Please rank the following:</strong></td>
        <td style="width: 15px;">1</td>
        <td style="width: 15px;">2</td>
        <td style="width: 15px;">3</td>
        <td style="width: 15px;">4</td>
        <td style="width: 15px;">5</td>
    </tr><tr>
        <td>Ensure your printing hardware matches your print volume needs.<?php if ($rank1->hasErrors()) : ?><div class="control-group error"><?php echo $rank1->renderErrors(); ?></div><?php endif; ?></td>
        <td><?php echo $rank1->renderValue(null, '1'); ?></td>
        <td><?php echo $rank2->renderValue(null, '1'); ?></td>
        <td><?php echo $rank3->renderValue(null, '1'); ?></td>
        <td><?php echo $rank4->renderValue(null, '1'); ?></td>
        <td><?php echo $rank5->renderValue(null, '1'); ?></td>
    </tr><tr>
        <td>Increase uptime and productivity for your employees.<?php if ($rank2->hasErrors()) : ?><div class="control-group error"><?php echo $rank2->renderErrors(); ?></div><?php endif; ?></td>
        <td><?php echo $rank1->renderValue(null, '2'); ?></td>
        <td><?php echo $rank2->renderValue(null, '2'); ?></td>
        <td><?php echo $rank3->renderValue(null, '2'); ?></td>
        <td><?php echo $rank4->renderValue(null, '2'); ?></td>
        <td><?php echo $rank5->renderValue(null, '2'); ?></td>
    </tr><tr>
        <td>Streamline logistics for supplies, service and hardware acquisition.<?php if ($rank3->hasErrors()) : ?><div class="control-group error"><?php echo $rank3->renderErrors(); ?></div><?php endif; ?></td>
        <td><?php echo $rank1->renderValue(null, '3'); ?></td>
        <td><?php echo $rank2->renderValue(null, '3'); ?></td>
        <td><?php echo $rank3->renderValue(null, '3'); ?></td>
        <td><?php echo $rank4->renderValue(null, '3'); ?></td>
        <td><?php echo $rank5->renderValue(null, '3'); ?></td>
    </tr><tr>
        <td>Reduce environmental impact.<?php if ($rank4->hasErrors()) : ?><div class="control-group error"><?php echo $rank4->renderErrors(); ?></div><?php endif; ?></td>
        <td><?php echo $rank1->renderValue(null, '4'); ?></td>
        <td><?php echo $rank2->renderValue(null, '4'); ?></td>
        <td><?php echo $rank3->renderValue(null, '4'); ?></td>
        <td><?php echo $rank4->renderValue(null, '4'); ?></td>
        <td><?php echo $rank5->renderValue(null, '4'); ?></td>
    </tr><tr>
        <td>Reduce costs.<?php if ($rank5->hasErrors()) : ?><div class="control-group error"><?php echo $rank5->renderErrors(); ?></div><?php endif; ?></td>
        <td><?php echo $rank1->renderValue(null, '5'); ?></td>
        <td><?php echo $rank2->renderValue(null, '5'); ?></td>
        <td><?php echo $rank3->renderValue(null, '5'); ?></td>
        <td><?php echo $rank4->renderValue(null, '5'); ?></td>
        <td><?php echo $rank5->renderValue(null, '5'); ?></td>
    </tr>
</table>


<?php echo $this->partial('survey/form/form-actions.phtml', array('canGoBack' => true)); ?>
</form>