<?php 
/* @var $form Proposalgen_Form_Survey_Finance */
$form = $this->element;

$itHoursRadio = $form->getElement('itHoursRadio');
$ithours = $form->getElement('itHours');

$monthlyBreakdownRadio = $form->getElement('monthlyBreakdownRadio');
$monthlyBreakdown = $form->getElement('monthlyBreakdown');



?>
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">

<div class="control-group <?php echo ($itHoursRadio->hasErrors() || $ithours->hasErrors()) ? 'error' : '' ?>">
    <?php echo $ithours->renderLabel(); ?>
    <div class="controls">
    <?php echo $itHoursRadio->renderViewHelper(); ?>
    <?php echo $itHoursRadio->renderErrors(); ?>
    </div>
    <div class="controls">
        <div class="input-append">
            <?php echo str_replace(PHP_EOL, '', $ithours->renderViewHelper()); ?><span class="add-on"><?php echo $ithours->getDescription(); ?></span>
        </div>
        <?php echo $ithours->renderErrors(); ?>
    </div>
</div>
<hr>
<div class="control-group <?php echo ($monthlyBreakdownRadio->hasErrors() || $monthlyBreakdown->hasErrors()) ? 'error' : '' ?>">
    <?php echo $monthlyBreakdown->renderLabel(); ?>
    <div class="controls">
        <?php echo $monthlyBreakdownRadio->renderViewHelper(); ?>
        <?php echo $monthlyBreakdownRadio->renderErrors(); ?>
    </div>
    <div class="controls">
        <div class="input-append">
            <?php echo str_replace(PHP_EOL, '', $monthlyBreakdown->renderViewHelper()); ?><span class="add-on"><?php echo $monthlyBreakdown->getDescription(); ?></span>
        </div>
        <?php echo $monthlyBreakdown->renderErrors(); ?>
    </div>
</div>
<hr>


<?php echo $form->getElement('location_tracking'); ?>


<?php echo $this->partial('survey/form/form-actions.phtml', array('canGoBack' => true)); ?>
</form>