<?php
/* @var $form Proposalgen_Form_Assessment_Survey */
$form                       = $this->element;
$tonerCostRadio             = $form->getElement('toner_cost_radio');
$tonerCost                  = $form->getElement('toner_cost');
$laborCostRadio             = $form->getElement('labor_cost_radio');
$laborCost                  = $form->getElement('labor_cost');
$averagePurchase            = $form->getElement('avg_purchase');
$itHourlyRate               = $form->getElement('it_hourlyRate');
$numberOfMonthlyOrdersRadio = $form->getElement('inkTonerOrderRadio');
$numberOfMonthlyOrders      = $form->getElement('numb_monthlyOrders');
$numberOfVendors            = $form->getElement('numb_vendors');
$itHoursRadio               = $form->getElement('itHoursRadio');
$ithours                    = $form->getElement('itHours');
$monthlyBreakdownRadio      = $form->getElement('monthlyBreakdownRadio');
$monthlyBreakdown           = $form->getElement('monthlyBreakdown');
$pageCoverageQuestion       = $form->getElement('pageCoverageQuestion');
$pageCoverageMonochrome     = $form->getElement('pageCoverage_BW');
$pageCoverageColor          = $form->getElement('pageCoverage_Color');
$printVolume                = $form->getElement('printVolume');
$repairTime                 = $form->getElement('repairTime');

$this->headScript()->appendFile($this->baseUrl('/js/proposalgen/survey/survey/surveyForm.js'));

?>

<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">

    <!--    FINANCE SECTION   -->
    <h2 id="surveyFinanceSection">Finance</h2>

    <!-- Cost of ink and toner -->
    <div class="control-group <?php echo ($tonerCostRadio->hasErrors() || $tonerCost->hasErrors()) ? 'error' : '' ?>">
        <?php echo $tonerCost->renderLabel(); ?>
        <div class="controls">
            <?php echo $tonerCostRadio->renderViewHelper(); ?>
            <?php echo $tonerCostRadio->renderErrors(); ?>
        </div>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on"><?php echo $tonerCost->getDescription(); ?></span><?php echo str_replace(PHP_EOL, '', $tonerCost->renderViewHelper()); ?><?php echo $tonerCost->renderErrors(); ?>
            </div>
        </div>
    </div>
    <hr>

    <!-- Amount spent on outside service (labor cost) -->
    <div class="control-group <?php echo ($laborCostRadio->hasErrors() || $laborCost->hasErrors()) ? 'error' : '' ?>">
        <?php echo $laborCost->renderLabel(); ?>
        <div class="controls">
            <?php echo $laborCostRadio->renderViewHelper(); ?>
            <?php echo $laborCostRadio->renderErrors(); ?>
        </div>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on"><?php echo $laborCost->getDescription(); ?></span><?php echo str_replace(PHP_EOL, '', $laborCost->renderViewHelper()); ?><?php echo $laborCost->renderErrors(); ?>
            </div>
        </div>
    </div>
    <hr>

    <!-- Average Cost To Execute Supplies Order -->
    <div class="control-group <?php echo ($averagePurchase->hasErrors()) ? 'error' : '' ?>">
        <?php echo $averagePurchase->renderLabel(); ?>
        <div class="controls">

            <div class="input-prepend">
                <span class="add-on"><?php echo $averagePurchase->getDescription(); ?></span><?php echo str_replace(PHP_EOL, '', $averagePurchase->renderViewHelper()); ?><?php echo $averagePurchase->renderErrors(); ?>
            </div>
        </div>
    </div>
    <hr>

    <!-- IT Hourly Rate -->
    <div class="control-group <?php echo ($itHourlyRate->hasErrors()) ? 'error' : '' ?>">
        <?php echo $itHourlyRate->renderLabel(); ?>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on"><?php echo $itHourlyRate->getDescription(); ?></span><?php echo str_replace(PHP_EOL, '', $itHourlyRate->renderViewHelper()); ?><?php echo $itHourlyRate->renderErrors(); ?>
            </div>
        </div>
    </div>
    <hr>

    <!--    PURCHASING SECTION   -->
    <h2 id="surveyPurchasingSection">Purchasing</h2>

    <!-- Number of supply vendors-->
    <?php echo $numberOfVendors; ?>
    <hr>

    <!-- Number of monthly orders -->
    <div class="control-group <?php echo ($numberOfMonthlyOrdersRadio->hasErrors() || $numberOfMonthlyOrders->hasErrors()) ? 'error' : '' ?>">
        <?php echo $numberOfMonthlyOrdersRadio->renderLabel(); ?>
        <div class="controls">
            <?php echo $numberOfMonthlyOrdersRadio->renderViewHelper(); ?>
            <?php echo $numberOfMonthlyOrdersRadio->renderErrors(); ?>
        </div>
        <div class="controls">
            <div class="input-append">
                <?php echo str_replace(PHP_EOL, '', $numberOfMonthlyOrders->renderViewHelper()); ?>
                <span class="add-on"><?php echo $numberOfMonthlyOrders->getDescription(); ?></span><?php echo $numberOfMonthlyOrders->renderErrors(); ?>
            </div>
        </div>
    </div>
    <hr>

    <!--    IT SECTION   -->
    <h2 id="surveyItSection">IT</h2>

    <!-- IT Hours -->
    <div class="control-group <?php echo ($itHoursRadio->hasErrors() || $ithours->hasErrors()) ? 'error' : '' ?>">
        <?php echo $ithours->renderLabel(); ?>
        <div class="controls">
            <?php echo $itHoursRadio->renderViewHelper(); ?>
            <?php echo $itHoursRadio->renderErrors(); ?>
        </div>
        <div class="controls">
            <div class="input-append">
                <?php echo str_replace(PHP_EOL, '', $ithours->renderViewHelper()); ?><span class="add-on"><?php echo $ithours->getDescription(); ?></span>
            </div>
            <?php echo $ithours->renderErrors(); ?>
        </div>
    </div>
    <hr>

    <!-- Monthly Breakdowns-->
    <div class="control-group <?php echo ($monthlyBreakdownRadio->hasErrors() || $monthlyBreakdown->hasErrors()) ? 'error' : '' ?>">
        <?php echo $monthlyBreakdown->renderLabel(); ?>
        <div class="controls">
            <?php echo $monthlyBreakdownRadio->renderViewHelper(); ?>
            <?php echo $monthlyBreakdownRadio->renderErrors(); ?>
        </div>
        <div class="controls">
            <div class="input-append">
                <?php echo str_replace(PHP_EOL, '', $monthlyBreakdown->renderViewHelper()); ?>
                <span class="add-on"><?php echo $monthlyBreakdown->getDescription(); ?></span>
            </div>
            <?php echo $monthlyBreakdown->renderErrors(); ?>
        </div>
    </div>
    <hr>

    <!--    USERS SECTION   -->
    <h2 id="surveyUsersSection">Users</h2>

    <p>Page coverages range from 5% to 10% for monochrome and 15% to 25% for color. Estimate your own average page coverages.</p>

    <!-- Page Coverage Question -->
    <div class="control-group <?php echo ($pageCoverageMonochrome->hasErrors()) ? 'error' : '' ?>">
        <?php echo $pageCoverageMonochrome->renderLabel(); ?>
        <div class="controls">
            <div class="input-append">
                <?php echo str_replace(PHP_EOL, '', $pageCoverageMonochrome->renderViewHelper()); ?>
                <span class="add-on"><?php echo $pageCoverageMonochrome->getDescription(); ?></span>
            </div>
            <?php echo $pageCoverageMonochrome->renderErrors(); ?>
        </div>
    </div>
    <div class="control-group <?php echo ($pageCoverageColor->hasErrors()) ? 'error' : '' ?>">
        <?php echo $pageCoverageColor->renderLabel(); ?>
        <div class="controls">
            <div class="input-append">
                <?php echo str_replace(PHP_EOL, '', $pageCoverageColor->renderViewHelper()); ?>
                <span class="add-on"><?php echo $pageCoverageColor->getDescription(); ?></span>
            </div>
            <?php echo $pageCoverageColor->renderErrors(); ?>
        </div>
    </div>
    <hr>

    <!-- Inkjet print volume -->
    <?php echo $printVolume; ?>
    <hr>

    <!-- Repair Time Question -->
    <?php echo $repairTime; ?>

    <?php echo $form->getDisplayGroup('actions')->render(); ?>

</form>