<?php

$settings = \MPSToolbox\Settings\Entities\DealerSettingsEntity::getDealerSettings();

/** @var \MPSToolbox\Legacy\Modules\QuoteGenerator\Models\ClientModel $selectedClient */
$selectedClient = null;
/** @var \MPSToolbox\Legacy\Modules\QuoteGenerator\Models\ContactModel $contact */
$contact = null;

$tonerVendorList = \MPSToolbox\Legacy\Modules\ProposalGenerator\Mappers\TonerVendorManufacturerMapper::getInstance()->fetchAllForDealerDropdown();

$clientOptions = [];
foreach($this->clients as $client) {
    $clientName = $client->companyName;
    $contact = \MPSToolbox\Legacy\Modules\QuoteGenerator\Mappers\ContactMapper::getInstance()->getContactByClientId($client->id);
    if (empty($contact->email)) $clientName .= ' (1)';
    if ($this->clientId==$client->id) {
        $selectedClient = $client;
        $selectedContact = $contact;
        $monochromeRank = explode(',',$selectedClient->ecomMonochromeRank);
        $colorRank = explode(',',$selectedClient->ecomColorRank);
    }
    $clientOptions[$client->id] = $clientName;
}

?>
<div class="container">
    <form method="post">
        <div class="row">
            <div class="col-sm-4">
                <p>Select a client</p>
            </div>
            <div class="col-sm-8">
                <select class="form-control" onchange="window.location.href='?client='+this.value">
                    <option></option>
                    <?php foreach($clientOptions as $id=>$clientName) { ?><option <?= $this->clientId==$id?'selected="selected"':'' ?> value="<?= $id ?>"><?= $clientName ?></option><?php } ?>
                </select>
                <?php if ($selectedClient) { ?>
                <p>
                    &nbsp;<br>
                    <a href="/company/clients/edit/<?= $selectedClient->id ?>" class="btn btn-primary">Edit Client Details</a>
                    <?php if (!empty($settings->shopSettings->shopifyName)) { ?>
                    &nbsp;
<?php
if (empty($selectedContact->email)) {
    echo '<button class="btn" disabled="disabled" type="button">Synchronize with Shopify</button><p><em><i class="fa fa-fw fa-exclamation-circle text-danger"></i> Shopify requires an e-mail address.</em></p>';
} else {
    echo '<button id="btn-shopifySync" class="btn btn-primary" type="button" onclick="shopifySync(this)">Synchronize Details with Shopify</button>';
}
?>
                    <?php } ?>
                </p>
                <script>
                    function sync_customer_done() {
                        $('#btn-shopifySync').replaceWith('<span style="color:green">Synchronized</span>');
                    }
                    function shopifySync(btn) {
                        $(btn).attr('disabled','disabled').text('Busy...');
                        var url = 'http://proxy.mpstoolbox.com/shopify/sync_customer.php?id=<?= $this->clientId ?>&dealerId=<?= \MPSToolbox\Entities\DealerEntity::getDealerId() ?>&origin=<?= $_SERVER['HTTP_HOST'] ?>';
                        //$.getScript(url, function() {});
                        $('body').append('<img style="display:none" src="'+url+'">');
                        window.setTimeout(sync_customer_done, 1000);
                    }
                </script>
                <?php } ?>
            </div>
        </div>
        <hr>
<?php if ($selectedClient) { ?>
        <div class="row">
            <div class="col-sm-4">
                <h3>E-Commerce Details</h3>
            </div>
            <div class="col-sm-8">
                <p>
                    <label>Price Level</label>
                    <select class="form-control" name="priceLevelId">
                        <?php foreach ($this->price_levels as $line) echo '<option '.($selectedClient->priceLevelId==$line['id']?'selected="selected"':'').' value="'.$line['id'].'">'.$line['name'].' ('.floatVal($line['margin']).'%)</option>'; ?>
                    </select>
                </p>
                <p>
                    <label>Transaction type</label>
                    <select class="form-control" name="transactionType">
                        <?php foreach (['Credit Card','Purchase Order'] as $value) echo '<option '.($selectedClient->transactionType==$value?'selected="selected"':'').' value="'.$value.'">'.$value.'</option>'; ?>
                    </select>
                </p>
                <p>
                    <label>Notification template</label>
                    <select class="form-control" name="templateNum">
                        <?php foreach (['1','2','3'] as $value) echo '<option '.($selectedClient->templateNum==$value?'selected="selected"':'').' value="'.$value.'">'.$value.'</option>'; ?>
                    </select>
                </p>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-4">
                <h3>Supply Vendor Preference</h3>
                <p>Select the supply vendors for toner replacement suggestions</p>
                <p><em>Note: The system always uses OEM as the <strong>last</strong> option. If you leave this blank then it will use <strong>only OEM</strong> supplies.</em></p>
            </div>
            <div class="col-sm-8">
                <p>
                    <label>Monochrome</label>
                    <select id="ecomMonochromeRank" name="ecomMonochromeRank[]" multiple="true" class="tonerMultiselect form-control">
                        <?php foreach($tonerVendorList as $id=>$name) echo '<option value="'.$id.'" '.(in_array($id,$monochromeRank)?'selected="selected"':'').'>'.$name.'</option>' ?>
                    </select>
                </p>
                <p>
                    <label>Color</label>
                    <select id="ecomColorRank" name="ecomColorRank[]" multiple="true" class="tonerMultiselect form-control">
                        <?php foreach($tonerVendorList as $id=>$name) echo '<option value="'.$id.'" '.(in_array($id,$colorRank)?'selected="selected"':'').'>'.$name.'</option>' ?>
                    </select>
                </p>

            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-4">
                <h3>Supply Cupboard Models</h3>
                <p>Select the printer models that will appear in the "Supply Cupboard"</p>
            </div>
            <div class="col-sm-8">
                <table class="table table-striped table-hover">
                    <?php

                    /** @var Zend_Db_Adapter_Abstract $db */
                    $db = Zend_Db_Table::getDefaultAdapter();
                    foreach ($db->fetchAll("
  select md.id, concat(mf.displayname,' ',md.modelName) as n
  from master_devices md
    join manufacturers mf on md.manufacturerId=mf.id
    join rms_device_instances di on di.masterDeviceId=md.id
  where di.clientId={$this->clientId}
  group by md.id
  order by n
") as $line) {
                        ?>
                        <tr>
                            <td><?= $line['n'] ?></td>
                            <td>
                                <select name="notSupportedMasterDevices[]" class="form-control">
                                    <option value="" <?= in_array($line['id'], explode(',',$selectedClient->notSupportedMasterDevices))?'':'selected="selected"' ?>>Yes</option>
                                    <option value="<?= $line['id'] ?>" <?= in_array($line['id'], explode(',',$selectedClient->notSupportedMasterDevices))?'selected="selected"':'' ?>> - No - </option>
                                </select>
                            </td>
                        </tr>
                    <?php
                    }
                    ?>
                </table>
            </div>
        </div>
        <div class="pull-right">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
<?php } ?>
    </form>
</div>
<script>
    require(['jquery', 'jquery.ui.multiselect'], function ($)
    {
        $(function ()
        {
            $('.tonerMultiselect').multiselect({
                selectionMode        : 'click',
                availableListPosition: 'left',
                sortable             : true

            });
        });
    });
</script>