<?php
/**
 * adddevice.phtml
 * admin only
 * allows uploader to add and request devices
 * 
 * @author: John Sadler
 * @version: v1.0
 * 
 * 08.22.2011 - JJS: Removed is_leased field
 */
?>

<?php $this->headScript()->captureStart('append','text/javascript') ?>
	
	$(document).ready(function() {
		$( "#mps_launch_date" ).datepicker({ dateFormat: 'mm/dd/yy', changeMonth: true, changeYear: true});
	
		$("#toner_config").change(function() {
			var config = new Array("black", "cyan", "magenta", "yellow", "3color", "4color");
			var config_name = $("#toner_config option:selected").text();
			
			switch(config_name) {
				case "Black Only":
					config = new Array("cyan", "magenta", "yellow", "3color", "4color");
					if($("#is_leased").is(":checked")) {
                        document.getElementById("black_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="black_toner_SKU">* Black Yield:</label>';
                    	document.getElementById("black_toner_SKU-label").style.display = "block";
                        document.getElementById("black_toner_SKU-element").style.display = "none";
                        document.getElementById("black_toner_price-element").style.display = "none";
                       	document.getElementById("black_toner_yield-element").style.display = "inline";
                       	
                        document.getElementById("black_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="black_comp_SKU">Black Yield:</label>';
                    	document.getElementById("black_comp_SKU-label").style.display = "block";
                        document.getElementById("black_comp_SKU-element").style.display = "none";
                        document.getElementById("black_comp_price-element").style.display = "none";
                       	document.getElementById("black_comp_yield-element").style.display = "inline";
					} else {
                        document.getElementById("black_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="black_toner_SKU">* Black SKU / Price / Yield:</label>';
                    	document.getElementById("black_toner_SKU-label").style.display = "block";
                        document.getElementById("black_toner_SKU-element").style.display = "inline";
                        document.getElementById("black_toner_price-element").style.display = "inline";
                       	document.getElementById("black_toner_yield-element").style.display = "inline";
                       	
                        document.getElementById("black_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="black_comp_SKU">Black SKU / Price / Yield:</label>';
                    	document.getElementById("black_comp_SKU-label").style.display = "block";
                        document.getElementById("black_comp_SKU-element").style.display = "inline";
                        document.getElementById("black_comp_price-element").style.display = "inline";
                       	document.getElementById("black_comp_yield-element").style.display = "inline";
					}
					break;
				case "3 Color - Combined":
					config = new Array("cyan", "magenta", "yellow", "4color");
					if($("#is_leased").is(":checked")) {
                        document.getElementById("black_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="black_toner_SKU">* Black Yield:</label>';
                        document.getElementById("black_toner_SKU-label").style.display = "block";
                        document.getElementById("black_toner_SKU-element").style.display = "none";
                        document.getElementById("black_toner_price-element").style.display = "none";
                    	document.getElementById("black_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("3color_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="3color_toner_SKU">* 3 Color Yield:</label>';
                        document.getElementById("3color_toner_SKU-label").style.display = "block";
                        document.getElementById("3color_toner_SKU-element").style.display = "none";
                        document.getElementById("3color_toner_price-element").style.display = "none";
                    	document.getElementById("3color_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("black_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="black_comp_SKU">Black Yield:</label>';
                        document.getElementById("black_comp_SKU-label").style.display = "block";
                        document.getElementById("black_comp_SKU-element").style.display = "none";
                        document.getElementById("black_comp_price-element").style.display = "none";
                    	document.getElementById("black_comp_yield-element").style.display = "inline";
                    	
                        document.getElementById("3color_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="3color_comp_SKU">3 Color Yield:</label>';
                        document.getElementById("3color_comp_SKU-label").style.display = "block";
                        document.getElementById("3color_comp_SKU-element").style.display = "none";
                        document.getElementById("3color_comp_price-element").style.display = "none";
                    	document.getElementById("3color_comp_yield-element").style.display = "inline";
                    	
					} else {
                        document.getElementById("black_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="black_toner_SKU">* Black SKU / Price / Yield:</label>';
                        document.getElementById("black_toner_SKU-label").style.display = "block";
                        document.getElementById("black_toner_SKU-element").style.display = "inline";
                        document.getElementById("black_toner_price-element").style.display = "inline";
                    	document.getElementById("black_toner_yield-element").style.display = "inline";
                        
                        document.getElementById("3color_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="3color_toner_SKU">* 3 Color SKU / Price / Yield:</label>';
                        document.getElementById("3color_toner_SKU-label").style.display = "block";
                        document.getElementById("3color_toner_SKU-element").style.display = "inline";
                        document.getElementById("3color_toner_price-element").style.display = "inline";
                    	document.getElementById("3color_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("black_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="black_comp_SKU">Black SKU / Price / Yield:</label>';
                        document.getElementById("black_comp_SKU-label").style.display = "block";
                        document.getElementById("black_comp_SKU-element").style.display = "inline";
                        document.getElementById("black_comp_price-element").style.display = "inline";
                    	document.getElementById("black_comp_yield-element").style.display = "inline";
                        
                        document.getElementById("3color_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="3color_comp_SKU">3 Color SKU / Price / Yield:</label>';
                        document.getElementById("3color_comp_SKU-label").style.display = "block";
                        document.getElementById("3color_comp_SKU-element").style.display = "inline";
                        document.getElementById("3color_comp_price-element").style.display = "inline";
                    	document.getElementById("3color_comp_yield-element").style.display = "inline";
                    	
					}
					break;
				case "3 Color - Separated":
					config = new Array("3color", "4color");
					if($("#is_leased").is(":checked")) {
						display = "none";
                        document.getElementById("black_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="black_toner_SKU">* Black Yield:</label>';
                        document.getElementById("black_toner_SKU-label").style.display = "block";
                        document.getElementById("black_toner_SKU-element").style.display = "none";
                        document.getElementById("black_toner_price-element").style.display = "none";
                    	document.getElementById("black_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("cyan_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="cyan_toner_SKU">* Cyan Yield:</label>';
                        document.getElementById("cyan_toner_SKU-label").style.display = "block";
                        document.getElementById("cyan_toner_SKU-element").style.display = "none";
                        document.getElementById("cyan_toner_price-element").style.display = "none";
                    	document.getElementById("cyan_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("magenta_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="magenta_toner_SKU">* Magenta Yield:</label>';
                        document.getElementById("magenta_toner_SKU-label").style.display = "block";
                        document.getElementById("magenta_toner_SKU-element").style.display = "none";
                        document.getElementById("magenta_toner_price-element").style.display = "none";
                    	document.getElementById("magenta_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("yellow_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="yellow_toner_SKU">* Yellow Yield:</label>';
                        document.getElementById("yellow_toner_SKU-label").style.display = "block";
                        document.getElementById("yellow_toner_SKU-element").style.display = "none";
                        document.getElementById("yellow_toner_price-element").style.display = "none";
                    	document.getElementById("yellow_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("black_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="black_comp_SKU">Black Yield:</label>';
                        document.getElementById("black_comp_SKU-label").style.display = "block";
                        document.getElementById("black_comp_SKU-element").style.display = "none";
                        document.getElementById("black_comp_price-element").style.display = "none";
                    	document.getElementById("black_comp_yield-element").style.display = "inline";
                    	
                        document.getElementById("cyan_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="cyan_comp_SKU">Cyan Yield:</label>';
                        document.getElementById("cyan_comp_SKU-label").style.display = "block";
                        document.getElementById("cyan_comp_SKU-element").style.display = "none";
                        document.getElementById("cyan_comp_price-element").style.display = "none";
                    	document.getElementById("cyan_comp_yield-element").style.display = "inline";
                    	
                        document.getElementById("magenta_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="magenta_comp_SKU">Magenta Yield:</label>';
                        document.getElementById("magenta_comp_SKU-label").style.display = "block";
                        document.getElementById("magenta_comp_SKU-element").style.display = "none";
                        document.getElementById("magenta_comp_price-element").style.display = "none";
                    	document.getElementById("magenta_comp_yield-element").style.display = "inline";
                    	
                        document.getElementById("yellow_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="yellow_comp_SKU">Yellow Yield:</label>';
                        document.getElementById("yellow_comp_SKU-label").style.display = "block";
                        document.getElementById("yellow_comp_SKU-element").style.display = "none";
                        document.getElementById("yellow_comp_price-element").style.display = "none";
                    	document.getElementById("yellow_comp_yield-element").style.display = "inline";
                    	
					} else {
                		display = "inline";
                        document.getElementById("black_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="black_toner_SKU">* Black SKU / Price / Yield:</label>';
                        document.getElementById("black_toner_SKU-label").style.display = "block";
                        document.getElementById("black_toner_SKU-element").style.display = "inline";
                        document.getElementById("black_toner_price-element").style.display = "inline";
                    	document.getElementById("black_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("cyan_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="cyan_toner_SKU">* Cyan SKU / Price / Yield:</label>';
                        document.getElementById("cyan_toner_SKU-label").style.display = "block";
                        document.getElementById("cyan_toner_SKU-element").style.display = "inline";
                        document.getElementById("cyan_toner_price-element").style.display = "inline";
                    	document.getElementById("cyan_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("magenta_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="magenta_toner_SKU">* Magenta SKU / Price / Yield:</label>';
                        document.getElementById("magenta_toner_SKU-label").style.display = "block";
                        document.getElementById("magenta_toner_SKU-element").style.display = "inline";
                        document.getElementById("magenta_toner_price-element").style.display = "inline";
                    	document.getElementById("magenta_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("yellow_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="yellow_toner_SKU">* Yellow SKU / Price / Yield:</label>';
                        document.getElementById("yellow_toner_SKU-label").style.display = "block";
                        document.getElementById("yellow_toner_SKU-element").style.display = "inline";
                        document.getElementById("yellow_toner_price-element").style.display = "inline";
                    	document.getElementById("yellow_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("black_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="black_comp_SKU">Black SKU / Price / Yield:</label>';
                        document.getElementById("black_comp_SKU-label").style.display = "block";
                        document.getElementById("black_comp_SKU-element").style.display = "inline";
                        document.getElementById("black_comp_price-element").style.display = "inline";
                    	document.getElementById("black_comp_yield-element").style.display = "inline";
                    	
                        document.getElementById("cyan_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="cyan_comp_SKU">Cyan SKU / Price / Yield:</label>';
                        document.getElementById("cyan_comp_SKU-label").style.display = "block";
                        document.getElementById("cyan_comp_SKU-element").style.display = "inline";
                        document.getElementById("cyan_comp_price-element").style.display = "inline";
                    	document.getElementById("cyan_comp_yield-element").style.display = "inline";
                    	
                        document.getElementById("magenta_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="magenta_comp_SKU">Magenta SKU / Price / Yield:</label>';
                        document.getElementById("magenta_comp_SKU-label").style.display = "block";
                        document.getElementById("magenta_comp_SKU-element").style.display = "inline";
                        document.getElementById("magenta_comp_price-element").style.display = "inline";
                    	document.getElementById("magenta_comp_yield-element").style.display = "inline";
                    	
                        document.getElementById("yellow_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="yellow_comp_SKU">Yellow SKU / Price / Yield:</label>';
                        document.getElementById("yellow_comp_SKU-label").style.display = "block";
                        document.getElementById("yellow_comp_SKU-element").style.display = "inline";
                        document.getElementById("yellow_comp_price-element").style.display = "inline";
                    	document.getElementById("yellow_comp_yield-element").style.display = "inline";
                    	
					}
					break;
				case "4 Color - Combined":
					config = new Array("black", "cyan", "magenta", "yellow", "3color");
					if($("#is_leased").is(":checked")) {
						display = "none";
                        document.getElementById("4color_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="4color_toner_SKU">* 4 Color Yield:</label>';
                        document.getElementById("4color_toner_SKU-label").style.display = "block";
                        document.getElementById("4color_toner_SKU-element").style.display = "none";
                        document.getElementById("4color_toner_price-element").style.display = "none";
                    	document.getElementById("4color_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("4color_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="4color_comp_SKU">4 Color Yield:</label>';
                        document.getElementById("4color_comp_SKU-label").style.display = "block";
                        document.getElementById("4color_comp_SKU-element").style.display = "none";
                        document.getElementById("4color_comp_price-element").style.display = "none";
                    	document.getElementById("4color_comp_yield-element").style.display = "inline";
                    	
					} else {
                		display = "inline";
                        document.getElementById("4color_toner_SKU-label").innerHTML = '<label class="forms_label optional" for="4color_toner_SKU">* 4 Color SKU / Price / Yield:</label>';
                        document.getElementById("4color_toner_SKU-label").style.display = "block";
                        document.getElementById("4color_toner_SKU-element").style.display = "inline";
                        document.getElementById("4color_toner_price-element").style.display = "inline";
                    	document.getElementById("4color_toner_yield-element").style.display = "inline";
                    	
                        document.getElementById("4color_comp_SKU-label").innerHTML = '<label class="forms_label optional" for="4color_comp_SKU">4 Color SKU / Price / Yield:</label>';
                        document.getElementById("4color_comp_SKU-label").style.display = "block";
                        document.getElementById("4color_comp_SKU-element").style.display = "inline";
                        document.getElementById("4color_comp_price-element").style.display = "inline";
                    	document.getElementById("4color_comp_yield-element").style.display = "inline";
					}
					break;
			}
			hide_color_configs(config);
		});
		
		$("#is_leased").change(function() {
            $("#toner_config").change();
		});

		function hide_color_configs(config) {
			for(var i=0; i < config.length; i++) {
				//OEM Fields
				document.getElementById(config[i] + "_toner_SKU-label").style.display = "none";
				document.getElementById(config[i] + "_toner_SKU-element").style.display = "none";
				document.getElementById(config[i] + "_toner_price-element").style.display = "none";
				document.getElementById(config[i] + "_toner_yield-element").style.display = "none";
				
				//COMP Fields
				document.getElementById(config[i] + "_comp_SKU-label").style.display = "none";
				document.getElementById(config[i] + "_comp_SKU-element").style.display = "none";
				document.getElementById(config[i] + "_comp_price-element").style.display = "none";
				document.getElementById(config[i] + "_comp_yield-element").style.display = "none";
			}
		}
		
		//set defaults
		$("#is_leased").change();
		toggle_request();
		
		<?php if($this->field != '') { ?>
			var field = '<?php echo $this->field; ?>';
			var is_comp = field.indexOf('_comp');
			
			if(is_comp > 0) {
				$("#"+field+"_yield-element").html($("#"+field+"_yield-element").html() + '<ul id="'+field+'_errors" class="errors"><li><?php echo $this->message; ?></li></ul>');
			} else {
				$("#"+field+"_toner_yield-element").html($("#"+field+"_toner_yield-element").html() + '<ul id="'+field+'_errors" class="errors"><li><?php echo $this->message; ?></li></ul>');
			}
		<?php } ?>
		
	});
	
	function toggle_history() {
		if($("#ticket_comment_history").is(":visible")) {
			$("#ticket_comment_history").hide();
			$("#view_marker").html('[+]');
		} else {
			$("#ticket_comment_history").show();
			$("#view_marker").html('[-]');
		}
	}
	
	
	function toggle_request(mode) {
		if(mode == true) {
			//lock scrollbars
			$("#lightbox, #lightbox-panel").fadeIn(300);
			$("html, body").animate({scrollTop:0}, 'slow');
			$("body").css("overflow", "hidden");
			
		} else {
			$("#lightbox, #lightbox-panel").fadeOut(300);
			$("body").css("overflow", "auto");
		}
	}
	
<?php $this->headScript()->captureEnd() ?>

<h2><?php echo $this->title;?></h2>
<br/>
<p><strong>* indicates a required field</strong><p>
<div id="form_container">
	
	<div id="mapped_container" class="margined warning">
		<?php if($this->mapped) echo $this->escape($this->mapped); ?>
	</div>
	
	<div id="message_container" class="margined">
		<?php if($this->field) {
		    echo "Save failed. Please review the errors below."; 
		} else if($this->message) {
		    echo $this->message;
		} ?>
	</div>

	<div id="device_container" class="margined">
		<?php echo $this->deviceform; ?>
	</div>
	
    <div id="lightbox-panel" class="support_request_container">
        <form name="requests" id="requests" action="" method="post">
        	<input type="hidden" name="hdnGrid" id="hdnGrid" value="<?php echo $this->grid; ?>" />
        	<input type="hidden" name="ticket_id" id="ticket_id" value="<?php echo $this->ticket_number; ?>" />
        	<input type="hidden" name="devices_pf_id" id="devices_pf_id" value="<?php echo $this->devices_pf_id; ?>" />
        	<input type="hidden" name="upload_data_collector_id" id="upload_data_collector_id" value="<?php echo $this->upload_data_collector_id; ?>" />
        	
        	<dl class="zend_form">
        		<dt class="botMenu">
        		
        			<div id="message_container" class="margined">
        			    <?php echo $this->message; ?>
        			</div>
        			
        			<div id="instruction_container" class="margined">
        			</div>
        			
        			<?php if($this->ticket_number > 0) { ?>
                    	<div id="edit_request">
                    		<h2>Review Support Request</h2>
                    	
                			<div id="details_container" class="margined">
                				<div class="ticket_header">Ticket #<?php echo $this->ticket_number; ?></div>
                				<div id="ticket_container">
                					<div class="ticket_title"><?php echo $this->ticket_title; ?></div>
                					<hr />
                					<div class="ticket_item"><div class="ticket_label">Reported By:</div> <?php echo $this->reported_by; ?></div>
                					<div class="ticket_item"><div class="ticket_label">Type:</div> <?php echo $this->ticket_type; ?></div>
                					<div class="ticket_item"><div class="ticket_label">Device PF ID:</div> <?php echo $this->devices_pf_id; ?></div>
                					<div class="ticket_item"><div class="ticket_label">Device PF Name:</div> <?php echo $this->device_pf_name; ?></div>
                					<div class="ticket_item"><div class="ticket_label">User Suggested Name:</div> <?php echo $this->user_suggested_name; ?></div>
                					
                					<div class="ticket_item">
                						<div class="ticket_label">Status:</div>
                						<div class="ticket_links">
                							<?php echo $this->ticket_status ?>
                							<input type="hidden" name="cboStatus" id="cboStatus" value="<?php echo $this->ticket_status_id ?>" />
                						</div>
                					</div>
                					
                					<div class="ticket_description_label">Description</div>
                					<hr />
                					<div class="ticket_description">
                					<?php if(isset($this->edit_description) && $this->edit_description == true) { ?>
                					    <textarea name="request_description" id="request_description" style="width: 682px;" rows="4"><?php echo $this->ticket_details; ?></textarea>
                					<?php } else { ?>
                						<?php echo $this->ticket_details; ?>
                					<?php } ?>
                					</div>
                				</div>
                			</div>
                			
                			<?php if(count($this->ticket_comments) > 0) { ?>
                			<div id="comments_history_container">
                				<div class="ticket_comments_label" onclick="javascript: toggle_history();"><span id="view_marker">[+]</span> View History</div>
                				<div id="ticket_comment_history" class="ticket_comment_history">
                				<?php foreach($this->ticket_comments as $key => $value) { ?>
                					<div id="comment_user" class="ticket_comment_user"><?php echo $value['username']; ?></div>
                					<div id="comment_date" class="ticket_comment_date"><?php echo $value['comment_date']; ?></div>
                					<div id="comment_text" class="ticket_comment_text"><?php echo $value['comment_text']; ?></div>
                				<?php } ?>
                				</div>
                			</div>
                			<hr />
                			<?php } ?>
                			
                			<div id="comments_container" style="clear: both;">
                				<div class="ticket_comments_label">Add a Comment</div>
                				<div class=""><textarea name="txtComment" id="txtComment" style="width: 690px;" rows="6"></textarea></div>
                			</div>
        			
                			<div class="submitBar" style="margin: 20px 0px 0px 0px;">			
                				<div id="submitBtns">
            						<input type="submit" name="btnSubmitRequest" id="btnSubmitRequest" value="Submit" />
            						<input type="button" value="Done" onclick="javascript: toggle_request(false);" />
                				</div>
                		    </div>
                			
                		</div>
                		
                	<?php } else { ?>
                    	
                    	<div id="add_request">
                    		<h2>Submit Support Request</h2>
                    		
        					<div class="ticket_comments_label" style="clear: both; margin: 10px 0px 0px 0px;">
        						Title:
        						<input type="text" name="request_title" id="request_title" size="50" value="Model Request: ID# <?php echo $this->printer_model_id; ?>" />
        					</div>
                    		
                			<div id="comments_container" style="clear: both; margin: 20px 0px 0px 0px;">
            					<div class="ticket_comments_label">Description:</div>
            					<div class=""><textarea name="request_description" id="request_description" style="width: 690px;" rows="6"></textarea></div>
            				</div>
        			
                			<div class="submitBar" style="margin: 20px 0px 0px 0px;">			
                				<div id="submitBtns">					
                					<div class="backbtn">
                						<input type="submit" name="btnSubmitRequest" id="btnSubmitRequest" value="Submit" />
                						<input type="button" value="Cancel" onclick="javascript: toggle_request(false);" />
                					</div>
                				</div>
                		    </div>
                		    
                    	</div>
                    	
            		<?php } ?>
        		    
        		</dt>
        	</dl>
            
        </form>
    </div>
    
</div>



