<?php
/**
 * Default view: index.phtml
 */
?>

<?php $this->headScript()->captureStart('append','text/javascript')?>
	var has_data = '<?php echo $this->has_data; ?>';
	
	$(document).ready(function() {
		//find center screen for modal popup
		var sTop = ($(window).height()/2)-100;
		var sLeft = ($(window).width()/2)-200;
		
		jQuery("#results_list").jqGrid({
			url:'<?php echo $this->baseUrl(); ?>/data/previewlist?filter=0',
			datatype:'json',
			colNames:[
				'upload_data_collector_id','devices_pf_id','printermodelid','manufacturer','modelname','serialnumber','ipaddress',
				'is_color','is_copier','is_scanner','is_fax','ppm_black','ppm_color','date_introduction','date_adoption','discovery_date','black_prodcodeoem',
				'black_yield','black_prodcostoem','cyan_prodcodeoem','cyan_yield','cyan_prodcostoem','magenta_prodcodeoem','magenta_yield','magenta_prodcostoem',
				'yellow_prodcodeoem','yellow_yield','yellow_prodcostoem','duty_cycle','wattspowernormal','wattspoweridle','startmeterlife','endmeterlife',
				'startmeterblack','endmeterblack','startmetercolor','endmetercolor','startmeterprintblack','endmeterprintblack','startmeterprintcolor',
				'endmeterprintcolor','startmetercopyblack','endmetercopyblack','startmetercopycolor','endmetercopycolor','startmeterscan','endmeterscan',
				'startmeterfax','endmeterfax','tonerlevel_black','tonerlevel_cyan','tonerlevel_magenta','tonerlevel_yellow','startdate','enddate'
			],
			colModel:[
				{width:100, name:'upload_data_collector_id', index:'upload_data_collector_id', hidden:true},
				{width:100, name:'devices_pf_id', index:'devices_pf_id', hidden:true},
				{width:100, name:'startdate', index:'startdate', edittype:'text'},
				{width:100, name:'enddate', index:'enddate', edittype:'text'},
				{width:100, name:'printermodelid', index:'printermodelid', edittype:'text'},
				{width:100, name:'manufacturer', index:'manufacturer'},
				{width:100, name:'modelname', index:'modelname'},
				{width:100, name:'serialnumber', index:'serialnumber'},
				{width:100, name:'ipaddress', index:'ipaddress'},
				{width:100, name:'is_color', index:'is_color'},
				{width:100, name:'is_copier', index:'is_copier'},
				{width:100, name:'is_scanner', index:'is_scanner'},
				{width:100, name:'is_fax', index:'is_fax'},
				{width:100, name:'ppm_black', index:'ppm_black'},
				{width:100, name:'ppm_color', index:'ppm_color'},
				{width:100, name:'date_introduction', index:'date_introduction'},
				{width:100, name:'date_adoption', index:'date_adoption'},
				{width:100, name:'discovery_date', index:'discovery_date'},
				{width:100, name:'black_prodcodeoem', index:'black_prodcodeoem'},
				{width:100, name:'black_yield', index:'black_yield'},
				{width:100, name:'black_prodcostoem', index:'black_prodcostoem'},
				{width:100, name:'cyan_prodcodeoem', index:'cyan_prodcodeoem'},
				{width:100, name:'cyan_yield', index:'cyan_yield'},
				{width:100, name:'cyan_prodcostoem', index:'cyan_prodcostoem'},
				{width:100, name:'magenta_prodcodeoem', index:'magenta_prodcodeoem'},
				{width:100, name:'magenta_yield', index:'magenta_yield'},
				{width:100, name:'magenta_prodcostoem', index:'magenta_prodcostoem'},
				{width:100, name:'yellow_prodcodeoem', index:'yellow_prodcodeoem'},
				{width:100, name:'yellow_yield', index:'yellow_yield'},
				{width:100, name:'yellow_prodcostoem', index:'yellow_prodcostoem'},
				{width:100, name:'duty_cycle', index:'duty_cycle'},
				{width:100, name:'wattspowernormal', index:'wattspowernormal'},
				{width:100, name:'wattspoweridle', index:'wattspoweridle'},
				{width:100, name:'startmeterlife', index:'startmeterlife'},
				{width:100, name:'endmeterlife', index:'endmeterlife'},
				{width:100, name:'startmeterblack', index:'startmeterblack'},
				{width:100, name:'endmeterblack', index:'endmeterblack'},
				{width:100, name:'startmetercolor', index:'startmetercolor'},
				{width:100, name:'endmetercolor', index:'endmetercolor'},
				{width:100, name:'startmeterprintblack', index:'startmeterprintblack'},
				{width:100, name:'endmeterprintblack', index:'endmeterprintblack'},
				{width:100, name:'startmeterprintcolor', index:'startmeterprintcolor'},
				{width:100, name:'endmeterprintcolor', index:'endmeterprintcolor'},
				{width:100, name:'startmetercopyblack', index:'startmetercopyblack'},
				{width:100, name:'endmetercopyblack', index:'endmetercopyblack'},
				{width:100, name:'startmetercopycolor', index:'startmetercopycolor'},
				{width:100, name:'endmetercopycolor', index:'endmetercopycolor'},
				{width:100, name:'startmeterscan', index:'startmeterscan'},
				{width:100, name:'endmeterscan', index:'endmeterscan'},
				{width:100, name:'startmeterfax', index:'startmeterfax'},
				{width:100, name:'endmeterfax', index:'endmeterfax'},
				{width:100, name:'tonerlevel_black', index:'tonerlevel_black'},
				{width:100, name:'tonerlevel_cyan', index:'tonerlevel_cyan'},
				{width:100, name:'tonerlevel_magenta', index:'tonerlevel_magenta'},
				{width:100, name:'tonerlevel_yellow', index:'tonerlevel_yellow'}
			],
			shrinkToFit:false,
			width:615,
			height:'auto',
			rowNum:10,
			rowList:[10,25,50,100],
			pager:'#results_pager'
		});
		
		jQuery("#results_list").jqGrid('navGrid','#results_pager',
				{add:false,del:false,edit:false,refresh:false,search:false},
				{closeAfterEdit:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{closeAfterAdd:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{},
				{},
				{}
		);
		
		jQuery("#excluded_results_list").jqGrid({
			url:'<?php echo $this->baseUrl(); ?>/data/previewlist?filter=1',
			datatype:'json',
			colNames:[
				'upload_data_collector_id','devices_pf_id','printermodelid','manufacturer','modelname','serialnumber','ipaddress',
				'is_color','is_copier','is_scanner','is_fax','ppm_black','ppm_color','date_introduction','date_adoption','discovery_date','black_prodcodeoem',
				'black_yield','black_prodcostoem','cyan_prodcodeoem','cyan_yield','cyan_prodcostoem','magenta_prodcodeoem','magenta_yield','magenta_prodcostoem',
				'yellow_prodcodeoem','yellow_yield','yellow_prodcostoem','duty_cycle','wattspowernormal','wattspoweridle','startmeterlife','endmeterlife',
				'startmeterblack','endmeterblack','startmetercolor','endmetercolor','startmeterprintblack','endmeterprintblack','startmeterprintcolor',
				'endmeterprintcolor','startmetercopyblack','endmetercopyblack','startmetercopycolor','endmetercopycolor','startmeterscan','endmeterscan',
				'startmeterfax','endmeterfax','tonerlevel_black','tonerlevel_cyan','tonerlevel_magenta','tonerlevel_yellow','startdate','enddate'
			],
			colModel:[
				{width:100, name:'upload_data_collector_id', index:'upload_data_collector_id', hidden:true},
				{width:100, name:'devices_pf_id', index:'devices_pf_id', hidden:true},
				{width:100, name:'printermodelid', index:'printermodelid', edittype:'text'},
				{width:100, name:'manufacturer', index:'manufacturer'},
				{width:100, name:'modelname', index:'modelname'},
				{width:100, name:'serialnumber', index:'serialnumber'},
				{width:100, name:'ipaddress', index:'ipaddress'},
				{width:100, name:'is_color', index:'is_color'},
				{width:100, name:'is_copier', index:'is_copier'},
				{width:100, name:'is_scanner', index:'is_scanner'},
				{width:100, name:'is_fax', index:'is_fax'},
				{width:100, name:'ppm_black', index:'ppm_black'},
				{width:100, name:'ppm_color', index:'ppm_color'},
				{width:100, name:'date_introduction', index:'date_introduction'},
				{width:100, name:'date_adoption', index:'date_adoption'},
				{width:100, name:'discovery_date', index:'discovery_date'},
				{width:100, name:'black_prodcodeoem', index:'black_prodcodeoem'},
				{width:100, name:'black_yield', index:'black_yield'},
				{width:100, name:'black_prodcostoem', index:'black_prodcostoem'},
				{width:100, name:'cyan_prodcodeoem', index:'cyan_prodcodeoem'},
				{width:100, name:'cyan_yield', index:'cyan_yield'},
				{width:100, name:'cyan_prodcostoem', index:'cyan_prodcostoem'},
				{width:100, name:'magenta_prodcodeoem', index:'magenta_prodcodeoem'},
				{width:100, name:'magenta_yield', index:'magenta_yield'},
				{width:100, name:'magenta_prodcostoem', index:'magenta_prodcostoem'},
				{width:100, name:'yellow_prodcodeoem', index:'yellow_prodcodeoem'},
				{width:100, name:'yellow_yield', index:'yellow_yield'},
				{width:100, name:'yellow_prodcostoem', index:'yellow_prodcostoem'},
				{width:100, name:'duty_cycle', index:'duty_cycle'},
				{width:100, name:'wattspowernormal', index:'wattspowernormal'},
				{width:100, name:'wattspoweridle', index:'wattspoweridle'},
				{width:100, name:'startmeterlife', index:'startmeterlife'},
				{width:100, name:'endmeterlife', index:'endmeterlife'},
				{width:100, name:'startmeterblack', index:'startmeterblack'},
				{width:100, name:'endmeterblack', index:'endmeterblack'},
				{width:100, name:'startmetercolor', index:'startmetercolor'},
				{width:100, name:'endmetercolor', index:'endmetercolor'},
				{width:100, name:'startmeterprintblack', index:'startmeterprintblack'},
				{width:100, name:'endmeterprintblack', index:'endmeterprintblack'},
				{width:100, name:'startmeterprintcolor', index:'startmeterprintcolor'},
				{width:100, name:'endmeterprintcolor', index:'endmeterprintcolor'},
				{width:100, name:'startmetercopyblack', index:'startmetercopyblack'},
				{width:100, name:'endmetercopyblack', index:'endmetercopyblack'},
				{width:100, name:'startmetercopycolor', index:'startmetercopycolor'},
				{width:100, name:'endmetercopycolor', index:'endmetercopycolor'},
				{width:100, name:'startmeterscan', index:'startmeterscan'},
				{width:100, name:'endmeterscan', index:'endmeterscan'},
				{width:100, name:'startmeterfax', index:'startmeterfax'},
				{width:100, name:'endmeterfax', index:'endmeterfax'},
				{width:100, name:'tonerlevel_black', index:'tonerlevel_black'},
				{width:100, name:'tonerlevel_cyan', index:'tonerlevel_cyan'},
				{width:100, name:'tonerlevel_magenta', index:'tonerlevel_magenta'},
				{width:100, name:'tonerlevel_yellow', index:'tonerlevel_yellow'},
				{width:100, name:'startdate', index:'startdate', edittype:'text'},
				{width:100, name:'enddate', index:'enddate', edittype:'text'}
			],
			shrinkToFit:false,
			width:615,
			height:'auto',
			rowNum:10,
			rowList:[10,25,50,100],
			pager:'#excluded_results_pager'
		});
		
		jQuery("#excluded_results_list").jqGrid('navGrid','#excluded_results_pager',
				{add:false,del:false,edit:false,refresh:false,search:false},
				{closeAfterEdit:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{closeAfterAdd:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{},
				{},
				{}
		);

    });

    function doAction(inAction) {
        if (inAction == 'confirm') {
            //change form action to confirmUpload and submit
            document.getElementById('fileinput').action = '<?php echo $this->baseUrl(); ?>/data/confirmation';
            document.getElementById('fileinput').submit();
            
        } else if(inAction == 'upload') {
        	if($('#uploadedfile').val() == '') {
        		$('#message_container').html('
<p>Please select a file to upload.</p>
');
        		
        	} else {
        		if(has_data == 'true') {
        			if(confirm('This report already contains previously uploaded data. If you continue, all existing data will be deleted. Do you wish to continue?')) {
						$('#fileinput').submit();
        			}
        		} else {
					$('#fileinput').submit();
        		}
            }
        
        } else if(inAction == 'continue') {
            document.location.href = "<?php echo $this->baseUrl(); ?>/data/devicemapping";
            
        } else if(inAction == 'back') {
            document.location.href = "<?php echo $this->baseUrl(); ?>/survey/verify";
        }
    }
    
<?php $this->headScript()->captureEnd()?>

<form id="fileinput" class="fileinput" enctype="multipart/form-data"
	action="<?php echo $this->baseUrl(); ?>/data" method="POST">
	<dl class="zend_form">
		<dt class="botMenu">

			<div id="message_container" class="margined">
	        <?php
        if (isset($this->errMessages))
        {
            //show the first error in the list of errors
            foreach ( $this->errMessages as $key => $value )
            {
                echo $value;
                break;
            }
        }
        else
        {
            if (isset($this->message))
            {
                echo $this->message;
            }
        }
        ?>
		    </div>

			<div id="upload_container">
				<div>
					Choose a <span style="color: red">.CSV</span> file to upload: <input
						name="uploadedfile" id="uploadedfile"
						accept="application/csv, text/csv" type="file" size="60"
						class="upload_file" />
				</div>
				<div>
					<input type="button" name="csv_submit" id="csv_submit"
						value="Upload File" onclick="javascript: doAction('upload');" />
				</div>
			</div>

			<div class="results_container">
		    <?php if($this->has_data > 0) { ?>
				<h3>Imported Results:</h3>
				<br />
				<table id="results_list"></table>
				<div id="results_pager"></div>
				<br />
			<?php } ?>
			
			<?php if($this->bad_data > 0) { ?>
				<h3>Excluded Results:</h3>
				<p>Records below have been excluded because they are missing data in
					required fields.</p>
				<table id="excluded_results_list"></table>
				<div id="excluded_results_pager"></div>
				<br />
	        <?php } ?>
	       	</div>

			<div class="submitBar">
				<div id="submitBtns">
					<div class="savebtn">
						<?php if($this->has_data > 0) { ?>
                			<input type="button" class="" name="btnNext"
							id="btnNext" value="Continue"
							onClick="javascript: doAction('confirm');" />
                		<?php } else { ?>
                			<input type="button" class="" name="btnNext"
							id="btnNext" value="Continue" disabled="disabled" />
            			<?php } ?>
					</div>
					<div class="backbtn">
						<input type="button" class="" name="btnBack" id="btnBack"
							value="Back" onClick="javascript: doAction('back');" />
					</div>
				</div>
			</div>

		</dt>
	</dl>
</form>
