<?php
/**
 * modificationwarning.phtml
 *
 * @author : John Sadler
 * @version : v1.0
 *         
 */
?>

<?php $this->headScript()->captureStart('append','text/javascript')?>
	
	$(document).ready(function() {
		$("#btnOk").attr("disabled", "disabled");
		
		$("#chkUnderstand").click(function() {
			if ($("#chkUnderstand").is(":checked")) {
				$("#btnOk").removeAttr("disabled");
			} else {
				$("#btnOk").attr("disabled", "disabled");
			}
		});
	});
	
<?php $this->headScript()->captureEnd()?>

<h3 style="display: inline;"><?php echo $this->title;?></h3>

<form name="frmWarning" id="frmWarning" action="" method="post">
	<div>&nbsp;</div>

	<div class="message_container margined warning">
	    <?php echo $this->message; ?>
	</div>

	<div class="margined">The master record for one or more of the printers
		assigned to your report have been removed by the system administrator.
		Before regenerating this report, please verify that all printers have
		been mapped correctly.</div>

	<div style="text-align: center; margin: 20px 0px 20px 0px;">
		<input type="checkbox" name="chkUnderstand" id="chkUnderstand"
			value="1" /> <label for="chkUnderstand">I understand this warning.</label>
	</div>

	<div style="text-align: center;">
		<input type="submit" name="btnOk" id="btnOk" value="Continue" />
	</div>

</form>
