<?php
/**
 * reportsettings.phtml
 *
 * @author	John Sadler
 * @version	v1.0
 */
?>
<table style="width: 100%;border-collapse: collapse; table-layout: fixed">
	<tr>
		<td class = "Title"><u><?php echo $this->formTitle?></u></td>
		<?php if ($this->companyName) :?>
		<td class = "PreparedFor"><i>Prepared For:</i></td>
		<td class = "PreparedForText"><i><?php echo $this->companyName; ?></i></td>
		<?php endif?>
	</tr>
</table>

<dl class="zend_form">
	<dt class="botMenu">
		<div id="form_container" class="margined">
		    <?php echo $this->FlashMessenger(); ?>
			<?php echo $this->settingsForm; ?>
		</div>
	</dt>
</dl>