<?php
/**
 * savemapping.phtml
 */
?>

<?php $this->headScript()->captureStart('append','text/javascript')?>

    function doAction(inAction) {
        if(inAction == 'cancel') {
			document.location.href = "<?php echo $this->baseUrl(); ?>/data/devicemapping";
        }
    }
    
<?php $this->headScript()->captureEnd()?>

<form id="mapping" name="mapping" action="" method="post">
	<dl class="zend_form">
		<dt class="botMenu">
			<div class="message_container margined">
			    <?php echo $this->message; ?>
			</div>
		</dt>
	</dl>
</form>

