<?php

$filename = 'FleetAttributes.xlsx';
$savePath = PUBLIC_PATH . "/downloads/client/{$this->clientId}/orderlist/{$this->quoteId}/";

if (!is_dir($savePath))
{
    if (!mkdir($savePath, 0777, true))
    {
        throw new Exception("Could not open cache folder! PATH:" . $savePath, 0);
    }
}

$savePath   = $savePath . $filename;
$linkToFile = $this->baseUrl("/downloads/client/{$this->clientId}/orderlist/{$this->quoteId}/{$filename}");

// Create a new PHPExcel Object * New PHPExcel objects will have one attached worksheet by default
/* @var $objPHPExcel PHPExcel */
$objPHPExcel = $this->phpexcel;

// Objects in memory are held in php memory as serialized objects, reduces memory footprint with little performance hit
PHPExcel_CachedObjectStorageFactory::cache_in_memory_serialized;

/**
 * Start of the summary Page
 */

$sheetCounter = 0;
$activeSheet  = $objPHPExcel->getActiveSheet();
$objPHPExcel->setActiveSheetIndex(0);
$activeSheet->setTitle("Fleet Attributes");
// Start building the document
if (isset($this->fleetAttributesData[0]))
{
    $fieldTitleCounter = 0;
    foreach ($this->fleetAttributesData[0] as $fieldTitle => $value)
    {
        $activeSheet->setCellValueExplicitByColumnAndRow($fieldTitleCounter, 1, $fieldTitle);
        $activeSheet->getColumnDimensionByColumn($fieldTitleCounter)->setAutoSize(true);
        $fieldTitleCounter++;
    }
}

foreach ($this->fleetAttributesData as $deviceData)
{
    $currentRow = $activeSheet->getHighestRow() + 1;

    $activeSheet->setCellValueByColumnAndRow(0, $currentRow, $deviceData['Device Name']);
    $activeSheet->setCellValueByColumnAndRow(1, $currentRow, $deviceData['IP Address']);
    $activeSheet->setCellValueByColumnAndRow(2, $currentRow, $deviceData['Serial Number']);
    $activeSheet->setCellValueByColumnAndRow(3, $currentRow, $deviceData['Device Age (Years)']);
    $activeSheet->setCellValueByColumnAndRow(4, $currentRow, $deviceData['Monthly Page Volume']);
    $activeSheet->setCellValueByColumnAndRow(5, $currentRow, $deviceData['Suggested Maximum Page Volume']);
    $activeSheet->setCellValueByColumnAndRow(6, $currentRow, $deviceData['Percent of Total Page Volume']);
    $activeSheet->setCellValueByColumnAndRow(7, $currentRow, $deviceData['Reports Toner Levels']);
    $activeSheet->setCellValueByColumnAndRow(8, $currentRow, $deviceData['Compatible with ' . My_Brand::$jit]);
    $activeSheet->setCellValueByColumnAndRow(9, $currentRow, $deviceData['Is Managed']);
    $activeSheet->setCellValueByColumnAndRow(10, $currentRow, $deviceData['Can Copy/Scan']);
    $activeSheet->setCellValueByColumnAndRow(11, $currentRow, $deviceData['Can Duplex']);
    $activeSheet->setCellValueByColumnAndRow(12, $currentRow, $deviceData['Can Fax']);
    $activeSheet->setCellValueByColumnAndRow(13, $currentRow, $deviceData['Can Print A3']);
    $activeSheet->setCellValueByColumnAndRow(14, $currentRow, $deviceData['Print Speed Mono']);
    $activeSheet->setCellValueByColumnAndRow(15, $currentRow, $deviceData['Print Speed Color']);
    $activeSheet->setCellValueByColumnAndRow(16, $currentRow, $deviceData['Operating Wattage']);
    $activeSheet->setCellValueByColumnAndRow(17, $currentRow, $deviceData['Idle/Sleep Wattage']);
    $activeSheet->setCellValueByColumnAndRow(18, $currentRow, PHPExcel_Shared_Date::stringToExcel($deviceData['Launch Date']));

    $activeSheet->getStyleByColumnAndRow(3, $currentRow)->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyleByColumnAndRow(4, $currentRow)->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyleByColumnAndRow(5, $currentRow)->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyleByColumnAndRow(6, $currentRow)->getNumberFormat()->applyFromArray(array('code' => PHPExcel_Style_NumberFormat::FORMAT_PERCENTAGE_00));
    $activeSheet->getStyleByColumnAndRow(14, $currentRow)->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyleByColumnAndRow(15, $currentRow)->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyleByColumnAndRow(16, $currentRow)->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyleByColumnAndRow(17, $currentRow)->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyleByColumnAndRow(18, $currentRow)->getNumberFormat()->setFormatCode('mm/dd/yyyy');


}

// Save Excel 2007 file
$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
$objWriter->save($savePath);

//Clear the workbook from php's memory
$objPHPExcel->disconnectWorksheets();

echo $this->baseUrl($linkToFile);