<?php

$savePath = PUBLIC_PATH . "/downloads/client/{$this->clientId}/orderlist/{$this->quoteId}/";

if (!is_dir($savePath))
{
    if (!mkdir($savePath, 0777, true))
    {
        throw new Exception("Could not open cache folder! PATH:" . $savePath, 0);
    }
}

// Create a new PHPExcel Object * New PHPExcel objects will have one attached worksheet by default
/* @var $objPHPExcel PHPExcel */
$objPHPExcel = $this->phpexcel;

// Objects in memory are held in php memory as serialized objects, reduces memory footprint with little performance hit
PHPExcel_CachedObjectStorageFactory::cache_in_memory_serialized;

/**
 * Start of the summary Page
 */

$sheetCounter = 0;
$activeSheet  = $objPHPExcel->getActiveSheet();
$objPHPExcel->setActiveSheetIndex(0);
$activeSheet->setTitle("Fleet Attributes");
$cellStyle = $activeSheet->getStyleByColumnAndRow($fieldTitleCounter, 1)->getFont()->setBold(true);

/**
 * Titles
 */
$activeSheet->setCellValue('A1', 'Device Name');
$activeSheet->setCellValue('B1', 'IP Address');
$activeSheet->setCellValue('C1', 'Serial Number');
$activeSheet->setCellValue('D1', 'Device Age (Years)');
$activeSheet->setCellValue('E1', 'Monthly Page Volume');
$activeSheet->setCellValue('F1', 'Suggested Maximum Page Volume');
$activeSheet->setCellValue('G1', 'Percent of Total Page Volume');
$activeSheet->setCellValue('H1', 'Reports Toner Levels');
$activeSheet->setCellValue('I1', 'Compatible with ' . My_Brand::$jit);
$activeSheet->setCellValue('J1', 'Is Managed');
$activeSheet->setCellValue('K1', 'Can Copy/Scan');
$activeSheet->setCellValue('L1', 'Can Duplex');
$activeSheet->setCellValue('M1', 'Can Fax');
$activeSheet->setCellValue('N1', 'Can Print A3');
$activeSheet->setCellValue('O1', 'Print Speed Mono');
$activeSheet->setCellValue('P1', 'Print Speed Color');
$activeSheet->setCellValue('Q1', 'Operating Wattage');
$activeSheet->setCellValue('R1', 'Idle/Sleep Wattage');
$activeSheet->setCellValue('S1', 'Launch Date');

$activeSheet->getStyle('A1')->getFont()->setBold(true);
$activeSheet->getStyle('B1')->getFont()->setBold(true);
$activeSheet->getStyle('C1')->getFont()->setBold(true);
$activeSheet->getStyle('D1')->getFont()->setBold(true);
$activeSheet->getStyle('E1')->getFont()->setBold(true);
$activeSheet->getStyle('F1')->getFont()->setBold(true);
$activeSheet->getStyle('G1')->getFont()->setBold(true);
$activeSheet->getStyle('H1')->getFont()->setBold(true);
$activeSheet->getStyle('I1')->getFont()->setBold(true);
$activeSheet->getStyle('J1')->getFont()->setBold(true);
$activeSheet->getStyle('K1')->getFont()->setBold(true);
$activeSheet->getStyle('L1')->getFont()->setBold(true);
$activeSheet->getStyle('M1')->getFont()->setBold(true);
$activeSheet->getStyle('N1')->getFont()->setBold(true);
$activeSheet->getStyle('O1')->getFont()->setBold(true);
$activeSheet->getStyle('P1')->getFont()->setBold(true);
$activeSheet->getStyle('Q1')->getFont()->setBold(true);
$activeSheet->getStyle('R1')->getFont()->setBold(true);
$activeSheet->getStyle('S1')->getFont()->setBold(true);

$activeSheet->getStyle('H1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$activeSheet->getStyle('I1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$activeSheet->getStyle('J1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$activeSheet->getStyle('K1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$activeSheet->getStyle('L1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$activeSheet->getStyle('M1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$activeSheet->getStyle('N1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);

$activeSheet->getColumnDimensionByColumn(0)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(1)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(2)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(3)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(4)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(5)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(6)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(7)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(8)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(9)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(10)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(11)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(12)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(13)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(14)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(15)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(16)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(17)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(18)->setAutoSize(true);

/**
 * Fleet Attributes List
 */
foreach ($this->fleetAttributesData as $deviceData)
{
    $currentRow = $activeSheet->getHighestRow() + 1;

    $activeSheet->setCellValue("A{$currentRow}", $deviceData['Device Name']);
    $activeSheet->setCellValue("B{$currentRow}", $deviceData['IP Address']);
    $activeSheet->setCellValue("C{$currentRow}", $deviceData['Serial Number']);
    $activeSheet->setCellValue("D{$currentRow}", $deviceData['Device Age (Years)']);
    $activeSheet->setCellValue("E{$currentRow}", $deviceData['Monthly Page Volume']);
    $activeSheet->setCellValue("F{$currentRow}", $deviceData['Suggested Maximum Page Volume']);
    $activeSheet->setCellValue("G{$currentRow}", $deviceData['Percent of Total Page Volume']);
    $activeSheet->setCellValue("H{$currentRow}", $deviceData['Reports Toner Levels']);
    $activeSheet->setCellValue("I{$currentRow}", $deviceData['Compatible with ' . My_Brand::$jit]);
    $activeSheet->setCellValue("J{$currentRow}", $deviceData['Is Managed']);
    $activeSheet->setCellValue("K{$currentRow}", $deviceData['Can Copy/Scan']);
    $activeSheet->setCellValue("L{$currentRow}", $deviceData['Can Duplex']);
    $activeSheet->setCellValue("M{$currentRow}", $deviceData['Can Fax']);
    $activeSheet->setCellValue("N{$currentRow}", $deviceData['Can Print A3']);
    $activeSheet->setCellValue("O{$currentRow}", $deviceData['Print Speed Mono']);
    $activeSheet->setCellValue("P{$currentRow}", $deviceData['Print Speed Color']);
    $activeSheet->setCellValue("Q{$currentRow}", $deviceData['Operating Wattage']);
    $activeSheet->setCellValue("R{$currentRow}", $deviceData['Idle/Sleep Wattage']);
    $activeSheet->setCellValue("S{$currentRow}", PHPExcel_Shared_Date::stringToExcel($deviceData['Launch Date']));

    $activeSheet->getStyle("A{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("B{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("C{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("D{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("E{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("F{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("G{$currentRow}")->getNumberFormat()->applyFromArray(['code' => PHPExcel_Style_NumberFormat::FORMAT_PERCENTAGE_00]);
    $activeSheet->getStyle("H{$currentRow}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $activeSheet->getStyle("I{$currentRow}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $activeSheet->getStyle("J{$currentRow}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $activeSheet->getStyle("K{$currentRow}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $activeSheet->getStyle("L{$currentRow}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $activeSheet->getStyle("M{$currentRow}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $activeSheet->getStyle("N{$currentRow}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $activeSheet->getStyle("O{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("P{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("Q{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("R{$currentRow}")->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyle("S{$currentRow}")->getNumberFormat()->setFormatCode('mm/dd/yyyy');

}

// Save Excel 2007 file
$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
$objWriter->save($this->savePath);

//Clear the workbook from php's memory
$objPHPExcel->disconnectWorksheets();

echo $this->baseUrl($this->publicFileName);