<?php
/**
 * managemyreports.phtml
 * 
 * @author	Mike Christie
 * @version	v1.0 
 */
?>
<?php $this->headScript()->captureStart('append','text/javascript') ?>

	$(document).ready(function() {
    
		//find center screen for modal popup
		var sTop = ($(window).height()/2)-100;
		var sLeft = ($(window).width()/2)-200;
		
		jQuery("#reports_list").jqGrid({
			url:'<?php echo $this->baseUrl(); ?>/admin/myreportslist',
			datatype:'json',
			colNames:['Report ID', 'User', 'Company Name', 'Date Created', 'Last Modified', 'Finished', 'View'],
			colModel:[
        		{width:60, name:'report_id', index:'report_id', align:'center'},
        		{width:80, name:'username', index:'username'},
        		{width:140, name:'company_name', index:'company_name'},
				{width:80, name:'date_created', index:'date_created', align:'center'},
				{width:80, name:'last_modified', index:'last_modified', align:'center'},
				{width:60, name:'is_finished', index:'is_finished', align:'center', edittype:'checkbox'},
				{width:40, name:'view_link', index:'view_link', align:'center'}
			],
			width:940,
			height:'auto',
			multiselect:true,
			pager:'#reports_pager',
			gridComplete:function(){
				//hide user column if not dealer
				if(document.getElementById("reports_fitler").length < 4) {
					jQuery("#reports_list").hideCol("username");
				}
				
				//build view link
				var ids = jQuery("#reports_list").jqGrid('getDataIDs');
				for(var i=0; i < ids.length; i++) { 
					var cur_row = ids[i];
					var is_finished = document.getElementById("reports_list").rows[i+1].cells[6].innerHTML;
					report_id = document.getElementById("reports_list").rows[i+1].cells[1].innerHTML;
					view_link = "<a href='javascript: view_report("+report_id+");'>View</a>"; 
					if(is_finished == "Yes") {
						jQuery("#reports_list").jqGrid('setRowData',ids[i],{view_link:view_link});
					}
				}
				
    			$('#reports_list').setGridWidth(940);
			}
		});
		
		jQuery("#reports_list").jqGrid('navGrid','#reports_pager',
				{add:false,del:false,edit:false,refresh:false,search:false},
				{closeAfterEdit:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{closeAfterAdd:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{},
				{},
				{}
		);

    });
	
	function update_grid() {
		$('#reports_list').setGridParam({url:'<?php echo $this->baseUrl(); ?>/admin/myreportslist?filter='+$("#reports_fitler").val()});
    	$('#reports_list').setGridWidth(940);
		$('#reports_list').trigger("reloadGrid");
	}
	
	function confirm_delete() {
		//check to make sure something is selected
		var isvalid = false;
		var ids = jQuery("#reports_list").jqGrid('getDataIDs');
		for(var i=0; i < ids.length; i++) {
			if ($("#jqg_reports_list_"+ids[i]).is(':checked')) {
				isvalid = true;
				break;
			}
		}
		
		if(isvalid) {
			if(confirm("Are you sure you want to delete the selected reports?")) {
				$("#form_mode").val('delete');
				$("#requests").submit();
			}
		} else {
			$("#message_container").html("You have not selected any reports. Please select a report to delete and try again.");
		}
	}
	
	function view_report(id) {
		$("#form_mode").val('view');
		$("#report_id").val(id);
		$("#requests").submit();
	}
    
<?php $this->headScript()->captureEnd() ?>
	
<h2 id="page_title"><?php echo $this->title;?></h2>

<?php echo $this->form ?>

<form name="requests" id="requests" action="<?php echo $this->baseUrl(); ?>/admin/managemyreports" method="POST">
	<input type="hidden" name="form_mode" id="form_mode" value="request" />
	<input type="hidden" name="request_id" id="request_id" value="" />
	<input type="hidden" name="devices_pf_id" id="devices_pf_id" value="" />
	<input type="hidden" name="report_id" id="report_id" value="" />	
			
	<div id="instruction_container">
		<p>Select the rows you wish to delete, and press the delete button to confirm.</p>
	</div>
	
	<div id="message_container" class="margined">
		<?php echo $this->message; ?>
	</div>
	
	<div id="filter_container" class="well">
		<label for="reports_fitler" class="forms_label" style="display: inline; margin: 0px 10px 0px 0px;">Filter Reports:</label>
		<select name="reports_fitler" id="reports_fitler" class="" style="margin: 0px 0px 0px 0px;" onchange="javascript: update_grid(this.value);">
		<?php
		foreach($this->filter as $key => $value) {
			echo "<option value='" . $key ."'";
			if ($key == $this->cur_fitler) {
				echo " selected";
			}
			echo ">" . ucwords(strtolower($value)) . "</option>";
		}
		?>
		</select>
		<div style="float: right; margin: 5px 10px 0px 0px;">
		    <a href="transferreports">Transfer Reports</a>
		</div>
	</div>
	
	<div id="request_container" class="margined">
		<table id="reports_list"></table>
		<div id="reports_pager"></div>
	</div>
	
	<div class="submitBar">
		<input type="button" name="btnDelete" id="btnDelete" value="Delete" onclick="javascript: confirm_delete();" class="btn btn-primary" />
		<input type="button" name="btnDone" id="btnDone" value="Done" onclick="javascript: document.location.href='<?php echo $this->baseUrl()."/admin"?>';" class="btn" />
	</div>		
</form>
