<?php $this->headScript()->captureStart('append','text/javascript') ?>
	var repop = <?php echo (empty($this->repop) == true ? "false" : $this->repop); ?>;
	var form_mode = '<?php echo $this->mode; ?>';
    var selectedPrinterModel = '<?php echo $this->printer_model; ?>';
    var man_id = '<?php echo $this->man_id; ?>';
    var mas_id = '<?php echo $this->mas_id; ?>';
<?php $this->headScript()->captureEnd() ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/proposalgen/admin/managereplacements.js')); ?>
<div class="page-header">
    <h1>Manage Replacement Printers</h1>
</div>

<form name="replacements" id="replacements" action="" method="post">
	<input type="hidden" name="hdnIds" id="hdnIds" />
	<input type="hidden" name="hdnManId" id="hdnManId" />
	<input type="hidden" name="hdnMasId" id="hdnMasId" />
	<input type="hidden" name="hdnOriginalCategory" id="hdnOriginalCategory" />

	<dl class="zend_form">
		<dt class="botMenu">
			<div id="instruction_container" class="margined">
				<p>
				</p>
				<p><strong>Note:</strong> there must be at least one replacement printer for each of the four replacement categories.</p>
			</div>

			<div id="message_container" class="margined">
			    <?php echo $this->message; ?>
			</div>

			<div id="grid_container" class="margined">
				<table id="grid_list"></table>
			</div>
            <br/>

			<div id="submitBtns" class="submitBar">
                <input type="button" name="btnDone" id="btnDone" value="Back" onClick="javascript: do_action('done');" class="btn btn-inverse" />
                <input type="button" name="btnAdd" id="btnAdd" value="Add New" onclick="javascript: do_action('add');" class="btn btn-primary" />
				<input type="button" name="btnDelete" id="btnDelete" value="Delete Selected" onclick="javascript: do_action('delete');" class="btn" />
			</div>

			<div id="lightbox-panel" class="replacement_printer_container">
				<h3 id="modal_title">Add New Replacement Device</h3>

				<div id="modal_instruction">
					<p class="instruction margined">All fields are required.</p>
				</div>

				<div id="modal_message_container" class="margined">
				    <?php echo $this->message; ?>
				</div>

				<div id="modal_form" class="well">
					<?php echo $this->replacement_form; ?>
				</div>

				<div id="submitBtns" class="submitBar">
					<input type="button" name="btnSave" id="btnSave" value="Save" onclick="javascript: do_action('save');" class="btn btn-primary" />
					<input type="button" name="btnDone" id="btnDone" value="Close" onClick="javascript: do_action('close');" class="btn" />
				</div>
			</div>

		</dt>
	</dl>

</form>
