<?php
/**
 * manageusers.phtml
 * 
 * @author	John Sadler
 * @version	v1.0 
 */
?>

<?php 
	//Capture the following jquery javascript code, and append it to the headscript variable in the main layout.	
	$this->headScript()->captureStart('append','text/javascript') 
	/*
	* This script is used to repopulate the contents of a form upon the user
    * changing the selected item in a drop box.  An ajax call is made to a retrieve
    * new json formatted user data from a dedicated data page (this page queries
    * the database).  
    *
    * @requires: jquery javascript library must be included in the html
    *            head section BEFORE this script is included.
    *
    * http://jquery.com/
    */
	?>
	$(document).ready(function() {
		//$( "#login_restricted_date" ).datepicker({ dateFormat: 'dd/mm/yy', changeMonth: true, changeYear: true});
			
			$("#privileges").change(function(event) {
				if($("#privileges option:selected").text() == "System Admin") {
					//set company to MASTER by default
					$("#select_company").append($('<option></option>').val('1').html('Master'));
					$("#select_company").val('1');
					$("#select_company").attr('disabled', 'disabled');
				} else {
					$("#select_company option[value='1']").remove();
					$("#select_company").removeAttr('disabled');
				}
			});
			
			$("#company_filter").change(function(event){
				var companyid = $("#company_filter").val();
				var url = '<?php echo $this->baseUrl(); ?>/admin/filtercompanies?companyid='+companyid;
				empty_form();
				
				$.ajax ({
					type: "POST",
					contentType: "application/json; charset=utf-8",
			        url: url,
					dataType: "json",
					success: function(data) {
					    //empty out printer_model
					    $("#select_user").html('');
					    
						var listItems= "<option value='0'>Add New User</option>";
						for (var i = 0; i < data.rows.length; i++){
							if(data.rows[i].cell[0] > 0) {
								listItems+= "<option value='" + data.rows[i].cell[0] + "'>" + data.rows[i].cell[1] + "</option>";
							}
						}
						$("#select_user").html(listItems);
					},
					error: function() {
						alert("ERROR IN FILTERCOMPANIES");
					},
					complete: function() {
					}
				});
			});
			
            // Handle updating form content on the edit user page (admin/edituser)
            $("#select_user").change(function(event){
				
				//clear any form validation
				clear_validation();
				
				//uncheck update_password
				document.getElementById("update_password").checked = false;

                var userid = $("#select_user").val();
                //var resultEle = $("#results");
                $.ajax({
                    beforeSend: function() {
                        // disable form elements while loading new info
                        $("#select_company").attr('disabled', 'disabled');
                        $("#username").attr('disabled', 'disabled');
                        $("#userFirstName").attr('disabled', 'disabled');
                        $("#userLastName").attr('disabled', 'disabled');
                        $("#userPhone").attr('disabled', 'disabled');
                        $("#userEmail").attr('disabled', 'disabled');
                        $("#privileges").attr('disabled', 'disabled');
                        $("#password").attr('disabled', 'disabled');
                        $("#passwordConfirm").attr('disabled', 'disabled');
                        $("#is_activated").attr('disabled', 'disabled');
                    },
                    url: '<?php echo $this->baseUrl(); ?>/admin/userdata?userid='+userid,
                    success: function(data) {
                        //resultEle.html(data);
                        var obj = jQuery.parseJSON(data);
                        $("#select_company").val(obj.dealer_company_id);
                        $("#username").val(obj.username);
                        $("#userFirstName").val(obj.firstname);
                        $("#userLastName").val(obj.lastname);
                        $("#userPhone").val(obj.phone);
                        $("#userEmail").val(obj.email);
                        $("#privileges").val(obj.priv_id);
                        $("#password").val(null);
                        $("#passwordConfirm").val(null);
                        $("#is_activated").attr('checked', obj.is_activated);
                        //alert("User Found!" + userid);
                        
                        if(obj.username == '') {
							set_defaults(true);
                        } else {
							set_defaults(false);
			    			$('#message_container').html('');
							$("#delete_user").removeAttr('disabled');
                        }
                    },
                    error: function() {
                        //Display an error if the selected user can not
                        //be found.

                        //$('.display-error').text("Error:  User not found");
                        //$('.display-error').show();
                    },
                    complete: function() {
                        //enable form elements after they are filled
                        $("#privileges").change();
                        
                        $("#username").removeAttr('disabled');
                        $("#userFirstName").removeAttr('disabled');
                        $("#userLastName").removeAttr('disabled');
                        $("#userPhone").removeAttr('disabled');
                        $("#userEmail").removeAttr('disabled');
                        
                        if($("#select_user").val() == '<?php echo strtolower($this->user_id) ?>') {
                        	$("#select_company").attr('disabled','disabled');
                        	$("#privileges").attr('disabled','disabled');
                        	$("#delete_user").attr('disabled','disabled');
                        } else {
							<?php if(in_array("System Admin", $this->privilege)) { ?>
                        		$("#select_company").removeAttr('disabled');
                        	<?php } ?>
                        	$("#privileges").removeAttr('disabled');
                        	$("#delete_user").removeAttr('disabled');
                        }
                        
                        $("#password").removeAttr('disabled');
                        $("#passwordConfirm").removeAttr('disabled');
                        $("#is_activated").removeAttr('disabled');
                    }
                });
            });
            			
            $("#update_password").click(function(event){
            	var toggle;
            	if(this.checked) {
					document.getElementById("auto_password-label").style.display = "inline-block";
					document.getElementById("auto_password-element").style.display = "inline-block";
					document.getElementById("password-label").style.display = "none";
					document.getElementById("password-element").style.display = "none";
					document.getElementById("passwordConfirm-label").style.display = "none";
					document.getElementById("passwordConfirm-element").style.display = "none";
            	} else  {
					document.getElementById("auto_password-label").style.display = "none";
					document.getElementById("auto_password-element").style.display = "none";
					document.getElementById("password-label").style.display = "none";
					document.getElementById("password-element").style.display = "none";
					document.getElementById("passwordConfirm-label").style.display = "none";
					document.getElementById("passwordConfirm-element").style.display = "none";
            	}
            	//always default to true?
				document.getElementById("password_mode").value = "true";
				document.getElementById("must_change").checked = this.checked;
			});
            	
			set_defaults(true);
			
        }); // end $(document).ready()
		
		function clear_validation() {
			$('ul li').remove();
		}
				
		function set_defaults(mode) {
			//hide the filter
			<?php if(in_array("Dealer Admin", $this->privilege)) { ?>
				document.getElementById("filter_container").style.display = "none";
			<?php } ?>
		
			document.getElementById("select_company-label").style.display = "none";
			document.getElementById("select_company-element").style.display = "none";
			
			//hide everything by default
			$("#update_password-label").css("display", "none");
			$("#update_password-element").css("display", "none");
			$("#password-label").css("display", "none");
			$("#password-element").css("display", "none");
			$("#passwordConfirm-label").css("display", "none");
			$("#passwordConfirm-element").css("display", "none");
			$("#auto_password-label").css("display", "none");
			$("#auto_password-element").css("display", "none");
			$("#is_activated").attr('checked','checked');
			$("#delete_user").attr('disabled','disabled');
			
			if($("#select_user").val() == 0) {
				//always show auto_password by default in add mode
				$("#auto_password-label").css("display", "inline-block");
				$("#auto_password-element").css("display", "inline-block");
				
				if($("#password_mode").val() == "true") {
					//do nothing
				} else {
					//hide auto_password
					$("#auto_password-label").css("display", "none");
					$("#auto_password-element").css("display", "none");
					
					//show password & confirmation
					$("#password-label").css("display", "inline-block");
					$("#password-element").css("display", "inline-block");
					$("#passwordConfirm-label").css("display", "inline-block");
					$("#passwordConfirm-element").css("display", "inline-block");
				}
			} else {
				//always show activated when in edit mode
				$("#update_password-label").css("display", "inline-block");
				$("#update_password-element").css("display", "inline-block");
				$("#is_activated-label").css("display", "inline-block");
				$("#is_activated-element").css("display", "inline-block");
				$("#must_change").attr('checked', false);
				
				if($("#update_password").is(':checked') == true) {					
					if($("#password_mode").val() == "true") {
						//auto password
						$("#auto_password-label").css("display", "inline-block");
						$("#auto_password-element").css("display", "inline-block");			
					} else {
						//custom password
						$("#password-label").css("display", "inline-block");
						$("#password-element").css("display", "inline-block");
						$("#passwordConfirm-label").css("display", "inline-block");
						$("#passwordConfirm-element").css("display", "inline-block");
					}
				}
			}
		}
		
		function toggle_password(mode) {
			if(mode == true) {
				//hide auto generate
				$("#auto_password-label").css("display", "none");
				$("#auto_password-element").css("display", "none");
				//show password & confirm password
				$("#password-label").css("display", "inline-block");
				$("#password-element").css("display", "inline-block");
				$("#passwordConfirm-label").css("display", "inline-block");
				$("#passwordConfirm-element").css("display", "inline-block");
				$("#password").focus();
			} else {
				//hide password & confirm password
				$("#password-label").css("display", "none");
				$("#password-element").css("display", "none");
				$("#passwordConfirm-label").css("display", "none");
				$("#passwordConfirm-element").css("display", "none");
				//show auto generate
				$("#auto_password-label").css("display", "inline-block");
				$("#auto_password-element").css("display", "inline-block");
			}
			
			//toggle change on login checkbox
			document.getElementById("must_change").checked = !mode;
			document.getElementById("password_mode").value = !mode;
		}
		
		function enable_fields() {
			$("#select_company").removeAttr("disabled"); 
			$("#privileges").removeAttr("disabled");
		}
		
		function empty_form() {
			$("#select_user").val('0');
			$("#privileges").val('');
			$("#privileges").removeAttr('disabled');
			$("#select_company").val('');
			$("#select_company").removeAttr('disabled');
			$("#username").val('');
			$("#userFirstName").val('');
			$("#userLastName").val('');
			$("#userPhone").val('');
			$("#userEmail").val('');
			$("#update_password").removeAttr('checked');
			$("#must_change").removeAttr('checked');
			$("#is_activated").attr('checked','checked');
		}
			
<?php $this->headScript()->captureEnd() ?>

<h2 id="page_title"><?php echo $this->title;?></h2>

<div id="message_container" class="margined">
	<?php echo $this->escape($this->message); ?>
</div>

<div id="filter_container" class="well">
	<label for="company_filter" class="details_label">Filter Users: </label>
	<select name="company_filter" id="company_filter" class="">
	<option value="">Show All Users</option>
	<option value="1">System Administrators</option>
	<?php
	foreach($this->companyList as $key => $value) {
		echo "<option value='" . $key ."'>" . ucwords(strtolower($value)) . "</option>";
	}
	?>
	</select>
</div>
<br/>
<div class="well">
<?php echo $this->form; ?>
</div>
