<?php
/**
 * managecompanies.phtml
 * 
 * @author	John Sadler
 * @version	v1.0 
 */
?>

<?php $this->headScript()->captureStart('append','text/javascript') ?>
var repop = <?php echo (empty($this->repop) == true ? "false" : $this->repop); ?>;

$(document).ready(function() {

	$("#select_company").change(function(event){
		// empty and hide the error message box
		$('.errors').empty();
		$('.errors').hide()
		
		var companyid = $("#select_company").val();
		$.ajax({
			beforeSend: function() {
				// disable form elements while loading new info
				$("#company_name").attr('disabled', 'disabled');
				$("#pricing_margin").attr('disabled', 'disabled');
			},
			url: '<?php echo $this->baseUrl(); ?>/admin/companydetails?companyid='+companyid,
			success: function(data) {
				var obj = jQuery.parseJSON(data);
				$("#company_name").val(obj.company_name);
				$("#pricing_margin").val(obj.pricing_margin);
				
				if($("#select_company").val() > 0) {
					$("#delete_company").removeAttr('disabled');
				} else {
					$("#pricing_margin").val(25);
					$("#delete_company").attr('disabled','disabled');
				}
			},
			error: function() {
				//Display an error if the selected user can not
				//be found.
				
				//$('.errors').text("Error:  User not found");
				//$('.errors').show();
			},
			complete: function() {
				//enable form elements after they are filled
				$("#company_name").removeAttr('disabled');
				$("#pricing_margin").removeAttr('disabled');
			}
		});
		
	});
	
	if(repop != true) {
		$("#select_company").change();
	} else {
		repop = false;
	}
	
});

<?php $this->headScript()->captureEnd() ?>

<h2><?php echo $this->title;?></h2>

<div id="message_container" class="margined">
	<?php if($this->message) echo $this->message; ?>
</div>

<div id="manufacturer_container" class="margined">
	<?php echo $this->companyForm; ?>
</div>