<?php
/**
 * managemyusers.phtml
 *
 * @author John Sadler
 * @version v1.0
 */
?>

		

<?php $this->headScript()->captureStart('append','text/javascript')?>
<?php $this->headScript()->captureEnd()?>

<h2><?php echo $this->title;?></h2>

<form name="requests" id="requests" action="" method="POST">
	<dl class="zend_form">
		<dt class="botMenu">
			<div class="message_container margined">
			    <?php echo $this->message; ?>
			    <?php echo $this->form; ?>
			</div>
		</dt>
	</dl>
</form>