<div class="container">
    <?php if (isset($this->result)) : ?>
        <div class="alert alert-success">
            Your encrypted password is <strong><?= $this->result; ?></strong>
        </div>
    <?php endif; ?>

    <form class="form-horizontal" method="POST">
        <fieldset>
            <legend>Encrypt your password</legend>
            <div class="form-group">
                <label class="control-label col-md-4" for="password">Password: </label>

                <div class="col-md-8">
                    <input type="text" class="form-control" id="password" name="password">

                    <p class="help-block">Enter your password and submit</p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-8 col-md-offset-4">
                    <ul class="pager">
                        <li class="previous">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button class="btn btn-default">Cancel</button>
                        </li>
                    </ul>
                </div>
            </div>
        </fieldset>
    </form>

    <form class="form-horizontal" method="POST">
        <fieldset>
            <legend>Encrypt your password</legend>
            <div class="form-group">
                <label class="control-label col-md-4" for="password">Password: </label>

                <div class="col-md-8">
                    <input type="text" class="form-control" id="password" name="password">

                    <p class="help-block">Enter your password and submit</p>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4" for="hash">Hash: </label>

                <div class="col-md-8">
                    <input type="text" class="form-control" id="hash" name="hash">

                    <p class="help-block">Enter the hash of your previous password to verify</p>
                </div>
            </div>
            <div class="col-md-8 col-md-offset-4">
                <ul class="pager">
                    <li class="previous">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button class="btn btn-default">Cancel</button>
                    </li>
                </ul>
            </div>
        </fieldset>
    </form>
</div>