<?php

use MPSToolbox\Legacy\Modules\DDefault\Forms\ResetPasswordForm;

/* @var $resetPasswordForm ResetPasswordForm */
$resetPasswordForm = $this->form;
?>
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-10 col-lg-8 col-center-block">
            <div class="login-panel panel <?= ($resetPasswordForm->hasErrors() ? 'panel-danger' : 'panel-primary') ?>">

                <div class="panel-heading">
                    <img src="<?= $this->baseUrl('/img/branding/logo/auth_brand.png') ?>" alt="MPSToolbox Logo" />
                </div>

                <div class="panel-body">
                    <?= $this->flashMessenger("info", '<div class="alert alert-%s">%s</div>'); ?>
                    <p class="lead">Please reset your password.</p>
                    <hr>
                    <?= $resetPasswordForm; ?>
                </div>
            </div>
        </div>
    </div>
</div>