<?php

use MPSToolbox\Legacy\Modules\DDefault\Forms\LoginForm;

/* @var $loginForm LoginForm */
$loginForm = $this->form;
?>
<div class="container">
    <div class="row">
        <div class="col-sm-8 col-md-6 col-lg-5 col-center-block">
            <div class="login-panel panel <?= ($loginForm->hasErrors() ? 'panel-danger' : 'panel-primary') ?>">

                <div class="panel-heading text-center">
                    <img src="<?= $this->baseUrl('/img/branding/logo/auth_brand.png') ?>" alt="MPSToolbox Logo" />
                </div>

                <div class="panel-body">
                    <?= $this->flashMessenger("info", '<div class="alert alert-%s">%s</div>'); ?>
                    <?= $loginForm; ?>
                </div>

                <div class="panel-footer">
                    <a href="<?= $this->url([], 'auth.forgot-password') ?>" class="btn-link">Forgot Password?</a>
                </div>

            </div>
        </div>
    </div>
</div>