<?php 
$id = $this->id;
?>

<?php if ( $this->deviceToners ) { ?>

<table class="table table-striped table-condensed table-bordered">
	<thead>
		<tr>
			<th>SKU</th>
			<th>Manufacturer</th>
			<th>Type</th>
			<th>Color</th>
			<th>Yield</th>
			<th>Cost</th>
			<th style="width: 120px; text-align: center;">Action</th>
		</tr>
	</thead>
	<tbody>
	    <?php foreach ($this->deviceToners as $toner) : /* @var $toner Admin_Model_Toner */ ?>
	    <tr>
			<td><?php echo $toner->getSku(); ?></td>
			<td><?php echo $toner->getManufacturer()->getDisplayname(); ?></td>
			<td><?php echo $toner->getPartType()->getTypeName(); ?></td>
			<td style="text-transform: capitalize;"><?php echo strToLower($toner->getTonerColor()->getTonerColorName()); ?></td>
			<td style="text-align: right;"><?php echo number_format($toner->getYield(), 0, '', ','); ?></td>
			<td style="text-align: right;"><?php echo "$" . number_format($toner->getCost(), 2, '.', ','); ?></td>
			<td>
				<div class="" style="text-align: center;">
					<a class="btn btn-warning btn-mini" title="Edit" href="<?php echo $this->url( array ( 'module' => 'admin', 'controller' => 'toner', 'action' => 'edit', 'id' => $id, 'tonerid' => $toner->getId())); ?>"><i class="icon-pencil icon-white"></i></a>
					<a class="btn btn-danger btn-mini" title="Delete" href="<?php echo $this->url(array ( 'module' => 'admin', 'controller' => 'toner', 'action' => 'unassign', 'id' => $id, 'tonerid' => $toner->getId())); ?>"><i class="icon-trash icon-white"></i></a>
				</div>
			</td>
		</tr>
        <?php endforeach; ?>
	</tbody>
</table>

<?php } ?>

<div class="pull-right">
	<a class="btn btn-success" title="Assign Toners" href="<?php echo $this->url( array ( 'action' => 'assigntoners', 'id' => $id ) ); ?>"><i class="icon-plus icon-white"></i> Assign Toners</a>
</div>
