<?php $this->headLink()->appendStylesheet($this->baseUrl("css/reports/reports.css"));
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
?>
<div class="container full-width" id="htmlReportContainer">
    <h2 class="reportTitle">Utilization</h2>

    <p>
        This report is only available in the excel format. Click the Excel button to download.
    </p>
</div>