<?php
/**
 * managemytickets.phtml
 * 
 * @author	John Sadler
 * @version	v1.0 
 */
?>

<?php $this->headScript()->captureStart('append','text/javascript') ?>

    $(document).ready(function() {
		//find center screen for modal popup
		var sTop = ($(window).height()/2)-100;
		var sLeft = ($(window).width()/2)-200;
		
		jQuery("#requests_list").jqGrid({
			url:'<?php echo $this->baseUrl(); ?>/ticket/myticketlist?status=-1',
			datatype:'json',			
			colNames:['Ticket ID','Title','Type','Reported By', 'Reported Date', 'Status'],
			colModel:[
        		{width:40, name:'ticket_id', index:'ticket_id', sorttype:'int'},
				{width:180, name:'ticket_title', index:'ticket_title'},
				{width:100, name:'ticket_type', index:'ticket_type'},
				{width:60, name:'reported_by', index:'reported_by'},
				{width:70, name:'date_created', index:'date_created'},
				{width:40, name:'ticket_status', index:'ticket_status'}
			],
			width: 625,
			height:'auto',
			multiselect:true,
			gridComplete:function(){
				var ids = jQuery("#requests_list").jqGrid('getDataIDs');
				for(var i=0; i < ids.length; i++) {
					var col1 = document.getElementById("requests_list").rows[i+1].cells[1].innerHTML;
					var col2 = document.getElementById("requests_list").rows[i+1].cells[2].innerHTML;
					
					var link1 = '<a href="ticketdetails?id='+col1+'">'+col1+'</a>';
					var link2 = '<a href="ticketdetails?id='+col1+'">'+col2+'</a>';
					
					jQuery("#requests_list").jqGrid('setRowData',ids[i],{ticket_id:link1});
					jQuery("#requests_list").jqGrid('setRowData',ids[i],{ticket_title:link2});
					
				}
			},
			editurl:'dummy.php'
		});
		
		jQuery("#requests_list").jqGrid('navGrid','#requests_pager',
				{add:false,del:false,edit:false,refresh:false,search:false},
				{closeAfterEdit:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{closeAfterAdd:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{},
				{},
				{}
		);
		
		$("#ticket_fitler").change(function() {
			var params = "?status="+this.value;
			
			$('#requests_list').setGridParam({url:'<?php echo $this->baseUrl(); ?>/ticket/myticketlist'+params});
			$('#requests_list').trigger("reloadGrid");
		});
		
	});
	
	function deletetickets() {
		//check to make sure something is selected
		var isvalid = false;
		var ids = jQuery("#requests_list").jqGrid('getDataIDs');
		for(var i=0; i < ids.length; i++) {
			if ($("#jqg_requests_list_"+ids[i]).is(':checked')) {
				isvalid = true;
				break;
			}
		}
		
		if(isvalid) {
			if(confirm("Are you sure you want to delete the selected tickets?")) {
				$("#form_mode").val('delete');
				$("#requests").submit();
			}
		} else {
			$("#message_container").html("You have not selected any tickets. Please select a ticket to delete and try again.");
		}
	}
	
	
<?php $this->headScript()->captureEnd() ?>

<h2><?php echo $this->title;?></h2>

<form name="requests" id="requests" action="<?php echo $this->baseUrl(); ?>/ticket/managemytickets" method="POST">
<input type="hidden" name="form_mode" id="form_mode" value="request" />
<input type="hidden" name="request_id" id="request_id" value="" />
<input type="hidden" name="devices_pf_id" id="devices_pf_id" value="" />
	<dl class="zend_form">
		<dt class="botMenu">
		
			<div id="message_container" class="margined">
			    <?php echo $this->message; ?>
			</div>
			
			<div id="instruction_container" class="margined">
				<p>Click on the ticket id or title to view it's details.</p>
			</div>
			
			<div id="filter_container">
				<label for="ticket_fitler" class="label">Filter: </label>
				<select name="ticket_fitler" id="ticket_fitler" class="">
					<option value="">Show All</option>
					<option value="-1" <?php if($this->defaultstatus == -1) { echo "selected"; } ?>>Active (New & Open)</option>
					<?php foreach($this->statuslist as $key => $value) { ?>
					<option value="<?php echo $key ?>" <?php if($this->defaultstatus == $key) { echo "selected"; } ?>><?php echo ucwords(strtolower($value)) ?></option>
					<?php } ?>
				</select>
			</div>
			
			<div id="request_container" class="margined">
				<table id="requests_list"></table>
				<div id="requests_pager"></div>
			</div>
			
			<br/>
			<div class="submitBar">			
				<div id="submitBtns">					
					<div class="backbtn">
						<input type="button" value="Delete" onclick="javascript: deletetickets();" />
						<input type="button" value="Done" onclick="javascript: document.location.href='<?php echo $this->baseUrl()."/admin"?>';" />
					</div>
				</div>
		    </div>
		</dt>
	</dl>
</form>
