<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;

// TODO: Save file to $this->savePath

$fh = fopen($this->savePath, "w+");


// Please note that is is a hacked way around things. This should be done more properly with PHPExcel or fputcsv.
// FIXME: This really defeats the purpose of a CSV
fputs($fh, "INCLUDED DEVICES:\n\n");
fputs($fh, $this->appendix_titles);
fputs($fh, "\n");
fputs($fh, $this->appendix_values);
fputs($fh, "\n\n\n");
fputs($fh, "EXCLUDED DEVICES:\n\n");
fputs($fh, $this->excluded_titles);
fputs($fh, "\n");
fputs($fh, $this->excluded_values);

fclose($fh);
echo $this->baseUrl($this->publicFileName);