<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><?php echo $this->title; ?></title>
        <link rel="stylesheet" href="<?php echo $this->theme("proposalgenerator/error.css") ?>" type="text/css" media="all" />
    </head>

    <body>
        <div class="errorPageContent">
            <p><a href=""><img border="0" src="<?php echo $this->theme("proposalgenerator/images/logo.png"); ?>" /></a></p>
            <p class='userErrorMessage'><?php echo $this->userFriendlyMessage; ?></p>
            <p><strong>Oops! We are sorry, it looks like something broke.</strong></p>
            <p>Please try again and if the problem continues please contact your system administrator.</p>
        </div>
    </body>

</html>