<?php
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/common_all.css"));
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/common_html.css"));
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/solution/solution_html.css"));
// Title page image
echo '<style type="text/css">
			div.titlepage {
				height: 500px;
				padding-left: 300px;
				padding-top: 350px;
				background-image: url(' . $this->serverUrl($this->theme("proposalgenerator/reports/images/solution.jpg")) . ');
				background-repeat: no-repeat;
			}
		 </style>';
$data = array(
    "proposal"       => $this->proposal,
    "isPDF"          => $this->isPDF,
    "backleft"       => $this->backleft,
    "backright"      => $this->backright,
    "backtop"        => $this->backtop,
    "backbottom"     => $this->backbottom,
    "footer"         => $this->footer,
    "pagestyle"      => $this->pagestyle,
    "titlePageStart" => $this->titlePageStart,
    "pageStart"      => $this->pageStart,
    "pageEnd"        => $this->pageEnd,
    "noBreakStart"   => $this->noBreakStart,
    "noBreakEnd"     => $this->noBreakEnd,
    "orientation"    => $this->orientation
);
?>
<div class="container" id="htmlReportContainer">
    <?php
    echo $this->partial('report/printingdevicelist/' . $this->App()->theme . '/html/01_Appendix.phtml', $data);
    echo $this->partial('report/printingdevicelist/' . $this->App()->theme . '/html/02_ExcludedDevices.phtml', $data);
    ?>
</div>