<?php
/* @var $phpWord PHPWord */
$phpWord = $this->phpword;
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;


/**
 * Document Properties
 */
$properties = $phpWord->getProperties();
$properties->setCreator('Demo Report');
$properties->setCompany('Demo Report');
$properties->setTitle('Demo Report');
$properties->setDescription('Demo Report');
$properties->setCategory('Demo Report');
$properties->setLastModifiedBy('Demo Report');
$properties->setCreated(time());
$properties->setModified(time());
$properties->setSubject('Demo Report');
$properties->setKeywords('demo, assessment, report');

$titlepageSection = $phpWord->createSection(array(
                                                 'orientation'  => null,
                                                 'marginLeft'   => 720,
                                                 'marginRight'  => 720,
                                                 'marginTop'    => 720,
                                                 'marginBottom' => 720
                                            ));
$section = $phpWord->createSection();

//array(
//    'marginLeft' => 100,
//    'marginRight' => 100,
//    'marginTop' => 100,
//    'marginBottom' => 100,
//
//)
/**
 * Footer
 */
// Footer in PHPWord is not working correctly
//$footer = $section->createFooter();
//$footer->addText("TEXT");
//$footer->addImage(PUBLIC_PATH . $this->theme('/proposalgenerator/reports/images/officedepotLogo.jpg'), array (    'align' => 'right'));


/**
 * Paragraph styles
 */
$phpWord->addParagraphStyle('titlepageHeaderParagraph', array(
                                                             'spaceAfter' => 200
                                                        ));

$phpWord->addParagraphStyle('nospacing', array(
                                              'spaceBefore' => 0,
                                              'spaceAfter'  => 0
                                         ));

$phpWord->addParagraphStyle('nospacing_rightalign', array(
                                                         'align'       => 'right',
                                                         'spaceBefore' => 0,
                                                         'spaceAfter'  => 0
                                                    ));

$phpWord->addParagraphStyle('nospacing_centeralign', array(
                                                          'align'       => 'center',
                                                          'spaceBefore' => 0,
                                                          'spaceAfter'  => 0
                                                     ));

$phpWord->addParagraphStyle('rightalign', array(
                                               'align' => 'right'
                                          ));

$phpWord->addParagraphStyle('gradeParagraph', array(
                                                   'align'       => 'center',
                                                   'spaceBefore' => 0,
                                                   'spaceAfter'  => 0
                                              ));

$phpWord->addParagraphStyle('savingsParagraph', array(
                                                     'align'       => 'center',
                                                     'spaceBefore' => 0,
                                                     'spaceAfter'  => 0
                                                ));

/**
 * Font Styles
 */
$phpWord->addFontStyle('titlepageHeaderFont', array(
                                                   'bold' => true,
                                                   'size' => 16
                                              ));

$phpWord->addFontStyle('bold_text', array(
                                         'bold' => true
                                    ));

$phpWord->addFontStyle('bold_red_text', array(
                                             'bold'  => true,
                                             'color' => 'F00001'
                                        ));

$phpWord->addFontStyle('gradeFont', array(
                                         'bold' => true,
                                         'size' => 18
                                    ));

$phpWord->addFontStyle('gradeTitleFont', array(
                                              'bold' => true,
                                              'size' => 12
                                         ));

$phpWord->addFontStyle('savingsFont', array(
                                           'bold' => true,
                                           'size' => 11
                                      ));

$phpWord->addFontStyle('savingsAmountFont', array(
                                                 'color' => 'F0003C',
                                                 'bold'  => true,
                                                 'size'  => 11
                                            ));

$phpWord->addFontStyle('small_italic_text', array(
                                                 'italic' => true,
                                                 'size'   => 9
                                            ));

/**
 * Header/Title Styles
 */
// H1 Style
$phpWord->addTitleStyle(1, array(
                                'size'  => 15,
                                'color' => 'F0003C',
                                'bold'  => true
                           ), array(
                                   'borderBottomSize' => 1
                              ));
// H2 Style #5881BC
$phpWord->addTitleStyle(2, array(
                                'size'   => 12,
                                'color'  => 'FFFFFF',
                                'bold'   => true,
                                'italic' => true
                           ), array(
                                   'bgColor' => 'F0003C'
                              ));
// H3 Style #5881BC
$phpWord->addTitleStyle(3, array(
                                'size'  => 10,
                                'color' => 'FF0000',
                                'bold'  => true
                           ), array(
                                   'spaceBefore' => 100,
                                   'spaceAfter'  => 100
                              ));

// H3 Style #5881BC
$phpWord->addFontStyle('heading3', array(
                                        'size'  => 10,
                                        'color' => 'FF0000',
                                        'bold'  => true
                                   ));

/**
 * Setup some styles to be used across the report
 */
$styles = (object)array(
    "tables" => (object)array(
        "grades"              => (object)array(
            "tablestyle" => array(
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ),
            "cell1"      => array(
                "bgColor"          => "F0F0F0",
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ),
            "cell2"      => array(
                "bgColor"          => "F0F0F0",
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            )
        ),
        "singleimage"         => (object)array(
            "tablestyle" => array(),
            "cell1"      => array(
                "valign" => "center"
            )
        ),
        "doubleimage"         => (object)array(
            "tablestyle" => array(),
            "cell1"      => array(
                "valign" => "center"
            ),
            "cell2"      => array(
                "valign" => "center"
            )
        ),
        "tripleimage"         => (object)array(
            "tablestyle" => array(),
            "cell1"      => array(
                "valign" => "center"
            ),
            "cell2"      => array(
                "valign" => "center"
            ),
            "cell3"      => array(
                "valign" => "center"
            )
        ),
        "savings"             => (object)array(
            "tablestyle" => array(
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ),
            "cell1"      => array(
                "bgColor"          => "F0F0F0",
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            )
        ),
        "utilization"         => (object)array(
            "tablestyle" => array(
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ),
            "rowheight"  => 400,
            "cell1"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell2"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell3"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell4"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            )
        ),
        "highriskdevices"     => (object)array(
            "tablestyle" => array(
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ),
            "rowheight"  => 400,
            "cell1"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell2"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell3"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell4"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell5"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell6"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            )
        ),
        "highenergy"          => (object)array(
            "tablestyle" => array(
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ),
            "rowheight"  => 400,
            "cell1"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell2"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell3"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell4"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            )
        ),
        "twoColumnDataTable"  => (object)array(
            "tablestyle" => array(
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ),
            "rowheight"  => null,
            "cell1"      => array(
                "valign" => "center"
            ),
            "cell2"      => array(
                "valign" => "center"
            )
        ),
        "expenseSummaryTable" => (object)array(
            "tablestyle"  => array(
                'cellMarginTop'    => 50,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 50,
                'cellMarginLeft'   => 100
            ),
            "rowheight"   => null,
            "col1Width"   => 7500,
            "col2Width"   => 1528,
            "cell1"       => array(
                "valign" => "center"
            ),
            "cell2"       => array(
                "valign" => "center"
            ),
            "cell1Border" => array(
                "valign"           => "center",
                'borderBottomSize' => 1
            ),
            "cell2Border" => array(
                "valign"           => "center",
                'borderBottomSize' => 1
            )
        ),
        "mostexpensive"       => (object)array(
            "tablestyle" => array(
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ),
            "rowheight"  => 400,
            "col1Width"  => 3611.2,
            "col2Width"  => 1805.6,
            "col3Width"  => 1805.6,
            "col4Width"  => 1805.6,
            "cell1"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell2"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell3"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ),
            "cell4"      => array(
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            )
        )
    ),
    "images" => (object)array(
        "center" => array(
            "align" => "center"
        )
    ),
);

/* Tables for the device layouts */
$widthTwips       = 15297;
$standard_cell = (object)array(
    "even"           => array(
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "odd"            => array(
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'right'
    )
);
$standard_cell_left = (object)array(
    "even"           => array(
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "odd"            => array(
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'left'
    )
);
$standard_cell_no_right_border = (object)array(
    "even"           => array(
        "bgColor" => $even_color,
    ),
    "odd"            => array(
        "bgColor" => $odd_color,
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'right'
    )
);
$standard_header = (object)array(
    "cellStyle"      => array(
        'bgColor' => $header_color
    ),
    "fontStyle"      => array(
        'bold' => true
    ),
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'center'
    )
);

$suggestDevices = (object)array(
    "tablestyle" => array(
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ),
    "col1Width"  => $widthTwips * 0.20,
    "col2Width"  => $widthTwips * 0.20,
    "col3Width"  => $widthTwips * 0.15,
    "col4Width"  => $widthTwips * 0.30,
    "col5Width"  => $widthTwips * 0.075,
    "col6Width"  => $widthTwips * 0.075,
    "body"       => (object)array(
        "rowheight" => null,
        "cell1"     => $standard_cell_left,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell,
        "cell4"     => $standard_cell,
        "cell5"     => $standard_cell,
        "cell6"     => $standard_cell_no_right_border,
    ),
    "header"     => (object)array(
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ),
);
$deviceTables = (object)array(
    ""

);
$titleData = array(
    "phpword"  => $phpWord,
    "section"  => $titlepageSection,
    "proposal" => $this->proposal,
    "styles"   => $styles
);

$data = array(
    "phpword"  => $phpWord,
    "section"  => $section,
    "proposal" => $this->proposal,
    "styles"   => $styles,
    "graphs"   => $this->graphs
);
// Actual document pages
$this->partial("report/optimization/customer/docx/01_titlepage.phtml", $titleData);
$this->partial("report/optimization/customer/docx/02_optimizationsummary.phtml", $data);
$this->partial("report/optimization/customer/docx/03_replacement.phtml", $data);
$this->partial("report/optimization/customer/docx/04_flagged.phtml", $data);
$this->partial("report/optimization/customer/docx/05_retire.phtml", $data);
$this->partial("report/optimization/customer/docx/06_acceptable.phtml", $data);



$this->partial("report/optimization/customer/docx/03_serviceandsupplies.phtml", $data);
$this->partial("report/optimization/customer/docx/05_technologyandproductivity.phtml", $data);
$objWriter = PHPWord_IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save($this->savePath);

echo $this->baseUrl($this->publicFileName);
