<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
/* @var $section PHPWord_Section */
$section = $this->section;
$section->addPageBreak();

// Flagged devices get rendered here

$section->addTitle($this->translate('Technology Features and Functionality'), 2);
$section->addText("If you printed every document on both sides of the page, you could use up to 50% less paper than you would by only printing on one side. You could further reduce your paper consumption
by using a scanner to e-mail documents instead of printing copies for distribution. The following charts show how many of your printing devices have duplexing and scanning capabilities:");
$section->addImage($this->graphs[12],$this->styles->images->center);