<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
$graphs = $proposal->getGraphs();
/* @var $section PHPWord_Section */
$section = $this->section;
$section->addTitle($this->translate('Analysis: Printing Hardware Usage'), 1);
$section->addTitle($this->translate('Print Volume and Number of Printing Devices'), 2);
$section->addText(sprintf($this->translate('You currently have %1$s networked printing devices that print an average of %2$s pages each per month, for an average total monthly print volume of %3$s pages. Ideally, you should have the minimum amount of printing hardware required to meet your print demand while maintaining user productivity.'), number_format($proposal->getDeviceCount()), number_format(($proposal->getPageCounts()->Total->Combined->Monthly / $proposal->getDeviceCount())), number_format($proposal->getPageCounts()->Total->Combined->Monthly)));
$section->addTextBreak();
$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($this->graphs [5]);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($this->graphs [6]);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($this->graphs [7]);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($this->graphs [8]);
$section->addTextBreak();




?>
