<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$graphs = $assessmentViewModel->getGraphs();
?>
<div class="h1">Your <?= My_Brand::getDealerBranding()->assessmentTitle ?></div>
<p>It can be a challenge to understand your printing needs, and there are many factors to consider: hardware functionality, supplies delivery, service, parts,
    maintenance kits,
    IT time spent supporting printers -- and the cost for all of this. This free <?= My_Brand::getDealerBranding()->assessmentTitle ?> will allow you to make sense
    of your printing needs and costs. <?= $this->companyName; ?>
    can help you get your office print under control with our smart and flexible managed print services solutions.</p>
<br />
<div class="pheader">Score Card</div>
<p style="margin: 10pt 0pt;">Your office printing environment was graded across five categories on a scale of 1 to 10. A score of 1 indicates a low-efficiency
    or high-cost scenario. A score of 10 indicates a high-efficiency or low-cost scenario. Your results are below:</p>
<table cellspacing="0" class="gradesTable">
    <tr>
        <td class="gradeDescription">
            <h4>Service and Supplies Logistics</h4>

            <p>Management breakdown, efficiency of break-fix service, number of vendors used for print, and number of different models and associated supply
                types.</p>
        </td>

        <td class="gradeNumber"><?= number_format($assessmentViewModel->getRanking()->getSuppliesAndServiceLogistics()->Rank, 1); ?></td>
    </tr>
    <tr>
        <td class="gradeDescription">
            <h4>Printing Hardware Usage</h4>

            <p>Total number of printing devices, average print volumes, underused and overused equipment, and color print usage.</p>
        </td>
        <td class="gradeNumber"><?= number_format($assessmentViewModel->getRanking()->getPrintingHardwareUsage()->Rank, 1); ?></td>
    </tr>
    <tr>
        <td class="gradeDescription">
            <h4>Technology Reliability and User Productivity</h4>

            <p>Age of printing devices, IT time spent managing printers, and availability of technology features that improve workflow and productivity.</p>
        </td>
        <td class="gradeNumber"><?= number_format($assessmentViewModel->getRanking()->getTechnologyReliabilityAndUserProductivity()->Rank, 1); ?></td>
    </tr>
    <tr>
        <td class="gradeDescription">
            <h4>Environmental Impact</h4>

            <p>Energy consumption from printing hardware and availability of green print technology features.</p>
        </td>
        <td class="gradeNumber"><?= number_format($assessmentViewModel->getRanking()->getEnvironmentalFriendliness()->Rank, 1); ?></td>
    </tr>
    <tr>
        <td class="gradeDescription">
            <h4>Expense</h4>

            <p>Your estimated annual expenses for print-related hardware, supplies, service, and internal support and administration.</p>
        </td>
        <td class="gradeNumber"><?= number_format($assessmentViewModel->getRanking()->getExpense()->Rank, 1); ?></td>
    </tr>
</table>
<br />
<div class="center">
    <img src="<?= $graphs[0]; ?>" /> <!-- Annual printing costs for purchased hardware -->
</div>
<br />
<br />
<div class="annualSavings">
    Our <?= $this->brandName; ?> program could provide you with annual savings of up to
    <strong><?= $this->currency($assessmentViewModel->getPrintIQSavings(), array('precision' => 0)); ?></strong>
</div>