<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$graphs = $assessmentViewModel->getGraphs();
?>
<div class="h1">Analysis: Environmental Impact</div>
<table cellspacing="0" class="gradesTable">
    <tr>
        <td class="gradeDescription">
            <p><?php echo $assessmentViewModel->getRanking()->getEnvironmentalFriendliness()->RankingText; ?></p>
        </td>
        <td class="gradeNumber"><?php echo number_format($assessmentViewModel->getRanking()->getEnvironmentalFriendliness()->Rank, 1); ?></td>
    </tr>
</table>
<br />
<div class="pheader">Energy Consumption</div>
<?php if ($assessmentViewModel->getPercentageOfDevicesReportingPower() > $assessmentViewModel->getDevicesReportingPowerThreshold())
{
    ?>
    <p>You are currently using an estimated average of
        <strong><?php echo number_format($assessmentViewModel->getAveragePowerUsagePerMonth()); ?> kWh</strong> per month to operate printing devices at an estimated monthly cost of
        <strong><?php echo $this->currency($assessmentViewModel->getAveragePowerCostPerMonth()); ?></strong>, assuming a cost of <?php echo $this->currency($assessmentViewModel->assessment->getAssessmentSettings()->kilowattsPerHour, 2); ?> per kWh.
    </p>
    <p>The following lists the devices with the highest average power consumption per month.</p>
    <table cellspacing="0" class="genericTable" style="font-size: 10pt;">
        <thead>
        <tr>
            <th style="width: 160px;">Model</th>
            <th style="width: 110px;" class="center">Serial No.</th>
            <th style="width: 170px;" class="center">Avg. kWh Consumption<br />Per Month Count</th>
            <th style="width: 145px;" class="center">Avg. Power<br />Cost per Month</th>
        </tr>
        </thead>
        <tbody>
        <?php $ctr = 0;
        foreach ($assessmentViewModel->getHighPowerConsumptionDevices() as $deviceInstance): ?>
            <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
            <tr>
                <td>
                    <div style="width: 160px; padding: 0;"><?php echo $deviceName; ?></div>
                </td>
                <td class="center"><?php if ($deviceInstance->serialNumber)
                    {
                        echo $deviceInstance->serialNumber;
                    }
                    else
                    {
                        echo 'Unknown';
                    } ?></td>
                <td class="center"><?php echo number_format($deviceInstance->getAverageMonthlyPowerConsumption()); ?> kWh</td>
                <td class="center"><?php echo $this->currency($deviceInstance->getAverageMonthlyPowerCost(), 2); ?></td>
            </tr>
            <?php $ctr++;
            if ($ctr > 2)
            {
                break;
            } endforeach; ?>
        </tbody>
    </table>
    <br />
<?php
}
else
{
    echo "<p>" . $assessmentViewModel->getNumberOfDevicesReportingPower() . " of your " . $assessmentViewModel->getDevices()->allIncludedDeviceInstances->getCount() . " printer(s) report power usage.  Not enough information is available to accurately calculate energy consumption for your fleet.</p>";
} ?>
<div class="pheader">Green Features: Duplexing and Scanning</div>
<p>If you printed every document on both sides of the page, you could use up to 50% less paper than you would by only printing on one side. You could further reduce your paper consumption by using a scanner to e-mail documents instead of printing copies for distribution. The following charts show how many of your printing devices have duplexing and scanning capabilities:</p>
<div class="center">
    <img src="<?php echo $graphs[13]; ?>" />
    <img src="<?php echo $graphs[14]; ?>" />
</div>