<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

$assessmentViewModel = $this->assessmentViewModel;

?>
<div class="h1">Analysis: Expense</div>
<table cellspacing="0" class="gradesTable">
    <tr>
        <td class="gradeDescription">
            <p><?= $assessmentViewModel->getRanking()->getExpense()->RankingText ?></p>
        </td>
        <td class="gradeNumber"><?= number_format($assessmentViewModel->getRanking()->getExpense()->Rank, 1); ?></td>
    </tr>
</table>
<br />
<p>Gartner Group called office printing the last great hidden expense in the office. They estimate the companies spend 1% to 3% of their revenue on office
    printing. Based on data collected from your printing devices and your questionnaire responses, we have estimated your annual printing expenses. We have
    separated your expenses into the cost of your leased printing devices and the cost of your purchased devices. Your leased devices are typically large
    multifunction devices and are assumed to be on an existing service contract. Your purchased devices are ones that can typically be transferred to
    our <?= $this->brandName; ?> program and be managed by <?= $this->companyName; ?>.</p>
<br />
<div class="pheader">Total Estimated Annual Printing Costs</div>
<p>Combining all costs, your current estimated annual printing expenses are as follows. Please note that our estimated costs may not match your actual
    purchases due to factors including inventory on hand, returns, timing of the assessment, etc. Our estimates, however, are a good representation of your
    average costs since they are based on actual observed usage.</p>
<br />
<table cellspacing="0" style="font-size: 10.5pt;">
    <tr>
        <td style="width: 565px;">Annual cost of hardware on leases</td>
        <td style="width: 80px;" class="right"><?= $this->currency($assessmentViewModel->getEstimatedAnnualCostOfLeaseMachines()); ?></td>
    </tr>
    <tr>
        <td class="bottomborder">Annual cost of hardware not on leases</td>
        <td class="right bottomborder"><?= $this->currency($assessmentViewModel->getTotalPurchasedAnnualCost()); ?></td>
    </tr>
    <tr>
        <td class="bold">TOTAL ESTIMATED ANNUAL PRINTING COSTS</td>
        <td class="right bold"><?= $this->currency($assessmentViewModel->calculateEstimatedAnnualCostOfPrinting()); ?></td>
    </tr>
</table>
<br />

<div class="pheader">Cost of Hardware Assumed to be Leased</div>
<p>To calculate your cost of leased printing devices, we assumed that you are paying a monthly lease rate in addition to a per-page cost, which includes
    supplies and service for each device.</p>
<br />
<table cellspacing="0" style="font-size: 10.5pt">
    <tr>
        <td style="width: 565px;">Number of printing devices assumed to be on a lease</td>
        <td style="width: 80px;" class="right"><?= count($assessmentViewModel->getDevices()->leasedDeviceInstances->getDeviceInstances()); ?></td>
    </tr>
    <tr>
        <td>Predicted average annual monochrome prints on leased machines</td>
        <td class="right"><?= $this->formatPageVolume($assessmentViewModel->getDevices()->leasedDeviceInstances->getPageCounts()->getBlackPageCount()->getYearly()); ?></td>
    </tr>
    <tr>
        <td></td>
        <td class="right"><?= $this->formatPageVolume($assessmentViewModel->getDevices()->leasedDeviceInstances->getPageCounts()->getColorPageCount()->getYearly()); ?></td>
    </tr>
    <tr>
        <td>Estimated annual total lease payments<br /><em>Based on
                <?= $this->currency($assessmentViewModel->assessment->getClient()->getClientSettings()->genericSettings->defaultMonthlyLeasePayment); ?> per month per device</em></td>

        <td class="right"><?= $this->currency($assessmentViewModel->getCombinedAnnualLeasePayments()); ?></td>
    </tr>
    <tr>
        <td class="bold topborder">Estimated per-page lease cost</td>
        <td class="right bold topborder"><?= $this->formatCostPerPage($assessmentViewModel->getPerPageLeaseCost()); ?></td>
    </tr>
    <tr>
        <td>Estimated monochrome per-page charge</td>
        <td class="right"><?= $this->formatCostPerPage($assessmentViewModel->getLeasedBlackAndWhiteCharge()); ?></td>
    </tr>
    <tr>
        <td>Estimated color per-page charge</td>
        <td class="right"><?= $this->formatCostPerPage($assessmentViewModel->getLeasedColorCharge()); ?></td>
    </tr>
    <tr>
        <td class="bold topborder">Estimated all-in cost for a monochrome page</td>
        <td class="right bold topborder"><?= $this->formatCostPerPage($assessmentViewModel->getLeasedEstimatedBlackAndWhiteCPP()); ?></td>
    </tr>
    <tr>
        <td class="bold">Estimated all-in cost for a color page</td>
        <td class="right bold"><?= $this->formatCostPerPage($assessmentViewModel->getLeasedEstimatedColorCPP()); ?></td>
    </tr>
    <tr>
        <td class="bold topborder">TOTAL ESTIMATED ANNUAL COST</td>
        <td class="right bold topborder"><?= $this->currency($assessmentViewModel->getEstimatedAnnualCostOfLeaseMachines()); ?></td>
    </tr>
</table>
<br />
<div class="pheader">Cost of Hardware Suitable for Transfer to a Managed Print Solution</div>
<p>Your
    <strong><?= count($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances()); ?></strong> print devices that are assumed to not be attached to leases may be
    suitable for transfer to a managed print program. Currently, you are paying for supplies and service separately for these devices and your internal IT staff
    spends time servicing them when they break down.</p>
<p>The costs below are based on data collected using remote monitoring software and your questionnaire responses. It also assumes a monochrome page coverage of
    <strong><?= number_format($assessmentViewModel->getPageCoverageBlackAndWhite()); ?>%</strong> and color coverage of
    <strong><?= number_format($assessmentViewModel->getPageCoverageColor()); ?>%</strong>.</p>
<table cellspacing="0" style="font-size: 10pt;">
    <tr>
        <td style="width: 565px;" class="bold">Supplies</td>
        <td style="width: 80px;" class="right">&nbsp;</td>
    </tr>
    <tr>
        <td>Annual cost of ink and toner<br /><em>Based on data collected by <?= $this->companyName; ?>.</em></td>
        <td class="right">
            <?= $this->currency($assessmentViewModel->getCostOfInkAndToner($assessmentViewModel->getCostPerPageSettingForCustomer())); ?></td>
    </tr>
    <tr>
        <td>Annual administration cost of executing supplies orders<br /><em>Based on your questionnaire responses.</em></td>
        <td class="right"><?= $this->currency($assessmentViewModel->getCostOfExecutingSuppliesOrders()); ?></td>
    </tr>
    <tr>
        <td class="bold topborder">Total estimated annual supplies-related expense</td>
        <td class="right bold topborder"><?= $this->currency($assessmentViewModel->getEstimatedAnnualSupplyRelatedExpense()); ?></td>
    </tr>
</table>
<table cellspacing="0" style="font-size: 10pt;">
    <tr>
        <td class="bold">Service</td>
        <td class="right">&nbsp;</td>
    </tr>
    <tr>
        <td style="width: 565px;">Annual cost of sourcing outside service organizations<br /><em>Based on your questionnaire responses.</em></td>
        <td style="width: 80px;" class="right"><?= $this->currency($assessmentViewModel->getAnnualCostOfOutSourcing()); ?></td>
    </tr>
    <tr>
        <td>Annual cost of internal IT servicing and supporting printing devices<br /><em>Based on your questionnaire responses.</em></td>
        <td class="right"><?= $this->currency($assessmentViewModel->getAnnualITCost()); ?></td>
    </tr>
    <tr>
        <td class="bold topborder">Total estimated annual cost of service</td>
        <td class="right bold topborder"><?= $this->currency($assessmentViewModel->getEstimatedAnnualCostOfService()); ?></td>
    </tr>
</table>
<table cellspacing="0" style="font-size: 10pt;">
    <tr>
        <td class="bold">Hardware</td>
        <td class="right">&nbsp;</td>
    </tr>
    <tr>
        <td style="width: 565px;"><strong>Total estimated annual cost of hardware purchases</strong><br /><em>Based on the age of your devices and an average
                purchase price of <?= $this->currency($assessmentViewModel->assessment->getClient()->getClientSettings()->genericSettings->defaultPrinterCost) ?>.</em></td>
        <td style="width: 80px;" class="right bold"><?= $this->currency($assessmentViewModel->getAnnualCostOfHardwarePurchases()); ?></td>
    </tr>
    <tr>
        <td class="bold topborder">TOTAL ESTIMATED ANNUAL COST</td>
        <td class="right bold topborder"><?= $this->currency($assessmentViewModel->getTotalPurchasedAnnualCost()); ?></td>
    </tr>
    <tr>
        <td>Predicted average annual monochrome prints</td>
        <td class="right"><?= $this->formatPageVolume($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getBlackPageCount()->getYearly()); ?></td>
    </tr>
    <tr>
        <td>Predicted average annual color prints</td>
        <td class="right"><?= $this->formatPageVolume($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getYearly()); ?></td>
    </tr>
    <tr>
        <td class="bold">Estimated all-in cost for a monochrome page</td>
        <td class="right bold"><?= $this->formatCostPerPage($assessmentViewModel->getEstimatedAllInBlackAndWhiteCPP()); ?></td>
    </tr>
    <tr>
        <td class="bold">Estimated all-in cost for a color page</td>
        <td class="right bold"><?= $this->formatCostPerPage($assessmentViewModel->getEstimatedAllInColorCPP()); ?></td>
    </tr>
</table>
<br />
<p>Through our <?= $this->brandName; ?> program, we can combine supplies and service for these machines into a single cost-per-page rate. By partnering
    with <?= $this->companyName; ?> as your single-source provider, your printing devices will be efficiently managed and your staff can get back to
    concentrating on their core responsibilities. Out of these devices, below are the top three most expensive to operate:</p>
<br />
<table cellspacing="0" class="genericTable">
    <thead>
    <tr>
        <th style="width: 225px;">Printing Device</th>
        <th style="width: 125px;" class="center">Serial No.</th>
        <th style="width: 125px;" class="center">Monthly Volume</th>
        <th style="width: 115px;" class="center">Monthly Cost</th>
    </tr>
    </thead>
    <tbody>

    <?php $ctr = 0;
    foreach ($assessmentViewModel->getMostExpensiveDevices() as $deviceInstance) : /* @var $deviceInstance DeviceInstanceModel */
        $ctr++;
        if ($ctr > 3)
        {
            break;
        } ?>
        <tr>
            <td>
                <div style="width: 225px; padding: 0px;"><?= $deviceInstance->getDeviceName(); ?></div>
            </td>
            <td class="center"><?= ($deviceInstance->serialNumber) ? : 'Unknown'; ?></td>
            <td class="center"><?= $this->formatPageVolume($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly()); ?> pages</td>
            <td class="center">
                <?= $this->currency($deviceInstance->getMonthlyRate($assessmentViewModel->getCostPerPageSettingForCustomer())); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
