<div class='container'>
    <div class="clearfix">
        <a class="btn btn-success pull-right btn-sm create-button" href="<?php
        use MPSToolbox\Legacy\Mappers\DealerMapper;
        use MPSToolbox\Legacy\Models\UserModel;

        echo $this->url(array(), 'admin.users.create') ?>">
            <i class="glyphicon glyphicon-plus-sign"></i> Create new</a>
    </div>
    <?php if (isset($this->users) && count($this->users) > 0) : ?>
        <table class="table table-striped table-condensed table-bordered">
            <thead>
            <tr>
                <th>Email</th>
                <th>Name</th>
                <th>Dealer Name</th>
                <th style="width: 70px;">Login Attempts</th>
                <th style="width: 100px;">Frozen Until</th>
                <th style="width: 60px;">Locked</th>
                <th style="width: 120px;">Last Seen</th>
                <th style="width: 60px;">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $user UserModel */ ?>
            <?php foreach ($this->users as $user) : ?>
                <tr>
                    <td><?= $user->email; ?></td>
                    <td><?= $user->firstname; ?> <?= $user->lastname; ?></td>
                    <td><?= DealerMapper::getInstance()->find($user->dealerId)->dealerName ?></td>
                    <td style="text-align: center;"><?= $user->loginAttempts; ?></td>
                    <td><?= ($user->isFrozen()) ? $user->frozenUntil : ""; ?></td>
                    <td style="text-align: center;"><?= ($user->locked) ? "Yes" : "No"; ?></td>
                    <td><?= ($user->lastSeen === null) ? "Never" : sprintf('<i class="fa fa-fw fa-clock-o js-tooltip" title="%s"></i> ', $user->lastSeen) . (new \Carbon\Carbon($user->lastSeen))->diffForHumans(); ?></td>
                    <td>
                        <div class="btn-group btn-group-justified btn-group-xs">
                            <?php if ($user->id == 1 && $this->identity()->id !== 1) : ?>
                                <span class="btn btn-warning disabled"><i class="glyphicon glyphicon-pencil"></i></span>
                            <?php else : ?>
                                <a class="btn btn-warning" title="Edit User" href="<?= $this->url(array('id' => $user->id), 'admin.users.edit') ?>">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </a>
                                <?php if ($user->id == 1) : ?>
                                    <span class="btn btn-danger disabled">
                                    <i class="glyphicon glyphicon-trash"></i></span>
                                <?php else : ?>
                                    <a class="btn btn-danger" title="Delete User" href="<?= $this->url(array('id' => $user->id), 'admin.users.delete') ?>"><i class="glyphicon glyphicon-trash"></i></a>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else : ?>
        <h1>There are no users</h1>
    <?php endif; ?>
</div>