<?php

use MPSToolbox\Legacy\Models\UserModel;

/* @var $user UserModel */
$user = $this->user;
?>
<div class='container'>
    <div class="row">
        <div class="col-md-4">
            <p></p>
            <p></p>
            <div class="thumbnail">
                <?= $this->UserAvatar(256, 'img-responsive'); ?>
                <div class="caption text-center">
                    <p class="lead"><?= $user->firstname?> <?= $user->lastname ?></p>
                </div>
            </div>

        </div>
        <?= $this->form ?>

    </div>
</div>