<?php

use MPSToolbox\Legacy\Models\UserModel;

/* @var $user UserModel */
$user = $this->user;
?>
<div class='container'>
    <div class="row">
        <div class="col-md-4">
            <div class="thumbnail">
                <?= $this->UserAvatar(256, 'img-responsive'); ?>
                <div class="caption text-center">
                    <p class="lead">Your Gravatar</p>

                    <p>Your profile picture is powered by
                        <a href="https://gravatar.com">Gravatar
                            <i class="fa fa-fw fa-external-link"></i></a>. To change your picture you will need to log into your Gravatar account and change the picture associated with your email address that you use to log into this application.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="panel panel-primary">
                <div class="panel-heading">User Profile</div>
                <div class="panel-body">
                    <?= $this->form ?>
                </div>
            </div>
        </div>
    </div>
</div>