<?php
use MPSToolbox\Legacy\Forms\DeleteConfirmationForm;

/* @var $form DeleteConfirmationForm */
$form    = $this->element;
$message = $this->message;
?>

<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>
<p><?= $message ?></p>
<fieldset>
    <hr>
    <?= $this->RenderFormSubmit($form->getElement('submit'), ['btn', 'btn-primary']) ?>
    <?= $this->RenderFormSubmit($form->getElement('cancel'), ['btn', 'btn-default']) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>


