<?php
/**
 * Memjet Optimization Title Page
 */

/* @var $section PHPWord_Section */
$section = $this->section;
/* @var $memjetOptimization Memjetoptimization_Model_Memjet_Optimization */
$memjetOptimization = $this->memjetOptimization;

$titleImageStyle = array('align' => 'center');

// Table to fix the issue of images being different sizes
$imageTable = $section->addTable(array('borderBottomSize' => 1));
$imageTable->addRow(2500);
$cell = $imageTable->addCell(15000.8, array('valign' => 'center'));
$cell->addImage(PUBLIC_PATH . "/themes/default/proposalgenerator/reports/images/mpstoolbox_logo.jpg", array('align' => 'center'));

$section->addTextBreak();
// Assessment Title
$section->addText('', null, 'titleStyle2');
$section->addText('  Memjet Optimization', 'titlepage_title', 'titleStyle2');
$section->addText('', null, 'titleStyle2');


$section->addTextBreak();

$section->addText(' ', 'titlepage_address', 'titleStyle3');
$section->addText(sprintf('Prepared For: %1$s', $this->memjetOptimization->getClient()->companyName), 'titlepage_subtitle', 'titleStyle3');

// Parse the address
$addressLines = explode("\n",$memjetOptimization->getClient()->getAddress()->getFullAddressMultipleLines());
$addressCount = 1;
foreach ($addressLines as $line)
{
    $section->addText($line, 'titlepage_address', 'titleStyle3');
    $addressCount++;
}
$section->addText(' ', 'titlepage_address', 'titleStyle3');
$section->addText('Date:' . " " . $memjetOptimization->dateCreated, 'titlepage_address', 'titleStyle3');

// Add extra blank lines to make the grey box big
if ($addressCount < 11)
{
    for ($i = 0; $i < 11 - $addressCount; $i++)
    {
        $section->addText(' ', 'titlepage_address', 'titleStyle3');
    }
}