<?php
/**
 * deviceleasing.phtml
 */
?>

<?php $this->headScript()->captureStart('append','text/javascript') ?>
	var show_mapped = false;
	
    $(document).ready(function() {
		//find center screen for modal popup
		var sTop = ($(window).height()/2)-100;
		var sLeft = ($(window).width()/2)-200;
		
		jQuery("#details_toners").jqGrid({
			url:'<?php echo $this->url(array('action' => 'devicetoners', 'controller' => 'admin')); ?>?deviceid=0',
			datatype:'json',
			colNames:['Toner ID', 'SKU', 'Manufacturer', 'Type', 'Color', 'Yield', 'Price', 'MasterID'],
			colModel:[
        		{width:30, name:'toner_id', index:'toner_id', sorttype:'int', hidden:true, editable:true, editoptions:{readonly:true, size:12}},
				{width:50, name:'toner_sku', index:'toner_sku', editable:true, editoptions:{size:12, maxlength:30}},
				{width:100, name:'manufacturer_id', index:'manufacturer_id'},
				{width:50, name:'part_type_id', index:'part_type_id'},
				{width:50, name:'toner_color_id', index:'toner_color_id'},
				{width:50, name:'toner_yield', index:'toner_yield', align:'right'},
				{width:50, name:'toner_price', index:'toner_price', align:'right', formatter:'currency', formatoptions:{prefix:"$", thousandsSeparator:","}},
				{width:50, name:'master_device_id', index:'master_device_id', hidden:true}
			],
			height: 110,
			width: 940,
			beforeProcessing:function() {
				
			},
			gridComplete:function(){
			}
		});
		
		jQuery("#details_toners").jqGrid('navGrid','#details_toners_pager',
			{add:false, del:false, edit:false, refresh:false, search:false},
			{closeAfterEdit:false, recreateForm:true, reloadAfterSubmit:true, closeOnEscape:true, width:400},
			{closeAfterAdd:false, recreateForm:true, reloadAfterSubmit:true, closeOnEscape:true, width:400},
			{},
			{},
			{}
		);
    		
		jQuery("#results_list").jqGrid({
			url:'<?php echo $this->url(array('action' => 'deviceleasinglist')); ?>',
			datatype:'json',
			colNames:['UDCID','Devices PF ID','Import Printer Name (IP)','Master Printer Name','AMPV','Ownership','Exclude','Master Printer ID'],
			colModel:[
				{tag:0, width: 10, name:'upload_data_collector_row_id', index:'upload_data_collector_row_id', hidden:true, title:false, sortable:false},
				{tag:1, width: 10, name:'devices_pf_id', index:'devices_pf_id', hidden:true, title:false, sortable:false},
				{tag:2, width: 240, name:'imported_devicename', index:'imported_devicename', title:false, sortable:false},
				{tag:3, width: 240, name:'master_device', index:'master_device', title:false, sortable:false},
				{tag:4, width: 50, name:'ampv', index:'ampv', title:false, sortable:false, align:'right'},
				{tag:5, width: 80, name:'is_leased', index:'is_leased', align:'center', title:false, sortable:false},
				{tag:6, width: 60, name:'is_excluded', index:'is_excluded', align:'center', title:false, sortable:false},
				{tag:7, width: 50, name:'master_device_id', index:'master_device_id', hidden:true, title:false, sortable:false}
			],
			width:940,
			height:400,
			rowNum:100,
			rowList:[100,200,400],
			pager:'#results_pager',
			gridComplete:function(){ 
				var ids = jQuery("#results_list").jqGrid('getDataIDs');
				for(var i=0; i < ids.length; i++) {
					var cur_row = ids[i];
					var id = document.getElementById("results_list").rows[i+1].cells[0].innerHTML;
					var is_leased = document.getElementById("results_list").rows[i+1].cells[5].innerHTML;
					var is_excluded = document.getElementById("results_list").rows[i+1].cells[6].innerHTML;
					var master_printer = document.getElementById("results_list").rows[i+1].cells[3].innerHTML;
					var master_printer_id = document.getElementById("results_list").rows[i+1].cells[7].innerHTML;
					
					if(is_leased == 1) {
						leased_checkbox = 'Leased';
					} else {
						leased_checkbox = 'Purchased';
					}
					jQuery("#results_list").jqGrid('setRowData',ids[i],{is_leased: leased_checkbox});
					
					if(is_excluded == 1) {
						excluded_checkbox = '<input type="checkbox" name="chkExclude'+cur_row+'" id="chkExclude'+cur_row+'" onclick="javascript: set_excluded('+cur_row+');" checked="checked" />';
					} else {
						excluded_checkbox = '<input type="checkbox" name="chkExclude'+cur_row+'" id="chkExclude'+cur_row+'" onclick="javascript: set_excluded('+cur_row+');" />';
					}
					jQuery("#results_list").jqGrid('setRowData',ids[i],{is_excluded: excluded_checkbox});
					
					//update master printer column to be a link to details
					master_printer_column = '<a href="javascript: void(0);" onclick="javascript: toggle_request(true,\''+master_printer_id+'\');" class="">'+master_printer+'</a>';
					jQuery("#results_list").jqGrid('setRowData',ids[i],{master_device: master_printer_column});
				}
			},
			editurl:'dummy.php'
		});
		
		jQuery("#results_list").jqGrid('navGrid','#results_pager',
				{add:false,del:false,edit:false,refresh:false,search:false},
				{closeAfterEdit:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{closeAfterAdd:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{},
				{},
				{}
		);
		
		jQuery("#excluded_results_list").jqGrid({
			url:'',
			datatype:'json',
			colNames:['UDCID','Devices PF ID','Import Printer Name (IP)','Reason For Exclusion'],
			colModel:[
				{tag:0, width: 10, name:'upload_data_collector_row_id', index:'upload_data_collector_row_id', hidden:true, title:false, sortable:false},
				{tag:1, width: 10, name:'devices_pf_id', index:'devices_pf_id', hidden:true, title:false, sortable:false},
				{tag:2, width: 300, name:'imported_devicename', index:'imported_devicename', title:false, sortable:false},
				{tag:3, width: 100, name:'reaason', index:'reaason', title:false, sortable:false}
			],
			width:940,
			height:200,
			rowNum:25,
			rowList:[25,50,100],
			pager:'#excluded_results_pager'
		});
		
		jQuery("#excluded_results_list").jqGrid('navGrid','#excluded_results_pager',
				{add:false,del:false,edit:false,refresh:false,search:false},
				{closeAfterEdit:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{closeAfterAdd:true,recreateForm:true,closeOnEscape:true,width:400,top:sTop,left:sLeft},
				{},
				{},
				{}
		);
    });
    
	function checkAllExcluded(mode, e) {
		var counter = 0;
		var allow_button = true;
		e = e||event;
		e.stopPropagation? e.stopPropagation() : e.cancelBubble = true;
		excluded = document.getElementById("chkToggleExclude").checked;
		
		for (i=0; i < document.leasing.elements.length; i++) {
			var id = '';
			if(document.leasing.elements[i].type == "checkbox") {
				if(document.leasing.elements[i].id.indexOf("chkExclude") > -1) {
					id = document.leasing.elements[i].name.replace("chkExclude","");
					document.leasing.elements[i].checked = excluded;
					set_excluded(id);
				}
			}
		}
	}
    
	function checkAllLeased(mode, e) {
		var counter = 0;
		var allow_button = true;
		e = e||event;
		e.stopPropagation? e.stopPropagation() : e.cancelBubble = true;
		leased = document.getElementById("chkToggleLeased").checked;
		
		for (i=0; i < document.leasing.elements.length; i++) {
			var id = '';
			if(document.leasing.elements[i].type == "checkbox") {
				if(document.leasing.elements[i].id.indexOf("chkLeased") > -1) {
					id = document.leasing.elements[i].name.replace("chkLeased","");
					document.leasing.elements[i].checked = leased;
					set_leased(id);
				}
			}
		}
	}
	
	function set_excluded(id) {
		mode = $("#chkExclude"+id).is(':checked');
		if(mode == true) {
			mode = 1;
		} else {
			mode = 0;
		}
		url = '<?php echo $this->url(array('action' => 'setexcluded')); ?>?id='+id+'&mode='+mode;
		$.ajax ({
			type: "POST",
			contentType: "application/json; charset=utf-8",
	        url: url,
			error: function() {
				$('#message_container').html("Error exluding printer.");
			}
		});
	}

	function set_leased(id) {
		mode = $("#chkLeased"+id).is(':checked');
		if(mode == true) {
			mode = 1;
		} else {
			mode = 0;
		}
		url = '<?php echo $this->url(array('action' => 'setleased')); ?>?id='+id+'&mode='+mode;
		$.ajax ({
			type: "POST",
			contentType: "application/json; charset=utf-8",
	        url: url,
			error: function() {
				$('#message_container').html("Error marking printer as leased.");
			}
		});
	}

    function doAction(inAction) {
        if(inAction == 'cancel') {
			document.location.href = "<?php echo $this->url(array('action' => 'devicemapping')); ?>";
        }
    }

	function toggle_mapped() {
		if(document.getElementById('excluded_results_list_container').style.display == 'none') {
		 	if(show_mapped == false) {
				$('#excluded_results_list').setGridParam({url:'<?php echo $this->url(array('action' => 'deviceleasingexcludedlist')); ?>'});
				$('#excluded_results_list').trigger("reloadGrid");
			}
			$("#toggle_mapped_link").html("[-] Hide Excluded Printers");
			document.getElementById('excluded_results_list_container').style.display = 'block';
		} else {
			$("#toggle_mapped_link").html("[+] Show Excluded Printers");
			document.getElementById('excluded_results_list_container').style.display = 'none';
		}
	}
	
	function toggle_request(mode, id) {
		if(mode == true) {
			if(id.indexOf('udi') >= 0) {
				//GET UNKNOWN DEVICE DETAILS
				url = '<?php echo $this->baseUrl(); ?>/data/unknowndevicedetails?deviceid='+id.replace('udi','');
				toners_url = '<?php echo $this->url(array('action' => 'unknowndevicetoners', 'controller' => 'data')); ?>?deviceid='+id.replace('udi','');
				$("#details_toners").jqGrid().hideCol('manufacturer_id');
				
			} else {
		    	//GET DEVICE DETAILS
				url = '<?php echo $this->url(array('action' => 'devicedetails', 'controller' => 'data')); ?>?deviceid='+id;
				toners_url = '<?php echo $this->url(array('action' => 'devicetoners', 'controller' => 'data')); ?>?deviceid='+id;
				$("#details_toners").jqGrid().showCol('manufacturer_id');
			}
			
		    $.ajax({
		        beforeSend: function() {
		        },
		        url: url,
		        success: function(data) {
		            var obj = jQuery.parseJSON(data);
		            var yes_image = '<img src="<?php echo $this->theme("statusicons/checkmark_32_32x32.png"); ?>" alt="yes" width="18" height="18" border="0" />';
		            var no_image = '<img src="<?php echo $this->theme("statusicons/error_32_32x32.png"); ?>" alt="no" width="18" height="18" border="0" />';
		            
		            $('#details_manufacturer').html(obj.manufacturer);
		            $('#details_printer_model').html(obj.printer_model);
		            $('#details_launch_date').html(obj.launch_date);
		            
		            if(obj.is_copier == 1) {
		            	$('#details_copier').html(yes_image);
		            } else {
		            	$('#details_copier').html(no_image);
		            }
		            if(obj.is_scanner == 1) {
    		            $('#details_scanner').html(yes_image);
		            } else {
    		            $('#details_scanner').html(no_image);
		            }
		            if(obj.is_fax == 1) {
    		            $('#details_fax').html(yes_image);
		            } else {
    		            $('#details_fax').html(no_image);
		            }
		            if(obj.is_duplex == 1) {
    		            $('#details_duplex').html(yes_image);
		            } else {
    		            $('#details_duplex').html(no_image);
		            }
		            
		            $('#details_ppm_black').html(obj.ppm_black);
		            $('#details_ppm_color').html(obj.ppm_color);
		            $('#details_duty_cycle').html(obj.duty_cycle);
		            $('#details_watts_power_normal').html(obj.watts_power_normal);
		            $('#details_watts_power_idle').html(obj.watts_power_idle);
		            $('#details_printer_price').html("$"+obj.device_price);
		            $('#details_toner_config').html(obj.toner_config);
		            if(obj.is_leased == 1) {
    		            $('#details_is_leased').html(yes_image);
		            } else {
    		            $('#details_is_leased').html(no_image);
		            }
		            $('#details_leased_toner_yield').html(obj.leased_toner_yield);
		            if (obj.leased_toner_yield > 0) {
		            	$('#leased_toner_yield_row').css('display','block');
		            } else {
		            	$('#leased_toner_yield_row').css('display','none');
		            }
		        },
		        error: function() {
		            $('#details_error').html("Error returning printer details.");
		        },
		        complete: function() {
		        }
			});
			
			//POPULATE TONERS
    		$('#details_toners').setGridParam({url:toners_url});
    	    $('#details_toners').trigger('reloadGrid');
    	   	setTimeout("$('#details_toners').setGridWidth(600)", 200);
			
			//lock scrollbars and open lightbox panel
			$("#lightbox, #lightbox-panel").fadeIn(300);
			$("html, body").animate({scrollTop:0}, 'slow');
			$("body").css("overflow", "hidden");
			
		} else {
			//close lightbox panel
			$("#lightbox, #lightbox-panel").fadeOut(300);
			$("body").css("overflow", "auto");
			
			//clear device details
			$("#selected_device_id").html('');
		}
	}
	
<?php $this->headScript()->captureEnd() ?>

<style>
/* THIS WILL WRAP CELL DATA IN GRID */
.ui-jqgrid tr.jqgrow td {
	white-space: normal !important;
}
</style>

<table style="width: 100%;border-collapse: collapse; table-layout: fixed">
	<tr>
		<td class = "Title"><u><?php echo $this->formTitle?></u></td>
		<?php if ($this->companyName) :?>
		<td class = "PreparedFor"><i>Prepared For:</i></td>
		<td class = "PreparedForText"><i><?php echo $this->companyName; ?></i></td>
		<?php endif?>
	</tr>
</table>

<form name="leasing" id="leasing" class="fileinput" action="" method="POST">
<input type="hidden" name="hdnID" id="hdnID" value="" />
<dl class="zend_form">
	<dt class="botMenu">
	
		<div class="message_container margined">
		    <?php echo $this->message; ?>
		</div>
		
		<?php if(isset($this->mapping_error)) { ?>
		<div class="mapping_error_container margined">
		    <?php echo $this->mapping_error; ?>
		</div>
		<?php } ?>
				
		<?php if(isset($this->mappingArray)) { ?>
		<div class="results_container">
		
			<div class="results_list_container">
				<table id="results_list"></table>
				<div id="results_pager"></div>
			</div>
			<div class="legend_note"><strong>AMPV</strong> = Average Monthly Page Volume</div>
			
			<?php if($this->exclude_count > 0) { ?>
			<p><a id="toggle_mapped_link" href="javascript: void(0);" onclick="javascript: toggle_mapped();" style="text-decoration: none;">[+] Show Excluded Printers</a></p>
			<div id="excluded_results_list_container" style="display: none;">
				<h3>Excluded Printers:</h3>
				<p></p>
				<table id="excluded_results_list"></table>
				<div id="excluded_results_pager"></div>
			</div>
			<?php } ?>
			
			<br/>
			
			<div id="submitBtns" class="submitBar">
				<input type="submit" name="btnNext" id="btnNext" value="Save and continue" class="btn btn-primary" />
				<input type="button" name="btnBack" id="btnBack" value="Back" onClick="javascript: doAction('cancel');" class="btn" />
			</div>
			
		</div>
		<?php } ?>
		
    	<div id="lightbox-panel" class="device_details_container">
        	<h3><span class="details_sub_header" id="details_manufacturer">Manufacturer</span> <span class="details_sub_header" id="details_printer_model">Model</span></h3>
        	
        	<div id="details_error"></div>
        	<div class="details_container">
        		<table width="100%" class="details_table" cellpadding="0" cellspacing="0">
        			<col width="30%" /><col width="70%" />
        			<tr class="details_alt">
        				<td><span class="details_label">Launch Date:</span></td>
        				<td><span id="details_launch_date"></span></td>
        			</tr>
        			<tr>
        				<td><span class="details_label">Copier:</span></td>
        				<td><span id="details_copier"></span></td>
        			</tr>
        			<tr class="details_alt">
        				<td><span class="details_label">Scanner:</span></td>
        				<td><span id="details_scanner"></span></td>
        			</tr>
        			<tr>
        				<td><span class="details_label">Fax:</span></td>
        				<td><span id="details_fax"></span></td>
        			</tr>
        			<tr class="details_alt">
        				<td><span class="details_label">Duplex:</span></td>
        				<td><span id="details_duplex"></span></td>
        			</tr>
        			<tr>
        				<td><span class="details_label">PPM Black:</span></td>
        				<td><span id="details_ppm_black"></span></td>
        			</tr>
        			<tr class="details_alt">
        				<td><span class="details_label">PPM Color:</span></td>
        				<td><span id="details_ppm_color"></span></td>
        			</tr>
        			<tr>
        				<td><span class="details_label">Duty Cycle:</span></td>
        				<td><span id="details_duty_cycle"></span></td>
        			</tr>
        			<tr class="details_alt">
        				<td><span class="details_label">Watts Power Normal:</span></td>
        				<td><span id="details_watts_power_normal"></span></td>
        			</tr>
        			<tr>
        				<td><span class="details_label">Watts Power Idle:</span></td>
        				<td><span id="details_watts_power_idle"></span></td>
        			</tr>
        			<tr class="details_alt">
        				<td><span class="details_label">Printer Price:</span></td>
        				<td><span id="details_printer_price"></span></td>
        			</tr>
        			<tr>
        				<td><span class="details_label">Toner Config:</span></td>
        				<td><span id="details_toner_config"></span></td>
        			</tr>
        			<tr class="details_alt">
        				<td><span class="details_label">Is Leased:</span></td>
        				<td><span id="details_is_leased"></span></td>
        			</tr>
        			<tr id="leased_toner_yield_row">
        				<td><span class="details_label">Leased Toner Yield:</span></td>
        				<td><span id="details_leased_toner_yield"></span></td>
        			</tr>
        		</table>
            </div>
            
            <div class="details_toners_container">
            	<h4>Toners:</h4>
				<table id="details_toners"></table>
            </div>
    		
    		<div id="submitBtns" class="submitBar">	
				<input type="button" value="Done" onclick="javascript: toggle_request(false);" class="btn" />
    	    </div>
    	    
    	</div>
    	
	</dt>
</dl>
</form>


<form class="proposalForm form-horizontal" method="POST">
    <div class="form-actions">
        <input type="submit" name="saveAndContinue" id="saveAndContinue" value="Save &amp; Continue" class="btn btn-primary">
        <input type="submit" name="goBack" id="goBack" value="Go Back" class="btn">
    </div>
</form>