<?php

use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\RmsUploadRowModel;

$this->headScript()->appendFile($this->baseUrl('js/app/legacy/proposalgen/fleet/FleetEditUnknownDevice.js'));

/* @var $rmsUploadRow RmsUploadRowModel */
$rmsUploadRow = $this->rmsUploadRow;
?>
<div class="container">
    <?php if ($rmsUploadRow instanceof RmsUploadRowModel) : ?>
        Device: <?= $rmsUploadRow->manufacturer . " " . $rmsUploadRow->modelName; ?>
    <?php endif; ?>
    <?= $this->form ?>
</div>
