<div class="page-header">
    <h1>Fleet<small> - Upload Data</small></h1>
</div>
<div class="well">
    <?php echo $this->form; ?>
</div>
<div class="well">
    <form class="proposalForm form-horizontal" method="POST">
    	<div class="form-actions">
            <input type="submit" name="saveAndContinue" id="saveAndContinue" value="Save &amp; Continue" class="btn btn-primary">
            <input type="submit" name="goBack" id="goBack" value="Go Back" class="btn">
        </div>
    </form>
</div>