<div class="page-header">
    <h1>Fleet<small> - Upload Data</small></h1>
</div>

<form id="fileinput" class="fileinput" enctype="multipart/form-data" method="POST">
    <div id="upload_container" class="well">
        <div>Choose a <span style="color: red">.CSV</span> file to upload: <input name="uploadedfile" id="uploadedfile" accept="application/csv, text/csv" type="file" size="60" class="upload_file" /></div>
        <div><input type="submit" name="uploadData" id="csv_submit" value="Upload File" class="btn" /></div>
    </div>
    
    <h3>Imported Results:</h3>
    <?php if($this->has_data) : ?>
    	<table id="results_list"></table>
    	<div id="results_pager"></div>
    <?php endif; ?>
    
    <?php if($this->bad_data) : ?>
    	<h3>Excluded Results:</h3>
    	<p>Records below have been excluded because they are missing data in required fields.</p>
        <table id="excluded_results_list"></table>
        <div id="excluded_results_pager"></div>
    <?php endif; ?>

</form>
    <form class="proposalForm form-horizontal" method="POST">
    	<div class="form-actions">
            <input type="submit" name="saveAndContinue" id="saveAndContinue" value="Save &amp; Continue" class="btn btn-primary">
            <input type="submit" name="goBack" id="goBack" value="Go Back" class="btn">
        </div>
    </form>