<?php

use MPSToolbox\Legacy\Models\Acl\AppAclModel;
use MPSToolbox\Legacy\Models\Acl\ProposalgenAclModel;
use MPSToolbox\Legacy\Models\Acl\QuoteGeneratorAclModel;

?>
<script>
    <?php $this->headScript()->captureStart('append', 'text/javascript'); ?>
    var isSaveAndApproveAdmin = <?=($this->IsAllowed(ProposalgenAclModel::RESOURCE_PROPOSALGEN_ADMIN_SAVEANDAPPROVE, AppAclModel::PRIVILEGE_ADMIN) ? 'true' : 'false'); ?>,
        canDelete             = <?=($this->IsAllowed(QuoteGeneratorAclModel::RESOURCE_QUOTEGEN_DEVICESETUP_DELETE, AppAclModel::PRIVILEGE_VIEW) ? 'true' : 'false'); ?>,
        dealerSkuName         = '<?= My_Brand::$dealerSku; ?>',
        rmsUploadId           = <?= $this->rmsUpload->id; ?>;
    <?php $this->headScript()->captureEnd(); ?>
</script>
<?php $this->headScript()->appendFile($this->baseUrl('js/app/legacy/proposalgen/fleet/FleetDeviceMapping.js')); ?>
<div class="container">
    <p>You can map and remap devices by typing into the "Select Master Device" field. The "Select Master Device" text box acts as a search. Once you select an item it will perform the mapping for you. In the case that the device does not exist you may add it using the action menu. If the device is mapped incorrectly you will need to remove the mapping by clearing the text in the "Select Master Device" box.</p>

    <div id="deviceMappingGrid"></div>
    <?= $this->navigationForm; ?>
</div>
