<?php $this->headScript()->captureStart('append', 'text/javascript'); ?>
var canEditMasterDevices = <?php echo ($this->IsAllowed('proposalgen__managedevices__managemappingdevices')) ? 'true' : 'false'; ?>;
var rmsUploadId = <?php echo $this->rmsUpload->id; ?>
<?php $this->headScript()->captureEnd(); ?>

<?php $this->headScript()->appendFile($this->baseUrl('js/proposalgen/fleet/deviceMapping.js')); ?>
<div class="well">
    <p>You can map and remap devices by typing into the "Select Master Device" field. The "Select Master Device" text box acts as a search. Once you select an
        item it will perform the mapping for you. In the case that the device does not exist you may add it using the action menu. If the device is mapped
        incorrectly you will need to remove the mapping by clearing the text in the "Select Master Device" box.</p>

    <form id="addUnknownDeviceForm" action="<?php echo $this->url(array("action" => "edit-unknown-device")); ?>" method="POST">
        <input type="hidden" name="deviceInstanceIds" id="unknownDeviceDeviceInstanceIds" />
    </form>
    <form id="addMasterDeviceForm" action="<?php echo $this->url(array("controller" => "managedevices", "action" => "managemappingdevices")); ?>" method="POST">
        <input type="hidden" name="deviceInstanceIds" id="masterDeviceDeviceInstanceIds" />
    </form>
    <table id="mappingGrid"></table>
    <div id="mappingGridPager"></div>

    <?php echo $this->navigationForm; ?>
</div>
