<?php $this->headScript()->captureStart('append', 'text/javascript'); ?>
var rmsUploadId = <?php echo $this->rmsUpload->id; ?>;
var jit = '<?php echo My_Brand::$jit; ?>';
<?php $this->headScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->baseUrl('js/proposalgen/fleet/deviceSummary.js')); ?>
<div class="well">
    <table id="summaryGrid"></table>
    <div id="summaryGridPager"></div>
    <?php echo $this->navigationForm; ?>
</div>
<div class="lightbox-panel" id="deviceDetailsContainer" style="display: none;">

    <div class="tabbable">
        <ul class="nav nav-tabs" id="deviceInstanceInfoTabs">
            <li class="active"><a href="#deviceInstanceDetailsTab" data-toggle="tab">Model Details</a></li>
            <li><a href="#deviceInstanceMetersTab" data-toggle="tab">Meters & Coverages</a></li>
            <li><a href="#deviceInstanceSuppliesTab" data-toggle="tab">Supplies</a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="deviceInstanceDetailsTab">
                <h4>Device Details</h4>
                <table class="table table-bordered table-striped table-condensed">
                    <tr>
                        <td style="width: 200px;">Launch Date:</td>
                        <td id="deviceDetails_launchDate">Launch Date</td>
                    </tr>
                    <tr>
                        <td>PPM Black:</td>
                        <td id="deviceDetails_ppmBlack"></td>
                    </tr>
                    <tr>
                        <td>PPM Color:</td>
                        <td id="deviceDetails_ppmColor"></td>
                    </tr>
                    <tr>
                        <td>Watts Power Normal:</td>
                        <td id="deviceDetails_wattsPowerNormal"></td>
                    </tr>
                    <tr>
                        <td>Watts Power Idle:</td>
                        <td id="deviceDetails_wattsPowerIdle"></td>
                    </tr>
                    <tr>
                        <td>Device Cost:</td>
                        <td id="deviceDetails_cost"></td>
                    </tr>
                    <tr>
                        <td>Toner Configuration:</td>
                        <td id="deviceDetails_tonerConfigName"></td>
                    </tr>
                    <tr>
                        <td>Leased by default:</td>
                        <td id="deviceDetails_isLeased">YESNO</td>
                    </tr>
                    <tr>
                        <td>Copier:</td>
                        <td id="deviceDetails_isCopier">YES</td>
                    </tr>
                    <tr>
                        <td>Duplex:</td>
                        <td id="deviceDetails_isDuplex">NO</td>
                    </tr>
                    <tr>
                        <td>Fax:</td>
                        <td id="deviceDetails_isFax">YES</td>
                    </tr>
                    <tr>
                        <td>Can Print A3:</td>
                        <td id="deviceDetails_isA3">YES</td>
                    </tr>
                    <tr>
                        <td>Capable of Reporting Toner Levels:</td>
                        <td id="deviceDetails_reportsToners">YES</td>
                    </tr>
                    <tr>
                        <td><?php echo My_Brand::$jit; ?> compatible by default:</td>
                        <td id="deviceDetails_compatibleWithJit">YESNO</td>
                    </tr>
                    <tr>
                        <td>Location</td>
                        <td id="deviceDetails_location"></td>
                    </tr>
                </table>
            </div>
            <div class="tab-pane" id="deviceInstanceMetersTab">
                <h4>Meters</h4>
                <table class="table table-bordered table-striped table-condensed">
                    <thead>
                    <tr>
                        <th>Type</th>
                        <th>Monthly Volume</th>
                    </tr>
                    </thead>
                    <tbody id="deviceDetails_meters">

                    </tbody>
                </table>

                <h4>Page Coverages</h4>
                <table class="table table-bordered table-striped table-condensed">
                    <thead>
                    <tr>
                        <th>Black</th>
                        <th>Cyan</th>
                        <th>Magenta</th>
                        <th>Yellow</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td id="pageCoverageMonochrome">5%</td>
                        <td id="pageCoverageCyan">5%</td>
                        <td id="pageCoverageMagenta">5%</td>
                        <td id="pageCoverageYellow">5%</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="tab-pane" id="deviceInstanceSuppliesTab">
                <h4>Toners</h4>
                <table class="table table-bordered table-striped table-condensed">
                    <thead>
                    <tr>
                        <th>SKU</th>
                        <th>Manufacturer</th>
                        <th>Color</th>
                        <th>Yield</th>
                        <th>Cost</th>
                    </tr>
                    </thead>
                    <tbody id="deviceDetails_toners">

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>