<script>
    <?php $this->headScript()->captureStart('append', 'text/javascript'); ?>
    var rmsUploadId = <?= $this->rmsUpload->id; ?>,
        jit         = '<?= My_Brand::$jit; ?>';
    <?php $this->headScript()->captureEnd(); ?>
</script>
<?php $this->headScript()->appendFile($this->baseUrl('js/app/legacy/proposalgen/fleet/FleetDeviceSummary.js')); ?>
<div class="container">
    <table id="rms-upload-device-summary-grid"></table>
    <div id="rms-upload-device-summary-grid-pager"></div>
    <?= $this->navigationForm; ?>
    <?= $this->partial('fleet/summary-device-details-partial.phtml'); ?>
</div>