<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$brandName           = My_Brand::getDealerBranding()->mpsProgramName;
$companyName         = My_Brand::getDealerBranding()->shortDealerName;

/**
 * Format the highest toner vendor configuration names
 */
$vendorConfigurationNames = implode(', ', $this->highestNames);

// Replace last occurrence of a comma to an and
if (strrpos($vendorConfigurationNames, ',') > 0)
{
    $vendorConfigurationNames = substr_replace($vendorConfigurationNames, ' and ', strrpos($vendorConfigurationNames, ','), 1);
}

?>
<div class="container-fluid">
    <div class="jumbotron">
        <h1>Toner Vendors</h1>

        <p>You might be wondering who has the
            <strong>best profitability?</strong> <?= $vendorConfigurationNames; ?> <?= (count($this->highestNames) > 1) ? 'have' : 'has' ?> the highest overall gross margin at <?= $this->highestMargin ?>.
        </p>
    </div>
    <div class="tabbable">
        <ul class="nav nav-tabs">
            <?php $tabCounter = 0; ?>
            <?php foreach ($this->vendorSeparatedData as $vendorData) : ?>
                <li class="<?= ($tabCounter === 0) ? 'active' : '' ?>">
                    <a data-toggle="tab" href="#tab<?= $tabCounter; ?>"><?= $vendorData['pageTitle'] ?> (<?= $vendorData['statisticsGroup']['right']['Overall Margin']; ?>%)</a>
                </li>
                <?php $tabCounter++; ?>
            <?php endforeach; ?>
        </ul>
        <div class="tab-content">
            <?php $tabCounter = 0; ?>
            <?php foreach ($this->vendorSeparatedData as $vendorData) : ?>
                <div class="tab-pane <?= ($tabCounter === 0) ? 'active' : '' ?>" id="tab<?= $tabCounter; ?>">
                    <div>
                        <em>AMPV = Average Monthly Page Volume</em>
                    </div>

                    <br />

                    <div class="row">
                        <div class="col-lg-4 col-lg-push-1 col-sm-6">
                            <div class="table-responsive">
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <th><?= My_Brand::getDealerBranding()->mpsProgramName; ?> Monochrome CPP:</th>
                                        <td class="cost-per-page"><?= $vendorData['statisticsGroup']['left'][My_Brand::getDealerBranding()->mpsProgramName . ' Monochrome CPP'] ?></td>
                                    </tr>
                                    <tr>
                                        <th><?= My_Brand::getDealerBranding()->mpsProgramName; ?> Color CPP:</th>
                                        <td class="cost-per-page"><?= $vendorData['statisticsGroup']['left'][My_Brand::getDealerBranding()->mpsProgramName . ' Color CPP'] ?></td>
                                    </tr>
                                    <tr>
                                        <th>Weighted Monochrome CPP:</th>
                                        <td class="cost-per-page"><?= $vendorData['statisticsGroup']['left']['Weighted Monochrome CPP'] ?></td>
                                    </tr>
                                    <tr>
                                        <th>Weighted Color CPP:</th>
                                        <td class="cost-per-page"><?= $vendorData['statisticsGroup']['left']['Weighted Color CPP'] ?></td>
                                    </tr>
                                    <tr>
                                        <th>Monochrome Margin:</th>
                                        <td class="margin"><?= $vendorData['statisticsGroup']['left']['Monochrome Margin'] ?></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-lg-4 col-lg-push-3 col-sm-6">
                            <div class="table-responsive">
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <th>Total Cost:</th>
                                        <td class="cost"><?= $vendorData['statisticsGroup']['right']['Total Cost'] ?></td>
                                    </tr>
                                    <tr>
                                        <th>Total Revenue:</th>
                                        <td class="cost"><?= $vendorData['statisticsGroup']['right']['Total Revenue'] ?></td>
                                    </tr>
                                    <tr>
                                        <th>Monthly Profit:</th>
                                        <td class="cost"><?= $vendorData['statisticsGroup']['right']['Monthly Profit'] ?></td>
                                    </tr>
                                    <tr>
                                        <th>Overall Margin:</th>
                                        <td class="margin"><?= $vendorData['statisticsGroup']['right']['Overall Margin'] ?>%</td>
                                    </tr>
                                    <tr>
                                        <th>Color Margin:</th>
                                        <td class="margin"><?= $vendorData['statisticsGroup']['right']['Color Margin'] ?></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <p class="text-muted">Yellow highlighted rows indicate devices that have not been assigned toners matching your selected toner vendor(s) preference. For these devices the system has selected the best available alternative based on the current toner preference.</p>

                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th rowspan="2">Device Name<br>(IP Address - Serial Number)
                                </th>
                                <th colspan="5">Monochrome</th>
                                <th colspan="5">Color</th>
                            </tr>
                            <tr>
                                <th>AMPV</th>
                                <th>Toner Cost</th>
                                <th>Toner Yield</th>
                                <th>CPP</th>
                                <th>Total Printing Cost</th>
                                <th>AMPV</th>
                                <th>Toner Cost</th>
                                <th>Toner Yield</th>
                                <th>CPP</th>
                                <th>Total Printing Cost</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($vendorData['fieldLists'] as $key => $fields) {

                                $tr_class=[];
                                if (!$fields['completeMono']) $tr_class[] = 'nonCompliantMono';
                                if (!$fields['completeMono']) $tr_class[] = 'nonCompliantColor';
                                if (!$fields['black_isUsingDealerPricing']) $tr_class[] = 'redMono';
                                if (!$fields['color_isUsingDealerPricing']) $tr_class[] = 'redColor';

                                ?>
                                <tr class="<?= implode(' ', $tr_class) ?>">
                                    <td class="device-name"><?= $fields[0]['deviceName'] ?>
                                        <br /><?= sprintf('(%s - %s)', $fields[0]['serialNumber'], $fields[0]['ipAddress']) ?>
                                    </td>
                                    <td class="page-volume mono"><?= number_format($fields[1]) ?></td>
                                    <td class="cost mono"><?= is_numeric($fields[2]) ? $this->currency($fields[2]) : '-' ?></td>
                                    <td class="yield mono"><?= is_numeric($fields[3]) ? number_format($fields[3]) : '-' ?></td>
                                    <td class="cost-per-page mono"><?= is_numeric($fields[4]) ? $this->formatCostPerPage($fields[4]) : '-' ?></td>
                                    <td class="cost mono"><?= is_numeric($fields[5]) ? $this->currency($fields[5]) : '-' ?></td>

                                    <td class="page-volume color"><?= (is_numeric($fields[6]) ? number_format($fields[6]) : "-") ?></td>
                                    <td class="cost color"><?= (is_numeric($fields[7]) ? $this->currency($fields[7]) : "-") ?></td>
                                    <td class="yield color"><?= (is_numeric($fields[8]) ? number_format($fields[8]) : "-") ?></td>
                                    <td class="cost-per-page color"><?= (is_numeric($fields[9]) ? $this->formatCostPerPage($fields[9]) : "-") ?></td>
                                    <td class="cost color"><?= (is_numeric($fields[10]) ? $this->currency($fields[10]) : "-") ?></td>

                                </tr>
                            <?php } ?>
                            <tr class="totals">
                                <td><?= $vendorData['fieldTotals'][0] ?></td>
                                <td class="page-volume mono"><?= number_format($vendorData['fieldTotals'][4]) ?></td>
                                <td colspan="3"></td>
                                <td class="cost mono"><?= $this->currency($vendorData['fieldTotals'][8]) ?></td>
                                <td class="page-volume color"><?= number_format($vendorData['fieldTotals'][9]) ?></td>
                                <td colspan="3"></td>
                                <td class="cost color"><?= $this->currency($vendorData['fieldTotals'][13]) ?></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <?php $tabCounter++; ?>
            <?php endforeach ?>
        </div>
    </div>
</div>