<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$brandName = 'MPSToolbox.com';
$companyName = 'MPSToolbox.com';
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/grossmargin/grossmargin_html.css"));
?>
<div class="container" id="htmlReportContainer" style="width:100%;">
<div class="rows">
<h2 class="reportTitle text-center">Toner Vendor Gross Margin Report</h2><br />

<div class="span" style="width:200px">
    <div class="text-center">Select a Toner Preference</div>
    <ul class="nav nav-tabs nav-stacked">
        <li class="active"><a data-toggle="tab" href="#summary">Summary</a></li>
        <?php
        $tabCounter = 0;
        foreach ($this->vendorSeperatedData as $vendorData)
        {
            ?>
            <li><a data-toggle="tab" href="#tab<?= $tabCounter; ?>"><?= $vendorData['pageTitle'] ?></a></li>
            <?php $tabCounter++;
        }
        ?>
    </ul>
</div>
<div class="tab-content">
<div class="tab-pane active" id="summary">
    <div class="span9">
        <h3>Summary</h3>

        <p>
            There are <?= count($this->vendorSeperatedData) - 2 ?> toner vendors in the system. Out of the <?= count($this->vendorSeperatedData) ?> Toner Preferences, <?php
            $vendorConfigurationNames = implode(', ', $this->highestNames);
            // Replace last occurrence of a comma to an and
            if (strrpos($vendorConfigurationNames, ',') > 0)
            {
                $vendorConfigurationNames = substr_replace($vendorConfigurationNames, ' and ', strrpos($vendorConfigurationNames, ','), 1);
            }
            echo $vendorConfigurationNames;
            ?> has the highest overall gross margin at <?= $this->highestMargin ?>.
        </p>
        <table class="table">
            <tr>
                <td><strong>Toner Preference</strong></td>
                <td><strong>Overall Gross Margin</strong></td>
            </tr>

            <?php
            $highestMarginArray = [];
            foreach ($this->vendorSeperatedData as $vendorData)
            {
                $vendorOverallMargin = $vendorData['statisticsGroup']['right']['Overall Margin'];
                $vendorName          = $vendorData['pageTitle'];
                ?>
                <tr <?= (in_array($vendorName, $this->highestNames) ? 'style="background-color:#C3FFA6"' : '') ?>>
                    <td><?= $vendorName ?></td>
                    <td><?= $vendorOverallMargin; ?>%</td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>


<?php
$tabCounter = 0;
foreach ($this->vendorSeperatedData as $vendorData)
{
    ?>
    <div class="tab-pane" id="tab<?= $tabCounter; ?>">
        <div class="span9">
            <div>
                <h3 class="reportTitle"><?= $vendorData['pageTitle']; ?></h3>
                <em>AMPV = Average Monthly Page Volume</em>
            </div>

            <br />

            <table id="grossMarginInformation">
                <tbody>
                <tr>
                    <td class="column1">
                        <div class="heading">MPSToolbox.com Monochrome CPP:</div>
                    </td>
                    <td class="column2">
                        <div><?= $vendorData['statisticsGroup']['left']['MPSToolbox.com Monochrome CPP'] ?></div>
                    </td>
                    <td class="column3">
                        <div class="heading">Total Cost:</div>
                    </td>
                    <td class="column4">
                        <div><?= $vendorData['statisticsGroup']['right']['Total Cost'] ?></div>
                    </td>
                </tr>
                <tr>
                    <td class="column1">
                        <div class="heading">MPSToolbox.com Color CPP:</div>
                    </td>
                    <td class="column2">
                        <div><?= $vendorData['statisticsGroup']['left']['MPSToolbox.com Color CPP'] ?></div>
                    </td>
                    <td class="column3">
                        <div class="heading">Total Revenue:</div>
                    </td>
                    <td class="column4">
                        <div><?= $vendorData['statisticsGroup']['right']['Total Revenue'] ?></div>
                    </td>
                </tr>
                <tr>
                    <td class="column1">
                        <div class="heading">Weighted Monochrome CPP:</div>
                    </td>
                    <td class="column2">
                        <div><?= $vendorData['statisticsGroup']['left']['Weighted Monochrome CPP'] ?></div>
                    </td>
                    <td class="column3">
                        <div class="heading">Monthly Profit:</div>
                    </td>
                    <td class="column4">
                        <div><?= $vendorData['statisticsGroup']['right']['Monthly Profit'] ?></div>
                    </td>
                </tr>
                <tr>
                    <td class="column1">
                        <div class="heading">Weighted Color CPP:</div>
                    </td>
                    <td class="column2">
                        <div><?= $vendorData['statisticsGroup']['left']['Weighted Color CPP'] ?></div>
                    </td>
                    <td class="column3">
                        <div class="heading">Overall Margin:</div>
                    </td>
                    <td class="column4">
                        <div><?= $vendorData['statisticsGroup']['right']['Overall Margin'] ?>%</div>
                    </td>
                </tr>
                <tr>
                    <td class="column1">
                        <div class="heading">Monochrome Margin:</div>
                    </td>
                    <td class="column2">
                        <div><?= $vendorData['statisticsGroup']['left']['Monochrome Margin'] ?></div>
                    </td>
                    <td class="column3">
                        <div class="heading">Color Margin:</div>
                    </td>
                    <td class="column4">
                        <div><?= $vendorData['statisticsGroup']['right']['Color Margin'] ?></div>
                    </td>
                </tr>
                </tbody>
            </table>

            <br />

            <div class="center">
                <em class="center">Yellow highlighted rows indicate devices that have not been assigned toners matching your selected first
                    toner vendor
                    preference.<br />
                    For these devices the system has selected the best available alternative based on the current toner preference.</em>
                <br /><br />
            </div>

            <table id="grossMarginDeviceSummary">
                <thead>
                <tr class="center">
                    <th class="column1" rowspan="2">Device Name<br>(IP Address - Serial Number)</th>
                    <th colspan="5">Monochrome</th>
                    <th colspan="5">Color</th>
                </tr>

                <tr class="center">
                    <th class="column2">AMPV</th>
                    <th class="column3">Toner Cost</th>
                    <th class="column4">Toner Yield</th>
                    <th class="column5">CPP</th>
                    <th class="column6">Total Printing Cost</th>
                    <th class="column7">AMPV</th>
                    <th class="column8">Toner Cost</th>
                    <th class="column9">Toner Yield</th>
                    <th class="column10">CPP</th>
                    <th class="column11">Total Printing Cost</th>
                </tr>

                </thead>
                <tbody>
                <?php
                // Display all the data on each device
                foreach ($vendorData['fieldLists'] as $key => $fields)
                {
                    ?>
                    <tr class="<?php echo ($fields['completeMono']) ? "" : "nonCompliantMono" ?> <?php echo ($fields['completeColor']) ? "" : "nonCompliantColor" ?>">
                        <td class=""><?= $fields[0]['deviceName'] ?><br /><?= '(' . $fields[0]['ipAddress'] . ' - ' . $fields[0]['serialNumber'] . ')' ?>
                        </td>
                        <td class="mono"><?= number_format($fields[1], 0) ?></td>
                        <td class="mono">$<?= number_format($fields[2], 2) ?></td>
                        <td class="mono"><?= number_format($fields[3], 0, '.', ',') ?></td>
                        <td class="mono">$<?= number_format($fields[4], 4) ?></td>
                        <td class="mono">$<?= number_format($fields[5], 2) ?></td>
                        <td class="color"><?= (is_numeric($fields[6]) ? number_format($fields[6], 0, '.', ',') : $fields[6]) ?></td>
                        <td class="color"><?= (is_numeric($fields[7]) ? number_format($fields[7], 2) : $fields[7]) ?></td>
                        <td class="color"><?= (is_numeric($fields[8]) ? number_format($fields[8], 0, '.', ',') : $fields[8]) ?></td>
                        <td class="color"><?= (is_numeric($fields[9]) ? number_format($fields[9], 4) : $fields[9]) ?></td>
                        <td class="color"><?= (is_numeric($fields[10]) ? number_format($fields[10], 2) : $fields[10]) ?></td>
                    </tr>
                <?php

                }
                ?>
                <tr class="totals">
                    <td class="column1">
                        <div><?= $vendorData['fieldTotals'][0] ?></div>
                    </td>
                    <td>
                        <div class="right"><?= number_format($vendorData['fieldTotals'][4], 0, '.', ',') ?></div>
                    </td>
                    <td colspan="3"></td>
                    <td class="column2">
                        <div class="right">$<?= number_format($vendorData['fieldTotals'][8], 2) ?></div>
                    </td>
                    <td>
                        <div class="center"><?= number_format($vendorData['fieldTotals'][9], 0, '.', ',') ?></div>
                    </td>
                    <td colspan="3"></td>
                    <td>
                        <div class="right">$<?= number_format($vendorData['fieldTotals'][13], 0) ?></div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <?php $tabCounter++;
}
?>
</div>
</div>