<div class="page-header">
    <h1>Administration</h1>
</div>

<?php if ($this->isAllowed(Admin_Model_Acl::RESOURCE_ADMIN_INDEX_INDEX, Application_Model_Acl::PRIVILEGE_ADMIN)) : ?>
    <h3>System Management</h3>
    <div class="row">
        <?php if ($this->isAllowed(Admin_Model_Acl::RESOURCE_ADMIN_CLIENT_INDEX)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "client", "module" => "admin")); ?>"><i class="icon-star icon-4x"></i><br /><br />
                    System Client Management</a>
            </div>
        <?php endif; ?>

        <?php if ($this->isAllowed(Admin_Model_Acl::RESOURCE_ADMIN_DEALER_INDEX)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "dealer", "module" => "admin")); ?>"><i class="icon-briefcase icon-4x"></i><br /><br />
                    System Dealer Management</a>
            </div>
        <?php endif; ?>

        <?php if ($this->isAllowed(Admin_Model_Acl::RESOURCE_ADMIN_USER_INDEX)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "user", "module" => "admin")); ?>"><i class="icon-group icon-4x"></i><br /><br />
                    System User Management</a>
            </div>
        <?php endif; ?>

        <?php if ($this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_ADMIN_MANAGEMATCHUPS)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "managematchups", "controller" => "admin", "module" => "proposalgen")); ?>"><i class="icon-bar-chart icon-4x"></i><br /><br />
                    Manage Master Matchups</a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Admin_Model_Acl::RESOURCE_ADMIN_MEMJETDEVICESWAPS_INDEX)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "memjetdeviceswaps", "module" => "admin")); ?>"><i class="icon-exchange icon-4x"></i><br /><br />
                    Manage Memjet Device Swaps</a>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if ($this->isAllowed(Quotegen_Model_Acl::RESOURCE_QUOTEGEN_DEVICESETUP_INDEX)
          || $this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_COSTS_BULKDEVICEPRICING)
          || $this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_ADMIN_MANAGEREPLACEMENTS)
          || $this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_ADMIN_MANAGEREPLACEMENTS)
) : ?>
    <h3>Device Management</h3>
    <div class="row">
        <?php if ($this->isAllowed(Quotegen_Model_Acl::RESOURCE_QUOTEGEN_DEVICESETUP_INDEX)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "devicesetup", "module" => "quotegen")); ?>"><i class="icon-print icon-4x"></i><br /><br />
                    All Devices<br /><br /> </a>
            </div>
        <?php endif; ?>

        <?php if ($this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_COSTS_BULKDEVICEPRICING)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "bulkdevicepricing", "controller" => "costs", "module" => "proposalgen")); ?>"><i class="icon-upload-alt icon-4x"></i><br /><br />
                    Bulk Hardware / <br />Pricing Updates <br /> </a>
            </div>
        <?php endif; ?>

        <?php if ($this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_ADMIN_MANAGEREPLACEMENTS)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "deviceswaps", "module" => "hardwareoptimization")); ?>"><i class="icon-print icon-4x"></i><br /><br />
                    Manage Device <br /> Swaps <br /> </a>
            </div>
        <?php endif; ?>
    </div>

<?php endif; ?>
<?php if ($this->isAllowed(Dealermanagement_Model_Acl::RESOURCE_DEALERMANAGEMENT_CLIENT_INDEX)
          || $this->isAllowed(Dealermanagement_Model_Acl::RESOURCE_DEALERMANAGEMENT_LEASINGSCHEMA_WILDCARD)
          || $this->isAllowed(Dealermanagement_Model_Acl::RESOURCE_DEALERMANAGEMENT_USER_WILDCARD)
          || $this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_ADMIN_SAVEANDAPPROVE)
) : ?>
    <h3>Account Management</h3>
    <div class="row">
        <?php if ($this->isAllowed(Dealermanagement_Model_Acl::RESOURCE_DEALERMANAGEMENT_CLIENT_INDEX)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "client", "module" => "dealermanagement")); ?>"><i class="icon-star icon-4x"></i><br /><br />
                    Clients<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Dealermanagement_Model_Acl::RESOURCE_DEALERMANAGEMENT_LEASINGSCHEMA_WILDCARD)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "leasingschema", "module" => "dealermanagement")); ?>"><i class="icon-money icon-4x"></i><br /><br />
                    Lease Rates<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Dealermanagement_Model_Acl::RESOURCE_DEALERMANAGEMENT_USER_WILDCARD)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "user", "module" => "dealermanagement")); ?>"><i class="icon-group icon-4x"></i><br /><br />
                    Users<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_MANUFACTURER_CREATE)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "index", "controller" => "manufacturer", "module" => "proposalgen")); ?>"><i class="icon-print icon-4x"></i><br /><br />
                    Manufacturers<br /><br /></a>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_INDEX_USER)) : ?>
    <h3>My Settings</h3>
    <div class="row">
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_PROPOSAL_USER)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "user", "controller" => "proposal", "module" => "preferences")); ?>"><i class="icon-star icon-4x"></i><br /><br />
                    Assessment<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_QUOTE_USER)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "user", "controller" => "quote", "module" => "preferences")); ?>"><i class="icon-money icon-4x"></i><br /><br />
                    Quote<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_HEALTHCHECK_USER)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "user", "controller" => "healthcheck", "module" => "preferences")); ?>"><i class="icon-medkit icon-4x"></i><br /><br />
                    Health Check<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_HARDWAREOPTIMIZATION_USER)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "user", "controller" => "hardwareoptimization", "module" => "preferences")); ?>"><i class="icon-dashboard icon-4x"></i><br />
                    Hardware Optimization<br /><br /></a>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_INDEX_DEALER)) : ?>
    <h3>Dealer Settings</h3>
    <div class="row">
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_PROPOSAL_DEALER)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "dealer", "controller" => "proposal", "module" => "preferences")); ?>"><i class="icon-star icon-4x"></i><br /><br />
                    Assessment<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_QUOTE_DEALER)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "dealer", "controller" => "quote", "module" => "preferences")); ?>"><i class="icon-money icon-4x"></i><br /><br />
                    Quote<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_HEALTHCHECK_DEALER)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "dealer", "controller" => "healthcheck", "module" => "preferences")); ?>"><i class="icon-medkit icon-4x"></i><br /><br />
                    Health Check<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_HARDWAREOPTIMIZATION_DEALER)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "dealer", "controller" => "hardwareoptimization", "module" => "preferences")); ?>"><i class="icon-dashboard icon-4x"></i><br />
                    Hardware Optimization<br /><br /></a>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_INDEX_SYSTEM)) : ?>
    <h3>System Settings</h3>
    <div class="row">
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_PROPOSAL_SYSTEM)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "system", "controller" => "proposal", "module" => "preferences")); ?>"><i class="icon-star icon-4x"></i><br /><br />
                    Assessment<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_QUOTE_SYSTEM)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "system", "controller" => "quote", "module" => "preferences")); ?>"><i class="icon-money icon-4x"></i><br /><br />
                    Quote<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_HEALTHCHECK_SYSTEM)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "system", "controller" => "healthcheck", "module" => "preferences")); ?>"><i class="icon-medkit icon-4x"></i><br /><br />
                    Health Check<br /><br /></a>
            </div>
        <?php endif; ?>
        <?php if ($this->isAllowed(Preferences_Model_Acl::RESOURCE_PREFERENCES_HARDWAREOPTIMIZATION_SYSTEM)) : ?>
            <div class="span2">
                <a class="btn btn-block" href="<?php echo $this->url(array("action" => "system", "controller" => "hardwareoptimization", "module" => "preferences")); ?>"><i class="icon-dashboard icon-4x"></i><br />
                    Hardware Optimization<br /><br /></a>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>