<?php 
$leasingSchemaTerms = $this->leasingSchemaTerms;
?>
<form name="leasingSchemaTerm" id="leasingSchemaTerm" class="form-horizontal" action="<?php echo $this->element->getAction() ?>" method="<?php echo $this->element->getMethod() ?>">
	<?php echo $this->element->getElement("hdnId")->renderViewHelper(); ?>
	
	<div class="control-group">
		<label class="control-label pull-left" for="range">Range Value: </label>
		<div class="controls">
			<div class="input-prepend input-append">
				<?php if ( $this->element->getElement("range")->hasErrors() ) { 
					$this->element->getElement("range")->setAttrib('style', 'border-color: #B94A48; color: #B94A48;');
				} ?>
				<span class="add-on">$</span><?php echo $this->element->getElement("range")->renderViewHelper(); ?>
			</div>
		</div>
	</div>
	
	<div class="controls" style="overflow: auto; overflow-y: hidden; -ms-overflow-y: hidden; margin: 20px 0px 0px 0px;">
		<table class="table table-stripped table-bordered" style="width: auto;">
			<thead>
				<tr>
					<th style="text-align: left;">Term</th>
					<th style="text-align: center;">Rate</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ( $leasingSchemaTerms as $term ) { ?>
				<tr>
					<td style="text-align: left;"><?php echo $term->getMonths(); ?></td>
					<td style="text-align: center;">
						<?php if ( $this->element->getElement("rate{$term->getId()}")->hasErrors() ) { 
							$this->element->getElement("rate{$term->getId()}")->setAttrib('style', 'border-color: #B94A48; color: #B94A48;');
						} ?> 
						<?php echo $this->element->getElement("rate{$term->getId()}")->renderViewHelper(); ?>
					</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
	
	<div>
		<?php echo $this->element->submit; ?>
		<?php echo $this->element->cancel; ?>
	</div>

</form>
