<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->healthcheck->proposal;
?>
<div class="h1">Fleet Attributes</div>
<p>The following provides a summary of your existing printing devices.</p>
<p>Leased devices are shown in gray.</p>
<div class="pheader">Optimized Devices - No Changes Necessary</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
        <tr>
            <th style="width: 170px;vertical-align: middle">Device Name</th>
            <th style="width: 51px;vertical-align: middle" class="center">Device Age (Years)</th>
            <th style="width: 51px;vertical-align: middle" class="center">Monthly Page Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Total Page Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Monthly Cost</th>
            <th style="width: 51px;vertical-align: middle" class="center">Office Depot™ ATR Compatible</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($proposal->getOptimizedDevices() as $deviceInstance): ?>
            <?php
            $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
            $monthlyRate = 0;
            if ($deviceInstance->getIsLeased())
            {
                $monthlyRate = $deviceInstance->getLeasedMonthlyRatePercentage($proposal->report->getReportSettings()->monthlyLeasePayment, $proposal->getLeasedBlackAndWhiteCharge(), $proposal->getLeasedColorCharge(), $proposal->calculateTotalMonthlyCost());
                echo ' shaded';
            }
            else
            {
                $monthlyRate = $deviceInstance->getMonthlyRatePercentage($proposal->calculateTotalMonthlyCost());
            }
            ?>">
            <td><?php echo $deviceName?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAverageMonthlyPageCount(), 0) ?></td>
            <td class="center"><?php echo number_format(($deviceInstance->getAverageMonthlyPageCount() / $proposal->getPageCounts()->Total->Combined->Monthly) * 100, 2) ?>
                %</td>
            <td><?php echo number_format($monthlyRate, 2) ?>
                %</td>
            <td class="center"><?php if ($deviceInstance->getIsLeased())
            {
                echo 'N';
            }
            else
            {
                echo ($deviceInstance->reportsTonerLevels == 1 ? 'Y' : 'N');
            }?></td>
        </tr>
            <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Underutilized Devices</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
        <tr>
            <th style="width: 30px;vertical-align: middle">Device Name</th>
            <th style="width: 51px;vertical-align: middle" class="center">Device Age (Years)</th>
            <th style="width: 51px;vertical-align: middle" class="center">Monthly Page Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Recommended Max. Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Total Page Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Monthly Cost</th>
            <th style="width: 51px;vertical-align: middle" class="center">Office Depot™ ATR Compatible</th>
            <th style="vertical-align: middle" class="center">Suggested Action</th>
        </tr>
    </thead>
    <tbody>
        <?php

        foreach ($proposal->getUnderutilizedDevices() as $deviceInstance):
            ?>
            <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
            if ($deviceInstance->getIsLeased())
            {
                echo ' shaded';
            }?>">
            <td><?php echo $deviceName?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAverageMonthlyPageCount(), 0) ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getMasterDevice()->getMaximumMonthlyPageVolume(), 0) ?></td>
            <td class="center"><?php echo number_format(($deviceInstance->getAverageMonthlyPageCount() / $proposal->getPageCounts()->Total->Combined->Monthly) * 100, 2) ?>
                %</td>
            <td><?php echo number_format(($deviceInstance->getMonthlyRate() / ($proposal->getTotalPurchasedAnnualCost() / 12)) * 100, 2) ?>%</td>
            <td class="center"><?php if ($deviceInstance->getIsLeased())
            {
                echo 'N';
            }
            else
            {
                echo ($deviceInstance->reportsTonerLevels == 1 ? 'Y' : 'N');
            }?></td>
            <td>Migrate all page volume to ATR compatible device.</td>
        </tr>
            <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Overutilized Devices</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
        <tr>
            <th style="width: 170px;vertical-align: middle">Device Name</th>
            <th style="width: 51px;vertical-align: middle" class="center">Device Age (Years)</th>
            <th style="width: 51px;vertical-align: middle" class="center">Monthly Page Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Recommended Max. Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Total Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Monthly Cost</th>
            <th style="width: 51px;vertical-align: middle" class="center">Office Depot™ ATR Compatible</th>
            <th style="width: 220px;vertical-align: middle" class="center">Suggested Action</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($proposal->getOverutilizedDevices() as $deviceInstance):
            ?>
            <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
            if ($deviceInstance->getIsLeased())
            {
                echo ' shaded';
            }?>">
            <td><?php echo $deviceName?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAverageMonthlyPageCount(), 0) ?></td>
                            <td class="center"><?php echo number_format($deviceInstance->getMasterDevice()->getMaximumMonthlyPageVolume(), 0) ?></td>
            <td class="center"><?php echo number_format(($deviceInstance->getAverageMonthlyPageCount() / $proposal->getPageCounts()->Total->Combined->Monthly) * 100, 2) ?>
                %</td>
            <td><?php echo number_format(($deviceInstance->getMonthlyRate() / ($proposal->getTotalPurchasedAnnualCost() / 12)) * 100, 2) ?>%</td>
            <td class="center"><?php if ($deviceInstance->getIsLeased())
            {
                echo 'N';
            }
            else
            {
                echo ($deviceInstance->reportsTonerLevels == 1 ? 'Y' : 'N');
            }?></td>
            <td>Migrate excess page volume to an ATR compatible device.</td>
        </tr>
            <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Old Devices</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
        <tr>
            <th style="width: 170px;vertical-align: middle">Device Name</th>
            <th style="width: 51px;vertical-align: middle" class="center">Device Age (Years)</th>
            <th style="width: 51px;vertical-align: middle" class="center">Monthly Page Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Total Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Monthly Cost</th>
            <th style="width: 51px;vertical-align: middle" class="center">Office Depot™ ATR Compatible</th>
            <th style="width: 220px;vertical-align: middle" class="center">Suggested Action</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($proposal->getOldDevices() as $deviceInstance): ?>
            <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
            if ($deviceInstance->getIsLeased())
            {
                echo ' shaded';
            }?>">
            <td><?php echo $deviceName?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAverageMonthlyPageCount(), 0) ?></td>
            <td class="center"><?php echo number_format(($deviceInstance->getAverageMonthlyPageCount() / $proposal->getPageCounts()->Total->Combined->Monthly) * 100, 2) ?>
                %</td>
            <td><?php echo number_format(($deviceInstance->getMonthlyRate() / ($proposal->getTotalPurchasedAnnualCost() / 12)) * 100, 2) ?>%</td>
            <td class="center"><?php if ($deviceInstance->getIsLeased())
            {
                echo 'N';
            }
            else
            {
                echo ($deviceInstance->reportsTonerLevels == 1 ? 'Y' : 'N');
            }?></td>
            <td>Migrate all page volume to a newer ATR compatible device.</td>
        </tr>
            <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Devices Not Reporting Toner Levels</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
        <tr>
            <th style="width: 170px;vertical-align: middle">Device Name</th>
            <th style="width: 51px;vertical-align: middle" class="center">Device Age (Years)</th>
            <th style="width: 51px;vertical-align: middle" class="center">Monthly Page Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Total Volume</th>
            <th style="width: 51px;vertical-align: middle" class="center">Percent of Monthly Cost</th>
            <th style="width: 51px;vertical-align: middle" class="center">Office Depot™ ATR Compatible</th>
            <th style="width: 220px;vertical-align: middle" class="center">Suggested Action</th>
        </tr>
    </thead>
    <tbody>
        <?php /** FIXME  Devices Not Reporting Toner Levels*/
        foreach ($proposal->getDevicesNotReportingTonerLevels() as $deviceInstance):
            if ($deviceInstance->getIsLeased() == false)
            {
                ?>
                <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
            <tr class="<?php
                if ($deviceInstance->getIsLeased())
                {
                    echo ' shaded';
                }?>">
            <td><?php echo $deviceName?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="center"><?php echo number_format($deviceInstance->getAverageMonthlyPageCount(), 0) ?></td>
            <td class="center"><?php echo number_format(($deviceInstance->getAverageMonthlyPageCount() / $proposal->getPageCounts()->Total->Combined->Monthly) * 100, 2) ?>
                %</td>
            <td><?php echo number_format(($deviceInstance->getMonthlyRate() / ($proposal->getTotalPurchasedAnnualCost() / 12)) * 100, 2) ?>%</td>
            <td class="center"><?php if ($deviceInstance->getIsLeased())
            {
                echo 'N';
            }
            else
            {
                echo ($deviceInstance->reportsTonerLevels == 1 ? 'Y' : 'N');
            }?></td>
            <td>Migrate all page volume to ATR compatible device.</td>
        </tr>
                <?php } endforeach; ?>
    </tbody>
</table>