<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
?>
<div class="h1">Next Steps</div>
<ol>
    <li>Financial: Review your toner usage and costs, and whether you can switch any of your OEM toners to Office Depot’s compatible toners.</li>
    <li>Environmental: Review how many pages you are printing on both sides of the page, and consider how much you could decrease your environmental impact by printing more on both sides.</li>
    <li>Hardware Usage: Review your devices to see where some of your page volumes could be shifted to other devices, and which devices could be replaced or removed from your fleet.</li>
    <li>MPS: Consider a managed print program that will allow your printing devices to be remotely managed with a set cost per page, saving you time and money and allowing you to focus more on your business.</li>
</ol>
<p>Whether you are looking for a comprehensive managed print services plan that includes new equipment, or are looking for assistance in maintaining your existing printer fleet, we can design a solution that meets your specific business needs. Let us take care of your print so you can get back to business.</p>
<p><strong>1-855-OD-GO-MPS</strong></p>
<p>1-855-634-6677</p>
<p>© 2013 Office Depot, Inc. All Rights Reserved.</p>
<p>The Office Depot name and logo are the registered trademarks of The Office Club, Inc.</p>