<?php

use MPSToolbox\Legacy\Models\Acl\AppAclModel;
use MPSToolbox\Legacy\Models\Acl\DealerManagementAclModel;
use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\ClientModel;

?>
<div class="container">
    <div class="clearfix">
        <a class="btn btn-success pull-right btn-sm create-button" href="<?= $this->url([], 'company.clients.create') ?>">
            <i class="glyphicon glyphicon-plus-sign"></i> Create new</a>
    </div>
    <?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
        <table class="table table-striped table-condensed table-bordered">
            <thead>
            <tr>
                <th style="width: 30px;">ID</th>
                <th>Company Name</th>
                <th>Legal Name</th>
                <th style="width: 120px;">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $client ClientModel */ ?>
            <?php foreach ($this->paginator->getCurrentItems() as $client) : ?>
                <tr>
                    <td><?= $this->escape($client->id); ?></td>
                    <td><?= $this->escape($client->companyName); ?></td>
                    <td><?= $this->escape($client->legalName); ?></td>
                    <td>
                        <div class="btn-group btn-group-justified">
                            <a class="btn btn-xs btn-info" title="View" href="<?= $this->url(['id' => $client->id], 'company.clients.view'); ?>">
                                <i class="glyphicon glyphicon-eye-open"></i>
                            </a>
                            <a class="btn btn-xs btn-warning" title="Edit" href="<?= $this->url(['id' => $client->id], 'company.clients.edit'); ?>">
                                <i class="glyphicon glyphicon-pencil"></i>
                            </a>
                            <?php if ($this->IsAllowed(DealerManagementAclModel::RESOURCE_DEALERMANAGEMENT_CLIENT_DELETE, AppAclModel::PRIVILEGE_VIEW)): ?>
                                <a class="btn btn-xs btn-danger" title="Delete" href="<?= $this->url(['id' => $client->id], 'company.clients.delete'); ?>">
                                    <i class="glyphicon glyphicon-trash"></i>
                                </a>
                            <?php endif; ?>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?= $this->paginationControl($this->paginator); ?>
    <?php else : ?>
        <div class='well'>
            <h1>There are no clients</h1>
        </div>
    <?php endif; ?>
</div>