<div class="page-header">
    <h1>Clients -
        <small>Client Management</small>
    </h1>
</div>
<div class="clearfix">
    <a class="btn btn-success pull-right btn-small create-button" href="<?php echo $this->url(array('action' => 'create')) ?>">
        <i class="icon-white icon-plus-sign"></i> Create new</a>
</div>
<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
    <table class="table table-striped table-condensed table-bordered">
        <thead>
        <tr>
            <th style="width: 30px;">ID</th>
            <th>Company Name</th>
            <th>Legal Name</th>
            <th style="width: 120px;">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($this->paginator->getCurrentItems() as $client) : /* @var $client Quotegen_Model_Client */ ?>
            <tr>
                <td><?php echo $this->escape($client->id); ?></td>
                <td><?php echo $this->escape($client->companyName); ?></td>
                <td><?php echo $this->escape($client->legalName); ?></td>
                <td>
                    <div class="btn-group">
                        <?php $canDelete = $this->IsAllowed(Dealermanagement_Model_Acl::RESOURCE_DEALERMANAGEMENT_CLIENT_DELETE, Application_Model_Acl::PRIVILEGE_VIEW);
                        $width = 35;
                        if($canDelete)
                        {
                            $width = 13;
                        }
                        ?>
                        <a class="btn btn-info" title="View" style="width:<?php echo $width; ?>px" href="<?php echo $this->url(array('action' => 'view', 'id' => $client->id)); ?>"><i class="icon-eye-open"></i></a>
                        <a class="btn btn-warning" title="Edit" style="width:<?php echo $width; ?>px" href="<?php echo $this->url(array('action' => 'edit', 'id' => $client->id)); ?>"><i class="icon-pencil"></i></a>
                        <?php
                        if($canDelete)
                        {
                            ?>
                        <a class="btn btn-danger" title = "Delete" href = "<?php echo $this->url(array ( 'action' => 'delete', 'id' => $client->id)); ?>" ><i class="icon-trash" ></i ></a >
                        <?php
                            }
                        ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
    <div class='well'>
        <h1>There are no clients</h1>
    </div>
<?php endif; ?>

