<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\ClientModel;

/* @var $client ClientModel */
$client  = $this->client;
$contact = $client->getContact();
$address = $client->getAddress();
?>
<div class="container">
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd><?= $client->companyName; ?></dd>
        <dt>Legal Name</dt>
        <dd><?= nl2br($client->legalName) . '&nbsp'; ?></dd>
        <dt>Country</dt>
        <dd><?= nl2br($address->getCountry()); ?></dd>
        <dt>State or Province</dt>
        <dd><?= nl2br($address->region); ?></dd>
        <dt>City</dt>
        <dd><?= nl2br($address->city); ?></dd>
        <dt>Address 1</dt>
        <dd><?= nl2br($address->addressLine1); ?></dd>
        <dt>Address 2</dt>
        <dd><?= nl2br($address->addressLine2) . '&nbsp'; ?></dd>
        <dt>Zip or Postal Code</dt>
        <dd><?= nl2br($address->postCode); ?></dd>
        <dt>Contact First Name</dt>
        <dd><?= nl2br(isset($contact->firstName) ? $contact->firstName : '') . '&nbsp'; ?></dd>
        <dt>Contact Last Name</dt>
        <dd><?= nl2br(isset($contact->lastName) ? $contact->lastName : '') . '&nbsp'; ?></dd>
        <dt>Phone Number</dt>
        <dd><?= (isset($contact->areaCode)) ? nl2br("+" . $contact->countryCode . "(" . $contact->areaCode . ")" . $contact->exchangeCode . "-" . $contact->number . ($contact->extension ? " Ext {$contact->extension}" : '')) : '' ?></dd>
    </dl>
</div>