<?php if ($this->pageCount): ?>
    <div class="pagination">
        <ul>
        <?php if (isset($this->previous)): ?>
            <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>">Prev</a></li>
        <?php else: ?>
            <li class="disabled"><a href="#">Prev</a></li>
        <?php endif; ?>

        
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
            <?php else: ?>
                <li class="active"><a href="#"><?php echo $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>

        
        <?php if (isset($this->next)): ?>
            <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">Next</a></li>
        <?php else: ?>
            <li class="disabled"><a href="#">Next</a></li>
        <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>