<div class="well">
    <h4>Purchase Price</h4>
    <p>$100,000.99</p>
    <h4>Lease Rate (84 Months)</h4>
    <p>$50,999.36/month</p>
    
    <ul>
        <li>104 Devices</li>
        <li>104 Devices</li>
        <li>104 Devices</li>
        <li>104 Devices</li>
        <li>104 Devices</li>
        <li>104 Devices</li>
        <li>104 Devices</li>
    </ul>
    
    <p>Lorem Ipsum. Some text goes here. Paragraphs of text are fun to write. Printers and devices with scan fax and duplex capabilities are the best! Hewlett-packard devices, Konica Minolta devices, Xerox devices, you name it we sell it.</p>
</div>
