<?php
/**
 * Assessment Title Page
 */
/* @var $phpword PHPWord */
$phpword = $this->phpword;
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;

/* @var $section PHPWord_Section */
$section = $this->section;

// Table to get the images working properly
$table = $section->addTable();
$table->addRow();
$cell = $table->addCell(3209);
$cell->addImage(PUBLIC_PATH . "/assets/images/docx/assessment/cell1.jpg");
$cell = $table->addCell(5818);
$cell->addTextBreak(3);
$cell->addImage(PUBLIC_PATH . "/assets/images/docx/assessment/cell2.jpg");
$cell->addTextBreak(5);
$cell->addText($this->translate('Prepared For:') . " " . $proposal->report->_customerCompanyName, 'titlepageHeaderFont', 'titlepageHeaderParagraph');
$cell->addText($proposal->getDateReportPrepared(), 'titlepageHeaderFont', 'titlepageHeaderParagraph');
$cell->addTextBreak(4);
// Parse the address
$addressLines = explode("\n", $proposal->CustomerAddress);
foreach ( $addressLines as $line )
{
    $cell->addText($line, null, 'nospacing');
}