<?php
/**
 * Assessment - Report Card
 */

/* @var $phpword PHPWord */
$phpword = $this->phpword;

/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;

$section->addTitle(sprintf($this->translate('Your %1$s Smart Assessment'), $this->brandName), 1);
$section->addText(sprintf($this->translate('It can be a challenge to understand your printing needs, and there are many factors to consider: hardware functionality, supplies delivery, service, parts, maintenance kits, IT time spent supporting printers -- and the cost for all of this. This free %1$s Smart Assessment will allow you to make sense of your printing needs and costs. %2$s can help you get your office print under control with our smart and flexible managed print services solutions.'), $this->brandName, $this->companyName));

$section->addTitle($this->translate('Score Card'), 2);
$section->addText($this->translate('Your office printing environment was graded across five categories on a scale of 1 to 10. A score of 1 indicates a low-efficiency or high-cost scenario. A score of 10 indicates a high-efficiency or low-cost scenario. Your results are below:'));

$reportCardTable = $section->addTable($this->styles->tables->grades->tablestyle);
$rowHeight = 800;
// Row 1
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText($this->translate('Supplies and Service Logistics'), 'gradeTitleFont', 'nospacing');
$cell->addText($this->translate('Management breakdown, efficiency of break-fix service, number of vendors used for print, and number of different models and associated supply types.'), null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($proposal->getRanking()->SuppliesAndServiceLogistics->Rank, 1), 'gradeFont', 'gradeParagraph');

// Row 2
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText($this->translate('Printing Hardware Usage'), 'gradeTitleFont', 'nospacing');
$cell->addText($this->translate('Total number of printing devices, average print volumes, underused and overused equipment, and color print usage.'), null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($proposal->getRanking()->PrintingHardwareUsage->Rank, 1), 'gradeFont', 'gradeParagraph');

// Row 3
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText($this->translate('Technology Reliability and User Productivity'), 'gradeTitleFont', 'nospacing');
$cell->addText($this->translate('Age of printing devices, IT time spent managing printers, and availability of technology features that improve workflow and productivity.'), null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($proposal->getRanking()->TechnologyReliabilityAndUserProductivity->Rank, 1), 'gradeFont', 'gradeParagraph');

// Row 4
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText($this->translate('Environmental Impact'), 'gradeTitleFont', 'nospacing');
$cell->addText($this->translate('Energy consumption from printing hardware and availability of green print technology features.'), null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($proposal->getRanking()->EnvironmentalFriendliness->Rank, 1), 'gradeFont', 'gradeParagraph');

// Row 5
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText($this->translate('Expense'), 'gradeTitleFont', 'nospacing');
$cell->addText($this->translate('Your estimated annual expenses for print-related hardware, supplies, service, and internal support and administration.'), null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($proposal->getRanking()->Expense->Rank, 1), 'gradeFont', 'gradeParagraph');

// Textbreak fix to ensure the tables don't merge into each other
$section->addTextBreak();

$imageTable = $section->addTable();
$imageTable->addRow();
$cell = $imageTable->addCell(9028, $this->styles->tables->singleimage->cell1);
$graphs = $proposal->getGraphs();
$cell->addImage($graphs[0]);

// Textbreak fix to ensure the tables don't merge into each other
$section->addTextBreak();
$savingsTable = $section->addTable($this->styles->tables->savings->tablestyle);
$savingsTable->addRow(720);
$cell = $savingsTable->addCell(9028, $this->styles->tables->savings->cell1);

$textrun = $cell->createTextRun('savingsParagraph');
$textrun->addText(sprintf($this->translate('Our %1$s program could provide you with annual savings of up to '), $this->brandName), 'savingsFont');
$textrun->addText('$' . number_format($proposal->getPrintIQSavings()), 'savingsAmountFont');
$textrun->addText('.', 'savingsFont');
