<?php 
/* @var $form Healthcheck_Form_Healthcheck_Settings */
$form = $this->element;
?>
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
    <div class="row">
        <div class="span10 offset1">
            <div class="well">
        <?php foreach ($form->getFormElementGroups() as $group) : ?>
            <h3><?php echo $group->title; ?></h3>
            <hr>
            <table style="width: 100%;">
                <tr>
                    <th style="width: 300px; text-align: left;">Property</th>
                    <th style="text-align: left;">Default</th>
                    <th style="width: 150px; text-align: right;">Value</th>
                    <th style="width: 75px;"></th>
                </tr>
            <?php foreach ($group->elements as $element) :
                $inputPrepend = (strlen($element->getAttrib('inputprepend')) > 0) ? $element->getAttrib('inputprepend') : FALSE;
                $inputAppend = (strlen($element->getAttrib('inputappend')) > 0) ? $element->getAttrib('inputappend') : FALSE;
                $append = (strlen($element->getAttrib('append')) > 0) ? $element->getAttrib('append') : FALSE;
            ?>
                <tr style="height: 50px;">
                    <td><?php echo $element->getLabel(); ?></td>
                    <td><?php echo ($inputPrepend) ?: ""; ?><?php echo $element->getAttrib('data-defaultvalue'); ?><?php echo ($inputAppend) ?: ""; ?></td>
                    <td style="text-align: right;"><?php echo ($inputPrepend) ?: ""; ?><?php
                    if ($element instanceof ZendX_JQuery_Form_Element_UiWidget)
                    { 
                        // Well this work around isn't so great, but it's necessary.
                        echo $element->renderUiWidgetElement();
                    }
                    else
                    {
                        echo $element->renderViewHelper();
                        
                    } 
                    ?></td>
                    <td style="padding-left: 5px;"><?php echo ($inputAppend . $append) ?: ""; ?></td>
                </tr>
                <?php if ($element->hasErrors()) : ?>
                <tr>
                    <td colspan="4" style="text-align: right;"><div class="control-group error"><?php echo $element->renderErrors(); ?></div></td>
                </tr>
                <?php endif; ?>
                
            <?php endforeach; ?>
            </table>
            <br><br>
        <?php endforeach; ?>
        
            <?php echo $form->getDisplayGroup('actions'); ?>

        
            </div>
        </div>
    </div>
</form>