<?php
/* @var $form Healthcheck_Form_Healthcheck_Settings */
$form = $this->element;
$tonerVendorElements = array('customerMonochromeRankSetArray' => 'Monochrome Toner Preference', 'customerColorRankSetArray' => 'Color Toner Preference');
?>
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">

    <div class="well">
        <?php foreach ($form->getFormElementGroups() as $group) : ?>
            <h3><?php echo $group->title; ?></h3>
            <table style="width: 100%;">
                <tr style="height: 50px;">
                    <th style="width: 375px; padding-left: 20px; text-align: left;">Property</th>
                    <th style="text-align: left;">Default</th>
                    <th style="width: 125px; text-align: right; padding-right:40px;">Value</th>
                </tr>
                <?php /* @var $element Zend_Form_Element_Text */ ?>
                <?php foreach ($group->elements as $element) :
                    // We want to render the multi selects differently
                    if (!array_key_exists($element->getName(), $tonerVendorElements)) :
                        $inputPrepend = (strlen($element->getAttrib('inputprepend')) > 0) ? $element->getAttrib('inputprepend') : false;
                        $inputAppend  = (strlen($element->getAttrib('inputappend')) > 0) ? $element->getAttrib('inputappend') : false;
                        $append       = (strlen($element->getAttrib('append')) > 0) ? $element->getAttrib('append') : false;
                        ?>
                        <tr style="height: 50px;">
                            <td style="padding-left: 20px;"><?php echo $element->getLabel(); ?></td>
                            <td><?php echo ($inputPrepend) ? : ""; ?><?php echo $element->getAttrib('data-defaultvalue'); ?><?php echo ($inputAppend) ? : ""; ?></td>
                            <td style="text-align: right;">
                                <?php if ($element instanceof ZendX_JQuery_Form_Element_UiWidget) : ?>
                                    <div class='control-group '>
                                        <div class='controls'>
                                            <div class='input-append'>
                                                <?php echo $element->renderUiWidgetElement(); ?>
                                                <span class='add-on' style="width: 65px;"><?php echo $inputPrepend . ' ' . $inputAppend; ?></span>;
                                            </div>
                                        </div>
                                    </div>
                                <?php
                                else :
                                    $errors = ($element->hasErrors()) ? 'error' : null;
                                    ?>
                                    <div class='control-group <?php echo $errors; ?>'>
                                        <div class='controls'>
                                            <div class='input-append'>
                                                <?php echo $element->renderViewHelper(); ?>
                                                <span class='add-on' style="width: 65px;"><?php echo $inputPrepend . ' ' . $inputAppend; ?></span>;
                                            </div>
                                            <?php foreach ($element->getMessages() as $key => $errorMessages) : ?>
                                                <span class='help-inline'> <?php echo $errorMessages; ?> </span>
                                            <?php endforeach; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php else: ?>
                        <tr>
                            <td style="padding-left: 20px; height: 50px;">
                                <?php echo $tonerVendorElements[$element->getName()] ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan='3' style="padding-left: 20px">
                                <?php echo $element->renderViewHelper(); ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan='3' style="height:15px;padding-left: 20px">
                                <em>OEM toners will be used by default</em>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </table>

        <?php endforeach; ?>
        <?php echo $form->getDisplayGroup('actions'); ?>
    </div>
</form>