<?php
/* @var $form ImportLeaseCsvForm */
use MPSToolbox\Legacy\Modules\DealerManagement\Forms\ImportLeaseCsvForm;

$form = $this->element;
?>

<?= $this->RenderFormOpen($form, array('form-horizontal')) ?>
<fieldset>
    <div class="form-group col-md-10 <?= ($form->getElement('uploadFile')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('uploadFile'), array()) ?>

        <div class="col-md-12">
            <?= $this->RenderFormFile($form->getElement('uploadFile')) ?>
            <?= $this->RenderFormDescription($form->getElement('uploadFile')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('uploadFile')) ?>
        </div>
    </div>
</fieldset>
<fieldset>
    <hr>
    <?= $this->RenderFormSubmit($form->getElement('performUpload'), array('btn', 'btn-primary')) ?>
    <?= $this->RenderFormSubmit($form->getElement('cancel'), array('btn', 'btn-default')) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>
