<?php
/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optmizationViewModel;
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareoptimization;
?>

<!-- Begin target cost per page table-->
<table class="table">
    <tbody>
    <tr>
        <td>
            <strong>Target Monochrome CPP
                : </strong><?php echo $this->formatCostPerPage($hardwareOptimization->getHardwareOptimizationSetting()->targetMonochromeCostPerPage); ?>
        </td>
        <td>
            <strong>Target Color CPP
                : </strong><?php echo $this->formatCostPerPage($hardwareOptimization->getHardwareOptimizationSetting()->targetColorCostPerPage); ?>
        </td>
        <td>
            <strong>Cost Threshold : </strong><?php echo $this->currency((float)$hardwareOptimization->getHardwareOptimizationSetting()->costThreshold); ?>
        </td>
        <td><strong>Total
                Revenue: </strong><?php echo $this->currency((float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()) ?>
        </td>
    </tr>
    </tbody>
</table>
<!-- End target cost per page table -->

<table class='table table-condensed' style="width: 100%">
    <thead>
    <tr class='header'>
        <td><strong>Fleet</strong></td>
        <td><strong>Weighted Monochrome CPP</strong></td>
        <td><strong>Weighted Color CPP</strong></td>
        <td><strong>Total Cost</strong></td>
        <td><strong>Margin $</strong></td>
        <td><strong>Margin %</strong></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td> Current</td>
        <td><?php echo $this->formatCostPerPage($optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage); ?></td>
        <td><?php echo ($optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage > 0) ? $this->formatCostPerPage($optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage) : 'N/A'; ?></td>
        <td><?php echo $this->currency($optimization->calculateDealerMonthlyCost()); ?></td>
        <td><?php echo $this->currency($optimization->calculateDealerMonthlyProfitUsingTargetCostPerPage()); ?></td>
        <td><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCost(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2); ?>%</td>
    </tr>
    <tr>
        <td> Optimized</td>
        <td id="monochromeCpp"><?php echo $this->formatCostPerPage($optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->monochromeCostPerPage) ?></td>
        <td id="colorCpp"><?php echo ((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage > 0) ? $this->formatCostPerPage($optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage) : 'N/A'; ?></td>
        <td id="totalCost"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyCostWithReplacements()) ?></td>
        <td id="marginDollar"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyProfitUsingTargetCostPerPageAndReplacements()) ?></td>
        <td id="marginPercent"><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCostWithReplacements(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2) ?>
            %
        </td>
    </tr>
    </tbody>
</table>
<em>The following
    <span id="numberOfDevicesReplaced"><?php echo number_format($optimization->getNumberOfDevicesWithReplacements()); ?></span> out of <?php echo number_format($optimization->getDevices()->purchasedDeviceInstances->getCount()); ?> eligible devices have been selected for replacement.</em>