<?php
/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optmizationViewModel;
?>
<table class='table table-condensed' style="width: 100%">
    <thead>
    <tr class='header'>
        <td><strong>Fleet</strong></td>
        <td><strong>Weighted Monochrome CPP</strong></td>
        <td><strong>Weighted Color CPP</strong></td>
        <td><strong>Total Cost</strong></td>
        <td><strong>Margin $</strong></td>
        <td><strong>Margin %</strong></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td> Current</td>
        <td><?php echo $this->currency($optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage, array('precision' => 4)); ?></td>
        <td><?php echo ($optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage > 0) ? $this->currency($optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage, array('precision' => 4)) : 'N/A'; ?></td>
        <td><?php echo $this->currency($optimization->calculateDealerMonthlyCost()); ?></td>
        <td><?php echo $this->currency($optimization->calculateDealerMonthlyProfitUsingTargetCostPerPage()); ?></td>
        <td><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCost(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2); ?>
            %
        </td>
    </tr>
    <tr>
        <td> Optimized</td>
        <td id="monochromeCpp"><?php echo $this->currency((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->monochromeCostPerPage, array('precision' => 4)) ?></td>
        <td id="colorCpp"><?php echo ((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage > 0) ? $this->currency((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage, array('precision' => 4)) : 'N/A'; ?></td>
        <td id="totalCost"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyCostWithReplacements(), array('precision' => 2)) ?></td>
        <td id="marginDollar"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyProfitUsingTargetCostPerPageAndReplacements(), array('precision' => 2)) ?></td>
        <td id="marginPercent"><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCostWithReplacements(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2) ?>
            %
        </td>
    </tr>
    </tbody>
</table>