<?php
/* @var $phpword \PhpOffice\PhpWord\PhpWord */
$phpword = $this->phpword;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

// Initialize some properties
$properties = $phpword->getDocumentProperties();
$properties->setCreator('MPS Assessment Software');
$properties->setCompany('MPS Assessment Software');
$properties->setTitle('Printing Device List');
$properties->setCategory('Dealer Report');
$properties->setLastModifiedBy('MPS Assessment Software');
$properties->setCreated(time());
$properties->setModified(time());
$properties->setSubject('MPS Assessment Software');

/**
 * Define the different Sections
 */

// This section is landscape with 0.5" margins insead of 1"
$mainSection = $phpword->addSection([
    'orientation'  => 'portrait',
    'marginLeft'   => 720,
    'marginRight'  => 720,
    'marginTop'    => 720,
    'marginBottom' => 720
]);

/**
 * Define Global Paragraph Styles here
 */

$phpword->addParagraphStyle('nospacing', [
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('nospacing_rightalign', [
    'align'       => 'right',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('nospacing_centeralign', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('centeralign', [
    'align' => 'right'
]);

$phpword->addParagraphStyle('rightalign', [
    'align' => 'right'
]);

/**
 * Define Global Font Styles here
 */

$phpword->addFontStyle('table_header', [
    'size' => 8,
    'bold' => true
]);

$phpword->addFontStyle('table_body', [
    'size' => 8
]);

$phpword->addFontStyle('table_footer', [
    'size'  => 8,
    'bold'  => true,
    'color' => 'red'
]);

$phpword->addFontStyle('bold_text', [
    'bold' => true
]);

$phpword->addFontStyle('italic_text', [
    'italic' => true
]);

/**
 * Define Global Heading (Title) Styles here
 */

// H1 Style
$phpword->addTitleStyle(1, [
    'size'  => 16,
    'color' => '000000',
    'bold'  => true
], [
    'borderBottomSize' => 1
]);
// H2 Style #5881BC
$phpword->addTitleStyle(2, [
    'size'  => 14,
    'color' => '000000',
    'bold'  => true
]);
// H3 Style #5881BC
$phpword->addTitleStyle(3, [
    'size'  => 12,
    'color' => '4F81BD',
    'bold'  => true
]);

/**
 * Define Table Styles here
 */
$header_color    = "dddddd";
$footer_color    = "dddddd";
$highlight_color = "f6ff8f";

/* LANDSCAPE FULL WIDTH TABLE = 16000 twips */
/* PORTRAIT FULL WIDTH TABLE = 10400 twips */

$includeTable = (object)[
    "rowheader"   => [
        'tblHeader' => true,
        'cantSplit' => true,
    ],
    "rowstyle"    => [
        "cantSplit" => true,
    ],
    "tablestyle"  => [
        'cellMarginTop'     => 50,
        'cellMarginRight'   => 50,
        'cellMarginBottom'  => 50,
        'cellMarginright'   => 50,
        'borderBottomSize'  => 10,
        'borderBottomColor' => 'black',
    ],
    "col1Width"   => 2200,
    "col2Width"   => 2200,
    "col3Width"   => 2000,
    "col4Width"   => 2000,
    "col5Width"   => 2000,
    "leftalign"   => "nospacing",
    "centeralign" => "nospacing_centeralign",
    "rightalign"  => "nospacing_rightalign",
    "header"      => (object)[
        "rowheight" => null,
        "fontStyle" => "table_header",
        "cell"      => [
            "borderTopSize"    => 1,
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "bgColor"          => $header_color,
            "valign"           => "center"
        ]
    ],
    "row"         => (object)[
        "rowheight" => null,
        "fontStyle" => 'table_body',
        "cell"      => [
            "borderTopSize"    => 1,
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "valign"           => "center"
        ]
    ],
    "footer"      => (object)[
        "rowheight" => null,
        "fontStyle" => 'table_footer',
        "cell"      => [
            "borderTopSize"    => 1,
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "bgColor"          => $footer_color,
            "valign"           => "center"
        ]
    ]
];

$excludeTable = (object)[
    "rowheader"   => [
        'tblHeader' => true,
        'cantSplit' => true,
    ],
    "rowstyle"    => [
        "cantSplit" => true,
    ],
    "tablestyle"  => [
        'cellMarginTop'     => 50,
        'cellMarginRight'   => 50,
        'cellMarginBottom'  => 50,
        'cellMarginright'   => 50,
        'borderBottomSize'  => 10,
        'borderBottomColor' => 'black',
    ],
    "col1Width"   => 2600,
    "col2Width"   => 2600,
    "col3Width"   => 2600,
    "col4Width"   => 2600,
    "leftalign"   => "nospacing",
    "centeralign" => "nospacing_centeralign",
    "rightalign"  => "nospacing_rightalign",
    "header"      => (object)[
        "rowheight" => null,
        "fontStyle" => "table_header",
        "cell"      => [
            "borderTopSize"    => 1,
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "bgColor"          => $header_color,
            "valign"           => "center"
        ]
    ],
    "row"         => (object)[
        "rowheight" => null,
        "fontStyle" => 'table_body',
        "cell"      => [
            "borderTopSize"    => 1,
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "valign"           => "center"
        ]
    ],
    "footer"      => (object)[
        "rowheight" => null,
        "fontStyle" => 'table_footer',
        "cell"      => [
            "borderTopSize"    => 1,
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "bgColor"          => $footer_color,
            "valign"           => "center"
        ]
    ]
];

/**
 * Here we put all our table styles into an object that gets passed to each of
 * the view scripts
 */
$styles = (object)[
    "tables"    => (object)[
        "includeTable" => $includeTable,
        "excludeTable" => $excludeTable
    ],
    "underline" => (object)[
        "tablestyle" => [
            'borderTopSize'  => 10,
            'borderTopColor' => 'black',
        ]
    ],
];

/**
 * An array of view variables to pass to the partial scripts
 */
$data = [
    "phpword"             => $phpword,
    "assessmentViewModel" => $assessmentViewModel,
    "section"             => $mainSection,
    "styles"              => $styles,
    "brandName"           => My_Brand::getDealerBranding()->mpsProgramName,
    "companyName"         => My_Brand::getDealerBranding()->shortDealerName
];

/**
 * Render each of the view scripts for different parts of the document
 */
$this->partial("/report/printingdevicelist/docx/01_header.phtml", $data);
$this->partial("/report/printingdevicelist/docx/02_included.phtml", $data);
$this->partial("/report/printingdevicelist/docx/03_excluded.phtml", $data);

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpword, 'Word2007');
$objWriter->save($this->savePath);

/**
 * Finally we write out the url to the file we just generated.
 */
if (Zend_Controller_Front::getInstance()->getRequest()->isXmlHttpRequest()) echo DOMAIN_URL.$this->baseUrl($this->publicFileName);
else header('Location: '.DOMAIN_URL.$this->baseUrl($this->publicFileName));
