<?php
/**
 * Cost Analysis - Header information
 *
 * This script contains everything that comes before the big table of
 * information in the cost analysis.
 */
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

/**
 * Variables
 */
// Add any variables that are needed throughout the page here.


/**
 * Section starts here
 */

$section->addTitle('Printing Device List');

$textRun = $section->addTextRun();
$textRun->addText('Below is a list of your printing device models and whether or not they are qualified for just-in-time supplies fulfillment. For devices not qualified for just-in-time supplies fulfillment, you can call into our office to order supplies for next-day delivery. Consider upgrading these devices to be on a 100%% just-in-time supplies fulfillment model. Devices not included in the report are listed in a subsequent table. These devices are typically older models that are not compatible with remote monitoring software or do not qualify for our managed print program.');

