<?php

use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationDealerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

$this->placeholder('ReportNav')->set($this->render('_partials/reportMenu.phtml'));

/* @var $hardwareOptimization HardwareOptimizationModel */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $dealerOptimization OptimizationDealerModel */
$dealerOptimization = new OptimizationDealerModel($hardwareOptimization);

/* @var $deviceInstances DeviceInstanceModel[] */
$deviceInstances = $optimization->getDevicesGroupedByAction();

$totalNumberOfDevices = $optimization->getDevices()->purchasedDeviceInstances->getCount();

/* @var $costPerPageSetting */
$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();

$titleData = [
    "hardwareOptimization" => $hardwareOptimization,
    "dealerLogoFile"       => $this->dealerLogoFile,
    "companyName"          => My_Brand::getDealerBranding()->shortDealerName,
];

$profitabilityDevices = new OptimizationCustomerModel($hardwareOptimization);

$data = [
    "hardwareOptimization" => $hardwareOptimization,
    "optimization"         => $optimization,
    "dealerOptimization"   => $dealerOptimization,
    "companyName"          => My_Brand::getDealerBranding()->shortDealerName,
    "deviceInstances"      => $deviceInstances,
    "totalDevices"         => $totalNumberOfDevices,
    "costPerPageSetting"   => $costPerPageSetting
];
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10">
            <div class="container full-width hardware-optimization" id="htmlReportContainer">
                <?php
                // Actual pages
                echo $this->partial("report/dealer/optimization/html/01_titlepage.phtml", $titleData);
                echo $this->partial("report/dealer/optimization/html/02_cost_analysis_summary.phtml", $data);
                echo $this->partial("report/dealer/optimization/html/03_device_summary.phtml", $data);
                echo $this->partial("report/dealer/optimization/html/04_suggested_replacement_devices.phtml", $data);
                echo $this->partial("report/dealer/optimization/html/05_suggested_upgrades.phtml", $data);
                echo $this->partial("report/dealer/optimization/html/06_acceptable_devices.phtml", $data);
                echo $this->partial("report/dealer/optimization/html/07_excess_inventory.phtml", $data);
                echo $this->partial("report/dealer/optimization/html/08_retired_devices.phtml", $data);
                echo $this->partial("report/dealer/optimization/html/09_flagged_devices.phtml", $data);
                echo $this->partial("report/dealer/optimization/html/10_leased_devices.phtml", $data);
                echo $this->partial("report/dealer/optimization/html/11_excluded.phtml", $data);
                ?>
            </div>
        </div>
        <div class="col-sm-2">
            <div id="reportNavbar" data-spy="affix" data-offset-top="158" class="affix-top">
                <ul id="reportNav" class="nav nav-pills nav-stacked">
                    <li class="active"><a href="#title-page">Title Page</a></li>
                    <li><a href="#cost-analysis-summary">Summary</a></li>
                    <li><a href="#device-summary">Device Summary</a></li>
                    <li><a href="#replacements">Replaced Devices</a></li>
                    <li><a href="#upgrades">Upgraded Devices</a></li>
                    <li><a href="#acceptable">Acceptable Devices</a></li>
                    <li><a href="#excess">Excess Inventory</a></li>
                    <li><a href="#retired">Retired Devices</a></li>
                    <li><a href="#flagged">Flagged Devices</a></li>
                    <li><a href="#leased">Leased Devices</a></li>
                    <li><a href="#excluded">Excluded Devices</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>