<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;
?>

<div class="h1" id="cost-analysis-summary">
    Fleet
</div>
<table class="rDevices">
    <tr>
        <td class="cell-label">Target Monochrome CPP:</td>
        <td class="cell-data cost-per-page"><?php echo $this->formatCostPerPage($hardwareOptimization->getHardwareOptimizationSetting()->targetMonochromeCostPerPage); ?></td>
        <td class="cell-label">Target Color CPP:</td>
        <td class="cell-data cost-per-page"><?php echo $this->formatCostPerPage($hardwareOptimization->getHardwareOptimizationSetting()->targetColorCostPerPage); ?></td>
    </tr>
    <tr>
        <td class="cell-label">Monthly Monochrome Page Count:</td>
        <td class="cell-data page-volume"><?php echo $this->formatPageVolume($optimization->getDevices()->purchasedDeviceInstances->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
        <td class="cell-label">Monthly Color Page Count:</td>
        <td class="cell-data page-volume"><?php echo $this->formatPageVolume($optimization->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly()); ?></td>
    </tr>
</table>
<br />

<div class="pheader">
    Cost Analysis Summary
</div>
<table class="rDevices cost-analysis-summary-table">
    <tr class="header">
        <th colspan="2">Current Fleet</th>
        <th colspan="2">Optimized Fleet</th>
    </tr>
    <tr>
        <td class="cell-label">Monochrome CPP:</td>
        <td class="cell-data cost-per-page"><?php echo $this->formatCostPerPage((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage) ?></td>
        <td class="cell-label">Monochrome CPP:</td>
        <td class="cell-data cost-per-page"><?php echo $this->formatCostPerPage((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->monochromeCostPerPage) ?></td>
    </tr>
    <tr>
        <td class="cell-label">Color CPP:</td>
        <td class="cell-data cost-per-page"><?php echo ($optimization->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly() > 0) ? $this->formatCostPerPage((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage) : 'No print volume'; ?></td>
        <td class="cell-label">Color CPP:</td>
        <td class="cell-data cost-per-page"><?php echo ($optimization->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly() > 0) ? $this->formatCostPerPage($optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage) : 'No print volume'; ?></td>
    </tr>
    <tr>
        <td class="cell-label">Total Cost:</td>
        <td class="cell-data cost"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyCost()) ?></td>
        <td class="cell-label">Total Cost:</td>
        <td class="cell-data cost"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyCostWithReplacements()) ?></td>
    </tr>
    <tr>
        <td class="cell-label">Margin ($):</td>
        <td class="cell-data margin-dollar"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyProfitUsingTargetCostPerPage()) ?></td>
        <td class="cell-label">Margin ($):</td>
        <td class="cell-data margin-dollar"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyProfitUsingTargetCostPerPageAndReplacements()) ?></td>
    </tr>
    <tr>
        <td class="cell-label">Margin (%):</td>
        <td class="cell-data margin-percent"><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCost(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2) ?>
            %
        </td>
        <td class="cell-label">Margin (%):</td>
        <td class="cell-data margin-percent"><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCostWithReplacements(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2) ?>
            %
        </td>
    </tr>
</table>
<br />