<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;

/* @var $deviceInstances Proposalgen_Model_DeviceInstance[] */
$deviceInstances = $optimization->getDevicesGroupedByAction();

/* @var $graphs array */
$graphs = $this->graphs;
?>

<div class="h1" id="cost-analysis-summary">
    Fleet
</div>
<table class="rDevices">
    <tr>
        <td><strong>Target Monochrome CPP:</strong></td>
        <td><?php echo $this->formatCostPerPage($hardwareOptimization->getHardwareOptimizationSetting()->targetMonochromeCostPerPage); ?></td>
        <td><strong>Target Color CPP:</strong></td>
        <td><?php echo $this->formatCostPerPage($hardwareOptimization->getHardwareOptimizationSetting()->targetColorCostPerPage); ?></td>
    </tr>
    <tr>
        <td><strong>Monthly Monochrome Page Count:</strong></td>
        <td><?php echo $this->formatPageVolume($optimization->getDevices()->purchasedDeviceInstances->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
        <td><strong>Monthly Color Page Count:</strong></td>
        <td><?php echo $this->formatPageVolume($optimization->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly()); ?></td>
    </tr>
</table>
<br />

<div class="pheader">
    Cost Analysis Summary
</div>
<table class="rDevices">
    <tr class='header'>
        <th colspan='2'>Current Fleet</th>
        <th colspan='2'>Optimized Fleet</th>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Monochrome CPP:</strong></td>
        <td><?php echo $this->formatCostPerPage((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage) ?></td>
        <td style='width:150px;'><strong>Monochrome CPP:</strong></td>
        <td style='width:250px;'><?php echo $this->formatCostPerPage((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->monochromeCostPerPage) ?></td>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Color CPP:</strong></td>
        <td><?php echo ($optimization->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly() > 0) ? $this->formatCostPerPage((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage) : 'No print volume'; ?></td>
        <td style='width:150px;'><strong>Color CPP:</strong></td>
        <td style='width:250px;'><?php echo ($optimization->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly() > 0) ? $this->formatCostPerPage($optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage) : 'No print volume'; ?></td>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Total Cost:</strong></td>
        <td><?php echo $this->currency((float)$optimization->calculateDealerMonthlyCost()) ?></td>
        <td style='width:150px;'><strong>Total Cost:</strong></td>
        <td style='width:250px;'><?php echo $this->currency((float)$optimization->calculateDealerMonthlyCostWithReplacements()) ?></td>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Margin ($):</strong></td>
        <td><?php echo $this->currency((float)$optimization->calculateDealerMonthlyProfitUsingTargetCostPerPage()) ?></td>
        <td style='width:150px;'><strong>Margin ($):</strong></td>
        <td style='width:250px;'><?php echo $this->currency((float)$optimization->calculateDealerMonthlyProfitUsingTargetCostPerPageAndReplacements()) ?></td>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Margin (%):</strong></td>
        <td><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCost(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2) ?>
            %
        </td>
        <td style='width:150px;'><strong>Margin (%):</strong></td>
        <td style='width:250px;'><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCostWithReplacements(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2) ?>
            %
        </td>
    </tr>
</table>
<br />