<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;

/* @var $deviceInstances Proposalgen_Model_DeviceInstance[] */
$deviceInstances = $this->deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_KEEP];

/* @var $costPerPageSetting */
$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();

/* @var $graphs array */
$graphs = $this->graphs;
?>
<div class="pheader" id="acceptable">
    Acceptable Devices <em><?php echo '(' . count($deviceInstances) . ' of ' . $this->totalDevices . ')' ?></em>
</div>
<em>The following devices have been deemed productive and fall within the target costs per pages.</em>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>Serial<br />IP Address</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
        <th>Mono CPP</th>
        <th>Color CPP</th>
        <th>Monthly Cost</th>
    </tr>
    <?php

    foreach ($deviceInstances as $deviceInstance) :
        $masterDevice = $deviceInstance->getMasterDevice();
        $isColor = $masterDevice->isColor();
        ?>
        <tr class='<?php echo $this->cycle(array("rowOne", "rowTwo"))->next(); ?>'>
            <td class='deviceName'><?php echo '<em>' . $masterDevice->getManufacturer()->fullname . '</em><br/><strong>' . $masterDevice->modelName . '</strong><br/><em>'; ?></td>
            <td class='deviceName'><?php echo $deviceInstance->serialNumber . '<br/>' . $deviceInstance->ipAddress . '</em>'; ?></td>
            <td><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td><?php echo ($isColor) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : 'N/A'; ?></td>
            <td><?php echo $this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->monochromeCostPerPage); ?></td>
            <td><?php echo ($isColor) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->colorCostPerPage) : 'N/A'; ?></td>
            <td><?php echo $this->currency($deviceInstance->calculateMonthlyCost($costPerPageSetting)); ?></td>
        </tr>
    <?php endforeach; ?>
</table>
<br />