<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;

/* @var $acceptableDeviceInstances Proposalgen_Model_DeviceInstance[] */
$acceptableDeviceInstances = (isset($this->deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_KEEP]) ? $this->deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_KEEP] : array());

/* @var $graphs array */
$graphs = $this->graphs;

$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();
?>
<div class="pheader" id="acceptable">
    Acceptable Devices <em><?php echo '(' . number_format(count($acceptableDeviceInstances)) . ' of ' . $this->totalDevices . ')' ?></em>
</div>

<!-- Only display message and table if there are replacement devices assigned -->
<?php if ($acceptableDeviceInstances): ?>
    <em>The following devices have been deemed productive and fall within the target cost per page.</em>

    <table class="rDevices">
        <tr class="header">
            <th class="device-name">Device Name</th>
            <th>Serial<br />IP Address</th>
            <th>Mono AMPV</th>
            <th>Color AMPV</th>
            <th>Life Page Count</th>
            <th>Device Age</th>
            <th>Mono CPP</th>
            <th>Color CPP</th>
            <th>Monthly Cost</th>
        </tr>
        <?php

        foreach ($acceptableDeviceInstances as $deviceInstance) :
            $masterDevice = $deviceInstance->getMasterDevice();
            $isColor      = $masterDevice->isColor();
            ?>
            <tr class='<?php echo $this->cycle(array("rowOne", "rowTwo"))->next(); ?>'>
                <td class="device-name"><?php echo '<em>' . $masterDevice->getManufacturer()->fullname . '</em><br/><strong>' . $masterDevice->modelName . '</strong><br/><em>'; ?></td>
                <td class="serial-number"><?php echo $deviceInstance->serialNumber . '<br/>' . $deviceInstance->ipAddress . '</em>'; ?></td>
                <td class="page-volume"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
                <td class="page-volume"><?php echo ($isColor) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : ' - '; ?></td>
                <td class="page-volume"><?php echo $this->formatPageVolume($deviceInstance->getMeter()->endMeterLife) ?></td>
                <td class="number"><?php echo number_format($deviceInstance->getMasterDevice()->getAge()) . 'y'; ?></td>
                <td class="cost-per-page"><?php echo $this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->monochromeCostPerPage); ?></td>
                <td class="cost-per-page"><?php echo ($isColor) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->colorCostPerPage) : ' - '; ?></td>
                <td><?php echo $this->currency($deviceInstance->calculateMonthlyCost($costPerPageSetting)); ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <em>There are currently no devices deemed productive and that fall within the target cost per page.</em>
<?php endif; ?>
<br />