<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;

/* @var $excessDeviceInstances Proposalgen_Model_DeviceInstance[] */
$excessDeviceInstances = (isset($this->deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_REPLACE]) ? $this->deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_REPLACE] : array());

/* @var $graphs array */
$graphs = $this->graphs;

$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();
$totalNumberOfDevices = $optimization->getDevices()->purchasedDeviceInstances->getCount();
?>
<div class="pheader" id="excess">
    Excess Inventory <em><?php echo '(' . number_format(count($excessDeviceInstances)) . ')' ?></em>
</div>

<!-- Only display message and table if there are replacement devices assigned -->
<?php if ($excessDeviceInstances): ?>
    <p>The following devices are excess devices that can still be used inside your client's fleet.</p>

    <table class="rDevices">
        <tr class="header">
            <th class="device-name">Device Name</th>
            <th>Serial<br />IP Address</th>
            <th><?php echo My_Brand::$jit; ?><br />Compatible</th>
            <th>Life Page<br />Count</th>
            <th>Mono CPP</th>
            <th>Color CPP</th>
        </tr>
        <?php foreach ($excessDeviceInstances as $deviceInstance) : ?>
            <?php
            $masterDevice = $deviceInstance->getMasterDevice();
            $isColor      = $masterDevice->isColor();
            ?>
            <tr>
                <td class="device-name"><?php echo '<em>' . $masterDevice->getManufacturer()->fullname . '</em><br/><strong>' . $masterDevice->modelName . '</strong><br/><em>'; ?></td>
                <td class="serial-number"><?php echo $deviceInstance->serialNumber . '<br/>' . $deviceInstance->ipAddress . '</em>'; ?></td>
                <td><?php echo ($deviceInstance->isCapableOfReportingTonerLevels) ? 'Yes' : 'No'; ?></td>
                <td class="pageVolume"><?php echo $this->formatPageVolume($deviceInstance->getMeter()->endMeterLife); ?></td>
                <td class="cost-per-page"><?php echo $this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->monochromeCostPerPage); ?></td>
                <td class="cost-per-page"><?php echo ($isColor) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->colorCostPerPage) : ' - '; ?></td>
            </tr>
        <?php endforeach ?>
    </table>
<?php else: ?>
    <em>There are currently no excess devices that can still be used inside your client's fleet.</em>
<?php endif; ?>
<br />