<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;

/* @var $deviceInstances Proposalgen_Model_DeviceInstance[] */
$deviceInstances = $this->deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_RETIRE];

/* @var $costPerPageSetting */
$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();

/* @var $graphs array */
$graphs = $this->graphs;
?>
<div class="pheader" id="retired">
    Retired Devices <em><?php echo '(' . count($deviceInstances) . ' of ' . $this->totalDevices . ')' ?></em>
</div>
<em>Devices with both low volume and age of over 8 years have been targeted for retirement. We suggest migrating the page volume to another device in your
    fleet. </em>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>Serial<br />IP Address</th>
        <th>Life Page Count</th>
        <th>Age (years)</th>
        <th><?php echo My_Brand::$jit; ?> Compatible</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
        <th>Mono CPP</th>
        <th>Color CPP</th>
        <th>Monthly Cost</th>
    </tr>
    <?php foreach ($deviceInstances as $deviceInstance) :
        $masterDevice = $deviceInstance->getMasterDevice();
        $isColor      = $masterDevice->isColor();
        ?>
        <tr>
            <td class='deviceName'><?php echo '<em>' . $masterDevice->getManufacturer()->fullname . '</em><br/><strong>' . $masterDevice->modelName . '</strong><br/><em>'; ?></td>
            <td class='deviceName'><?php echo $deviceInstance->serialNumber . '<br/>' . $deviceInstance->ipAddress . '</em>'; ?></td>
            <td><?php echo number_format($deviceInstance->getMeter()->endMeterLife) ?></td>
            <td><?php echo number_format($deviceInstance->getMasterDevice()->getAge()); ?></td>
            <td><?php echo ($deviceInstance->isCapableOfReportingTonerLevels) ? 'Yes' : 'No'; ?>
            <td><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td><?php echo ($isColor) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : 'N/A'; ?></td>
            <td><?php echo $this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->monochromeCostPerPage); ?></td>
            <td><?php echo ($isColor) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->colorCostPerPage) : 'N/A'; ?></td>
            <td><?php echo $this->currency($deviceInstance->calculateMonthlyCost($costPerPageSetting)); ?></td>
        </tr>
    <?php endforeach ?>
</table>
<br />