<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;

/* @var $deviceInstances Proposalgen_Model_DeviceInstance[] */
$deviceInstances = $optimization->getDevices()->leasedDeviceInstances->getDeviceInstances();

/* @var $costPerPageSetting */
$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();

/* @var $graphs array */
$graphs = $this->graphs;

$totalNumberOfDevices = $optimization->getDevices()->purchasedDeviceInstances->getCount();
?>
    <div class="pheader" id="leased">
        Leased Devices <em><?php echo '(' . count($deviceInstances) . ')' ?></em>
    </div>
<em>The following devices were flagged as leased within the ownership section.</em>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>Serial Number <br /> IP Address</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
    </tr>
    <?php foreach ($deviceInstances as $deviceInstance) :
        $masterDevice = $deviceInstance->getMasterDevice();
        $isColor = $masterDevice->isColor();
        ?>
        <tr>

            <td class='deviceName'><?php echo '<em>' . $masterDevice->getManufacturer()->fullname . '</em><br/><strong>' . $masterDevice->modelName . '</strong><br/><em>'; ?></td>
            <td class='deviceName'><?php echo $deviceInstance->serialNumber . '<br/>' . $deviceInstance->ipAddress . '</em>'; ?></td>
            <td><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td><?php echo ($isColor) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : 'N/A'; ?></td>
        </tr>
    <?php endforeach ?>
</table>
<br />