<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;

$leasedDeviceInstances = $optimization->getDevices()->leasedDeviceInstances->getDeviceInstances();
$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();
$totalNumberOfDevices = $optimization->getDevices()->purchasedDeviceInstances->getCount();
?>
<div class="pheader" id="leased">
    Leased Devices <em><?php echo '(' . number_format(count($leasedDeviceInstances)) . ')' ?></em>
</div>
<em>The following devices were flagged as leased within the ownership section.</em>
<table class="rDevices">
    <tr class="header">
        <th style="width:175px;">Device Name</th>
        <th>Serial Number <br /> IP Address</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
    </tr>
    <?php foreach ($leasedDeviceInstances as $deviceInstance) :
        $masterDevice = $deviceInstance->getMasterDevice();
        $isColor      = $masterDevice->isColor();
        ?>
        <tr>

            <td class="device-name"><?php echo '<em>' . $masterDevice->getManufacturer()->fullname . '</em><br/><strong>' . $masterDevice->modelName . '</strong><br/><em>'; ?></td>
            <td class="serial-number"><?php echo $deviceInstance->serialNumber . '<br/>' . $deviceInstance->ipAddress . '</em>'; ?></td>
            <td class="page-volume"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td class="page-volume"><?php echo ($isColor) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : 'N/A'; ?></td>
        </tr>
    <?php endforeach ?>
</table>
<br />