<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;


$deviceInstances = $optimization->getDevices()->excludedDeviceInstances->getDeviceInstances();

$unmappedInstances = $optimization->getDevices()->unmappedDeviceInstances->getDeviceInstances();


/* @var $costPerPageSetting */
$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();

/* @var $graphs array */
$graphs = $this->graphs;

$totalNumberOfDevices = $optimization->getDevices()->purchasedDeviceInstances->getCount();
?>
<div class="pheader" id="excluded">
    Excluded <em><?php echo '(' . count($deviceInstances) . ')' ?></em>
</div>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>IP Address</th>
        <th>Serial Number</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
        <th>Reason</th>
    </tr>
    <?php foreach ($deviceInstances as $deviceInstance) : ?>
        <tr>
            <td class='deviceName'><?php echo $deviceInstance->getDeviceName(); ?></td>
            <td><?php echo $deviceInstance->ipAddress; ?></td>
            <td><?php echo $deviceInstance->serialNumber; ?></td>
            <td><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()); ?></td>
            <td>Manually Excluded</td>
        </tr>
    <?php endforeach; ?>

    <?php foreach ($unmappedInstances as $deviceInstance) : ?>
        <tr>
            <td class='deviceName'><?php echo $deviceInstance->getDeviceName(); ?></td>
            <td><?php echo $deviceInstance->ipAddress; ?></td>
            <td><?php echo $deviceInstance->serialNumber; ?></td>
            <td><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()); ?></td>
            <td>Not Mapped</td>
        </tr>
    <?php endforeach; ?>
</table>