<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Dealer */
$dealerOptimization = $this->dealerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;

$excludedDeviceInstances = $optimization->getDevices()->excludedDeviceInstances->getDeviceInstances();
$unmappedInstances = $optimization->getDevices()->unmappedDeviceInstances->getDeviceInstances();
$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();
$totalNumberOfDevices = $optimization->getDevices()->excludedDeviceInstances->getCount() + $optimization->getDevices()->unmappedDeviceInstances->getCount();
?>
<div class="pheader" id="excluded">
    Excluded and Unmapped <em><?php echo '(' . number_format($totalNumberOfDevices) . ')' ?></em>
</div>
<table class="rDevices">
    <tr class="header">
        <th style="width:175px;">Device Name</th>
        <th>IP Address</th>
        <th>Serial Number</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
        <th>Reason</th>
    </tr>
    <?php foreach ($excludedDeviceInstances as $deviceInstance) : ?>
        <tr>
            <td class="device-name"><?php echo $deviceInstance->getDeviceName(); ?></td>
            <td class="serial-number"><?php echo $deviceInstance->ipAddress; ?></td>
            <td class="serial-number"><?php echo $deviceInstance->serialNumber; ?></td>
            <td class="page-volume"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td class="page-volume"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()); ?></td>
            <td>Manually Excluded</td>
        </tr>
    <?php endforeach; ?>

    <?php foreach ($unmappedInstances as $deviceInstance) : ?>
        <tr>
            <td class="deviceName"><?php echo $deviceInstance->getDeviceName(); ?></td>
            <td class="serialNumber"><?php echo $deviceInstance->ipAddress; ?></td>
            <td class="serialNumber"><?php echo $deviceInstance->serialNumber; ?></td>
            <td class="pageVolume"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td class="pageVolume"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()); ?></td>
            <td>Not Mapped</td>
        </tr>
    <?php endforeach; ?>
</table>