<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
<h1>All Options </h1>
<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th>Devcie</th>
            <th>CCP Mono</th>
            <th>CCP Color</th>
            <th>Billing Pref</th>
            <th>Margin</th>
            <th style="width: 120px;">Action</th>
        </tr>
    </thead>
    <tbody>
    	
        <?php foreach ($this->paginator->getCurrentItems() as $option) : /* @var $option Quotegen_Model_Option */ ?>
        <tr>
            <td><?php echo $option->getName(); ?></td>
            <td><?php echo $option->getDescription(); ?></td>
            <td><?php echo $option->getPrice();?></td>
            <td><?php echo $option->getSku();?></td>
            <?php if (count($option->getCategories()) > 0 ) :
				$categoryNames = array();
            ?>
            <td>
            <?php foreach ($option->getCategories() as $category) : /* @var $category Quotegen_Model_Category */?>
            	<?php $categoryNames [] = $category->getName(); ?>
            <?php endforeach; ?>
            <?php echo implode(', ', $categoryNames);?>
            </td>
            <?php else : ?>
            	<td></td>
            <?php endif; ?>
            <td>
                <div class="btn-group">
                	<a class="btn btn-info" title="View Client" href="<?php echo $this->url( array ( 'action' => 'view', 'id' =>  $option->getId())); ?>"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-warning" title="Edit Client" href="<?php echo $this->url(array ( 'action' => 'edit', 'id' =>  $option->getId())); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-danger" title="Delete Client" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' =>  $option->getId())); ?>"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
<div class='well'>
    <h1>There are no options</h1>
</div>
<a class="btn btn-success btn-small pull-right create-button" href="<?php echo $this->url(array('action' => 'create')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
<?php endif; ?>

