<div class="page-header">
    <h1>Leasing Rates -
        <small>Clear Schema</small>
    </h1>
</div>
<div class="well">
    <form enctype="application/x-www-form-urlencoded" method="post" class="form-horizontal" action="">
        <div class="control-group">
            <div class="controls">Are you sure you want to reset the current schema back to it's default? This action cannot be undone.</div>
        </div>
        <div class="form-actions">
            <input type="submit" name="submit" id="submit" value="Reset" class="btn btn-primary">
            <input type="submit" name="cancel" id="cancel" value="Cancel" class="btn" type="reset">
        </div>
    </form>
</div>