<?php

/* @var $leasingSchema \MPSToolbox\Legacy\Modules\QuoteGenerator\Models\LeasingSchemaModel */
$leasingSchema = $this->leasingSchema;

?>
<div class="container">
    <?php if (isset($this->errMessages)) : ?>
        <div class="alert alert-danger"><?= implode('<br>', $this->errMessages) ?></div>
    <?php endif; ?>

    <?php if ($leasingSchema) : ?>
        <?php
        // Loop through the terms and rates
        $rates = $leasingSchema->getRates();
        ?>
        <div class="clearfix">
            <div class="pull-right">
                <a class="btn btn-warning" href="<?= $this->url(['leasingSchemaId' => $leasingSchema->id], 'company.leasing-schema.import-leasing-rate') ?>">Import from file</a>
                <a class="btn btn-default" title="Clear Schema" href="<?= $this->url(['leasingSchemaId' => $leasingSchema->id], 'company.leasing-schema.clear-provider'); ?>">
                    <i class="glyphicon glyphicon-exclamation-sign icon-white"></i> Clear Schema
                </a>
            </div>
        </div>
        <div style="overflow: auto; overflow-y: hidden; -ms-overflow-y: hidden; margin: 20px 0px 0px 0px;">

            <table id="leasingSchemaTable" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th nowrap="nowrap" style="min-width: 80px; text-align: center;">Term (months)</th>
                    <?php foreach ($leasingSchema->getRanges() as $range) : ?>
                        <?php if ($range->startRange == 0) : ?>
                            <th style="min-width: 80px; text-align: center;">$0+</th>
                        <?php else : ?>
                            <th style="min-width: 80px; text-align: center;"><?= $this->currency($range->startRange); ?>+</th>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <th nowrap="nowrap" style="min-width: 80px; text-align: center;">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($leasingSchema->getTerms() as $term) : ?>
                    <tr>
                        <td style="text-align: center;">
                            <?= $term->months; ?> months
                        </td>

                        <?php foreach ($leasingSchema->getRanges() as $range) : ?>
                            <td style="text-align: center;"><?= $this->formatLeaseRate($rates[$term->id][$range->id]->rate); ?></td>
                        <?php endforeach; ?>

                        <td style="text-align: center;">
                            <a class="btn btn-warning btn-xs" title="Edit Term" href="<?= $this->url(['id' => $term->id, 'leasingSchemaId' => $leasingSchema->id], 'company.leasing-schema.edit-term'); ?>">
                                <i class="glyphicon glyphicon-pencil icon-white"></i>
                            </a>
                            <?php if (count($leasingSchema->getTerms()) > 1) : ?>
                                <a class="btn btn-danger btn-xs" title="Delete Term" href="<?= $this->url(['id' => $term->id, 'leasingSchemaId' => $leasingSchema->id], 'company.leasing-schema.delete-term'); ?>">
                                    <i class="glyphicon glyphglyphicon glyphicon-trash"></i>
                                </a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td></td>
                    <?php foreach ($leasingSchema->getRanges() as $range) : ?>
                        <td style="text-align: center;">
                            <a class="btn btn-warning btn-xs" title="Edit Range" href="<?= $this->url(['id' => $range->id, 'leasingSchemaId' => $range->leasingSchemaId], 'company.leasing-schema.edit-range'); ?>">
                                <i class="glyphicon glyphicon-pencil icon-white"></i>
                            </a>
                            <?php if ($range->startRange != 0) : ?>
                                <a class="btn btn-danger btn-xs" title="Delete Range" href="<?= $this->url(['id' => $range->id, 'leasingSchemaId' => $range->leasingSchemaId], 'company.leasing-schema.delete-range'); ?>">
                                    <i class="glyphicon glyphglyphicon glyphicon-trash"></i>
                                </a>
                            <?php endif; ?>
                        </td>
                    <?php endforeach; ?>
                    <td style="text-align: center;">&nbsp;</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="clearfix">
             <span class="pull-left">
                 <a class="btn btn-default" title="Back" href="<?= $this->url([], 'company.leasing-schema'); ?>">Done</a>
            </span>
    	<span class="pull-right">
          	<a class="btn btn-success" title="Add Term" href="<?= $this->url(['leasingSchemaId' => $range->leasingSchemaId], 'company.leasing-schema.add-term'); ?>"><i class="glyphicon glyphicon-plus-sign icon-white"></i> Add Term</a>
          	<a class="btn btn-success" title="Add Range" href="<?= $this->url(['leasingSchemaId' => $range->leasingSchemaId], 'company.leasing-schema.add-range'); ?>"><i class="glyphicon glyphicon-plus-sign icon-white"></i> Add Range</a>
    	</span>
        </div>
    <?php else : ?>
        <h2>There is no Leasing Schema Data available.</h2>
    <?php endif; ?>
</div>