<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
<h1>All Devices</h1>
<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th style="width: 30px;">ID</th>
            <th>Name</th>
            <th>Phone number</th>
            <th style="width: 120px;">Action</th>
        </tr>
    </thead>
    <tbody>
    	
        <?php foreach ($this->paginator->getCurrentItems() as $device) : /* @var $device Quotegen_Model_Device */ ?>
        <tr>
            <td><?php echo $device->getId(); ?></td>
            <td><?php echo $device->getFullname(); ?></td>
            <td><?php echo $device->getPhoneNumber(); ?></td>
            <td>
                <div class="btn-group">
	                <a class="btn btn-info" title="View Device" href="<?php echo $this->url( array ( 'action' => 'view', 'id' => $device->getId())); ?>"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-warning" title="Edit Device" href="<?php echo $this->url( array ( 'action' => 'edit', 'id' => $device->getId())); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-danger" title="Delete Device" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' => $device->getId())); ?>"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
    <h1>There are no devices</h1>
<?php endif; ?>

