
<?php $this->headScript()->captureStart('append','text/javascript') ?>
	
	$(document).ready(function() {
		
	});
	
	function edit_rate(term, range) {
		var label = $('#label-term'+term+'-range'+range);
		var editbox = $('#edit-term'+term+'-range'+range);
		var field = $('#term'+term+'-range'+range);
		
		if (editbox.is(':visible')) {
			label.html(field.val());
			editbox.hide();
			label.show();
		} else {
			label.hide();
			editbox.show();
		}
	}
	
<?php $this->headScript()->captureEnd() ?>

<div class="well">

	<form name="leasingSchemas" id="leasingSchemas" class="form-horizontal" action="" method="post" enctype="application/x-www-form-urlencoded">
		<p>Click on a value to edit it.</p>
		
		<div id="lease-terms-container">
		  <table class="table table-striped table-bordered">
		    <thead>
		      <!-- get all max-cost fields and loop through to display -->
		      <th width="12%">Term (months) </th>
		      <th width="">
		      	$0 - $100
		      	<span class="pull-right">
			      	<a class="btn btn-mini btn-warning" title="Edit Range" href="#">
						<i class="icon-pencil"></i>
					</a> 
			      	<a class="btn btn-danger btn-mini" title="Remove Range" href="#">
						<i class="icon-remove"></i>
					</a>
				</span>
		      </th>
		      <th width="">
		      	$101 - $1,000 
		      	<span class="pull-right">
			      	<a class="btn btn-mini btn-warning" title="Edit Range" href="#">
						<i class="icon-pencil"></i>
					</a> 
			      	<a class="btn btn-danger btn-mini" title="Remove Range" href="#">
						<i class="icon-remove"></i>
					</a>
				</span>
		      </th>
		      <th width="">
		      	$1,001 - $10,000 
		      	<span class="pull-right">
			      	<a class="btn btn-mini btn-warning" title="Edit Range" href="#">
						<i class="icon-pencil"></i>
					</a> 
			      	<a class="btn btn-danger btn-mini" title="Remove Range" href="#">
						<i class="icon-remove"></i>
					</a>
				</span>
		      </th>
		      <th width="">
		      	$10,001+ 
		      	<span class="pull-right">
			      	<a class="btn btn-mini btn-warning" title="Edit Range" href="#">
						<i class="icon-pencil"></i>
					</a> 
			      	<a class="btn btn-danger btn-mini" title="Remove Range" href="#">
						<i class="icon-remove"></i>
					</a>
				</span>
		      </th>
		    </thead>
		    <tbody>
		      <tr>
		        <th>
		        	12
			      	<span class="pull-right">
				      	<a class="btn btn-mini btn-warning" title="Edit Term" href="#">
							<i class="icon-pencil"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Remove Term" href="#">
							<i class="icon-remove"></i>
						</a>
					</span>
		        </th>
		        <td>
		        	<label id="label-term1-range1" onclick="javascript: edit_rate(1,1);">0.0990</label>
		        	<div id="edit-term1-range1" style="display: none;">
			        	<input type="text" name="term1-range1" id="term1-range1" class="span1" value="0.0990" />
				      	<a class="btn btn-mini btn-success" title="Save Rate" href="#">
							<i class="icon-ok"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Cancel" onclick="javascript: edit_rate(1,1);" href="#">
							<i class="icon-ban-circle"></i>
						</a>
					</div>
		        </td>
		        <td>
		        	<label id="label-term1-range2" onclick="javascript: edit_rate(1,2);">0.0965</label>
		        	<div id="edit-term1-range2" style="display: none;">
		        		<input type="text" name="term1-range2" id="term1-range2" class="span1" value="0.0965" />
				      	<a class="btn btn-mini btn-success" title="Save Rate" href="#">
							<i class="icon-ok"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Cancel" onclick="javascript: edit_rate(1,2);" href="#">
							<i class="icon-ban-circle"></i>
						</a>
					</div>
		        </td>
		        <td>
		        	<label id="label-term1-range3" onclick="javascript: edit_rate(1,3);">0.0954</label>
		        	<div id="edit-term1-range3" style="display: none;">
		        		<input type="text" name="term1-range3" id="term1-range3" class="span1" value="0.0954" />
				      	<a class="btn btn-mini btn-success" title="Save Rate" href="#">
							<i class="icon-ok"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Cancel" onclick="javascript: edit_rate(1,3);" href="#">
							<i class="icon-ban-circle"></i>
						</a>
					</div>
		        </td>
		        <td>
		        	<label id="label-term1-range4" onclick="javascript: edit_rate(1,4);">0.0944</label>
		        	<div id="edit-term1-range4" style="display: none;">
		        		<input type="text" name="term1-range4" id="term1-range4" class="span1" value="0.0944" />
				      	<a class="btn btn-mini btn-success" title="Save Rate" href="#">
							<i class="icon-ok"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Cancel" onclick="javascript: edit_rate(1,4);" href="#">
							<i class="icon-ban-circle"></i>
						</a>
					</div>
		        </td>
		      </tr>
		      <tr>
		        <th>
		        	24
			      	<span class="pull-right">
				      	<a class="btn btn-mini btn-warning" title="Edit Term" href="#">
							<i class="icon-pencil"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Remove Term" href="#">
							<i class="icon-remove"></i>
						</a>
					</span>
		        </th>
		        <td>
		        	<label id="label-term2-range1" onclick="javascript: edit_rate(2,1);">0.0529</label>
		        	<div id="edit-term2-range1" style="display: none;">
		        		<input type="text" name="term2-range1" id="term2-range1" class="span1" value="0.0529" />
				      	<a class="btn btn-mini btn-success" title="Save Rate" href="#">
							<i class="icon-ok"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Cancel" onclick="javascript: edit_rate(2,1);" href="#">
							<i class="icon-ban-circle"></i>
						</a>
					</div>
		        </td>
		        <td>
		        	<label id="label-term2-range2" onclick="javascript: edit_rate(2,2);">0.0502</label>
		        	<div id="edit-term2-range2" style="display: none;">
		        		<input type="text" name="term2-range2" id="term2-range2" class="span1" value="0.0502" />
				      	<a class="btn btn-mini btn-success" title="Save Rate" href="#">
							<i class="icon-ok"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Cancel" onclick="javascript: edit_rate(2,2);" href="#">
							<i class="icon-ban-circle"></i>
						</a>
					</div>
		        </td>
		        <td>
		        	<label id="label-term2-range3" onclick="javascript: edit_rate(2,3);">0.0501</label>
		        	<div id="edit-term2-range3" style="display: none;">
		        		<input type="text" name="term2-range3" id="term2-range3" class="span1" value="0.0501" />
				      	<a class="btn btn-mini btn-success" title="Save Rate" href="#">
							<i class="icon-ok"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Cancel" onclick="javascript: edit_rate(2,3);" href="#">
							<i class="icon-ban-circle"></i>
						</a>
					</div>
		        </td>
		        <td>	
		        	<label id="label-term2-range4" onclick="javascript: edit_rate(2,4);">0.0499</label>
		        	<div id="edit-term2-range4" style="display: none;">
		        		<input type="text" name="term2-range4" id="term2-range4" class="span1" value="0.0499" />
				      	<a class="btn btn-mini btn-success" title="Save Rate" href="#">
							<i class="icon-ok"></i>
						</a> 
				      	<a class="btn btn-danger btn-mini" title="Cancel" onclick="javascript: edit_rate(2,4);" href="#">
							<i class="icon-ban-circle"></i>
						</a>
					</div>
		        </td>
		      </tr>
		    </tbody>
		  </table>
		</div>
		
	</form>
	
</div>