<div class="well">

	<form name="leasingSchemas" id="leasingSchemas" class="form-horizontal" action="" method="post" enctype="application/x-www-form-urlencoded">
		
		<div id="lease-terms-container">
		  <table class="table table-striped table-bordered">
		    <thead>
		      <!-- get all max-cost fields and loop through to display -->
		      <th width="30%">Term (months) </th>
		      <th width="30%">Range</th>
		      <th width="30%">Rate</th>
		      <th width="10%">Action</th>
		    </thead>
		    <tbody>
		      <tr>
		        <td>12 months</td>
		        <td>$0 - $100</td>
		        <td>.0990</td>
		        <td>
		          <a id="add-new-term" class="btn pull-right">
		            <i class="icon-pencil"></i> Edit
		          </a>
		        </td>
		      </tr>
		      <tr>
		        <td>12 months</td>
		        <td>$101 - $1000</td>
		        <td>.0965</td>
		        <td>
		          <a id="add-new-term" class="btn pull-right">
		            <i class="icon-pencil"></i> Edit
		          </a>
		        </td>
		      </tr>
		      <tr>
		        <td>24 months</td>
		        <td>$0 - $100</td>
		        <td>.0529</td>
		        <td>
		          <a id="add-new-term" class="btn pull-right">
		            <i class="icon-pencil"></i> Edit
		          </a>
		        </td>
		      </tr>
		      <tr>
		        <td>
            	  	<div class="input-append">
		              	<input type="text" name="new-term" id="new-term" class="span1" value="" /><span class="add-on">months</span>
	              	</div>
		        </td>
		        <td>
            	  	<div class="input-prepend">
		              	<span class="add-on">$</span><input type="text" name="new-range-min" id="new-range-min" class="span1" value="" style="text-align: right;" />
	              	</div> - 
            	  	<div class="input-prepend">
		              	<span class="add-on">$</span><input type="text" name="new-range-max" id="new-range-max" class="span1" value="" style="text-align: right;" />
	              	</div>
		       	</td>
		        <td>
            	  	<div class="input-prepend">
		              	<span class="add-on">.</span><input type="text" name="new-rate" id="new-rate" class="span1" value="" style="text-align: right;" />
	              	</div>
		       	</td>
		        <td>
		          <a id="add-new-term" class="btn pull-right">
		            <i class="icon-plus-sign"></i> Add
		          </a>
		        </td>
		      </tr>
		    </tbody>
		  </table>
		</div>
		  
	</form>
	
</div>