<?php

/* @var $quote Quotegen_Model_Quote */
$quote = $this->quote;

/**
 * Solution - Solution 1: PrintIQ®
 */
/* @var $section PHPWord_Section */
$section = $this->section;
$section->addPageBreak();
$section->addTitle($this->translate('Your PrintIQ Solution'), 1);
$section->addText($this->translate('Below is a quote for the requested hardware:'));

$quoteDeviceGroups = $quote->getQuoteDeviceGroups();
$groupCount = 0;
$tcStyle = $this->styles->tables->quoteTable;

/* @var $quoteDeviceGroup Quotegen_Model_QuoteDeviceGroup */
foreach ( $this->quote->getQuoteDeviceGroups() as $quoteDeviceGroup )
{
    $table = $section->addTable($tcStyle->tablestyle);
    
    $table->addRow($tcStyle->header->rowheight);
    $table->addCell($tcStyle->col1Width, $tcStyle->header->cell1->cellStyle)->addText($this->translate('Item'), $tcStyle->header->cell1->fontStyle, $tcStyle->header->cell1->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $tcStyle->header->cell2->cellStyle)->addText($this->translate('SKU'), $tcStyle->header->cell2->fontStyle, $tcStyle->header->cell2->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $tcStyle->header->cell3->cellStyle)->addText($this->translate('Description and Features'), $tcStyle->header->cell3->fontStyle, $tcStyle->header->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $tcStyle->header->cell4->cellStyle)->addText($this->translate('Quantity'), $tcStyle->header->cell4->fontStyle, $tcStyle->header->cell4->paragraphStyle);
    
    /* @var $quoteDeviceGroupDevice Quotegen_Model_QuoteDeviceGroupDevice */
    foreach ( $quoteDeviceGroup->getQuoteDeviceGroupDevices() as $quoteDeviceGroupDevice )
    {
        
        $device = $quoteDeviceGroupDevice->getQuoteDevice();
        $table->addRow($tcStyle->device->rowheight);
        // Device Name
        $table->addCell($tcStyle->col1Width, $tcStyle->device->cell1->cellStyle)->addText($device->getName(), $tcStyle->device->cell1->fontStyle, $tcStyle->device->cell1->paragraphStyle);
        // Sku
        $table->addCell($tcStyle->col2Width, $tcStyle->device->cell2->cellStyle)->addText($device->getSku(), $tcStyle->device->cell2->fontStyle, $tcStyle->device->cell2->paragraphStyle);
        // Description and features
        $table->addCell($tcStyle->col3Width, $tcStyle->device->cell3->cellStyle);
        // Quantity
        $table->addCell($tcStyle->col4Width, $tcStyle->device->cell4->cellStyle)->addText(number_format($quoteDeviceGroupDevice->getQuantity()), $tcStyle->device->cell4->fontStyle, $tcStyle->device->cell4->paragraphStyle);
        
        // Get quote device options
        $quoteDeviceOptions = $quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions();
        /* @var $quoteDeviceOption Quotegen_Model_QuoteDeviceOption */
        foreach ( $quoteDeviceOptions as $quoteDeviceOption )
        {
            $table->addRow($tcStyle->option->rowheight);
            $table->addCell($tcStyle->col1Width, $tcStyle->option->cell1->cellStyle)->addText($quoteDeviceOption->getName() . ' (' . number_format($quoteDeviceOption->getQuantity()) . 'x)', $tcStyle->option->cell1->fontStyle, $tcStyle->option->cell1->paragraphStyle);
            $table->addCell($tcStyle->col2Width, $tcStyle->option->cell2->cellStyle)->addText($quoteDeviceOption->getSku(), $tcStyle->option->cell2->fontStyle, $tcStyle->option->cell2->paragraphStyle);
            $table->addCell($tcStyle->col3Width, $tcStyle->option->cell3->cellStyle)->addText($quoteDeviceOption->getDescription(), $tcStyle->option->cell3->fontStyle, $tcStyle->option->cell3->paragraphStyle);
            $table->addCell($tcStyle->col4Width, $tcStyle->option->cell4->cellStyle)->addText();
        }
        
    }
    
    // Show page information in the rows, one for black and the other for.. you got it... color
    $table->addRow($tcStyle->pages->rowheight);
    $table->addCell($tcStyle->col1Width, $tcStyle->pages->cell1->cellStyle)->addText($this->translate('Monochrome Pages'), $tcStyle->pages->cell1->fontStyle, $tcStyle->pages->cell1->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $tcStyle->pages->cell2->cellStyle)->addText();
    $table->addCell($tcStyle->col3width, $tcStyle->pages->cell3->cellStyle)->addText($this->translate('Pages Included Per Month'), $tcStyle->pages->cell3->fontStyle, $tcStyle->pages->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $tcStyle->pages->cell4->cellStyle)->addText(number_format($quoteDeviceGroup->calculateTotalMonochromePages()), $tcStyle->pages->cell4->fontStyle, $tcStyle->pages->cell4->paragraphStyle);
    
    $table->addRow($tcStyle->pages->rowheight);
    $table->addCell($tcStyle->col1Width, $tcStyle->pages->cell1->cellStyle)->addText($this->translate('Color Pages'), $tcStyle->pages->cell1->fontStyle, $tcStyle->pages->cell1->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $tcStyle->pages->cell2->cellStyle)->addText();
    $table->addCell($tcStyle->col3Width, $tcStyle->pages->cell3->cellStyle)->addText($this->translate('Pages Included Per Month'), $tcStyle->pages->cell3->fontStyle, $tcStyle->pages->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $tcStyle->pages->cell4->cellStyle)->addText(number_format($quoteDeviceGroup->calculateTotalColorPages()), $tcStyle->pages->cell4->fontStyle, $tcStyle->pages->cell4->paragraphStyle);
    
    // Show subtotal line
    $table->addRow($tcStyle->subtotal->rowheight);
    $table->addCell($tcStyle->cell1Width, $tcStyle->subtotal->cell1->cellStyle)->addText();
    $table->addCell($tcStyle->span23Width, $tcStyle->subtotal->cell2->cellStyle, 2)->addText($this->translate('Subtotal for group ' . $quoteDeviceGroup->getName()), $tcStyle->subtotal->cell2->fontStyle, $tcStyle->subtotal->cell2->paragraphStyle);
    $table->addCell($tcStyle->cell4Width, $tcStyle->subtotal->cell3->cellStyle)->addText($this->currency($quoteDeviceGroup->calculateMonthlyLeasePrice()), $tcStyle->subtotal->cell3->fontStyle, $tcStyle->subtotal->cell3->paragraphStyle);
    
    $groupCount ++;
    $section->addTextBreak();
}

// Show monthly total
$table = $section->addTable($tcStyle->tablestyle);
$table->addRow($tcStyle->monthlyTotal->rowheight);
$table->addCell($tcStyle->span123Width, $tcStyle->monthlyTotal->cell1->cellStyle, 3)->addText($this->translate('Monthly Total (Term: ' . $quote->getLeaseTerm() . ' Months)'), $tcStyle->monthlyTotal->cell1->fontStyle, $tcStyle->monthlyTotal->cell1->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->monthlyTotal->cell2->cellStyle)->addText($this->currency($quote->calculateQuoteMonthlyLeaseSubtotal()), $tcStyle->monthlyTotal->cell2->fontStyle, $tcStyle->monthlyTotal->cell2->paragraphStyle);

$section->addTextBreak();
$section->addText('This quote is valid for 7 days from the date on the cover of this document. Depending on your requirements, you may be subject to additional charges for installation, insurance, and documentation fees. Please review the contract for details.');
