<?php
/**
 * Solution - Next Steps
 */
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;

$section->addPageBreak();
$section->addTitle($this->translate('Next Steps'), 1);

$section->addText($this->translate('We recommend the following implementation plan for your managed print services program:'));
$section->addTextBreak();
$tc = $this->styles->tables->nextsteps;
$table = $section->addTable($tc->tablestyle);

$table->addRow($tc->body->rowheight);
$table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('Today:'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle);
$cell->addListItem($this->translate('Remote monitoring software is already installed.'), 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);
$cell->addListItem($this->translate('Select a department or floor for initial migration to managed print services.'), 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);

$table->addRow($tc->body->rowheight);
$table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('Within 30 days:'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle);
$cell->addListItem($this->translate('Migrate the selected department or floor to managed print services.'), 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);

$table->addRow($tc->body->rowheight);
$table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('Within 90 days:'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle);
$cell->addListItem($this->translate('Migrate all other desired locations to managed print services.'), 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);

$table->addRow($tc->body->rowheight);
$table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('Every six months:'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle);
$cell->addListItem($this->translate('Evaluation and adjustment of recommendations as needed.'), 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);

$section->addTextBreak();

$section->addText($this->translate('Whether you are looking for a comprehensive managed print services plan that includes new equipment, or are looking for assistance in maintaining your existing printer fleet, we can design a solution that meets your specific business needs. Let us take care of your print so you can get back to business.'));
$section->addText($this->translate('1-855-OD-GO-MPS'), 'bold_text');
$section->addText($this->translate('1-855-634-6677 '), 'small_italic_text');
$section->addText($this->translate('Copyright 2013 Office Depot, Inc. All Rights Reserved.'), 'small_italic_text');
$section->addText($this->translate('The Office Depot name and logo are the registered trademarks of The Office Club, Inc.'), 'small_italic_text');