<?php

$this->headScript()->appendFile($this->baseUrl('js/app/legacy/preferences/TonerVendors.js'));

/* @var $form \MPSToolbox\Settings\Form\AllSettingsForm */
$form = $this->element;

$currentFleetSettingsForm  = $form->getSubForm('currentFleetSettingsForm');
$proposedFleetSettingsForm = $form->getSubForm('proposedFleetSettingsForm');
$genericSettingsForm       = $form->getSubForm('genericSettingsForm');
$quoteSettingsForm         = $form->getSubForm('quoteSettingsForm');
$optimizationSettingsForm  = $form->getSubForm('optimizationSettingsForm');

$is_pricing_administrator=false;
$roles = \MPSToolbox\Legacy\Mappers\UserMapper::getInstance()->findCurrent()->getUserRoles();
foreach ($roles as $role) {
    if ($role->roleId==3) {
        $is_pricing_administrator=true;
    }
}

?>

<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <fieldset>
                <legend>Current Fleet Settings
                    <small>
                        <i class="fa fa-fw fa-question-circle js-tooltip" data-toggle="tooltip" data-placement="right" title="These values are used to determine the current costs <strong>that you will show the customer</strong>. These values are set up by your administrator for all accounts and do not need to be changed for every report."></i>
                    </small>
                </legend>
                <div class="form-group <?= ($currentFleetSettingsForm->getElement('currentUseDevicePageCoverages')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($currentFleetSettingsForm->getElement('currentUseDevicePageCoverages'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormBootstrapSwitch($currentFleetSettingsForm->getElement('currentUseDevicePageCoverages'), ['js-yes-no-switch']) ?>
                        <?= $this->RenderFormDescription($currentFleetSettingsForm->getElement('currentUseDevicePageCoverages')) ?>
                        <?= $this->RenderFormElementErrors($currentFleetSettingsForm->getElement('currentUseDevicePageCoverages')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($currentFleetSettingsForm->getElement('currentPageCoverageMono')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($currentFleetSettingsForm->getElement('currentPageCoverageMono'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($currentFleetSettingsForm->getElement('currentPageCoverageMono'), [], null, '%') ?>
                        <?= $this->RenderFormElementErrors($currentFleetSettingsForm->getElement('currentPageCoverageMono')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($currentFleetSettingsForm->getElement('currentPageCoverageColor')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($currentFleetSettingsForm->getElement('currentPageCoverageColor'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($currentFleetSettingsForm->getElement('currentPageCoverageColor'), [], null, '%') ?>
                        <?= $this->RenderFormElementErrors($currentFleetSettingsForm->getElement('currentPageCoverageColor')) ?>
                    </div>
                </div>

<? if ($is_pricing_administrator) { ?>
                <div class="form-group <?= ($currentFleetSettingsForm->getElement('currentLevel')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($currentFleetSettingsForm->getElement('currentLevel'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormSelect($currentFleetSettingsForm->getElement('currentLevel')) ?>
                        <?= $this->RenderFormElementErrors($currentFleetSettingsForm->getElement('currentLevel')) ?>
                    </div>
                </div>
<? } ?>

                <div class="form-group <?= ($currentFleetSettingsForm->getElement('currentMonochromeRankSetArray')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($currentFleetSettingsForm->getElement('currentMonochromeRankSetArray'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormSelect($currentFleetSettingsForm->getElement('currentMonochromeRankSetArray')) ?>
                        <?= $this->RenderFormDescription($currentFleetSettingsForm->getElement('currentMonochromeRankSetArray')) ?>
                        <?= $this->RenderFormElementErrors($currentFleetSettingsForm->getElement('currentMonochromeRankSetArray')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($currentFleetSettingsForm->getElement('currentColorRankSetArray')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($currentFleetSettingsForm->getElement('currentColorRankSetArray'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormSelect($currentFleetSettingsForm->getElement('currentColorRankSetArray')) ?>
                        <?= $this->RenderFormDescription($currentFleetSettingsForm->getElement('currentColorRankSetArray')) ?>
                        <?= $this->RenderFormElementErrors($currentFleetSettingsForm->getElement('currentColorRankSetArray')) ?>
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="col-sm-12 col-md-6">
            <fieldset>
                <legend>Proposed Fleet Settings
                    <small>
                        <i class="fa fa-fw fa-question-circle js-tooltip" data-toggle="tooltip" data-placement="right" title="These values are used to determine <strong>your costs</strong> to manage the customer. They may be different than what you wish to share with customers. These values are setup by your administrator for all accounts and do not need to be changed for every report."></i>
                    </small>
                </legend>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedUseDevicePageCoverages')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedUseDevicePageCoverages'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormBootstrapSwitch($proposedFleetSettingsForm->getElement('proposedUseDevicePageCoverages'), ['js-yes-no-switch']) ?>
                        <?= $this->RenderFormDescription($proposedFleetSettingsForm->getElement('proposedUseDevicePageCoverages')) ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedUseDevicePageCoverages')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedPageCoverageMono')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedPageCoverageMono'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($proposedFleetSettingsForm->getElement('proposedPageCoverageMono'), [], null, '%') ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedPageCoverageMono')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedPageCoverageColor')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedPageCoverageColor'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($proposedFleetSettingsForm->getElement('proposedPageCoverageColor'), [], null, '%') ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedPageCoverageColor')) ?>
                    </div>
                </div>

<? if ($is_pricing_administrator) { ?>
                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedLevel')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedLevel'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormSelect($proposedFleetSettingsForm->getElement('proposedLevel')) ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedLevel')) ?>
                    </div>
                </div>
<? } ?>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedMonochromeRankSetArray')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedMonochromeRankSetArray'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormSelect($proposedFleetSettingsForm->getElement('proposedMonochromeRankSetArray')) ?>
                        <?= $this->RenderFormDescription($proposedFleetSettingsForm->getElement('proposedMonochromeRankSetArray')) ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedMonochromeRankSetArray')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedColorRankSetArray')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedColorRankSetArray'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormSelect($proposedFleetSettingsForm->getElement('proposedColorRankSetArray')) ?>
                        <?= $this->RenderFormDescription($proposedFleetSettingsForm->getElement('proposedColorRankSetArray')) ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedColorRankSetArray')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedDefaultAdminCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedDefaultAdminCostPerPage'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($proposedFleetSettingsForm->getElement('proposedDefaultAdminCostPerPage'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedDefaultAdminCostPerPage')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedDefaultMonochromeLaborCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedDefaultMonochromeLaborCostPerPage'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($proposedFleetSettingsForm->getElement('proposedDefaultMonochromeLaborCostPerPage'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedDefaultMonochromeLaborCostPerPage')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedDefaultMonochromePartsCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedDefaultMonochromePartsCostPerPage'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($proposedFleetSettingsForm->getElement('proposedDefaultMonochromePartsCostPerPage'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedDefaultMonochromePartsCostPerPage')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedDefaultColorLaborCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedDefaultColorLaborCostPerPage'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($proposedFleetSettingsForm->getElement('proposedDefaultColorLaborCostPerPage'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedDefaultColorLaborCostPerPage')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($proposedFleetSettingsForm->getElement('proposedDefaultColorPartsCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($proposedFleetSettingsForm->getElement('proposedDefaultColorPartsCostPerPage'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($proposedFleetSettingsForm->getElement('proposedDefaultColorPartsCostPerPage'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($proposedFleetSettingsForm->getElement('proposedDefaultColorPartsCostPerPage')) ?>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <fieldset>
                <legend>Generic Settings
                    <small>
                        <i class="fa fa-fw fa-question-circle js-tooltip" data-toggle="tooltip" data-placement="right" title="When analyzing a fleet, these settings are used when assigning a financial cost for devices you may not have complete information for, such as a competitive leased device."></i>
                    </small>
                </legend>

                <div class="form-group <?= ($genericSettingsForm->getElement('defaultMonthlyLeasePayment')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($genericSettingsForm->getElement('defaultMonthlyLeasePayment'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($genericSettingsForm->getElement('defaultMonthlyLeasePayment'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('defaultMonthlyLeasePayment')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($genericSettingsForm->getElement('defaultPrinterCost')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($genericSettingsForm->getElement('defaultPrinterCost'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($genericSettingsForm->getElement('defaultPrinterCost'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('defaultPrinterCost')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($genericSettingsForm->getElement('defaultEnergyCost')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($genericSettingsForm->getElement('defaultEnergyCost'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($genericSettingsForm->getElement('defaultEnergyCost'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('defaultEnergyCost')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($genericSettingsForm->getElement('leasedMonochromeCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($genericSettingsForm->getElement('leasedMonochromeCostPerPage'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($genericSettingsForm->getElement('leasedMonochromeCostPerPage'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('leasedMonochromeCostPerPage')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($genericSettingsForm->getElement('leasedColorCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($genericSettingsForm->getElement('leasedColorCostPerPage'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($genericSettingsForm->getElement('leasedColorCostPerPage'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('leasedColorCostPerPage')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($genericSettingsForm->getElement('mpsMonochromeCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($genericSettingsForm->getElement('mpsMonochromeCostPerPage'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($genericSettingsForm->getElement('mpsMonochromeCostPerPage'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('mpsMonochromeCostPerPage')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($genericSettingsForm->getElement('mpsColorCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($genericSettingsForm->getElement('mpsColorCostPerPage'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($genericSettingsForm->getElement('mpsColorCostPerPage'), [], '$') ?>
                        <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('mpsColorCostPerPage')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($genericSettingsForm->getElement('tonerMargin')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($genericSettingsForm->getElement('tonerMargin'), ['col-md-6']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormText($genericSettingsForm->getElement('tonerMargin'), [], null, '%') ?>
                        <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('tonerMargin')) ?>
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="col-sm-12 col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <fieldset>
                        <legend>Target Cost Settings</legend>

                        <div class="form-group <?= ($genericSettingsForm->getElement('targetMonochromeCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($genericSettingsForm->getElement('targetMonochromeCostPerPage'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($genericSettingsForm->getElement('targetMonochromeCostPerPage'), [], '$') ?>
                                <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('targetMonochromeCostPerPage')) ?>
                            </div>
                        </div>

                        <div class="form-group <?= ($genericSettingsForm->getElement('targetColorCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($genericSettingsForm->getElement('targetColorCostPerPage'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($genericSettingsForm->getElement('targetColorCostPerPage'), [], '$') ?>
                                <?= $this->RenderFormElementErrors($genericSettingsForm->getElement('targetColorCostPerPage')) ?>
                            </div>
                        </div>

                        <div class="form-group <?= ($optimizationSettingsForm->getElement('optimizedTargetMonochromeCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($optimizationSettingsForm->getElement('optimizedTargetMonochromeCostPerPage'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($optimizationSettingsForm->getElement('optimizedTargetMonochromeCostPerPage'), [], '$') ?>
                                <?= $this->RenderFormElementErrors($optimizationSettingsForm->getElement('optimizedTargetMonochromeCostPerPage')) ?>
                            </div>
                        </div>

                        <div class="form-group <?= ($optimizationSettingsForm->getElement('optimizedTargetColorCostPerPage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($optimizationSettingsForm->getElement('optimizedTargetColorCostPerPage'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($optimizationSettingsForm->getElement('optimizedTargetColorCostPerPage'), [], '$') ?>
                                <?= $this->RenderFormElementErrors($optimizationSettingsForm->getElement('optimizedTargetColorCostPerPage')) ?>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-12">
                    <fieldset>
                        <legend>Default Hardware Quote Settings</legend>

                        <div class="form-group <?= ($quoteSettingsForm->getElement('defaultDeviceMargin')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($quoteSettingsForm->getElement('defaultDeviceMargin'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($quoteSettingsForm->getElement('defaultDeviceMargin'), [], null, '%') ?>
                                <?= $this->RenderFormElementErrors($quoteSettingsForm->getElement('defaultDeviceMargin')) ?>
                            </div>
                        </div>

                        <div class="form-group <?= ($quoteSettingsForm->getElement('defaultPageMargin')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($quoteSettingsForm->getElement('defaultPageMargin'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($quoteSettingsForm->getElement('defaultPageMargin'), [], null, '%') ?>
                                <?= $this->RenderFormElementErrors($quoteSettingsForm->getElement('defaultPageMargin')) ?>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-12">
                    <fieldset>
                        <legend>Optimization - General Settings</legend>

                        <div class="form-group <?= ($optimizationSettingsForm->getElement('costThreshold')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($optimizationSettingsForm->getElement('costThreshold'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($optimizationSettingsForm->getElement('costThreshold'), [], '$') ?>
                                <?= $this->RenderFormElementErrors($optimizationSettingsForm->getElement('costThreshold')) ?>
                            </div>
                        </div>
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        <legend>Optimization - Monochrome to Color Upgrade</legend>

                        <div class="form-group <?= ($optimizationSettingsForm->getElement('autoOptimizeFunctionality')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($optimizationSettingsForm->getElement('autoOptimizeFunctionality'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormBootstrapSwitch($optimizationSettingsForm->getElement('autoOptimizeFunctionality'), ['js-enabled-switch']) ?>
                                <?= $this->RenderFormDescription($optimizationSettingsForm->getElement('autoOptimizeFunctionality')) ?>
                                <?= $this->RenderFormElementErrors($optimizationSettingsForm->getElement('autoOptimizeFunctionality')) ?>
                            </div>
                        </div>

                        <div class="form-group <?= ($optimizationSettingsForm->getElement('lossThreshold')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($optimizationSettingsForm->getElement('lossThreshold'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($optimizationSettingsForm->getElement('lossThreshold'), [], '$') ?>
                                <?= $this->RenderFormElementErrors($optimizationSettingsForm->getElement('lossThreshold')) ?>
                            </div>
                        </div>

                        <div class="form-group <?= ($optimizationSettingsForm->getElement('blackToColorRatio')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($optimizationSettingsForm->getElement('blackToColorRatio'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($optimizationSettingsForm->getElement('blackToColorRatio'), [], null, '%') ?>
                                <?= $this->RenderFormElementErrors($optimizationSettingsForm->getElement('blackToColorRatio')) ?>
                            </div>
                        </div>

                        <div class="form-group <?= ($optimizationSettingsForm->getElement('minimumPageCount')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                            <?= $this->RenderFormLabel($optimizationSettingsForm->getElement('minimumPageCount'), ['col-md-6']) ?>

                            <div class="col-md-6">
                                <?= $this->RenderFormText($optimizationSettingsForm->getElement('minimumPageCount'), [], null, null) ?>
                                <?= $this->RenderFormElementErrors($optimizationSettingsForm->getElement('minimumPageCount')) ?>
                            </div>

                    </fieldset>
                </div>
            </div>
        </div>
    </div>

<?= $form->getDisplayGroup('form-actions'); ?>

<?= $this->RenderFormClose($form) ?>