<div class="page-header">
    <h1>Dealers -
        <small>Dealer Management</small>
    </h1>
</div>
<div class='well'>
    <div class="clearfix">
        <a class="btn btn-success pull-right btn-small create-button" href="<?php echo $this->url(array('action' => 'create')) ?>">
            <i class="icon-white icon-plus-sign"></i> Create new</a>
    </div>
    <?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
        <table class="table table-striped table-condensed table-bordered">
            <thead>
            <tr>
                <th style="width: 30px;">ID</th>
                <th>Dealer Name</th>
                <th>Date Created</th>
                <th>User Licenses</th>
                <th style="width: 80px;">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->paginator->getCurrentItems() as $dealer) : /* @var $dealer Admin_Model_Dealer */ ?>

                <tr>
                    <td><?php echo $this->escape($dealer->id); ?></td>
                    <td><?php echo $this->escape($dealer->dealerName); ?></td>
                    <td><?php echo (new \Carbon\Carbon($dealer->dateCreated))->toFormattedDateString(); ?></td>
                    <td><?php echo $this->escape($dealer->userLicenses); ?></td>
                    <td>
                        <div class="btn-group">
                            <?php if ($dealer->id == 1) : ?>
                                <span class="btn btn-warning disabled"><i class="icon-pencil"></i></span>
                                <span class="btn btn-danger disabled"><i class="icon-trash"></i></span>
                            <?php else : ?>
                                <a class="btn btn-warning" title="Edit" href="<?php echo $this->url(array('action' => 'edit', 'id' => $dealer->id)); ?>"><i class="icon-pencil"></i></a>
                                <a class="btn btn-danger" title="Delete" href="<?php echo $this->url(array('action' => 'delete', 'id' => $dealer->id)); ?>"><i class="icon-trash"></i></a>
                            <?php endif; ?>
                        </div>
                    </td>
                </tr>

            <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator); ?>
    <?php else : ?>
        <h2>There are no dealers.</h2>
    <?php endif ?>
</div>
