<?php

use MPSToolbox\Legacy\Models\DealerModel;

?>
<div class='container'>
    <div class="clearfix">
        <a class="btn btn-success pull-right btn-sm create-button" href="<?php


        echo $this->url([], 'admin.dealers.create') ?>">
            <i class="glyphicon glyphicon-plus-sign"></i> Create new</a>
    </div>
    <?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
        <table class="table table-striped table-condensed table-bordered">
            <thead>
            <tr>
                <th style="width: 30px;">ID</th>
                <th>Dealer Name</th>
                <th>Date Created</th>
                <th>User Licenses</th>
                <th style="width: 80px;">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $dealer DealerModel */ ?>
            <?php foreach ($this->paginator->getCurrentItems() as $dealer) : ?>
                <tr>
                    <td><?= $this->escape($dealer->id); ?></td>
                    <td><?= $this->escape($dealer->dealerName); ?></td>
                    <td><?= (new \Carbon\Carbon($dealer->dateCreated))->toFormattedDateString(); ?></td>
                    <td><?= $this->escape($dealer->userLicenses); ?></td>
                    <td>
                        <div class="btn-group btn-group-justified">
                            <?php if ($dealer->id == 1 && $this->Identity()->id != 1) : ?>
                                <span class="btn btn-xs btn-warning disabled"><i class="glyphicon glyphicon-eye-close"></i></span>
                            <?php else : ?>
                                <a class="btn btn-xs btn-info" title="Edit" href="<?= $this->url(['id' => $dealer->id], 'admin.dealers.view'); ?>">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </a>
                                <?php if ($dealer->id == 1) : ?>
                                    <span class="btn btn-xs btn-danger disabled"><i class="glyphicon glyphicon-trash"></i></span>
                                <?php else : ?>
                                    <a class="btn btn-xs btn-danger" title="Delete" href="<?= $this->url(['id' => $dealer->id], 'admin.dealers.delete'); ?>">
                                        <i class="glyphicon glyphicon-trash"></i>
                                    </a>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?= $this->paginationControl($this->paginator); ?>
    <?php else : ?>
        <h2>There are no dealers.</h2>
    <?php endif ?>
</div>
