<?php

use MPSToolbox\Legacy\Mappers\DealerMapper;
use MPSToolbox\Legacy\Models\DealerModel;
use MPSToolbox\Legacy\Models\UserModel;

/* @var $dealer DealerModel */
$dealer = $this->dealer;
?>
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="pull-right btn btn-warning btn-xs" href="<?= $this->url(array('id' => $dealer->id), 'admin.dealers.edit') ?>">
                <i class="glyphicon glyphicon-pencil"></i>
                Edit
            </a>

            <h2>#<?= number_format($dealer->id) ?> - <?= $dealer->dealerName ?> -
                <small>Created on <?= $dealer->dateCreated ?></small>
            </h2>
        </div>
        <div class="panel-body">
            <h3>Dealer Logo</h3>
            <?php if ($dealer->dealerLogoImageId > 0) : ?>
                <p class="text-center">
                    <img src="<?= $this->baseUrl($dealer->getDealerLogoImageFile()) ?>" alt="Tangent MTW Dealer Logo File" style="box-shadow: 0 0 2px #ccc;">
                </p>
            <?php else : ?>
                <div class="alert alert-info">
                    <i class="fa fa-fw fa-info-circle"></i> Dealer does not have a logo file!
                </div>
            <?php endif; ?>
            <hr>
            <h3>Toner Vendors</h3>

            <p>
                <a class="btn btn-warning btn-xs" href="<?= $this->url(array('id' => $dealer->id), 'admin.dealers.edit-toner-vendors') ?>">
                    <i class="glyphicon glyphicon-pencil"></i>
                    Edit Toner Vendors
                </a>
            </p>
            <hr>
            <h3>RMS Providers</h3>

            <p>
                <a class="btn btn-warning btn-xs" href="<?= $this->url(array('id' => $dealer->id), 'admin.dealers.edit-rms-providers') ?>">
                    <i class="glyphicon glyphicon-pencil"></i>
                    Edit RMS Providers
                </a>
            </p>
            <hr>
            <h3>Users -
                <small><?= number_format($dealer->getNumberOfLicensesUsed()) ?> / <?= number_format($dealer->userLicenses) ?></small>
                <a class="btn btn-success btn-xs create-button" href="<?= $this->url(array('dealerId' => $dealer->id), 'admin.dealers.create-user') ?>">
                    <i class="glyphicon glyphicon-plus-sign"></i>
                    Add User
                </a>
            </h3>

            <div class="progress progress-striped">
                <?php $width = count($dealer->getUsers()) / $dealer->userLicenses * 100; ?>
                <div class="bar <?= (count($dealer->getUsers()) < $dealer->userLicenses) ? '' : 'bar-danger'; ?>" style="width: <?= ($width > 100) ? 100 : $width . '%' ?>;"></div>
            </div>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Email</th>
                    <th>Name</th>
                    <th style="width: 70px;">Login Attempts</th>
                    <th style="width: 100px;">Frozen Until</th>
                    <th style="width: 60px;">Locked</th>
                    <th style="width: 180px;">Last Seen</th>
                    <th style="width: 80px;">Action</th>
                </tr>
                </thead>
                <tbody>
                <tr class="info">
                </tr>
                <?php if (count($dealer->getUsers()) > 0) : ?>
                    <?php foreach ($dealer->getUsers() as $user) : ?>
                        <tr>
                            <td><?= $user->email; ?></td>
                            <td><?= $user->firstname; ?> <?= $user->lastname; ?></td>
                            <td style="text-align: center;"><?= $user->loginAttempts; ?></td>
                            <td><?= ($user->isFrozen()) ? $user->frozenUntil : ""; ?></td>
                            <td style="text-align: center;"><?= ($user->locked) ? "Yes" : "No"; ?></td>
                            <td>
                                <span class="js-tooltip" data-toggle="tooltip" title="<?= $user->lastSeen ?>"><i class="fa fa-fw fa-clock-o"></i> <?= ($user->lastSeen === null) ? "Never" : (new \Carbon\Carbon($user->lastSeen))->diffForHumans(); ?></span>
                            </td>
                            <td>
                                <div class="btn-group btn-group-xs">
                                    <?php if ($user->id == 1 && $this->identity()->id !== 1) : ?>
                                        <span class="btn btn-warning btn-mini disabled"><i class="glyphicon glyphicon-pencil"></i></span>
                                    <?php else : ?>
                                        <a class="btn btn-warning btn-mini" title="Edit User" href="<?= $this->url(array('id' => $user->id, 'dealerId' => $dealer->id), 'admin.dealers.users.edit') ?>">
                                            <i class="glyphicon glyphicon-pencil"></i></a>
                                        <?php if ($user->id == 1) : ?>
                                            <span class="btn btn-danger btn-mini disabled"><i class="glyphicon glyphicon-trash"></i></span>
                                        <?php else : ?>
                                            <a class="btn btn-danger btn-mini" title="Delete User" href="<?= $this->url(array('id' => $user->id, 'dealerId' => $dealer->id), 'admin.users.delete') ?>"><i class="glyphicon glyphicon-trash"></i></a>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                    <tr class="warning">
                        <td colspan="8">No users added yet.</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>

        </div>

    </div>
    <div class="well">
        <a class="btn btn-default" href="<?= $this->url(array(), 'admin.dealers') ?>">
            <i class="glyphicon glyphicon-arrow-left"></i>
            Go Back
        </a>
    </div>
</div>