<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
$graphs = $proposal->getGraphs();
?>
<div class="h1">Analysis: Service and Supplies Logistics</div>
<br />
<table cellspacing="0" class="gradesTable">
    <tr>
        <td class="gradeDescription">
            <p><?php echo $proposal->getRanking()->getSuppliesAndServiceLogistics()->RankingText; ?></p>
        </td>
        <td class="gradeNumber"><?php echo number_format($proposal->getRanking()->getSuppliesAndServiceLogistics()->Rank, 1); ?></td>
    </tr>
</table>
<br />
<div class="pheader">Printing Device Management Breakdown</div>
<p>Different types of printing devices are managed in different ways-newer networked printers can be managed with remote monitoring software; leased multifunction devices are typically managed by the vendor who sold the machine; devices not connected to the network, such as inkjets and some older printers, are difficult to manage because you cannot monitor them with software.</p>
<br />
<div class="center">
    <table>
        <tbody>
            <tr>
                <td width="70"></td>
                <td><img src="<?php echo $graphs[1]; ?>" /></td> <!-- Devices leased/Devices Purchased -->
                <td><img src="<?php echo $graphs[2]; ?>" /></td> <!-- Monthly pages on leased MFPs/Monthly pages on devices not leased -->
                <td width="70"></td>
            </tr>
        </tbody>
    </table>
</div>
<br />
<?php
$inkjetString = "less than 10%";
if ($proposal->getPercentPrintingDoneOnInkjet() == 50)
{
    $inkjetString = "more than 50%";
}
else if ($proposal->getPercentPrintingDoneOnInkjet() == 38)
{
    $inkjetString = "26% to 50%";
}
else if ($proposal->getPercentPrintingDoneOnInkjet() == 18)
{
    $inkjetString = "10% to 25%";
}
?>
<p>Based on your questionnaire, <strong><?php echo $inkjetString; ?> of your printing is done on inkjet devices</strong>. We did not monitor inkjet machines that are not connected to the network, and on average, pages printed to inkjet printers cost three times more than pages printed to laser devices. Without being on the network, users also cannot share these devices. There are some instances where desktop printers are appropriate, for instance, if a single user requires confidential, high-convenience printing. We can help you consolidate desktop hardware where appropriate, and where desktop printing is required, we can help you select network-capable equipment so your desktop printing can be managed with the rest of your office print.</p>
<br />
<?php if (count($proposal->getExcludedDevices()) > 0) :?>
<p><?php echo count($proposal->getExcludedDevices())?> devices were not included in the analysis due to lack of data or model information. See the Appendix in the PrintIQ Your Solution document for the list of excluded device(s).</p>
<?php endif; ?>
<div class="pheader">Efficiency of Break-Fix Service</div>
<p>Based on your questionnaire responses, we discovered the following:</p>
<table cellspacing="0" class="bold" style="font-size: 10.5pt; margin: 6pt 0;">
    <tr>
        <td style="width: 470px;">Number of printer repairs per month</td>
        <td style="width: 175px;" class="right"><?php echo number_format($proposal->getNumberOfRepairs()); ?></td>
    </tr>
    <tr>
        <td>Average time between printer breaking down and printer being fixed</td>
        <td class="right"><?php echo $proposal->getAverageTimeBetweenBreakdownAndFix(); ?> day(s)</td>
    </tr>
    <tr>
        <td>Annual downtime resulting from printer breakdowns<br />(Based on an 8 hour work day)</td>
        <td class="right"><?php echo number_format($proposal->getAnnualDowntimeFromBreakdowns(),0); ?> hour(s)</td>
    </tr>
</table>
<br />
<p>Office Depot can provide next-day service for your printer fleet.</p>
<br />
<div class="pheader">Number of Vendors</div>
<p>Based on your questionnaire responses, we discovered the following:</p>
<table cellspacing="0" class="bold" style="font-size: 10.5pt">
    <tr>
        <td style="width: 500px;">Number of vendors used to source printing hardware, supplies and service</td>
        <td style="width: 145px;" class="right"><?php echo $proposal->getNumberOfVendors(); ?></td>
    </tr>
    <tr>
        <td>Number of orders for ink and toner executed annually</td>
        <td class="right"><?php echo $proposal->getNumberOfAnnualInkTonerOrders(); ?></td>
    </tr>
    <tr>
        <td>Estimated annual cost to execute ink and toner orders</td>
        <td class="right">$<?php echo number_format($proposal->getCostOfExecutingSuppliesOrders()); ?></td>
    </tr>
</table>
<br />
<p>Time spent dealing with multiple vendors could be better spent focusing on your core business tasks. Office Depot can bundle your supplies and service into a single invoice - and if you need new hardware, that can be included too.</p>
<br />
<div class="pheader">Number of Printing Device Models and Supply Types</div>
<p>Out of your <strong><?php echo $proposal->getDeviceCount(); ?></strong> networked printing devices, you have of <strong><?php echo $proposal->getNumberOfUniqueModels(); ?></strong> different models. Each section of the chart below represents a single model type. We estimate that <strong><?php echo count($proposal->getLeasedDevices()); ?></strong> of your printing devices are leased machines, for which supplies are included in your contract. The <strong><?php echo count($proposal->getPurchasedDevices()); ?></strong> remaining machines consist of <strong><?php echo $proposal->getNumberOfUniquePurchasedModels(); ?></strong> different models and use <strong><?php echo $proposal->getNumberOfUniquePurchasedToners(); ?></strong> different supply types. If you hold two of each supply in inventory, you have an estimated <strong>$<?php echo number_format($proposal->getCashHeldInInventory()); ?> in operating cash held in printer supplies inventory</strong> at any given time.</p>
<div class="center">
    <img src="<?php echo $graphs[3]; ?>" /> <!--  Giant pie chart -->
</div>
<p>By using printing devices with the same supplies, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space required. Office Depot can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.</p>