<?php
/* @var $form Dealermanagement_Form_Dealer_Branding */
$form = $this->element;
$this->headScript()->appendFile($this->baseUrl('/js/colorTextbox.js'));
?>
<form class="form-horizontal" method="<?= $form->getMethod() ?>" action="<?= $form->getAction() ?>">
    <fieldset>
        <legend>Text Variables</legend>
        <?= $form->getElement('dealerName') ?>
        <?= $form->getElement('shortDealerName') ?>
        <?= $form->getElement('mpsProgramName') ?>
        <?= $form->getElement('shortMpsProgramName') ?>
        <?= $form->getElement('jitProgramName') ?>
        <?= $form->getElement('shortJitProgramName') ?>
    </fieldset>
    <fieldset>
        <legend>Generic Report Colors</legend>
        <?= $form->getElement('titlePageTitleFontColor') ?>
        <?= $form->getElement('titlePageTitleBackgroundColor') ?>
        <?= $form->getElement('titlePageInformationFontColor') ?>
        <?= $form->getElement('titlePageInformationBackgroundColor') ?>
        <?= $form->getElement('h1FontColor') ?>
        <?= $form->getElement('h1BackgroundColor') ?>
        <?= $form->getElement('h2FontColor') ?>
        <?= $form->getElement('h2BackgroundColor') ?>
    </fieldset>
    <fieldset>
        <legend>Graph Colors</legend>
        <?= $form->getElement('graphCustomerColor') ?>
        <?= $form->getElement('graphDealerColor') ?>
        <?= $form->getElement('graphPositiveColor') ?>
        <?= $form->getElement('graphNegativeColor') ?>
        <?= $form->getElement('graphCompatibleDeviceColor') ?>
        <?= $form->getElement('graphNotCompatibleDeviceColor') ?>
        <?= $form->getElement('graphMonoDeviceColor') ?>
        <?= $form->getElement('graphColorDeviceColor') ?>
        <?= $form->getElement('graphCopyCapableDeviceColor') ?>
        <?= $form->getElement('graphDuplexCapableDeviceColor') ?>
        <?= $form->getElement('graphFaxCapableDeviceColor') ?>
        <?= $form->getElement('graphPurchasedDeviceColor') ?>
        <?= $form->getElement('graphLeasedDeviceColor') ?>
        <?= $form->getElement('graphExcludedDeviceColor') ?>
        <?= $form->getElement('graphIndustryAverageColor') ?>
        <?= $form->getElement('graphKeepDeviceColor') ?>
        <?= $form->getElement('graphReplacedDeviceColor') ?>
        <?= $form->getElement('graphDoNotRepairDeviceColor') ?>
        <?= $form->getElement('graphRetireDeviceColor') ?>
        <?= $form->getElement('graphManagedDeviceColor') ?>
        <?= $form->getElement('graphManageableDeviceColor') ?>
        <?= $form->getElement('graphFutureReviewDeviceColor') ?>
        <?= $form->getElement('graphJitCompatibleDeviceColor') ?>
        <?= $form->getElement('graphCurrentSituationColor') ?>
        <?= $form->getElement('graphNewSituationColor') ?>
        <?= $form->getElement('graphAgeOfDevices1') ?>
        <?= $form->getElement('graphAgeOfDevices2') ?>
        <?= $form->getElement('graphAgeOfDevices3') ?>
        <?= $form->getElement('graphAgeOfDevices4') ?>
    </fieldset>

    <?= $form->getDisplayGroup('actions') ?>
</form>