<?php $this->placeholder('ReportNav')->set($this->render('_partials/reportMenu.phtml')); ?>
<div class="jumbotron">
    <div class='container'>
        <h1>Your reports are ready.</h1>

        <p>Please select a report from the list. After verifying the contents of your reports, you may download a copy by selecting your desired output format from top right corner of each report.</p>

        <?php if (My_Feature::canAccess(My_Feature::HARDWARE_QUOTE)) : ?>
            <?= $this->form ?>
        <?php endif; ?>
    </div>
</div>