<?php $this->headScript()->appendFile($this->baseUrl('js/hardwareoptimization/deviceListings.js')); ?>
<h4> Manage Device Swaps </h4>

<div class="modal hide">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">x</a>
        <h3 style="text-align: center">Add Device Swap</h3>
    </div>
    <div class="modal-body well" style="height: 300px;">
        <?php echo $this->form; ?>
        <button type="submit" id="saveTest" class="btn btn-primary">Submit</button>
    </div>
</div>

<div class="well">
    <button id="trigger"  class="btn btn-success">Create new</button>
    <table id='deviceSwapsTable' style="width: 100%" class="scroll">
        <tr>
            <td></td>
        </tr>
    </table>
    <sup>*</sup><em>Cost per page for devices are derived using OEM toners.</em>
</div>
