<?php $this->headScript()->appendFile($this->baseUrl('js/hardwareoptimization/deviceListings.js')); ?>
<h4> Manage Device Swaps </h4>

<div class="modal hide" id="deviceAdd">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">x</a>

        <h3 style="text-align: center">Create New Device Swap</h3>
    </div>
    <div class="modal-body well" style="height: 375px;">
        <div class="alert" id="save-error" style="display:none;">

        </div>
        <?php echo $this->form; ?>
        <div style="text-align: center">
            <button type="button" id="cancelSave" class="btn btn-inverse" style="width: 40%; padding: 4px;">Cancel</button>
            <button type="button" id="saveDevice" class="btn btn-success" style="width: 40%; padding: 4px;">Submit</button>
        </div>
        <br /><br />
        <em> Only devices from the hardware library that have "Can Sell" checked qualify to be a device swap.</em>
    </div>
</div>

<div class="modal hide" id="deleteModal">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">x</a>

        <h3 style="text-align: center">Confirm Delete Device Swap</h3>
    </div>
    <div class="modal-body well" style="height: 50px; text-align: center">
        <button type="button" id="cancelDeviceBtn" class="btn btn-inverse" style="width: 40%; padding: 4px;">Cancel</button>
        <button type="button" id="deleteDeviceBtn" class="btn btn-danger" style="width: 40%; padding: 4px;">Delete</button>
    </div>
</div>

<div class="well">
    <button id="createNewBtn" class="btn btn-success" style="float:right">Create new</button>
    <br /><br />

    <table id='deviceSwapsTable' style="width: 100%" class="scroll">
        <tr>
            <td></td>
        </tr>
    </table>
    <br />
    <sup>*</sup><em>Cost per page for devices are derived using OEM toners.</em>
</div>

<p>The end reason will be the last condition it hits. </p>
<table class="table">
    <tr>
        <th>Logic</th>
        <th>Explanation</th>
    </tr>
    <tr>
        <td>Default</td>
        <td>Okay</td>
    </tr>
    <tr>
        <td>Has a replacement device</td>
        <td>Current CPP Greater than target CPP</td>
    </tr>
    <tr>
        <td>
            (Device greater than 10 years <strong>OR</strong> has printed more than 100% of it's recommended page volume.)<br/> <strong>AND</strong> <br/>
            Monthly combined (mono and color) page counts > 500
        </td>
        <td>Device not consistent with MPS program.  AMPV is significant</td>
    </tr>
    <tr>
        <td>
            Device greater than 10 years <strong>AND</strong> <br/>
            Monthly combined (mono and color) page counts < 500
        </td>
        <td>Device no longer reliable, AMPV not significant</td>
    </tr>
</table>
