<?php
/**
 * Default view: index.phtml
 */
$session = new Zend_Session_Namespace('report');
$session->url = $this->baseUrl();
$session->surveyurl = $this->baseUrl('/survey');
$session->PNsurveyurl = $this->baseUrl('/partsnow');
$session->generalurl = $this->baseUrl() . "/survey/general";
?>
<h2><?php echo $this->title?></h2>
<div class="alert"><strong>Warning:</strong> Proposal Generator is not fully functional. You will likely encounter many issues at this current point in time.</div>
<div class="well">
    <?php echo $this->selectForm; ?>
    <?php echo $this->selectReportForm; ?>
</div>