<?php 
$id = $this->id;
?>

<div class="clearfix">
    <div class="page-header">
        <h1>Hardware Quote Devices - <small><?php echo $this->devicename; ?></small></h1>
    </div>
</div>

<div class="tabbable"> <!-- Only required for left/right tabs -->
    <ul class="nav nav-tabs">
    	<li><a href="<?php echo $this->url( array ( 'module' => 'quotegen', 'controller' => 'devicesetup', 'action' => 'edit', 'id' => $id ), null, true ); ?>">Details</a></li>
    	<li><a href="<?php echo $this->url( array ( 'module' => 'quotegen', 'controller' => 'devicesetup', 'action' => 'toners', 'id' => $id ), null, true ); ?>">Toners</a></li>
    	<li><a href="<?php echo $this->url( array ( 'module' => 'quotegen', 'controller' => 'devicesetup', 'action' => 'options', 'id' => $id ), null, true ); ?>">Available Options</a></li>
    	<li class="active"><a href="#tab4" data-toggle="tab">Hardware Configurations</a></li>
    </ul>
    <div class="tab-content">
		<form name="frmOptions" id="frmOptions" action="" method="post">
			<input type="hidden" name="configurationid" id="configurationid" value="" />
			
			<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
		
				<div class="clearfix">
    				<a class="btn btn-success btn-small pull-right create-button" href="<?php echo $this->url(array( 'module' => 'quotegen', 'controller' => 'configuration', 'action' => 'create', 'id' => $id, 'page' => 'configurations')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
	    		</div>
	    		
				<table class="table table-striped table-condensed table-bordered">
				    <thead>
				        <tr>
				            <th style="width: 30px;">ID</th>
				            <th style="width: 200px;">Configuration Name</th>
				            <th>Description</th>
				            <th style="width: 100px; text-align: center;">Action</th>
				        </tr>
				    </thead>
				    <tbody>
				    	
				        <?php foreach ($this->paginator as $configuration) : /* @var $configuration Quotegen_Model_DeviceConfiguration */ ?>
				        <tr>
				            <td><?php echo $configuration->id; ?></td>
				            <td><?php echo $configuration->name; ?></td>
				            <td><?php echo $configuration->description; ?></td>
				            <td>
				                <div class="" style="text-align: center;">
				                    <a class="btn btn-warning btn-mini" title="Edit Configuration" href="<?php echo $this->url( array ( 'module' => 'quotegen', 'controller' => 'configuration', 'action' => 'edit', 'id' => $id, 'configurationid' => $configuration->id, 'page' => 'configurations')); ?>"><i class="icon-pencil icon-white"></i></a>
				                    <a class="btn btn-danger btn-mini" title="Delete Configuration" href="<?php echo $this->url(array ( 'module' => 'quotegen', 'controller' => 'configuration', 'action' => 'delete', 'id' => $id, 'configurationid' => $configuration->id, 'page' => 'configurations')); ?>"><i class="icon-trash icon-white"></i></a>
				                </div>
				            </td>
				        </tr>
				        <?php endforeach; ?>
				        
				    </tbody>
				</table>
				<?php echo $this->paginationControl($this->paginator); ?>
				
			<?php else : ?>
			    
			   	<h4>There are no configurations</h4>
			   	<br />
			    <div class="clearfix">
    				<a class="btn btn-success btn-small create-button" href="<?php echo $this->url(array( 'module' => 'quotegen', 'controller' => 'configuration', 'action' => 'create', 'id' => $id, 'page' => 'configurations')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
			    </div>
			    
			<?php endif; ?>
			
			<div style="text-align: center;">
				<a class="btn" title="Done" href="<?php echo $this->url( array ( 'module' => 'quotegen', 'controller' => 'devicesetup', 'action' => 'index' ), null, true ); ?>">Done</a>
			</div>
			
		</form>
    </div>
</div>
