<?php 
$id = $this->id;
$device = Quotegen_Model_Mapper_Device::getInstance()->find($id);
$devicename = $device->getMasterDevice()->getManufacturer()->getDisplayname() . ' ' . $device->getMasterDevice()->getPrinterModel();
?>

<div class="clearfix">
	<h1><?php echo $devicename; ?></h1>
</div>

<div class="tabbable"> <!-- Only required for left/right tabs -->
    <ul class="nav nav-tabs">
    	<li><a href="<?php echo $this->url( array ( 'module' => 'quotegen', 'controller' => 'devicesetup', 'action' => 'edit', 'id' => $id ), null, true ); ?>">Details</a></li>
    	<li><a href="<?php echo $this->url( array ( 'module' => 'quotegen', 'controller' => 'devicesetup', 'action' => 'toners', 'id' => $id ), null, true ); ?>">Toners</a></li>
    	<li><a href="<?php echo $this->url( array ( 'module' => 'quotegen', 'controller' => 'devicesetup', 'action' => 'options', 'id' => $id ), null, true ); ?>">Options</a></li>
    	<li class="active"><a href="#tab4" data-toggle="tab">Configurations</a></li>
    </ul>
    <div class="tab-content">
		<form name="frmOptions" id="frmOptions" action="" method="post">
			<input type="hidden" name="optionid" id="optionid" value="" />
    		<h3>Configurations</h3>
			<div style="text-align: center;">
				<a class="btn" title="Done" href="<?php echo $this->url( array ( 'module' => 'quotegen', 'controller' => 'devicesetup', 'action' => 'index' ), null, true ); ?>">Done</a>
			</div>
		</form>
    </div>
</div>
