<?php 
$id = $this->id;
$device = Quotegen_Model_Mapper_Device::getInstance()->find($id);
$devicename = $device->getMasterDevice()->getManufacturer()->getDisplayname() . ' ' . $device->getMasterDevice()->getPrinterModel();
?>

<div class="clearfix">
	<h1><?php echo $devicename; ?></h1>
</div>

<div class="tabbable"> <!-- Only required for left/right tabs -->
    <ul class="nav nav-tabs">
    	<li class="active"><a href="#tab1" data-toggle="tab">Details</a></li>
    	<li><a href="#tab2" data-toggle="tab">Toners</a></li>
    	<li><a href="#tab3" data-toggle="tab">Options</a></li>
    </ul>
    <div class="tab-content">
    	<div class="tab-pane active" id="tab1"><?php echo $this->render('devicesetup/forms/tab-details.phtml')?></div>
    	<div class="tab-pane" id="tab2"><?php echo $this->render('devicesetup/forms/tab-toners.phtml')?></div>
    	<div class="tab-pane" id="tab3"><?php echo $this->render('devicesetup/forms/tab-options.phtml')?></div>
    </div>
</div>
