<?php 
$id = $this->id; 
$device = Quotegen_Model_Mapper_Device::getInstance()->find($id);
$devicename = $device->getMasterDevice()->getManufacturer()->getDisplayname() . ' ' . $device->getMasterDevice()->getPrinterModel();
?>

<div class="clearfix">
	<h1><?php echo $devicename; ?></h1>
</div>

<div class="tabbable"> <!-- Only required for left/right tabs -->
    <ul class="nav nav-tabs">
    	<li class="active"><a href="#tab1" data-toggle="tab">Details</a></li>
    	<li><a href="#tab2" data-toggle="tab">Toners</a></li>
    	<li><a href="#tab3" data-toggle="tab">Options</a></li>
    	<li><a href="#tab4" data-toggle="tab">Configurations</a></li>
    </ul>
    <div class="tab-content">
    	<div class="tab-pane active" id="tab1">
    		<?php echo $this->form; ?>
    	</div>
    	<div class="tab-pane" id="tab2">
    	    		
    		<?php if ( $this->deviceToners ) { ?>
    		
				<table class="table table-striped table-condensed table-bordered">
				    <thead>
				        <tr>
				            <th>SKU</th>
				            <th>Manufacturer</th>
				            <th>Type</th>
				            <th>Color</th>
				            <th>Yield</th>
				            <th>Cost</th>
				            <th style="width: 120px;">Action</th>
				        </tr>
				    </thead>
				    <tbody>
				        <?php foreach ($this->deviceToners as $toner) : /* @var $toner Admin_Model_Toner */ ?>
				        <tr>
				            <td><?php echo $toner->getSku(); ?></td>
				            <td><?php echo $toner->getManufacturer()->getDisplayname(); ?></td>
				            <td><?php echo $toner->getPartType()->getTypeName(); ?></td>
				            <td style="text-transform: capitalize;"><?php echo strToLower($toner->getTonerColor()->getTonerColorName()); ?></td>
				            <td style="text-align: right;"><?php echo number_format($toner->getYield(), 0, '', ','); ?></td>
				            <td style="text-align: right;"><?php echo "$" . number_format($toner->getCost(), 2, '.', ','); ?></td>
				            <td>
				                <div class="btn-group">
				                    <a class="btn btn-warning btn-mini" title="Edit" href="<?php echo $this->url( array ( 'module' => 'admin', 'controller' => 'toner', 'action' => 'edit', 'id' => $toner->getId())); ?>"><i class="icon-pencil icon-white"></i></a>
				                    <a class="btn btn-danger btn-mini" title="Delete" href="<?php echo $this->url(array ( 'module' => 'admin', 'controller' => 'toner', 'action' => 'unassign', 'id' => $toner->getId())); ?>"><i class="icon-trash icon-white"></i></a>
				                </div>
				            </td>
				        </tr>
				        <?php endforeach; ?>
				    </tbody>
				</table>
				
    		<?php } ?>
    		
    	</div>
    	<div class="tab-pane" id="tab3">
    		<h3>Options</h3>
    	</div>
    	<div class="tab-pane" id="tab4">
    		<h3>Configurations</h3>
    	</div>
    </div>
</div>
