<div class="clearfix">
    <h1>All Devices</h1>
    <a class="btn btn-success btn-small pull-right create-button"
        href="<?php echo $this->url(array('action' => 'create')) ?>"> <i
        class="icon-white icon-plus-sign"></i> Create new
    </a>
</div>
<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>



<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th style="width: 30px;">ID</th>
            <th>Full Device Name</th>
            <th>OEM SKU</th>
            <th>Dealer Sku</th>
            <th style="width: 120px; text-align: center;">Edit</th>
        </tr>
    </thead>
    <tbody>
	    	
	        <?php
    foreach ( $this->paginator->getCurrentItems() as $device )
    : /* @var $device Proposalgen_Model_MasterDevice */
        $oemSku = null;
        $dealerSku = "N/A";
        $quotegenDevice = Quotegen_Model_Mapper_Device::getInstance()->find($device->id);
        if ($quotegenDevice)
        {
            $oemSku = $quotegenDevice->oemSku;
            $dealerSku = $quotegenDevice->dealerSku;
        }
        ?>
	        <tr>
            <td><?php echo $device->id; ?></td>
            <td><?php echo $device->printerModel; ?></td>
            <td><?php echo $oemSku; ?></td>
            <td><?php echo $dealerSku; ?></td>
            <td>
                <div class="" style="text-align: center;">
                    <a class="btn btn-warning btn-mini"
                        title="Edit Device"
                        href="<?php echo $this->url( array ( 'action' => 'edit', 'id' => $device->id)); ?>"><i
                        class="icon-pencil icon-white"></i></a> <a
                        class="btn btn-danger btn-mini"
                        title="Delete Device"
                        href="<?php echo $this->url(array ( 'action' => 'delete', 'id' => $device->id)); ?>"><i
                        class="icon-trash icon-white"></i></a>
                </div>
            </td>
        </tr>
	        <?php endforeach; ?>
	    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>
	
<?php else : ?>
<h2>There are no devices currently in the system.</h2>
<?php endif; ?>

