<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>

	<div class="clearfix">
	    <h1>All Devices</h1>
	</div>
	
	<table class="table table-striped table-condensed table-bordered">
	    <thead>
	        <tr>
	            <th style="width: 30px;">ID</th>
	            <th>Full Device Name</th>
	            <th>SKU</th>
	            <th style="width: 120px;">Action</th>
	        </tr>
	    </thead>
	    <tbody>
	    	
	        <?php foreach ($this->paginator->getCurrentItems() as $device) : /* @var $device Quotegen_Model_Device */ ?>
	        <tr>
	            <td><?php echo $device->getMasterDeviceId(); ?></td>
	            <td><?php echo $device->getMasterDevice()->getFullDeviceName(); ?></td>
	            <td><?php echo $device->getSku(); ?></td>
	            <td>
	                <div class="btn-group">
	                    <a class="btn btn-warning btn-mini" title="Edit Device" href="<?php echo $this->url( array ( 'action' => 'edit', 'id' => $device->getMasterDeviceId())); ?>"><i class="icon-pencil icon-white"></i></a>
	                    <a class="btn btn-danger btn-mini" title="Delete Device" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' => $device->getMasterDeviceId())); ?>"><i class="icon-trash icon-white"></i></a>
	                </div>
	            </td>
	        </tr>
	        <?php endforeach; ?>
	    </tbody>
	</table>
	<?php echo $this->paginationControl($this->paginator); ?>
	
<?php else : ?>
    
    <h1>There are no devices</h1>
    
<?php endif; ?>

