<script>
    <?php $this->headScript()->captureStart('append', 'text/javascript') ?>
    var repop         = '<?= isset($this->pricing_filter); ?>',
        refilter      = '<?= !empty($this->search_criteria); ?>',
        default_labor = <?= (float)$this->default_labor; ?>,
        default_parts = <?= (float)$this->default_parts; ?>,
        repop_array   = '<?= $this->repop_array; ?>',
        repop_page    = '<?= $this->repop_page; ?>',
        dealerSkuName = '<?= My_Brand::$dealerSku; ?>';
    <?php $this->headScript()->captureEnd() ?>
</script>
<?php $this->headScript()->appendFile($this->baseUrl('/js/app/legacy/proposalgen/admin/BulkDevicePricing.js')); ?>
<div class="container">
    <form class="form-inline" name="bulk" id="bulk" action="" method="post" xmlns="http://www.w3.org/1999/html">

        <input type="hidden" name="hdnPage" id="hdnPage" />
        <input type="hidden" name="hdnRole" id="hdnRole" value="system" />
        <input type="hidden" name="hdnMode" id="hdnMode" value="" />
        <input type="hidden" name="hdnManufacturerID" id="hdnManufacturerID" value="" />

        <div id="instruction_container">
            <p>If you wish to remove a price, enter 0 as the new price and update.</p>
        </div>

        <div class="message_container" id="message_container">
            <?= $this->message ?>
        </div>

        <div class="row">
            <div class="form-group col-sm-6 col-md-8 col-lg-9">
                <label class="control-label" for="pricing_filter">Property:</label>
                <select class="form-control" name="pricing_filter" id="pricing_filter">
                    <option value="printer" <?= ($this->pricing_filter == 'printer') ? "selected" : '' ?>>Printer Service Costs</option>
                    <option value="toner" <?= ($this->pricing_filter == 'toner') ? "selected" : '' ?>>Toner Costs</option>
                </select>
            </div>

            <div class="col-sm-6 col-md-4 col-lg-3">
                <a href="<?= $this->url([], 'hardware-library.bulk-hardware-pricing-updates.bulk-file-device-pricing') ?>" class="btn btn-primary btn-block">
                    <i class="glyphicon glyphicon-file"></i> File Import / Exports
                </a>
            </div>
        </div>
        <br>

        <div class="row well">
            <div class="col-lg-8">
                <div class="form-group">
                    <label for="criteria_filter">Filter:</label>
                    <select class="form-control filter_dropdown input-large" name="criteria_filter" id="criteria_filter">
                        <option value="manufacturerId" <?= ($this->search_filter == 'manufacturerId') ? "selected" : '' ?>>Manufacturer</option>
                        <option value="modelName" <?= ($this->search_filter == 'printer_model') ? "selected" : '' ?>>Printer Model</option>
                    </select>
                </div>

                <div class="sr-only">
                    <label for="txtCriteria" id="text_criteria"></label>
                    <input type="text" name="txtCriteria" id="txtCriteria" <?= ($this->search_criteria != '') ? 'value="' . $this->search_criteria . '"' : '' ?>/>
                </div>

                <div class="form-group">
                    <label for="cboCriteria" id="list_criteria">for</label>
                    <select class="form-control input-large" name="cboCriteria" id="cboCriteria"></select>
                </div>
                <div class="form-group">
                    <input class="form-control btn btn-info" type="button" name="btnSearch" id="btnSearch" value="Search" />
                    <input class="form-control btn btn-default" type="button" name="btnClearSearch" id="btnClearSearch" value="Clear" />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-xs-6 col-sm-6 col-md-8 col-lg-8">
                <div class="form-group">
                    <label for="cboSign">Update selected by:</label>
                    <select class="form-control" name="cboSign" id="cboSign">
                        <option value="+">+</option>
                        <option value="-">-</option>
                    </select>
                </div>
                <div class="form-group row">
                    <label class="sr-only" for="txtUpdate"></label>

                    <div class="col-xs-8 col-sm-8">
                        <input class="form-control text-right int-only" type="text" name="txtUpdate" id="txtUpdate" size="3" maxlength="3" />
                    </div>
                    <div class="col-xs-4 col-sm-4 text-left">%</div>
                </div>
                <div class="form-group">
                    <label class="sr-only" for="btnApply"></label>
                    <input class="form-control btn btn-default" type="button" name="btnApply" id="btnApply" value="Preview" />
                </div>
            </div>
        </div>
        <br>

        <div id="devices_table">
            <table id="devices_list"></table>
            <div id="devices_pager"></div>
        </div>

        <div id="toners_table">
            <table id="toners_list"></table>
            <div id="toners_pager"></div>
        </div>

        <div id="dealer_devices_table">
            <table id="dealer_devices_list"></table>
            <div id="dealer_devices_pager"></div>
        </div>

        <div id="dealer_toners_table">
            <table id="dealer_toners_list"></table>
            <div id="dealer_toners_pager"></div>
        </div>

        <br>

        <div class="form-group">
            <input class="form-control btn btn-primary" type="button" name="btnUpdate" id="btnUpdate" value="Save" />
            <a href="<?= $this->url([], 'admin') ?>" class="form-control btn btn-default">Done</a>
        </div>
    </form>
</div>