<?php
/**
 * bulkdevicepricing.phtml
 *
 * @author : John Sadler
 * @version: v1.0
 *
 * Change: August 15, 2011 - modified so all bulk pricing updates are done from this page. Migrated toners into page.
 */
?>

<?php $this->headScript()->captureStart('append', 'text/javascript') ?>
var repop = '<?php echo isset($this->pricing_filter); ?>';
var refilter = '<?php echo !empty($this->search_criteria); ?>';
var default_labor = <?php echo $this->default_labor; ?>;
var default_labor_formated = <?php echo number_format($this->default_labor, 4, '.', ','); ?>;
var default_parts_formated = <?php echo number_format($this->default_parts, 4, '.', ','); ?>;
var default_parts  = <?php echo $this->default_parts; ?>;
var repop_array = '<?php echo $this->repop_array; ?>';
var repop_page = '<?php echo $this->repop_page; ?>';
<?php $this->headScript()->captureEnd() ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/proposalgen/admin/bulkdevicepricing.js')); ?>
<?php $this->headTitle('Bulk Hardware/Pricing Updates'); ?>
<div class="page-header">
    <h1>Bulk Hardware/Pricing Updates</h1>
</div>

<form name="bulk" id="bulk" action="" method="post">
    <input type="hidden" name="hdnPage" id="hdnPage" />
    <input type="hidden" name="hdnRole" id="hdnRole" value="system" />
    <input type="hidden" name="hdnMode" id="hdnMode" value="" />
    <input type="hidden" name="hdnManufacturerID" id="hdnManufacturerID" value="" />

    <div id="instruction_container">
        <p>If you wish to remove a price, enter 0 as the new price and update.</p>
    </div>

    <div id="message_container" class="message_container" style="height: 30px;">
        <?php echo $this->message; ?>
    </div>

    <div id="options_container" style="margin: 0px 0px 10px 5px;">
        <div id="filter_pricing" style="display: inline; padding: 0px 0px 0px 0px;">
            <label for="pricing_filter" class="details_label" style="display: inline;">Property:</label>
            <select name="pricing_filter" id="pricing_filter" class="filter_dropdown" style="width: 180px; margin: 0px 0px 0px 15px;" onchange="javascript: update_grid('pricing');">
                <option value="printer" <?php if ($this->pricing_filter == 'printer')
                {
                    echo "selected";
                } ?>>Printer Service Costs
                </option>
                <option value="toner" <?php if ($this->pricing_filter == 'toner')
                {
                    echo "selected";
                } ?>>Toner Costs
                </option>
                <!-- option value="parts" <?php if($this->pricing_filter == 'parts') { echo "selected"; } ?>>Parts Cost Per Page</option -->
                <!-- option value="labor" <?php if($this->pricing_filter == 'labor') { echo "selected"; } ?>>Labor Cost Per Page</option -->
            </select>
        </div>

        <div class="pull-right">
            <a href="<?php echo $this->url(array('action' => 'bulk-file-device-pricing', 'controller' => 'costs', 'module' => 'proposalgen')); ?>" class="btn btn-primary"><i class="icon-file"></i> File Import / Exports</a>
        </div>


    </div>

    <div id="filter_container" class="well">
        <div id="criteria_container">
            <label for="criteria_filter" class="details_label" style="display: inline; padding: 0px 0px 0px 0px;">Filter:</label>
            <select name="criteria_filter" id="criteria_filter" class="filter_dropdown" style="width: 160px; margin: 0px 0px 0px 10px;">
                <option value="manufacturerId" <?php if ($this->search_filter == 'manufacturerId')
                {
                    echo "selected";
                } ?>>Manufacturer
                </option>
                <option value="modelName" <?php if ($this->search_filter == 'printer_model')
                {
                    echo "selected";
                } ?>>Printer Model
                </option>
            </select>
            <label for="txtCriteria" class="details_label" style="display: inline; padding: 0px 10px 0px 10px;">for</label>
            <span id="text_criteria"><input type="text" name="txtCriteria" style="width: 152px;" id="txtCriteria" <?php if ($this->search_criteria != '')
                {
                    echo 'value="' . $this->search_criteria . '"';
                } ?> /></span>
            <span id="list_criteria" style="display: none;"><select name="cboCriteria" id="cboCriteria" style="width: 160px; margin: 0px 0px 0px 0px;"></select></span>
            <input type="button" name="btnSearch" id="btnSearch" value="Search" class="btn btn-info" />
            <input type="button" name="btnClearSearch" id="btnClearSearch" value="Clear" class="btn" />
        </div>
    </div>

    <div class="results_container">
        <div class="list_container">
            <div style="margin: 0px 0px 5px 0px;">
                <div class="bold margined" style="display: inline;">
                    <span class="details_label">Update selected by:</span>
                    <select name="cboSign" id="cboSign" class="span1" style="margin: 0px 0px 0px 0px;">
                        <option value="+">+</option>
                        <option value="-">-</option>
                    </select>
                    <input type="text" name="txtUpdate" id="txtUpdate" size="3" maxlength="3" class="span1" style="text-align: right; margin: 0px 0px 0px 0px;" onkeypress="javascript: return numbersonly(this, event);" />%
                    <input type="button" name="btnApply" id="btnApply" value="Preview" onclick="javascript: apply_percentage();" class="btn" />
                </div>
                <div id="default_price" class="details_label margined" style="display: none; float: right; margin-right: 5px;">Default Price: $<?php echo $this->default_price; ?></div>
            </div>

            <div id="devices_table">
                <table id="devices_list"></table>
                <div id="devices_pager"></div>
            </div>

            <div id="toners_table">
                <table id="toners_list"></table>
                <div id="toners_pager"></div>
            </div>

            <div id="dealer_devices_table">
                <table id="dealer_devices_list"></table>
                <div id="dealer_devices_pager"></div>
            </div>

            <div id="dealer_toners_table">
                <table id="dealer_toners_list"></table>
                <div id="dealer_toners_pager"></div>
            </div>

            <br />

            <div class="submitBar">
                <input type="button" name="btnUpdate" id="btnUpdate" value="Save" onclick="javascript: do_update();" class="btn btn-primary" />
                <input type="button" name="btnDone" id="btnDone" value="Done" onClick="javascript:  document.location.href='<?php echo $this->baseUrl("/admin") ?>';" class="btn" />
            </div>
        </div>
    </div>

</form>

