<?php

$this->headScript()->appendFile($this->baseUrl('js/app/legacy/proposalgen/cost/CostImportExport.js'));

?>
<div class="container">
    <br />

    <div class="tabbable">
        <ul class="nav nav-tabs">
            <li>
                <a href="<?= $this->url(array(), 'hardware-library.bulk-hardware-pricing-updates.bulk-file-device-pricing'); ?>" title='Device Price'> Device Price </a>
            </li>
            <?php if ($this->canApprove) : ?>
                <li>
                    <a href="<?= $this->url(array(), 'hardware-library.bulk-hardware-pricing-updates.bulk-file-device-features'); ?>" title='Device Features'> Device Features </a>
                </li>
            <?php endif; ?>
            <li class="active">
                <a href="#" title="Toner Pricing"> Toner Pricing</a></li>
            <li>
                <a href="<?= $this->url(array(), 'hardware-library.bulk-hardware-pricing-updates.bulk-file-toner-matchup'); ?>" title='Toner Matchup'> Toner Matchup </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="deviceFeaturesTabPane">
                <h3> Toner Pricing Import & Export </h3>

                <p> Toner pricing will allow you to adjust toner prices for your dealership. </p>

                <form id="tonerPricingForm" action="" method="post" enctype="multipart/form-data">

                    <div id="upload_container" class="well">
                        <div>Choose a
                            <span style="color: red">.CSV</span> file to upload:
                            <input type="file" name="uploadedfile" id="uploadedfile" accept="application/csv, text/csv" size="60" class="upload_file" />
                        </div>
                    </div>

                    <a href="#" id="importLink" class="btn btn-primary"><i class="glyphicon glyphicon-upload"></i> Import</a>
                    <a href="#" id="exportLink" data-type="toner" class="btn btn-primary"><i class="fa fa-fw fa-download"></i>Export</a>

                    <input class="manufacturerMultiSelect" type="text" name="manufacturers" id="manufacturers" />
                </form>
            </div>
        </div>
    </div>
    <br />
    <a href="<?= $this->url(array(), 'hardware-library.bulk-hardware-pricing-updates'); ?>" class="btn btn-default">Back</a>

    <br />
    <br />
    <?php if ($this->errorMessages != null): ?>
        <div class="well">
            <table class="table">
                <tr>
                    <th>Line Number</th>
                    <th>Error Type</th>
                    <th>Error Message</th>
                </tr>
                <?php foreach ($this->errorMessages as $lineNumber => $error) : ?>
                    <?php foreach ($error as $errorType => $fieldErrors): ?>
                        <?php foreach ($fieldErrors as $fieldName => $errorMessages): ?>
                            <?php foreach ($errorMessages as $key => $errorMessage): ?>
                                <tr>
                                    <td><?= $lineNumber ?></td>
                                    <td><?= $errorType ?></td>
                                    <td><?= $fieldName . ' ' . $errorMessage ?></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endif; ?>
</div>