<?php
use MPSToolbox\Legacy\Modules\HardwareOptimization\Forms\DeviceSwapReasonsForm;

/* @var $form DeviceSwapReasonsForm */
$form = $this->element;
?>

<?= $this->RenderFormOpen($form, array('form-horizontal')) ?>
<div class="clearfix">
    <fieldset class="col-md-10 col-md-offset-1">
        <div class="form-group  <?= ($form->getElement('reasonCategory')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('reasonCategory')) ?>
            <div>
                <?= $this->RenderFormSelect($form->getElement('reasonCategory')) ?>
                <?= $this->RenderFormDescription($form->getElement('reasonCategory')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('reasonCategory')) ?>
            </div>
        </div>

        <div class="form-group <?= ($form->getElement('reason')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('reason')) ?>
            <div>
                <?= $this->RenderFormText($form->getElement('reason')) ?>
                <?= $this->RenderFormDescription($form->getElement('reason')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('reason')) ?>
            </div>
        </div>

        <div class="form-group <?= ($form->getElement('isDefault')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <div>
                <?= $this->RenderFormCheckbox($form->getElement('isDefault')) ?>
                <?= $this->RenderFormDescription($form->getElement('isDefault')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('isDefault')) ?>
            </div>
        </div>
    </fieldset>
</div>
<fieldset>
    <?= ($this->formHidden('deviceSwapReasonId')) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>
