<?php
/* @var $phpword \PhpOffice\PhpWord\PhpWord */
$phpword = $this->phpword;
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

/**
 * Styles
 */
$h1Color                   = My_Brand::getDealerBranding()->h1FontColor;
$h1BackgroundColor         = My_Brand::getDealerBranding()->h1BackgroundColor;
$titlePageBackgroundColor1 = My_Brand::getDealerBranding()->titlePageTitleBackgroundColor;
$titlePageBackgroundColor2 = My_Brand::getDealerBranding()->titlePageInformationBackgroundColor;
$titlePageTextColor1       = My_Brand::getDealerBranding()->titlePageTitleFontColor;
$titlePageTextColor2       = My_Brand::getDealerBranding()->titlePageInformationFontColor;
$h1BorderColor             = $this->wordStyles->default->sectionHeaderBorderColor;
$h2Background              = My_Brand::getDealerBranding()->h2BackgroundColor;
$h2Color                   = My_Brand::getDealerBranding()->h2FontColor;
$h3Color                   = "000000";

$textHighlightColor = "0096D6";

/**
 * Document Properties
 */
$properties = $phpword->getDocumentProperties();
$properties->setCreator('MPS Assessment Software');
$properties->setCompany('MPS Assessment Software');
$properties->setTitle('Solution');
$properties->setCategory('Customer Report');
$properties->setLastModifiedBy('MPS Assessment Software');
$properties->setCreated(time());
$properties->setModified(time());
$properties->setSubject('MPS Assessment Software');

$titlePageSection = $phpword->addSection([
    'orientation'  => null,
    'marginLeft'   => 1420,
    'marginRight'  => 1420,
    'marginTop'    => 1420,
    'marginBottom' => 1420
]);
$section          = $phpword->addSection();

/**
 * Paragraph styles
 */
// Title page
$phpword->addParagraphStyle('titleStyle1', [
    'align'      => 'center',
    'spaceAfter' => 100,
    //    'bgColor'    => $titlePageBackgroundColor1,
    'shading'    => [
        'fill' => $titlePageBackgroundColor1,
    ]
]);
$phpword->addParagraphStyle('titleStyle2', [
    'spaceAfter'  => 50,
    'spaceBefore' => 50,
    'bgColor'     => $titlePageBackgroundColor2
]);
$phpword->addParagraphStyle('titleStyle3', [
    'spaceAfter' => 100,
    'tabs'       => [
        new \PhpOffice\PhpWord\Style\Tab('left', 350)
    ],
    'shading'    => [
        'fill' => $titlePageBackgroundColor2,
    ]
]);
$phpword->addFontStyle('titlepage_title', [
    'size'  => 24,
    'bold'  => true,
    'color' => $titlePageTextColor1
]);

$phpword->addFontStyle('titlepage_subtitle', [
    'size'  => 16,
    'bold'  => true,
    'color' => $titlePageTextColor2
]);

$phpword->addFontStyle('titlepage_address', [
    'size'  => 12,
    'color' => $titlePageTextColor2
]);
$phpword->addParagraphStyle('titlepageHeaderParagraph', [
    'spaceAfter' => 200
]);

$phpword->addParagraphStyle('nospacing', [
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('nospacing_rightalign', [
    'align'       => 'right',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('nospacing_centeralign', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('rightalign', [
    'align' => 'right'
]);

$phpword->addParagraphStyle('gradeParagraph', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('savingsParagraph', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

/**
 * Font Styles
 */
$phpword->addFontStyle('titlepageHeaderFont', [
    'bold' => true,
    'size' => 16
]);

$phpword->addFontStyle('bold_text', [
    'bold' => true
]);

$phpword->addFontStyle('bold_highlight_text', [
    'bold'  => true,
    'color' => $h3Color
]);

$phpword->addFontStyle('gradeFont', [
    'bold' => true,
    'size' => 18
]);

$phpword->addFontStyle('gradeTitleFont', [
    'bold' => true,
    'size' => 12
]);

$phpword->addFontStyle('savingsFont', [
    'bold' => true,
    'size' => 11
]);

$phpword->addFontStyle('savingsAmountFont', [
    'color' => 'F0003C',
    'bold'  => true,
    'size'  => 11
]);

$phpword->addFontStyle('small_italic_text', [
    'color'  => '333333',
    'italic' => true,
    'size'   => 9
]);

/**
 * Header/Title Styles
 */
/**
 * Header/Title Styles
 */
// H1 Style
$phpword->addTitleStyle(1, [
    'size'  => 15,
    'color' => $h1Color,
    'bold'  => true
],
    [
        'shading' => [
            'fill' => $h1Background,
        ],
    ]);
// H2 Style #5881BC
$phpword->addTitleStyle(2, [
    'size'   => 12,
    'color'  => $h2Color,
    'bold'   => true,
    'italic' => true
],
    [
        'shading' => [
            'fill' => $h2Background,
        ]
    ]);
// H3 Style #5881BC
$phpword->addTitleStyle(3, [
    'size'  => 10,
    'color' => $h3Color,
    'bold'  => true
],
    [
        'spaceBefore' => 100,
        'spaceAfter'  => 100
    ]);

// H3 Style #5881BC
$phpword->addFontStyle('heading3', [
    'size'  => 10,
    'color' => $h3Color,
    'bold'  => true
]);

/**
 * Addtional replacements table
 */
$addtionalReplacementsTable = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 100,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 100
    ],
    "col1Width"  => 3325,
    "col2Width"  => 2325,
    "col3Width"  => 1825,
    "col4Width"  => 1825,
    "header"     => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ]
    ],
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_centeralign'
        ]
    ]
];

/**
 * True costs table styles
 */
$trueCostsTable = (object)[
    "rowheader"  => [
        'tblHeader' => true,
        'cantSplit' => true,
    ],
    "rowstyle"   => [
        "cantSplit" => true,
    ],
    "tablestyle" => [
        'cellMarginTop'     => 100,
        'cellMarginRight'   => 100,
        'cellMarginBottom'  => 100,
        'cellMarginLeft'    => 100,
        'borderBottomSize'  => 10,
        'borderBottomColor' => 'black',
    ],
    "col1Width"  => 1805.6,
    "col2Width"  => 3611.2,
    "col3Width"  => 3811.2,
    "header"     => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ]
    ],
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => [
                'color' => '000000',
                'bold'  => true
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ]
    ]
];

/**
 * Print IQ Plus Costs Table
 */
$printiqpluscostsTable = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 100,
        'cellMarginRight'  => 100,
        'cellMarginBottom' => 100,
        'cellMarginLeft'   => 100
    ],
    "col1Width"  => 7020,
    "col2Width"  => 2008,
    "row"        => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "valign" => "center"
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "valign" => "center"
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_rightalign'
        ]
    ],
    "boldRow"    => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "valign" => "center"
            ],
            "fontStyle"      => [
                'bold' => true
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "valign" => "center"
            ],
            "fontStyle"      => [
                'bold' => true
            ],
            "paragraphStyle" => 'nospacing_rightalign'
        ]
    ],
    "footer"     => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "valign" => "center"
            ],
            "fontStyle"      => [
                "color" => '000000',
                'bold'  => true
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "valign" => "center"
            ],
            "fontStyle"      => [
                "color" => '000000',
                'bold'  => true
            ],
            "paragraphStyle" => 'nospacing_rightalign'
        ]
    ]
];

/**
 * Print IQ Plus Summary Table
 */

$printiqplussummaryTable = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 100,
        'cellMarginRight'  => 100,
        'cellMarginBottom' => 100,
        'cellMarginLeft'   => 100
    ],
    "col1Width"  => 5320,
    "col2Width"  => 1369,
    "col3Width"  => 1369,
    "col4Width"  => 1369,
    "header"     => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_rightalign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_rightalign'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_rightalign'
        ]
    ],
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_rightalign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_rightalign'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => [
                'color' => '000000'
            ],
            "paragraphStyle" => 'nospacing_rightalign'
        ]
    ],
    "footer"     => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_rightalign'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_rightalign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_rightalign'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => [
                'color' => '000000',
                'bold'  => true
            ],
            "paragraphStyle" => 'nospacing_rightalign'
        ]
    ]
];

/**
 * Total Annual Savings Table
 */

$totalAnnualSavingsTable = (object)[
    "tablestyle" => [
        'cellMarginTop'     => 100,
        'cellMarginRight'   => 100,
        'cellMarginBottom'  => 100,
        'cellMarginLeft'    => 100,
        'borderBottomSize'  => 1,
        'borderBottomColor' => '999999',
    ],
    "col1Width"  => 6020,
    "col2Width"  => 3008,
    "body"       => (object)[
        "rowheight" => 400,
        "cell1"     => (object)[
            "cellStyle"      => [
                "bgColor"          => "F0F0F0",
                "borderColor"      => "999999",
                "borderTopSize"    => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => [
                "color" => '000000',
                'bold'  => true,
                'size'  => 12
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "bgColor"          => "F0F0F0",
                "borderColor"      => "999999",
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "valign"           => "center"
            ],
            "fontStyle"      => [
                "color" => '000000',
                'bold'  => true,
                'size'  => 12
            ],
            "paragraphStyle" => 'nospacing_rightalign'
        ]
    ]
];

/**
 * Estimated Annual Savings table styles
 */
$estimatedAnnualSavingsTable = (object)[
    "rowheader"       => [
        'tblHeader' => true,
        'cantSplit' => true,
    ],
    "rowstyle"        => [
        "cantSplit" => true,
    ],
    "tablestyle"      => [
        'cellMarginTop'     => 50,
        'cellMarginRight'   => 50,
        'cellMarginBottom'  => 50,
        'cellMarginLeft'    => 50,
        'borderBottomSize'  => 10,
        'borderBottomColor' => 'black',
    ],
    "headerCol1Width" => 4414,
    "headerCol2Width" => 4614,
    "col1Width"       => 3008,
    "col2Width"       => 1404,
    "col3Width"       => 3308,
    "col4Width"       => 1304,
    "header"          => (object)[
        "rowheight" => 400,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cellspan"       => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "gridSpan"         => 2,
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cellspan"       => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "gridSpan"         => 2,
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ]
    ],
    "body"            => (object)[
        "rowheight" => 200,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_rightalign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_rightalign'
        ]
    ],
    "footer"          => (object)[
        "rowheight" => 200,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_rightalign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_rightalign'
        ]
    ]
];

/**
 * Print IQ Plus device table
 */

$printiqplusdevicesTable = (object)[
    "tablestyle"      => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "col1Width"       => 3300,
    "col2Width"       => 2000,
    "col3Width"       => 1000,
    "col4Width"       => 1000,
    "col5Width"       => 1000,
    "col6Width"       => 1000,
    "footerCol1Width" => 6300,
    "footerCol2Width" => 1000,
    "footerCol3Width" => 1000,
    "footerCol4Width" => 1000,
    "header"          => (object)[
        "rowheight" => 400,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell5"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell6"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ]
    ],
    "body"            => (object)[
        "rowheight" => 200,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell5"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell6"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => [
                'color' => '000000'
            ],
            "paragraphStyle" => 'nospacing_centeralign'
        ]
    ],
    "footer"          => (object)[
        "rowheight" => 200,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "fontStyle"      => [
                'color' => '000000',
                'bold'  => true
            ],
            "paragraphStyle" => 'nospacing_centeralign'
        ]
    ]
];

$assumptionsTable = (object)[
    "tablestyle"  => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "leftalign"   => "nospacing",
    "centeralign" => "nospacing_centeralign",
    "rightalign"  => "nospacing_rightalign",
    "col1Width"   => 10200,
    "col2Width"   => 1600,
    "header"      => (object)[
        "rowheight"      => null,
        "fontStyle"      => "table_header",
        "cell"           => [
            "borderTopSize"   => 1,
            "borderRightSize" => 1,
            "borderLeftSize"  => 1,
            "bgColor"         => $header_color,
            "valign"          => "center"
        ],
        "nobottomborder" => [
            "borderTopSize"   => 1,
            "borderRightSize" => 1,
            "borderLeftSize"  => 1,
            "bgColor"         => $header_color,
            "valign"          => "center"
        ],
        "notopborder"    => [
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "bgColor"          => $header_color,
            "valign"           => "center"
        ]
    ],
    "row"         => (object)[
        "rowheight"     => null,
        "fontStyle"     => 'table_body',
        "cell"          => [
            "borderTopSize"    => 1,
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "valign"           => "center"
        ],
        "highlightcell" => [
            "borderTopSize"    => 1,
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "bgColor"          => $highlight_color,
            "valign"           => "center"
        ]
    ],
    "footer"      => (object)[
        "rowheight" => null,
        "fontStyle" => 'table_footer',
        "cell"      => [
            "borderTopSize"    => 1,
            "borderRightSize"  => 1,
            "borderBottomSize" => 1,
            "borderLeftSize"   => 1,
            "valign"           => "center"
        ]
    ]
];

/**
 * Next Steps Table
 */

$nextStepsTable = (object)[
    "rowstyle"   => [
        "cantSplit" => true,
    ],
    "tablestyle" => [
        'cellMarginTop'    => 100,
        'cellMarginRight'  => 100,
        'cellMarginBottom' => 100,
        'cellMarginLeft'   => 100,
    ],
    "col1Width"  => 2000,
    "col2Width"  => 7300,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "valign" => "top"
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "valign" => "top"
            ],
            "fontStyle"      => null,
            "paragraphStyle" => null,
            "listStyle"      => null
        ]
    ]
];

/**
 * Setup some styles to be used across the report
 */
$styles = (object)[
    "tables" => (object)[
        "assumptions"            => $assumptionsTable,
        "truecosts"              => $trueCostsTable,
        "estimatedAnnualSavings" => $estimatedAnnualSavingsTable,
        "totalAnnualSavings"     => $totalAnnualSavingsTable,
        "printiqplusdevices"     => $printiqplusdevicesTable,
        "printiqpluscosts"       => $printiqpluscostsTable,
        "printiqplussummary"     => $printiqplussummaryTable,
        "addtionalReplacements"  => $addtionalReplacementsTable,
        "nextsteps"              => $nextStepsTable,
    ],
];

$titledata = [
    "phpword"             => $phpword,
    "section"             => $titlePageSection,
    "assessmentViewModel" => $this->assessmentViewModel,
    "styles"              => $styles,
    "dealerLogoFile"      => $this->dealerLogoFile,
];

$data = [
    "phpword"             => $phpword,
    "section"             => $section,
    "assessmentViewModel" => $this->assessmentViewModel,
    "styles"              => $styles,
    "brandName"           => My_Brand::getDealerBranding()->mpsProgramName,
    "companyName"         => My_Brand::getDealerBranding()->shortDealerName
];
// Actual document pages
$this->partial("report/solution/docx/01_titlepage.phtml", $titledata);
$this->partial("report/solution/docx/02_yourprintiq.phtml", $data);
$this->partial("report/solution/docx/03_evaluatingthetruecost.phtml", $data);
$this->partial("report/solution/docx/04_solution1.phtml", $data);
$this->partial("report/solution/docx/05_assumptions.phtml", $data);
$this->partial("report/solution/docx/06_additionalreplacements.phtml", $data);
$this->partial("report/solution/docx/07_businessprint.phtml", $data);
$this->partial("report/solution/docx/08_nextsteps.phtml", $data);

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpword, 'Word2007');
$objWriter->save($this->savePath);

echo $this->baseUrl($this->publicFileName);