<?php
/**
 * Assessment Title Page
 */
/* @var $phpword \PhpOffice\PhpWord\PhpWord */
$phpword = $this->phpword;
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

/* @var $titlePage \PhpOffice\PhpWord\Element\Section */
$titlePage       = $this->section;
$titleImageStyle = [
    'align' => 'center'
];

// Table to fix the issue of images being different sizes
$imageTable = $titlePage->addTable([]);
$imageTable->addRow(5760);
$cell = $imageTable->addCell(9028.8, [
    'valign' => 'center'
]);
$cell->addImage(PUBLIC_PATH . $this->dealerLogoFile, [
    'align' => 'center'
]);

$titlePage->addTextBreak();
// Assessment Title
$titlePage->addText('', null, 'titleStyle1');
$titlePage->addText('Solution', 'titlepage_title', 'titleStyle1');
$titlePage->addText('', null, 'titleStyle1');


$titlePage->addTextBreak();

$titlePage->addText('', 'titlepage_address', 'titleStyle3');
$titlePage->addText("\t" . sprintf('Prepared For: %1$s', htmlentities($assessmentViewModel->assessment->getClient()->companyName)), 'titlepage_subtitle', 'titleStyle3');

// Parse the address
$addressLines = explode("\n", $assessmentViewModel->assessment->getClient()->getAddress()->getFullAddressMultipleLines());
$addressCount = 1;
foreach ($addressLines as $line)
{
    $titlePage->addText("\t" . $line, 'titlepage_address', 'titleStyle3');
    $addressCount++;
}
$titlePage->addText('', 'titlepage_address', 'titleStyle3');
$titlePage->addText("\t" . 'Date:' . " " . $assessmentViewModel->getDateReportPrepared(), 'titlepage_address', 'titleStyle3');
// Add extra blank lines to make the grey box big
if ($addressCount < 11)
{
    for ($i = 0; $i < 11 - $addressCount; $i++)
    {
        $titlePage->addText('', 'titlepage_address', 'titleStyle3');
    }
}