<?php
/**
 * Assessment Title Page
 */
/* @var $phpword PHPWord */
$phpword = $this->phpword;
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

/* @var $titlePage PHPWord_Section */
$titlePage       = $this->section;
$titleImageStyle = array(
    'align' => 'center'
);

// Table to fix the issue of images being different sizes
$imageTable = $titlePage->addTable(array(
                                        'borderBottomSize' => 1
                                   ));
$imageTable->addRow(5760);
$cell = $imageTable->addCell(9028.8, array(
                                          'valign' => 'center'
                                     ));
$cell->addImage(PUBLIC_PATH . $this->dealerLogoFile, array(
                                                          'align' => 'center'
                                                     ));

$titlePage->addTextBreak();
// Assessment Title
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText('  Solution', 'titlepage_title', 'titleStyle2');
$titlePage->addText('', null, 'titleStyle2');


$titlePage->addTextBreak();

$titlePage->addText(' ', 'titlepage_address', 'titleStyle3');
$titlePage->addText(sprintf('Prepared For: %1$s', $assessmentViewModel->assessment->getClient()->companyName), 'titlepage_subtitle', 'titleStyle3');

// Parse the address
$addressLines = explode("\n", $assessmentViewModel->assessment->getClient()->getAddress()->getFullAddressMultipleLines());
$addressCount = 1;
foreach ($addressLines as $line)
{
    $titlePage->addText($line, 'titlepage_address', 'titleStyle3');
    $addressCount++;
}
$titlePage->addText(' ', 'titlepage_address', 'titleStyle3');
$titlePage->addText('Date:' . " " . $assessmentViewModel->getDateReportPrepared(), 'titlepage_address', 'titleStyle3');
// Add extra blank lines to make the grey box big
if ($addressCount < 11)
{
    for ($i = 0; $i < 11 - $addressCount; $i++)
    {
        $titlePage->addText(' ', 'titlepage_address', 'titleStyle3');
    }
}