<?php
/**
 * Solution - Next Steps
 */
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$section->addPageBreak();
$section->addTitle('Next Steps', 1);

$section->addText('We recommend the following implementation plan for your managed print services program:');

$section->addTextBreak();

$tc    = $this->styles->tables->nextsteps;
$table = $section->addTable($tc->tablestyle);

$table->addRow($tc->body->rowheight, $tc->rowstyle);
$table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText('Today:', $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle);
$cell->addListItem('Remote monitoring software is already installed.', 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);
$cell->addListItem('Select a department or floor for initial migration to managed print services.', 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);

$table->addRow($tc->body->rowheight, $tc->rowstyle);
$table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText('Within 30 days:', $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle);
$cell->addListItem('Migrate the selected department or floor to managed print services.', 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);

$table->addRow($tc->body->rowheight, $tc->rowstyle);
$table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText('Within 90 days:', $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle);
$cell->addListItem('Migrate all other desired locations to managed print services.', 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);

$table->addRow($tc->body->rowheight, $tc->rowstyle);
$table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText('Every six months:', $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle);
$cell->addListItem('Evaluation and adjustment of recommendations as needed.', 0, $tc->body->cell2->fontStyle, $tc->body->cell2->listStyle);

$section->addTextBreak();

$section->addText('Whether you are looking for a comprehensive managed print services plan that includes new equipment, or are looking for assistance in maintaining your existing printer fleet, we can design a solution that meets your specific business needs. Let us take care of your print so you can get back to business.');