<?php

use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
?>
    <div class="jumbotron">
        <h2>Other Printing Devices</h2>

        <p>The following devices are not included in the assessment.</p>
    </div>
<?php if (count($assessmentViewModel->getExcludedDevices()) > 0) : ?>
    <table class="table table-bordered table-condensed" id="ExcludedDevicesTable">
        <thead>
        <tr>
            <th>Manufacturer</th>
            <th>Model</th>
            <th>Serial Number</th>
            <th>IP Address</th>
            <th>Exclusion Reason</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($assessmentViewModel->getExcludedDevices() as $device): ?>
            <tr>
                <?php if ($device->getIsMappedToMasterDevice()) : ?>
                    <td class="manufacturer"><?= $device->getMasterDevice()->getManufacturer()->displayname; ?></td>
                    <td class="model-name"><?= $device->getMasterDevice()->modelName; ?></td>
                <?php else : ?>
                    <td class="manufacturer"><?= $device->getRmsUploadRow()->manufacturer; ?></td>
                    <td class="model-name"><?= $device->getRmsUploadRow()->modelName; ?></td>
                <?php endif; ?>
                <td class="serial-number"><?= (strlen($device->serialNumber) == 0) ? 'Unknown Serial' : $device->serialNumber; ?></td>
                <td class="ip-address"><?= ($device->ipAddress) ?: 'Unknown IP' ?></td>
                <td class="is-excluded"><?= ($device->isExcluded) ? 'Manually excluded.' : 'Not mapped.'; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="alert alert-info">No devices were excluded from this report.</div>
<?php endif ?>