<?php

use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\TonerColorModel;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
?>

<div class="jumbotron">
    <h2><?= My_Brand::$jit; ?> Supply and Toner SKU Report</h2>

    <p>This is a list of all the unique supplies and SKUs in the fleet</p>
</div>

<div class="container-fluid full-width jit-toner" id="htmlReportContainer">
    <table class="table table-bordered table-condensed">
        <thead>
        <tr>
            <th colspan="3"></th>
            <th colspan="12">Customer Preferred</th>
            <th colspan="12">Dealer Preferred</th>
        </tr>
        <tr>
            <th>Device Name</th>
            <th>Serial Number</th>
            <th>IP Address</th>
            <th>Black SKU</th>
            <th>Black Cost</th>
            <th>Cyan SKU</th>
            <th>Cyan Cost</th>
            <th>Magenta SKU</th>
            <th>Magenta Cost</th>
            <th>Yellow SKU</th>
            <th>Yellow Cost</th>
            <th>3Color SKU</th>
            <th>3Color Cost</th>
            <th>4Color SKU</th>
            <th>4Color Cost</th>
            <th>Black SKU</th>
            <th>Black Cost</th>
            <th>Cyan SKU</th>
            <th>Cyan Cost</th>
            <th>Magenta SKU</th>
            <th>Magenta Cost</th>
            <th>Yellow SKU</th>
            <th>Yellow Cost</th>
            <th>3Color SKU</th>
            <th>3Color Cost</th>
            <th>4Color SKU</th>
            <th>4Color Cost</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $customerCostPerPageSetting = $assessmentViewModel->getCostPerPageSettingForCustomer();
        $dealerCostPerPageSetting   = $assessmentViewModel->getCostPerPageSettingForDealer();
        ?>
        <?php foreach ($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances() as $deviceInstance) : ?>
            <?php
            $toners           = $deviceInstance->getMasterDevice()->getCheapestTonerSetByVendor($customerCostPerPageSetting);
            $compatibleToners = $deviceInstance->getMasterDevice()->getCheapestTonerSetByVendor($dealerCostPerPageSetting);
            ?>
            <tr>
                <td class="device-name"><?= str_ireplace("hewlett-packard", "HP", $deviceInstance->getDeviceName()) ?></td>
                <td class="serial-number"><?= $deviceInstance->serialNumber; ?></td>
                <td class="ip-address"><?= $deviceInstance->ipAddress; ?></td>

                <!-- OEM -->
                <td class="sku"><?= (isset($toners[TonerColorModel::BLACK])) ? $toners[TonerColorModel::BLACK]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($toners[TonerColorModel::BLACK])) ? $this->currency($toners[TonerColorModel::BLACK]->cost) : "-"; ?></td>
                <td class="sku"><?= (isset($toners[TonerColorModel::CYAN])) ? $toners[TonerColorModel::CYAN]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($toners[TonerColorModel::CYAN])) ? $this->currency($toners[TonerColorModel::CYAN]->cost) : "-"; ?></td>
                <td class="sku"><?= (isset($toners[TonerColorModel::MAGENTA])) ? $toners[TonerColorModel::MAGENTA]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($toners[TonerColorModel::MAGENTA])) ? $this->currency($toners[TonerColorModel::MAGENTA]->cost) : "-"; ?></td>
                <td class="sku"><?= (isset($toners[TonerColorModel::YELLOW])) ? $toners[TonerColorModel::YELLOW]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($toners[TonerColorModel::YELLOW])) ? $this->currency($toners[TonerColorModel::YELLOW]->cost) : "-"; ?></td>
                <td class="sku"><?= (isset($toners[TonerColorModel::THREE_COLOR])) ? $toners[TonerColorModel::THREE_COLOR]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($toners[TonerColorModel::THREE_COLOR])) ? $this->currency($toners[TonerColorModel::THREE_COLOR]->cost) : "-"; ?></td>
                <td class="sku"><?= (isset($toners[TonerColorModel::FOUR_COLOR])) ? $toners[TonerColorModel::FOUR_COLOR]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($toners[TonerColorModel::FOUR_COLOR])) ? $this->currency($toners[TonerColorModel::FOUR_COLOR]->cost) : "-"; ?></td>

                <!-- COMPATIBLE -->
                <td class="sku"><?= (isset($compatibleToners[TonerColorModel::BLACK])) ? $compatibleToners[TonerColorModel::BLACK]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($compatibleToners[TonerColorModel::BLACK])) ? $this->currency($compatibleToners[TonerColorModel::BLACK]->cost) : "-"; ?></td>
                <td class="sku"><?= (isset($compatibleToners[TonerColorModel::CYAN])) ? $compatibleToners[TonerColorModel::CYAN]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($compatibleToners[TonerColorModel::CYAN])) ? $this->currency($compatibleToners[TonerColorModel::CYAN]->cost) : "-"; ?></td>
                <td class="sku"><?= (isset($compatibleToners[TonerColorModel::MAGENTA])) ? $compatibleToners[TonerColorModel::MAGENTA]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($compatibleToners[TonerColorModel::MAGENTA])) ? $this->currency($compatibleToners[TonerColorModel::MAGENTA]->cost) : "-"; ?></td>
                <td class="sku"><?= (isset($compatibleToners[TonerColorModel::YELLOW])) ? $compatibleToners[TonerColorModel::YELLOW]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($compatibleToners[TonerColorModel::YELLOW])) ? $this->currency($compatibleToners[TonerColorModel::YELLOW]->cost) : "-"; ?></td>
                <td class="sku"><?= (isset($compatibleToners[TonerColorModel::THREE_COLOR])) ? $compatibleToners[TonerColorModel::THREE_COLOR]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($compatibleToners[TonerColorModel::THREE_COLOR])) ? $compatibleToners[TonerColorModel::THREE_COLOR]->cost : "-"; ?></td>
                <td class="sku"><?= (isset($compatibleToners[TonerColorModel::FOUR_COLOR])) ? $compatibleToners[TonerColorModel::FOUR_COLOR]->sku : "-"; ?></td>
                <td class="cost"><?= (isset($compatibleToners[TonerColorModel::FOUR_COLOR])) ? $this->currency($compatibleToners[TonerColorModel::FOUR_COLOR]->cost) : "-"; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php $excludedDevices = $assessmentViewModel->getExcludedDevices(); ?>
    <?php if (count($excludedDevices) > 0) : ?>
        <div class="jumbotron">
            <h2>Excluded Devices</h2>
        </div>

        <table class="table table-bordered table-condensed" id="ExcludedDevicesTable" style="font-size: 9pt;">
            <thead>
            <tr>
                <th>Device Name</th>
                <th>IP Address</th>
                <th>Serial Number</th>
                <th>Exclusion Reason</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($excludedDevices as $deviceInstance): ?>
                <tr>
                    <td class="device-name"><?= $deviceInstance->getDeviceName(); ?></td>
                    <td class="ip-address"><?= ($deviceInstance->ipAddress) ?: 'Unknown IP' ?></td>
                    <td><?= (strlen($deviceInstance->serialNumber) === "") ? 'Unknown Serial' : $deviceInstance->serialNumber; ?></td>
                    <td><?= $deviceInstance->_exclusionReason; ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <br /><p><em>No devices were excluded from this report.</em></p>
    <?php endif ?>
</div>


