<?php
/**
 * Cost Analysis - Main Table
 *
 * This script contains everything for the main table of the cost analysis.
 */
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $proposal Proposalgen_Model_Proposal_Abstract */
$proposal = $this->proposal;

/**
 * Variables
 */
// Add any variables that are needed throughout the page here.


/**
 * Section starts here
 */
// You would normally put this here if you needed it but in the cost analysis we do not need it.
// $section->addPageBreak();

$tcStyle = $this->styles->tables->grossMargin;
$table = $section->addTable($tcStyle->tablestyle);

// Table header
$table->addRow($tcStyle->header->rowheight, $tcStyle->header->fontStyle);
$table->addCell($tcStyle->col1Width, $tcStyle->header->nobottomborder)->addText(null, $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->colSpanWidth, $tcStyle->header->cell, 5)->addText($this->translate('Black And White'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->colSpanWidth, $tcStyle->header->cell, 5)->addText($this->translate('Color'), $tcStyle->header->fontStyle, $tcStyle->centeralign);

$table->addRow($tcStyle->header->rowheight, $tcStyle->header->fontStyle);

$column1 = $table->addCell($tcStyle->col1Width, $tcStyle->header->notopborder);
$column1 ->addText($this->translate('Device Name'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$column1 ->addText($this->translate('(IP Address - Serial Number)'), $tcStyle->header->fontStyle, $tcStyle->centeralign);

$table->addCell($tcStyle->col2Width, $tcStyle->header->cell)->addText($this->translate('AMPV'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col3Width, $tcStyle->header->cell)->addText($this->translate('Toner Cost'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col4Width, $tcStyle->header->cell)->addText($this->translate('Toner Yield'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col5Width, $tcStyle->header->cell)->addText($this->translate('CPP'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col6Width, $tcStyle->header->cell)->addText($this->translate('Total Printing Cost'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col7Width, $tcStyle->header->cell)->addText($this->translate('AMPV'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col8Width, $tcStyle->header->cell)->addText($this->translate('Toner Cost'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col9Width, $tcStyle->header->cell)->addText($this->translate('Toner Yield'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col10Width, $tcStyle->header->cell)->addText($this->translate('CPP'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col11Width, $tcStyle->header->cell)->addText($this->translate('Total Printing Cost'), $tcStyle->header->fontStyle, $tcStyle->centeralign);


foreach ($proposal->PurchasedDevices as $device) {
    // This is only here for zend content assist
    //$device = new Proposalgen_Model_DeviceInstance();
    $tonerConfig = $device->MasterDevice->TonerConfigId;
    $grossMarginPricingConfig = Proposalgen_Model_MasterDevice::getGrossMarginPricingConfig();
    $completeMonoToners = $device->MasterDevice->HasValidMonoGrossMarginToners;
    $completeColorToners = $device->MasterDevice->HasValidColorGrossMarginToners;
    $blackToner = null;
    $colorToner = null;
    
    switch ($tonerConfig)
    {
        case Proposalgen_Model_TonerConfig::THREE_COLOR_SEPARATED:
            $blackToner = $device->MasterDevice->getCheapestToner(Proposalgen_Model_TonerColor::BLACK, $grossMarginPricingConfig);
            $colorToner = $device->MasterDevice->getCheapestToner(Proposalgen_Model_TonerColor::CYAN, $grossMarginPricingConfig);
            break;
        case Proposalgen_Model_TonerConfig::THREE_COLOR_COMBINED:
            $blackToner = $device->MasterDevice->getCheapestToner(Proposalgen_Model_TonerColor::BLACK, $grossMarginPricingConfig);
            $colorToner = $device->MasterDevice->getCheapestToner(Proposalgen_Model_TonerColor::THREE_COLOR, $grossMarginPricingConfig);
            break;
        case Proposalgen_Model_TonerConfig::FOUR_COLOR_COMBINED:
            $blackToner = $device->MasterDevice->getCheapestToner(Proposalgen_Model_TonerColor::FOUR_COLOR, $grossMarginPricingConfig);
            $colorToner = $blackToner;
            break;
        default:
            $blackToner = $device->MasterDevice->getCheapestToner(Proposalgen_Model_TonerColor::BLACK, $grossMarginPricingConfig);
            break;
    }
    
    // Black Toner
    $blackCost = "$" . number_format($blackToner->TonerPrice, 2);
    $blackYield = number_format($blackToner->TonerYield);

    // Color Toner
    $colorCost = "-";
    $colorStyle = "style='text-align: center;'";
    $colorYield = "-";
    $isColor = false;
    if ($colorToner)
    {
        $colorCost = "$" . number_format($colorToner->TonerPrice, 2);
        $colorYield = number_format($colorToner->TonerYield);
        $colorStyle = 'right';
        $isColor = true;
    }
    
    // Row Colors
    $mono_toner_class = ($completeMonoToners) ? $tcStyle->row->cell : $tcStyle->row->highlightcell;
    $color_toner_class = ($completeColorToners) ? $tcStyle->row->cell : $tcStyle->row->highlightcell;
    
    $table->addRow($tcStyle->cell->rowheight);
    $column1 = $table->addCell($tcStyle->col1Width, $tcStyle->row->cell);
    $column1 ->addText( $this->translate(str_ireplace("hewlett-packard", "HP", $device->DeviceName) ), $tcStyle->row->fontStyle, $tcStyle->leftalign);
    $column1 ->addText("(" . $device->IPAddress . " - " . $device->SerialNumber . ")", $tcStyle->row->fontStyle, $tcStyle->leftalign);
    
    // Mono
    $table->addCell($tcStyle->col2Width, $mono_toner_class)->addText(number_format($device->AverageMonthlyBlackAndWhitePageCount), $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col3Width, $mono_toner_class)->addText($blackCost, $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col4Width, $mono_toner_class)->addText($blackYield, $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col5Width, $mono_toner_class)->addText(number_format($device->MasterDevice->CostPerPage->Actual->BasePlusService->BlackAndWhite, 4), $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col6Width, $mono_toner_class)->addText("$" .number_format($device->GrossMarginMonthlyBlackAndWhiteCost, 2), $tcStyle->row->fontStyle, $tcStyle->rightalign);
    
    // Color
    $table->addCell($tcStyle->col7Width, $color_toner_class)->addText(($isColor) ? number_format($device->AverageMonthlyColorPageCount) : "-", $tcStyle->row->fontStyle, ($isColor) ? $tcStyle->rightalign : $tcStyle->centeralign);
    $table->addCell($tcStyle->col8Width, $color_toner_class)->addText($colorCost, $tcStyle->row->fontStyle, (trim($colorCost) != "-") ? $tcStyle->rightalign : $tcStyle->centeralign);
    $table->addCell($tcStyle->col9Width, $color_toner_class)->addText($colorYield, $tcStyle->row->fontStyle, (trim($colorYield) != "-") ? $tcStyle->rightalign : $tcStyle->centeralign);
    $table->addCell($tcStyle->col10Width, $color_toner_class)->addText(($isColor) ? number_format($device->MasterDevice->CostPerPage->Actual->BasePlusService->Color, 4) : "-", $tcStyle->row->fontStyle, ($isColor ? $tcStyle->rightalign : $tcStyle->centeralign));
    $table->addCell($tcStyle->col11Width, $color_toner_class)->addText(($isColor) ? "$" . number_format($device->GrossMarginMonthlyColorCost, 2) : "-", $tcStyle->row->fontStyle, ($isColor ? $tcStyle->rightalign : $tcStyle->centeralign));

}

// Table footer (totals row)
$table->addRow($tcStyle->footer->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->footer->cell)->addText($this->translate('Totals for ' . $proposal->PurchasedDeviceCount. ' devices:'), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col2Width, $tcStyle->footer->cell)->addText(number_format($this->proposal->PageCounts->Purchased->BlackAndWhite->Monthly), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col3Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col4Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col5Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col6Width, $tcStyle->footer->cell)->addText('$' . number_format($this->proposal->GrossMarginTotalMonthlyCost->BlackAndWhite, 2), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col7Width, $tcStyle->footer->cell)->addText(number_format($this->proposal->PageCounts->Purchased->Color->Monthly), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col8Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col9Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col10Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col11Width, $tcStyle->footer->cell)->addText('$' . number_format($this->proposal->GrossMarginTotalMonthlyCost->Color, 2), $tcStyle->footer->fontStyle, $tcStyle->rightalign);

