<?php 
/* @var $form Quotegen_Form_QuoteSetting */
$form = $this->element;
$percentageElements = array();
$percentageElements[] = $form->getElement('pageCoverageMonochrome');
$percentageElements[] = $form->getElement('pageCoverageColor');
$percentageElements[] = $form->getElement('deviceMargin');
$percentageElements[] = $form->getElement('pageMargin');
$pricingConfigID = $form->getElement('pricingConfigId');
?>


<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
<?php foreach ($percentageElements as $element) : ?>
<div class="control-group <?php echo ($element->hasErrors()) ? 'error' : '' ?>">
	<?php echo $element->renderLabel(); ?>
	<div class="controls">
		<div class="input-append">
			<?php echo $element->renderViewHelper()?><span class="add-on"><strong>System Default: </strong><?php echo number_format($element->getDescription(), 2); ?>%</span>
		</div>
		<?php echo $element->renderErrors(); ?>
	</div>
</div>
<?php endforeach; ?>
<div class="control-group <?php echo ($pricingConfigID->hasErrors()) ? 'error' : '' ?>">
	<?php echo $pricingConfigID->renderLabel()?>
	<div class="controls">
		<div class="input-append">
		<?php /* @var $princingConfig Proposalgen_Model_Mapper_PricingConfig */ $pricingConfig = Proposalgen_Model_Mapper_PricingConfig::getInstance()->find($pricingConfigID->getDescription()); ?>
			<?php echo $pricingConfigID->renderViewHelper(); ?><span class="add-on"><strong>System Default: </strong><?php echo $pricingConfig->getConfigName(); ?></span>			
		</div>
		<?php echo $element->renderErrors(); ?>
	</div>
</div>

<?php echo $this->render('quotesetting/form/form-actions.phtml')?>
</form>