<?php 
/* @var $form Quotegen_Form_QuoteSetting */
$form = $this->element;
$percentageElements = array();
$percentageElements[] = $form->getElement('pageCoverageMonochrome');
$percentageElements[] = $form->getElement('pageCoverageColor');
$percentageElements[] = $form->getElement('deviceMargin');
$percentageElements[] = $form->getElement('pageMargin');
$percentageElements[] = $form->getElement('pricingConfigId');
//$pricingConfigID = $form->getElement('pricingConfigId');
?>
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
<?php foreach ($percentageElements as $element) : ?>
<div class="control-group <?php echo ($element->hasErrors()) ? 'error' : '' ?>">
	<?php echo $element->renderLabel(); ?>
	<div class="controls">
		<div class="input-append">
			<?php if($element->getType() === 'Zend_Form_Element_Text'):?>
				<?php echo $element->renderViewHelper()?><span class="add-on"><strong>System Default: </strong><?php echo number_format($element->getDescription(), 2); ?>%</span>
			<?php else :?>
				<?php /* @var $princingConfig Proposalgen_Model_Mapper_PricingConfig */ $pricingConfig = Proposalgen_Model_Mapper_PricingConfig::getInstance()->find($element->getDescription()); ?>
				<?php echo $element->renderViewHelper(); ?><span class="add-on"><strong>System Default: </strong><?php echo $pricingConfig->getConfigName(); ?></span>			
			<?php endif?>
		</div>
		<?php echo $element->renderErrors(); ?>
	</div>
</div>
<?php endforeach; ?>
<?php echo $this->render('quotesetting/form/form-actions.phtml')?>
</form>