<div class="hero-unit">
	<h1>
		TODO List <small>Things that need to be done before starting the
			project</small>
	</h1>
	<hr>
	<ul>
		<li>Lock out users based on incorrect number of login attempts. Lock
			out ip/session with a captcha after a number of incorrect login
			attempts</li>
		<li>Figure out where branding points should be (IE header, product
			name/app name)</li>
		<li>ACL kinks need to be worked out so that we may define ACL as we
			go. SQL Dumps will be necessary to persist ACL. We could also think
			about an import/export function for all the different roles &
			privileges.</li>
		<li>SubMenu navigation with twitter bootstrap (Zend_Navigation issue)
			needs to be solved. This way we can kick the old way of handwriting
			menus throughout the application.</li>
		<li><strike>User Passwords should be hashed using crypt() and the
				SHA-512 method (See Example #3) <a
				href="http://php.net/manual/en/function.crypt.php">function.crypt</a>
		</strike></li>
		<li><strike>Guest user needs to be created so that we may assign
				"guest" privileges</strike></li>

	</ul>
</div>
<ul class="breadcrumb">
	<li><i class="icon-th-list"></i> Proposal</li>
	<li>-</li>
	<li>
		
			<select>
				<option>Company</option>
				<option>Geneal</option>
				<option>Finance</option>
				<option>Purchasing</option>
				<option>IT</option>
				<option>Users</option>
				<option>Verify</option>
				<option>Upload</option>
				<option>Mapping</option>
				<option>Summary</option>
				<option>Settings</option>
				<option>Report</option>
			</select>
		
	</li>

</ul>

<div class="hero-unit">
	<h1>Landing Page</h1>
	<p>This page should contain handy links that the user is presented with
		when they first sign onto the system.</p>
	<p>Thinking about it, maybe we should have some kind of marketing blurb
		here with links to sign on. This would let the product advertise
		itself.</p>
</div>
<hr>
<div class="row">
	<div class="span12">
		<div class="well">
			<p>Anything below this well isn't meant for a marketing landing page.</p>
		</div>
	</div>
	<div class="span4">
		<div class="well">
			<div class="well-header">Hardware Quotes</div>
		</div>
	</div>
	<div class="span4">
		<div class="well">
			<div class="well-header">Favorite Devices</div>
		</div>
	</div>
	<div class="span4">
		<div class="well">
			<div class="well-header">Leasing Schemas</div>
		</div>
	</div>
</div>