<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h1>MPS Dashboard</h1>
</div>

<div class="row">
<div class="span3">
    <div class="well well-small">

        <?php if (isset($this->selectedClientId)) :
            $selectedClient = Quotegen_Model_Mapper_Client::getInstance()->find($this->selectedClientId);
            ?>
            <form method="POST">
                <button class="btn btn-primary btn-mini pull-right" name="editClient">Edit</button>
                <p>
                    <strong><?php echo (strlen($selectedClient->companyName) > 20) ? substr($selectedClient->companyName, 0, 20) . "..." : $selectedClient->companyName; ?></strong>
                </p>

                <p><strong>Address:</strong><br>
                    <?php
                    $truncatedAddressLines = array();
                    foreach (explode("\n", $selectedClient->getAddress()->getFullAddressMultipleLines()) as $addressLine) : ?>
                        <?php $truncatedAddressLines[] = (strlen($addressLine) > 26) ? substr($addressLine, 0, 26) . "..." : $addressLine; ?>
                    <?php
                    endforeach;

                    echo implode("<br>", $truncatedAddressLines);
                    ?>
                </p>

                <p><strong>Organization Size:</strong><br><strong><?php echo number_format($selectedClient->employeeCount); ?></strong> employees</p>
            </form>
        <?php endif; ?>
    </div>
    <div class="well well-small">
        <div class="btn-group pull-right">
            <a class="btn btn-mini btn-primary" title="View Client List" href="<?php echo $this->url(array('action' => 'view-all-clients', 'controller' => 'index', 'module' => 'default')); ?>"><i class="icon-list-ul"></i>
                List</a>
            <a class="btn btn-mini btn-success" href="<?php echo $this->url(array('action' => 'create-client', 'controller' => 'index', 'module' => 'default')); ?>"><i class="icon-plus"></i>
                New</a>
        </div>
        <p><strong>Clients</strong></p>

        <form id="searchForClientForm" class="form-search" method="POST">
            <input type="text" id="searchClientByName" placeholder="Enter name to search..." data-link="<?php echo $this->url(array("action" => "search-for-client", "controller" => "index", "module" => "default")); ?>" autocomplete="off" class="input-block-level">
            <input type="hidden" name="selectClient" id="hiddenSelectClientId" />
        </form>

        <hr>
        <strong>Recently Viewed Clients</strong>

        <form method="POST">
            <table class="table table-condensed">
                <?php foreach (Quotegen_Model_Mapper_Client::getInstance()->fetchRecentlyViewed($this->userId) as $client) : ?>
                    <tr class="<?php echo (isset($this->selectedClientId) && $client->id == $this->selectedClientId) ? "info" : ""; ?>">
                        <td><?php echo (strlen($client->companyName) > 20) ? substr($client->companyName, 0, 20) . "..." : $client->companyName; ?></td>
                        <td style="width: 50px;">
                            <button class="btn btn-primary btn-mini" name="selectClient" value="<?php echo $client->id; ?>">Select</button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </form>
        <hr>


    </div>
</div>
<div class="span9">

<?php if (isset($this->selectedClientId)) : ?>
    <div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#assessmentTabPane" data-toggle="tab" title="Assessment"><i class="mpsicon-assessment"></i></a></li>
        <li><a href="#hardwareOptimizationTabPane" data-toggle="tab" title="Hardware Optimization"><i class="mpsicon-optimize"></i></a></li>
        <?php if (My_Feature::canAccess(My_Feature::MEMJET_OPTIMIZATION)) : ?>
            <li><a href="#memjetOptimizationTabPane" data-toggle="tab" title="Memjet Optimization"><i class="mpsicon-memjet"></i></a></li>
        <?php endif; ?>
        <li><a href="#healthcheckTabPane" data-toggle="tab" title="Health Check"><i class="mpsicon-healthcheck"></i></a></li>
        <li><a href="#quoteTabPane" data-toggle="tab" title="Hardware Quote"><i class="mpsicon-quote"></i></a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active" id="assessmentTabPane">
            <p>Assessment</p>

            <form method="POST">
                <table class="table table-striped table-condensed table-bordered">
                    <tr>
                        <th>Title <br /> File Name</th>
                        <th style="width:125px">Date Created <br /> Last Modified</th>
                        <th>Finished</th>
                        <th style="width: 70px;">Action</th>
                    </tr>
                    <tr class="info">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td style="text-align: center;">
                            <button name="selectAssessment" value="0" class="btn btn-success btn-mini">Start New</button>
                        </td>
                    </tr>
                    <?php foreach ($this->availableAssessments as $report) : /* @var $report Assessment_Model_Assessment */ ?>
                        <tr class="<?php echo ($report->stepName == Proposalgen_Model_Assessment_Step::STEP_FINISHED) ? "success" : "warning"; ?>">
                            <td><?php echo $report->name . '<br/> <small>' . $report->getRmsUpload()->fileName; ?></small></td>
                            <td><?php echo strftime("%B %d, %Y", strtotime($report->dateCreated)) . "<br/>" . strftime("%B %d, %Y", strtotime($report->lastModified)); ?></td>
                            <?php if ($report->stepName == Proposalgen_Model_Assessment_Step::STEP_FINISHED) : ?>
                                <td>Finished</td>

                            <?php else : ?>
                                <td>In Progress</td>
                            <?php endif; ?>
                            <td style="text-align: center;">
                                <button name="selectAssessment" value="<?php echo $report->id; ?>" class="btn btn-primary btn-mini">Select</button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </form>

        </div>
        <div class="tab-pane" id="hardwareOptimizationTabPane">
            <p>Hardware Optimization</p>

            <form method="POST">
                <table class="table table-striped table-condensed table-bordered">
                    <tr>
                        <th>Title <br /> File Name</th>
                        <th style="width:125px">Date Created <br /> Last Modified</th>
                        <th>Finished</th>
                        <th style="width: 70px;">Action</th>
                    </tr>
                    <tr class="info">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td style="text-align: center;">
                            <button name="selectHardwareOptimization" value="0" class="btn btn-success btn-mini">Start New</button>
                        </td>
                    </tr>
                    <?php foreach ($this->availableHardwareOptimizations as $hardwareOptimization) : /* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */ ?>
                        <tr class="<?php echo ($hardwareOptimization->stepName == Hardwareoptimization_Model_Hardware_Optimization_Steps::STEP_FINISHED) ? "success" : "warning"; ?>">
                            <td><?php echo $hardwareOptimization->name . '<br/> <small>' . $hardwareOptimization->getRmsUpload()->fileName; ?></small></td>
                            <td><?php echo strftime("%B %d, %Y", strtotime($hardwareOptimization->dateCreated)) . "<br/>" . strftime("%B %d, %Y", strtotime($hardwareOptimization->lastModified)); ?></td>

                            <?php if ($hardwareOptimization->stepName == Hardwareoptimization_Model_Hardware_Optimization_Steps::STEP_FINISHED) : ?>
                                <td>Finished</td>

                            <?php else : ?>
                                <td>In Progress</td>
                            <?php endif; ?>
                            <td style="text-align: center;">
                                <button name="selectHardwareOptimization" value="<?php echo $hardwareOptimization->id; ?>" class="btn btn-primary btn-mini">
                                    Select
                                </button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </form>
        </div>
        <?php if (My_Feature::canAccess(My_Feature::MEMJET_OPTIMIZATION)) : ?>
            <div class="tab-pane" id="memjetOptimizationTabPane">
                <p>Memjet Optimization</p>

                <form method="POST">
                    <table class="table table-striped table-condensed table-bordered">
                        <tr>
                            <th>Title <br /> File Name</th>
                            <th style="width:125px">Date Created <br /> Last Modified</th>
                            <th>Finished</th>
                            <th style="width: 70px;">Action</th>
                        </tr>
                        <tr class="info">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td style="text-align: center;">
                                <button name="selectMemjetOptimization" value="0" class="btn btn-success btn-mini">Start New</button>
                            </td>
                        </tr>
                        <?php foreach ($this->availableMemjetOptimizations as $memjetOptimization) : /* @var $memjetOptimization Memjetoptimization_Model_Memjet_Optimization */ ?>
                            <tr class="<?php echo ($memjetOptimization->stepName == Memjetoptimization_Model_Memjet_Optimization_Steps::STEP_FINISHED) ? "success" : "warning"; ?>">
                                <td><?php echo $memjetOptimization->name . '<br/> <small>' . $memjetOptimization->getRmsUpload()->fileName; ?></small></td>
                                <td><?php echo strftime("%B %d, %Y", strtotime($memjetOptimization->dateCreated)) . "<br/>" . strftime("%B %d, %Y", strtotime($memjetOptimization->lastModified)); ?></td>

                                <?php if ($memjetOptimization->stepName == Memjetoptimization_Model_Memjet_Optimization_Steps::STEP_FINISHED) : ?>
                                    <td>Finished</td>

                                <?php else : ?>
                                    <td>In Progress</td>
                                <?php endif; ?>
                                <td style="text-align: center;">
                                    <button name="selectMemjetOptimization" value="<?php echo $memjetOptimization->id; ?>" class="btn btn-primary btn-mini">
                                        Select
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </form>
            </div>
        <?php endif; ?>
        <div class="tab-pane" id="healthcheckTabPane">
            <p>Health Check</p>

            <form method="POST">
                <table class="table table-striped table-condensed table-bordered">
                    <tr>
                        <th>Title <br /> File Name</th>
                        <th style="width:125px">Date Created <br /> Last Modified</th>
                        <th>Finished</th>
                        <th style="width: 70px;">Action</th>
                    </tr>
                    <tr class="info">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td style="text-align: center;">
                            <button name="selectHealthcheck" value="0" class="btn btn-success btn-mini">Start New</button>
                        </td>
                    </tr>
                    <?php foreach ($this->availableHealthchecks as $healthcheck) : /* @var $healthcheck Healthcheck_Model_Healthcheck */ ?>
                        <tr class="<?php echo ($healthcheck->stepName == Healthcheck_Model_Healthcheck_Steps::STEP_FINISHED) ? "success" : "warning"; ?>">
                            <td><?php echo $healthcheck->name . '<br/> <small>' . $healthcheck->getRmsUpload()->fileName; ?></small></td>
                            <td><?php echo strftime("%B %d, %Y", strtotime($healthcheck->dateCreated)) . "<br/>" . strftime("%B %d, %Y", strtotime($healthcheck->lastModified)); ?></td>

                            <?php if ($healthcheck->stepName == Healthcheck_Model_Healthcheck_Steps::STEP_FINISHED) : ?>
                                <td>Finished</td>

                            <?php else : ?>
                                <td>In Progress</td>
                            <?php endif; ?>
                            <td style="text-align: center;">
                                <button name="selectHealthcheck" value="<?php echo $healthcheck->id; ?>" class="btn btn-primary btn-mini">Select
                                </button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </form>
        </div>
        <div class="tab-pane" id="quoteTabPane">
            <p>Hardware Quote</p>

            <form method="POST">
                <p>
                    <button name="createLeasedQuote" value="0" class="btn btn-primary btn-mini">Create New Leased Quote</button>
                    <button name="createPurchasedQuote" value="0" class="btn btn-success btn-mini">Create New Purchased Quote</button>
                </p>
                <table class="table table-striped table-condensed table-bordered">
                    <tr>
                        <th>Title</th>
                        <th style="width: 120px; ">Date Created <br /> Last Modified</th>
                        <th>Type</th>
                        <th style="width: 100px;">Action</th>
                    </tr>

                    <?php foreach ($this->availableQuotes as $quote) : /* @var $quote Quotegen_Model_Quote */ ?>
                        <?php
                        $exportName = ($quote->isHardwareOptimizationExport()) ? "Quote for: " . Hardwareoptimization_Model_Mapper_Hardware_Optimization_Quote::getInstance()->fetchHardwareOptimizationByQuoteId($quote->id)->name
                            : (($quote->isMemjetOptimizationExport()) ? "Quote for: " . Memjetoptimization_Model_Mapper_Memjet_Optimization_Quote::getInstance()->fetchMemjetOptimizationByQuoteId($quote->id)->name : " ");
                        ?>
                        <tr>
                            <td><?php echo $quote->name . "<br/><small>" . $exportName; ?></small></td>
                            <td><?php echo strftime("%B %d, %Y", strtotime($quote->dateCreated)) . "<br/>" . strftime("%B %d, %Y", strtotime($quote->dateModified)); ?></td>

                            <?php if ($quote->quoteType == Quotegen_Model_Quote::QUOTE_TYPE_LEASED) : ?>
                                <td>Leased</td>
                            <?php else : ?>
                                <td>Purchased</td>
                            <?php endif; ?>
                            <td>
                                <button name="selectQuote" value="<?php echo $quote->id; ?>" class="btn btn-primary btn-mini">Select</button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>

        </div>
    </div>
    </div>
    <hr>

    <h3>RMS Uploads</h3>
    <form method="POST">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th>Date Uploaded</th>
                <th>Type</th>
                <th>File</th>
                <th>Valid</th>
                <th>Invalid</th>
                <th style="width: 70px;">Action</th>
            </tr>
            <tr class="info">
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td style="text-align: center;">
                    <button name="selectRmsUpload" value="0" class="btn btn-success btn-mini">Upload</button>
                </td>
            </tr>
            <?php foreach ($this->availableRmsUploads as $rmsUpload) : /* @var $rmsUpload Proposalgen_Model_Rms_Upload */ ?>
                <tr>
                    <td><?php echo strftime("%B %d, %Y %I:%M:%S %p", strtotime($rmsUpload->uploadDate)); ?></td>
                    <td><?php echo $rmsUpload->getRmsProvider()->name; ?></td>
                    <td><?php echo $rmsUpload->fileName; ?></td>
                    <td><?php echo number_format($rmsUpload->validRowCount); ?></td>
                    <td><?php echo number_format($rmsUpload->invalidRowCount); ?></td>

                    <td style="text-align: center;">
                        <button name="selectRmsUpload" value="<?php echo $rmsUpload->id; ?>" class="btn btn-primary btn-mini">Select</button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </form>
<?php else : ?>
    <div class="well">
        <div class="alert alert-info"><strong>Important:</strong> Please select a client from the left menu to proceed.</div>
    </div>
<?php endif; ?>
</div>
</div>