<div class="jumbotron">
    <div class="container">
        <h1>Missing Fleet Data</h1>
        <p>You don't have any fleet data for this client yet. Use the form below to perform your first upload.</p>
        <p>or <a class="btn btn-primary" href="<?= $this->url([], 'rms-upload.realtime') ?>" title="Use Real Time Data">
                <i class="fa fa-user fa-dashboard"></i>
                Use Real Time Data
            </a></p>
    </div>
</div>
<div class="container">
    <?= $this->form ?>
</div>