<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">
        <a class="btn btn-success btn-xs pull-right" href="<?= $this->url(array(), 'app.dashboard.new-client') ?>"><i class="fa fa-fw fa-plus-circle"></i> Create new</a>
            Client List
        </div>
        <div class="panel-body">
            <form method="POST">
                <div class="table-responsive">
                    <table id="js-select-client-table" class="table table-bordered table-condensed responsive js-select-client-table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Employees</th>
                            <th>Last Viewed</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
            </form>
        </div>
    </div>
</div>
</div>
