<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <span class="pull-right">
                <a class="btn btn-info btn-xs" href="<?= $this->url([], 'company.clients') ?>?select"><i class="fa fa-fw fa-wrench"></i> Manage Clients</a>
                &nbsp;&nbsp;&nbsp;
                <a class="btn btn-success btn-xs" href="<?= $this->url([], 'company.clients.create') ?>?select"><i class="fa fa-fw fa-plus-circle"></i> Create New</a>
            </span>

            Client List
        </div>
        <div class="panel-body">
            <form method="POST">
                <div class="table-responsive">
                    <table id="js-select-client-table" class="table table-bordered table-condensed responsive js-select-client-table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Employees</th>
                            <th>Last Viewed</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
            </form>
        </div>
    </div>
</div>
</div>
