<div class="page-header">
    <h1>Select Client</h1>
</div>
    <div class="alert alert-info">Please note that is page is just a temporary client selection screen.</div>
<div class="well">
    <form method="POST">
    <?php foreach ($this->clients as $client) : /* @var $client Quotegen_Model_Client */ ?>
        <p><button class="btn btn-primary btn-small" type="submit" name="clientId" value="<?php echo $client->id; ?>">Select</button> - <?php echo $client->companyName; ?></p>
    <?php endforeach; ?>
    </form>
</div>