<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\ClientModel;

?>
<div class="container">
    <a href="<?= $this->url([], 'app.dashboard'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-arrow-left"></i> Go Back</a>
    <hr>
    <form method="POST" action="<?= $this->url([], 'app.dashboard.select-client'); ?>">
        <table class="table table-bordered table-condensed table-striped table-hover">
            <thead>
            <tr>
                <th style="width: 50px;"></th>
                <th>Client Name</th>
            </tr>
            </thead>
            <tbody>
            <?php if ($this->clients && count($this->clients) > 0) : ?>
                <?php /* @var $client ClientModel */ ?>
                <?php foreach ($this->clients as $client) : ?>
                    <tr>
                        <td>
                            <button class="btn btn-primary btn-xs" name="selectClient" value="<?= $client->id; ?>">Select</button>
                        </td>
                        <td><?= $this->escape($client->companyName); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else : ?>
                <tr>
                    <td colspan="2">You have no clients.</td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </form>
    <hr>
    <a href="<?= $this->url([], 'app.dashboard'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-arrow-left"></i> Go Back</a>
</div>