<?php $this->headScript()->captureStart('append','text/javascript') ?>
$("#leasingSchemaId").change(function() {
    //add new options depending on selection
    $.ajax({
        beforeSend: function() {
        // disable form elements while loading new info
        $("#leasingSchemaId").attr('disabled', 'disabled');
        },
        url: '<?php echo $this->baseUrl('/quotegen/quote_profitability/leasingdetails'); ?>?schemaId='+$("#leasingSchemaId").val(),
        success: function(data) {

            for (var i = 0; i < data.length; i++)
            {

                //empty out leasingSchemaId
                $("#leasingSchemaTermId").html('');
                var listItems = "";
                for (var i = 0; i < data.length; i++)
                {
                    listItems += "<option value=" + data[i][0] + " >" + data[i][1] + "</option>";
                }
                $("#leasingSchemaTermId").append(listItems);
            }
        },
        error: function() {

        },
        complete: function() {
        //enable form elements after they are filled
        $("#leasingSchemaId").removeAttr('disabled');
        }
    });
});
<?php $this->headScript()->captureEnd();
$quote = $this->Quote(); /* @var $quote Quotegen_Model_Quote */
$this->headScript()->appendFile($this->baseUrl('js/quotegen/devicesetup/deviceSetup.js'));
$this->placeholder('ProgressionNav')->set($this->render('_partials/quoteHeading.phtml'));
?>
<?php echo $this->render('_partials/quoteHeading.phtml'); ?>
<div class='well'>
	<?php echo $this->form; ?>
</div>
