<?php
/* @var $quote Quotegen_Model_Quote */
$quote = $this->Quote();

$this->headScript()->appendFile($this->baseUrl('js/quotegen/quote_profitability/index.js'));
$this->headScript()->appendFile($this->baseUrl('js/quotegen/devicesetup/deviceSetup.js'));
$this->placeholder('ProgressionNav')->set($this->render('_partials/quoteHeading.phtml'));
?>
<?php echo $this->render('_partials/quoteHeading.phtml'); ?>
<div class='well'>
    <?php echo $this->form; ?>
</div>
