<?php
/* @var $form Quotegen_Form_QuoteDevices */

$form = $this->element;
?>
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
<?php foreach ($form->getQuoteDeviceGroups() as $group) : 
    /* @var $quoteDeviceGroup Quotegen_Model_QuoteDeviceGroup */
    $quoteDeviceGroup = $group->quoteDeviceGroup;
?>
    <hr>
    <table class="table table-condensed table-bordered table-striped quoteDeviceTable">
        <tr class="header-row">
            <th colspan="4"><div class="input-prepend"><button type="submit" name="addConfiguration" value="<?php echo $quoteDeviceGroup->getId(); ?>" class="btn btn-success">Add</button><select name="deviceConfigurationId-<?php echo $quoteDeviceGroup->getId(); ?>">
                                <option value="-1">New Configuration</option>
                                <option value="1">Favorite 1</option>
                                <option value="2">Favorite 2</option>
                                <option value="3">Favorite 3</option>
                            </select>    </div></th>
            
            <th colspan="2" style="text-align: center;">Purchase</th>
            <th colspan="3" style="text-align: center">Lease</th>
            <th style="width: 30px;"></th>
        </tr>
        <tr class="header-row">
            <th>Item</th>
            <th style="width: 90px;">Package Cost</th>
            <th style="width: 50px;">Margin</th>
            <th style="width: 40px;">Qty</th>
            <th style="width: 80px;">Price</th>
            <th style="width: 70px;">Subtotal</th>
            
            <th style="width: 60px;">Residual</th>
            <th style="width: 60px;">Price</th>
            <th style="width: 80px;">Subtotal <i class="icon-info-sign pull-right" data-placement="left" data-title="Leasing Subtotal Details" data-content="This subtotal is rounded to the nearest whole number to give nice looking numbers to the client."></i></th>
            <th style="width: 30px;"></th>
        </tr>
        <?php foreach ($group->sets as $set) :
            /* @var $quoteDevice Quotegen_Model_QuoteDevice */
            $quoteDevice = $set->quoteDevice;
        ?>
        <tr class="deviceRow">
            <th><h5><?php echo $quoteDevice->getName(); ?><br><small><?php echo $quoteDevice->getSku(); ?></small></h5></th>                
            <td style="text-align: right;"><?php echo $this->currency($quoteDevice->calculatePackageCost()); ?></td>
            <td>
                <div class="control-group <?php echo ($set->margin->hasErrors()) ? 'error' : ''; ?>">
                    <?php if ($set->margin->hasErrors()) :?><i class="" data-title="Error" data-placement="top" data-content="<?php echo implode('<br>', $set->margin->getMessages()); ?>"><?php endif; ?>
                    <?php echo $set->margin->renderViewHelper(); ?>
                    <?php if ($set->margin->hasErrors()) :?></i><?php endif; ?>
                </div>
            </td>
            <td>
                <div class="control-group <?php echo ($set->quantity->hasErrors()) ? 'error' : ''; ?>">
                    <?php if ($set->quantity->hasErrors()) :?><i class="" data-title="Error" data-placement="top" data-content="<?php echo implode('<br>', $set->quantity->getMessages()); ?>"><?php endif; ?>
                    <?php echo $set->quantity->renderViewHelper();?>
                    <?php if ($set->quantity->hasErrors()) :?></i><?php endif; ?>
                </div>
            </td>
            <td>
                <div class="control-group <?php echo ($set->packagePrice->hasErrors()) ? 'error' : ''; ?>">
                    <?php if ($set->packagePrice->hasErrors()) :?><i class="" data-title="Error" data-placement="top" data-content="<?php echo implode('<br>', $set->packagePrice->getMessages()); ?>"><?php endif; ?>
                    <?php echo $set->packagePrice->renderViewHelper();?>
                    <?php if ($set->packagePrice->hasErrors()) :?></i><?php endif; ?>
                </div>
            </td>
            <td style="text-align: right;"><?php echo $this->currency($quoteDevice->calculateSubtotal()); ?></td>
            <td>
                <div class="control-group <?php echo ($set->residual->hasErrors()) ? 'error' : ''; ?>">
                    <?php if ($set->residual->hasErrors()) :?><i class="" data-title="Error" data-placement="top" data-content="<?php echo implode('<br>', $set->residual->getMessages()); ?>"><?php endif; ?>
                    <?php echo $set->residual->renderViewHelper();?>
                    <?php if ($set->residual->hasErrors()) :?></i><?php endif; ?>
                </div>
            </td>
            <td style="text-align: right;"><?php echo $this->currency($quoteDevice->calculateLeasePrice()); ?></td>
            <td style="text-align: right;"><?php echo $this->currency($quoteDevice->calculateLeaseSubtotal()); ?></td>
            <td>
                <div class="btn-group">
                    <a href="#" class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown"><i class="icon-wrench"></i></a>
                    <ul class="dropdown-menu pull-right">
                        <?php if ($quoteDevice->getDevice()) : ?>
                        <li><a href="<?php echo $this->url(array('action' => 'sync-device-configuration', 'id' => $quoteDevice->getId())); ?>"><i class="icon-refresh"></i> Sync Device</a>
                        <?php endif; ?>
                        <li><a href="<?php echo $this->url(array('action' => 'edit-quote-device', 'id' => $quoteDevice->getId())); ?>"><i class="icon-pencil"></i> Edit Device</a>
                        <li><a href="<?php echo $this->url(array('action' => 'delete-quote-device', 'id' => $quoteDevice->getId())); ?>"><i class="icon-trash"></i> Delete Device</a>
                    </ul>
                </div>
            </td>
        </tr>
        <?php if (count($quoteDevice->getQuoteDeviceOptions()) > 0) : ?>
            <?php foreach ($quoteDevice->getQuoteDeviceOptions() as $quoteDeviceOption) : /* @var $quoteDeviceOption Quotegen_Model_QuoteDeviceOption */ ?>
            <tr class="optionRow">
                <td><?php echo $quoteDeviceOption->getName(); ?><i class="icon-info-sign pull-right" data-placement="right" data-title="<?php echo $quoteDeviceOption->getSku(); ?>" data-content="<?php echo $quoteDeviceOption->getDescription(); ?>"></i><br><h5><small><?php echo $quoteDeviceOption->getSku(); ?></small></h5></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        
    <?php endforeach; ?>
    <tr class="header-row">
        <th>Pages</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th><button type="submit" name="addPages" value="<?php echo $quoteDeviceGroup->getId(); ?>" class="btn btn-success btn-mini"><i class="icon-plus-sign icon-white"></i></button></th>
    </tr>
    <?php if (count($quoteDeviceGroup->getPages()) > 0) :?>
    <?php foreach ($quoteDeviceGroup->getPages() as $quoteDeviceGroupPage) : /* @var $quoteDeviceGroupPage Quotegen_Model_QuoteDeviceGroupPage */ ?>
    <tr>
        <td><h5><?php echo $quoteDeviceGroupPage->getName(); ?><br><small><?php echo $quoteDeviceGroupPage->getSku(); ?></small></h5></td>
        <td></td>
        <td></td>
        <td></td>
        <td><?php echo number_format($quoteDeviceGroupPage->getIncludedQuantity()); ?></td>
        <td></td>
        <td></td>
        <td><?php echo $this->currency($quoteDeviceGroupPage->getCostPerPage()); ?></td>
        <td><?php echo $this->currency($quoteDeviceGroupPage->getIncludedPrice()); ?></td>
        <td></td>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    <tr class="header-row">
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th><?php echo $this->currency($quoteDeviceGroup->calculateGroupSubtotal()); ?></th>
        <th><?php echo $this->currency($quoteDeviceGroup->calculateTotalResidual()); ?></th>
        <th></th>
        <th><?php echo $this->currency($quoteDeviceGroup->calculateGroupLeaseSubtotal()); ?></th>
        <th></th>
    </tr>
    </table>
<?php endforeach; ?>
    <div class="form-actions">
        <input type="submit" name="back" value="Go Back" class="btn"/>
        <input type="submit" name="save" value="Save" class="btn btn-success"/>
        <input type="submit" name="saveAndContinue" value="Save &amp; Continue" class="btn btn-primary"/>
    </div>
    <?php echo $form->getElement('crsf_check')->renderViewHelper(); ?>
</form>