<?php 
/* @var $form Quotegen_Form_DeviceConfiguration */
$form = $this->element;
?>
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
    <h3>Device Configuration</h3>
    <?php echo $form->getElement('deviceName'); ?>
    <?php echo $form->getElement('name'); ?>
    <?php echo $form->getElement('sku'); ?>
    <?php echo $form->getElement('cost'); ?>
    <h3> Device Options <?php echo $form->getElement('add')->renderViewHelper(); ?></h3>
    <br>
    <?php if (count($form->getOptionElements()) > 0) : ?>
    <?php foreach ($form->getOptionElements() as $element) : ?>
    <div class="control-group <?php echo ($element->quantity->hasErrors() || $element->cost->hasErrors()) ? 'error' : '' ?>">
        <?php echo $element->quantity->renderLabel(); ?>
        <div class="controls">
        	<div class="input-prepend input-append">
        		<span class="add-on">Qty:</span><?php echo trim($element->quantity->renderViewHelper()); ?><span class='add-on' style="width: 150px; text-align: left;">Cost Per Unit: <?php echo $this->currency((float)$element->quoteDeviceOption->getCost()); ?></span><a href="<?php echo $this->url(array('action' => 'delete-option-from-quote-device', 'quoteDeviceOptionId' => $element->quantity->getDescription()));?>" class="add-on btn btn-danger"><i class="icon-trash"></i></a>
        	</div>
        	<?php
        	    echo $element->quantity->renderErrors();
        	    echo $element->cost->renderErrors();
        	 ?>
        </div>
	</div>
    <?php endforeach; ?>
    <?php else : ?>
    <p>There are no options added to this device yet.</p>
    <?php endif; ?>
    <div class="control-group">
        <label class="control-label optional">Package Cost Per Unit</label>
        <div class="controls">
            <input class="span2" disabled="disabled" style="padding-left: 2px" value="<?php echo $form->getQuoteDevice()->calculatePackageCost(); ?>" />
        </div>
    </div>
    <hr>
    <h3> Prices and Margins </h3> <br/>
    <?php echo $form->getElement('margin'); ?>
    <?php echo $form->getElement('packagePrice'); ?>
    <?php echo $form->getElement('residual'); ?>
    <?php echo $form->getElement('quantity'); ?>    
    
    
    <div class="control-group">
        <label class="control-label optional">Total Package Price</label>
        <div class="controls">
            <input class="span2" disabled="disabled" style="padding-left: 2px" value="<?php echo $form->getQuoteDevice()->calculatePurchaseSubtotal(); ?>" />
        </div>
    </div>
    
    
    <div class="form-actions">
        <?php echo $form->getElement('cancel')->renderViewHelper(); ?>
        <?php echo $form->getElement('submit')->renderViewHelper(); ?>
        <?php echo $form->getElement('saveAndFinish')->renderViewHelper(); ?>
    </div>    
</form>