<!-- Prompt to upgrade browsers/install chrome frame if IE 8 -->
<!--[if lt IE 9]>
<div class="alert alert-danger">
    <div class="container">
        <i class="fa fa-warning"></i> Your browser is
        <em>ancient!</em> Some of this sites functionality may not work correctly. Please update your browser or to a different browser to ensure the best possible experience.
        <a class="alert-link" href="http://browsehappy.com/">Click here for more information</a>
    </div>
</div>
<![endif]-->

