<!-- Sub Navbar -->
<?php $subNav = $this->Subnav(); ?>
<?php if (strlen($subNav) > 0) : ?>
    <nav class="navbar navbar-default navbar-static-top secondary-navbar" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand visible-xs" data-toggle="collapse" data-target="#top-navbar-collapse-2">Sub Menu</a>
            </div>
            <div class="collapse navbar-collapse" id="top-navbar-collapse-2">
                <?php echo $subNav; ?>
            </div>
            <!-- /Sub Navbar -->
        </div>
    </nav>
<?php endif; ?>