<?php
/* @var $memjetOptimization Memjetoptimization_Model_Memjet_Optimization */
$memjetOptimization = $this->memjetOptimization;
/* @var $form Proposalgen_Form_DeviceSwapChoice */
$form = $this->form;

$thresholdPercent = 30;
$targetBlackCPP = (float)$memjetOptimization->getMemjetOptimizationSetting()->targetMonochromeCostPerPage;
$thresholdBlackCpp = $targetBlackCPP * (1 - ($thresholdPercent / 100));
$targetColorCPP = (float)$memjetOptimization->getMemjetOptimizationSetting()->targetColorCostPerPage;
$thresholdColorCpp = $targetColorCPP * (1 - ($thresholdPercent / 100));
$optimizedTargetMonochromeCPP = (float)$memjetOptimization->getMemjetOptimizationSetting()->optimizedTargetMonochromeCostPerPage;
$optimizedTargetColorCPP = (float)$memjetOptimization->getMemjetOptimizationSetting()->optimizedTargetColorCostPerPage;
$formActions [] = $form->getElement('ResetReplacements');
$formActions [] = $form->getElement('Analyze');

?>
<br />
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
    <div class="clearfix">
        <?php foreach ($formActions as $element) : ?>
            <?php echo $element->renderViewHelper(); ?>
        <?php endforeach; ?>
    </div>
    <br />
    <!-- Begin Optimization Summary table -->
    <div id="optimizationSummary" style="position: relative; min-height: 100px">
        <div id="loadingDiv" style="position: absolute; height: 100%; width: 100%; top: 0; left:0; background-color: rgb(255,255,255);">
            <div class="spinner64"></div>
        </div>
        <div id="optimizationTable">
        </div>
    </div>

    <div id='replacementDevices'>

    </div>

    <table id='replacementDeviceTable' style="width: 100%" class="scroll"></table>
    <div id="replacementDevicePager"></div>

</form>



<?php $this->headScript()->captureStart('append', 'text/javascript'); ?>

var targetCostPerPageMono               = <?php echo $targetBlackCPP; ?>;
var targetCostPerPageMonoThreshold      = <?php echo $thresholdBlackCpp; ?>;
var targetCostPerPageColor              = <?php echo $targetColorCPP; ?>;
var targetCostPerPageColorThreshold     = <?php echo $thresholdColorCpp; ?>;
var optimizedTargetCostPerPageMono      = <?php echo $optimizedTargetMonochromeCPP; ?>;
var optimizedTargetCostPerPageColor     = <?php echo $optimizedTargetColorCPP; ?>;
var deviceListUrl                       = '<?php echo $this->baseUrl('memjetoptimization/index/get-device-by-device-instance-id'); ?>'

<?php $this->headScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/memjetoptimization/optimize.js')); ?>
<div id="deviceInstanceInformationModal">
    <table id="replacementInformationModalTable" style="width: 300px; float: right; border:1px solid black;">
    </table>
    <table id="deviceInstanceInformationModalTable" style="width: 300px; border:1px solid black;">
    </table>
    <p id="replacementReason"></p>
</div>
<?php echo $this->navigationForm; ?>

