<?php
/* @var $optimization Memjetoptimization_ViewModel_Optimization */
$optimization = $this->optmizationViewModel;
/* @var $MemjetOptimization Memjetoptimization_Model_Memjet_Optimization */
$MemjetOptimization = $this->memjetOptimization;
?>

<!-- Begin target cost per page table-->
<table class="table">
    <tbody>
    <tr>
        <td>
            <strong>Target Monochrome CPP
                : </strong><?php echo $this->currency((float)$MemjetOptimization->getMemjetOptimizationSetting()->targetMonochromeCostPerPage, array('precision' => 4)); ?>
        </td>
        <td>
            <strong>Target Color CPP
                : </strong><?php echo $this->currency((float)$MemjetOptimization->getMemjetOptimizationSetting()->targetColorCostPerPage, array('precision' => 4)); ?>
        </td>
        <td>
            <strong>Loss Threshold : </strong><?php echo $this->currency((float)$MemjetOptimization->getMemjetOptimizationSetting()->lossThreshold); ?>
        </td>
        <td>
            <strong>Pre Optimized Cost: </strong><span style="float:right"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage(), array('precision' => 2)) ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="3"></td>
        <td>
            <strong>Memjet Optimized Cost: </strong><span style="float:right" id="memjetOptimizedCost"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPageWithReplacements($MemjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio), array('precision' => 2)) ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="3"></td>
        <td>
            <strong>Savings: </strong><span style="float:right" id="savings"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage() - (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPageWithReplacements($MemjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio), array('precision' => 2)) ?></span>
        </td>
    </tr>
    </tbody>
</table>
<!-- End target cost per page table -->

<table class='table table-condensed' style="width: 100%">
    <thead>
    <tr class='header'>
        <td><strong>Fleet</strong></td>
        <td><strong>Weighted Monochrome CPP</strong></td>
        <td><strong>Weighted Color CPP</strong></td>
        <td><strong>Total Cost</strong></td>
        <td><strong>Margin $</strong></td>
        <td><strong>Margin %</strong></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td> Current</td>
        <td><?php echo $this->currency($optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage, array('precision' => 4)); ?></td>
        <td><?php echo ($optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage > 0) ? $this->currency($optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage, array('precision' => 4)) : 'N/A'; ?></td>
        <td><?php echo $this->currency($optimization->calculateDealerMonthlyCost()); ?></td>
        <td><?php echo $this->currency($optimization->calculateDealerMonthlyProfitUsingTargetCostPerPage()); ?></td>
        <td><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCost(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2); ?>
            %
        </td>
    </tr>
    <tr>
        <td> Optimized</td>
        <td id="monochromeCpp"><?php echo $this->currency((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements($MemjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)->monochromeCostPerPage, array('precision' => 4)) ?></td>
        <td id="colorCpp"><?php echo ((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements($MemjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)->colorCostPerPage > 0) ? $this->currency((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage, array('precision' => 4)) : 'N/A'; ?></td>
        <td id="totalCost"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyCostWithReplacements($MemjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio), array('precision' => 2)) ?></td>
        <td id="marginDollar"><?php echo $this->currency((float)$optimization->calculateDealerMonthlyProfitUsingTargetCostPerPageAndReplacements($MemjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio), array('precision' => 2)) ?></td>
        <td id="marginPercent"><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCostWithReplacements($MemjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2) ?>
            %
        </td>
    </tr>
    </tbody>
</table>
<em>The following <?php echo count($optimization->getDevices()->purchasedDeviceInstances->getDeviceInstances()); ?> out
    of <?php echo $optimization->getDevices()->allIncludedDeviceInstances->getCount(); ?> devices are
    eligible for potential optimization.</em>