<?php
/* @var $optimizationViewModel Memjetoptimization_ViewModel_Optimization */
$optimizationViewModel = $this->optmizationViewModel;
/* @var $memjetOptimization Memjetoptimization_Model_Memjet_Optimization */
$memjetOptimization = $this->memjetOptimization;
?>

<h3>Settings</h3>
<table class="table">
    <tbody>
    <tr>
        <td>
            <strong>Target Monochrome CPP : </strong><?php echo $this->formatCostPerPage((float)$memjetOptimization->getMemjetOptimizationSetting()->targetMonochromeCostPerPage); ?>
        </td>
        <td>
            <strong>Target Color CPP : </strong><?php echo $this->formatCostPerPage((float)$memjetOptimization->getMemjetOptimizationSetting()->targetColorCostPerPage); ?>
        </td>
        <td>
            <strong>Mono/Color Conversion: </strong><?php echo number_format((float)$memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio); ?>%
        </td>
    </tr>
    <tr>
        <td>
            <strong>Optimized Target Monochrome CPP : </strong><?php echo $this->formatCostPerPage((float)$memjetOptimization->getMemjetOptimizationSetting()->optimizedTargetMonochromeCostPerPage); ?>
        </td>
        <td>
            <strong>Optimized Target Color CPP : </strong><?php echo $this->formatCostPerPage((float)$memjetOptimization->getMemjetOptimizationSetting()->optimizedTargetColorCostPerPage); ?>
        </td>
        <td>
        </td>
    </tr>
    <tr>
        <td>
            <strong>Loss Threshold : </strong><?php echo $this->currency((float)$memjetOptimization->getMemjetOptimizationSetting()->lossThreshold); ?>
        </td>
        <td>
            <strong>Cost Savings Threshold : </strong><?php echo $this->currency((float)$memjetOptimization->getMemjetOptimizationSetting()->costThreshold); ?>
        </td>
        <td>&nbsp;</td>
    </tr>
    </tbody>
</table>

<h3>Current Metrics</h3>

<!-- Begin target cost per page table-->
<table class="table optimization-summary-table">
    <tbody>
    <tr>
        <td class="description"><strong>Mono CPP :</strong></td>
        <td><?php echo $this->formatCostPerPage($optimizationViewModel->calculateDealerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage); ?></td>
        <td class="description"><strong>Color CPP :</strong></td>
        <td><?php echo $this->formatCostPerPage($optimizationViewModel->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage); ?></td>
        <td class="description"><strong>Customer Cost :</strong></td>
        <td><?php echo $this->currency((float)$optimizationViewModel->calculateDealerMonthlyRevenueUsingTargetCostPerPage()) ?></td>
    </tr>
    <tr>
        <td class="description"><strong>Mono Volume : </strong></td>
        <td><?php echo $this->formatPageVolume($optimizationViewModel->getPageCounts()->getBlackPageCount()->getMonthly()); ?> (<?php echo number_format($optimizationViewModel->getPageCounts()->getMonochromePagePercentage()); ?>%)</td>
        <td class="description"><strong>Color Volume : </strong></td>
        <td><?php echo $this->formatPageVolume($optimizationViewModel->getPageCounts()->getColorPageCount()->getMonthly()); ?> (<?php echo number_format($optimizationViewModel->getPageCounts()->getColorPagePercentage()); ?>%)</td>
        <td class="description"><strong>Dealer Cost :</strong></td>
        <td><?php echo $this->currency($optimizationViewModel->calculateDealerMonthlyCost()); ?></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
        <td class="description"><strong>Gross Margin :</strong></td>
        <td><?php echo $this->currency($optimizationViewModel->calculateDealerMonthlyProfitUsingTargetCostPerPage()); ?> (<?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimizationViewModel->calculateDealerMonthlyCost(), (float)$optimizationViewModel->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2); ?>%)</td>
    </tr>
    </tbody>
</table>

<h3>Memjet Optimized Metrics</h3>

<!-- Begin target cost per page table-->
<table class="table optimization-summary-table">
    <tbody>
    <tr>
        <td class="description"><strong>Mono CPP :</strong></td>
        <td id="monochromeCpp"><?php echo $this->formatCostPerPage((float)$optimizationViewModel->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)->monochromeCostPerPage, array('precision' => 4)) ?></td>
        <td class="description"><strong>Color CPP :</strong></td>
        <td id="colorCpp"><?php echo ((float)$optimizationViewModel->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)->colorCostPerPage > 0) ? $this->currency((float)$optimizationViewModel->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage) : 'N/A'; ?></td>
        <td class="description"><strong>Customer Cost :</strong></td>
        <td id="totalRevenue"><?php echo $this->currency((float)$optimizationViewModel->calculateDealerMonthlyRevenueUsingTargetCostPerPageWithReplacements($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)) ?></td>
    </tr>
    <tr>
        <td class="description"><strong>Mono Volume : </strong></td>
        <td>
            <span id="monoVolume"><?php echo $this->formatPageVolume($optimizationViewModel->getPageCounts($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)->getBlackPageCount()->getMonthly()); ?></span> (<span id="monoVolumePercent"><?php echo number_format($optimizationViewModel->getPageCounts($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)->getMonochromePagePercentage()); ?></span>%)
        </td>
        <td class="description"><strong>Color Volume : </strong></td>
        <td>
            <span id="colorVolume"><?php echo $this->formatPageVolume($optimizationViewModel->getPageCounts($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)->getColorPageCount()->getMonthly()); ?></span> (<span id="colorVolumePercent"><?php echo number_format($optimizationViewModel->getPageCounts($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)->getColorPagePercentage()); ?></span>%)
        </td>
        <td class="description"><strong>Dealer Cost :</strong></td>
        <td id="totalCost"><?php echo $this->currency((float)$optimizationViewModel->calculateDealerMonthlyCostWithReplacements($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)) ?></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
        <td class="description"><strong>Gross Margin :</strong></td>
        <td>
            <span id="marginDollar"><?php echo $this->currency((float)$optimizationViewModel->calculateDealerMonthlyProfitUsingTargetCostPerPageAndReplacements($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)) ?></span> (<span id="marginPercent"><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$optimizationViewModel->calculateDealerMonthlyCostWithReplacements($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio), (float)$optimizationViewModel->calculateDealerMonthlyRevenueUsingTargetCostPerPageWithReplacements($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio)), 2) ?></span>%)
        </td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
        <?php
        /**
         * FIXME lrobert: This needs  to be removed from the view script
         */
        $grossMarginDelta =
            (float)$optimizationViewModel->calculateDealerMonthlyProfitUsingTargetCostPerPageAndReplacements($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio) -
            (float)$optimizationViewModel->calculateDealerMonthlyProfitUsingTargetCostPerPage();
        ?>
        <td class="description">
            <strong id="grossMarginDeltaTitle"><?php echo ($grossMarginDelta >= 0) ? 'Gross Margin Increase' : 'Gross Margin Decrease'; ?> :</strong></td>
        <td id="grossMarginDelta"><?php echo $this->currency(abs($grossMarginDelta)) ?></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
        <?php
        /**
         * FIXME lrobert: This needs  to be removed from the view script
         */
        $customerCostDelta =
            (float)$optimizationViewModel->calculateDealerMonthlyRevenueUsingTargetCostPerPageWithReplacements($memjetOptimization->getMemjetOptimizationSetting()->blackToColorRatio) -
            (float)$optimizationViewModel->calculateDealerMonthlyRevenueUsingTargetCostPerPage();
        ?>
        <td class="description">
            <strong id="customerCostDeltaTitle"><?php echo ($customerCostDelta >= 0) ? 'Customer Cost Increase' : 'Customer Cost Decrease'; ?> :</strong></td>
        <td id="customerCostDelta"><?php echo $this->currency(abs($customerCostDelta)) ?></td>
    </tr>

    </tbody>
</table>
<em>The following
    <span id="numberOfDevicesReplaced"><?php echo number_format($optimizationViewModel->getNumberOfDevicesWithReplacements()); ?></span> out of <?php echo number_format($optimizationViewModel->getDevices()->purchasedDeviceInstances->getCount()); ?> eligible devices have been selected for replacement.</em>