<?php 
?>
<form name="leasingSchemaTerm" id="leasingSchemaTerm" class="form-horizontal" action="<?php echo $this->element->getAction() ?>" method="<?php echo $this->element->getMethod() ?>">

	<div class="control-group">
		<label class="control-label pull-left" for="term">Term Value: </label>
		<div class="controls">
			<input type="text" name="term" id="term" class="span1 focused" value="">
		</div>
	</div>
	
	<div class="controls">
		<table class="table table-stripped table-bordered">
			<thead>
				<tr>
					<th style="text-align: left;">Range</th>
					<?php // loop through ranges ?>
					<th style="text-align: center;">$0</th>
					<?php // } ?>
					<th style="text-align: center;">$1,000.00</th>
					<th style="text-align: center;">$50,000.00</th>
					<th style="text-align: center;">$100,000.00</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>Rate</th>
					<?php // loop through ranges ?>
					<td style="text-align: center;"><input type="text" name="range1-rate" id="range1-rate" class="span1" value="" /></td>
					<?php // } ?>
					<td style="text-align: center;"><input type="text" name="range2-rate" id="range2-rate" class="span1" value="" /></td>
					<td style="text-align: center;"><input type="text" name="range3-rate" id="range3-rate" class="span1" value="" /></td>
					<td style="text-align: center;"><input type="text" name="range4-rate" id="range4-rate" class="span1" value="" /></td>
				</tr>
			</tbody>
		</table>
	</div>
	
	<div>
		<?php echo $this->element->submit ?>
		<?php echo $this->element->cancel ?>
	</div>

</form>
