<?php 
$leasingSchemaTerms = $this->leasingSchemaTerms;
?>
<form name="leasingSchemaTerm" id="leasingSchemaTerm" class="form-horizontal" action="<?php echo $this->element->getAction() ?>" method="<?php echo $this->element->getMethod() ?>">

	<div class="control-group">
		<label class="control-label pull-left" for="range">Term Value: </label>
		<div class="controls">
			<?php echo $this->element->getElement("range")->renderViewHelper(); ?>
		</div>
	</div>
	
	<div class="controls">
		<table class="table table-stripped table-bordered" style="width: auto;">
			<thead>
				<tr>
					<th style="text-align: left;">Term</th>
					<th style="text-align: center;">Rate</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ( $leasingSchemaTerms as $term ) { ?>
				<tr>
					<td style="text-align: left;"><?php echo $term->getMonths(); ?></td>
					<td style="text-align: center;"><?php echo $this->element->getElement("term{$term->getId()}")->renderViewHelper(); ?></td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
	
	<div>
		<?php echo $this->element->submit; ?>
		<?php echo $this->element->cancel; ?>
	</div>

</form>
