<?php
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/common_all.css"));
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/common_html.css"));
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/solution/solution_html.css"));
?>
<div class="container" id="htmlReportContainer">
    <?php echo $this->render('report/olddevicelist/html/01_Appendix.phtml'); ?>
</div>