<?php

use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$this->brandName     = My_Brand::getDealerBranding()->mpsProgramName;
$this->companyName   = My_Brand::getDealerBranding()->shortDealerName;
?>
<h2>Old Device List</h2>
<table class="table table-bordered table-condensed" id="AppendixDeviceTable">
    <thead>
    <tr>
        <th>Device</th>
        <th>Serial No.</th>
        <th>IP Address</th>
        <th>Device Age (In Years)</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($assessmentViewModel->getIncludedDevicesSortedAscendingByAge() as $deviceInstance) : ?>
        <tr>
            <td class="device-name"><?= $deviceInstance->getMasterDevice()->getFullDeviceName(); ?></td>
            <td class="serial-number"><?= ($deviceInstance->serialNumber) ?: "Unknown"; ?></td>
            <td class="ip-address"><?= ($deviceInstance->ipAddress) ?: "Unknown"; ?></td>
            <td class="age"><?= $deviceInstance->getAge(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>