<?php
/* @var $section PHPWord_Section */
$section   = $this->section;

/* @var $contractTemplateSection Quotegen_Model_ContractTemplateSection */
$contractTemplateSection = $this->contractTemplateSection;


$tableSpan = $this->tableStyle->gridSpan;
$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;

$customerTable = $section->addTable($this->tableStyle->standard);
$customerTable->addRow();
$customerTable->addCell($tableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText($contractTemplateSection->getContractSectionName(), $this->fontStyle->invertBackground, $noSpacing);

$customerTable->addRow();
$textRun = $customerTable->addCell($tableSpan ['span8'], $this->cellStyle->bottomBorder, 8)->createTextRun($noSpacing);
$textRun->addText(" FULL LEGAL NAME: ", $labelFont);
$textRun->addText(" {$this->company->name}", $this->fontStyle->bold);

$customerTable->addRow();
$textRun = $customerTable->addCell($tableSpan ['span8'], null, 8)->createTextRun($noSpacing);
$textRun->addText(" ADDRESS: ", $labelFont);
$textRun->addText(" {$this->company->address}", $this->fontStyle->bold);
