<?php
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $contractTemplateSection Quotegen_Model_ContractTemplateSection */
$contractTemplateSection = $this->contractTemplateSection;

$tableSpan = $this->tableStyle->gridSpan;
$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;

$contractTable = $section->addTable($this->tableStyle->standard);
$contractTable->addRow();
$contractTable->addCell($tableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText($contractTemplateSection->getContractSectionName(), $this->fontStyle->invertBackground, $noSpacing);


$contractHtml = new DOMDocument(5);
$contractHtml->loadHTML($contractTemplateSection->getContractSectionText());

/* @var $childNode DOMElement */
foreach ($contractHtml->getElementsByTagName('p') as $paragraphNode)
{
    $contractTable->addRow();
    $cell    = $contractTable->addCell($tableSpan ['span8'], null, 8);
    $textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);

    $childNodes = $paragraphNode->childNodes;
    for ($i = 0; $i < $childNodes->length; $i++)
    {
        /** @var $node DOMElement */
        $node = $childNodes->item($i);

        if ($node->tagName == 'b')
        {
            $textRun->addText($node->textContent, $this->fontStyle->boldFinePrint);
        }
        else
        {
            $textRun->addText($node->textContent, $this->fontStyle->finePrint);
        }
    }
}