<?php
/* @var $section PHPWord_Section */
$section   = $this->section;

/* @var $contractTemplateSection Quotegen_Model_ContractTemplateSection */
$contractTemplateSection = $this->contractTemplateSection;

$tableSpan = $this->tableStyle->gridSpan;
$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;

$customerSignatureTable = $section->addTable($this->tableStyle->standard);
$customerSignatureTable->addRow();
$customerSignatureTable->addCell($tableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText($contractTemplateSection->getContractSectionName(), $this->fontStyle->invertBackground, $noSpacing);

/**
 * Signature Text
 */
$guarantyHtml = new DOMDocument(5);
$guarantyHtml->loadHTML($contractTemplateSection->getContractSectionText());

/* @var $childNode DOMElement */
foreach ($guarantyHtml->getElementsByTagName('p') as $paragraphNode)
{
    $customerSignatureTable->addRow();
    $cell    = $customerSignatureTable->addCell($tableSpan ['span8'], null, 8);
    $textRun = $cell->createTextRun($this->paragraphStyle->justified);

    $childNodes = $paragraphNode->childNodes;
    for ($i = 0; $i < $childNodes->length; $i++)
    {
        /** @var $node DOMElement */
        $node = $childNodes->item($i);

        if ($node->tagName == 'b')
        {
            $textRun->addText($node->textContent, $this->fontStyle->boldFinePrint);
        }
        else
        {
            $textRun->addText($node->textContent, $this->fontStyle->finePrint);
        }
    }
}

/**
 * Actual Signature Row
 */
$customerSignatureTable->addRow(350);
$customerSignatureTable->addCell($tableSpan ['span2'], $this->cellStyle->bottomBorderBAlign)->addText('(As Stated Above)', null, $noSpacing);
$customerSignatureTable->addCell($tableSpan ['span3'], $this->cellStyle->borderBAlign, 3)->addText('X', null, $noSpacing);
$customerSignatureTable->addCell($tableSpan ['span3'], $this->cellStyle->bottomBorderBAlign, 3)->addText('', null, $noSpacing);
$customerSignatureTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText('', null, $noSpacing);
$customerSignatureTable->addRow();
$customerSignatureTable->addCell($tableSpan ['span1'], null)->addText('CUSTOMER', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$customerSignatureTable->addCell($tableSpan ['span3'], null, 3)->addText('SIGNATURE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$customerSignatureTable->addCell($tableSpan ['span3'], null, 3)->addText('PRINT NAME & TITLE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$customerSignatureTable->addCell($tableSpan ['span1'], null)->addText('DATE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);