<?php
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $contractTemplateSection Quotegen_Model_ContractTemplateSection */
$contractTemplateSection = $this->contractTemplateSection;

$tableSpan = $this->tableStyle->gridSpan;
$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;

$footerTable = $section->addTable($this->tableStyle->standard);
$footerTable->addRow(300);
$footerTable->addCell($tableSpan ['span8'], $this->cellStyle->fullWidthGridSpan4)->addText($contractTemplateSection->getContractSectionName(), $this->fontStyle->invertBackground, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($tableSpan ['span8'], $this->cellStyle->gridSpan4)->addText(' ', $this->fontStyle->finePrint, $noSpacing);
$footerTable->addRow(350);
$footerTable->addCell($tableSpan ['span2'], $this->cellStyle->bottomBorderBAlign)->addText(' ', null, $noSpacing);
$footerTable->addCell($tableSpan ['span3'], $this->cellStyle->borderBAlign)->addText('X', null, $noSpacing);
$footerTable->addCell($tableSpan ['span3'], $this->cellStyle->bottomBorderBAlign)->addText('', null, $noSpacing);
$footerTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText('', null, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($tableSpan ['span1'], $this->cellStyle->borderTop)->addText('OWNER', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($tableSpan ['span3'], $this->cellStyle->borderTop)->addText('SIGNATURE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($tableSpan ['span3'], $this->cellStyle->borderTop)->addText('PRINT NAME & TITLE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($tableSpan ['span1'], $this->cellStyle->borderTop)->addText('DATE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
