<?php
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $contractTemplateSection Quotegen_Model_ContractTemplateSection */
$contractTemplateSection = $this->contractTemplateSection;

$tableSpan = $this->tableStyle->gridSpan;
$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;


// Begin Terms Table
$termDetailsTable = $section->addTable($this->tableStyle->standard);
$termDetailsTable->addRow();
$termDetailsTable->addCell($tableSpan ['span8'], $this->cellStyle->fullWidthGridSpan8)->addText($contractTemplateSection->getContractSectionName(), $this->fontStyle->invertBackground, $noSpacing);
$termDetailsTable->addRow();
$termDetailsTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->gridSpan2, $this->cellStyle->middle))->addText('TERM IN MONTHS: ' . $this->leaseDetails->termInMonths, $labelFont, $noSpacing);
$termDetailsTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->gridSpan2, $this->cellStyle->middle))->addText('SECURITY DEPOSIT ' . $this->leaseDetails->securityDeposit, $labelFont, $noSpacing);
$termDetailsTable->addCell($tableSpan ['span4'], array_merge($this->cellStyle->gridSpan4, $this->cellStyle->middle))->addText('METER FREQUENCY: MONTHLY OR SPECIFY OTHER: ___________', $labelFont, $noSpacing);

$section->addText(' ');
$leaseDetailsTable = $section->addTable($this->tableStyle->standard);
$leaseDetailsTable->getStyle()->setBorderLeftSize(1);
$leaseDetailsTable->getStyle()->setBorderRightSize(1);
$leaseDetailsTable->getStyle()->setBorderBottomSize(1);

$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->fullWidthGridSpan4)->addText($this->header->sectionHeader[2], $this->fontStyle->invertBackground, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->fullWidthGridSpan4)->addText($this->header->sectionHeader[3], $this->fontStyle->invertBackground, $noSpacing);
// Row #1
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->leftBorder, $this->cellStyle->gridSpan2))->addText('', null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText(' B&W', $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign)->addText(' COLOR', $labelFont, $noSpacing);

$firstRowTextRun = $leaseDetailsTable->addCell($tableSpan ['span4'], array_merge($this->cellStyle->gridSpan4))->addTextRun($noSpacing);

$firstRowTextRun->addText('MONTHLY FIXED CHARGE: ', $labelFont);
$firstRowTextRun->addText("{$this->leaseDetails->monthlyCharge}", $this->fontStyle->underline);
$firstRowTextRun->addText("**");

// Row #2
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->leftBorderBAlign, $this->cellStyle->gridSpan2))->addText("PER PAGE CHARGE**: ", $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], array_merge($this->cellStyle->bottomBorderBAlign, $this->cellStyle->borderTop))
                  ->addText("\${$this->leaseDetails->blackPerPageCharge}", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], array_merge($this->cellStyle->bottomRightBorderBAlign, $this->cellStyle->borderTop))
                  ->addText("\${$this->leaseDetails->colorPerPageCharge}", null, $noSpacing);

$leaseDetailsTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->bottomAlign, $this->cellStyle->gridSpan2))->addText(" ", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText("B&W ONLY DEVICE(S)", $labelFont, $this->paragraphStyle->noSpacingCentered);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign, $this->cellStyle->gridSpan2)->addText("B&W AND COLOR DEVICE(S)", $labelFont, $this->paragraphStyle->noSpacingCentered);

// Row #3
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->gridSpan2))->addText("", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->gridSpan2, $this->cellStyle->borderTop))->addText("", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->leftBorder, $this->cellStyle->gridSpan2))->addText('MONTLY ALLOWANCE PER DEVICE:  ', $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->borderTop)->addText("{$this->leaseDetails->monochromeAllowance}", null, $this->paragraphStyle->noSpacingCentered);
$leaseDetailsTable->addCell($tableSpan ['span1'], array_merge($this->cellStyle->borderTop))->addText("{$this->leaseDetails->colorAllowance}", null, $this->paragraphStyle->noSpacingCentered);

// Row #4
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], array_merge($this->cellStyle->gridSpan4))->addText("", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->leftBorder, $this->cellStyle->gridSpan2))->addText("EXCESS PER PAGE CHARGE**:  ", $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->borderTop)->addText("\${$this->leaseDetails->monochromeCPP}", null, $this->paragraphStyle->noSpacingCentered);
$leaseDetailsTable->addCell($tableSpan ['span1'], array_merge($this->cellStyle->borderTop))->addText("\${$this->leaseDetails->colorCPP}", null, $this->paragraphStyle->noSpacingCentered);

// Row #5
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], array_merge($this->cellStyle->gridSpan4, $this->cellStyle->borderRight))->addText("PROGRAM SET-UP FEE {$this->leaseDetails->programFee}", $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->gridSpan4)->addText("PROGRAM SET-UP FEE {$this->leaseDetails->programFee}", $labelFont, $noSpacing);

// Row #6t
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->gridSpan4)->addText("APPLIES TO \"YOUR DEVICES\" AS DEFINED BELOW       (**PLUS TAX)", $labelFont, $noSpacing);
$textRun = $leaseDetailsTable->addCell($tableSpan ['span4'], array_merge($this->cellStyle->gridSpan4, $this->cellStyle->borderLeft))->addTextRun($noSpacing);

$textRun->addText('INSTALLATION FEE: ', $labelFont);
$textRun->addText('$0.00 ', $this->fontStyle->bold);
$textRun->addText('DEVICES X ', $labelFont);
$textRun->addText('$0.00', $this->fontStyle->bold);
$textRun->addText('PER DEVICE = ', $labelFont);
$textRun->addText('$0.00', $this->fontStyle->bold);

// Row #7
$leaseDetailsTable->addRow(400);
$leaseDetailsTable->addCell($tableSpan ['span4'], array_merge($this->cellStyle->gridSpan4))->addText("", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span4'], array_merge($this->cellStyle->gridSpan4, $this->cellStyle->borderLeft))->addText("SEE MPS PROGRAM PLUS EQUIPMENT AND SCHEDULE AND DEVICE USAGE TERMS AND CONDITIONS (**PLUS TAX)", $labelFont, $noSpacing);
