<?php
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $contractTemplateSection Quotegen_Model_ContractTemplateSection */
$contractTemplateSection = $this->contractTemplateSection;

$tableSpan = $this->tableStyle->gridSpan;
$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;


// Begin Terms Table
$termDetailsTable = $section->addTable($this->tableStyle->standard);
$termDetailsTable->addRow();
$termDetailsTable->addCell($tableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText($contractTemplateSection->getContractSectionName(), $this->fontStyle->invertBackground, $noSpacing);
$termDetailsTable->addRow();
$termDetailsTable->addCell($tableSpan ['span1'], null, 2)->addText('TERM IN MONTHS: ' . $this->leaseDetails->termInMonths, $labelFont, $noSpacing);
$termDetailsTable->addCell($tableSpan ['span1'], null, 2)->addText('SECURITY DEPOSIT ' . $this->leaseDetails->securityDeposit, $labelFont, $noSpacing);
$termDetailsTable->addCell($tableSpan ['span4'], null, 4)->addText('METER FREQUENCY: MONTHLY OR SPECIFY OTHER: ___________', $labelFont, $noSpacing);

$leaseDetailsTable = $section->addTable($this->tableStyle->standard);
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->invertBackground, 4)->addText($this->header->sectionHeader[2], $this->fontStyle->invertBackground, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->invertBackground, 4)->addText($this->header->sectionHeader[3], $this->fontStyle->invertBackground, $noSpacing);
// Row #1
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText('', null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText(' B&W', $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign)->addText(' COLOR', $labelFont, $noSpacing);
$firstRowTextRun = $leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->leftRightBorder, 4)->createTextRun($noSpacing);
$firstRowTextRun->addText('MONTHLY FIXED CHARGE: ', $labelFont);
$firstRowTextRun->addText("{$this->leaseDetails->monthlyCharge}", $this->fontStyle->underline);
$firstRowTextRun->addText("**");

// Row #2
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span2'], $this->cellStyle->leftBorderBAlign, 2)->addText("PER PAGE CHARGE**: ", $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText("\${$this->leaseDetails->blackPerPageCharge}", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign)->addText("\${$this->leaseDetails->colorPerPageCharge}", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span2'], $this->cellStyle->bottomAlign, 2)->addText("", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText("B&W ONLY DEVICE(S)", $labelFont, $this->paragraphStyle->noSpacingCentered);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign)->addText("B&W AND COLOR DEVICE(S)", $labelFont, $this->paragraphStyle->noSpacingCentered);

// Row #3
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->leftBorder, 4)->addText("", null, $noSpacing);
// $leaseDetailsTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText('MONTLY ALLOWANCE PER DEVICE:  ', $labelFont, $this->paragraphStyle->noSpacingRight);
$leaseDetailsTable->addCell($tableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText('MONTLY ALLOWANCE PER DEVICE:  ', $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomBorder)->addText("{$this->leaseDetails->monochromeAllowance}", null, $this->paragraphStyle->noSpacingCentered);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomRightBorder)->addText("{$this->leaseDetails->colorAllowance}", null, $this->paragraphStyle->noSpacingCentered);

// Row #4
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->leftBorder, 4)->addText("", null, $noSpacing);
// $leaseDetailsTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText("EXCESS PER PAGE CHARGE**:  ", $labelFont, $this->paragraphStyle->noSpacingRight);
$leaseDetailsTable->addCell($tableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText("EXCESS PER PAGE CHARGE**:  ", $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomBorder)->addText("\${$this->leaseDetails->monochromeCPP}", null, $this->paragraphStyle->noSpacingCentered);
$leaseDetailsTable->addCell($tableSpan ['span1'], $this->cellStyle->bottomRightBorder)->addText("\${$this->leaseDetails->colorCPP}", null, $this->paragraphStyle->noSpacingCentered);

// Row #5
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->leftBorder, 4)->addText("PROGRAM SET-UP FEE {$this->leaseDetails->programFee}", $labelFont, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->leftRightBorder, 4)->addText("PROGRAM SET-UP FEE {$this->leaseDetails->programFee}", $labelFont, $noSpacing);

// Row #6t
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->leftRightBorder, 4)->addText("APPLIES TO \"YOUR DEVICES\" AS DEFINED BOLOW       (**PLUS TAX)", $labelFont, $noSpacing);
$textRun = $leaseDetailsTable->addCell($tableSpan ['span4'], $this->cellStyle->rightBorder, 4)->createTextRun($noSpacing);
$textRun->addText('INSTALLATION FEE: ', $labelFont);
$textRun->addText('$0.00 ', $this->fontStyle->bold);
$textRun->addText('DEVICES X ', $labelFont);
$textRun->addText('$0.00', $this->fontStyle->bold);
$textRun->addText('PER DEVICE = ', $labelFont);
$textRun->addText('$0.00', $this->fontStyle->bold);

// Row #7
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($tableSpan ['span4'], array_merge($this->cellStyle->leftRightBorder, $this->cellStyle->bottomBorder), 4)->addText("", null, $noSpacing);
$leaseDetailsTable->addCell($tableSpan ['span4'], array_merge($this->cellStyle->rightBorder, $this->cellStyle->bottomBorder), 4)->addText("SEE MPS PROGRAM PLUS EQUIPMENT AND SCHEDULE AND DEVICE USAGE TERMS AND CONDITIONS (**PLUS TAX)", $labelFont, $noSpacing);