<?php
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $contractTemplateSection Quotegen_Model_ContractTemplateSection */
$contractTemplateSection = $this->contractTemplateSection;

$tableSpan = $this->tableStyle->gridSpan;
$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;


// Begin Terms Table
$termDetailsTable = $section->addTable($this->tableStyle->standard);
$termDetailsTable->getStyle()->setBorderBottomSize(1);
$termDetailsTable->getStyle()->setBorderRightSize(1);
$termDetailsTable->getStyle()->setBorderLeftSize(1);


$termDetailsTable->addRow();
$termDetailsTable->addCell($tableSpan ['span8'], $this->cellStyle->fullWidthGridSpan8)->addText($contractTemplateSection->getContractSectionName(), $this->fontStyle->invertBackground, $noSpacing);
$termDetailsTable->addRow();

/**
 * Term & Payment
 */
$termAndPaymentCell = $termDetailsTable->addCell($tableSpan ['span3'], $this->cellStyle->gridSpan3);
$termAndPaymentCell->addText('TERM IN MONTHS      : ' . $this->leaseDetails->termInMonths . ' Months', $labelFont, $noSpacing);

$termAndPaymentTextRun = $termAndPaymentCell->addTextRun($noSpacing);
$termAndPaymentTextRun->addText('MONTHLY FIXED CHARGE: ', $labelFont);
$termAndPaymentTextRun->addText("{$this->leaseDetails->monthlyCharge}", array_merge($labelFont, $this->fontStyle->underline, $this->fontStyle->bold));
$termAndPaymentTextRun->addText("**");

$termAndPaymentCell->addText('SEE ATTACHED EQUIPMENT LIST [ ]', $labelFont, $noSpacing);

/**
 * Security Deposit
 */
$securityDepositCell = $termDetailsTable->addCell($tableSpan ['span2'], $this->cellStyle->gridSpan2);
$securityDepositCell->addText('SECURITY DEPOSIT ' . $this->leaseDetails->securityDeposit, $labelFont, $noSpacing);

/**
 * Purchase Option Cell
 */
$purchaseOptionCell = $termDetailsTable->addCell($tableSpan ['span3'], $this->cellStyle->gridSpan3);
$purchaseOptionCell->addText('Purchase Option: [ ] Fair Market Value', $labelFont, $noSpacing);
$purchaseOptionCell->addText('                 [ ] 10% of Equipment Cost', $labelFont, $noSpacing);
$purchaseOptionCell->addText('                 [ ] Other:________________', $labelFont, $noSpacing);