<?php
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $quote Quotegen_Model_Quote */
$quote = $this->quote;

/* @var $contractTemplateSection Quotegen_Model_ContractTemplateSection */
$contractTemplateSection = $this->contractTemplateSection;

$tableSpan = $this->tableStyle->gridSpan;
$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;


/**
 * Devices Table - Title Row
 */
$deviceTable = $section->addTable($this->tableStyle->standard);
$deviceTable->getStyle()->setBorderBottomSize(1);
$deviceTable->getStyle()->setBorderLeftSize(1);
$deviceTable->getStyle()->setBorderRightSize(1);

$deviceTable->addRow(300);
$deviceTable->addCell(null, $this->cellStyle->fullWidthGridSpan3)->addText($contractTemplateSection->getContractSectionName(), $this->fontStyle->invertBackground, $this->paragraphStyle->noSpacing);

/**
 * Devices Table - Header Row
 */
$deviceTable->addRow(300);
$deviceTable->addCell($tableSpan ['span3'], $this->cellStyle->bottomAlign)->addText('MAKE, MODEL NUMBER & INCLUDED ACCESSORIES', $this->fontStyle->label, $this->paragraphStyle->noSpacing);
$deviceTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->bottomAlign, $this->cellStyle->borderRight))->addText('SERIAL NUMBER', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$deviceTable->addCell($tableSpan ['span3'], $this->cellStyle->bottomRightBorderBAlign)->addText('ADDRESS', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);

/**
 * Devices Table - Device Rows
 */
foreach ($quote->getQuoteDevices() as $quoteDevice)
{
    for ($i = 0; $i < $quoteDevice->calculateTotalQuantity(); $i++)
    {
        $deviceTable->addRow(600);
        $deviceDetailsCell = $deviceTable->addCell($tableSpan ['span3'], $this->cellStyle->borderTop);
        $deviceDetailsCell->addText($quoteDevice->name, null, $this->paragraphStyle->noSpacing);

        foreach ($quoteDevice->getQuoteDeviceOptions() as $quoteDeviceOption)
        {
            $deviceDetailsCell->addText('    - ' . $quoteDeviceOption->quantity . ' x ' . $quoteDeviceOption->name, $this->fontStyle->finePrint, $this->paragraphStyle->noSpacing);
        }

        $deviceTable->addCell($tableSpan ['span2'], array_merge($this->cellStyle->bottomRightBorder, $this->cellStyle->borderTop))->addText(' ', null, $this->paragraphStyle->noSpacing);
        $deviceTable->addCell($tableSpan ['span3'], array_merge($this->cellStyle->bottomRightBorder, $this->cellStyle->borderTop))->addText(' ', null, $this->paragraphStyle->noSpacing);
    }
}
