<?php

/* @var $quote Quotegen_Model_Quote */
$quote = $this->quote;

/**
 * Equipment Schedule
 */
/* @var $section PHPWord_Section */
$section = $this->section;

// Title of the document 
$section->addText($this->translate($this->header->pageHeader), array (
        'size' => '18', 
        'color' => $this->style->mainColor 
));

$deviceTableSpan = array (
        "span1" => 2827, 
        "span2" => 5654, 
        "span3" => 8481, 
        'span4' => 11306 
);

$agreementTableSpan = array (
        "span1" => 1413.5, 
        "span2" => 2827, 
        "span3" => 4240.5, 
        "span4" => 5654, 
        "span6" => 8481, 
        "span8" => 11306 
);

$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;


// Change this section to render header file
$customerTable = $section->addTable($this->tableStyle->standard);

$customerTable->addRow();
$customerTable->addCell($agreementTableSpan ['span4'], null, 4)->addText($this->translate($this->header->subHeader), $this->fontStyle->subHeader, $noSpacing);
$customerTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->bottomAlign, 4)->addText($this->translate("Agreement No.:    {$this->agreement->number}"), null, $this->paragraphStyle->noSpacingRight);

/**
 * Begin creation of customer table
 */

$customerTable = $section->addTable($this->tableStyle->standard);
$customerTable->addRow();
$customerTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText($this->header->sectionHeader[0], $this->fontStyle->invertBackground, $noSpacing);

$customerTable->addRow();
$textRun = $customerTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->bottomBorder, 8)->createTextRun($noSpacing);
$textRun->addText(" FULL LEGAL NAME: ", $labelFont);
$textRun->addText(" {$this->company->name}", $this->fontStyle->bold);

$customerTable->addRow();
$textRun = $customerTable->addCell($agreementTableSpan ['span8'], null, 8)->createTextRun($noSpacing);
$textRun->addText(" ADDRESS: ", $labelFont);
$textRun->addText(" {$this->company->address}", $this->fontStyle->bold);

/**
 * End creation of customer table
 */

/**
 * Begin creation of pricing table
 */

$section->addTextBreak();
$termDetailsTable = $section->addTable($this->tableStyle->standard);
$termDetailsTable->addRow();
$termDetailsTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText($this->header->sectionHeader[1], $this->fontStyle->invertBackground, $noSpacing);
$termDetailsTable->addRow();
$termDetailsTable->addCell($agreementTableSpan ['span1'], null, 2)->addText('TERM IN MONTHS: ' . $this->leaseDetails->termInMonths, $labelFont, $noSpacing);
$termDetailsTable->addCell($agreementTableSpan ['span1'], null, 2)->addText('SECURITY DEPOSIT ' . $this->leaseDetails->securityDeposit, $labelFont, $noSpacing);
$termDetailsTable->addCell($agreementTableSpan ['span4'], null, 4)->addText('METER FREQUENCY: MONTHLY OR SPECIFY OTHER: ___________', $labelFont, $noSpacing);

// $section->addTextBreak();
$leaseDetailsTable = $section->addTable($this->tableStyle->standard);
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->invertBackground, 4)->addText($this->header->sectionHeader[2], $this->fontStyle->invertBackground, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->invertBackground, 4)->addText($this->header->sectionHeader[3], $this->fontStyle->invertBackground, $noSpacing);
// Row #1
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText('', null, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText(' B&W', $labelFont, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign)->addText(' COLOR', $labelFont, $noSpacing);
$firstRowTextRun = $leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->leftRightBorder, 4)->createTextRun($noSpacing);
$firstRowTextRun->addText('MONTHLY FIXED CHARGE: ', $labelFont);
$firstRowTextRun->addText("{$this->leaseDetails->monthlyCharge}", $this->fontStyle->underline);
$firstRowTextRun->addText("**");

// Row #2
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->leftBorderBAlign, 2)->addText("PER PAGE CHARGE**: ", $labelFont, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText("\${$this->leaseDetails->blackPerPageCharge}", null, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign)->addText("\${$this->leaseDetails->colorPerPageCharge}", null, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomAlign, 2)->addText("", null, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText("B&W ONLY DEVICE(S)", $labelFont, $this->paragraphStyle->noSpacingCentered);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign)->addText("B&W AND COLOR DEVICE(S)", $labelFont, $this->paragraphStyle->noSpacingCentered);

// Row #3
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->leftBorder, 4)->addText("", null, $noSpacing);
// $leaseDetailsTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText('MONTLY ALLOWANCE PER DEVICE:  ', $labelFont, $this->paragraphStyle->noSpacingRight);
$leaseDetailsTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText('MONTLY ALLOWANCE PER DEVICE:  ', $labelFont, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomBorder)->addText("{$this->leaseDetails->monochromeAllowance}", null, $this->paragraphStyle->noSpacingCentered);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomRightBorder)->addText("{$this->leaseDetails->colorAllowance}", null, $this->paragraphStyle->noSpacingCentered);

// Row #4
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->leftBorder, 4)->addText("", null, $noSpacing);
// $leaseDetailsTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText("EXCESS PER PAGE CHARGE**:  ", $labelFont, $this->paragraphStyle->noSpacingRight);
$leaseDetailsTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->leftBorder, 2)->addText("EXCESS PER PAGE CHARGE**:  ", $labelFont, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomBorder)->addText("\${$this->leaseDetails->monochromeCPP}", null, $this->paragraphStyle->noSpacingCentered);
$leaseDetailsTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomRightBorder)->addText("\${$this->leaseDetails->colorCPP}", null, $this->paragraphStyle->noSpacingCentered);

// Row #5
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->leftBorder, 4)->addText("PROGRAM SET-UP FEE {$this->leaseDetails->programFee}", $labelFont, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->leftRightBorder, 4)->addText("PROGRAM SET-UP FEE {$this->leaseDetails->programFee}", $labelFont, $noSpacing);

// Row #6t
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->leftRightBorder, 4)->addText("APPLIES TO \"YOUR DEVICES\" AS DEFINED BOLOW       (**PLUS TAX)", $labelFont, $noSpacing);
$textRun = $leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->rightBorder, 4)->createTextRun($noSpacing);
$textRun->addText('INSTALLATION FEE: ', $labelFont);
$textRun->addText('$0.00 ', $this->fontStyle->bold);
$textRun->addText('DEVICES X ', $labelFont);
$textRun->addText('$0.00', $this->fontStyle->bold);
$textRun->addText('PER DEVICE = ', $labelFont);
$textRun->addText('$0.00', $this->fontStyle->bold);

// Row #7
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->leftRightBorder, 4)->addText("", null, $noSpacing);
$leaseDetailsTable->addCell($agreementTableSpan ['span4'], $this->cellStyle->rightBorder, 4)->addText("SEE MPS PROGRAM PLUS EQUIPMENT AND SCHEDULE AND DEVICE USAGE TERMS AND CONDITIONS (**PLUS TAX)", $labelFont, $noSpacing);

// Agreement terms and coditions
$leaseDetailsTable->addRow();
$leaseDetailsTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText($this->header->sectionHeader[4], $this->fontStyle->invertBackground, $noSpacing);

$leaseDetailsTable->addRow();

$cell = $leaseDetailsTable->addCell($agreementTableSpan ['span4'], null, 4);
$textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);
$textRun->addText('AGREEMENT ', $this->fontStyle->boldFinePrint);
$textRun->addText("{$this->agreement->section1}", $this->fontStyle->finePrint);

$cell->addTextBreak();
$textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);
$textRun->addText('PAGE CHARGES AND OVERAGES ', $this->fontStyle->boldFinePrint);
$textRun->addText("{$this->agreement->section2}", $this->fontStyle->finePrint);

$cell->addTextBreak();
$textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);
$textRun->addText('SERVICES AND SUPPLIES ', $this->fontStyle->boldFinePrint);
$textRun->addText("{$this->agreement->section3}", $this->fontStyle->finePrint);

$cell->addTextBreak();
$textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);
$textRun->addText('DEVICE USAGE PAYMENTS ', $this->fontStyle->boldFinePrint);
$textRun->addText("{$this->agreement->section4}", $this->fontStyle->finePrint);

$cell = $leaseDetailsTable->addCell($agreementTableSpan ['span4'], null, 4);
$textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);
$textRun->addText('REMOTE MONITORING ', $this->fontStyle->boldFinePrint);
$textRun->addText("{$this->agreement->section5}", $this->fontStyle->finePrint);

$cell->addTextBreak();
$textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);
$textRun->addText('TAXES ', $this->fontStyle->boldFinePrint);
$textRun->addText("{$this->agreement->section6}", $this->fontStyle->finePrint);

$cell->addTextBreak();
$textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);
$textRun->addText('DEFAULT AND REMEDIES ', $this->fontStyle->boldFinePrint);
$textRun->addText("{$this->agreement->section7}", $this->fontStyle->finePrint);

$cell->addTextBreak();
$textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);
$textRun->addText('LAW/FORUM ', $this->fontStyle->boldFinePrint);
$textRun->addText("{$this->agreement->section8}", $this->fontStyle->finePrint);

$cell->addTextBreak();
$textRun = $cell->createTextRun($this->paragraphStyle->noSpacingJustified);
$textRun->addText('MISCELLANEOUS ', $this->fontStyle->boldFinePrint);
$textRun->addText("{$this->agreement->section9}", $this->fontStyle->finePrint);

$footerTable = $section->addTable($this->tableStyle->standard);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText($this->header->sectionHeader[5], $this->fontStyle->invertBackground, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span8'], null, 8)->addText($this->agreement->signature , $this->fontStyle->finePrint, $noSpacing);
$footerTable->addRow(350);
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorderBAlign)->addText('(As Stated Above)', null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span3'], $this->cellStyle->borderBAlign, 3)->addText('X', null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span3'], $this->cellStyle->bottomBorderBAlign, 3)->addText('', null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText('', null, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span1'], null)->addText('CUSTOMER', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span3'], null, 3)->addText('SIGNATURE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span3'], null, 3)->addText('PRINT NAME & TITLE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span1'], null)->addText('DATE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);

$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText($this->header->sectionHeader[6], $this->fontStyle->invertBackground, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorder, 2)->addText("{$this->leaseDetails->companyName}", null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorder, 2)->addText('', null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorder, 2)->addText("{$this->leaseDetails->companyOwner}", null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorder, 2)->addText('', null, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span1'], null)->addText('OWNER', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span3'], null, 3)->addText('SIGNATURE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span3'], null, 3)->addText('PRINT NAME & TITLE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span1'], null)->addText('DATE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->bottomBorder, 8)->addText("{$this->leaseDetails->companyAddress}", $this->fontStyle->label, $noSpacing);

// New page for devices
$section->addPageBreak();
// Title of the document
$section->addText($this->translate($this->header->pageHeader), array (
        'size' => '18', 
        'color' => $this->style->mainColor 
));
/*
 * Devices table
 */
$deviceTable = $section->addTable($this->tableStyle->standard);

/*
 * Title Row
 */
$deviceTable->addRow();
$deviceTable->addCell($deviceTableSpan ['span2'], null, 2)->addText($this->translate($this->header->subHeader), $this->fontStyle->subHeader, $noSpacing);
$deviceTable->addCell($deviceTableSpan ['span2'], $this->cellStyle->bottomAlign, 2)->addText($this->translate("Agreement No.:    {$this->agreement->number}"), null, $this->paragraphStyle->noSpacingRight);

$deviceTable->addRow();
$deviceTable->addCell($deviceTableSpan ['span4'], $this->cellStyle->invertBackground, 4)->addText($this->header->sectionHeader[7], $this->fontStyle->invertBackground, $this->paragraphStyle->noSpacing);

/*
 * Heading Row
 */
$deviceTable->addRow(600);
$deviceTable->addCell($deviceTableSpan ['span2'], $this->cellStyle->bottomLeftBorderBAlign, 2)->addText($this->translate('MAKE, MODEL NUMBER & INCLUDED ACCESSORIES'), $this->fontStyle->label, $this->paragraphStyle->noSpacing);
$deviceTable->addCell($deviceTableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign, 1)->addText($this->translate('SERIAL NO.'), $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$deviceTable->addCell($deviceTableSpan ['span1'], $this->cellStyle->bottomRightBorderBAlign, 1)->addText($this->translate('ADDRESS'), $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);

$deviceName = 'Xerox Phaser 8660';

/*
 * Device Rows
 */
/* @var $quoteDevice Quotegen_Model_QuoteDevice */
foreach ( $quote->getQuoteDevices() as $quoteDevice )
{
    for($i = 0; $i < $quoteDevice->calculateTotalQuantity(); $i ++)
    {
        $deviceTable->addRow(600);
        $deviceTable->addCell($deviceTableSpan ['span2'], $this->cellStyle->bottomLeftBorder, 2)->addText($quoteDevice->getName(), null, $this->paragraphStyle->noSpacing);
        $deviceTable->addCell($deviceTableSpan ['span1'], $this->cellStyle->bottomRightBorder, 1)->addText(' ', null, $this->paragraphStyle->noSpacing);
        $deviceTable->addCell($deviceTableSpan ['span1'], $this->cellStyle->bottomRightBorder, 1)->addText(' ', null, $this->paragraphStyle->noSpacing);
    }
}
$section->addTextBreak();
$footerTable = $section->addTable('termDetailStyle');
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText("CUSTOMER'S AUTHORIZED SIGNATURE", $this->fontStyle->invertBackground, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span8'], null, 8)->addText($this->agreement->signature, $this->fontStyle->finePrint, $noSpacing);
$footerTable->addRow(350);
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorderBAlign)->addText('(As Stated Above)', null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span3'], $this->cellStyle->borderBAlign, 3)->addText('X', null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span3'], $this->cellStyle->bottomBorderBAlign, 3)->addText('', null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span1'], $this->cellStyle->bottomBorderBAlign)->addText('', null, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span1'], null)->addText('CUSTOMER', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span3'], null, 3)->addText('SIGNATURE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span3'], null, 3)->addText('PRINT NAME & TITLE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span1'], null)->addText('DATE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);

$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->invertBackground, 8)->addText("OWNER (\"we\", \"us\", \"our\")", $this->fontStyle->invertBackground, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorder, 2)->addText("{$this->dealerCompany->companyName}", null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorder, 2)->addText('', null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorder, 2)->addText("{$this->dealerCompany->companyOwner}", null, $noSpacing);
$footerTable->addCell($agreementTableSpan ['span2'], $this->cellStyle->bottomBorder, 2)->addText('', null, $noSpacing);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span1'], null)->addText('OWNER', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span3'], null, 3)->addText('SIGNATURE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span3'], null, 3)->addText('PRINT NAME & TITLE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addCell($agreementTableSpan ['span1'], null)->addText('DATE', $this->fontStyle->label, $this->paragraphStyle->noSpacingCentered);
$footerTable->addRow();
$footerTable->addCell($agreementTableSpan ['span8'], $this->cellStyle->bottomBorder, 8)->addText("{$this->dealerCompany->companyAddress}", $this->fontStyle->label, $noSpacing);


