<?php
//**************************************/
//**************CELL STYLE**************/
//**************************************/
$this->cellStyle                   = new stdClass();
$this->cellStyle->invertBackground = [
    'bgColor'        => '111111',
    'borderLeftSize' => 1
];
$this->cellStyle->topBorder        = [
    'borderTopSize' => 1,
];
$this->cellStyle->rightBorder      = [
    'borderRightSize' => 1
];
$this->cellStyle->bottomAlign      = [
    'valign' => 'bottom'
];
$this->cellStyle->topAlign         = [
    'valign'          => 'top',
    'borderRightSize' => 1,
];
$this->cellStyle->span8            = [
    'gridSpan' => 8
];
$this->cellStyle->span7            = [
    'gridSpan' => 7
];
$this->cellStyle->span6            = [
    'gridSpan' => 6
];
$this->cellStyle->span5            = [
    'gridSpan' => 5
];
$this->cellStyle->span4            = [
    'gridSpan' => 4
];
$this->cellStyle->span3            = [
    'gridSpan' => 3
];
$this->cellStyle->span2            = [
    'gridSpan' => 2
];
$this->cellStyle->span1            = [
    'gridSpan' => 1
];
$this->cellStyle->center           = [
    'valign' => 'center',
];


//**************************************/
//**************FONT STYLE**************/
//**************************************/
$this->fontStyle                   = new stdClass();
$this->fontStyle->invertBackground = [
    'color' => 'FFFFFF',
    'bold'  => true,
    'size'  => '10'
];
$this->fontStyle->label            = [
    "size" => '7',
];
$this->fontStyle->boldFinePrint    = [
    'bold' => true,
    'size' => '8'
];
$this->fontStyle->finePrint        = [
    'size' => '8'
];
$this->fontStyle->center           = [
    'align' => 'center'
];
$this->fontStyle->bold             = [
    'bold' => true
];
$this->fontStyle->underline        = [
    'underline' => \PhpOffice\PhpWord\Style\Font::UNDERLINE_SINGLE
];

//**************************************/
//*********PARAGRAPH STYLE**************/
//**************************************/
$this->paragraphStyle                    = new stdClass();
$this->paragraphStyle->noSpacing         = [
    'spaceAfter' => 0
];
$this->paragraphStyle->noSpacingCentered = [
    'spaceAfter' => 0,
    'align'      => 'center'
];
$this->paragraphStyle->noSpacingRight    = [
    'spaceAfter' => 0,
    'align'      => 'right'
];

$this->paragraphStyle->noSpacingLeft = [
    'spaceAfter' => 0,
    'align'      => 'left'
];

$this->paragraphStyle->noSpacingJustified = [
    'spaceAfter' => 0,
    'align'      => 'both'
];

$this->paragraphStyle->justified = [
    'align' => 'both'
];

//**************************************/
//*************TABLE STYLE**************/
//**************************************/
$this->tableStyle = new stdClass();

$this->tableStyle->standard = [
    'cellMarginTop'    => 35,
    'cellMarginBottom' => 35,
    'cellMarginRight'  => 35,
    'cellMarginLeft'   => 100,
];
$this->tableStyle->gridSpan = [
    "span1" => 1413.5,
    "span2" => 2827,
    "span3" => 4240.5,
    "span4" => 5654,
    "span5" => 7067.5,
    "span6" => 8481,
    "span8" => 11308
];



