<?php
//**************************************/
//**************CELL STYLE**************/
//**************************************/
$this->cellStyle                   = new stdClass();
$this->cellStyle->invertBackground = array(
    'bgColor'        => '111111',
    'borderLeftSize' => 1
);
$this->cellStyle->topBorder        = array(
    'borderTopSize' => 1,
);
$this->cellStyle->rightBorder      = array(
    'borderRightSize' => 1
);
$this->cellStyle->bottomAlign      = array(
    'valign' => 'bottom'
);
$this->cellStyle->topAlign         = array(
    'valign'          => 'top',
    'borderRightSize' => 1,
);
$this->cellStyle->span8            = array(
    'gridSpan' => 8
);
$this->cellStyle->span7            = array(
    'gridSpan' => 7
);
$this->cellStyle->span6            = array(
    'gridSpan' => 6
);
$this->cellStyle->span5            = array(
    'gridSpan' => 5
);
$this->cellStyle->span4            = array(
    'gridSpan' => 4
);
$this->cellStyle->span3            = array(
    'gridSpan' => 3
);
$this->cellStyle->span2            = array(
    'gridSpan' => 2
);
$this->cellStyle->span1            = array(
    'gridSpan' => 1
);
$this->cellStyle->center           = array(
    'valign' => 'center',
);


//**************************************/
//**************FONT STYLE**************/
//**************************************/
$this->fontStyle                   = new stdClass();
$this->fontStyle->invertBackground = array(
    'color' => 'FFFFFF',
    'bold'  => true,
    'size'  => '10'
);
$this->fontStyle->label            = array(
    "size" => '7',
);
$this->fontStyle->boldFinePrint    = array(
    'bold' => true,
    'size' => '8'
);
$this->fontStyle->finePrint        = array(
    'size' => '8'
);
$this->fontStyle->center           = array(
    'align' => 'center'
);
$this->fontStyle->bold             = array(
    'bold' => true
);
$this->fontStyle->underline        = array(
    'underline' => \PhpOffice\PhpWord\Style\Font::UNDERLINE_SINGLE
);

//**************************************/
//*********PARAGRAPH STYLE**************/
//**************************************/
$this->paragraphStyle                    = new stdClass();
$this->paragraphStyle->noSpacing         = array(
    'spaceAfter' => 0
);
$this->paragraphStyle->noSpacingCentered = array(
    'spaceAfter' => 0,
    'align'      => 'center'
);
$this->paragraphStyle->noSpacingRight    = array(
    'spaceAfter' => 0,
    'align'      => 'right'
);

$this->paragraphStyle->noSpacingLeft = array(
    'spaceAfter' => 0,
    'align'      => 'left'
);

$this->paragraphStyle->noSpacingJustified = array(
    'spaceAfter' => 0,
    'align'      => 'both'
);

$this->paragraphStyle->justified = array(
    'align' => 'both'
);

//**************************************/
//*************TABLE STYLE**************/
//**************************************/
$this->tableStyle = new stdClass();

$this->tableStyle->standard = array(
    'cellMarginTop'    => 35,
    'cellMarginBottom' => 35,
    'cellMarginRight'  => 35,
    'cellMarginLeft'   => 100,
);
$this->tableStyle->gridSpan = array(
    "span1" => 1413.5,
    "span2" => 2827,
    "span3" => 4240.5,
    "span4" => 5654,
    "span5" => 7067.5,
    "span6" => 8481,
    "span8" => 11308
);



