<?php 

/* @var $quote Quotegen_Model_Quote */
$quote = $this->quote;

/* @var $section PHPWord_Section */
$section = $this->section;

$tableSpan = array (
        "span1" => 1413.5,
        "span2" => 2827,
        "span3" => 4240.5,
        "span4" => 5654,
        "span6" => 8481,
        "span8" => 11306
);

$noSpacing = $this->paragraphStyle->noSpacing;
$labelFont = $this->fontStyle->label;

// Title of the document
$section->addText($this->translate($this->header->pageHeader), array (
        'size' => '18',
        'color' => $this->style->mainColor
));

// Change this section to render header file
$headerTable = $section->addTable($this->tableStyle->standard);

$headerTable->addRow();
$headerTable->addCell($tableSpan ['span4'], null, 4)->addText($this->translate($this->header->subHeader), $this->fontStyle->subHeader, $noSpacing);
$headerTable->addCell($tableSpan ['span4'], $this->cellStyle->bottomAlign, 4)->addText($this->translate("Agreement No.:    {$this->agreement->number}"), null, $this->paragraphStyle->noSpacingRight);