<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$brandName = My_Brand::$brandName;
$companyName = My_Brand::$companyName;
$dealerId = Zend_Auth::getInstance()->getIdentity()->dealerId;
$this->headLink()->appendStylesheet($this->baseUrl("css/reports/reports.css")); ?>
<div class="container full-width gross-margin" id="htmlReportContainer">
<div>
    <h2 class="reportTitle">Gross Margin Report</h2><br />
    <em>AMPV = Average Monthly Page Volume</em>
</div>

<br />

<table id="grossMarginInformation">
    <tbody>
    <tr>
        <td class="column1">
            <div class="heading"><?php echo $brandName ?> Black And White CPP:</div>
        </td>
        <td class="column2">
            <div><?php echo $this->formatCostPerPage($assessmentViewModel->getMPSBlackAndWhiteCPP()); ?></div>
        </td>
        <td class="column3">
            <div class="heading">Total Cost:</div>
        </td>
        <td class="column4">
            <div><?php echo $this->currency($assessmentViewModel->getGrossMarginTotalMonthlyCost()->Combined); ?></div>
        </td>
    </tr>
    <tr>
        <td class="column1">
            <div class="heading"><?php echo $brandName ?> Color CPP:</div>
        </td>
        <td class="column2">
            <div><?php echo $this->formatCostPerPage($assessmentViewModel->getMPSColorCPP()); ?></div>
        </td>
        <td class="column3">
            <div class="heading">Total Revenue:</div>
        </td>
        <td class="column4">
            <div><?php echo $this->currency($assessmentViewModel->getGrossMarginTotalMonthlyRevenue()->Combined); ?></div>
        </td>
    </tr>
    <tr>
        <td class="column1">
            <div class="heading">Weighted Black And White CPP:</div>
        </td>
        <td class="column2">
            <div><?php echo $this->formatCostPerPage($assessmentViewModel->getGrossMarginWeightedCPP()->BlackAndWhite); ?></div>
        </td>
        <td class="column3">
            <div class="heading">Monthly Profit:</div>
        </td>
        <td class="column4">
            <div><?php echo $this->currency($assessmentViewModel->getGrossMarginMonthlyProfit()); ?></div>
        </td>
    </tr>
    <tr>
        <td class="column1">
            <div class="heading">Weighted Color CPP:</div>
        </td>
        <td class="column2">
            <div><?php echo $this->formatCostPerPage($assessmentViewModel->getGrossMarginWeightedCPP()->Color); ?></div>
        </td>
        <td class="column3">
            <div class="heading">Overall Margin:</div>
        </td>
        <td class="column4">
            <div><?php echo number_format($assessmentViewModel->getGrossMarginOverallMargin()); ?>%</div>
        </td>
    </tr>
    <tr>
        <td class="column1">
            <div class="heading">Black And White Margin:</div>
        </td>
        <td class="column2">
            <div><?php echo number_format($assessmentViewModel->getGrossMarginBlackAndWhiteMargin()); ?>%</div>
        </td>
        <td class="column3">
            <div class="heading">Color Margin:</div>
        </td>
        <td class="column4"><?php echo number_format($assessmentViewModel->getGrossMarginColorMargin()); ?>%</td>
    </tr>
    </tbody>
</table>

<br />

<div class="center">
    <em class="center">Yellow highlighted rows indicate devices that have not been assigned toners matching your selected first toner vendor preference.<br />
        For these devices the system has selected the best available alternative based on your preference.</em>
    <br /><br />
</div>

<table id="grossMarginDeviceSummary">
    <thead>
    <tr class="center">
        <th class="column1" rowspan="2">Device Name<br />(IP Address - Serial Number)</th>
        <th colspan="5">Black And White</th>
        <th colspan="5">Color</th>
        <th colspan="2">Toner SKUs</th>
    </tr>
    <tr class="center">
        <th class="column2">AMPV</th>
        <th class="column3">Toner Cost</th>
        <th class="column4">Toner Yield</th>
        <th class="column5">CPP</th>
        <th class="column6">Total Printing Cost</th>
        <th class="column7">AMPV</th>
        <th class="column8">Toner Cost</th>
        <th class="column9">Toner Yield</th>
        <th class="column10">CPP</th>
        <th class="column11">Total Printing Cost</th>
        <th class="column12"><?php echo My_Brand::$dealerSku; ?>s</th>
        <th class="column13">OEM SKUs</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances() as $deviceInstance) : ?>
        <?php
        $tonerConfig               = $deviceInstance->getMasterDevice()->tonerConfigId;
        $dealerCostPerPageSettings = $assessmentViewModel->getCostPerPageSettingForDealer();
        $completeMonoToners        = $deviceInstance->getMasterDevice()->getHasValidMonoGrossMarginToners($assessmentViewModel->getCostPerPageSettingForDealer());
        $completeColorToners       = $deviceInstance->getMasterDevice()->getHasValidColorGrossMarginToners($assessmentViewModel->getCostPerPageSettingForDealer());
        $blackToner                = null;
        $colorToner                = null;
        $toners                    = $deviceInstance->getMasterDevice()->getCheapestTonerSetByVendor($assessmentViewModel->getCostPerPageSettingForDealer());
        $tonerSkus                 = array();
        foreach ($toners as $toner)
        {
            $dealerTonerAttribute = Proposalgen_Model_Mapper_Dealer_Toner_Attribute::getInstance()->findTonerAttributeByTonerId($toner->id, $dealerId);
            $dealerSku            = null;

            if ($dealerTonerAttribute instanceof Proposalgen_Model_Dealer_Toner_Attribute)
            {
                $dealerSku = $dealerTonerAttribute->dealerSku;
            }

            switch ($toner->tonerColorId)
            {
                case Proposalgen_Model_TonerColor::BLACK:
                    $blackToner                      = $toner;
                    $tonerSkus['black']['sku']       = $toner->sku;
                    $tonerSkus['black']['dealerSku'] = $dealerSku;
                    break;
                case Proposalgen_Model_TonerColor::CYAN:
                    $colorToner                     = $toner;
                    $tonerSkus['cyan']['sku']       = $toner->sku;
                    $tonerSkus['cyan']['dealerSku'] = $dealerSku;
                    break;
                case Proposalgen_Model_TonerColor::MAGENTA:
                    $tonerSkus['magenta']['sku']       = $toner->sku;
                    $tonerSkus['magenta']['dealerSku'] = $dealerSku;
                    $colorToner                        = $toner;
                    break;
                case Proposalgen_Model_TonerColor::YELLOW:
                    $tonerSkus['yellow']['sku']       = $toner->sku;
                    $tonerSkus['yellow']['dealerSku'] = $dealerSku;
                    $colorToner                       = $toner;
                    break;
                case Proposalgen_Model_TonerColor::THREE_COLOR:
                    $tonerSkus['threeColor']['sku']       = $toner->sku;
                    $tonerSkus['threeColor']['dealerSku'] = $dealerSku;
                    $colorToner                           = $toner;
                    break;
                case Proposalgen_Model_TonerColor::FOUR_COLOR:
                    $tonerSkus['fourColor']['sku']       = $toner->sku;
                    $tonerSkus['fourColor']['dealerSku'] = $dealerSku;
                    $blackToner                          = $toner;
                    $colorToner                          = $toner;
                    break;
                default:
                    break;
            }
        }

        // Black Toner
        $blackCost  = $this->currency($blackToner->calculatedCost);
        $blackYield = number_format($blackToner->yield);

        // Color Toner
        $colorCost  = "-";
        $colorStyle = "right";
        $colorYield = "-";
        $isColor    = false;
        if ($colorToner instanceof Proposalgen_Model_Toner)
        {
            $colorCost  = $this->currency($colorToner->cost);
            $colorYield = number_format($colorToner->yield);
            $isColor    = true;
        }
        ?>
        <tr class="<?php echo ($completeMonoToners) ? "" : "nonCompliantMono" ?> <?php echo ($completeColorToners) ? "" : "nonCompliantColor" ?>">
            <!-- Monochrome -->
            <td class="column1">
                <div><?php echo str_ireplace("hewlett-packard", "HP", $deviceInstance->getDeviceName()) . "<br />(" . $deviceInstance->ipAddress . " - " . $deviceInstance->serialNumber . ")"; ?></div>
            </td>
            <td class="column2 mono">
                <div class="right"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></div>
            </td>

            <td class="column3 mono">
                <div class="right"><?php echo $blackCost ?></div>
            </td>
            <td class="column4 mono">
                <div class="right"><?php echo $blackYield ?></div>
            </td>
            <td class="column5 mono">
                <div class="right"><?php echo $this->formatCostPerPage($deviceInstance->calculateCostPerPage($assessmentViewModel->getCostPerPageSettingForDealer())->getCostPerPage()->monochromeCostPerPage); ?></div>
            </td>
            <td class="column6 mono">
                <div class="right">
                    <?php echo $this->currency($deviceInstance->getMonthlyBlackAndWhiteCost($assessmentViewModel->getCostPerPageSettingForDealer())); ?></div>
            </td>

            <!-- Color -->
            <td class="column7 color">
                <div class="<?php echo $colorStyle; ?>"><?php echo ($isColor) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : "-"; ?></div>
            </td>
            <td class="column8 color">
                <div class="<?php echo $colorStyle; ?>"><?php echo $colorCost ?></div>
            </td>
            <td class="column9 color">
                <div class="<?php echo $colorStyle; ?>"><?php echo $colorYield ?></div>
            </td>
            <td class="column10 color">
                <div class="<?php echo $colorStyle; ?>"><?php echo ($isColor) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($assessmentViewModel->getCostPerPageSettingForDealer())->getCostPerPage()->colorCostPerPage) : "-"; ?></div>
            </td>

            <td class="column11 color">
                <div class="<?php echo $colorStyle; ?>"><?php echo ($isColor) ? $this->currency($deviceInstance->calculateMonthlyColorCost($assessmentViewModel->getCostPerPageSettingForDealer())) : "-"; ?></div>
            </td>
            <td class="column12">
                <div class="<?php echo $colorStyle; ?>">
                    <?php
                    foreach ($tonerSkus as $tonerSku)
                    {
                        if (isset($tonerSku['dealerSku']))
                        {
                            echo $tonerSku['dealerSku'] . '<br />';
                        }
                        else
                        {
                            echo "-" . "<br />";
                        }
                    }
                    ?>
                </div>
            </td>
            <td class="column12">
                <div class="<?php echo $colorStyle; ?>">
                    <?php
                    foreach ($tonerSkus as $tonerSku)
                    {
                        echo $tonerSku['sku'] . '<br />';
                    }
                    ?>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    <tr class="totals">
        <td class="column1">
            <div>Totals for <?php echo number_format($assessmentViewModel->getDevices()->purchasedDeviceInstances->getCount()); ?> devices:</div>
        </td>
        <td>
            <div class="right"><?php echo $this->formatPageVolume($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getBlackPageCount()->getMonthly()); ?></div>
        </td>
        <td colspan="3"></td>
        <td class="column2">
            <div class="right"><?php echo $this->currency($assessmentViewModel->getGrossMarginTotalMonthlyCost()->BlackAndWhite); ?></div>
        </td>
        <td>
            <div class="center"><?php echo $this->formatPageVolume($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly()); ?></div>
        </td>
        <td colspan="3"></td>
        <td>
            <div class="right"><?php echo $this->currency($assessmentViewModel->getGrossMarginTotalMonthlyCost()->Color); ?></div>
        </td>
        <td colspan="2"></td>
    </tr>
    </tbody>
</table>
</div>