<?php
/* @var $proposal Assessment_ViewModel_Assessment */
$proposal = $this->proposal;
?>
<div class="titlepage">
    <div class="header">
        <div class="title-page-logo-box-wrapper">
            <div class="title-page-logo-box">
                <img class="title-page-logo" src="<?php echo $this->serverUrl($this->dealerLogoFile) ?>" />
            </div>
        </div>
    </div>
    <div class="title-page-report-title">
        <h2>Solution</h2>
    </div>
    <div class="title-page-customer-details">
        <h3>Prepared for:
            <?php
            if (strlen($proposal->assessment->getClient()->companyName) > 26)
            {
                echo "<br/>";
            }

            echo $proposal->assessment->getClient()->companyName;
            ?>
        </h3>

        <h3><?php echo $proposal->getDateReportPrepared(); ?></h3>

        <p><?php echo nl2br($proposal->assessment->getClient()->getAddress()); ?></p>
    </div>
</div>