<?php
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/report_devicedetails.css"), "screen");
$noIcon = "<img src='" . $this->theme("statusicons/error_32_32x32.png") . "' alt='No' />";
$yesIcon = "<img src='" . $this->theme("statusicons/checkmark_32_32x32.png") . "' alt='Yes' />";
$maybeIcon = "<img src='" . $this->theme("statusicons/help_32_32x32.png") . "' alt='Unknown' />";

$tagFields = array (
	"Copier" => ($this->device->MasterDevice->IsCopier) ? $yesIcon : $noIcon,
	"Duplex" => ($this->device->MasterDevice->IsDuplex) ? $yesIcon : $noIcon,
	"Fax" => ($this->device->MasterDevice->IsFax) ? $yesIcon : $noIcon,
    "Deleted" => ($this->device->MasterDevice->IsDeleted) ? $yesIcon : $noIcon,
    "Excluded" => ($this->device->IsExcluded) ? $yesIcon : $noIcon,
    "Replacement" => ($this->device->MasterDevice->IsReplacementDevice) ? $yesIcon : $noIcon,
    "JIT Support" => ($this->device->JITSuppliesSupported) ? $yesIcon : $noIcon,
    "Leased" => ($this->device->MasterDevice->IsLeased) ? $yesIcon : $noIcon,
    "Master" => ($this->device->IsUnknown) ? $noIcon : $yesIcon,
);

$deviceinstanceFields = array(
	"ID" => $this->device->DeviceInstanceId,
    "Serial" => $this->device->SerialNumber,
	"IP Address" => $this->device->IPAddress,
	"MPS Start" => $this->device->MPSMonitorStartDate,
	"MPS End" => $this->device->MPSMonitorEndDate,
    "MPS Discovery" => $this->device->MPSDiscoveryDate,
	"MPS Interval" => $this->device->MPSMonitorInterval->days . " days",
	"Age" => $this->device->Age . " Years(s)",
	"Daily Power" => $this->device->AverageDailyPowerConsumption . " kWh",
    "Daily Power Cost" => "$" . number_format($this->device->AverageDailyPowerCost, 2),
	"Monthly Power" => $this->device->AverageMonthlyPowerConsumption . " kWh",
	"Monthly Power Cost" => "$" . number_format($this->device->AverageMonthlyPowerCost, 2),
    "Monthly Usage" => number_format($this->device->Usage * 100, 2) . "%",
	"Life Usage" => number_format($this->device->LifeUsage, 2) . "%",
	"Max AMPV" => number_format($this->device->MasterDevice->MaximumMonthlyPageVolume) . " pages",
	"Monthly Rate" => "$" . number_format($this->device->MonthlyRate, 2),
    "Monthly Cost" => "$" . number_format($this->device->MonthlyCost, 2),
    "Monthly Revenue" => "$" . number_format($this->device->MonthlyRevenue, 2),
    "Monthly Profit" => "$" . number_format($this->device->MonthlyProfit, 2),
    "Yearly Profit" => "$" . number_format($this->device->AnnualProfit, 2),
	"Age Rank" => number_format($this->device->AgeRank, 2),
    "Life Usage Rank" => number_format($this->device->LifeUsageRank, 2),
    "Risk Rank" => number_format($this->device->RiskRank, 2),
    "Recommended Action" => $this->device->Action,

);

$printingFields = array(
    "Black And White" => array(
        "DailyVolume" => number_format($this->device->AverageDailyBlackAndWhitePageCount) . " pages",
        "MonthlyVolume" => number_format($this->device->AverageMonthlyBlackAndWhitePageCount) . " pages",
        "YearlyVolume" => number_format($this->device->AverageYearlyBlackAndWhitePageCount) . " pages",
        "LifeVolume" => number_format($this->device->LifeBlackAndWhitePageCount) . " pages",
        "CostOfInkAndToner" => "$" . number_format($this->device->CostOfBlackAndWhiteInkAndToner, 2),

    ),
    "Color" => array(
        "DailyVolume" => number_format($this->device->AverageDailyColorPageCount) . " pages",
        "MonthlyVolume" => number_format($this->device->AverageMonthlyColorPageCount) . " pages",
        "YearlyVolume" => number_format($this->device->AverageYearlyColorPageCount) . " pages",
        "LifeVolume" => number_format($this->device->LifeColorPageCount) . " pages",
		"CostOfInkAndToner" => "$" . number_format($this->device->CostOfColorInkAndToner, 2),
        
    ),
    "Combined" => array(
        "DailyVolume" => number_format($this->device->AverageDailyPageCount) . " pages",
        "MonthlyVolume" => number_format($this->device->AverageMonthlyPageCount) . " pages",
        "YearlyVolume" => number_format($this->device->AverageYearlyPageCount) . " pages",
        "LifeVolume" => number_format($this->device->LifePageCount) . " pages",
        "CostOfInkAndToner" => "$" . number_format($this->device->CostOfInkAndToner, 2),
    ),
);

$masterDeviceFields = array(
    "CPP Admin" => "$" . number_format($this->device->MasterDevice->AdminCostPerPage, 4),
	"CPP parts" => "$" . number_format($this->device->MasterDevice->getAttributes()->partsCostPerPage, 4),
	"CPP labor" => "$" . number_format($this->device->MasterDevice->getAttributes()->laborCostPerPage, 4),
	"Date Created" => $this->device->MasterDevice->DateCreated,
	"Device Price" => "$" . number_format($this->device->MasterDevice->DevicePrice, 2),
	"Duty Cycle" => ($this->device->MasterDevice->DutyCycle) ? $this->device->MasterDevice->DutyCycle : "N/A",
    "Launch Date" => $this->device->MasterDevice->LaunchDate,
    "PPM Black" => ($this->device->MasterDevice->PPMBlack) ? $this->device->MasterDevice->PPMBlack : "N/A",
	"PPM Color" => ($this->device->MasterDevice->PPMColor) ? $this->device->MasterDevice->PPMColor : "N/A",
    "Toner Config" => Proposalgen_Model_TonerConfig::$TonerConfigNames[$this->device->MasterDevice->TonerConfigId],
	"Incomplete Black Toner Data" => ($this->device->MasterDevice->isUsingIncompleteBlackTonerData()) ? "Yes" : "No",
	"Incomplete Color Toner Data" => ($this->device->MasterDevice->isUsingIncompleteColorTonerData()) ? "Yes" : "No",
	"Watts Normal" => ($this->device->MasterDevice->WattsPowerNormal) ? $this->device->MasterDevice->WattsPowerNormal . " watts" : "N/A",
	"Watts Idle" => ($this->device->MasterDevice->WattsPowerIdle) ? $this->device->MasterDevice->WattsPowerIdle . " watts" : "N/A",
);
?>
<div class="span-24 center"><h2>Device Details for: <?php echo $this->device->DeviceName; ?></h2></div>
<hr/>
<div class="span-24">
    <!-- ---------------------------------------------------------------------------------------------- -->
    <div class="span-8 border">
		<h3>Device Instance Info</h3>
        <table>
        	<thead>
        		<tr>
        			<th>Field Name</th>
        			<th>Value</th>
        		</tr>
        	</thead>
        	<tbody>
        	<?php foreach($deviceinstanceFields as $name => $value) :?>
        		<tr>
        			<td><strong><?php echo $name; ?></strong></td>
        			<td><?php echo $value; ?></td>
        	<?php endforeach; ?>
        	</tbody>
        </table>
    </div>
    <div class="span-8 border">
		<h3>Device Info</h3>
        <table>
        	<thead>
        		<tr>
        			<th>Field Name</th>
        			<th>Value</th>
        		</tr>
        	</thead>
        	<tbody>
        	<?php foreach($masterDeviceFields as $name => $value) :?>
        		<tr>
        			<td><strong><?php echo $name; ?></strong></td>
        			<td><?php echo $value; ?></td>
        	<?php endforeach; ?>
        	</tbody>
        </table>
    </div>
<div class="span-8 last">
<h3>Tags?</h3>
<?php
    $tagCount = 0;
    $last = "";
?>
    <?php foreach($tagFields as $field => $value) :?>
    	<?php
    	$tagCount++;
    	if ($tagCount >= 2)
    	{
    		$last = "last";
    		$tagCount = 0;
    	}
    	else
    		$last = "";
    	?>
    	<div class="span-4 <?php echo $last; ?>">
    		<table>
    			<thead>
    				<tr>
    					<th class="center"><strong><?php echo $field; ?></strong></th>
    				</tr>
    			</thead>
    			<tbody>
    				<tr>
    					
    					<td class="center"><?php echo $value; ?></td>
    				</tr>
    			</tbody>
    		</table>
    	</div>
    <?php endforeach; ?>
</div>
    <!-- ---------------------------------------------------------------------------------------------- -->
</div>
<hr/>
<div class="span-24">
    <table>
    <caption><strong>Printing Statistics</strong></caption>
    	<thead>
    		<tr>
    			<th>Type</th>
    			<th>Daily Volume</th>
    			<th>Monthly Volume</th>
    			<th>Yearly Volume</th>
    			<th>Life Volume</th>
    			<th>Cost Of Ink And Toner</th>
    		</tr>
    	</thead>
    	<tbody>
    	<?php foreach($printingFields as $category => $column) : ?>
    		<tr>
    			<td><?php echo $category; ?></td>
    			<td><?php echo $column["DailyVolume"]; ?></td>
    			<td><?php echo $column["MonthlyVolume"]; ?></td>
    			<td><?php echo $column["YearlyVolume"]; ?></td>
    			<td><?php echo $column["LifeVolume"]; ?></td>
    			<td><?php echo $column["CostOfInkAndToner"]; ?> / month</td>
			</tr>
		<?php endforeach; ?>
    	</tbody>
    </table>
</div>
<hr/>
<!-- ---------------------------------------------------------------------------------------------- -->
<div class="push-6 pull-6 span-12">
	<div class="span-12 last">
    	<h3>Device Meters</h3>
        <table>
        	<thead>
        		<tr>
        			<th>Meter Type</th>
        			<th>Start Meter</th>
        			<th>End Meter</th>
        		</tr>
        	</thead>
        	<tbody>
        	<?php foreach($this->device->Meters as $meterType => $meter) :?>
        		<tr>
        			<td><strong><?php echo $meterType; ?><?php if ($meter->GeneratedBySystem) { echo "**"; }?></strong></td>
        			<td><?php echo number_format($meter->StartMeter); ?></td>
        			<td><?php echo number_format($meter->EndMeter); ?></td>
        	<?php endforeach; ?>
        	</tbody>
        </table>
        <em>** Meter was automatically calculated.</em>
    </div>
</div>
<hr/>
    <!-- ---------------------------------------------------------------------------------------------- -->
<div class="push-6 pull-6 span-12">
    <div class="span-12">
    	<?php $last = "span-5 "; ?>
    	<?php foreach($this->device->MasterDevice->CostPerPage as $category1 => $subcategories) : ?>
    	<div class="<?php echo $last; ?>">
    	<h3><?php echo "Device $category1 CPP"; ?></h3>
    	<?php foreach($subcategories as $category2 => $colors) : ?>
    	<table>
    		<caption class="loud"><strong><?php echo "$category2 CPP"; ?></strong></caption>
    		<thead>
    			<tr>
    				<th>Cost</th>
    				<th>Value</th>
    			</tr>
    		</thead>
    		<tbody>
            	<?php foreach($colors as $color => $cpp) : ?>
            	<tr>
        			<td><?php echo $color; ?></td>
        			<td><?php echo ($cpp > 0) ? "$" . number_format($cpp, 4) : "-"; ?></td>
    			</tr>
            	<?php endforeach; ?>
            </tbody>
    	</table>
    	<?php endforeach; ?>
    	</div>
    	<?php $last = "span-5 last push-2"; ?>
    	<?php endforeach; ?>
	</div>
</div>
<hr>
<!-- ---------------------------------------------------------------------------------------------- -->
<div class="push-6 pull-6 span-12">
    <div class="span-12">
    	<table>
    		<caption class="loud"><strong>Other CPP Data</strong></caption>
    		<thead>
    			<tr>
    				<th>Setting</th>
    				<th>Value</th>
    			</tr>
    		</thead>
    		<tbody>
            	<tr>
        			<td>Admin CPP</td>
        			<td><?php echo number_format($this->device->MasterDevice->CostPerPage->Actual->Raw->AdminCPP, 5); ?></td>
    			</tr>
    			<tr>
        			<td>Service CPP</td>
        			<td><?php echo number_format($this->device->MasterDevice->CostPerPage->Actual->Raw->ServiceCPP, 5); ?></td>
    			</tr>
    			<tr>
        			<td>Report Margin Applied</td>
        			<td><?php echo number_format($this->device->MasterDevice->CostPerPage->Actual->Raw->ReportMargin, 5); ?></td>
    			</tr>
            </tbody>
    	</table>
    </div>
</div>
<hr>
<!-- ---------------------------------------------------------------------------------------------- -->
<div class="span-24">
    <?php foreach($this->device->MasterDevice->Toners as $manufacturerId => $tonersByManufacturer) :?>
    <h3>Manufacturer #<?php echo $manufacturerId; ?>  Toners</h3>
    <?php foreach($tonersByManufacturer as $tonerColor => $tonersByColor) :?>
    <table class='tonerTable'>
    	<caption class="loud"><strong>Color: <?php echo Proposalgen_Model_TonerColor::$ColorNames[$tonerColor]; ?></strong></caption>
    	<thead>
    		<tr>
    			<th style="">Manufacturer</th>
    			<th style="width: 80px;">SKU</th>
    			<th style="width: 80px;">Price</th>
    			<th style="width: 80px;">Yield</th>
    			<th style="width: 80px;">Estimated Black CPP</th>
    			<th style="width: 80px;">Estimated Color CPP</th>
    			<th style="width: 80px;">Actual Black CPP</th>
    			<th style="width: 80px;">Actual Color CPP</th>
    		</tr>
    	</thead>
    	<tbody>
    	<?php foreach($tonersByColor as $toner) :?>
    		<tr>
    			<td ><?php echo $toner->Manufacturer->ManufacturerName; ?></td>
    			<td ><?php echo $toner->TonerSKU; ?></td>
    			<td >$<?php echo number_format($toner->TonerPrice, 2);?></td>
    			<td ><?php echo $toner->TonerYield; ?></td>
    			<td ><?php echo ($toner->CostPerPage->Estimated->BlackAndWhite > 0) ? "$" . number_format($toner->CostPerPage->Estimated->BlackAndWhite, 4) : "-"; ?></td>
    			<td ><?php echo ($toner->CostPerPage->Estimated->Color > 0) ? "$" . number_format($toner->CostPerPage->Estimated->Color, 4) : "-"; ?></td>
    			<td ><?php echo ($toner->CostPerPage->Actual->BlackAndWhite > 0) ? "$" . number_format($toner->CostPerPage->Actual->BlackAndWhite, 4) : "-"; ?></td>
    			<td><?php echo ($toner->CostPerPage->Actual->Color > 0) ? "$" . number_format($toner->CostPerPage->Actual->Color, 4) : "-"; ?></td>
    	<?php endforeach; ?>
    	</tbody>
    </table>
    <?php endforeach; ?>
    <hr/>
    <?php $last = "last"; ?>
    <?php endforeach; ?>
</div>