<?php $this->placeholder('extraNavbar')->set($this->render('_partials/reportMenu.phtml')); ?>
<div class="well">
    <div class="row-fluid">
        <div class="span6">
            <p style="text-align: left">
                <em>Please select a report from the list. After verifying the contents of your reports, you may download a copy by selecting your desired output
                    format from top right corner of each report. </em>
            </p>
        </div>
    </div>
</div>