<?php $this->placeholder('ReportNav')->set($this->render('_partials/reportMenu.phtml')); ?>
<div class="jumbotron">
    <div class='container'>
        <h1>Your reports are ready.</h1>

        <p>Please select a report from the list. After verifying the contents of your reports, you may download a copy by selecting your desired output format from top right corner of each report.</p>
    </div>
</div>