<?php
/**
 * Assessment - Analysis: Service and Supplies Logistics
 */

/* @var $phpWord PHPWord */
$phpWord = $this->phpword;
/* @var $section PHPWord_Section */
$section = $this->section;
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->healthcheck->proposal;
$graphs = $this->graphs;

$section->addTitle($this->translate('Analysis: Service and Supplies Logistics'), 1);
$gradeTable = $section->addTable($this->styles->tables->grades->tablestyle);
$gradeTable->addRow();
$gradeTable->addCell(8028, $this->styles->tables->grades->cell1)->addText($proposal->getRanking()->SuppliesAndServiceLogistics->RankingText, null, 'nospacing');
$gradeTable->addCell(1000, $this->styles->tables->grades->cell2)->addText(number_format($proposal->getRanking()->SuppliesAndServiceLogistics->Rank, 1), 'gradeFont', 'gradeParagraph');
$section->addTextBreak();
$section->addTitle('Printing Device Management Breakdown', 2);
$section->addText($this->translate('Different types of printing devices are managed in different ways-newer networked printers can be managed with remote monitoring software; leased multifunction devices are typically managed by the vendor who sold the machine; devices not connected to the network, such as inkjets and some older printers, are difficult to manage because you cannot monitor them with software.'));

$section->addTextBreak(2);
$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($graphs[1]);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($graphs[2]);
$section->addTextBreak(2);

$inkJetString = $this->translate('less than 10%');
if ($proposal->getPercentPrintingDoneOnInkjet() == 50)
{
    $inkJetString = $this->translate('more than 50%');
}
else if ($proposal->getPercentPrintingDoneOnInkjet()== 38)
{
    $inkJetString = $this->translate('26% to 50%');
}
else if ($proposal->getPercentPrintingDoneOnInkjet() == 18)
{
    $inkJetString = $this->translate('10% to 25%');
}


$section->addTitle($this->translate('Number of Printing Device Models and Supply Types'), 2);

$textrun = $section->createTextRun();
$textrun->addText($this->translate('Out of your '));
$textrun->addText(number_format(count($proposal->getDevices()->allIncludedDeviceInstances)),"bold_text");
$textrun->addText($this->translate(' networked printing devices, you have of '));
$textrun->addText(number_format($proposal->getNumberOfUniqueModels()),"bold_text");
$textrun->addText($this->translate(' different models. Each section of the chart below represents a single model type. We estimate that '));
$textrun->addText(number_format(count($proposal->getLeasedDevices())),"bold_text");
$textrun->addText($this->translate(' of your printing devices are leased machines, for which supplies are included in your contract. The '));
$textrun->addText(number_format(count($proposal->getPurchasedDevices())),"bold_text");
$textrun->addText($this->translate(' remaining machines consist of '));
$textrun->addText(number_format($proposal->getNumberOfUniquePurchasedModels()),"bold_text");
$textrun->addText($this->translate(' different models and use '));
$textrun->addText(number_format($proposal->getNumberOfUniquePurchasedToners()),"bold_text");
$textrun->addText($this->translate(' different supply types. If you hold two of each supply in inventory, you have an estimated '));
$textrun->addText($this->translate('$'),"bold_text");
$textrun->addText(number_format($proposal->getCashHeldInInventory()),"bold_text");
$textrun->addText($this->translate(' in operating cash held in printer supplies inventory'),'bold_text');
$textrun->addText($this->translate(' at any given time.'));


$imageTable = $section->addTable(array (
    'borderBottomSize' => 1 
));
$imageTable->addRow();
$cell = $imageTable->addCell(9028.8, array (
    'valign' => 'center' 
));

$cell->addImage($graphs[3], array (
    'align' => 'center' 
));

$section->addText($this->translate('By using printing devices with the same supplies, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space required. Office Depot can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.'));

$section->addTitle($this->translate('Number of Printing Devices Compatible with Office Depot™ ATR'), 2);
$textrun = $section->createTextRun();
$textrun->addText($this->translate("Out of your " . $proposal->getPurchasedDeviceCount() . " networked printing devices(excluding leased devices), you have "));
$textrun->addText($proposal->getNumberOfDevicesReportingTonerLevels(),"bold_text");
$textrun->addText($this->translate(" that are compatible with Office Depot™ Auto Toner Replenishment (ATR) and " . $proposal->getNumberOfDevicesNotReportingTonerLevels() . " devices that are not compatible. These incompatible devices are shown in the fleet attributes section below. A complete list of all devices and their ATR compatibility can be found in the Appendix."));

$section->addTextBreak(2);
$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($graphs['CompatibleATRBarGraph']);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($graphs['PagesPrinterATRPieGraph']);

$section->addTitle($this->translate('Estimated OEM Toner Costs vs. Estimated Compatible Toner Costs'), 2);
$estimateTonerCostsTable = $section->addTable($this->styles->tables->utilization->tablestyle);
$estimateTonerCostsTable->addRow();
$estimateTonerCostsTable->addCell($cellWidths [0], $this->styles->tables->utilization->cell1)->addText($this->translate('Lowest Utilization'), 'bold_text', 'nospacing_centeralign');
$estimateTonerCostsTable->addCell($cellWidths [1], $this->styles->tables->utilization->cell2)->addText($this->translate('Serial No.'), 'bold_text', 'nospacing_centeralign');
$estimateTonerCostsTable->addCell($cellWidths [2], $this->styles->tables->utilization->cell3)->addText($this->translate('Avg. Monthly Volume'), 'bold_text', 'nospacing_centeralign');
$estimateTonerCostsTable->addCell($cellWidths [3], $this->styles->tables->utilization->cell4)->addText($this->translate('Recommended Max. Volume'), 'bold_text', 'nospacing_centeralign');
/* @var $device Proposalgen_Model_DeviceInstance */
foreach ( $proposal->getLeastUsedDevices() as $device )
{
    $estimateTonerCostsTable->addRow($this->styles->tables->utilization->rowheight);
    $estimateTonerCostsTable->addCell($cellWidths [0], $this->styles->tables->utilization->cell1)->addText($device->getDeviceName(), null, 'nospacing');
    $estimateTonerCostsTable->addCell($cellWidths [1], $this->styles->tables->utilization->cell2)->addText(($device->serialNumber) ?  : "Unknown", null, 'nospacing');
    $estimateTonerCostsTable->addCell($cellWidths [2], $this->styles->tables->utilization->cell3)->addText(number_format($device->getAverageMonthlyPageCount()), null, 'nospacing');
    $estimateTonerCostsTable->addCell($cellWidths [3], $this->styles->tables->utilization->cell4)->addText(number_format($device->getMasterDevice()->getMaximumMonthlyPageVolume()), null, 'nospacing');
}

$section->addText($this->translate('Only takes into account devices for which expected cartridge yields are known.'), 'small_italic_text', 'nospacing');
$section->addTextBreak();
