<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$fh = fopen($this->savePath, "w+");


fputcsv($fh, $this->fieldTitleList);
fputcsv($fh, []);
fputcsv($fh, [My_Brand::getDealerBranding()->mpsProgramName . " Black And White CPP:", $this->monochromeCPP]);
fputcsv($fh, []);
fputcsv($fh, [My_Brand::getDealerBranding()->mpsProgramName . " Color CPP:", $this->colorCPP]);
fputcsv($fh, []);
fputcsv($fh, []);

foreach ($this->fieldList as $line)
{
    fputcsv($fh, $line);
}


fclose($fh);

if (Zend_Controller_Front::getInstance()->getRequest()->isXmlHttpRequest()) echo DOMAIN_URL.$this->baseUrl($this->publicFileName);
else header('Location: '.DOMAIN_URL.$this->baseUrl($this->publicFileName));
