<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$fh = fopen($this->savePath, "w+");


fputcsv($fh, $this->fieldTitleList);
fputcsv($fh, array());
fputcsv($fh, array(My_Brand::getDealerBranding()->mpsProgramName . " Black And White CPP:", $this->monochromeCPP));
fputcsv($fh, array());
fputcsv($fh, array(My_Brand::getDealerBranding()->mpsProgramName . " Color CPP:", $this->colorCPP));
fputcsv($fh, array());
fputcsv($fh, array());

foreach ($this->fieldList as $line)
{
    fputcsv($fh, $line);
}


fclose($fh);
echo $this->baseUrl($this->publicFileName);