<?php /* @var $masterDevice Proposalgen_Model_MasterDevice */ $masterDevice = $this->masterDevice; ?>
<div class="well">
    <dl class="dl-horizontal">
        <dt>Manufacturer</dt><dd><?php echo $masterDevice->getManufacturer()->getFullname(); ?></dd>
        <dt>Name</dt><dd><?php echo $masterDevice->getPrinterModel(); ?></dd>
        <dt>Full Name</dt><dd><?php echo $masterDevice->getFullDeviceName(); ?></dd>
        
        <dt>Toner Config</dt><dd><?php echo $masterDevice->getTonerConfig()->getTonerConfigName(); ?></dd>
        <dt>Is Copier</dt><dd><?php echo ($masterDevice->getIsCopier()) ? "Yes" : "No"; ?></dd>
        <dt>Is Fax</dt><dd><?php echo ($masterDevice->getIsFax()) ? "Yes" : "No"; ?></dd>
        <dt>Is Scanner</dt><dd><?php echo ($masterDevice->getIsScanner()) ? "Yes" : "No"; ?></dd>
        <dt>Is Duplex</dt><dd><?php echo ($masterDevice->getIsDuplex()) ? "Yes" : "No"; ?></dd>
        <dt>Is Replacement Device</dt><dd><?php echo ($masterDevice->getIsReplacementDevice()) ? "Yes" : "No"; ?></dd>
        <dt>Watts Power Normal</dt><dd><?php echo ($masterDevice->getWattsPowerNormal()) ?: 'Not Set'; ?></dd>
        <dt>Watts Power Idle</dt><dd><?php echo ($masterDevice->getWattsPowerIdle()) ?: 'Not Set'; ?></dd>
        <dt>Device Price</dt><dd><?php echo ($masterDevice->getCost()) ? $this->currency($masterDevice->getCost()) : 'No Price Defined'; ?></dd>
        <dt>Service Cost Per Page</dt><dd><?php echo ($masterDevice->getServiceCostPerPage()) ? $this->currency($masterDevice->getServiceCostPerPage(), array('precision' => 4)) : 'No Price Defined'; ?></dd>
        <dt>Launch Date</dt><dd><?php echo ($masterDevice->getLaunchDate()) ?: 'Not Set'; ?></dd>
        <dt>Date Created</dt><dd><?php echo ($masterDevice->getDateCreated()) ?: 'Not Set'; ?></dd>
        <dt>Duty Cycle</dt><dd><?php echo ($masterDevice->getDutyCycle()) ?: 'Not Set'; ?></dd>
        <dt>PPM Black</dt><dd><?php echo ($masterDevice->getPPMColor()) ?: 'Not Set'; ?></dd>
        <dt>PPM Color</dt><dd><?php echo ($masterDevice->getPPMColor()) ?: 'Not Set'; ?></dd>
        <dt>Is Leased</dt><dd><?php echo ($masterDevice->getIsLeased()) ? "Yes" : "No"; ?></dd>
        <?php if ($masterDevice->getIsLeased()) : ?>
        <dt>Leased Toner Yield</dt><dd><?php echo number_format($masterDevice->getLeasedTonerYield()); ?></dd>
        <?php endif; ?>
    </dl>
</div>