<div class="container">
    <p><em>Version: <?= $this->Version(); ?></em></p>

    <p><em>Database Version: <?= $this->databaseVersion; ?></em></p>

    <p><em>Build Date: <?= $this->buildinfo->date; ?></em></p>

    <p><em>Build Hash: <?= $this->buildinfo->githash; ?></em></p>
    <hr>
    <div class="changelog">
        <?php
        $markdown = new \Michelf\MarkdownExtra();
        echo $markdown->transform($this->changelog);
        ?>
    </div>
</div>