<div class="page-header">
    <h1>Hardware Library -
        <small>Manufacturers</small>
    </h1>
</div>
<?php if ($this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_MANUFACTURER_CREATE))
{ ?>
    <div class="clearfix">
        <a class="btn btn-success pull-right btn-small create-button" href="<?php echo $this->url(array('action' => 'create')) ?>">
            <i class="icon-white icon-plus-sign"></i> Create new</a>
    </div>
<?php
}
if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
    <table class="table table-striped table-condensed table-bordered">
        <thead>
        <tr>
            <th style="width: 30px;">ID</th>
            <th>Full Name</th>
            <th>Display Name</th>
            <?php if ($this->canEdit) : ?>
                <th style="width: 80px;">Is Deleted</th>
                <th style="width: 80px;">Action</th>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($this->paginator->getCurrentItems() as $manufacturer) : /* @var $manufacturer Proposalgen_Model_Manufacturer */ ?>
            <tr>
                <td><?php echo $manufacturer->id; ?></td>
                <td><?php echo $manufacturer->fullname; ?></td>
                <td><?php echo $manufacturer->displayname; ?></td>
                <?php if ($this->canEdit) : ?>
                    <td><?php echo ($manufacturer->isDeleted) ? "Deleted" : ""; ?></td>
                    <td>
                        <?php if ($this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_MANUFACTURER_EDIT))
                        { ?>
                            <div class="btn-group">
                                <a class="btn btn-warning" title="Edit Manufacturer" href="<?php echo $this->url(array('action' => 'edit', 'id' => $manufacturer->id)); ?>"><i class="icon-pencil"></i></a>
                            </div>
                        <?php } ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
    <h1>There are no manufacturers</h1>
<?php endif; ?>

