<?php /* @var $manufacturer Proposalgen_Model_Manufacturer */ $manufacturer = $this->manufacturer; ?>
<div class="page-header">
    <h1>Manufacturer Management (Beta)</h1>
</div>
<div class="well">
    <dl class="dl-horizontal">
        <dt>Full Name</dt><dd><?php echo $manufacturer->getName(); ?></dd>
        <dt>Display Name</dt><dd><?php echo $manufacturer->getPhoneNumber(); ?></dd>
        <?php if ($manufacturer->getIsDeleted()) : ?>
        <dt>Deleted</dt><dd>This manufacturer is deleted.</dd>
        <?php else: ?>
        <dt>Deleted</dt><dd>No.</dd>
        <?php endif; ?>
    </dl>
</div>