<?php /* @var $manufacturer Proposalgen_Model_Manufacturer */ $manufacturer = $this->manufacturer; ?>
<div class="well">
    <dl class="dl-horizontal">
        <dt>Name</dt><dd><?php echo $manufacturer->getName(); ?></dd>
        <dt>Phone Number</dt><dd><?php echo $manufacturer->getPhoneNumber(); ?></dd>
        <dt>Address</dt><dd><?php echo nl2br($manufacturer->getAddress()); ?></dd>
    </dl>
</div>