<?php $this->headScript()->appendFile($this->baseUrl('js/healthcheck/index/selectUpload.js')); ?>
<div class="well">
    <form id="selectUpload" method="POST">
        <input type="hidden" name="selectIds" id="selectIds" value="<?php echo $this->selectedUploadId;?>" />
    </form>
        <table id="selectUploadGrid"></table>
        <div id="selectUploadGridPager"></div>

    <?php echo $this->navigationForm; ?>
</div>