<?php
/* @var $optimization Memjetoptimization_ViewModel_Optimization */
$optimization = $this->optimization;
/* @var $memjetOptimization Memjetoptimization_Model_Memjet_Optimization */
$memjetOptimization = $this->memjetOptimization;
/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

// Initialize some properties
$properties = $phpWord->getDocumentProperties();
$properties->setCreator('MPS Assessment Software');
$properties->setTitle('Customer Memjet Optimization Report');
$properties->setDescription('MPS Assessment Software');
$properties->setCategory('Customer Report');
$properties->setLastModifiedBy('MPS Assessment Software');

$section          = $phpWord->addSection(array(
    'orientation'  => null,
    'marginLeft'   => 375,
    'marginRight'  => 375,
    'marginTop'    => 375,
    'marginBottom' => 375
));
$titlepageSection = $section;

$titlePageBackgroundColor  = My_Brand::getDealerBranding()->titlePageTitleBackgroundColor;
$titlePageBackgroundColor2 = My_Brand::getDealerBranding()->titlePageInformationBackgroundColor;
$titlePageTextColor        = My_Brand::getDealerBranding()->titlePageTitleFontColor;
$titlePageTextColor2       = My_Brand::getDealerBranding()->titlePageInformationFontColor;
$headingColor              = My_Brand::getDealerBranding()->h1FontColor;
$h2Background              = My_Brand::getDealerBranding()->h2BackgroundColor;
$h2Color                   = My_Brand::getDealerBranding()->h2FontColor;
$h3Color                   = My_Brand::getDealerBranding()->h1FontColor;

/* Tables for the device layouts */
$widthTwips       = 11490;
$header_color     = $this->wordStyles->default->tableHeaderBackgroundColor;
$sub_header_color = $this->wordStyles->default->tableSubHeaderBackgroundColor;
$even_color       = "EFEFEF";
$odd_color        = "FCFCFC";
$footer_color     = "b8cce3";
$highlight_color  = "ebc7a4";


/**
 * Paragraph styles
 */
// H2 Style #5881BC
$phpWord->addTitleStyle(2, array(
    'size'   => 12,
    'color'  => My_Brand::getDealerBranding()->h2FontColor,
    'bold'   => true,
    'italic' => true
), array(
    'bgColor' => My_Brand::getDealerBranding()->h2BackgroundColor,
    'shading' => array(
        'fill' => My_Brand::getDealerBranding()->h2BackgroundColor,
    )
));
$this->phpword->addParagraphStyle('titleStyle1', array(
    'align'      => 'center',
    'spaceAfter' => 100,
    'bgColor'    => $titlePageBackgroundColor,
    'shading'    => array(
        'fill' => $titlePageBackgroundColor,
    )
));
$phpWord->addParagraphStyle('titleStyle2', array(
    'spaceAfter'  => 50,
    'spaceBefore' => 50,
    'bgColor'     => $titlePageBackgroundColor2,
    'shading'     => array(
        'fill' => $titlePageBackgroundColor2,
    )
));
$phpWord->addParagraphStyle('titleStyle3', array(
    'spaceAfter' => 100,
    'tabs'       => array(
        new \PhpOffice\PhpWord\Style\Tab('left', 350)
    ),
    'bgColor'    => $titlePageBackgroundColor2,
    'shading'    => array(
        'fill' => $titlePageBackgroundColor2,
    )
));
$phpWord->addFontStyle('titlepage_title', array(
    'size'  => 24,
    'bold'  => true,
    'color' => $titlePageTextColor
));

$phpWord->addFontStyle('titlepage_subtitle', array(
    'size'  => 16,
    'bold'  => true,
    'color' => $titlePageTextColor2
));

$phpWord->addFontStyle('titlepage_address', array(
    'size'  => 12,
    'color' => $titlePageTextColor2
));
$styles = (object)array(
    "tables" => (object)array(
            "rowheader"          => array(
                'tblHeader' => true,
                'cantSplit' => true,
            ),
            "rowstyle"           => array(
                "cantSplit" => true,
            ),
            "singleimage"        => (object)array(
                    "tablestyle" => array(),
                    "cell1"      => array(
                        "valign" => "center"
                    )
                ),
            "doubleimage"        => (object)array(
                    "tablestyle" => array(),
                    "cell1"      => array(
                        "valign" => "center"
                    ),
                    "cell2"      => array(
                        "valign" => "center"
                    )
                ),
            "tripleimage"        => (object)array(
                    "tablestyle" => array(),
                    "cell1"      => array(
                        "valign" => "center"
                    ),
                    "cell2"      => array(
                        "valign" => "center"
                    ),
                    "cell3"      => array(
                        "valign" => "center"
                    )
                ),
            "twoColumnDataTable" => (object)array(
                    "tablestyle" => array(
                        'cellMarginTop'    => 100,
                        'cellMarginRight'  => 100,
                        'cellMarginBottom' => 100,
                        'cellMarginLeft'   => 100
                    ),
                    "rowheight"  => null,
                    "cell1"      => array(
                        "valign" => "center"
                    ),
                    "cell2"      => array(
                        "valign" => "center"
                    )
                ),
        ),
    "images" => (object)array(
            "center" => array(
                "align" => "center"
            )
        ),
);

$standard_cell = (object)array(
    "even"           => array(
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
    ),
    "odd"            => array(
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'right'
    )
);

$standard_cell_vcenter = (object)array(
    "even"           => array(
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
        "valign"           => 'center'
    ),
    "odd"            => array(
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
        "valign"           => 'center'
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'center',
    )
);

$standard_cell_vcenter_no_right_border = (object)array(
    "even"           => array(
        "bgColor" => $even_color,
        "valign"  => 'center'
    ),
    "odd"            => array(
        "bgColor" => $odd_color,
        "valign"  => 'center'
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'center',
    )
);


$standard_cell_left = (object)array(
    "even"             => array(
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "odd"              => array(
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "fontStyle"        => null,
    "paragraphStyle"   => array(
        'spaceAfter' => 0,
        'align'      => 'left'
    ),
    "manufacturerName" => (object)array(
            "fontStyle"      => array('italic' => true),
            "paragraphStyle" => array(
                'spaceAfter' => 0,
                'align'      => 'left'
            ),
        ),
    "modelName"        => (object)array(
            "fontStyle"      => array('bold' => true),
            "paragraphStyle" => array(
                'spaceAfter' => 0,
                'align'      => 'left'
            ),
        ),
);

$standard_cell_right = (object)array(
    "even"           => array(
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "odd"            => array(
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'right'
    ),
);

$standard_cell_no_right_border = (object)array(
    "even"           => array(
        "bgColor" => $even_color,
    ),
    "odd"            => array(
        "bgColor" => $odd_color,
    ),
    "fontStyle"      => null,
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'right'
    )
);

$standard_header = (object)array(
    "cellStyle"      => array(
        'bgColor' => $header_color
    ),
    "fontStyle"      => array(
        'bold' => true
    ),
    "paragraphStyle" => array(
        'spaceAfter' => 0,
        'align'      => 'center'
    )
);

$suggestedDevices = (object)array(
    "tablestyle" => array(
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ),
    "col1Width"  => $widthTwips * 0.20,
    "col2Width"  => $widthTwips * 0.20,
    "col3Width"  => $widthTwips * 0.15,
    "col4Width"  => $widthTwips * 0.30,
    "col5Width"  => $widthTwips * 0.075,
    "col6Width"  => $widthTwips * 0.075,
    "body"       => (object)array(
            "rowheight" => null,
            "cell1"     => $standard_cell_left,
            "cell2"     => $standard_cell_left,
            "cell3"     => $standard_cell,
            "cell4"     => $standard_cell_vcenter,
            "cell5"     => $standard_cell_vcenter,
            "cell6"     => $standard_cell_vcenter_no_right_border
        ),
    "header"     => (object)array(
            'header'     => $standard_header,
            'sub_header' => $standard_sub_header,
        ),
);
$flaggedDevices   = (object)array(
    "tablestyle" => array(
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ),
    "col1Width"  => $widthTwips * 0.25,
    "col2Width"  => $widthTwips * 0.15,
    "col3Width"  => $widthTwips * 0.25,
    "col4Width"  => $widthTwips * 0.05,
    "col5Width"  => $widthTwips * 0.075,
    "col6Width"  => $widthTwips * 0.075,
    "col7Width"  => $widthTwips * 0.075,
    "col8Width"  => $widthTwips * 0.075,
    "body"       => (object)array(
            "rowheight" => null,
            "cell1"     => $standard_cell_left,
            "cell2"     => $standard_cell_left,
            "cell3"     => $standard_cell_left,
            "cell4"     => $standard_cell_no_right_border,
            "cell5"     => $standard_cell_no_right_border,
            "cell6"     => $standard_cell_no_right_border,
            "cell7"     => $standard_cell_no_right_border,
            "cell8"     => $standard_cell_no_right_border,
        ),
    "header"     => (object)array(
            'header'     => $standard_header,
            'sub_header' => $standard_sub_header,
        ),
);
$retiredDevices   = (object)array(
    "tablestyle" => array(
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ),
    "col1Width"  => $widthTwips * 0.35,
    "col2Width"  => $widthTwips * 0.25,
    "col3Width"  => $widthTwips * 0.166,
    "col4Width"  => $widthTwips * 0.166,
    "col5Width"  => $widthTwips * 0.166,
    "body"       => (object)array(
            "rowheight" => null,
            "cell1"     => $standard_cell_left,
            "cell2"     => $standard_cell_left,
            "cell3"     => $standard_cell_right,
            "cell4"     => $standard_cell_vcenter,
            "cell5"     => $standard_cell_vcenter_no_right_border,
        ),
    "header"     => (object)array(
            'header'     => $standard_header,
            'sub_header' => $standard_sub_header,
        ),
);

$acceptableDevices = (object)array(
    "tablestyle" => array(
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ),
    "col1Width"  => $widthTwips * 0.25,
    "col2Width"  => $widthTwips * 0.25,
    "col3Width"  => $widthTwips * 0.25,
    "col4Width"  => $widthTwips * 0.25,
    "body"       => (object)array(
            "rowheight" => null,
            "cell1"     => $standard_cell_left,
            "cell2"     => $standard_cell_left,
            "cell3"     => $standard_cell_right,
            "cell4"     => $standard_cell_right,
        ),
    "header"     => (object)array(
            'header'     => $standard_header,
            'sub_header' => $standard_sub_header,
        ),
);

$deviceTables = (object)array(
    "tables" => (object)array(
            "replacement" => $suggestedDevices,
            "acceptable"  => $acceptableDevices,
            "retire"      => $retiredDevices,
            "flagged"     => $flaggedDevices,
        ));

$doubleCenterTable = (object)array(
    "tablestyle" => array(),
    "col1Width"  => $widthTwips * 0.50,
    "col2Width"  => $widthTwips * 0.50,
    "body"       => (object)array(
            "cell1" => array(
                "valign" => "center"
            ),
            "cell2" => array(
                "valign" => "center"
            )
        ),
    "image"      => (object)array(
            "cell1" => array(
                'align' => 'right'
            ),
            "cell2" => array(
                'align' => 'left'
            ),
        )
);

$titleData = array(
    "phpword"            => $phpWord,
    "section"            => $titlepageSection,
    "memjetOptimization" => $memjetOptimization,
    "styles"             => $styles,
    "dealerLogoFile"     => $this->dealerLogoFile,
    "companyName"        => My_Brand::getDealerBranding()->shortDealerName,
);

$profitabilityDevices = new Memjetoptimization_Model_Optimization_Customer($memjetOptimization);

$data = array(
    "phpword"              => $phpWord,
    "section"              => $section,
    "memjetOptimization"   => $memjetOptimization,
    "optimization"         => $optimization,
    "styles"               => $styles,
    "graphs"               => $this->graphs,
    "devicetables"         => $deviceTables,
    "profitabilityDevices" => $profitabilityDevices,
    "twocenter"            => $doubleCenterTable,
    "companyName"          => My_Brand::getDealerBranding()->shortDealerName,

);
// Actual document pages
$this->partial("report/customer/optimization/docx/01_titlepage.phtml", $titleData);
$this->partial("report/customer/optimization/docx/02_optimizationsummary.phtml", $data);
$this->partial("report/customer/optimization/docx/03_replacement.phtml", $data);
$this->partial("report/customer/optimization/docx/04_flagged.phtml", $data);
$this->partial("report/customer/optimization/docx/05_retire.phtml", $data);
$this->partial("report/customer/optimization/docx/06_acceptable.phtml", $data);
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save($this->savePath);

echo $this->baseUrl($this->publicFileName);
