<?php
$memjetOptimization = $this->memjetOptimization;
/* @var $optimization Memjetoptimization_ViewModel_Optimization */
$optimization = $this->optimization;
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $profitabiltyDevices Memjetoptimization_Model_Optimization_Dealer */
$profitabiltyDevices = $this->profitabilityDevices;

$deviceCount           = count($profitabiltyDevices->flagged);
$totalPurchasedDevices = count($optimization->getDevices()->purchasedDeviceInstances->getDeviceInstances());
;
$section->addTitle(sprintf($this->translate('Flagged Devices (%1$s of %2$s)'), $deviceCount, $totalPurchasedDevices), 2);
$section->addText($this->translate('The following devices have been targeted for replacements: '));

// Table with values
$tcStyle = $this->devicetables->tables->flagged;
$table   = $section->addTable($tcStyle->tablestyle);
// Table header
$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText($this->translate('Device Name'), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText($this->translate('Serial / IP Address'), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText($this->translate('Reason'), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText($this->translate('Mono AMPV'), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col5Width, $tcStyle->header->header->cellStyle)->addText($this->translate('Color AMPV'), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col6Width, $tcStyle->header->header->cellStyle)->addText($this->translate('Mono CPP'), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col7Width, $tcStyle->header->header->cellStyle)->addText($this->translate('Color CPP'), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col8Width, $tcStyle->header->header->cellStyle)->addText($this->translate('Monthly Cost'), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

// Begin with data rows
foreach ($profitabiltyDevices->flagged as $device)
{
    $isColor = $device->getMasterDevice()->isColor();
    $cycle   = ($this->cycle(array(true, false))->next()->current());
    if ($cycle)
    {
        $ampvStyle = $tcStyle->body->cell3->even;
        $style     = $tcStyle->body->cell1->even;
    }
    else
    {
        $ampvStyle = $tcStyle->body->cell3->odd;
        $style     = $tcStyle->body->cell1->odd;
    }

    $table->addRow($tcStyle->body->rowheight);

    $cell1 = $table->addCell($tcStyle->collWidth, $style);
    $cell1->addText($device->getMasterDevice()->getManufacturer()->fullname, $tcStyle->body->cell1->manufacturerName->fontStyle, $tcStyle->body->cell1->manufacturerName->paragraphStyle);
    $cell1->addText($device->getMasterDevice()->modelName, $tcStyle->body->cell1->modelName->fontStyle, $tcStyle->body->cell1->modelName->paragraphStyle);

    $cell2 = $table->addCell($tcStyle->col2Width, $style);
    $cell2->addText($device->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
    $cell2->addText($device->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);

    $table->addCell($tcStyle->col3Width, $ampvStyle)->addText($device->getMemjetReason($memjetOptimization->id), $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $ampvStyle)->addText(number_format($device->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $ampvStyle)->addText(($isColor) ? number_format($device->getPageCounts()->getColorPageCount()->getMonthly()) : 'N/A', $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);
    $table->addCell($tcStyle->col6Width, $ampvStyle)->addText($this->currency($device->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->monochromeCostPerPage, array('precision' => 4)), $tcStyle->body->cell6->fontStyle, $tcStyle->body->cell6->paragraphStyle);
    $table->addCell($tcStyle->col7Width, $ampvStyle)->addText(($isColor) ? $this->currency($device->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->colorCostPerPage, array('precision' => 4)) : 'N/A', $tcStyle->body->cell7->fontStyle, $tcStyle->body->cell7->paragraphStyle);
    $table->addCell($tcStyle->col8Width, $ampvStyle)->addText($this->currency($device->calculateMonthlyCost($optimization->getCostPerPageSettingForDealer())), $tcStyle->body->cell8->fontStyle, $tcStyle->body->cell8->paragraphStyle);
}
$section->addTextBreak();
$section->addTitle($this->translate('Technology Features and Functionality'), 2);
$section->addText($this->translate('If you printed every document on both sides of the page, you could use up to 50% less paper than you would by only printing on one side. You could further reduce your paper consumption
by using a scanner to e-mail documents instead of printing copies for distribution. The following charts show how many of your printing devices have duplex and scanning capabilities:'));

$tcStyle    = $this->twocenter;
$imageTable = $section->addTable($tcStyle->tablestyle);
$imageTable->addRow();
$imageTable->addCell($tcStyle->col1Width)->addImage($this->graphs [8], $tcStyle->image->cell1);
$imageTable->addCell($tcStyle->col2Width)->addImage($this->graphs [9], $tcStyle->image->cell2);