<?php
/* @var $optimization Memjetoptimization_ViewModel_Optimization */
$optimization = $this->optimization;
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;
/* @var $profitabiltyDevices MemjetOptimization_Model_Optimization_Dealer */
$profitabiltyDevices = $this->profitabilityDevices;
// Retired devices get rendered here

// Table with values
$deviceCount           = count($profitabiltyDevices->retired);
$totalPurchasedDevices = count($optimization->getDevices()->purchasedDeviceInstances->getDeviceInstances());
$section->addTitle(sprintf('Retired Devices (%1$s of %2$s)', $deviceCount, $totalPurchasedDevices), 2);
$section->addText('Devices with both low volume and age of over 8 years have been targeted for retirement. We suggest migrating the page volume into another device. ');

$tcStyle = $this->devicetables->tables->retire;
$table   = $section->addTable($tcStyle->tablestyle);
// Table header
$table->addRow($tcStyle->body->rowheight,$this->styles->tables->rowheader);
$table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText('Device Name', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText('Life Page Count', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText('Age (Years)', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col5Width, $tcStyle->header->header->cellStyle)->addText(sprintf('%1$s Compatible', My_Brand::$jit), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

// Begin with data rows
foreach ($profitabiltyDevices->retired as $device)
{
    $cycle = ($this->cycle(array(true, false))->next()->current());
    if ($cycle)
    {
        $ampvStyle = $tcStyle->body->cell3->even;
        $style     = $tcStyle->body->cell1->even;
    }
    else
    {
        $ampvStyle = $tcStyle->body->cell3->odd;
        $style     = $tcStyle->body->cell1->odd;
    }

    $table->addRow($tcStyle->body->rowheight,$this->styles->tables->rowstyle);

    $cell = $table->addCell($tcStyle->col1Width, $style);
    $cell->addText($device->getMasterDevice()->getManufacturer()->fullname, $tcStyle->body->cell1->manufacturerName->fontStyle, $tcStyle->body->cell1->manufacturerName->paragraphStyle);
    $cell->addText($device->getMasterDevice()->modelName, $tcStyle->body->cell1->modelName->fontStyle, $tcStyle->body->cell1->modelName->paragraphStyle);

    $cell2 = $table->addCell($tcStyle->col2Width, $style);
    $cell2->addText($device->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
    $cell2->addText($device->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);

    $table->addCell($tcStyle->col3Width, $ampvStyle)->addText($device->getMeter()->endMeterLife, $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $ampvStyle)->addText($device->getAge(), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $ampvStyle)->addText(($device->isCapableOfReportingTonerLevels) ? 'Yes' : 'No', $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);
}
$section->addTextBreak();
$tcStyle    = $this->twocenter;
$imageTable = $section->addTable($tcStyle->tablestyle);
$imageTable->addRow();
$imageTable->addCell($tcStyle->col1Width, $tcStyle->body->cell1)->addImage($this->graphs [10], $tcStyle->image->cell1);
$imageTable->addCell($tcStyle->col2Width, $tcStyle->body->cell2)->addImage($this->graphs [11], $tcStyle->image->cell2);
$section->addTextBreak();