<?php
/* @var $optimization Memjetoptimization_ViewModel_Optimization */
$optimization = $this->optimization;
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;
/* @var $profitabiltyDevices Memjetoptimization_Model_Optimization_Dealer */
$profitabiltyDevices = $this->profitabilityDevices;

$deviceCount           = count($profitabiltyDevices->kept);
$totalPurchasedDevices = count($optimization->getDevices()->purchasedDeviceInstances->getDeviceInstances());
$section->addTitle("Acceptable Devices ({$deviceCount} of {$totalPurchasedDevices}) ", 2);
$section->addText('The following devices have been deemed productive and we suggest keeping these devices.');

// Table with values
$tcStyle = $this->devicetables->tables->acceptable;
$table   = $section->addTable($tcStyle->tablestyle);
// Table header
$table->addRow($tcStyle->body->rowheight, $this->styles->tables->rowheader);
$table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText('Device Name', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText('Mono AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText('Color AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

// Begin with data rows
foreach ($profitabiltyDevices->kept as $device)
{
    $isColor = $device->getMasterDevice()->isColor();
    $cycle   = ($this->cycle(array(true, false))->next()->current());
    if ($cycle)
    {
        $ampvStyle = $tcStyle->body->cell3->even;
        $style     = $tcStyle->body->cell1->even;
    }
    else
    {
        $ampvStyle = $tcStyle->body->cell3->odd;
        $style     = $tcStyle->body->cell1->odd;
    }

    $table->addRow($tcStyle->body->rowheight, $this->styles->tables->rowstyle);

    $cell = $table->addCell($tcStyle->collWidth, $style);
    $cell->addText($device->getMasterDevice()->getManufacturer()->fullname, $tcStyle->body->cell1->manufacturerName->fontStyle, $tcStyle->body->cell1->manufacturerName->paragraphStyle);
    $cell->addText($device->getMasterDevice()->modelName, $tcStyle->body->cell1->modelName->fontStyle, $tcStyle->body->cell1->modelName->paragraphStyle);

    $cell2 = $table->addCell($tcStyle->col2Width, $style);
    $cell2->addText($device->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
    $cell2->addText($device->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $ampvStyle)->addText($this->formatPageVolume($device->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $ampvStyle)->addText(($isColor) ? $this->formatPageVolume($device->getPageCounts()->getColorPageCount()->getMonthly()) : 'N/A', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
}

$section->addTextBreak();
$section->addTitle('Number of Printing Device Models and Supply Types', 2);
$section->addText(sprintf('Out of your %1$s networked printing devices, you have %2$s unique %3$s. Each section of the chart below represents a single model type. We estimate that %4$s of your printing devices %5$s leased %6$s, for which supplies are included in your contract. The %7$s remaining %8$s of %9$s %10$s and %11$s %12$s %13$s. If you hold two of each supply in inventory, you have an estimated $%7$s in operating cash held in printer supplies inventory at any given time.',
    number_format(count($optimization->getDevices()->purchasedDeviceInstances->getDeviceInstances())), //1
    number_format($optimization->getNumberOfUniqueModels()), //2
    (number_format($optimization->getNumberOfUniqueModels()) == 1) ? 'model' : 'models', //3
    number_format(count($optimization->getDevices()->leasedDeviceInstances->getDeviceInstances())), //4
    (number_format($optimization->getDevices()->leasedDeviceInstances->getCount()) == 1) ? 'is a' : 'are', //5
    (number_format($optimization->getDevices()->leasedDeviceInstances->getCount()) == 1) ? 'machine' : 'machines', //6
    number_format(count($optimization->getDevices()->purchasedDeviceInstances->getDeviceInstances())), //7
    (number_format($optimization->getDevices()->purchasedDeviceInstances->getCount()) == 1) ? 'machine consists' : 'machines consist', //8
    number_format($optimization->getNumberOfUniquePurchasedModels()), //9
    (number_format($optimization->getNumberOfUniquePurchasedModels()) == 1) ? 'model' : 'different models', //10
    (number_format($optimization->getNumberOfUniquePurchasedModels()) == 1) ? 'uses' : 'use', //11
    number_format($optimization->getNumberOfUniquePurchasedToners()), //12
    (number_format($optimization->getNumberOfUniquePurchasedToners()) == 1) ? 'supply type' : 'different supply types', //13
    number_format($optimization->getCashHeldInInventory())));
$section->addTextBreak();

$section->addImage($this->graphs [12], array('align' => 'center'));
$section->addImage($this->graphs [13], array('align' => 'center'));
$section->addTextBreak();

$section->addText($this->translate('By using printing devices with the same supplies, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space required.
%1$s can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.', $this->companyName));

$section->addTitle('Color Usage', 2);
$section->addText(sprintf('You currently have %1$s color printing devices that print a monthly average of %2$s color pages per month, which is %3$s%% of your total monthly print volume.', number_format($optimization->getNumberOfColorCapableDevices()), $this->formatPageVolume($optimization->getDevices()->allIncludedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly()), number_format(($optimization->getPercentages()->TotalColorPercentage * 100), 2)));

$section->addText($this->translate('Overall, printing in color is more expensive than printing in monochrome. The ideal amount of color usage depends on your printing needs, but the use of color in important documents can enhance your
company\'s professional image, improve comprehension and increase readership. %1$s can help you track your color printing and provide low-cost color hardware options.', $this->companyName));

$tcStyle    = $this->twocenter;
$imageTable = $section->addTable($tcStyle->tablestyle);
$imageTable->addRow();
$imageTable->addCell($tcStyle->col1Width)->addImage($this->graphs [14], $tcStyle->image->cell1);
$imageTable->addCell($tcStyle->col2Width)->addImage($this->graphs [15], $tcStyle->image->cell2);