<?php
/* @var $pages Zend_Navigation_Page[] */
$pages = $this->pages;
if (count($pages) > 0)
{
    $html    = array(
        '<ul class="breadcrumb">'
    );
    $html [] = "<li><a href='" . $pages [0]->getHref() . "'>" . $pages [0]->getLabel() . "</a></li>";

    for ($i = 1; $i < count($pages); $i++)
    {
        $html [] = "<li><span class='divider'>/</span><a href='" . $pages [$i]->getHref() . "'>" . $pages [$i]->getLabel() . "</a></li>";
    }

    $html [] = '</ul>';

    echo join(PHP_EOL, $html);
}