<?php
/* @var $pages Zend_Navigation_Page[] */
$pages = $this->pages;
$html  = [];
if (count($pages) > 0)
{
    $html[] = '<ol class="breadcrumb">';

    foreach ($pages as $page)
    {
        $icon = ($page->get('icon')) ? sprintf('<i class="%s"></i> ', $page->get('icon')) : '';

        $html [] = sprintf('<li><a href="%s">%s%s</a></li>', $page->getHref(), $icon, $page->getLabel());
    }

    $html[] = '</ol>';

    echo implode(PHP_EOL, $html);
}