<?php
$html = array (
    '<ul class="' . $this->navigation()
        ->menu()
        ->getUlClass() . '">' 
);

/* @var $page Zend_Navigation_Page */ 
foreach ( $this->container as $page )
{
    // visibility of the page
    if (! $page->isVisible())
    {
        continue;
    }
    
    // dropdown
    $dropdown = ! empty($page->pages);
    // header
    $liclasses = "";
    $liclasses .= ($dropdown) ? "dropdown " : "";
    $liclasses .= ($page->isActive()) ? "active " : "";
    
    $html [] = '<li' . (strlen($liclasses) > 0 ? ' class="' . $liclasses . '"' : '') . '>';
    $html [] = '<a href="' . ($dropdown ? '#' : $page->getHref()) . '" ' . 'class="dropdown-toggle" data-toggle="dropdown">';
    $html [] = $page->getLabel();
    
    if ($dropdown)
    {
        $html [] = '<b class="caret"></b>';
    }
    
    $html [] = '</a>';
    
    if (! $dropdown)
    {
        $html [] = '</li>';
        continue;
    }
    
    $html [] = '<ul class="dropdown-menu">';
    
    /* @var $page Zend_Navigation_Page */
    foreach ( $page->pages as $subpage )
    {
        // visibility of the sub-page
        if (! $subpage->isVisible())
        {
            continue;
        }
        
        $subPageClasses = "";
        $subPageClasses .= ($subpage->isActive()) ? "active " : "";
        $subPageClasses .= ($subpage->getClass()) ?  : "";
        $html [] = '<li' . (strlen($subPageClasses) > 0 ? ' class="' . $subPageClasses . '"' : '') . '>';
        if (strcasecmp("divider", $subpage->getClass()))
        {
            $html [] = '<a href="' . $subpage->getHref() . '">';
        }
        if ($subpage->get('icon'))
        {
            $html [] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
        }
        
        $html [] = $subpage->getLabel();
        $html [] = "</a>";
        $html [] = "</li>";
    }
    
    $html [] = "</ul>";
    $html [] = "</li>";
}

$html [] = '</ul>';

echo join(PHP_EOL, $html);