<?php

// Get the path based on the theme
$commonPartsBasePath = 'quote/reports/common/' . $this->App()->theme;
// Render the elements in the theme
$this->render("{$commonPartsBasePath}/styles.phtml");

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;
$section->addPageBreak();
$section->addTitle($this->translate($this->docStrings->quoteHeader), 1);
$section->addText('Below is a quote for the requested hardware:');

$groupCount = 0;
$tcStyle    = $this->styles->tables->quoteTable;
/* @var $quote Quotegen_Model_Quote */
$quote = $this->quote;

/* @var $quoteDeviceGroup Quotegen_Model_QuoteDeviceGroup */
foreach ($quote->getQuoteDeviceGroups() as $quoteDeviceGroup)
{
    if ($quoteDeviceGroup->calculateTotalQuantity() > 0)
    {
        $table = $section->addTable($tcStyle->tablestyle);

        $table->addRow($tcStyle->header->rowheight, $tcStyle->header->rowStyle);
        $table->addCell($tcStyle->col1Width, $tcStyle->header->cell1->cellStyle)->addText('Item', $tcStyle->header->cell1->fontStyle, $tcStyle->header->cell1->paragraphStyle);
        $table->addCell($tcStyle->col2Width, $tcStyle->header->cell2->cellStyle)->addText('SKU', $tcStyle->header->cell2->fontStyle, $tcStyle->header->cell2->paragraphStyle);
        $table->addCell($tcStyle->col3Width, $tcStyle->header->cell3->cellStyle)->addText('Description and Features', $tcStyle->header->cell3->fontStyle, $tcStyle->header->cell3->paragraphStyle);
        $table->addCell($tcStyle->col4Width, $tcStyle->header->cell4->cellStyle)->addText('Quantity', $tcStyle->header->cell4->fontStyle, $tcStyle->header->cell4->paragraphStyle);

        /* @var $quoteDeviceGroupDevice Quotegen_Model_QuoteDeviceGroupDevice */
        foreach ($quoteDeviceGroup->getQuoteDeviceGroupDevices() as $quoteDeviceGroupDevice)
        {
            if ($quoteDeviceGroupDevice->quantity > 0)
            {
                $device = $quoteDeviceGroupDevice->getQuoteDevice();
                $table->addRow($tcStyle->device->rowheight);
                // Device Name
                $table->addCell($tcStyle->col1Width, $tcStyle->device->cell1->cellStyle)->addText($device->name, $tcStyle->device->cell1->fontStyle, $tcStyle->device->cell1->paragraphStyle);
                // SKU
                $table->addCell($tcStyle->col2Width, $tcStyle->device->cell2->cellStyle)->addText($device->getReportSku(), $tcStyle->device->cell2->fontStyle, $tcStyle->device->cell2->paragraphStyle);
                // Description and features
                $table->addCell($tcStyle->col3Width, $tcStyle->device->cell3->cellStyle);
                // Quantity
                $table->addCell($tcStyle->col4Width, $tcStyle->device->cell4->cellStyle)->addText(number_format($quoteDeviceGroupDevice->quantity), $tcStyle->device->cell4->fontStyle, $tcStyle->device->cell4->paragraphStyle);
                // Get quote device options
                $quoteDeviceOptions = $quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions();

                /* @var $quoteDeviceOption Quotegen_Model_QuoteDeviceOption */
                foreach ($quoteDeviceOptions as $quoteDeviceOption)
                {
                    $table->addRow($tcStyle->option->rowheight);
                    $table->addCell($tcStyle->col1Width, $tcStyle->option->cell1->cellStyle)->addText($quoteDeviceOption->name . ' (' . number_format($quoteDeviceOption->quantity) . 'x)', $tcStyle->option->cell1->fontStyle, $tcStyle->option->cell1->paragraphStyle);
                    $table->addCell($tcStyle->col2Width, $tcStyle->option->cell2->cellStyle)->addText($quoteDeviceOption->getReportSku(), $tcStyle->option->cell2->fontStyle, $tcStyle->option->cell2->paragraphStyle);
                    $table->addCell($tcStyle->col3Width, $tcStyle->option->cell3->cellStyle)->addText($quoteDeviceOption->description, $tcStyle->option->cell3->fontStyle, $tcStyle->option->cell3->paragraphStyle);
                    $table->addCell($tcStyle->col4Width, $tcStyle->option->cell4->cellStyle)->addText('');
                }
            }
        }

        // Show subtotal line
        $groupCount++;
        $table->addRow($tcStyle->subtotal->rowheight);
        $table->addCell($tcStyle->span23Width, $tcStyle->subtotal->cell2->cell2Span3)->addText(sprintf('Subtotal for group %1$s', number_format($groupCount)), $tcStyle->subtotal->cell2->fontStyle, $tcStyle->subtotal->cell2->paragraphStyle);
        $table->addCell($tcStyle->cell4Width, $tcStyle->subtotal->cell3->cellStyle)->addText($this->currency($quoteDeviceGroup->calculateGroupSubtotal()), $tcStyle->subtotal->cell3->fontStyle, $tcStyle->subtotal->cell3->paragraphStyle);

        $section->addTextBreak();
    }
}

$table = $section->addTable($tcStyle->tablestyle);

// Show page overage rate for monochrome and color
$table->addRow($tcStyle->pages->rowheight);
$table->addCell($tcStyle->span123Width, $tcStyle->pages->cell1->cellStyle)->addText('Monochrome Page Overage Rate', $tcStyle->pages->cell1->fontStyle, $tcStyle->pages->cell1->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->pages->cell2->cellStyle)->addText($this->formatCostPerPage($quote->calculateMonochromeOverageRatePerPage()), $tcStyle->pages->cell2->fontStyle, $tcStyle->pages->cell2->paragraphStyle);
$table->addRow($tcStyle->pages->rowheight);
$table->addCell($tcStyle->span123Width, $tcStyle->pages->cell1->cellStyle)->addText('Color Page Overage Rate', $tcStyle->pages->cell1->fontStyle, $tcStyle->pages->cell1->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->pages->cell2->cellStyle)->addText($this->formatCostPerPage($quote->calculateColorOverageRatePerPage()), $tcStyle->pages->cell2->fontStyle, $tcStyle->pages->cell2->paragraphStyle);

// Show monthly total
$table->addRow($tcStyle->monthlyTotal->rowheight);
$table->addCell($tcStyle->span123Width, $tcStyle->monthlyTotal->cell1->purchaseTotal)->addText('Purchase Total', $tcStyle->monthlyTotal->cell1->fontStyle, $tcStyle->monthlyTotal->cell1->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->monthlyTotal->cell2->cellStyle)->addText($this->currency($this->quote->calculateQuoteSubtotal()), $tcStyle->monthlyTotal->cell2->fontStyle, $tcStyle->monthlyTotal->cell2->paragraphStyle);

$section->addTextBreak();
$section->addText('This quote is valid for 7 days from the date on the cover of this document. Depending on your requirements, you may be subject to additional charges for installation, insurance, and documentation fees. Please review the contract for details.');
