<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\TonerConfigModel;

$assessmentViewModel = $this->assessmentViewModel;

$customerCostPerPageSetting = $assessmentViewModel->getCostPerPageSettingForCustomer();
$deviceInstances            = $assessmentViewModel->getMonthlyHighCostPurchasedDevice($customerCostPerPageSetting);
?>

<div class="container landscape cost-analysis" id="htmlReportContainer">
    <h2 class="reportTitle"><?= My_Brand::getDealerBranding()->customerCostAnalysisTitle ?></h2>
    <br />

    <p><strong>Average Monochrome CPP:</strong>
        <?= $this->formatCostPerPage($assessmentViewModel->calculateCustomerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage); ?>
    </p>

    <p><strong>Average Color CPP:</strong>
        <?= $this->formatCostPerPage($assessmentViewModel->calculateCustomerWeightedAverageMonthlyCostPerPage()->colorCostPerPage); ?>
    </p>

    <table class="mainTable">
        <tr>
            <th>Device Name</th>
            <th>% Of Monthly Cost</th>
            <th>Monochrome AMPV</th>
            <th>Color AMPV</th>
            <th>Black CPP</th>
            <th>Color CPP</th>
            <th>Estimated Monthly Cost</th>
        </tr>

        <?php foreach ($deviceInstances as $deviceInstance) : ?>
            <?php
            $isColor              = ($deviceInstance->getMasterDevice()->tonerConfigId != TonerConfigModel::BLACK_ONLY) ? true : false;
            $percentOfMonthlyCost = ($assessmentViewModel->calculateTotalMonthlyCost() > 0) ? number_format($deviceInstance->calculateMonthlyCost($customerCostPerPageSetting) / $assessmentViewModel->calculateTotalMonthlyCost() * 100, 2) : 0;
            ?>
            <tr>
                <td><?= $deviceInstance->getDeviceName(); ?></td>
                <td class='number'><?= $percentOfMonthlyCost; ?>%</td>
                <td class='number'><?= $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
                <td class='number'><?= ($isColor) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : ' - '; ?></td>
                <td class='number cpp'><?= $this->formatCostPerPage($deviceInstance->calculateCostPerPage($customerCostPerPageSetting)->getCostPerPage()->monochromeCostPerPage); ?></td>
                <td class='number cpp'><?= ($isColor) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($customerCostPerPageSetting)->getCostPerPage()->colorCostPerPage) : ' - '; ?></td>
                <td class='number'><?= $this->currency($deviceInstance->calculateMonthlyCost($customerCostPerPageSetting)); ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>