<?php 

/* @var $form Quotegen_Form_QuoteSetting */
$form = $this->element;

$formElements = array ();
$formElements[] = 'clientDisplayName';
$formElements[] = 'quoteDate';
$formElements[] = 'pricingConfigId';
$formElements[] = 'pageCoverageMonochrome';
$formElements[] = 'pageCoverageColor';
$formElements[] = 'leasingSchemaId';
$formElements[] = 'leasingSchemaTermId';
$formElements[] = 'serviceCostPerPage';
$formElements[] = 'adminCostPerPage';
$this->headScript()->captureStart(); 
?>

$(function() 
{
	$('#leasingSchema').change(function()
	{
		var value = this.value;
		$('#leasingSchemaTermId').empty().attr('disabled', 'disabled');
		if (value != 0)
		{
    		$.ajax(
    		{
    		    url:'<?php echo $this->url(array('format' => 'json', 'action' => 'leasing-schema-terms')); ?>/leasingSchemaId/' + value,
    		    success: function(data) 
    		    {
    		         var terms = data['leasingSchemaTerms'];
    		         var html = '';
    		         var len = terms.length;
    		         for (var i = 0; i < len; i++)
    		         {
    		             html += '<option value="' + terms[i].id + '">' + terms[i].months + ' Months</option>';
    		         }
    		         $('#leasingSchemaTermId').append(html);
    		         $('#leasingSchemaTermId').removeAttr('disabled');
    		    },
    		    error: function (data) 
    		    {
                    alert('Error Occured!');
    		    }
    		});
		}
	});
});

<?php $this->headScript()->captureEnd(); ?>
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
<?php echo $form->getElement('clientId'); ?>
<?php echo $form->getElement('quoteType'); ?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse1"> Other Options </a>
        </div>
        <div id="collapse1" class="accordion-body collapse">
            <div class="accordion-inner">    
            	<?php foreach ($formElements as $element) : ?>
	            	<?php echo $form->getElement($element); ?>
            	<?php endforeach ?>            
            </div>
        </div>
    </div>
</div>
<div class="form-actions">
	<input type="submit" name="saveAndContinue" value="Create Quote" class="btn btn-primary"/>
</div>
</form>