<?php 

/* @var $form Quotegen_Form_QuoteSetting */
$form = $this->element;

?>
<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
<?php echo $form->getElement('clientId'); ?>
<?php echo $form->getElement('quoteType'); ?>

<div class="form-actions">
	<input type="submit" name="saveAndContinue" value="Create Quote" class="btn btn-primary"/>
</div>
</form>