<?php
/**
 * Solution - Evaluating the True Cost of MPS Contracts and Copier Leases
 */
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $quote Quotegen_Model_Quote */
$quote = $this->quote;


$section->addTitle('Lorem Ipsum', 1);

$section->addText('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a metus eget nulla pretium tincidunt nec eu felis. Quisque pharetra sagittis aliquet. Sed tempus, augue sed consectetur rutrum, lacus urna rhoncus nisi, volutpat imperdiet nisi dolor a tellus. Morbi sollicitudin, ante et mattis eleifend, arcu lacus blandit justo, sed lobortis orci ligula ut risus. Cras eu eros lorem. Nam tempor, lectus in imperdiet venenatis, elit quam semper ante, sit amet ornare nisl lectus eu mi. Nam egestas eros sed diam tincidunt sollicitudin. Donec gravida arcu eu nisl sodales sollicitudin. Donec placerat orci vitae risus tincidunt aliquet. Aliquam adipiscing interdum lectus ut tempor. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi at facilisis quam.');
$section->addTextBreak();
$section->addText('Duis porta enim eu justo fermentum et volutpat odio congue. Cras dapibus sapien mattis nisi hendrerit et sodales urna mollis. Nunc et leo turpis, eget aliquam elit. Quisque sit amet nisi metus, sit amet dapibus diam. Nullam accumsan laoreet nulla molestie vulputate. Donec sem purus, luctus nec rhoncus quis, mattis vitae tellus. Maecenas nibh urna, luctus ac commodo a, dignissim at nibh. Etiam cursus auctor vestibulum. Donec sagittis risus non odio pellentesque a ultrices augue vulputate. Proin ut ligula et eros placerat imperdiet. Vestibulum tristique porta placerat. Donec ac nunc a metus rhoncus rutrum quis quis tellus. Cras blandit purus sit amet risus vestibulum feugiat. Curabitur aliquet mi sed augue dictum a tincidunt mi aliquet. Mauris eleifend elementum erat, ut interdum neque blandit fermentum.');
$section->addTextBreak();
$section->addText('Vestibulum volutpat enim sit amet ipsum molestie rutrum. Vestibulum tempus velit risus, nec tristique ligula. Vestibulum adipiscing diam at justo laoreet sit amet laoreet enim feugiat. Integer ac purus in ligula malesuada laoreet. Nulla sollicitudin magna non lectus consequat sit amet egestas mauris hendrerit. Nam nulla eros, congue eget fringilla id, ultricies eu tortor. Proin posuere feugiat diam vitae vestibulum. Quisque sed diam ante, et viverra risus. In varius malesuada justo, id blandit eros fringilla eget. Aenean ullamcorper tellus sed ipsum sagittis sit amet consectetur augue laoreet. In ultrices ullamcorper nisi eget pretium. Vivamus consectetur nibh suscipit mi tincidunt auctor. Suspendisse non blandit turpis. Etiam massa tortor, faucibus at blandit id, tincidunt quis eros. Donec dapibus, lacus at posuere tincidunt, ante nunc aliquet metus, sit amet congue arcu arcu vitae turpis.');
$section->addTextBreak();
$section->addText('Curabitur diam ligula, ultrices tincidunt dignissim sed, feugiat rhoncus libero. Maecenas ultricies hendrerit urna sit amet porta. Sed varius fringilla mollis. Nulla tincidunt vehicula est vitae luctus. Curabitur vulputate nibh nec tellus volutpat sit amet tincidunt felis ultrices. Maecenas dignissim tellus at nulla hendrerit consectetur. Aenean cursus, odio sit amet semper fermentum, dolor diam sagittis libero, dignissim faucibus justo dolor ac dolor. Morbi nec leo sit amet felis dictum viverra. Proin commodo congue egestas. Curabitur sodales lorem ut velit posuere egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus ornare eleifend suscipit.');