<?php
/**
 * Assessment Title Page
 */
/* @var $phpword PHPWord */
$phpword = $this->phpword;
/* @var $quote Quotegen_Model_Quote */
$quote = $this->quote;

/* @var $titlePage PHPWord_Section */
$titlePage       = $this->section;
$titleImageStyle = array(
    'align' => 'center'
);

// Table to fix the issue of images being different sizes
$imageTable = $titlePage->addTable(array(
    'borderBottomSize' => 1
));
$imageTable->addRow(5760);
$cell = $imageTable->addCell(9028.8, array(
    'valign' => 'center'
));
$cell->addImage($this->theme("img/report_logo.png", true), array('align' => 'center'));

$titlePage->addTextBreak();
// Assessment Title
$titlePage->addText('', null, 'titleStyle2');
$titlePage->addText(sprintf('  %1$s Hardware Quote', 'titlepage_title', 'titleStyle2'), My_Brand::$brandName);
$titlePage->addText('', null, 'titleStyle2');


$client = $quote->getClient();

$titlePage->addTextBreak();

$titlePage->addText(' ', 'titlepage_address', 'titleStyle3');
$titlePage->addText(sprintf('Prepared For: %1$s', $client->companyName), 'titlepage_subtitle', 'titleStyle3');

// Parse the address
$addressLines = explode("\n", $client->getAddress()->getFullAddressMultipleLines());
$addressCount = 1;
foreach ($addressLines as $line)
{
    $titlePage->addText($line, 'titlepage_address', 'titleStyle3');
    $addressCount++;
}