<?php 
$quote = $this->quote; /* @var $quote Quotegen_Model_Quote */
$this->placeholder('ProgressionNav')->set($this->render('_partials/quoteHeading.phtml'));
?>
<div class="row">
    <div class="span12">
        <form method="POST">
       <div class="clearfix">
           <div class="pull-right"><input type="submit" name="update" value="Save and Recalculate" class="btn" /></div>
       </div>
       <br>
        <div>
            <table class="quoteDevices">
                <thead>
                    <tr>
                        <th colspan="6"></th>
                        <th colspan="2" class="leasedColumn">Leased Quotes Only</th>
                    </tr>
                    <tr>
                        <th>QTY</th>
                        <th>Device</th>
                        <th>Package Cost</th>
                        <th>Margin</th>
                        <th>Package Price</th>
                        <th>Subtotal</th>
                        <th class="leasedColumn">Residual</th>
                        <th class="leasedColumn">Monthly Payment</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($quote->getQuoteDevices() as $quoteDevice) : /* @var $quoteDevice Quotegen_Model_QuoteDevice */ ?>
                    <tr class="deviceRow">
                        <td><input type="text" name="quantity" value="<?php echo $quoteDevice->getQuantity(); ?>" class="span1" /></td>
                        <td><?php echo $quoteDevice->getName(); ?>
                            <?php if (count($quoteDevice->getQuoteDeviceOptions()) > 0) : ?>
                            <ul>
                            <?php foreach ($quoteDevice->getQuoteDeviceOptions() as $quoteDeviceOption) : /* @var $quoteDeviceOption Quotegen_Model_QuoteDeviceOption */ ?>
                                <li><?php echo $quoteDeviceOption->getTotalQuantity(); ?> x <?php echo $quoteDeviceOption->getName(); ?></li>
                            <?php endforeach; ?>
                            </ul>
                            <?php endif; ?>
                        </td>
                        <td><?php echo $this->currency($quoteDevice->calculatePackageCost()); ?></td>
                        <td><input type="text" name="margin" class="span1" value="<?php echo $quoteDevice->getMargin(); ?>" /></td>
                        <td><input type="text" name="packageCost" value="<?php echo $quoteDevice->getPackagePrice(); ?>" class="span2" /></td>
                        <td><?php echo $this->currency($quoteDevice->calculateSubTotal()); ?></td>
                        <td class="leasedColumn"><input type="text" name="residual" class="span1" value="<?php echo $quoteDevice->getResidual(); ?>" /></td>
                        <td class="leasedColumn">$149.99(*fake)</td>
                    </tr>
                    
                    
                    
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        </form>
    </div>
</div>
<div class="well">
    <form method="POST" class="form-center-actions">
        <div class="form-actions">
            <input type="submit" name="back" value="Go Back" class="btn"/>
            <input type="submit" name="save" value="Save" class="btn btn-success"/>
            <input type="submit" name="saveAndContinue" value="Save &amp; Continue" class="btn btn-primary"/>
        </div>
    </form>
</div>