<?php 
$quote = $this->quote; /* @var $quote Quotegen_Model_Quote */
$this->placeholder('ProgressionNav')->set($this->render('_partials/quoteHeading.phtml'));

$this->headScript()->appendScript("$('i').popover();");

?>
<div class="row">
    <div class="span12">
        <div class="clearfix">
            <div class="pull-right">
                <p>REMEMBER TO ADD SAVE AND RECALC HERE?</p>
            </div>
        </div>
        <?php foreach ($quote->getQuoteDevices() as $quoteDevice) : /* @var $quoteDevice Quotegen_Model_QuoteDevice */ ?>
        <hr>
            <table class="table table-condensed table-bordered table-striped quoteDeviceTable">
                <tr class="header-row">
                    <th>Device</th>
                    <th>Pages</th>
                    <th>Package Cost</th>
                    <th>Margin</th>
                    <th>Package Price</th>
                    <th style="width:60px;">Quantity</th>
                    <th style="width: 90px;">Subtotal</th>
                </tr>
                <tr>
                    <td><h4><?php echo $quoteDevice->getName(); ?><br><small><?php echo $quoteDevice->getSku(); ?></small></h4>
                        <?php if (count($quoteDevice->getQuoteDeviceOptions()) > 0) : ?>
                        <ul>
                        <?php foreach ($quoteDevice->getQuoteDeviceOptions() as $quoteDeviceOption) : /* @var $quoteDeviceOption Quotegen_Model_QuoteDeviceOption */ ?>
                            <li><?php echo $quoteDeviceOption->getTotalQuantity(); ?> x <?php echo $quoteDeviceOption->getName(); ?></li>
                        <?php endforeach; ?>
                        </ul>
                        <?php endif; ?>
                    </td>
                    <td>Insert ability to edit pages here</td>
                    <th><?php echo $this->currency($quoteDevice->calculatePackageCost()); ?></th>
                    <th><?php echo number_format($quoteDevice->getMargin(), 2); ?>%</th>
                    <th><?php echo $this->currency($quoteDevice->getPackagePrice()); ?></th>
                    <th><?php echo $quoteDevice->getQuantity(); ?></th>
                    <th><?php echo $this->currency($quoteDevice->calculateSubtotal()); ?></th>
                </tr>
            </table>
        <?php endforeach; ?>
    </div>
</div>
<div class="well">
    <form method="POST" class="form-center-actions">
        <div class="form-actions">
            <input type="submit" name="back" value="Go Back" class="btn"/>
            <input type="submit" name="save" value="Save" class="btn btn-success"/>
            <input type="submit" name="saveAndContinue" value="Save &amp; Continue" class="btn btn-primary"/>
        </div>
    </form>
</div>
