<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
?>
<div class="h1">3 Smart Steps to Success with Managed Print</div>
<p style="margin-bottom: 15pt;"><?php echo $this->companyName;?> has been managing print for our customers since the beginning. Sourcing and delivering printers and supplies is our mainstay and we've been taking care of business for 25 years. Our full service MPS program was designed to manage and support your printing environment, based on your unique office printing needs.</p>
<p style="margin-bottom: 10pt;">The <?php echo $this->companyName;?> MPS program empowers you to:</p>
<ul>
    <li>Accurately identify printing costs</li>
    <li>Control expenses and budget for future needs</li>
    <li>Increase your working capital by reducing supplies inventory</li>
    <li>Free IT from print related issues</li>
    <li>Choose to keep your existing assets or obtain new hardware from a choice of manufacturers</li>
    <li>Leverage Copy & Print Depot in our 1,100+ stores nationwide for a Total Print Solution</li>
    <li>Improve productivity and user satisfaction</li>
    <li>Foster your eco-smart objectives</li>
</ul>
<div class="pheader">Step 1: Assess</div>
<p>This complimentary <?php echo $this->brandName; ?> Smart Assessment will help us determine what your needs are for office print. By combining data collected from your printing devices with questionnaire responses, we can determine what is working and what isn't in your office print environment. From this information, we can build a managed print solution that meets your business needs.</p>
<div class="pheader">Step 2: Optimize</div>
<p><strong>Increase Hardware Efficiency: </strong>Whether you choose to maintain your existing printer fleet or refresh inefficient devices, your managed print program delivers benefits that meet your specific needs. We will make sure your printing equipment meets your needs and help you optimize the placement of your equipment to make sure you are getting the most out of your assets.</p>
<p><strong>Just-in-Time Supplies & Efficient Service: </strong>Our just-in-time supplies fulfillment and 4-hour response repair service will get you the supplies and service you need, when you need it. By remotely monitoring your printers, we can help you minimize downtime and reduce the amount of working capital held in supplies inventory. Next-day service is available for all printers under a managed print contract so your IT staff will be free from handling printer-related issues.</p>
<p><strong>Single Contact, Single Invoice: </strong>Forget dealing with multiple vendors and receive one invoice for all of your managed printers-this includes either service and supplies on a per-page rate, or hardware, service and supplies on a flat monthly rate. Either way, you will be able to budget for printing with predictable expenses.</p>
<p><strong>Eco Smart Solutions: </strong><?php echo $this->companyName;?> was recognized by Newsweek as the No. 1 green retailer, and we can help you reduce your environmental impact and achieve your sustainability goals. </p>
<div class="pheader">Step 3: Manage</div>
<p>Ongoing management of your print environment enables you to focus on your core business, while we take care of print. By monitoring your print environment on an ongoing basis, we can help you decide if and when your managed print strategy needs to be updated to accommodate new needs.</p>

<div class="pheader">Potential Savings with <?php echo $this->reportName; ?></div>
<p><?php echo $this->companyName;?> can manage your existing printing devices that are not currently on a lease with another vendor. Note that while we have included all of your purchased equipment in the following calculations, not all of them may qualify for managed print services or just-in-time supplies fulfillment. Please refer to the <?php echo $this->reportName; ?> Your Solution document for a complete list of qualified devices.</p>
<br />
<table cellspacing="0" style="font-size: 10pt;">
    <tr>
        <td style="width: 565px;" class="bold">Estimated Costs: Printing Devices Managed with <?php echo $this->reportName; ?>;</td>
        <td style="width: 80px;" class="right">&nbsp;</td>
    </tr>
    <tr>
        <td><?php echo $this->reportName; ?> monochrome cost per page</td>
        <td class="right">$<?php echo number_format($proposal->getMPSBlackAndWhiteCPP(), 5); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->reportName; ?> color cost per page</td>
        <td class="right">$<?php echo number_format($proposal->getMPSColorCPP(), 5); ?></td>
    </tr>
    <tr>
        <td>Predicted annual monochrome pages</td>
        <td class="right"><?php echo number_format($proposal->getPageCounts()->Purchased->BlackAndWhite->Yearly); ?></td>
    </tr>
    <tr>
        <td>Predicted annual color pages</td>
        <td class="right"><?php echo number_format($proposal->getPageCounts()->Purchased->Color->Yearly); ?></td>
    </tr>
    <tr>
        <td>Cost of monochrome pages</td>
        <td class="right">$<?php echo number_format($proposal->getPageCounts()->Purchased->BlackAndWhite->Yearly * $proposal->getMPSBlackAndWhiteCPP()); ?></td>
    </tr>
    <tr>
        <td>Cost of color pages</td>
        <td class="right">$<?php echo number_format($proposal->getPageCounts()->Purchased->Color->Yearly * $proposal->getMPSColorCPP()); ?></td>
    </tr>
    <tr>
        <td>Annual internal administration cost<br/><em>Processing 1 invoice/month @ $<?php echo $proposal->getCostOfExecutingSuppliesOrder(); ?>/invoice</em></td>
        <td class="right">$<?php echo number_format($proposal->getInternalAdminCost()) ?></td>
    </tr>
    <tr>
        <td>Annual cost of external service<br/><em>Maintenance kits and parts are included</em></td>
        <td class="right">Included</td>
    </tr>
    <tr>
        <td>Annual cost of internal IT supporting printing devices<br/><em>Assume reduction of 50%</em></td>
        <td class="right">$<?php echo number_format($proposal->getAnnualITCost() * 0.5);?></td>
    </tr>
    <tr>
        <td>Annual cost of new hardware purchases<br/><em>Assume no change</em></td>
        <td class="right">$<?php echo number_format($proposal->getAnnualCostOfHardwarePurchases());?></td>
    </tr>
    <tr>
        <td class="bold topborder"><?php echo $this->reportName; ?> estimated annual cost of purchased devices</td>
        <td class="right bold topborder">$<?php echo number_format($proposal->getPrintIQTotalCost());?></td>
    </tr>
    <tr>
        <td class="bold topborder">Current estimated annual cost of purchased devices</td>
        <td class="right bold topborder">$<?php echo number_format($proposal->getTotalPurchasedAnnualCost());?></td>
    </tr>
    <tr>
        <td class="bold topborder">POTENTIAL ANNUAL SAVINGS USING <?php echo $this->reportName; ?></td>
        <td class="right bold topborder">$<?php echo number_format($proposal->getPrintIQSavings());?></td>
    </tr>
</table>
<br />

<p>Whether you are looking for a comprehensive managed print services plan that includes new equipment,
or are looking for assistance in maintaining your existing printer fleet, we can design a solution that meets
your specific business needs. Let us take care of your print so you can get back to business.</p>
<br />