<div class="page-header">
    <h1>Leasing Rates - <small>Lease Management</small></h1>
</div>
<div class="clearfix">
    <a class="btn btn-success pull-right btn-small create-button" href="<?php echo $this->url(array('action' => 'create')) ?>">
        <i class="icon-white icon-plus-sign"></i> Create new</a>
</div>
<?php if (isset($this->leasingSchemas) && count($this->leasingSchemas) > 0) : ?>
    <table class="table table-striped table-condensed table-bordered">
        <thead>
        <tr>
            <th style="width:200px;">Id</th>
            <th style="width:200px;">Name</th>
            <th style="width:405px;">Dealer Name</th>
            <th >Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->leasingSchemas as $leasingSchema) : /* @var $user Application_Model_User */ ?>
            <tr>
                <td><?php echo $leasingSchema->id; ?></td>
                <td><?php echo $leasingSchema->name; ?></td>
                <td><?php echo Admin_Model_Mapper_Dealer::getInstance()->find($leasingSchema->dealerId)->dealerName; ?></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-warning btn-mini" title="Edit Leasing Rate" href="<?php echo $this->url( array ( 'action' => 'view', 'leasingSchemaId' => $leasingSchema->id))?>" ?><i class="icon-pencil"></i></a>
                        <a class="btn btn-danger btn-mini" title="Delete Leasing Rate" href="<?php echo $this->url( array ( 'action' => 'delete', 'leasingSchemaId' => $leasingSchema->id))?>" ?><i class="icon-trash"></i></a>
                        <a class="btn btn-primary btn-mini" title="Update Leasing Rate" href="<?php echo $this->url( array ( 'action' => 'edit', 'leasingSchemaId' => $leasingSchema->id))?>" ?><i class="icon-cog"></i></a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <h1>There are no Leasing Schemas</h1>
<?php endif; ?>