<?php
/**
 * Solution - Solution 1: PrintIQ®
 */
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;

/**
 * Variables
 */
$listParagraphStyle = array (
    'spaceAfter' => 80 
);

/**
 * Section Start
 */
$section->addPageBreak();
$section->addTitle($this->translate('Solution 1: PrintIQ®'), 1);
$section->addText($this->translate('Get the most out of your existing printing assets with the PrintIQ® program. Office Depot will take over the management of your current printing equipment and wrap your supplies and service into a single invoice.'));

$section->addTitle($this->translate('Program Components'), 2);
$section->addText($this->translate('Pay by the page with the PrintIQ® program:'));
$section->addListItem(sprintf($this->translate('$%1$s for monochrome pages'), $this->NumberFormat($proposal->getMPSBlackAndWhiteCPP(), 8)), 0, 'bold_text', null, $listParagraphStyle);
$section->addListItem(sprintf($this->translate('$%1$s for color pages'), $this->NumberFormat($proposal->getMPSColorCPP(), 8)), 0, 'bold_text', null, $listParagraphStyle);
$section->addListItem($this->translate('Includes supplies and service for your existing equipment'), 0, 'bold_text', null, $listParagraphStyle);

$section->addText($this->translate('The PrintIQ® program uses remote monitoring software to provide you with:'));
$section->addListItem($this->translate('Just-in-time supplies fulfillment'), 0, null, null, $listParagraphStyle);
$section->addListItem($this->translate('Efficient maintenance and break-fix service'), 0, null, null, $listParagraphStyle);
$section->addListItem($this->translate('Monthly business intelligence reports'), 0, null, null, $listParagraphStyle);

$section->addTitle($this->translate('Estimated Annual Savings'), 2);
$section->addText($this->translate('Based on information from your PrintIQ® Smart Assessment, we have estimated your annual cost savings:'));

// FIXME: Insert Table
$tc = $this->styles->tables->estimatedAnnualSavings;
$table = $section->addTable($tc->tablestyle);
$table->addRow($tc->header->rowheight);
$cell = $table->addCell($tc->headerCol1Width, $tc->header->cell1->cellStyle, 2)->addText($this->translate('Current Scenario'), $tc->header->cell1->fontStyle, $tc->header->cell1->paragraphStyle);
$cell = $table->addCell($tc->headerCol2Width, $tc->header->cell2->cellStyle, 2)->addText($this->translate('Proposed Scenario'), $tc->header->cell2->fontStyle, $tc->header->cell2->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('Ink and toner'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('$' . number_format($this->proposal->CostOfInkAndToner), $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText($this->translate('Monochrome cost per page'), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText('$' . number_format($this->proposal->MPSBlackAndWhiteCPP, 4), $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('Executing supplies orders'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('$' . number_format($this->proposal->CostOfExecutingSuppliesOrders), $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText($this->translate('Color cost per page'), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText('$' . number_format($this->proposal->MPSColorCPP, 4), $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('External service'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('$' . number_format($this->proposal->AnnualCostOfOutSourcing), $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText($this->translate('Estimated monochrome pages'), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText(number_format($this->proposal->getPageCounts()->Purchased->BlackAndWhite->Yearly), $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('Internal IT support for printers'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('$' . number_format($this->proposal->AnnualITCost), $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText($this->translate('Estimated color pages'), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText(number_format($this->proposal->getPageCounts()->Purchased->Color->Yearly), $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('Hardware purchases'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('$' . number_format($this->proposal->AnnualCostOfHardwarePurchases), $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText($this->translate('Cost of monochrome pages'), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText('$' . number_format($this->proposal->getPageCounts()->Purchased->BlackAndWhite->Yearly * $this->proposal->MPSBlackAndWhiteCPP), $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate(''), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('', $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText($this->translate('Cost of color pages'), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText('$' . number_format($this->proposal->getPageCounts()->Purchased->Color->Yearly * $this->proposal->MPSColorCPP), $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate(''), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('', $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText(sprintf($this->translate('Processing 1 invoice/month @ $%1$s'), number_format($this->proposal->CostOfExecutingSuppliesOrder)), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText('$' . number_format($this->proposal->InternalAdminCost), $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate(''), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('', $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText($this->translate('External service'), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText('Included', $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate(''), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('', $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText($this->translate('Internal IT support for printers'), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText('$' . number_format($this->proposal->AnnualITCost * 0.5), $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate(''), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('', $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->body->cell3->cellStyle)->addText($this->translate('Hardware purchases'), $tc->body->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->body->cell4->cellStyle)->addText('$' . number_format($this->proposal->AnnualCostOfHardwarePurchases), $tc->body->cell4->fontStyle, $tc->body->cell4->paragraphStyle);

// Table Footer
$table->addRow($tc->body->rowheight);
$cell = $table->addCell($tc->col1Width, $tc->footer->cell1->cellStyle)->addText($this->translate('Total Cost'), $tc->footer->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$cell = $table->addCell($tc->col2Width, $tc->footer->cell2->cellStyle)->addText('$' . number_format($this->proposal->TotalPurchasedAnnualCost), $tc->footer->cell2->fontStyle, $tc->body->cell2->paragraphStyle);
$cell = $table->addCell($tc->col3Width, $tc->footer->cell3->cellStyle)->addText($this->translate('Total Cost'), $tc->footer->cell3->fontStyle, $tc->body->cell3->paragraphStyle);
$cell = $table->addCell($tc->col4Width, $tc->footer->cell4->cellStyle)->addText('$' . number_format($this->proposal->PrintIQTotalCost), $tc->footer->cell4->fontStyle, $tc->body->cell4->paragraphStyle);


$section->addText($this->translate('Note that although the page volumes from all of your purchased devices were included in our savings calculations, not all of them may qualify for our managed print services program or just-in-time supplies fulfillment. Volumes from unqualified devices would have to be merged to an existing or new qualified device to be included in the program. Please see the Appendix for a complete printing device list with details on compatibility with the PrintIQ® program.'), 'small_italic_text');

$tc = $this->styles->tables->totalAnnualSavings;
$table = $section->addTable($tc->tablestyle);

$table->addRow($tc->body->rowheight);
$table->addCell($tc->col1Width, $tc->body->cell1->cellStyle)->addText($this->translate('Total annual savings with PrintIQ®'), $tc->body->cell1->fontStyle, $tc->body->cell1->paragraphStyle);
$table->addCell($tc->col2Width, $tc->body->cell2->cellStyle)->addText('$' . number_format($this->proposal->PrintIQSavings), $tc->body->cell2->fontStyle, $tc->body->cell2->paragraphStyle);



// EOF