<?php
/**
 * Cost Analysis - Header information
 *
 * This script contains everything that comes before the big table of
 * information in the cost analysis.
 */
/* @var $section PHPWord_Section */
$section = $this->section;
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
/* @var $profitabiltyDevices Proposalgen_Model_Optimization_Dealer */
$profitabiltyDevices = $this->profitabilityDevices;

$section->addTextBreak();
$section->addText('Device Summary', array('bold' => true, 'size' => 12));

$tcStyle = $this->styles->tables->twocenter;
$imageTable = $section->addTable($tcStyle->tablestyle);
$imageTable->addRow();
$imageTable->addCell($tcStyle->col1Width, $tcStyle->body->cell1)->addImage($this->graphs [0], $tcStyle->image->cell1);
$imageTable->addCell($tcStyle->col2Width, $tcStyle->body->cell2)->addImage($this->graphs [1], $tcStyle->image->cell2);

$section->addTextBreak();