<?php
/**
 * Cost Analysis - Header information
 *
 * This script contains everything that comes before the big table of
 * information in the cost analysis.
 */

/* @var $section PHPWord_Section */
$section = $this->section;
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
$section->addTextBreak();
$section->addText('Suggested Replacement Devices', array('bold' => true, 'size' => 12));

// Table with values
$tcStyle = $this->styles->tables->replacement;
$table = $section->addTable($tcStyle->tablestyle);
// Table header
$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->span5Width, $tcStyle->header->header->cellStyle, 5)->addText('Current', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->span4Width, $tcStyle->header->header->cellStyle, 4)->addText('Replacement', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->span3Width, $tcStyle->header->header->cellStyle, 3)->addText('Statistics', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
// Table sub header
$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->header->sub_header->cellStyle)->addText('Device Name', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->header->sub_header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->header->sub_header->cellStyle)->addText('Mono CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->header->sub_header->cellStyle)->addText('Color CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col5Width, $tcStyle->header->sub_header->cellStyle)->addText('Monthly Cost', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col6Width, $tcStyle->header->sub_header->cellStyle)->addText('Device Name', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col7Width, $tcStyle->header->sub_header->cellStyle)->addText('Mono CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col8Width, $tcStyle->header->sub_header->cellStyle)->addText('Color CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col9Width, $tcStyle->header->sub_header->cellStyle)->addText('Monthly Cost', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col10Width, $tcStyle->header->sub_header->cellStyle)->addText('Mono AMPV', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col11Width, $tcStyle->header->sub_header->cellStyle)->addText('Color AMPV', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col12Width, $tcStyle->header->sub_header->cellStyle)->addText('Cost Delta', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);

// Begin with data rows
$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->collWidth, $tcStyle->body->cell1->odd)->addText('Hewlett-Packard Color LaserJet CM3530 MFP', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->body->cell2->odd)->addText('CNJLB01441 10.12.0.232', $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->body->cell3->odd)->addText('$0.0273', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->body->cell4->odd)->addText('$0.1027', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
$table->addCell($tcStyle->col5Width, $tcStyle->body->cell5->odd)->addText('$873.51', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
$table->addCell($tcStyle->col6Width, $tcStyle->body->cell6->odd)->addText('Hewlett-Packard Color LaserJet 4730mfp', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
$table->addCell($tcStyle->col7Width, $tcStyle->body->cell7->odd)->addText('$0.0732', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
$table->addCell($tcStyle->col8Width, $tcStyle->body->cell8->odd)->addText('$0.0732', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
$table->addCell($tcStyle->col9Width, $tcStyle->body->cell9->odd)->addText('$818.33', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
$table->addCell($tcStyle->col10Width, $tcStyle->body->cell10->odd)->addText('4,625', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
$table->addCell($tcStyle->col11Width, $tcStyle->body->cell11->odd)->addText('7,274', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
$table->addCell($tcStyle->col12Width, $tcStyle->body->cell12->odd)->addText('$55.17', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
?>