<?php
/**
 * Cost Analysis - Header information
 *
 * This script contains everything that comes before the big table of
 * information in the cost analysis.
 */

/* @var $section PHPWord_Section */
$section = $this->section;
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
/* @var $optimizationDevices Proposalgen_Model_Optimization_Dealer */
$optimizationDevices = $this->profitabilityDevices;
$costPerPageSetting   = $proposal->getCostPerPageSettingForDealer();

$section->addTextBreak();
$headerTextRun = $section->createTextRun();
$headerTextRun->addText('Suggested Replacement Devices','titlepageHeaderFont');
$headerTextRun->addText(' (' . count($optimizationDevices->replaced). ' of ' . $optimizationDevices->getDeviceCount() . ')');
$section->addText($headerTextRun,null,array('spaceAfter' => 0));
$costThreshold = number_format($proposal->report->getReportSettings()->costThreshold);
$section->addText("The following devices have been targeted for replacement, either for a monthly cost savings greater than {$costThreshold} or manual replacement.");

// Table with values
$tcStyle = $this->styles->tables->replacement;
$table   = $section->addTable($tcStyle->tablestyle);
// Table header
$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->span5Width, $tcStyle->header->header->cellStyle, 5)->addText('Current', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->span4Width, $tcStyle->header->header->cellStyle, 4)->addText('Replacement', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->span3Width, $tcStyle->header->header->cellStyle, 3)->addText('Statistics', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
// Table sub header
$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->header->sub_header->cellStyle)->addText('Device Name', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->header->sub_header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->header->sub_header->cellStyle)->addText('Mono CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->header->sub_header->cellStyle)->addText('Color CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col5Width, $tcStyle->header->sub_header->cellStyle)->addText('Monthly Cost', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col6Width, $tcStyle->header->sub_header->cellStyle)->addText('Device Name', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col7Width, $tcStyle->header->sub_header->cellStyle)->addText('Mono CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col8Width, $tcStyle->header->sub_header->cellStyle)->addText('Color CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col9Width, $tcStyle->header->sub_header->cellStyle)->addText('Monthly Cost', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col10Width, $tcStyle->header->sub_header->cellStyle)->addText('Mono AMPV', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col11Width, $tcStyle->header->sub_header->cellStyle)->addText('Color AMPV', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col12Width, $tcStyle->header->sub_header->cellStyle)->addText('Cost Delta', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);

// Begin with data rows
foreach ($optimizationDevices->replaced as $device)
{
    $masterDevice      = $device->getMasterDevice();
    $replacementDevice = $device->getReplacementMasterDevice();
    $isColor           = ($masterDevice->tonerConfigId !== Proposalgen_Model_TonerConfig::BLACK_ONLY) ? true : false;
    $style = ($this->cycle(array($tcStyle->body->cell1->even, $tcStyle->body->cell1->odd))->next()->current());


    $table->addRow($tcStyle->body->rowheight);
    $table->addCell($tcStyle->collWidth, $style)->addText($device->getDeviceName(), $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $style)->addText($device->serialNumber . ' ' . $device->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $style)->addText($this->currency($device->calculateCostPerPage($costPerPageSetting)->monochromeCostPerPage, array('precision' => 4)), $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $style)->addText(($isColor) ? $this->currency($device->calculateCostPerPage($costPerPageSetting)->colorCostPerPage, array('precision' => 4)) : 'N/A', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $style)->addText($this->currency($device->calculateMonthlyCost($costPerPageSetting)), $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);
    $table->addCell($tcStyle->col6Width, $style)->addText($replacementDevice->getManufacturer()->fullname . ' ' . $replacementDevice->modelName, $tcStyle->body->cell6->fontStyle, $tcStyle->body->cell6->paragraphStyle);
    $table->addCell($tcStyle->col7Width, $style)->addText($this->currency($replacementDevice->calculateCostPerPage($proposal->getCostPerPageSettingForDealer())->monochromeCostPerPage, array('precision' => 4)), $tcStyle->body->cell7->fontStyle, $tcStyle->body->cell7->paragraphStyle);
    $table->addCell($tcStyle->col8Width, $style)->addText(($isColor) ? $this->currency($replacementDevice->calculateCostPerPage($proposal->getCostPerPageSettingForDealer())->colorCostPerPage, array('precision' => 4)) : 'N/A', $tcStyle->body->cell8->fontStyle, $tcStyle->body->cell8->paragraphStyle);
    $table->addCell($tcStyle->col9Width, $style)->addText($this->currency($device->calculateMonthlyCost($costPerPageSetting, $replacementDevice)), $tcStyle->body->cell9->fontStyle, $tcStyle->body->cell9->paragraphStyle);
    $table->addCell($tcStyle->col10Width, $style)->addText(number_format($device->getAverageMonthlyBlackAndWhitePageCount()), $tcStyle->body->cell10->fontStyle, $tcStyle->body->cell10->paragraphStyle);
    $table->addCell($tcStyle->col11Width, $style)->addText(($isColor) ? number_format($device->getAverageMonthlyColorPageCount()) : 'N/A', $tcStyle->body->cell11->fontStyle, $tcStyle->body->cell11->paragraphStyle);
    $table->addCell($tcStyle->col12Width, $style)->addText($this->currency($device->calculateMonthlyCost($costPerPageSetting) - $device->calculateMonthlyCost($costPerPageSetting, $device->getReplacementMasterDevice())), $tcStyle->body->cell12->fontStyle, $tcStyle->body->cell12->paragraphStyle);
}
?>