<?php
/* @var $form ChangePasswordForm */
use MPSToolbox\Legacy\Modules\DDefault\Forms\ChangePasswordForm;

$form = $this->element;
?>

<?= $this->RenderFormOpen($form, array('form-horizontal')) ?>
<fieldset>
    <div class="form-group <?= ($form->getElement('current_password')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('current_password'), array('col-md-3')) ?>

        <div class="col-md-6 col-lg-4">
            <?= $this->RenderFormPassword($form->getElement('current_password')) ?>
            <?= $this->RenderFormDescription($form->getElement('current_password')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('current_password')) ?>
        </div>
    </div>


    <div class="form-group <?= ($form->getElement('password')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('password'), array('col-md-3')) ?>

        <div class="col-md-6 col-lg-4">
            <?= $this->RenderFormPassword($form->getElement('password')) ?>
            <?= $this->RenderFormDescription($form->getElement('password')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('password')) ?>
        </div>
    </div>


    <div class="form-group <?= ($form->getElement('password_confirm')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('password_confirm'), array('col-md-3')) ?>
        
        <div class="col-md-6 col-lg-4">
            <?= $this->RenderFormPassword($form->getElement('password_confirm')) ?>
            <?= $this->RenderFormDescription($form->getElement('password_confirm')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('password_confirm')) ?>
        </div>
    </div>
</fieldset>

<fieldset>
    <hr>
    <?= $this->RenderFormSubmit($form->getElement('submit'), array('btn', 'btn-primary')) ?>
    <?= $this->RenderFormSubmit($form->getElement('cancel'), array('btn', 'btn-default')) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>
