<?php
use MPSToolbox\Legacy\Modules\DDefault\Forms\ForgotPasswordForm;

/* @var $form ForgotPasswordForm */
$form = $this->element;
?>

<?= $this->RenderFormOpen($form) ?>
<fieldset>
    <div class="form-group <?= ($form->getElement('email')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormEmail($form->getElement('email')) ?>
        <?= $this->RenderFormElementErrors($form->getElement('email')) ?>
    </div>
    <hr>
    <ul class="pager">
        <li class="previous"><?= $this->RenderFormSubmit($form->getElement('cancel'), ['btn btn-default']) ?></li>
        <li class="next"><?= $this->RenderFormSubmit($form->getElement('forgotPassword'), ['btn', 'btn-primary']) ?></li>
    </ul>
</fieldset>
<?= $this->RenderFormClose($form) ?>
