<?php
/* @var $form LoginForm */
use MPSToolbox\Legacy\Modules\DDefault\Forms\LoginForm;

$form = $this->element;
?>

<?= $this->RenderFormOpen($form) ?>
<fieldset>
    <div class="form-group <?= ($form->getElement('email')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormEmail($form->getElement('email')) ?>
        <?= $this->RenderFormElementErrors($form->getElement('email')) ?>
    </div>

    <div class="form-group <?= ($form->getElement('password')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormPassword($form->getElement('password')) ?>
        <?= $this->RenderFormElementErrors($form->getElement('password')) ?>
    </div>
    <hr>
    <?= $this->RenderFormSubmit($form->getElement('login')) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>
