<?php
/* @var $form \MPSToolbox\Legacy\Modules\DDefault\Forms\ResetPasswordForm */
use MPSToolbox\Legacy\Modules\DDefault\Forms\ResetPasswordForm;

$form = $this->element;
?>

<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>
<fieldset>
    <div class="form-group <?= ($form->getElement('password')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('password'), ['col-md-3']) ?>

        <div class="col-md-6 col-lg-4">
            <?= $this->RenderFormPassword($form->getElement('password')) ?>
            <?= $this->RenderFormDescription($form->getElement('password')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('password')) ?>
        </div>
    </div>

    <div class="form-group <?= ($form->getElement('password_confirm')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('password_confirm'), ['col-md-3']) ?>

        <div class="col-md-6 col-lg-4">
            <?= $this->RenderFormPassword($form->getElement('password_confirm')) ?>
            <?= $this->RenderFormDescription($form->getElement('password_confirm')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('password_confirm')) ?>
        </div>
    </div>
</fieldset>

<fieldset>
    <hr>
    <?= $this->RenderFormSubmit($form->getElement('submit'), ['btn', 'btn-primary']) ?>
    <?= $this->RenderFormSubmit($form->getElement('cancel'), ['btn', 'btn-default']) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>
