<div class="subnav" id="selectReportMenu">
    <div class="subnav-affix-container" data-spy="affix" data-offset-top="160">
        <div class="container navbar-container">
            <div class="navbar-form pull-left">
                <div class="btn-group">
                    <form class="form-inline" method="POST" action="<?php echo $this->url(array('action' => 'index', 'controller' => 'report_index')); ?>">
                        <button name="goBack" id="goBack" type="submit" class="btn btn-inverse"><i class="icon-arrow-left icon-white"></i> Go Back</button>
                        <select id="reportNavigator" style='margin-top: 2px;'>
                            <?php foreach ($this->availableReports as $report) : ?>
                            <option value='<?php echo $report->url; ?>' <?php echo ($report->active) ? "selected='selected'" : "";?>><?php echo $report->pagetitle; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </form>
                </div>
            </div>
            <?php if (count($this->formats) > 0) : ?>
            <div class="navbar-form pull-right">
                <div class="btn-group">
                    <?php foreach ($this->formats as $url => $format) : ?>
                    <a class="btn btn-<?php echo $format->btnstyle; ?> downloadButton" href="<?php echo $this->baseUrl($url); ?>" data-ext="<?php echo $format->extension; ?>" data-loadingmessage="<?php echo $format->loadingmessage; ?>"><?php echo $format->name; ?>
                        <i class="icon-download icon-white"></i></a>
                    <?php endforeach; ?>
                </div>

            </div>
            <?php endif;?>
        </div>
    </div>
</div>