<?php
/**
 * Assessment - Report Card
 */

/* @var $phpword PHPWord */
$phpword = $this->phpword;

/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$section->addTitle(sprintf('Your %1$s Smart Assessment', $this->brandName), 1);
$section->addText(sprintf('It can be a challenge to understand your printing needs, and there are many factors to consider: hardware functionality, supplies delivery, service, parts, maintenance kits, IT time spent supporting printers -- and the cost for all of this. This free %1$s Smart Assessment will allow you to make sense of your printing needs and costs. %2$s can help you get your office print under control with our smart and flexible managed print services solutions.', $this->brandName, $this->companyName));

$section->addTitle('Score Card', 2);
$section->addText('Your office printing environment was graded across five categories on a scale of 1 to 10. A score of 1 indicates a low-efficiency or high-cost scenario. A score of 10 indicates a high-efficiency or low-cost scenario. Your results are below:');

$reportCardTable = $section->addTable($this->styles->tables->grades->tablestyle);
$rowHeight       = 800;
// Row 1
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText('Supplies and Service Logistics', 'gradeTitleFont', 'nospacing');
$cell->addText('Management breakdown, efficiency of break-fix service, number of vendors used for print, and number of different models and associated supply types.', null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($assessmentViewModel->getRanking()->getSuppliesAndServiceLogistics()->Rank, 1), 'gradeFont', 'gradeParagraph');

// Row 2
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText('Printing Hardware Usage', 'gradeTitleFont', 'nospacing');
$cell->addText('Total number of printing devices, average print volumes, underused and overused equipment, and color print usage.', null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($assessmentViewModel->getRanking()->getPrintingHardwareUsage()->Rank, 1), 'gradeFont', 'gradeParagraph');

// Row 3
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText('Technology Reliability and User Productivity', 'gradeTitleFont', 'nospacing');
$cell->addText('Age of printing devices, IT time spent managing printers, and availability of technology features that improve workflow and productivity.', null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($assessmentViewModel->getRanking()->getTechnologyReliabilityAndUserProductivity()->Rank, 1), 'gradeFont', 'gradeParagraph');

// Row 4
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText('Environmental Impact', 'gradeTitleFont', 'nospacing');
$cell->addText('Energy consumption from printing hardware and availability of green print technology features.', null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($assessmentViewModel->getRanking()->getEnvironmentalFriendliness()->Rank, 1), 'gradeFont', 'gradeParagraph');

// Row 5
$reportCardTable->addRow($rowHeight);
$cell = $reportCardTable->addCell(8028, $this->styles->tables->grades->cell1);
$cell->addText('Expense', 'gradeTitleFont', 'nospacing');
$cell->addText('Your estimated annual expenses for print-related hardware, supplies, service, and internal support and administration.', null, 'nospacing');
$cell = $reportCardTable->addCell(1000, $this->styles->tables->grades->cell2);
$cell->addText(number_format($assessmentViewModel->getRanking()->getExpense()->Rank, 1), 'gradeFont', 'gradeParagraph');

// Textbreak fix to ensure the tables don't merge into each other
$section->addTextBreak();

$imageTable = $section->addTable();
$imageTable->addRow();
$cell   = $imageTable->addCell(9028, $this->styles->tables->singleimage->cell1);
$graphs = $assessmentViewModel->getGraphs();
$cell->addImage($graphs[0]);

// Textbreak fix to ensure the tables don't merge into each other
$section->addTextBreak();
$savingsTable = $section->addTable($this->styles->tables->savings->tablestyle);
$savingsTable->addRow(720);
$cell = $savingsTable->addCell(9028, $this->styles->tables->savings->cell1);

$textrun = $cell->createTextRun('savingsParagraph');
$textrun->addText(sprintf('Our %1$s program could provide you with annual savings of up to ', $this->brandName), 'savingsFont');
$textrun->addText($this->currency($assessmentViewModel->getPrintIQSavings()), 'savingsAmountFont');
$textrun->addText('.', 'savingsFont');
