<?php
/**
 * Assessment - Analysis: Service and Supplies Logistics
 */

/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

$section->addPageBreak();

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

/* The graphs */
$graphs = $this->graphs;

$section->addTitle('Analysis: Service and Supplies Logistics', 1);

$gradeTable = $section->addTable($this->styles->tables->grades->tablestyle);
$gradeTable->addRow();
$gradeTable->addCell(8028, $this->styles->tables->grades->cell1)->addText($assessmentViewModel->getRanking()->getSuppliesAndServiceLogistics()->RankingText, null, 'nospacing');
$gradeTable->addCell(1000, $this->styles->tables->grades->cell2)->addText(number_format($assessmentViewModel->getRanking()->getSuppliesAndServiceLogistics()->Rank, 1), 'gradeFont', 'gradeParagraph');
$section->addTextBreak();

$section->addTitle('Printing Device Management Breakdown', 2);
$section->addText('Different types of printing devices are managed in different ways. Newer networked printers can be managed with remote monitoring software; leased multifunction devices are typically managed by the vendor who sold the machine; devices not connected to the network, such as inkjets and some older printers, are difficult to manage because you cannot monitor them with software.');

$section->addTextBreak(2);
$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($graphs[1]);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($graphs[2]);
$section->addTextBreak(2);

$inkJetString = 'less than 10%';
if ($assessmentViewModel->getPercentPrintingDoneOnInkjet() == 50)
{
    $inkJetString = 'more than 50%';
}
else if ($assessmentViewModel->getPercentPrintingDoneOnInkjet() == 38)
{
    $inkJetString = '26% to 50%';
}
else if ($assessmentViewModel->getPercentPrintingDoneOnInkjet() == 18)
{
    $inkJetString = '10% to 25%';
}

$textRun = $section->addTextRun();
$textRun->addText('Based on your questionnaire, ');
$textRun->addText(sprintf('%1$s of your printing is done on non-network devices. ', $inkJetString), [
    'bold' => true
]);
$textRun->addText('We did not monitor locally connected printers machines that are not connected to the network, and on average, pages printed to locally connected printers cost three times more than pages printed to network devices. Without being on the network, users also cannot share these devices. There are some instances where desktop printers are appropriate, for instance, if a single user requires confidential, high-convenience printing. We can help you consolidate desktop hardware where appropriate, and where desktop printing is required, we can help you select network-capable equipment so your desktop printing can be managed with the rest of your office print.');
$excludedDeviceCount = count($assessmentViewModel->getExcludedDevices());
if ($excludedDeviceCount > 0)
{
    $section->addTextBreak();
    $section->addText(sprintf('There are %1$s devices not included in the analysis due to lack of data or model information. See the Appendix in the %2$s document for details regarding the excluded device(s).', number_format($excludedDeviceCount), My_Brand::getDealerBranding()->solutionTitle));
}

$section->addTitle('Efficiency of Break-Fix Service', 2);
$section->addText('Based on your questionnaire responses, we discovered the following:');

// Efficiency of Break-Fix Service table
$cellWidths = [
    7500,
    1528
];
$table      = $section->addTable($this->styles->tables->twoColumnDataTable->tablestyle);
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Number of printer repairs per month', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($assessmentViewModel->getNumberOfRepairs()), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Average time between printer breaking down and printer being fixed', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(sprintf('%1$s day(s)', number_format($assessmentViewModel->getAverageTimeBetweenBreakdownAndFix())), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$cell = $table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1);
$cell->addText('Annual downtime resulting from printer breakdowns', 'bold_text', 'nospacing');
$cell->addText('(Based on an 8 hour work day)', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(sprintf('%1$s hour(s)', number_format($assessmentViewModel->getAnnualDowntimeFromBreakdowns())), 'bold_text', 'nospacing_rightalign');
$section->addText(sprintf('%1$s can provide next-day service for your printer fleet.', $this->companyName), 'small_italic_text');

$section->addTitle('Number of Vendors', 2);
$section->addText('Based on your questionnaire responses, we discovered the following:');

// Number of Vendors table
$cellWidths = [
    7500,
    1528
];

$table = $section->addTable($this->styles->tables->twoColumnDataTable->tablestyle);
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Percentage of fleet capable of reporting toner levels', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(sprintf('%1$s %', number_format($assessmentViewModel->calculatePercentageOfFleetReportingTonerLevels(), 2)), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Number of orders for ink and toner executed annually', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($assessmentViewModel->getNumberOfAnnualInkTonerOrders()), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Estimated annual cost of ink and toner orders', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText($this->currency($assessmentViewModel->getCostOfExecutingSuppliesOrders()), 'bold_text', 'nospacing_rightalign');
$section->addText(sprintf('Time spent dealing with multiple vendors could be better spent focusing on your core business tasks. %1$s can bundle your supplies and service into a single invoice - and if you need new hardware, that can be included too.', $this->companyName), 'small_italic_text');

$section->addTitle('Number of Printing Device Models and Supply Types', 2);
$section->addText(sprintf('Out of your %1$s networked printing devices, you have %2$s unique device %3$s. Each section of the chart below represents a single model type. We estimate that %4$s of your printing devices %5$s leased %6$s, for which supplies are included in your contract. The %7$s remaining %8$s of %9$s %10$s and use %11$s %12$s. If you hold two of each supply in inventory, you have an estimated $%13$s in operating cash held in printer supplies inventory at any given time.',
    number_format($assessmentViewModel->getDevices()->allIncludedDeviceInstances->getCount()), //1
    number_format($assessmentViewModel->getNumberOfUniqueModels()), //2
    (number_format($assessmentViewModel->getNumberOfUniqueModels()) == 1) ? 'model' : 'models', //3
    number_format(count($assessmentViewModel->getDevices()->leasedDeviceInstances->getDeviceInstances())), //4
    (number_format(count($assessmentViewModel->getDevices()->leasedDeviceInstances->getDeviceInstances())) == 1) ? 'is a' : 'are', //5
    (number_format(count($assessmentViewModel->getDevices()->leasedDeviceInstances->getDeviceInstances())) == 1) ? 'machine' : 'machines', //6
    number_format(count($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances())), //7
    (number_format(count($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances())) == 1) ? 'machine consists' : 'machines consist', //8
    number_format($assessmentViewModel->getNumberOfUniquePurchasedModels()), //9
    (number_format($assessmentViewModel->getNumberOfUniquePurchasedModels()) == 1) ? 'model' : 'different models', //10
    number_format($assessmentViewModel->getNumberOfUniquePurchasedModels()), //11
    (number_format($assessmentViewModel->getNumberOfUniquePurchasedModels()) == 1) ? 'supply type' : 'different supply types', //12
    number_format($assessmentViewModel->getCashHeldInInventory()))); //13


$imageTable = $section->addTable();
$imageTable->addRow();
$cell = $imageTable->addCell(9028.8, ['valign' => 'center']);

$cell->addImage($graphs[3], [
    'align' => 'center'
]);

$section->addText(sprintf('By using the same supplies for all printing devices, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space required. %1$s can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.', $this->companyName));
