<?php
/**
 * Assessment - Analysis: Service and Supplies Logistics
 */

/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

$section->addPageBreak();

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

/* The graphs */
$graphs = $this->graphs;

$section->addTitle('Analysis: Service and Supplies Logistics', 1);

$gradeTable = $section->addTable($this->styles->tables->grades->tablestyle);
$gradeTable->addRow();
$gradeTable->addCell(8028, $this->styles->tables->grades->cell1)->addText($assessmentViewModel->getRanking()->getSuppliesAndServiceLogistics()->RankingText, null, 'nospacing');
$gradeTable->addCell(1000, $this->styles->tables->grades->cell2)->addText(number_format($assessmentViewModel->getRanking()->getSuppliesAndServiceLogistics()->Rank, 1), 'gradeFont', 'gradeParagraph');
$section->addTextBreak();

$section->addTitle('Printing Device Management Breakdown', 2);
$section->addText('Different types of printing devices are managed in different ways. Newer networked printers can be managed remotely. Devices designated as “Future Consideration” are assumed to be managed by the vendor who sold the machine and therefore will be considered separately within this report. Print volumes for Non-networked devices have been estimated based on your response in the Assessment Questionnaire.');

$section->addTextBreak(2);
$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($graphs[1]);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($graphs[2]);
$section->addTextBreak(2);

$inkJetString = 'less than 10%';
if ($assessmentViewModel->getPercentPrintingDoneOnInkjet() == 50)
{
    $inkJetString = 'more than 50%';
}
else if ($assessmentViewModel->getPercentPrintingDoneOnInkjet() == 38)
{
    $inkJetString = '26% to 50%';
}
else if ($assessmentViewModel->getPercentPrintingDoneOnInkjet() == 18)
{
    $inkJetString = '10% to 25%';
}

$textRun = $section->addTextRun();
$textRun->addText('Based on your questionnaire, ');
$textRun->addText(sprintf('%1$s of your printing is done on non-network devices. ', $inkJetString), [
    'bold' => true
]);
$textRun->addText('We did not monitor locally connected printers machines that are not connected to the network, and on average, pages printed to locally connected printers cost three times more than pages printed to network devices. Without being on the network, users also cannot share these devices. There are some instances where desktop printers are appropriate, for instance, if a single user requires confidential, high-convenience printing. We can help you consolidate desktop hardware where appropriate, and where desktop printing is required, we can help you select network-capable equipment so your desktop printing can be managed with the rest of your office print.');
$excludedDeviceCount = count($assessmentViewModel->getExcludedDevices());
if ($excludedDeviceCount > 0)
{
    $section->addTextBreak();
    $section->addText(sprintf('There are %1$s devices not included in the analysis due to lack of data or model information. See the Appendix in the %2$s document for details regarding the excluded device(s).', number_format($excludedDeviceCount), My_Brand::getDealerBranding()->solutionTitle));
}

$section->addTitle('Efficiency of Break-Fix Service', 2);
$section->addText('Based on your questionnaire responses, we discovered the following:');

// Efficiency of Break-Fix Service table
$cellWidths = [
    7500,
    1528
];
$table      = $section->addTable($this->styles->tables->twoColumnDataTable->tablestyle);
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Number of printer repairs per month', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($assessmentViewModel->getNumberOfRepairs(),1), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Average time between printer breaking down and printer being fixed', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(sprintf('%1$s day(s)', number_format($assessmentViewModel->getAverageTimeBetweenBreakdownAndFix())), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$cell = $table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1);
$cell->addText('Annual downtime resulting from printer breakdowns', 'bold_text', 'nospacing');
$cell->addText('(Based on an 8 hour work day)', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(sprintf('%1$s hour(s)', number_format($assessmentViewModel->getAnnualDowntimeFromBreakdowns())), 'bold_text', 'nospacing_rightalign');
$section->addText(sprintf('%1$s can provide next-day service for your printer fleet.', $this->companyName), 'small_italic_text');

$section->addTitle('Managing Supplies and Service', 2);
$section->addText('Based on your questionnaire responses, we discovered the following:');

// Number of Vendors table
$cellWidths = [
    7500,
    1528
];

$table = $section->addTable($this->styles->tables->twoColumnDataTable->tablestyle);
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Number of Vendors', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($assessmentViewModel->getNumberOfVendors()), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Percentage of fleet capable of reporting toner levels', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(sprintf('%1$s %', number_format($assessmentViewModel->calculatePercentageOfFleetReportingTonerLevels(), 2)), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Number of annual invoices processed for supplies and service management', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($assessmentViewModel->getNumberOfAnnualInkTonerOrders()), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText('Estimated annual administrative cost for supplies and service orders', 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText($this->currency($assessmentViewModel->getCostOfExecutingSuppliesOrders()), 'bold_text', 'nospacing_rightalign');
$section->addText(sprintf('Time spent dealing with multiple vendors could be better spent focusing on your core business tasks. %1$s can combine all of your purchase orders into a single monthly invoice.', $this->companyName), 'small_italic_text');

$section->addTitle('Number of Printing Device Models and Supply Types', 2);
$section->addText(sprintf('Out of your %1$s networked printing devices, you have %2$s unique device %3$s. Each section of the chart below represents a single model type. We assume that %4$s of your printing %6$s %5$s supplies and service included. The %7$s remaining %8$s of %9$s %10$s and use %11$s %12$s. If you hold two of each supply in inventory, you have an estimated $%13$s in operating cash held in printer supplies inventory at any given time.',
    number_format($assessmentViewModel->getDevices()->allIncludedDeviceInstances->getCount()), //1
    number_format($assessmentViewModel->getNumberOfUniqueModels()), //2
    (number_format($assessmentViewModel->getNumberOfUniqueModels()) == 1) ? 'model' : 'models', //3
    number_format(count($assessmentViewModel->getDevices()->leasedDeviceInstances->getDeviceInstances())), //4
    (number_format(count($assessmentViewModel->getDevices()->leasedDeviceInstances->getDeviceInstances())) == 1) ? 'has' : 'have', //5
    (number_format(count($assessmentViewModel->getDevices()->leasedDeviceInstances->getDeviceInstances())) == 1) ? 'machine' : 'machines', //6
    number_format(count($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances())), //7
    (number_format(count($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances())) == 1) ? 'machine consists' : 'machines consist', //8
    number_format($assessmentViewModel->getNumberOfUniquePurchasedModels()), //9
    (number_format($assessmentViewModel->getNumberOfUniquePurchasedModels()) == 1) ? 'model' : 'different models', //10
    number_format($assessmentViewModel->getNumberOfUniquePurchasedModels()), //11
    (number_format($assessmentViewModel->getNumberOfUniquePurchasedModels()) == 1) ? 'supply type' : 'different supply types', //12
    number_format($assessmentViewModel->getCashHeldInInventory()))); //13

$section->addPageBreak();

$imageTable = $section->addTable();
$imageTable->addRow();
$cell = $imageTable->addCell(9028.8, ['valign' => 'center']);
$cell->addImage($graphs[3], ['align' => 'center']);

#--
//HERE IS NEW TABLE
$deviceVendorCount = [];
foreach ($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances() as $device) {
    if (array_key_exists($device->getMasterDevice()->modelName, $deviceVendorCount))  {
        $deviceVendorCount [$device->getMasterDevice()->modelName] += 1;
    } else {
        $deviceVendorCount [$device->getMasterDevice()->modelName] = 1;
    }
}
arsort($deviceVendorCount);

$totalAmount       = $assessmentViewModel->getDevices()->allIncludedDeviceInstances->getCount();
$amountOfRows      = ceil(count($deviceVendorCount) / 2);
//FirstHalf is whether we are writing to the left side of the table or the right side.
$firstColumn  = true;
$colorCounter = 0;
$tableData    = [];
$counter      = 0;

foreach ($deviceVendorCount as $modelName => $deviceCount)
{
    if ($counter < $amountOfRows)
    {
        $tableData[$counter]["column1"] = [
            "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
            "name"    => $modelName . " (" . $deviceCount . ")",
            "percent" => number_format(($deviceCount / $totalAmount) * 100, 1) . "%",
        ];
    }
    else
    {
        $tableData[$counter - $amountOfRows]["column2"] = [
            "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
            "name"    => $modelName . " (" . $deviceCount . ")",
            "percent" => number_format(($deviceCount / $totalAmount) * 100, 1) . "%",
        ];

    }
    $counter++;
}

$cellWidths = [
    500,
    3300,
    400,
    500,
    3300,
    400
];

$uniqueDevicesTable = $section->addTable($this->styles->tables->uniqueDevices->tablestyle);
foreach ($tableData as $row)
{
    $uniqueDevicesTable->addRow();
    if (array_key_exists("column1", $row))
    {
        $cellStyle = $this->styles->tables->uniqueDevices->firstCell;
        $cellStyle = array_merge($cellStyle, ["bgColor" => $row["column1"]["color"]]);
        $uniqueDevicesTable->addCell($cellWidths [0], $cellStyle);
        $uniqueDevicesTable->addCell($cellWidths [1], $this->styles->tables->uniqueDevices->middleCell)->addText($this->translate($row["column1"]["name"], null, null));
        $uniqueDevicesTable->addCell($cellWidths [2], $this->styles->tables->uniqueDevices->middleCell)->addText($row["column1"]["percent"]);
    }
    else
    {
        $uniqueDevicesTable->addCell($cellWidths [0], $this->styles->tables->uniqueDevices->firstCell);
        $uniqueDevicesTable->addCell($cellWidths [1], $this->styles->tables->uniqueDevices->middleCell);
        $uniqueDevicesTable->addCell($cellWidths [2], $this->styles->tables->uniqueDevices->middleCell);
    }

    if (array_key_exists("column2", $row))
    {
        $cellStyle = $this->styles->tables->uniqueDevices->middleCell;
        $cellStyle = array_merge($cellStyle, ["bgColor" => $row["column2"]["color"]]);
        $uniqueDevicesTable->addCell($cellWidths [3], $cellStyle);
        $uniqueDevicesTable->addCell($cellWidths [4], $this->styles->tables->uniqueDevices->middleCell)->addText($this->translate($row["column2"]["name"], null, null));
        $uniqueDevicesTable->addCell($cellWidths [5], $this->styles->tables->uniqueDevices->lastCell)->addText($row["column2"]["percent"]);
    }
    else
    {
        $uniqueDevicesTable->addCell($cellWidths [3], $this->styles->tables->uniqueDevices->middleCell);
        $uniqueDevicesTable->addCell($cellWidths [4], $this->styles->tables->uniqueDevices->middleCell);
        $uniqueDevicesTable->addCell($cellWidths [5], $this->styles->tables->uniqueDevices->lastCell);
    }
}
$section->addTextBreak();
#--

$section->addText(sprintf('By reducing the number of suppliers and the number of unique printing devices, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space required. %1$s can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.', $this->companyName));
