<?php
/**
 * Assessment - Analysis: Printing Hardware Usage
 */

/* @var $phpword \PhpOffice\PhpWord\PhpWord */
$phpword = $this->phpword;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$graphs              = $assessmentViewModel->getGraphs();

$section->addTitle('Analysis: Printing Hardware Usage', 1);

$gradeTable = $section->addTable($this->styles->tables->grades->tablestyle);
$gradeTable->addRow();
$gradeTable->addCell(8028, $this->styles->tables->grades->cell1)->addText($assessmentViewModel->getRanking()->getPrintingHardwareUsage()->RankingText);
$gradeTable->addCell(1000, $this->styles->tables->grades->cell2)->addText(number_format($assessmentViewModel->getRanking()->getPrintingHardwareUsage()->Rank, 1), "gradeFont", "gradeParagraph");

$section->addTextBreak();

$section->addTitle('Print Volume and Number of Printing Devices', 2);
$section->addText(sprintf('You currently have %1$s networked printing %2$s that %3$s an average of %4$s pages each per month, for an average total monthly print volume of %5$s pages. Ideally, you should have the minimum amount of printing hardware required to meet your print demand while maintaining user productivity.',
    number_format($assessmentViewModel->getDevices()->allIncludedDeviceInstances->getCount()), //1
    (number_format($assessmentViewModel->getDevices()->allIncludedDeviceInstances->getCount()) == 1) ? 'device' : 'devices', //2
    (number_format($assessmentViewModel->getDevices()->allIncludedDeviceInstances->getCount()) == 1) ? 'prints' : 'print', //3
    number_format($assessmentViewModel->calculateAveragePagesPerDeviceMonthly()), //4
    $this->formatPageVolume($assessmentViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()))); //5

$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell1)->addImage($graphs [4]);
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell2)->addImage($graphs [5]);
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell3)->addImage($graphs [6]);

$section->addTextBreak();

$section->addTitle('Underused and Overused Printing Devices', 2);
$section->addText(sprintf('Currently, %1$s%% of your printing devices are printing less than one quarter of our recommended monthly print volume, and %2$s%% are printing above our recommended monthly print volume. Our recommended monthly print volumes are equal to the manufacturer\'s stated yield for a single print cartridge (for monochrome devices, the black cartridge, and for color devices, a single color cartridge unless the device is not being used for color).', number_format($assessmentViewModel->getPercentDevicesUnderused()), number_format($assessmentViewModel->getPercentDevicesOverused())));
$section->addText('Underused printing devices can be consolidated or retired to free up floor and desk space, reduce the amount of cash held in unused supplies inventory, and reduce the energy costs associated with powering underused machines. Overused printing devices risk having increased breakdowns and should have a portion of their print volumes moved to underused printers or be replaced with higher-capacity machines.');

$section->addPageBreak();

$cellWidths             = array(
    3611,
    1805,
    1805,
    1805
);
$lowestUtilizationTable = $section->addTable($this->styles->tables->utilization->tablestyle);
$lowestUtilizationTable->addRow(null, $this->styles->tables->rowheader);
$lowestUtilizationTable->addCell($cellWidths [0], $this->styles->tables->utilization->cell1)->addText('Lowest Utilization', 'bold_text', 'nospacing_centeralign');
$lowestUtilizationTable->addCell($cellWidths [1], $this->styles->tables->utilization->cell2)->addText('Serial No.', 'bold_text', 'nospacing_centeralign');
$lowestUtilizationTable->addCell($cellWidths [2], $this->styles->tables->utilization->cell3)->addText('Avg. Monthly Volume', 'bold_text', 'nospacing_centeralign');
$lowestUtilizationTable->addCell($cellWidths [3], $this->styles->tables->utilization->cell4)->addText('Recommended Max. Volume', 'bold_text', 'nospacing_centeralign');
/* @var $device Proposalgen_Model_DeviceInstance */
foreach ($assessmentViewModel->getLeastUsedDevices() as $device)
{
    $lowestUtilizationTable->addRow($this->styles->tables->utilization->rowheight, $this->styles->tables->rowstyle);
    $lowestUtilizationTable->addCell($cellWidths [0], $this->styles->tables->utilization->cell1)->addText($device->getDeviceName(), null, 'nospacing');
    $lowestUtilizationTable->addCell($cellWidths [1], $this->styles->tables->utilization->cell2)->addText(($device->serialNumber) ? : "Unknown", null, 'nospacing');
    $lowestUtilizationTable->addCell($cellWidths [2], $this->styles->tables->utilization->cell3)->addText($this->formatPageVolume($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_centeralign');
    $lowestUtilizationTable->addCell($cellWidths [3], $this->styles->tables->utilization->cell4)->addText($this->formatPageVolume($device->getMasterDevice()->maximumRecommendedMonthlyPageVolume), null, 'nospacing_centeralign');
}

$section->addText('Only takes into account devices for which expected cartridge yields are known.', 'small_italic_text', 'nospacing');
$section->addTextBreak();

$highestUtilizationTable = $section->addTable($this->styles->tables->utilization->tablestyle);
$highestUtilizationTable->addRow($this->styles->tables->utilization->rowheight, $this->styles->tables->rowheader);
$highestUtilizationTable->addCell($cellWidths [0], $this->styles->tables->utilization->cell1)->addText('Highest Utilization', 'bold_text', 'nospacing_centeralign');
$highestUtilizationTable->addCell($cellWidths [1], $this->styles->tables->utilization->cell2)->addText('Serial No.', 'bold_text', 'nospacing_centeralign');
$highestUtilizationTable->addCell($cellWidths [2], $this->styles->tables->utilization->cell3)->addText('Avg. Monthly Volume', 'bold_text', 'nospacing_centeralign');
$highestUtilizationTable->addCell($cellWidths [3], $this->styles->tables->utilization->cell4)->addText('Recommended Max. Volume', 'bold_text', 'nospacing_centeralign');

/* @var $device Proposalgen_Model_DeviceInstance */
foreach ($assessmentViewModel->getMostUsedDevices() as $device)
{
    $highestUtilizationTable->addRow($this->styles->tables->utilization->rowheight, $this->styles->tables->rowstyle);
    $highestUtilizationTable->addCell($cellWidths [0], $this->styles->tables->utilization->cell1)->addText($device->getDeviceName(), null, 'nospacing');
    $highestUtilizationTable->addCell($cellWidths [1], $this->styles->tables->utilization->cell2)->addText(($device->serialNumber) ? : "Unknown", null, 'nospacing');
    $highestUtilizationTable->addCell($cellWidths [2], $this->styles->tables->utilization->cell3)->addText($this->formatPageVolume($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_centeralign');
    $highestUtilizationTable->addCell($cellWidths [3], $this->styles->tables->utilization->cell4)->addText($this->formatPageVolume($device->getMasterDevice()->maximumRecommendedMonthlyPageVolume), null, 'nospacing_centeralign');
}
$section->addText('Only takes into account devices for which expected cartridge yields are known.', 'small_italic_text', 'nospacing');
$section->addTextBreak();

$section->addTitle('Color Usage', 2);
$section->addText(sprintf('You currently have %1$s color printing %2$s a monthly average of %3$s color pages per month, which is %4$s%% of your total monthly print volume.',
    number_format($assessmentViewModel->getNumberOfColorCapableDevices()), //1
    (number_format($assessmentViewModel->getNumberOfColorCapableDevices()) == 1) ? 'device that prints' : 'devices that print', //2
    $this->formatPageVolume($assessmentViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly()), //3
    number_format(($assessmentViewModel->getPercentages()->TotalColorPercentage * 100), 2))); //4

$section->addTextBreak();
$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($graphs [7]);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($graphs [8]);
$section->addTextBreak();

$section->addText('Overall, printing in color is more expensive than printing in monochrome. The ideal amount of color usage depends on your printing needs, but the use of color in important documents can enhance your company\'s professional image, improve comprehension and increase readership.');
$section->addText(sprintf('%1$s can help you track your color printing and provide low-cost color hardware options.', $this->companyName));
