<?php
/**
 * Assessment - Analysis: Environmental Impact
 */
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;
$section->addPageBreak();

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
/* The graphs */
$graphs = $this->graphs;

$section->addTitle("Analysis: Environmental Impact", 1);

$gradeTable = $section->addTable($this->styles->tables->grades->tablestyle);
$gradeTable->addRow();
$gradeTable->addCell(8028, $this->styles->tables->grades->cell1)->addText($assessmentViewModel->getRanking()->getEnvironmentalFriendliness()->RankingText);
$gradeTable->addCell(1000, $this->styles->tables->grades->cell2)->addText(number_format($assessmentViewModel->getRanking()->getEnvironmentalFriendliness()->Rank, 1), "gradeFont", "gradeParagraph");

$section->addTextBreak();

$section->addTitle('Energy Consumption', 2);
$section->addTextBreak();
$section->addText(sprintf('You are currently using an estimated average of %1$s kWh per month to operate printing devices at an estimated monthly cost of %2$s, assuming a cost of %3$s per kWh.',
    number_format($assessmentViewModel->getAveragePowerUsagePerMonth()), // 1
    $this->currency($assessmentViewModel->getAveragePowerCostPerMonth()), // 2
    $this->currency($assessmentViewModel->assessment->getClient()->getClientSettings()->genericSettings->defaultEnergyCost, ['precision' => 4]))); // 3
$section->addText('The following lists the devices with the highest average power consumption per month.');

$cellWidths = [
    2657,
    1857,
    2457,
    2057
];

$highEnergyTable = $section->addTable($this->styles->tables->highenergy->tablestyle);
$highEnergyTable->addRow($this->styles->tables->highriskdevices->rowheight, $this->styles->tables->rowheader);
$highEnergyTable->addCell($cellWidths [0], $this->styles->tables->highriskdevices->cell1)->addText('High Risk Devices', 'bold_text', 'nospacing_centeralign');
$highEnergyTable->addCell($cellWidths [1], $this->styles->tables->highriskdevices->cell2)->addText('Serial No.', 'bold_text', 'nospacing_centeralign');
$highEnergyTable->addCell($cellWidths [2], $this->styles->tables->highriskdevices->cell3)->addText('Avg. kWh Consumption Per Month Count', 'bold_text', 'nospacing_centeralign');
$highEnergyTable->addCell($cellWidths [3], $this->styles->tables->highriskdevices->cell4)->addText('Avg. Power Cost per Month', 'bold_text', 'nospacing_centeralign');
/* @var $device DeviceInstanceModel */
$rowCount = 0;
foreach ($assessmentViewModel->getHighPowerConsumptionDevices() as $device)
{
    $highEnergyTable->addRow($this->styles->tables->highriskdevices->rowheight, $this->styles->tables->rowstyle);
    $highEnergyTable->addCell($cellWidths [0], $this->styles->tables->highriskdevices->cell1)->addText($device->getDeviceName(), null, 'nospacing');
    $highEnergyTable->addCell($cellWidths [1], $this->styles->tables->highriskdevices->cell2)->addText(($device->serialNumber) ?: "Unknown", null, 'nospacing');
    $highEnergyTable->addCell($cellWidths [2], $this->styles->tables->highriskdevices->cell3)->addText(number_format($device->getAverageMonthlyPowerConsumption()) . ' kWh', null, 'nospacing_centeralign');
    $highEnergyTable->addCell($cellWidths [3], $this->styles->tables->highriskdevices->cell4)->addText($this->currency($device->getAverageMonthlyPowerCost()), null, 'nospacing_centeralign');
    $rowCount++;
    if ($rowCount >= 3)
    {
        break;
    }
}

$section->addTextBreak();

$section->addTitle('Green Features: Duplexing and Scanning', 2);
$section->addText('If you printed every document on both sides of the page, you could use up to 50% less paper than you would by only printing on one side. You could further reduce your paper consumption by using a scanner to e-mail documents instead of printing copies for distribution. The following charts show how many of your printing devices have duplexing and scanning capabilities:');

$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($graphs [13]);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($graphs[14]);
