<?php
/**
 * Assessment - Analysis: Expense
 */

/* @var $phpWord PHPWord */
$phpWord = $this->phpword;

/* @var $section PHPWord_Section */
$section = $this->section;
$section->addPageBreak();

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$graphs = $assessmentViewModel->getGraphs();

$section->addTitle("Analysis: Expense", 1);
$gradeTable = $section->addTable($this->styles->tables->grades->tablestyle);
$gradeTable->addRow();
$gradeTable->addCell(8028, $this->styles->tables->grades->cell1)->addText($assessmentViewModel->getRanking()->getExpense()->RankingText);
$gradeTable->addCell(1000, $this->styles->tables->grades->cell2)->addText(number_format($assessmentViewModel->getRanking()->getExpense()->Rank, 1), "gradeFont", "gradeParagraph");

$section->addTextBreak();
$section->addText(sprintf('Gartner Group called office printing the last great hidden expense in the office. They estimate the companies spend 1% to 3% of their revenue on office printing. Based on data collected from your printing devices and your questionnaire responses, we have estimated your annual printing expenses. We have separated your expenses into the cost of your leased printing devices and the cost of your purchased devices. Your leased devices are typically large multifunction devices and are assumed to be on an existing service contract. Your purchased devices are ones that can typically be transferred to our %1$s program and be managed by %2$s.', $this->brandName, $this->companyName));

$section->addTitle('Total Estimated Annual Printing Costs', 2);
$section->addText('Combining all costs, your current estimated annual printing expenses are as follows. Please note that our estimated costs may not match your actual purchases, due to factors including inventory on hand, returns, timing of the assessment, etc., but our estimates should be a good representation of your average costs since they are based on actual observed usage.');

$annualPrintingCostsTable = $section->addTable($this->styles->tables->expenseSummaryTable->tablestyle);
$annualPrintingCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$annualPrintingCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Annual cost of hardware on leases', null, 'nospacing');
$annualPrintingCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getEstimatedAnnualCostOfLeaseMachines()), null, 'nospacing_rightalign');
$annualPrintingCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$annualPrintingCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1Border)->addText('Annual cost of hardware not on leases', null, 'nospacing');
$annualPrintingCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2Border)->addText('$' . number_format($assessmentViewModel->getTotalPurchasedAnnualCost()), null, 'nospacing_rightalign');
$annualPrintingCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$annualPrintingCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('TOTAL ESTIMATED ANNUAL PRINTING COSTS', 'bold_text', 'nospacing');
$annualPrintingCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->calculateEstimatedAnnualCostOfPrinting()), 'bold_text', 'nospacing_rightalign');

$section->addTextBreak();
$section->addTitle('Cost of Hardware Assumed to be Leased', 2);
$section->addText('To calculate your cost of leased printing devices, we assumed that you are paying a monthly lease rate in addition to a per-page cost, which includes supplies and service for each device.');

$assumedLeasedCostsTable = $section->addTable($this->styles->tables->expenseSummaryTable->tablestyle);
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Number of printing devices assumed to be on a lease', null, 'nospacing');
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText(number_format(count($assessmentViewModel->getDevices()->leasedDeviceInstances->getDeviceInstances())), null, 'nospacing_rightalign');
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Predicted average annual monochrome prints on leased machines', null, 'nospacing');
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText(number_format($assessmentViewModel->getDevices()->leasedDeviceInstances->getPageCounts()->getBlackPageCount()->getYearly()), null, 'nospacing_rightalign');
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Predicted average annual color prints on leased machines', null, 'nospacing');
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText(number_format($assessmentViewModel->getDevices()->leasedDeviceInstances->getPageCounts()->getColorPageCount()->getYearly()), null, 'nospacing_rightalign');
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1Border);
$cell->addText('Estimated annual total lease payments', null, 'nospacing');
$cell->addText(sprintf('Based on $%1$s per month per device', number_format($assessmentViewModel->assessment->getAssessmentSettings()->monthlyLeasePayment)), 'small_italic_text', 'nospacing');


$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2Border)->addText('$' . number_format($assessmentViewModel->getCombinedAnnualLeasePayments()), null, 'nospacing_rightalign');
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Estimated per-page lease cost', 'bold_text', 'nospacing');
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getPerPageLeaseCost(), 4), 'bold_text', 'nospacing_rightalign');
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Estimated monochrome per-page charge', null, 'nospacing');
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getLeasedBlackAndWhiteCharge(), 4), null, 'nospacing_rightalign');
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1Border)->addText('Estimated color per-page charge', null, 'nospacing');
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2Border)->addText('$' . number_format($assessmentViewModel->getLeasedColorCharge(), 4), null, 'nospacing_rightalign');
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Estimated all-in cost for a monochrome page', 'bold_text', 'nospacing');
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getLeasedEstimatedBlackAndWhiteCPP(), 4), 'bold_text', 'nospacing_rightalign');
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1Border)->addText('Estimated all-in cost for a color page', 'bold_text', 'nospacing');
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2Border)->addText('$' . number_format($assessmentViewModel->getLeasedEstimatedColorCPP(), 4), 'bold_text', 'nospacing_rightalign');
$assumedLeasedCostsTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('TOTAL ESTIMATED ANNUAL COST', 'bold_text', 'nospacing');
$assumedLeasedCostsTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getEstimatedAnnualCostOfLeaseMachines()), 'bold_text', 'nospacing_rightalign');

$section->addPageBreak();
$section->addTitle('Cost of Hardware Suitable for Transfer to a Managed Print Solution', 2);
$section->addText(sprintf('Your %1$s print devices that are assumed to not be attached to leases may be suitable for transfer to a managed print program. Currently, you are paying for supplies and service separately for these devices and your internal IT staff spends time servicing them when they break down.', number_format(count($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances()))));
$section->addText(sprintf('The costs below are based on data collected using remote monitoring software and your questionnaire responses. It also assumes a monochrome page coverage of %1$s%% and color coverage of %2$s%%.', number_format($assessmentViewModel->getPageCoverageBlackAndWhite()), number_format($assessmentViewModel->getPageCoverageColor())));

$section->addTitle('Supplies', 3);
$suppliesTable = $section->addTable($this->styles->tables->expenseSummaryTable->tablestyle);
$suppliesTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $suppliesTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1);
$cell->addText('Annual cost of ink and toner', null, 'nospacing');
$cell->addText(sprintf('Based on data collected by %1$s.', $this->companyName), 'small_italic_text', 'nospacing');
$suppliesTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getCostOfInkAndToner($assessmentViewModel->getCostPerPageSettingForCustomer())), null, 'nospacing_rightalign');

$suppliesTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $suppliesTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1Border);
$cell->addText('Annual administration cost of executing supplies orders', null, 'nospacing');
$cell->addText('Based on your questionnaire responses.', 'small_italic_text', 'nospacing');
$suppliesTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2Border)->addText('$' . number_format($assessmentViewModel->getCostOfExecutingSuppliesOrders()), null, 'nospacing_rightalign');

$suppliesTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$suppliesTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Total estimated annual supplies-related expense', 'bold_text', 'nospacing');
$suppliesTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getEstimatedAnnualSupplyRelatedExpense()), 'bold_text', 'nospacing_rightalign');

$section->addTitle('Service', 3);
$serviceTable = $section->addTable($this->styles->tables->expenseSummaryTable->tablestyle);
$serviceTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $serviceTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1);
$cell->addText('Annual cost of sourcing outside service organizations', null, 'nospacing');
$cell->addText('Based on your questionnaire responses.', 'small_italic_text', 'nospacing');
$serviceTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getAnnualCostOfOutSourcing()), null, 'nospacing_rightalign');

$serviceTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $serviceTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1Border);
$cell->addText('Annual cost of internal IT servicing and supporting printing devices', null, 'nospacing');
$cell->addText('Based on your questionnaire responses.', 'small_italic_text', 'nospacing');
$serviceTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2Border)->addText('$' . number_format($assessmentViewModel->getAnnualITCost()), null, 'nospacing_rightalign');

$serviceTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$serviceTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Total estimated annual cost of service', 'bold_text', 'nospacing');
$serviceTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getEstimatedAnnualCostOfService()), 'bold_text', 'nospacing_rightalign');

$section->addTitle('Hardware', 3);
$hardwareTable = $section->addTable($this->styles->tables->expenseSummaryTable->tablestyle);
$hardwareTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1Border);
$cell->addText('Total estimated annual cost of hardware purchases', 'bold_text', 'nospacing');
$cell->addText(sprintf('Based on the age of your devices and an average purchase price of $%1$s.', number_format($assessmentViewModel->assessment->getAssessmentSettings()->defaultPrinterCost)), 'small_italic_text', 'nospacing');
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2Border)->addText('$' . number_format($assessmentViewModel->getAnnualCostOfHardwarePurchases()), null, 'nospacing_rightalign');

$hardwareTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('TOTAL ESTIMATED ANNUAL COST', 'bold_text', 'nospacing');
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getTotalPurchasedAnnualCost()), 'bold_text', 'nospacing_rightalign');

$hardwareTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Predicted average annual monochrome prints', null, 'nospacing');
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText(number_format($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getBlackPageCount()->getYearly()), null, 'nospacing_rightalign');

$hardwareTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Predicted average annual color prints', null, 'nospacing');
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText(number_format($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getYearly()), null, 'nospacing_rightalign');

$hardwareTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Estimated all-in cost for a monochrome page', 'bold_text', 'nospacing');
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getEstimatedAllInBlackAndWhiteCPP(), 4), 'bold_text', 'nospacing_rightalign');

$hardwareTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Estimated all-in cost for a color page', 'bold_text', 'nospacing');
$hardwareTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('$' . number_format($assessmentViewModel->getEstimatedAllInColorCPP(), 4), 'bold_text', 'nospacing_rightalign');

$section->addTextBreak();
$section->addText(sprintf('Through our %1$s program, we can wrap supplies and service for these machines into a single cost-per-page rate. By partnering with %2$s as your single-source provider, your printing devices will be efficiently managed and your staff can get back to concentrating on their core responsibilities. Out of these devices, below are the top three most expensive to operate:', $this->brandName, $this->companyName));

$expensiveTable = $section->addTable($this->styles->tables->mostexpensive->tablestyle);
$expensiveTable->addRow($this->styles->tables->mostexpensive->rowheight);
$expensiveTable->addCell($this->styles->tables->mostexpensive->col1Width, $this->styles->tables->mostexpensive->cell1)->addText('Printing Device', 'bold_text', 'nospacing_centeralign');
$expensiveTable->addCell($this->styles->tables->mostexpensive->col2Width, $this->styles->tables->mostexpensive->cell2)->addText('Serial No.', 'bold_text', 'nospacing_centeralign');
$expensiveTable->addCell($this->styles->tables->mostexpensive->col3Width, $this->styles->tables->mostexpensive->cell3)->addText('Monthly Volume', 'bold_text', 'nospacing_centeralign');
$expensiveTable->addCell($this->styles->tables->mostexpensive->col4Width, $this->styles->tables->mostexpensive->cell4)->addText('Monthly Cost', 'bold_text', 'nospacing_centeralign');
$rowCounter = 0;
/* @var $device Proposalgen_Model_DeviceInstance */
foreach ($assessmentViewModel->getMostExpensiveDevices() as $device)
{
    $expensiveTable->addRow();
    $expensiveTable->addCell($this->styles->tables->mostexpensive->col1Width, $this->styles->tables->mostexpensive->cell1)->addText($device->getDeviceName(), null, 'nospacing');
    $expensiveTable->addCell($this->styles->tables->mostexpensive->col2Width, $this->styles->tables->mostexpensive->cell2)->addText(($device->serialNumber) ? : "Unknown", null, 'nospacing_centeralign');
    $expensiveTable->addCell($this->styles->tables->mostexpensive->col3Width, $this->styles->tables->mostexpensive->cell3)->addText(number_format($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_centeralign');
    $expensiveTable->addCell($this->styles->tables->mostexpensive->col4Width, $this->styles->tables->mostexpensive->cell4)->addText('$' . number_format($device->getMonthlyRate($assessmentViewModel->getCostPerPageSettingForCustomer())
        ), null, 'nospacing_centeralign');
    $rowCounter++;
    if ($rowCounter >= 3)
    {
        break;
    }
}
