<?php
/**
 * Assessment - 3 Smart Steps to Success with Managed Print
 */

/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;
$section->addPageBreak();

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$section->addTitle("3 Smart Steps to Success with Managed Print", 1);

if ($this->App()->theme == 'printiq')
{
    $section->addText(sprintf('%1$s has been managing print for our customers since the beginning. Sourcing and delivering printers and supplies is our mainstay and we\'ve been taking care
    of business for 25 years. Our full service MPS program was designed to manage and support your printing environment, based on your unique office printing needs.', $this->companyName));
}

$section->addText(sprintf('The %1$s MPS program empowers you to:', $this->companyName));

$section->addListItem("Accurately identify printing costs");
$section->addListItem("Control expenses and budget for future needs");
$section->addListItem("Increase your working capital by reducing supplies inventory");
$section->addListItem("Free IT from print related issues");
$section->addListItem("Choose to keep your existing assets or obtain new hardware from a choice of manufacturers");
if ($this->App()->theme == 'printiq')
{
    $section->addListItem("Leverage Copy & Print Depot in our 1,100+ stores nationwide for a Total Print Solution");
}
$section->addListItem("Improve productivity and user satisfaction");
$section->addListItem("Foster your eco-smart objectives");

$section->addTitle('Step 1: Assess', 2);
$section->addText(sprintf('This complimentary %1$s will help us determine what your needs are for office print. By combining data collected from your printing devices with questionnaire responses, we can determine what is working and what isn\'t in your office print environment. From this information, we can build a managed print solution that meets your business needs.', My_Brand::getDealerBranding()->assessmentTitle));

$section->addTitle('Step 2: Optimize', 2);
$tr = $section->addTextRun();
$tr->addText('Increase Hardware Efficiency: ', 'bold_text');
$tr->addText('Whether you choose to maintain your existing printer fleet or refresh inefficient devices, your managed print program delivers benefits that meet your specific needs. We will make sure your printing equipment meets your needs and help you optimize the placement of your equipment to make sure you are getting the most out of your assets.');

$tr = $section->addTextRun();
$tr->addText('Just-in-Time Supplies & Efficient Service: ', 'bold_text');
$tr->addText('Our just-in-time supplies fulfillment and 4-hour response repair service will get you the supplies and service you need, when you need it. By remotely monitoring your printers, we can help you minimize downtime and reduce the amount of working capital held in supplies inventory. Next-day service is available for all printers under a managed print contract so your IT staff will be free from handling printer-related issues.');

$tr = $section->addTextRun();
$tr->addText('Single Contact, Single Invoice: ', 'bold_text');
$tr->addText('Forget dealing with multiple vendors and receive one invoice for all of your managed printers. This includes either service and supplies on a per-page rate, or hardware, service and supplies on a flat monthly rate. Either way, you will be able to budget for printing with predictable expenses.');

if ($this->App()->theme == 'printiq')
{
    $tr = $section->addTextRun();
    $tr->addText('Eco Smart Solutions: ', 'bold_text');
    $tr->addText(sprintf('%1$s was recognized by Newsweek as the No. 1 green retailer, and we can help you reduce your environmental impact and achieve your sustainability goals.', $this->companyName));
}

$section->addPageBreak();

$section->addTitle('Step 3: Manage', 2);
$section->addText('Ongoing management of your print environment enables you to focus on your core business, while we take care of print. By monitoring your print environment on an ongoing basis, we can help you decide if and when your managed print strategy needs to be updated to accommodate new needs.');

$section->addTitle(sprintf('Potential Savings with the %1$s program', $this->brandName), 2);
$section->addText(sprintf('%1$s can manage your existing printing devices that are not currently on a lease with another vendor. Note that while we have included all of your purchased equipment in the following calculations, not all of them may qualify for managed print services or just-in-time supplies fulfillment. Please refer to the %2$s document for a complete list of qualified devices.', $this->companyName, My_Brand::getDealerBranding()->solutionTitle));

$section->addTitle(sprintf('Estimated Costs: Printing Devices Managed with the %1$s program', $this->brandName), 3);

$summaryTable = $section->addTable($this->styles->tables->expenseSummaryTable->tablestyle);

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText(sprintf('%1$s monochrome cost per page', $this->brandName), null, 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText($this->formatCostPerPage($assessmentViewModel->getMPSBlackAndWhiteCPP()), null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText(sprintf('%1$s color cost per page', $this->brandName), null, 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText($this->formatCostPerPage($assessmentViewModel->getMPSColorCPP()), null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Predicted annual monochrome pages', null, 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText($this->formatPageVolume($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getBlackPageCount()->getYearly()), null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Predicted annual color pages', null, 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText($this->formatPageVolume($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getYearly()), null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Cost of monochrome pages', null, 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText($this->currency($assessmentViewModel->calculateTotalCostOfMonochromePagesAnnually()), null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1)->addText('Cost of color pages', null, 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText($this->currency($assessmentViewModel->calculateTotalCostOfColorPagesAnnually()), null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1);
$cell->addText('Annual internal administration cost', null, 'nospacing');
$cell->addText(sprintf('Processing 1 invoice/month @ %1$s/invoice', $this->currency($assessmentViewModel->assessment->getClient()->getSurvey()->costToExecuteSuppliesOrder)), 'small_italic_text', 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText($this->currency($assessmentViewModel->getInternalAdminCost()), null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1);
$cell->addText('Annual cost of external service', null, 'nospacing');
$cell->addText('Maintenance kits and parts are included', 'small_italic_text', 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText('Included', null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1);
$cell->addText('Annual cost of internal IT supporting printing devices', null, 'nospacing');
$cell->addText('Assume reduction of 50%', 'small_italic_text', 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2)->addText($this->currency($assessmentViewModel->getHalfOfAnnualITCost()), null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$cell = $summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, $this->styles->tables->expenseSummaryTable->cell1Border);
$cell->addText('Annual cost of new hardware purchases', null, 'nospacing');
$cell->addText('Assume no change', 'small_italic_text', 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, $this->styles->tables->expenseSummaryTable->cell2Border)->addText($this->currency($assessmentViewModel->getAnnualCostOfHardwarePurchases()), null, 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, array_merge($this->styles->tables->expenseSummaryTable->cell1Border, $this->styles->tables->expenseSummaryTable->underline))->addText(sprintf('%1$s estimated annual cost of purchased devices', $this->brandName), 'bold_text', 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, array_merge($this->styles->tables->expenseSummaryTable->cell2Border, $this->styles->tables->expenseSummaryTable->underline))->addText($this->currency($assessmentViewModel->getPrintIQTotalCost()), 'bold_text', 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, array_merge($this->styles->tables->expenseSummaryTable->cell1Border, $this->styles->tables->expenseSummaryTable->underline))->addText('Current estimated annual cost of purchased devices', 'bold_text', 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, array_merge($this->styles->tables->expenseSummaryTable->cell2Border, $this->styles->tables->expenseSummaryTable->underline))->addText($this->currency($assessmentViewModel->getTotalPurchasedAnnualCost()), 'bold_text', 'nospacing_rightalign');

$summaryTable->addRow($this->styles->tables->expenseSummaryTable->rowheight);
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col1Width, array_merge($this->styles->tables->expenseSummaryTable->cell1, $this->styles->tables->expenseSummaryTable->underline))->addText(sprintf('POTENTIAL ANNUAL SAVINGS USING %1$s', $this->brandName), 'bold_red_text', 'nospacing');
$summaryTable->addCell($this->styles->tables->expenseSummaryTable->col2Width, array_merge($this->styles->tables->expenseSummaryTable->cell2, $this->styles->tables->expenseSummaryTable->underline))->addText($this->currency($assessmentViewModel->getPrintIQSavings()), 'bold_highlight_text', 'nospacing_rightalign');

$section->addTextBreak();

$section->addText('Whether you are looking for a comprehensive managed print services plan that includes new equipment, or are looking for assistance in maintaining your existing printer fleet, we can design a solution that meets your specific business needs. Let us take care of your print so you can get back to business.');