<div class="page-header">
        <h1>Users - <small>User Management</small></h1>
</div>
<div class="clearfix">
    <?php if (count($this->users) < $this->maxUsers) : ?>
        <a class="btn btn-success pull-right btn-small create-button" href="<?php echo $this->url(array('action' => 'create')) ?>">
            <i class="icon-white icon-plus-sign"></i> Create new</a>
    <?php endif ?>

</div>
<?php if (isset($this->users) && count($this->users) > 0) : ?>
<table class="table table-striped table-condensed table-bordered">
    <thead>
    <tr>
        <th colspan="6">
            <p><?php echo count($this->users);?> of <?php echo $this->maxUsers; ?> Users Created</p>
            <div class="progress progress-striped">
                <div class="bar <?php echo (count($this->users) < $this->maxUsers) ? '' : 'bar-danger';?>" style="width: <?php echo count($this->users) / $this->maxUsers  * 100 . '%'?>;"></div>
            </div>
        </th>
    </tr>
    <tr>
        <th>Email</th>
        <th>Name</th>
        <th style="width: 70px;">Login Attempts</th>
        <th style="width: 100px;">Frozen Until</th>
        <th style="width: 60px;">Locked</th>
        <th style="width: 60px;">Action</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($this->users as $user) : /* @var $user Application_Model_User */ ?>
    <tr>
        <td><?php echo $user->email; ?></td>
        <td><?php echo $user->firstname; ?> <?php echo $user->lastname; ?></td>
        <td style="text-align: center;"><?php echo $user->loginAttempts; ?></td>
        <td><?php echo ($user->isFrozen()) ? $user->frozenUntil : ""; ?></td>
        <td style="text-align: center;"><?php echo ($user->locked) ? "Yes" : "No"; ?></td>
        <td>
            <div class="btn-group">
                <a class="btn btn-warning btn-mini" title="Edit User" href="<?php echo $this->url( array ( 'action' => 'edit', 'id' => $user->id))?>" ?><i class="icon-pencil"></i></a>
                <a class="btn btn-danger btn-mini" title="Delete User" href="<?php echo $this->url( array ( 'action' => 'delete', 'id' => $user->id))?>" ?><i class="icon-trash"></i></a>
            </div>
        </td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else : ?>
<h1>There are no users</h1>
<?php endif; ?>

