<?php

use MPSToolbox\Legacy\Models\UserModel;

?>
<div class="container">
    <div class="clearfix">
        <?php if (count($this->users) < $this->maxUsers) : ?>
            <a class="btn btn-success pull-right btn-sm create-button" href="<?= $this->url([], 'company.users.create') ?>">
                <i class="glyphicon glyphicon-plus-sign"></i> Create new</a>
        <?php endif ?>

    </div>
    <?php if (isset($this->users) && count($this->users) > 0) : ?>
        <div class="table-responsive">
            <table class="table table-striped table-condensed table-bordered">
                <thead>
                <tr>
                    <th colspan="7">
                        <p><?= count($this->users); ?> of <?= $this->maxUsers; ?> Users Created</p>

                        <div class="progress">
                            <?php $width = count($this->users) / $this->maxUsers * 100; ?>
                            <div class="progress-bar <?= (count($this->users) < $this->maxUsers) ? '' : 'bar-danger'; ?>" style="width: <?= ($width > 100) ? 100 : $width . '%' ?>;"></div>
                        </div>
                    </th>
                </tr>
                <tr>
                    <th>Email</th>
                    <th>Name</th>
                    <th>Login Attempts</th>
                    <th>Frozen Until</th>
                    <th>Locked</th>
                    <th>Last Seen</th>
                    <th style="width: 80px;">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php /* @var $user UserModel */ ?>
                <?php foreach ($this->users as $user) : ?>
                    <tr>
                        <td><?= $user->email; ?></td>
                        <td><?= $user->firstname; ?> <?= $user->lastname; ?></td>
                        <td style="text-align: center;"><?= $user->loginAttempts; ?></td>
                        <td><?= ($user->isFrozen()) ? $user->frozenUntil : ""; ?></td>
                        <td style="text-align: center;"><?= ($user->locked) ? "Yes" : "No"; ?></td>
                        <td><?php echo ($user->lastSeen === null) ? "Never" : (new \Carbon\Carbon($user->lastSeen))->diffForHumans(); ?>
                            <br><?php echo $user->lastSeen ?></td>
                        <td>
                            <div class="btn-group btn-group-justified btn-group-xs">
                                <a class="btn btn-warning" title="Edit User" href="<?= $this->url(['id' => $user->id], 'company.users.edit') ?>"><i class="glyphicon glyphglyphicon glyphicon-pencil"></i></a>
                                <a class="btn btn-danger" title="Delete User" href="<?= $this->url(['id' => $user->id], 'company.users.delete') ?>"><i class="glyphicon glyphicon-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else : ?>
        <h1>There are no users</h1>
    <?php endif; ?>
</div>
