<?php

/* @var $options Quotegen_Model_Option [] */
$options = $this->options;

foreach ($options as $option) :
    ?>
    <div class="control-group ">
        <label class="control-label"><?php echo $option['name']; ?></label>

        <div class="controls">
            <div class="input-prepend input-append">
                <span class="add-on">Quantity: <?php echo $option['quantity']; ?></span>
                <span class="add-on" style="width: 150px; text-align: left;">Cost Per Unit: <?php echo $this->currency($option['cost']); ?></span>
            </div>
        </div>
    </div>
<?php
endforeach;

if ($options) :
    ?>
    <input type="submit" id="useConfiguration" name="useConfiguration" class="btn btn-primary" value="Use Configuration">
<?php
endif;