<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\OptionModel;

/* @var $options OptionModel[] */
$options = $this->options;
?>
<div class="container">
    <?php if ($options): ?>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Quantity</th>
                <th>Cost per Unit</th>
            </tr>
            </thead>
            <?php foreach ($options as $option) : ?>
                <tr>
                    <td><?= $option['name']; ?></td>
                    <td class="quantity"><?= $option['quantity']; ?></td>
                    <td class="cost"><?= $this->currency($option['cost']); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <p>There are no options in this configuration.</p>
    <?php endif; ?>
    <input type="submit" id="useConfiguration" name="useConfiguration" class="btn btn-success btn-sm pull-right" value="Use Configuration">
</div>