<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\DeviceModel;
use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\QuoteModel;

/* @var $deviceConfiguration DeviceModel */
$device = $this->device;

/* @var $quote QuoteModel */
$quote = $this->Quote();

$this->headScript()->appendFile($this->baseUrl('/js/app/legacy/quotegen/quote/devices/DeviceConfigurations.js'));
?>
<div class="container">
    <?= $this->form ?>
</div>