<?php $device = $this->device; /* @var $deviceConfiguration Quotegen_Model_Device */ ?>
<?php
$this->headScript()->appendFile($this->baseUrl('/js/quotegen/quote/devices/configurations.js'));

$quote = $this->Quote();
/* @var $quote Quotegen_Model_Quote */
$this->placeholder('ProgressionNav')->set($this->render('_partials/quoteHeading.phtml'));
?>
<div class="well">
    <?php echo $this->form; ?>
</div>