<form id="loginForm" action="<?php echo $this->baseUrl() ?>/auth/changepassword" method="post">
<?php if ($this->updatePassword == 0) echo "<h2>Change Password</h2>";?>
	<div id="login_messages">
    	<div id="message_container"><?php echo $this->message; ?></div>
	</div>   
	<div class="well">
    <table cellspacing="2" cellpadding="2" border="0">
        <tbody>
            <tr>
				<td><label class="forms_label" for="password">Password:</label></td>
				<td><input type="password" id="password" name="password" value="" /></td>
            </tr>
            <tr>
				<td><label class="forms_label" for="confirm">Confirm:</label></td>
				<td><input type="password" id="confirm" name="confirm" value="" /></td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
				<td colspan="2" style="text-align: center">					
					<input type='submit' name='update' value='Update' class='btn btn-primary' />
					<?php if ($this->updatePassword == 0) echo "<input type='submit' name='cancel' value='Done' class='btn' />";
					else echo "<input type='submit' name='cancel' value='Cancel' class='btn' />";?>
				</td>
            </tr>
        </tfoot>
    </table>
    </div>
</form>