<form id="loginForm" action="<?php echo $this->baseUrl() ?>/auth/forgotpassword" method="post">
	<input type="hidden" value="<?=$this->captcha ?>" name="captcha[id]"/>
    <table style="width: 300px" cellspacing="2" cellpadding="2" border="0">
    	<thead>
    		<tr>
    			<th colspan="2">&nbsp;</th>
			</tr>
    	</thead>
        <tbody>
        	<tr>
        		<td colspan="2">
        			<div id="login_messages">
        			<?php if(!empty($this->message)) { ?>
        				<?php echo $this->message; ?>
        			<?php } else { ?>
						To reset your password please enter your username.
					<?php } ?>
					</div>
				</td>
			</tr>
            <tr>
				<td><label for="username">Username:</label></td>
				<td><input type="text" id="username" name="username" value="<?php echo $this->username; ?>" size="30" /></td>
            </tr>
            <tr>
            	<td valign="top">&nbsp;</td>
            	<td>
					<div id="captcha_container">
						<img src="<?php echo $this->baseUrl("/cache/captcha/" . $this->captcha . ".png"); ?>" alt="" />
					</div>
            	</td>
            </tr>
            <tr>
            	<td><label for="captcha">CAPTCHA:</label></td>
            	<td><input type="text" name="captcha[input]" size="30" /></td>
            </tr>
            <tr>
				<td colspan="2" style="text-align: center">
					<input type="submit" name="Submit" value="Submit" />
					<input type="button" name="Cancel" value="Cancel" onclick="javascript: document.location.href='<?php echo $this->baseUrl() ?>/auth/login';" />
				</td>
            </tr>
        </tbody>
        <tfoot>
        	<tr><td colspan="2">&nbsp;</td></tr>
        </tfoot>
    </table>
</form>