<form id="loginForm" action="<?php echo $this->baseUrl("/auth/resetpassword/verify/" . $this->reset_token) ?>" method="post">
	<div id="login_messages">Reset Password
    	<div id="message_container"><?php echo $this->message; ?></div>
	</div>   
    <table cellspacing="2" cellpadding="2" border="0" class="details_table">
        <tbody>
            <tr>
				<td><label class="forms_label" for="password">Password:</label></td>
				<td><input type="password" id="password" name="password" value="" /></td>
            </tr>
            <tr>
				<td><label class="forms_label" for="confirm">Confirm:</label></td>
				<td><input type="password" id="confirm" name="confirm" value="" /></td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
				<td colspan="2" style="text-align: center">					
					<input type='submit' name='reset' value='Reset' />
					<input type='submit' name='cancel' value='Cancel' />
				</td>
            </tr>
        </tfoot>
    </table>
</form>