<?php
/**
 * Assessment - Analysis: Technology Reliability and User Productivity
 */

/* @var $phpWord PHPWord */
$phpWord = $this->phpword;

/* @var $section PHPWord_Section */
$section = $this->section;
$section->addPageBreak();

/* @var $proposal Assessment_ViewModel_Assessment */
$proposal = $this->proposal;
$graphs = $proposal->getGraphs();

$section->addTitle($this->translate("Analysis: Technology Reliability and User Productivity"), 1);
$gradeTable = $section->addTable($this->styles->tables->grades->tablestyle);
$gradeTable->addRow();
$gradeTable->addCell(8028, $this->styles->tables->grades->cell1)->addText($proposal->getRanking()->TechnologyReliabilityAndUserProductivity->RankingText);
$gradeTable->addCell(1000, $this->styles->tables->grades->cell2)->addText(number_format($proposal->getRanking()->TechnologyReliabilityAndUserProductivity->Rank, 1), "gradeFont", "gradeParagraph");

$section->addTextBreak();
$section->addTitle($this->translate('Age Of Printing Devices'), 2);
$section->addText(sprintf($this->translate('The average age of printing devices in your office is %1$s year(s) old. Printers under 5 years old are the most reliable machines. As printing devices get older, the risk of frequent breakdowns increases. Printers over 8 years old have a high risk of frequent breakdowns and there is a risk that supplies and parts for these machines may be discontinued.')), number_format($proposal->getAverageAgeOfDevices(), 1));
$section->addText($this->translate('The breakdown of the age of your printing devices is shown below:'));
$imageTable = $section->addTable(array (
    'borderBottomSize' => 1 
));
$imageTable->addRow();
$cell = $imageTable->addCell(9028.8, array (
    'valign' => 'center' 
));

$cell->addImage($graphs [9], array (
    'align' => 'center' 
));
$section->addTextBreak();

$section->addText($this->translate('The devices listed below have a high risk of breaking down, because of a combination of their age and the total amount of pages they have printed throughout their life.'));

$cellWidths = array (
    3611, 
    1805, 
    1805, 
    1805, 
    1805, 
    1805 
);

$highRiskDevicesTable = $section->addTable($this->styles->tables->highriskdevices->tablestyle);
$highRiskDevicesTable->addRow($this->styles->tables->highriskdevices->rowheight);
$highRiskDevicesTable->addCell($cellWidths [0], $this->styles->tables->highriskdevices->cell1)->addText($this->translate('High Risk Devices'), 'bold_text', 'nospacing_centeralign');
$highRiskDevicesTable->addCell($cellWidths [1], $this->styles->tables->highriskdevices->cell2)->addText($this->translate('Serial No.'), 'bold_text', 'nospacing_centeralign');
$highRiskDevicesTable->addCell($cellWidths [2], $this->styles->tables->highriskdevices->cell3)->addText($this->translate('Age'), 'bold_text', 'nospacing_centeralign');
$highRiskDevicesTable->addCell($cellWidths [3], $this->styles->tables->highriskdevices->cell4)->addText($this->translate('AMPV'), 'bold_text', 'nospacing_centeralign');
$highRiskDevicesTable->addCell($cellWidths [4], $this->styles->tables->highriskdevices->cell5)->addText($this->translate('Current Life Page Count'), 'bold_text', 'nospacing_centeralign');
$highRiskDevicesTable->addCell($cellWidths [5], $this->styles->tables->highriskdevices->cell6)->addText($this->translate('Est. Max Life Page Count'), 'bold_text', 'nospacing_centeralign');
/* @var $device Proposalgen_Model_DeviceInstance */
$rowCount = 0;
foreach ( $proposal->getHighRiskDevices() as $device )
{
    $highRiskDevicesTable->addRow();
    $highRiskDevicesTable->addCell($cellWidths [0], $this->styles->tables->highriskdevices->cell1)->addText($device->getDeviceName(), null, 'nospacing');
    $highRiskDevicesTable->addCell($cellWidths [1], $this->styles->tables->highriskdevices->cell2)->addText(($device->serialNumber) ?  : "Unknown", null, 'nospacing');
    $highRiskDevicesTable->addCell($cellWidths [2], $this->styles->tables->highriskdevices->cell3)->addText(number_format($device->getAge()) . " year(s)", null, 'nospacing_centeralign');
    $highRiskDevicesTable->addCell($cellWidths [3], $this->styles->tables->highriskdevices->cell4)->addText(number_format($device->getAverageMonthlyPageCount()), null, 'nospacing_centeralign');
    $highRiskDevicesTable->addCell($cellWidths [4], $this->styles->tables->highriskdevices->cell5)->addText(number_format($device->getLifePageCount()), null, 'nospacing_centeralign');
    $highRiskDevicesTable->addCell($cellWidths [5], $this->styles->tables->highriskdevices->cell6)->addText(number_format($device->calculateEstimatedMaxLifeCount()), null, 'nospacing_centeralign');
    $rowCount ++;
    if ($rowCount >= 3)
        break;
}
$section->addText($this->translate('Only takes into account devices for which release dates and expected cartridge yields are known. Age is based on the assumption that the device was installed approximately 1 year after the release date.'), 'small_italic_text', 'nospacing');
$section->addPageBreak();

$section->addTitle($this->translate('IT Time Spent Supporting Printing Devices'), 2);
$section->addText(sprintf($this->translate('Based on your questionnaire responses, your internal IT personnel spend an average of %1$s hours per week supporting printing devices. This results in the following:'), number_format($this->proposal->getWeeklyITHours())));

// IT Time Spent Supporting Printing Devices table
$cellWidths = array (
    7500, 
    1528 
);
$table = $section->addTable($this->styles->tables->twoColumnDataTable->tablestyle);
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText($this->translate('Annual internal IT hours spent servicing and supporting printers'), 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($proposal->getAnnualITHours()), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText($this->translate('Average hourly IT rate'), 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText('$' . number_format($proposal->getAverageITRate()), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText($this->translate('Annual cost for internal IT staff to service and support printers'), 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText('$' . number_format($proposal->getAnnualITCost()), 'bold_text', 'nospacing_rightalign');
$section->addTextBreak();

$section->addText($this->translate('The Gartner Group stated that 30% to 40% of all IT and help desk calls are related to issues with printing and copying. The time that your IT personnel spend managing printers reduces the resources available for your core technology projects. Office Depot can help you manage your printers efficiently and free up the time of your IT staff.'));

$section->addTitle($this->translate('Technology Features and Functionality'), 2);
$section->addText($this->translate('The ability to scan and fax documents from convenient locations helps to improve document workflow and productivity, and scanning can also help reduce the amount of pages printed. Color printing capabilities are important if you are generating client-facing or other important documents in-house.'));
$section->addText($this->translate('The charts below show the percent of your printing devices that are capable of scanning, faxing, and color printing.'));

$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell1)->addImage($graphs [10]);
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell2)->addImage($graphs [11]);
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell3)->addImage($graphs [12]);

$section->addTextBreak();
$section->addText($this->translate('If you are in need of additional features and functionality to improve workflow and print quality, Office Depot has a variety of printing devices that can meet your specific business needs. If you already have everything you need, we can manage the printing assets you have.'));