<?php
/* @var $section \PhpOffice\PhpWord\Element\Section */
use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\ContractTemplateSectionModel;

$section = $this->section;

/* @var $contractTemplateSection ContractTemplateSectionModel */
$contractTemplateSection = $this->contractTemplateSection;

$tableSpan      = $this->tableStyle->gridSpan;
$cellStyle      = $this->cellStyle;
$fontStyle      = $this->fontStyle;
$paragraphStyle = $this->paragraphStyle;

$contractTable = $section->addTable($this->tableStyle->standard);
$contractTable->addRow(300);
$contractTable->addCell($tableSpan ['span8'], $cellStyle->invertBackground)->addText($contractTemplateSection->getContractSectionName(), $fontStyle->invertBackground, $paragraphStyle->noSpacing);


$contractHtml = new DOMDocument(5);
$contractHtml->loadHTML($contractTemplateSection->getContractSectionText());

/* @var $childNode DOMElement */
foreach ($contractHtml->getElementsByTagName('p') as $paragraphNode)
{
    $contractTable->addRow();
    $cell = $contractTable->addCell($tableSpan ['span8'], null);

    $textRun = $cell->addTextRun($paragraphStyle->noSpacingJustified);

    $childNodes = $paragraphNode->childNodes;
    for ($i = 0; $i < $childNodes->length; $i++)
    {
        /** @var $node DOMElement */
        $node = $childNodes->item($i);

        if ($node->tagName == 'b')
        {
            $textRun->addText($node->textContent, $fontStyle->boldFinePrint);
        }
        else
        {
            $textRun->addText($node->textContent, $fontStyle->finePrint);
        }
    }
}