<?php $this->headScript()->captureStart(); ?>
$(function() 
{
	doLoad($('#clientId')[0].value);

	function doLoad(clientId)
	{
		$('#quoteId').empty().attr('disabled', 'disabled');
		$('#clientId').attr('disabled', 'disabled');
			$.ajax(
    		{
    		    url:'<?php echo $this->url(array('format' => 'json', 'controller' => 'index', 'action' => 'get-reports-for-client', )); ?>/clientId/' + clientId,
    		    success:function(data) 
    		    {
    		    	var quotes = data['quotes'];
    		        var html = '';
    		        var len = quotes.length;
    		        for(var i = 0; i < len; i++)
			        {
			        	quoteType = (quotes[i].isLeased) ? 'Leased' : 'Purchased'; 
    		        	html += '<option value="' + quotes[i].id + '">' + quotes[i].quotedate + ' - ' + quoteType + '</option>';
    		        }
    		        $('#quoteId').append(html);
    		        $('#quoteId').removeAttr('disabled');
    		        $('#clientId').removeAttr('disabled');
    		    },
    		    error:function(data) 
    		    {
    		    	alert('doesnt work');
    		    }
    		});
	}
	
	$('#clientId').change(function()
	{
		var clientId = this.value;
		doLoad(clientId);
	});
});
	
<?php $this->headScript()->captureEnd()?>
<div class="page-header">
    <h1>Quote Generator</h1>
</div>
<?php echo $this->Indexmenu(); ?>
<div class="well">
    <?php echo $this->existingQuoteForm; ?>
</div>