<?php

$savePath = PUBLIC_PATH . "/downloads/client/{$this->clientId}/orderlist/{$this->quoteId}/";

if (!is_dir($savePath))
{
    if (!mkdir($savePath, 0777, true))
    {
        throw new Exception("Could not open cache folder! PATH:" . $savePath, 0);
    }
}

// Create a new PHPExcel Object * New PHPExcel objects will have one attached worksheet by default
/* @var $objPHPExcel PHPExcel */
$objPHPExcel = $this->phpexcel;

// Objects in memory are held in php memory as serialized objects, reduces memory footprint with little performance hit
PHPExcel_CachedObjectStorageFactory::cache_in_memory_serialized;

/**
 * Start of the summary Page
 */

$sheetCounter = 0;
$activeSheet  = $objPHPExcel->getActiveSheet();
$objPHPExcel->setActiveSheetIndex(0);
$activeSheet->setTitle("Utilization");

/**
 * Titles
 */
$activeSheet->setCellValue('A1', 'Device Name');
$activeSheet->setCellValue('B1', 'IP Address');
$activeSheet->setCellValue('C1', 'Serial Number');
$activeSheet->setCellValue('D1', 'Monthly Page Volume');
$activeSheet->setCellValue('E1', 'Maximum Monthly Recommended Volume');
$activeSheet->setCellValue('F1', 'Utilization Percent');

$activeSheet->getStyle('A1')->getFont()->setBold(true);
$activeSheet->getStyle('B1')->getFont()->setBold(true);
$activeSheet->getStyle('C1')->getFont()->setBold(true);
$activeSheet->getStyle('D1')->getFont()->setBold(true);
$activeSheet->getStyle('E1')->getFont()->setBold(true);
$activeSheet->getStyle('F1')->getFont()->setBold(true);

$activeSheet->getColumnDimensionByColumn(0)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(1)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(2)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(3)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(4)->setAutoSize(true);
$activeSheet->getColumnDimensionByColumn(5)->setAutoSize(true);

/**
 * Utilization Data List
 */
foreach ($this->utilizationData as $deviceData)
{
    $currentRow = $activeSheet->getHighestRow() + 1;
    $activeSheet->setCellValueByColumnAndRow(0, $currentRow, $deviceData['Device']);
    $activeSheet->setCellValueByColumnAndRow(1, $currentRow, $deviceData['IP Address']);
    $activeSheet->setCellValueByColumnAndRow(2, $currentRow, $deviceData['Serial Number']);
    $activeSheet->setCellValueByColumnAndRow(3, $currentRow, $deviceData['Monthly Page Volume']);
    $activeSheet->setCellValueByColumnAndRow(4, $currentRow, $deviceData['Maximum Monthly Recommended Volume']);
    $activeSheet->setCellValueByColumnAndRow(5, $currentRow, $deviceData['Utilization Percent']);

    $activeSheet->getStyleByColumnAndRow(3, $currentRow)->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyleByColumnAndRow(4, $currentRow)->getNumberFormat()->setFormatCode('#,##0');
    $activeSheet->getStyleByColumnAndRow(5, $currentRow)->getNumberFormat()->applyFromArray(['code' => PHPExcel_Style_NumberFormat::FORMAT_PERCENTAGE_00]);
}

// Save Excel 2007 file
$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
$objWriter->save($this->savePath);

//Clear the workbook from php's memory
$objPHPExcel->disconnectWorksheets();

if (Zend_Controller_Front::getInstance()->getRequest()->isXmlHttpRequest()) echo DOMAIN_URL.$this->baseUrl($this->publicFileName);
else header('Location: '.DOMAIN_URL.$this->baseUrl($this->publicFileName));
