<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

$fh = fopen($this->savePath, "w+");


// Please note that is is a hacked way around things. This should be done more properly with PHPExcel or fputcsv.
fputcsv($fh, ["INCLUDED DEVICES:"]);
fputcsv($fh, []);
fputcsv($fh, []);
fputcsv($fh, $this->appendix_titles);
fputcsv($fh, []);
foreach ($this->appendix_values as $line)
{
    fputcsv($fh, $line);
}
fputcsv($fh, []);
fputcsv($fh, []);
fputcsv($fh, []);
fputcsv($fh, ["EXCLUDED DEVICES:"]);
fputcsv($fh, []);
fputcsv($fh, $this->excluded_titles);
fputcsv($fh, []);
foreach ($this->excluded_values as $line)
{
    fputcsv($fh, $line);
}

fclose($fh);

if (Zend_Controller_Front::getInstance()->getRequest()->isXmlHttpRequest()) echo $this->baseUrl($this->publicFileName);
else header('Location: '.$this->baseUrl($this->publicFileName));

