<?php
$this->placeholder('extraNavbar')->set($this->render('_partials/reportMenu.phtml'));
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/common_all.css"));
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/common_html.css"));
$this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/optimization/optimization_html.css"));

/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal            = $this->proposal;
$costPerPageSetting  = $proposal->getCostPerPageSettingForDealer();
$optimizationDevices = new Proposalgen_Model_Optimization_Dealer($proposal);
$graphs              = $optimizationDevices->getGraphs();
// Get the count of all the devices used in the system
$totalDevices = $optimizationDevices->getDeviceCount();
?>
<div class="container" id="htmlReportContainer">
    <div class="titlepage">
        <div class="header">
            <div class="title-page-logo-box-wrapper">
                <div class="title-page-logo-box">
                    <img class="title-page-logo" src="<?php echo $this->serverUrl($this->theme("proposalgenerator/reports/images/mpstoolbox_logo.jpg")) ?> " />
                </div>
            </div>
        </div>
        <div class="title-page-report-title">
            <h2>Hardware Optimization</h2>
        </div>
        <div class="title-page-customer-details">
            <h3>Prepared for:
                <?php
                if (strlen($proposal->report->getClient()->companyName) > 26)
                {
                    echo "<br/>";
                }

                echo $proposal->report->getClient()->companyName;
                ?>
            </h3>

            <h3><?php echo $proposal->getDateReportPrepared(); ?></h3>

            <p><?php echo nl2br($proposal->report->getClient()->getAddress()); ?></p>
        </div>
    </div>
</div>

<div class="container" id="htmlReportContainer">
<h3>Fleet</h3>
<table class="rDevices">
    <tr>
        <td><strong>Target Monochrome CPP:</strong></td>
        <td><?php echo $this->currency($proposal->report->getReportSettings()->targetMonochromeCostPerPage, array('precision' => 4));?></td>
        <td><strong>Target Color CPP:</strong></td>
        <td><?php echo $this->currency($proposal->report->getReportSettings()->targetColorCostPerPage, array('precision' => 4));?></td>
    </tr>
    <tr>
        <td><strong>Monthly Monochrome Page Count:</strong></td>
        <td><?php echo number_format($proposal->getPageCounts()->Purchased->BlackAndWhite->Monthly);?></td>
        <td><strong>Monthly Color Page Count:</strong></td>
        <td><?php echo number_format($proposal->getPageCounts()->Purchased->Color->Monthly);?></td>
    </tr>
</table>
<br />

<h3>Cost Analysis Summary</h3>
<table class="rDevices">
    <tr class='header'>
        <th colspan='2'>Current Fleet</th>
        <th colspan='2'>Optimized Fleet</th>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Monochrome CPP:</strong></td>
        <td><?php echo $this->currency((float)$proposal->calculateDealerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage, array('precision' => 4))?></td>
        <td style='width:150px;'><strong>Monochrome CPP:</strong></td>
        <td style='width:250px;'><?php echo $this->currency((float)$proposal->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->monochromeCostPerPage, array('precision' => 4))?></td>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Color CPP:</strong></td>
        <td><?php echo ($proposal->getPageCounts()->Purchased->Color->Monthly > 0) ? $this->currency((float)$proposal->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage, array('precision' => 4)) : 'No print volume'; ?></td>
        <td style='width:150px;'><strong>Color CPP:</strong></td>
        <td style='width:250px;'><?php echo ($proposal->getPageCounts()->Purchased->Color->Monthly > 0) ?$this->currency((float)$proposal->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage, array('precision' => 4)) : 'No print volume'; ?></td>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Total Cost:</strong></td>
        <td><?php echo $this->currency((float)$proposal->calculateDealerMonthlyCost(), array('precision' => 2))?></td>
        <td style='width:150px;'><strong>Total Cost:</strong></td>
        <td style='width:250px;'><?php echo $this->currency((float)$proposal->calculateDealerMonthlyCostWithReplacements(), array('precision' => 2))?></td>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Margin ($):</strong></td>
        <td><?php echo $this->currency((float)$proposal->calculateDealerMonthlyProfitUsingTargetCostPerPage(), array('precision' => 2))?></td>
        <td style='width:150px;'><strong>Margin ($):</strong></td>
        <td style='width:250px;'><?php echo $this->currency((float)$proposal->calculateDealerMonthlyProfitUsingTargetCostPerPageAndReplacements(), array('precision' => 2))?></td>
    </tr>
    <tr>
        <td style='width:150px;'><strong>Margin (%):</strong></td>
        <td><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$proposal->calculateDealerMonthlyCost(), (float)$proposal->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2)?>
            %
        </td>
        <td style='width:150px;'><strong>Margin (%):</strong></td>
        <td style='width:250px;'><?php echo number_format(Tangent_Accounting::reverseEngineerMargin((float)$proposal->calculateDealerMonthlyCostWithReplacements(), (float)$proposal->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2)?>
            %
        </td>
    </tr>
</table>
<br />

<h3>Device Summary</h3>
<table class='center'>
    <tr>
        <td><img src="<?php echo $graphs[0]; ?>" /></td>
        <td><img src="<?php echo $graphs[1]; ?>" /></td>
    </tr>
</table>

<h3>Suggested Replacement Devices<em><?php echo '(' . count($optimizationDevices->replaced) . ' of ' . $totalDevices . ')'?></em></h3>
<em>The following devices have been targeted for replacement, either for a monthly cost savings greater
    than <?php echo $this->currency($proposal->report->getReportSettings()->costThreshold);?> or manual replacement.</em>
<!-- Only display table if there are replacement devices assigned -->
<?php if ($optimizationDevices->replaced) : ?>
<table class="rDevices">
    <tr class='header'>
        <th colspan='5' class='header'>Current</th>
        <th colspan='4' class='header'>Replacement</th>
        <th colspan='3' class='header'>Statistics</th>
    </tr>
    <tr class='subHeader'>
        <th style='width:175px;'>Device Name</th>
        <th>Serial<br />IP Address</th>
        <th>Mono CPP</th>
        <th>Color CPP</th>
        <th>Monthly Cost</th>
        <th style='width:175px;'>Device Name</th>
        <th>Mono CPP</th>
        <th>Color CPP</th>
        <th>Monthly Cost</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
        <th>Cost Delta</th>
    </tr>
    <?php foreach ($optimizationDevices->replaced as $device) :
    $isColor           = $device->getMasterDevice()->isColor();
    $replacementDevice = $device->getReplacementMasterDevice();
    ?>
    <tr class='<?php echo $this->cycle(array("rowOne", "rowTwo"))->next();?>'>
        <td class='deviceName'><?php echo '<em>' . $device->getMasterDevice()->getManufacturer()->fullname . '</em><br/><strong>' . $device->getMasterDevice()->modelName . '</strong><br/><em>';?></td>
        <td class='deviceName'><?php echo $device->serialNumber . '<br/>' . $device->ipAddress . '</em>';?></td>
        <td><?php echo $this->currency($device->calculateCostPerPage($costPerPageSetting)->monochromeCostPerPage, array('precision' => 4));?></td>
        <td><?php echo ($isColor) ? $this->currency($device->calculateCostPerPage($costPerPageSetting)->colorCostPerPage, array('precision' => 4)) : 'N/A';?></td>
        <td class='borderRight'><?php echo $this->currency($device->calculateMonthlyCost($costPerPageSetting));?></td>
        <!-- Replacement Devices -->
        <td class='deviceName'><?php echo '<em>' . $replacementDevice->getManufacturer()->fullname . '</em><br/><strong>' . $replacementDevice->modelName . '</strong>';?></td>
        <td><?php echo $this->currency($replacementDevice->calculateCostPerPage($proposal->getCostPerPageSettingForDealer())->monochromeCostPerPage, array('precision' => 4))?></td>
        <td><?php echo ($isColor) ? $this->currency($replacementDevice->calculateCostPerPage($proposal->getCostPerPageSettingForDealer())->colorCostPerPage, array('precision' => 4)) : 'N/A';?></td>
        <td class='borderRight'><?php echo $this->currency($device->calculateMonthlyCost($costPerPageSetting, $replacementDevice));?></td>
        <!-- Monthly Statistics -->
        <td><?php echo number_format($device->getAverageMonthlyBlackAndWhitePageCount());?></td>
        <td><?php echo ($isColor) ? number_format($device->getAverageMonthlyColorPageCount()) : 'N/A';?></td>
        <td><?php echo $this->currency($device->calculateMonthlyCost($costPerPageSetting) - $device->calculateMonthlyCost($costPerPageSetting, $device->getReplacementMasterDevice()));?></td>
    </tr>
    <?php endforeach?>
</table>
    <?php else: ?>
<em>This assessment has no replacement devices assigned.</em>
    <?php endif; ?>
<br />

<h3>Acceptable Devices<em><?php echo '(' . count($optimizationDevices->kept) . ' of ' . $totalDevices . ')'?></em></h3>
<em>The following devices have been deemed productive and fall within the target costs per pages.</em>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>Serial<br />IP Address</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
        <th>Mono CPP</th>
        <th>Color CPP</th>
        <th>Monthly Cost</th>
    </tr>
    <?php foreach ($optimizationDevices->kept as $device) :
    $isColor = $device->getMasterDevice()->isColor();
    ?>
    <tr class='<?php echo $this->cycle(array("rowOne", "rowTwo"))->next();?>'>
        <td class='deviceName'><?php echo '<em>' . $device->getMasterDevice()->getManufacturer()->fullname . '</em><br/><strong>' . $device->getMasterDevice()->modelName . '</strong><br/><em>';?></td>
        <td class='deviceName'><?php echo $device->serialNumber . '<br/>' . $device->ipAddress . '</em>';?></td>
        <td><?php echo number_format($device->getAverageMonthlyBlackAndWhitePageCount());?></td>
        <td><?php echo ($isColor) ? number_format($device->getAverageMonthlyColorPageCount()) : 'N/A';?></td>
        <td><?php echo $this->currency($device->calculateCostPerPage($costPerPageSetting)->monochromeCostPerPage, array('precision' => 4));?></td>
        <td><?php echo ($isColor) ? $this->currency($device->calculateCostPerPage($costPerPageSetting)->colorCostPerPage, array('precision' => 4)) : 'N/A';?></td>
        <td><?php echo $this->currency($device->calculateMonthlyCost($costPerPageSetting));?></td>
    </tr>
    <?php endforeach;?>
</table>
<br />

<h3>Excess Inventory<em><?php echo '(' . count($optimizationDevices->excess) . ')'?></em></h3>
<em>The following devices are excess devices that can still be used inside your clients fleet.</em>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>Serial / IP Address</th>
        <th>Life Page Count</th>
        <th>JIT Compatible</th>
        <th>Mono CPP</th>
        <th>Color CPP</th>
    </tr>
    <?php foreach ($optimizationDevices->excess as $device) :
    $isColor = $device->getMasterDevice()->isColor();
    ?>
    <tr>
        <td class='deviceName'><?php echo '<em>' . $device->getMasterDevice()->getManufacturer()->fullname . '</em><br/><strong>' . $device->getMasterDevice()->modelName . '</strong><br/><em>';?></td>
        <td class='deviceName'><?php echo $device->serialNumber . '<br/>' . $device->ipAddress . '</em>';?></td>
        <td><?php echo number_format($device->getLifePageCount());?></td>
        <td><?php echo ($device->reportsTonerLevels) ? 'Yes' : 'No';?></td>
        <td><?php echo $this->currency($device->calculateCostPerPage($costPerPageSetting)->monochromeCostPerPage, array('precision' => 4));?></td>
        <td><?php echo ($isColor) ? $this->currency($device->calculateCostPerPage($costPerPageSetting)->colorCostPerPage, array('precision' => 4)) : 'N/A';?></td>
    </tr>
    <?php endforeach?>
</table>
<br />

<h3>Retired Devices<em><?php echo '(' . count($optimizationDevices->retired) . ' of ' . $totalDevices . ')'?></em></h3>
<em>Devices with both low volume and age of over 8 years have been targeted for retirement. We suggest migrating the page volume to another device in your
    fleet. </em>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>Serial<br />IP Address</th>
        <th>Life Page Count</th>
        <th>Age (years)</th>
        <th>JIT Compatible</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
        <th>Mono CPP</th>
        <th>Color CPP</th>
        <th>Monthly Cost</th>
    </tr>
    <?php foreach ($optimizationDevices->retired as $device) :
    $isColor = $device->getMasterDevice()->isColor();
    ?>
    <tr>
        <td class='deviceName'><?php echo '<em>' . $device->getMasterDevice()->getManufacturer()->fullname . '</em><br/><strong>' . $device->getMasterDevice()->modelName . '</strong><br/><em>';?></td>
        <td class='deviceName'><?php echo $device->serialNumber . '<br/>' . $device->ipAddress . '</em>';?></td>
        <td><?php echo number_format($device->getLifePageCount())?></td>
        <td><?php echo number_format($device->getMasterDevice()->getAge());?></td>
        <td><?php echo ($device->reportsTonerLevels) ? 'Yes' : 'No';?>
        <td><?php echo number_format($device->getAverageMonthlyBlackAndWhitePageCount());?></td>
        <td><?php echo ($isColor) ? number_format($device->getAverageMonthlyColorPageCount()) : 'N/A';?></td>
        <td><?php echo $this->currency($device->calculateCostPerPage($costPerPageSetting)->monochromeCostPerPage, array('precision' => 4));?></td>
        <td><?php echo ($isColor) ? $this->currency($device->calculateCostPerPage($costPerPageSetting)->colorCostPerPage, array('precision' => 4)) : 'N/A';?></td>
        <td><?php echo $this->currency($device->calculateMonthlyCost($costPerPageSetting));?></td>
    </tr>
    <?php endforeach?>
</table>
<br />

<h3>Flagged Devices<em><?php echo '(' . count($optimizationDevices->flagged) . ' of ' . $totalDevices . ')'?></em></h3>
<em>These devices have been flagged for replacement based on operation reliability and not financial consideration.</em>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>Serial<br />IP Address</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
        <th>Mono CPP</th>
        <th>Color CPP</th>
        <th>Monthly Cost</th>
    </tr>
    <?php foreach ($optimizationDevices->flagged as $device) :
    $isColor = $device->getMasterDevice()->isColor();
    ?>
    <tr>
        <td class='deviceName'><?php echo '<em>' . $device->getMasterDevice()->getManufacturer()->fullname . '</em><br/><strong>' . $device->getMasterDevice()->modelName . '</strong><br/><em>';?></td>
        <td class='deviceName'><?php echo $device->serialNumber . '<br/>' . $device->ipAddress . '</em>';?></td>
        <td><?php echo number_format($device->getAverageMonthlyBlackAndWhitePageCount());?></td>
        <td><?php echo ($isColor) ? number_format($device->getAverageMonthlyColorPageCount()) : 'N/A';?></td>
        <td><?php echo $this->currency($device->calculateCostPerPage($costPerPageSetting)->monochromeCostPerPage, array('precision' => 4));?></td>
        <td><?php echo ($isColor) ? $this->currency($device->calculateCostPerPage($costPerPageSetting)->colorCostPerPage, array('precision' => 4)) : 'N/A';?></td>
        <td><?php echo $this->currency($device->calculateMonthlyCost($costPerPageSetting));?></td>
    </tr>
    <?php endforeach?>
</table>

<br />

<h3>Leased Devices<em><?php echo '(' . count($optimizationDevices->leased) . ')'?></em></h3>
<em>The following devices were flagged as leased within the ownership section.</em>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>Serial Number <br /> IP Address</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
    </tr>
    <?php foreach ($optimizationDevices->leased as $device) :
    $isColor = $device->getMasterDevice()->isColor();
    ?>
    <tr>

        <td class='deviceName'><?php echo '<em>' . $device->getMasterDevice()->getManufacturer()->fullname . '</em><br/><strong>' . $device->getMasterDevice()->modelName . '</strong><br/><em>';?></td>
        <td class='deviceName'><?php echo $device->serialNumber . '<br/>' . $device->ipAddress . '</em>';?></td>
        <td><?php echo number_format($device->getAverageMonthlyBlackAndWhitePageCount());?></td>
        <td><?php echo ($isColor) ? number_format($device->getAverageMonthlyColorPageCount()) : 'N/A';?></td>
    </tr>
    <?php endforeach?>
</table>
<br />

<h3>Excluded<em><?php echo '(' . count($optimizationDevices->excluded) . ')'?></em></h3>
<table class="rDevices">
    <tr class='header'>
        <th style='width:175px;'>Device Name</th>
        <th>IP Address</th>
        <th>Serial Number</th>
        <th>Mono AMPV</th>
        <th>Color AMPV</th>
    </tr>
    <?php foreach ($optimizationDevices->excluded as $device) : ?>
    <tr>
        <td class='deviceName'><?php echo $device->getDeviceName();?></td>
        <td><?php echo $device->ipAddress;?></td>
        <td><?php echo $device->serialNumber;?></td>
        <td><?php echo number_format($device->getAverageMonthlyBlackAndWhitePageCount());?></td>
        <td><?php echo number_format($device->getAverageMonthlyColorPageCount());?></td>
    </tr>
    <?php endforeach;?>
</table>
</div>