<?php

$settings = \MPSToolbox\Settings\Entities\DealerSettingsEntity::getDealerSettings();
$shopSettings = $settings->shopSettings;

/** @var \MPSToolbox\Entities\DealerEntity $dealer */
$dealerBranding = \MPSToolbox\Legacy\Mappers\DealerBrandingMapper::getInstance()->find(\MPSToolbox\Entities\DealerEntity::getDealerId());
if (empty($shopSettings->emailFromName)) $shopSettings->emailFromName = $dealerBranding->dealerName;
if (empty($shopSettings->emailFromAddress)) $shopSettings->emailFromAddress = $dealerBranding->dealerEmail;
if (empty($shopSettings->supplyNotifySubject)) $shopSettings->supplyNotifySubject = 'Printing Supplies Order Requirements for {{clientName}}';
if (empty($shopSettings->supplyNotifyMessage)) $shopSettings->supplyNotifyMessage = <<<HTML
<p>Hello {{contactName}}</p>
<p>We have determined that the following devices require supplies:</p>
{{devices}}
<p>
    <em>Note:</em> print quality typically degrades when supply levels are between 5 and 10%.
    Lighter prints or inaccurate color representation are often common when supply levels are low.
    Some devices will stop printing at any point below 5%.
    Delivery times should also be considered to ensure the device does not stop printing due to empty supplies.
</p>
<p>
    We have prepared a supply order for you. Please click here to login to your account and order:<br>
    {{link}}
</p>
<p>Regards,<br>
The toner management team at {$dealerBranding->dealerName}
</p>
HTML;

if (empty($shopSettings->supplyNotifySubject2)) $shopSettings->supplyNotifySubject2=$shopSettings->supplyNotifySubject;
if (empty($shopSettings->supplyNotifySubject3)) $shopSettings->supplyNotifySubject3=$shopSettings->supplyNotifySubject;
if (empty($shopSettings->supplyNotifyMessage2)) $shopSettings->supplyNotifyMessage2=$shopSettings->supplyNotifyMessage;
if (empty($shopSettings->supplyNotifyMessage3)) $shopSettings->supplyNotifyMessage3=$shopSettings->supplyNotifyMessage;

?>
<div class="container">
    <hr>
    <div class="row">
        <div class="col-sm-4">
            <h3>Client Price Levels</h3>
        </div>
        <div class="col-sm-8">
            <form method="post" action="?section=price_levels">
                <table class="table table-hover">
                    <colgroup>
                        <col width="40%">
                        <col width="40%">
                        <col width="20%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Margin (%)</th>
                            <th class="text-right"><a href="javascript:;" onclick="$('#tr-add').show()">add</a></th>
                        </tr>
                    </thead>
                    <tbody>
<?php foreach ($this->price_levels as $line) { ?>
                        <tr>
                            <td><?= $line['name'] ?></td>
                            <td><?= $line['margin'] ?></td>
                            <td>
                                <a href="javascript:;" onclick='editPriceLevel(this, <?= json_encode($line) ?>)'>edit</a>
                                <?php if (!$line['is_used']) { ?>
                                <a href="javascript:;" onclick="if (window.confirm('Delete this Price Level?')) window.location.href='/ecommerce/dealer?section=price_levels&delete=<?= $line['id'] ?>'">delete</a>
                                <?php } ?>
                            </td>
                        </tr>
<?php } ?>
                    </tbody>
                    <tfoot>
                        <tr id="tr-add" style="display:none">
                            <td><input type="text" class="form-control" name="price_level_add[name]"></td>
                            <td><input type="number" class="form-control" name="price_level_add[margin]" min="0" max="999" step="0.01"></td>
                            <td><button class="btn btn-primary" type="submit">Add</button></td>
                        </tr>
                    </tfoot>
                </table>
                <script>
                    function editPriceLevel(ahref, data) {
                        $('#tr-add').replaceWith('');
                        var tr = '<tr>';
                        tr+= '<td><input type="hidden" class="form-control" name="price_level_edit[id]" value="'+data.id+'"><input type="text" class="form-control" value="'+data.name+'" name="price_level_edit[name]"></td>';
                        tr+= '<td><input type="number" class="form-control" name="price_level_edit[margin]" value="'+data.margin+'" min="0" max="999" step="0.01"></td>';
                        tr+= '<td><button class="btn btn-primary" type="submit">Save</button></td>';
                        tr+= '</tr>';
                        $(ahref).parent().parent().replaceWith(tr);
                    }
                </script>
            </form>
        </div>
    </div>
    <hr>
    <form method="post" action="?section=main">
        <div class="row">
            <div class="col-sm-4">
                <h3>Distributors</h3>
                <p>Use this table to enable or disable automatic pricing updates from your distributors.</p>
            </div>
            <div class="col-sm-8">
                <table class="table">
                    <colgroup>
                        <col width="30%">
                        <col width="10%">
                        <col width="20%">
                        <col width="20%">
                        <col width="20%">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>Distributor</th>
                        <th>Enabled</th>
                        <th>URL</th>
                        <th>User</th>
                        <th>Pass</th>
                    </tr>
                    </thead>
                    <?php foreach ($this->distributors as $line) { ?>
                        <tr>
                            <td><?= $line['name'] ?></td>
                            <td><input type="checkbox" name="supplier[<?= $line['id'] ?>][enabled]" value="1" <?= $line['dealerId']?'checked="checked"':'' ?>></td>
                            <td><input type="text" name="supplier[<?= $line['id'] ?>][url]" class="form-control" value="<?= $line['url'] ?>"></td>
                            <td><input type="text" name="supplier[<?= $line['id'] ?>][user]" class="form-control" value="<?= $line['user'] ?>"></td>
                            <td><input type="password" name="supplier[<?= $line['id'] ?>][pass]" class="form-control" value="<?= $line['pass'] ?>"></td>
                        </tr>
                    <?php } ?>
                </table>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-4">
                <h3>E-mail</h3>
                <p>E-mail settings for supply notifications</p>
            </div>
            <div class="col-sm-8">
                <p>
                    <label>Send E-mail From</label>
                    <table style="width:100%"><tr>
                        <td>Name:&nbsp;</td><td><input xrequired="required" class="form-control" type="text" placeholder="Sender Name" name="emailFromName" value="<?= $shopSettings->emailFromName ?>"></td>
                        <td>&nbsp;</td>
                        <td>E-mail:&nbsp;</td><td><input xrequired="required" class="form-control" type="email" placeholder="E-mail Address" name="emailFromAddress" value="<?= $shopSettings->emailFromAddress ?>"></td>
                    </tr></table>
                </p>

                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">Template 1</a></li>
                    <li role="presentation"><a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab">Template 2</a></li>
                    <li role="presentation"><a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab">Template 3</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="tab1">
                        <p>
                            <label>Subject</label>
                            <input required="required" class="form-control" type="text" placeholder="E-mail Subject" name="supplyNotifySubject" value="<?= $shopSettings->supplyNotifySubject ?>">
                        </p>

                        <p>
                            <label>Message</label>
                            <textarea required="required" class="form-control" id="editor1" style="height:450px;" name="supplyNotifyMessage"><?= $shopSettings->supplyNotifyMessage ?></textarea>
                        </p>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="tab2">
                        <p>
                            <label>Subject</label>
                            <input required="required" class="form-control" type="text" placeholder="E-mail Subject" name="supplyNotifySubject2" value="<?= $shopSettings->supplyNotifySubject2 ?>">
                        </p>

                        <p>
                            <label>Message</label>
                            <textarea required="required" class="form-control" id="editor2" style="height:450px;" name="supplyNotifyMessage2"><?= $shopSettings->supplyNotifyMessage2 ?></textarea>
                        </p>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="tab3">
                        <p>
                            <label>Subject</label>
                            <input required="required" class="form-control" type="text" placeholder="E-mail Subject" name="supplyNotifySubject3" value="<?= $shopSettings->supplyNotifySubject3 ?>">
                        </p>

                        <p>
                            <label>Message</label>
                            <textarea required="required" class="form-control" id="editor3" style="height:450px;" name="supplyNotifyMessage3"><?= $shopSettings->supplyNotifyMessage3 ?></textarea>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-4">
                <h3>Shopify</h3>
                <p>Your shopify sub-domain as configured by the Administrator</p>
            </div>
            <div class="col-sm-8">
                <label>Shopify Sub-domain</label>
                <table style="width:100%">
                    <tr><td><input class="form-control" disabled="disabled" value="<?= $shopSettings->shopifyName ?>"></td><td>.myshopify.com</td></tr>
                </table>
            </div>
        </div>
        <hr>

        <div class="pull-right">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>

<script src="//cdn.ckeditor.com/4.5.5/basic/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor1');
    CKEDITOR.replace('editor2');
    CKEDITOR.replace('editor3');
</script>