<?php

/* @var $form DeviceConfigurationForm */
use MPSToolbox\Legacy\Modules\QuoteGenerator\Forms\DeviceConfigurationForm;

$form = $this->element;
?>
<form id="<?= $form->getId(); ?>" class='<?= $form->getAttrib('class') ?>' action="<?= $form->getAction() ?>" method="<?= $form->getMethod() ?>" name="<?= $form->getName() ?>">
    <h3>Device Configuration</h3>
    <?= $form->getElement('deviceName'); ?>

    <h3>Options <?= $form->getElement('add')->renderViewHelper(); ?></h3>
    <br>
    <?php if (count($form->getOptionElements()) > 0) : ?>
        <?php foreach ($form->getOptionElements() as $element) : ?>
            <div class="control-group <?= ($element->hasErrors()) ? 'error' : '' ?>">
                <?= $element->renderLabel(); ?>
                <div class="controls">
                    <div class="input-prepend input-append">
                        <span class="add-on">Qty:</span><?= trim($element->renderViewHelper()); // Trim shouldn't need to happen, but the element has a newline rendered with it.     ?>
                        <a href="<?= $this->url(['optionId' => $element->getDescription()], 'quotes.device-configurations.delete-option'); ?>" class="add-on btn btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
                    </div>
                    <?= $element->renderErrors(); ?>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else : ?>
        <p>There are no options added to this device yet.</p>
    <?php endif; ?>

    <?= $form->getElement('submit'); ?>
    <?= $form->getElement('cancel'); ?>
</form>