<?php
/* @var $optimization OptimizationViewModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationDealerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

$optimization = $this->optimization;

/* @var $hardwareOptimization HardwareOptimizationModel */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $deviceInstances DeviceInstanceModel[] */
$deviceInstances = $optimization->getDevicesGroupedByAction();

$totalNumberOfDevices = $optimization->getDevices()->purchasedDeviceInstances->getCount();

/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

// Initialize some properties
$properties = $phpWord->getDocumentProperties();
$properties->setCreator('MPS Assessment Software');
$properties->setTitle('Dealer Hardware Optimization Report');
$properties->setCategory('Dealer Report');
$properties->setLastModifiedBy('MPS Assessment Software');


/**
 * Define the different Sections
 */

// This section is landscape with 0.5" margins insead of 1"
$mainSection = $phpWord->addSection([
    'orientation'  => 'landscape',
    'marginLeft'   => 720,
    'marginRight'  => 720,
    'marginTop'    => 720,
    'marginBottom' => 720
]);

/**
 * Define Table Styles here
 */
$widthTwips       = 15840;
$header_color     = $this->wordStyles->default->tableHeaderBackgroundColor;
$sub_header_color = $this->wordStyles->default->tableSubHeaderBackgroundColor;
$even_color       = "EFEFEF";
$odd_color        = "FCFCFC";
$footer_color     = "b8cce3";
$highlight_color  = "ebc7a4";

$titlePageBackgroundColor  = My_Brand::getDealerBranding()->titlePageTitleBackgroundColor;
$titlePageBackgroundColor2 = My_Brand::getDealerBranding()->titlePageInformationBackgroundColor;
$titlePageTextColor        = My_Brand::getDealerBranding()->titlePageTitleFontColor;
$titlePageTextColor2       = My_Brand::getDealerBranding()->titlePageInformationFontColor;
$headingColor              = My_Brand::getDealerBranding()->h1FontColor;
$h2Background              = My_Brand::getDealerBranding()->h2BackgroundColor;
$h2Color                   = My_Brand::getDealerBranding()->h2FontColor;
$h3Color                   = My_Brand::getDealerBranding()->h1FontColor;

$phpWord->addFontStyle('titlepageHeaderFont', ['bold' => true, 'size' => 12]);
$phpWord->addFontStyle('documentHeader', ['bold' => true, 'size' => 16]);
$phpWord->addParagraphStyle('documentHeader', ['align' => 'center']);

$phpWord->addParagraphStyle('titleStyle1', [
    'align'      => 'center',
    'spaceAfter' => 100,
    'shading'    => [
        'fill' => $titlePageBackgroundColor,
    ]
]);
$phpWord->addParagraphStyle('titleStyle2', [
    'spaceAfter'  => 50,
    'spaceBefore' => 50,
    'bgColor'     => $titlePageBackgroundColor2
]);
$phpWord->addParagraphStyle('titleStyle3', [
    'spaceAfter' => 100,
    'tabs'       => [
        new \PhpOffice\PhpWord\Style\Tab('left', 350)
    ],
    'shading'    => [
        'fill' => $titlePageBackgroundColor2,
    ]
]);

$phpWord->addFontStyle('italic_subheading', [
    "italic" => true,
]);
$phpWord->addFontStyle('titlepage_title', [
    'size'  => 24,
    'bold'  => true,
    'color' => $titlePageTextColor
]);

$phpWord->addFontStyle('titlepage_subtitle', [
    'size'  => 16,
    'bold'  => true,
    'color' => $titlePageTextColor2
]);

$phpWord->addFontStyle('titlepage_address', [
    'size'  => 12,
    'color' => $titlePageTextColor2,
]);
$phpWord->addTitleStyle(1, [
    'size'  => 14,
    'color' => My_Brand::getDealerBranding()->h2BackgroundColor,
    'bold'  => true,
]);

$phpWord->addTitleStyle(2, [
    'size'   => 12,
    'color'  => My_Brand::getDealerBranding()->h2FontColor,
    'bold'   => true,
    'italic' => true
], [
    'shading' => [
        'fill' => My_Brand::getDealerBranding()->h2BackgroundColor,
    ]]);

// Classes that describe standard cells
$standard_cell                  = (object)[
    "even"           => [
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
        "valign"           => 'center',
    ],
    "odd"            => [
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
        "valign"           => 'center',
    ],
    "fontStyle"      => null,
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'right'
    ]
];
$standard_cell_left             = (object)[
    "even"           => [
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ],
    "odd"            => [
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ],
    "fontStyle"      => null,
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'left'
    ]
];
$standard_cell_left_device_name = (object)[
    "even"             => [
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ],
    "odd"              => [
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ],
    "manufacturerName" => (object)[
        "fontStyle"      => ['italic' => true],
        "paragraphStyle" => [
            'spaceAfter' => 0,
            'align'      => 'left'
        ],
    ],
    "modelName"        => (object)[
        "fontStyle"      => ['bold' => true],
        "paragraphStyle" => [
            'spaceAfter' => 0,
            'align'      => 'left'
        ],
    ],
];
$standard_cell_no_right_border  = (object)[
    "even"           => [
        "bgColor" => $even_color,
        "valign"  => 'center',
    ],
    "odd"            => [
        "bgColor" => $odd_color,
        "valign"  => 'center',
    ],
    "fontStyle"      => null,
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'right'
    ]
];

$standard_header_right = (object)[
    "even"           => [
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
        "valign"           => 'center',
    ],
    "odd"            => [
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
        "valign"           => 'center',
    ],
    "fontStyle"      => [
        'bold' => true,
    ],
    "paragraphStyle" => [
        'align' => 'right',
    ]
];
$standard_header       = (object)[
    "cellStyle"      => [
        'bgColor' => $header_color
    ],
    "fontStyle"      => [
        'bold' => true
    ],
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'center'
    ]
];
$standard_sub_header   = (object)[
    "cellStyle"      => [
        'bgColor' => $sub_header_color
    ],
    "fontStyle"      => [
        'bold' => true
    ],
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'center'
    ]
];

$fleetTable = (object)[
    "tablestyle"  => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "headerStyle" => [
        'bgColor' => $header_color,
    ],
    "rowstyle"    => [
        "cantSplit" => true,
    ],
    "colWidth"    => $widthTwips * 0.25,

    "span2Width"  => $widthTwips / 2,
    "spanAll"     => $widthTwips,
    "body"        => (object)[
        "rowheight"  => 500,
        "cellHeader" => $standard_header_right,
        "cell1"      => $standard_cell,
        "cell2"      => $standard_cell_no_right_border,
    ],
    "header"      => (object)[
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ]
];

$compareTable = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "headercell" => [
        "gridSpan" => 2,
        'bgColor'  => $header_color,
    ],
    "rowstyle"   => [
        "cantSplit" => true,
    ],
    "colWidth"   => $widthTwips * 0.25,

    "span2Width" => $widthTwips / 2,
    "spanAll"    => $widthTwips,
    "body"       => (object)[
        "rowheight" => 400,
        "cell1"     => $standard_cell,
        "cell2"     => $standard_cell,
        "cell3"     => $standard_cell,
        "cell4"     => $standard_cell_no_right_border,
    ],
    "header"     => (object)[
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ]
];

$replacementSpan5Width = $widthTwips * 0.5;
$replacementSpan4Width = $widthTwips * 0.3;
$replacementSpan3Width = $widthTwips * 0.2;

$replacementTable = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "cellspan5"  => [
        'gridSpan' => 5,
        'bgColor'  => $header_color
    ],
    "cellspan4"  => [
        'gridSpan' => 4,
        'bgColor'  => $header_color
    ],
    "cellspan3"  => [
        'gridSpan' => 3,
        'bgColor'  => $header_color
    ],
    "span5Width" => $replacementSpan5Width,
    "span4Width" => $replacementSpan4Width,
    "span3Width" => $replacementSpan3Width,
    "col1Width"  => $replacementSpan5Width * 0.32,
    "col2Width"  => $replacementSpan5Width * 0.2,
    "col3Width"  => $replacementSpan5Width * 0.16,
    "col4Width"  => $replacementSpan5Width * 0.16,
    "col5Width"  => $replacementSpan5Width * 0.16,
    "col6Width"  => $replacementSpan4Width * 0.4,
    "col7Width"  => $replacementSpan4Width * 0.2,
    "col8Width"  => $replacementSpan4Width * 0.2,
    "col9Width"  => $replacementSpan4Width * 0.2,
    "col10Width" => $replacementSpan3Width / 3,
    "col11Width" => $replacementSpan3Width / 3,
    "col12Width" => $replacementSpan3Width / 3,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left_device_name,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell,
        "cell4"     => $standard_cell,
        "cell5"     => (object)[
            "even"           => [
                "bgColor"          => $even_color,
                "borderRightColor" => 'DDDDDD',
                "borderRightSize"  => 20
            ],
            "odd"            => [
                "bgColor"          => $odd_color,
                "borderRightColor" => 'DDDDDD',
                "borderRightSize"  => 20
            ],
            "fontStyle"      => null,
            "paragraphStyle" => [
                'spaceAfter' => 0,
                'align'      => 'right'
            ]
        ],
        "cell6"     => $standard_cell_left_device_name,
        "cell7"     => $standard_cell,
        "cell8"     => $standard_cell,
        "cell9"     => (object)[
            "even"           => [
                "bgColor"          => $even_color,
                "borderRightColor" => 'DDDDDD',
                "borderRightSize"  => 20
            ],
            "odd"            => [
                "bgColor"          => $odd_color,
                "borderRightColor" => 'DDDDDD',
                "borderRightSize"  => 20
            ],
            "fontStyle"      => null,
            "paragraphStyle" => [
                'spaceAfter' => 0,
                'align'      => 'right'
            ]
        ],
        "cell10"    => $standard_cell,
        "cell11"    => $standard_cell,
        "cell12"    => $standard_cell_no_right_border,
    ],
    "header"     => (object)[
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ],
];

$acceptableTable   = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "rowheader"  => [
        "tblHeader" => true,
    ],
    "col1Width"  => $widthTwips * 0.20,
    "col2Width"  => $widthTwips * 0.15,
    "col3Width"  => $widthTwips * 0.092,
    "col4Width"  => $widthTwips * 0.092,
    "col5Width"  => $widthTwips * 0.092,
    "col6Width"  => $widthTwips * 0.092,
    "col7Width"  => $widthTwips * 0.092,
    "col8Width"  => $widthTwips * 0.092,
    "col9Width"  => $widthTwips * 0.092,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left_device_name,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell,
        "cell4"     => $standard_cell,
        "cell5"     => $standard_cell,
        "cell6"     => $standard_cell,
        "cell7"     => $standard_cell,
        "cell8"     => $standard_cell,
        "cell9"     => $standard_cell_no_right_border,
    ],
    "header"     => (object)[
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ],
];
$excessTable       = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "col1Width"  => $widthTwips * 0.25,
    "col2Width"  => $widthTwips * 0.15,
    "col3Width"  => $widthTwips * 0.175,
    "col4Width"  => $widthTwips * 0.175,
    "col5Width"  => $widthTwips * 0.125,
    "col6Width"  => $widthTwips * 0.125,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left_device_name,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell,
        "cell4"     => $standard_cell,
        "cell5"     => $standard_cell,
        "cell6"     => $standard_cell_no_right_border,
    ],
    "header"     => (object)[
        'header' => $standard_header,
    ],
];
$retireTable       = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "rowHeader"  => [
        "tblHeader" => true,
    ],
    "col1Width"  => $widthTwips * 0.25,
    "col2Width"  => $widthTwips * 0.15,
    "col3Width"  => $widthTwips * 0.075,
    "col4Width"  => $widthTwips * 0.075,
    "col5Width"  => $widthTwips * 0.075,
    "col6Width"  => $widthTwips * 0.075,
    "col7Width"  => $widthTwips * 0.075,
    "col8Width"  => $widthTwips * 0.075,
    "col9Width"  => $widthTwips * 0.075,
    "col10Width" => $widthTwips * 0.075,
    "body"       => (object)[
        "rowheight" => 400,
        "cell1"     => $standard_cell_left_device_name,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell,
        "cell4"     => $standard_cell,
        "cell5"     => $standard_cell,
        "cell6"     => $standard_cell,
        "cell7"     => $standard_cell,
        "cell8"     => $standard_cell,
        "cell9"     => $standard_cell,
        "cell10"    => $standard_cell_no_right_border,
    ],
    "header"     => (object)[
        'header' => $standard_header,
    ],
];
$flaggedTable      = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "rowHeader"  => [
        "tblHeader" => true,
    ],
    "col1Width"  => $widthTwips * 0.20,
    "col2Width"  => $widthTwips * 0.15,
    "col3Width"  => $widthTwips * 0.092,
    "col4Width"  => $widthTwips * 0.092,
    "col5Width"  => $widthTwips * 0.092,
    "col6Width"  => $widthTwips * 0.092,
    "col7Width"  => $widthTwips * 0.092,
    "col8Width"  => $widthTwips * 0.092,
    "col9Width"  => $widthTwips * 0.092,
    "body"       => (object)[
        "rowheight" => 400,
        "cell1"     => $standard_cell_left_device_name,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell,
        "cell4"     => $standard_cell,
        "cell5"     => $standard_cell,
        "cell6"     => $standard_cell,
        "cell7"     => $standard_cell,
        "cell8"     => $standard_cell,
        "cell9"     => $standard_cell_no_right_border,
    ],
    "header"     => (object)[
        'header' => $standard_header,
    ],
];
$leasedTable       = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50,
    ],
    "col1Width"  => $widthTwips * 0.25,
    "col2Width"  => $widthTwips * 0.25,
    "col3Width"  => $widthTwips * 0.20,
    "col4Width"  => $widthTwips * 0.15,
    "col5Width"  => $widthTwips * 0.15,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell_left,
        "cell4"     => $standard_cell,
        "cell5"     => $standard_cell_no_right_border,
    ],
    "header"     => (object)[
        'header' => $standard_header,
    ],
];
$excludedTable     = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "col1Width"  => $widthTwips * 0.25,
    "col2Width"  => $widthTwips * 0.20,
    "col3Width"  => $widthTwips * 0.20,
    "col4Width"  => $widthTwips * 0.15,
    "col5Width"  => $widthTwips * 0.15,
    "col6Width"  => $widthTwips * 0.15,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell_left,
        "cell4"     => $standard_cell,
        "cell5"     => $standard_cell_no_right_border,
        "cell6"     => $standard_cell,
    ],
    "header"     => (object)[
        'header' => $standard_header,
    ],
];
$doubleCenterTable = (object)[
    "tablestyle" => [],
    "col1Width"  => $widthTwips * 0.50,
    "col2Width"  => $widthTwips * 0.50,
    "body"       => (object)[
        "cell1" => [
            "valign" => "center"
        ],
        "cell2" => [
            "valign" => "center"
        ]
    ],
    "image"      => (object)[
        "cell1" => [
            'align' => 'right'
        ],
        "cell2" => [
            'align' => 'left'
        ],
    ]
];

$tableStyle = (object)[
    "rowheader" => [
        'tblHeader' => true,
        'cantSplit' => true,
    ],
    "rowstyle"  => [
        "cantSplit" => true,
    ],
];

/**
 * Here we put all our table styles into an object that gets passed to each of
 * the view scripts
 */
$styles                      = (object)[
    "tables" => (object)[
        "fleet"       => $fleetTable,
        "compare"     => $compareTable,
        "replacement" => $replacementTable,
        "acceptable"  => $acceptableTable,
        "excess"      => $excessTable,
        "retire"      => $retireTable,
        "flagged"     => $flaggedTable,
        "leased"      => $leasedTable,
        "excluded"    => $excludedTable,
        "twocenter"   => $doubleCenterTable,
        "tablestyle"  => $tableStyle,
    ]];
$hardwareOptimizationDevices = new OptimizationDealerModel($hardwareOptimization);
/**
 * An array of view variables to pass to the partial scripts
 */
$data = [
    "phpword"                     => $phpWord,
    "hardwareOptimization"        => $hardwareOptimization,
    "optimization"                => $optimization,
    "section"                     => $mainSection,
    "hardwareOptimizationDevices" => $hardwareOptimizationDevices,
    "graphs"                      => $this->graphs,
    "dealerLogoFile"              => $this->dealerLogoFile,
    "styles"                      => $styles,
    "deviceInstances"             => $deviceInstances,
    "totalDevices"                => $totalNumberOfDevices,
];

/**
 * Render each of the view scripts for different parts of the document
 */

$this->partial("report/dealer/optimization/docx/01_titlepage.phtml", $data);
$this->partial("report/dealer/optimization/docx/02_costanalysis.phtml", $data);
$this->partial("report/dealer/optimization/docx/03_devicesummary.phtml", $data);
$this->partial("report/dealer/optimization/docx/04_replacements.phtml", $data);
$this->partial("report/dealer/optimization/docx/05_upgrades.phtml", $data);
$this->partial("report/dealer/optimization/docx/06_acceptable.phtml", $data);
$this->partial("report/dealer/optimization/docx/07_excess.phtml", $data);
$this->partial("report/dealer/optimization/docx/08_retired.phtml", $data);
$this->partial("report/dealer/optimization/docx/09_flagged.phtml", $data);
$this->partial("report/dealer/optimization/docx/10_leased.phtml", $data);
$this->partial("report/dealer/optimization/docx/11_excluded.phtml", $data);


$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($this->phpword, 'Word2007');

$objWriter->save($this->savePath);

/**
 * Finally we write out the url to the file we just generated.
 */
echo $this->baseUrl($this->publicFileName);