<?php
/**
 * Hardware Optimization Title Page
 */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $hardwareOptimization HardwareOptimizationModel */
$hardwareOptimization = $this->hardwareOptimization;

$titleImageStyle = array('align' => 'center');

$cellStyle = array('bgColor' => My_Brand::getDealerBranding()->titlePageTitleBackgroundColor, 'width' => 15297);

// Table to fix the issue of images being different sizes
$imageTable = $section->addTable();
$imageTable->addRow(2500);
$cell = $imageTable->addCell(15000.8, array('valign' => 'center'));
$cell->addImage(PUBLIC_PATH . $this->dealerLogoFile, array(
    'align' => 'center'
));


$section->addTextBreak();

// Assessment Title

$section->addText('', null, 'titleStyle1');
$section->addText('Hardware Optimization', 'titlepage_title', 'titleStyle1');
$section->addText('', null, 'titleStyle1');

$section->addTextBreak();

$section->addText('', 'titlepage_address', 'titleStyle3');
$section->addText(sprintf("\t" . 'Prepared For: %1$s', $this->hardwareOptimization->getClient()->companyName), 'titlepage_subtitle', 'titleStyle3');

// Parse the address
$addressLines = explode("\n", $hardwareOptimization->getClient()->getAddress()->getFullAddressMultipleLines());
$addressCount = 1;
foreach ($addressLines as $line)
{
    $section->addText("\t" . $line, 'titlepage_address', 'titleStyle3');
    $addressCount++;
}
$section->addText('', 'titlepage_address', 'titleStyle3');
$section->addText(sprintf("\t Date: %s", $hardwareOptimization->getFormattedDatePrepared()), 'titlepage_address', 'titleStyle3');

// Add extra blank lines to make the grey box big
if ($addressCount < 11)
{
    for ($i = 0; $i < 11 - $addressCount; $i++)
    {
        $section->addText(' ', 'titlepage_address', 'titleStyle3');
    }
}
