<?php
/**
 * Cost Analysis - Header information
 *
 * This script contains everything that comes before the big table of
 * information in the cost analysis.
 */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

/* @var $hardwareOptimization HardwareOptimizationModel */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

// todo:kate Determine if this should be rendered in its own file and all other files renumbered accordingly
$tcStyle = $this->styles->tables->fleet;

$section->addTitle('Cost Analysis Summary', 2);

// Table with values
$tcStyle = $this->styles->tables->compare;
$table   = $section->addTable($tcStyle->tablestyle);

$table->addRow($tcStyle->body->rowheight, $this->tableStyle->rowheader);
$cell1 = $table->addCell($tcStyle->span2Width, $tcStyle->headercell);
$cell1->addText('Current Fleet', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

$cell2 = $table->addCell($tcStyle->span2Width, $tcStyle->headercell);
$cell2->addText('Optimized', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

$table->addRow($tcStyle->body->rowheight, $this->tableStyle->rowheader);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->odd)->addText('Pre-Optimized Monochrome CPP: ', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->odd)->addText($this->formatCostPerPage($hardwareOptimization->getClient()->getClientSettings()->genericSettings->targetMonochromeCostPerPage), $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->odd)->addText('Post-Optimized Monochrome CPP: ', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->odd)->addText($this->formatCostPerPage($hardwareOptimization->getClient()->getClientSettings()->optimizationSettings->optimizedTargetMonochromeCostPerPage), $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);

$table->addRow($tcStyle->body->rowheight, $this->tableStyle->rowheader);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->even)->addText('Pre-Optimized Color CPP: ', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->even)->addText($this->formatCostPerPage($hardwareOptimization->getClient()->getClientSettings()->genericSettings->targetColorCostPerPage), $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->even)->addText('Post-Optimized Color CPP: ', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->even)->addText($this->formatCostPerPage($hardwareOptimization->getClient()->getClientSettings()->optimizationSettings->optimizedTargetColorCostPerPage), $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);

$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->odd)->addText('Weighted Monochrome CPP:', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell2->odd)->addText($this->formatCostPerPage((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->monochromeCostPerPage), $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell3->odd)->addText('Weighted Monochrome CPP:', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell4->odd)->addText($this->formatCostPerPage($optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->monochromeCostPerPage), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->even)->addText('Monthly Monochrome Page Count:', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell2->even)->addText($this->formatPageVolume($optimization->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell3->even)->addText('Monthly Monochrome Page Count:', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell4->even)->addText($this->formatPageVolume($optimization->getNewPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->odd)->addText('Weighted Color CPP:', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell2->odd)->addText(($optimization->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly() > 0) ? $this->formatCostPerPage((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPage()->colorCostPerPage) : 'No color volume', $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell3->odd)->addText('Weighted Color CPP:', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell4->odd)->addText(((float)$optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage > 0) ? $this->formatCostPerPage($optimization->calculateDealerWeightedAverageMonthlyCostPerPageWithReplacements()->colorCostPerPage) : '-', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->even)->addText('Monthly Color Page Count:', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell2->even)->addText($this->formatPageVolume($optimization->getPageCounts()->getColorPageCount()->getMonthly()), $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell3->even)->addText('Monthly Color Page Count:', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell4->even)->addText($this->formatPageVolume($optimization->getNewPageCounts()->getColorPageCount()->getMonthly()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->odd)->addText('Total Cost:', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell2->odd)->addText($this->currency((float)$optimization->calculateDealerMonthlyCost()), $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell3->odd)->addText('Total Cost:', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell4->odd)->addText($this->currency((float)$optimization->calculateDealerMonthlyCostWithReplacements()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->even)->addText('Revenue:', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell2->even)->addText($this->currency((float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell3->even)->addText('Revenue:', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell4->even)->addText($this->currency((float)$optimization->calculateOptimizedDealerMonthlyRevenueUsingTargetCostPerPage()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->odd)->addText('Margin ($):', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell2->odd)->addText($this->currency((float)$optimization->calculateDealerMonthlyProfitUsingTargetCostPerPage()), $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell3->odd)->addText('Margin ($):', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell4->odd)->addText($this->currency((float)$optimization->calculateDealerMonthlyProfitUsingTargetCostPerPageAndReplacements()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell1->even)->addText('Margin (%):', $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell2->even)->addText(number_format(\Tangent\Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCost(), (float)$optimization->calculateDealerMonthlyRevenueUsingTargetCostPerPage()), 2) . '%', $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell3->even)->addText('Margin (%):', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
$table->addCell($tcStyle->colWidth, $tcStyle->body->cell4->even)->addText(number_format(\Tangent\Accounting::reverseEngineerMargin((float)$optimization->calculateDealerMonthlyCostWithReplacements(), (float)$optimization->calculateOptimizedDealerMonthlyRevenueUsingTargetCostPerPage()), 2) . '%', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

$section->addPageBreak();