<?php
/**
 * Device Summary - Header information
 *
 * This script display the two graphs the displays the summary of devices after HWO
 */
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

$section->addTextBreak();
$section->addTitle('Device Summary', 2);

$tcStyle    = $this->styles->tables->twocenter;
$imageTable = $section->addTable($tcStyle->tablestyle);
$imageTable->addRow();
$imageTable->addCell($tcStyle->col1Width, $tcStyle->body->cell1)->addImage($this->graphs [0], $tcStyle->image->cell1);
$imageTable->addCell($tcStyle->col2Width, $tcStyle->body->cell2)->addImage($this->graphs [1], $tcStyle->image->cell2);

$section->addTextBreak();