<?php
/**
 * Device Summary - Header information
 *
 * This script display the two graphs the displays the summary of devices after HWO
 */
/* @var $section PHPWord_Section */
$section = $this->section;

$section->addTextBreak();
$section->addText($this->translate('Device Summary'), array('bold' => true, 'size' => 12));

$tcStyle = $this->styles->tables->twocenter;
$imageTable = $section->addTable($tcStyle->tablestyle);
$imageTable->addRow();
$imageTable->addCell($tcStyle->col1Width, $tcStyle->body->cell1)->addImage($this->graphs [0], $tcStyle->image->cell1);
$imageTable->addCell($tcStyle->col2Width, $tcStyle->body->cell2)->addImage($this->graphs [1], $tcStyle->image->cell2);

$section->addTextBreak();