<?php
/**
 * Replacements- Header information
 *
 * This scripts will show the appropriate graphs for HWO replacement devices
 * as well as related devices information
 */

/* @var $section PHPWord_Section */
$section = $this->section;
/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;
/* @var $hardwareOptimizationDevices Hardwareoptimization_Model_Optimization_Dealer */
$hardwareOptimizationDevices = $this->hardwareOptimizationDevices;
$costPerPageSetting          = $optimization->getCostPerPageSettingForDealer();

$section->addTextBreak();
$headerTextRun = $section->createTextRun();
$headerTextRun->addText('Suggested Replacement Devices', 'titlepageHeaderFont');
$headerTextRun->addText(' (' . count($hardwareOptimizationDevices->replaced) . ' of ' . $hardwareOptimizationDevices->getDeviceCount() . ')');
$costThreshold = number_format($hardwareOptimization->getHardwareOptimizationSetting()->costThreshold);
$section->addText('The following devices have been targeted for replacement, either for a monthly cost savings greater than {$costThreshold} or manual replacement.');

// Table with values
$tcStyle = $this->styles->tables->replacement;
$table   = $section->addTable($tcStyle->tablestyle);
// Table header
$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->span5Width, $tcStyle->header->header->cellStyle, 5)->addText('Current', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->span4Width, $tcStyle->header->header->cellStyle, 4)->addText('Replacement', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->span3Width, $tcStyle->header->header->cellStyle, 3)->addText('Statistics', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
// Table sub header
$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->header->sub_header->cellStyle)->addText('Device Name', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->header->sub_header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->header->sub_header->cellStyle)->addText('Mono CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->header->sub_header->cellStyle)->addText('Color CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col5Width, $tcStyle->header->sub_header->cellStyle)->addText('Monthly Cost', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col6Width, $tcStyle->header->sub_header->cellStyle)->addText('Device Name', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col7Width, $tcStyle->header->sub_header->cellStyle)->addText('Mono CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col8Width, $tcStyle->header->sub_header->cellStyle)->addText('Color CPP', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col9Width, $tcStyle->header->sub_header->cellStyle)->addText('Monthly Cost', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col10Width, $tcStyle->header->sub_header->cellStyle)->addText('Mono AMPV', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col11Width, $tcStyle->header->sub_header->cellStyle)->addText('Color AMPV', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);
$table->addCell($tcStyle->col12Width, $tcStyle->header->sub_header->cellStyle)->addText('Cost Delta', $tcStyle->header->sub_header->fontStyle, $tcStyle->header->sub_header->paragraphStyle);

// Begin with data rows
foreach ($hardwareOptimizationDevices->replaced as $device)
{
    $masterDevice      = $device->getMasterDevice();
    $replacementDevice = $device->getReplacementMasterDevice();
    $isColor           = ($masterDevice->tonerConfigId !== Proposalgen_Model_TonerConfig::BLACK_ONLY) ? true : false;
    $style             = ($this->cycle(array($tcStyle->body->cell1->odd, $tcStyle->body->cell1->even))->next()->current());

    $table->addRow($tcStyle->body->rowheight);
    $cell = $table->addCell($tcStyle->collWidth, $style);
    $cell->addText($device->getMasterDevice()->getManufacturer()->fullname, $tcStyle->body->cell1->manufacturerName->fontStyle, $tcStyle->body->cell1->manufacturerName->paragraphStyle);
    $cell->addText($device->getMasterDevice()->modelName, $tcStyle->body->cell1->modelName->fontStyle, $tcStyle->body->cell1->modelName->paragraphStyle);

    $cell2 = $table->addCell($tcStyle->col2Width, $style);
    $cell2->addText($device->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
    $cell2->addText($device->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);

    $table->addCell($tcStyle->col3Width, $style)->addText($this->currency($device->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->monochromeCostPerPage, array('precision' => 4)), $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $style)->addText(($isColor) ? $this->currency($device->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->colorCostPerPage, array('precision' => 4)) : 'N/A', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $style)->addText($this->currency($device->calculateMonthlyCost($costPerPageSetting)), $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);

    $cell6 = $table->addCell($tcStyle->col6Width, $style);
    $cell6->addText($replacementDevice->getManufacturer()->fullname, $tcStyle->body->cell6->manufacturerName->fontStyle, $tcStyle->body->cell6->manufacturerName->paragraphStyle);
    $cell6->addText($replacementDevice->modelName, $tcStyle->body->cell6->modelName->fontStyle, $tcStyle->body->cell6->modelName->paragraphStyle);


    $table->addCell($tcStyle->col7Width, $style)->addText($this->currency($replacementDevice->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->getCostOfInkAndTonerPerPage()->monochromeCostPerPage, array('precision' => 4)), $tcStyle->body->cell7->fontStyle, $tcStyle->body->cell7->paragraphStyle);
    $table->addCell($tcStyle->col8Width, $style)->addText(($isColor) ? $this->currency($replacementDevice->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->getCostOfInkAndTonerPerPage()->colorCostPerPage, array('precision' => 4)) : 'N/A', $tcStyle->body->cell8->fontStyle, $tcStyle->body->cell8->paragraphStyle);
    $table->addCell($tcStyle->col9Width, $style)->addText($this->currency($device->calculateMonthlyCost($costPerPageSetting, $replacementDevice)), $tcStyle->body->cell9->fontStyle, $tcStyle->body->cell9->paragraphStyle);
    $table->addCell($tcStyle->col10Width, $style)->addText(number_format($device->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell10->fontStyle, $tcStyle->body->cell10->paragraphStyle);
    $table->addCell($tcStyle->col11Width, $style)->addText(($isColor) ? number_format($device->getPageCounts()->getColorPageCount()->getMonthly()) : 'N/A', $tcStyle->body->cell11->fontStyle, $tcStyle->body->cell11->paragraphStyle);
    $table->addCell($tcStyle->col12Width, $style)->addText($this->currency($device->calculateMonthlyCost($costPerPageSetting) - $device->calculateMonthlyCost($costPerPageSetting, $device->getReplacementMasterDevice())), $tcStyle->body->cell12->fontStyle, $tcStyle->body->cell12->paragraphStyle);
}