<?php
/**
 * Acceptable - Header information
 *
 * This scripts will show the appropriate graphs for HWO Acceptable devices
 * as well as related devices information
 */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationDeviceInstanceModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $acceptableDeviceInstances DeviceInstanceModel[] */
$acceptableDeviceInstances = $this->deviceInstances[HardwareOptimizationDeviceInstanceModel::ACTION_KEEP];

$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();

$section->addTextBreak();
$section->addTitle(sprintf('Acceptable Devices (%1$s of %2$s)', number_format(count($acceptableDeviceInstances)), number_format($this->totalDevices)), 2);

if (count($acceptableDeviceInstances) > 0)
{
    $section->addText("The following devices have been deemed productive and fall within the target cost per page.");

// Table with values
    $tcStyle = $this->styles->tables->acceptable;
    $table   = $section->addTable($tcStyle->tablestyle);

// Table header
    $table->addRow($tcStyle->body->rowheight, $tcStyle->rowheader);
    $table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText('Device Name', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText('Mono AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText('Color AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $tcStyle->header->header->cellStyle)->addText('Life Page Count', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col6Width, $tcStyle->header->header->cellStyle)->addText('Device Age', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col7Width, $tcStyle->header->header->cellStyle)->addText('Mono CPP', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col8Width, $tcStyle->header->header->cellStyle)->addText('Color CPP', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col9Width, $tcStyle->header->header->cellStyle)->addText('Monthly Cost', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

// Begin with data rows
    foreach ($acceptableDeviceInstances as $deviceInstance)
    {
        $table->addRow($tcStyle->body->rowheight, $this->styles->tables->tablestyle->rowstyle);
        $style = ($this->cycle(array($tcStyle->body->cell1->odd, $tcStyle->body->cell1->even))->next()->current());

        $cell = $table->addCell($tcStyle->col1Width, $style);
        $cell->addText($deviceInstance->getMasterDevice()->getManufacturer()->fullname, $tcStyle->body->cell1->manufacturerName->fontStyle, $tcStyle->body->cell1->manufacturerName->paragraphStyle);
        $cell->addText($deviceInstance->getMasterDevice()->modelName, $tcStyle->body->cell1->modelName->fontStyle, $tcStyle->body->cell1->modelName->paragraphStyle);

        $cell2 = $table->addCell($tcStyle->col2Width, $style);
        $cell2->addText($deviceInstance->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
        $cell2->addText($deviceInstance->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);

        $table->addCell($tcStyle->col3Width, $style)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);

        $table->addCell($tcStyle->col4Width, $style)->addText(($deviceInstance->getMasterDevice()->isColor()) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : ' - ', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

        $table->addCell($tcStyle->col5Width, $style)->addText(number_format($deviceInstance->getMeter()->endMeterLife), $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);

        $table->addCell($tcStyle->col6Width, $style)->addText($deviceInstance->getAge() . 'y', $tcStyle->body->cell6->fontStyle, $tcStyle->body->cell6->paragraphStyle);

        $table->addCell($tcStyle->col7Width, $style)->addText($this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->monochromeCostPerPage), $tcStyle->body->cell7->fontStyle, $tcStyle->body->cell7->paragraphStyle);

        $table->addCell($tcStyle->col8Width, $style)->addText(($deviceInstance->getMasterDevice()->isColor()) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($costPerPageSetting)->getCostPerPage()->colorCostPerPage) : ' - ', $tcStyle->body->cell8->fontStyle, $tcStyle->body->cell8->paragraphStyle);

        $table->addCell($tcStyle->col9Width, $style)->addText($this->currency($deviceInstance->calculateMonthlyCost($costPerPageSetting)), $tcStyle->body->cell9->fontStyle, $tcStyle->body->cell9->paragraphStyle);
    }
}
else
{
    $section->addText("There are currently no devices deemed productive and that fall within the target cost per page.", 'italic_subheading');
}