<?php
/**
 * Excesss - Header information
 *
 * This scripts will show the appropriate graphs for HWO Excesss devices
 * as well as related devices information
 */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationDeviceInstanceModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $excessDeviceInstances DeviceInstanceModel[] */
$excessDeviceInstances = $this->deviceInstances[HardwareOptimizationDeviceInstanceModel::ACTION_REPLACE];

$section->addTextBreak();
$section->addTitle(sprintf('Excess Inventory (%1$s)', number_format(count($excessDeviceInstances))), 2);

if (count($excessDeviceInstances) > 0)
{
    $section->addText("The following devices are excess devices that can still be used inside your client's fleet.");

// Table with values
    $tcStyle = $this->styles->tables->excess;
    $table   = $section->addTable($tcStyle->tablestyle);
// Table header
    $table->addRow($tcStyle->body->rowheight, $this->styles->tables->tablestyle->rowheader);
    $table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText('Device Name', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText(sprintf('%1$s Compatible', My_Brand::$jit), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText('Life Page Count', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $tcStyle->header->header->cellStyle)->addText('Mono CPP', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col6Width, $tcStyle->header->header->cellStyle)->addText('Color CPP', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

// Begin with data rows
    foreach ($excessDeviceInstances as $deviceInstance)
    {
        $style = ($this->cycle([$tcStyle->body->cell1->odd, $tcStyle->body->cell1->even])->next()->current());

        $table->addRow($tcStyle->body->rowheight, $this->styles->tables->tablestyle->rowstyle);
        $cell = $table->addCell($tcStyle->collWidth, $style);
        $cell->addText($deviceInstance->getMasterDevice()->getManufacturer()->fullname, $tcStyle->body->cell1->manufacturerName->fontStyle, $tcStyle->body->cell1->manufacturerName->paragraphStyle);
        $cell->addText($deviceInstance->getMasterDevice()->modelName, $tcStyle->body->cell1->modelName->fontStyle, $tcStyle->body->cell1->modelName->paragraphStyle);

        $cell2 = $table->addCell($tcStyle->col2Width, $style);
        $cell2->addText($deviceInstance->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
        $cell2->addText($deviceInstance->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);

        $table->addCell($tcStyle->col3Width, $style)->addText(($deviceInstance->isCapableOfReportingTonerLevels) ? 'Yes' : 'No', $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);

        $table->addCell($tcStyle->col4Width, $style)->addText(number_format($deviceInstance->getMeter()->endMeterLife), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

        $table->addCell($tcStyle->col5Width, $style)->addText($this->formatCostPerPage($deviceInstance->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->getCostPerPage()->monochromeCostPerPage), $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);

        $table->addCell($tcStyle->col6Width, $style)->addText(($deviceInstance->getMasterDevice()->isColor()) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->getCostPerPage()->colorCostPerPage) : ' - ', $tcStyle->body->cell6->fontStyle, $tcStyle->body->cell6->paragraphStyle);
    }
}
else
{
    $section->addText("There are currently no excess devices that can still be used inside your client's fleet.", 'italic_subheading');
}