<?php
/**
 * Flagged - Header information
 *
 * This scripts will show the appropriate graphs for HWO Flagged devices
 * as well as related devices information
 */

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $flaggedDeviceInstances Proposalgen_Model_DeviceInstance[] */
$flaggedDeviceInstances = $this->deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_DNR];

$section->addTextBreak();
$section->addTitle(sprintf('Devices Flagged as Do Not Repair (%1$s of %2$s)', number_format(count($flaggedDeviceInstances)), number_format($this->totalDevices)), 2);

if (count($flaggedDeviceInstances) > 0)
{
    $section->addText('These devices have been flagged for replacement upon breakdown based on operational reliability and not financial considerations.');

// Table with values
    $tcStyle = $this->styles->tables->flagged;
    $table   = $section->addTable($tcStyle->tablestyle);

// Table header
    $table->addRow($tcStyle->body->rowheight, $this->styles->tables->tablestyle->rowheader);
    $table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText('Device Name', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText('Mono AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText('Color AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $tcStyle->header->header->cellStyle)->addText('Life Page Count', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col6Width, $tcStyle->header->header->cellStyle)->addText('Device Age', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col7Width, $tcStyle->header->header->cellStyle)->addText('Mono CPP', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col8Width, $tcStyle->header->header->cellStyle)->addText('Color CPP', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col9Width, $tcStyle->header->header->cellStyle)->addText('Monthly Cost', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

// Begin with data rows
    foreach ($flaggedDeviceInstances as $deviceInstance)
    {
        $style = ($this->cycle(array($tcStyle->body->cell1->odd, $tcStyle->body->cell1->even))->next()->current());

        $table->addRow($tcStyle->body->rowheight, $this->styles->tables->tablestyle->rowstyle);
        $cell = $table->addCell($tcStyle->collWidth, $style);
        $cell->addText($deviceInstance->getMasterDevice()->getManufacturer()->fullname, $tcStyle->body->cell1->manufacturerName->fontStyle, $tcStyle->body->cell1->manufacturerName->paragraphStyle);
        $cell->addText($deviceInstance->getMasterDevice()->modelName, $tcStyle->body->cell1->modelName->fontStyle, $tcStyle->body->cell1->modelName->paragraphStyle);

        $cell2 = $table->addCell($tcStyle->col2Width, $style);
        $cell2->addText($deviceInstance->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
        $cell2->addText($deviceInstance->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);

        $table->addCell($tcStyle->col3Width, $style)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);

        $table->addCell($tcStyle->col4Width, $style)->addText(($deviceInstance->getMasterDevice()->isColor()) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : ' - ', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

        $table->addCell($tcStyle->col5Width, $style)->addText(number_format($deviceInstance->getMeter()->endMeterLife), $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);

        $table->addCell($tcStyle->col6Width, $style)->addText($deviceInstance->getAge() . 'y', $tcStyle->body->cell6->fontStyle, $tcStyle->body->cell6->paragraphStyle);

        $table->addCell($tcStyle->col7Width, $style)->addText($this->formatCostPerPage($deviceInstance->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->getCostPerPage()->monochromeCostPerPage), $tcStyle->body->cell7->fontStyle, $tcStyle->body->cell7->paragraphStyle);

        $table->addCell($tcStyle->col8Width, $style)->addText(($deviceInstance->getMasterDevice()->isColor()) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->getCostPerPage()->colorCostPerPage) : ' - ', $tcStyle->body->cell8->fontStyle, $tcStyle->body->cell8->paragraphStyle);

        $table->addCell($tcStyle->col9Width, $style)->addText($this->currency($deviceInstance->calculateMonthlyCost($optimization->getCostPerPageSettingForDealer())), $tcStyle->body->cell9->fontStyle, $tcStyle->body->cell9->paragraphStyle);
    }
}
else
{
    $section->addText("There are no devices currently flagged for replacement upon breakdown.", 'italic_subheading');
}