<?php
/**
 * Retired - Header information
 *
 * This scripts will show the appropriate graphs for HWO Retired devices
 * as well as related devices information
 */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationDeviceInstanceModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;


/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $retiredDeviceInstances DeviceInstanceModel[] */
$retiredDeviceInstances = $this->deviceInstances[HardwareOptimizationDeviceInstanceModel::ACTION_RETIRE];

$section->addTextBreak();
$section->addTitle(sprintf('Retired Devices (%1$s of %2$s)', number_format(count($retiredDeviceInstances)), number_format($this->totalDevices)), 2);

if (count($retiredDeviceInstances) > 0)
{
    $section->addText("Devices with both low volume and age of over 8 years have been targeted for retirement. We suggest migrating page volumes to other
devices in your fleet. ");

// Table with values
    $tcStyle = $this->styles->tables->retire;
    $table   = $section->addTable($tcStyle->tablestyle);
// Table header
    $table->addRow($tcStyle->body->rowheight, $this->styles->tables->tablestyle->rowheader);
    $table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText('Device Name', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText(sprintf('%1$s Compatible', My_Brand::$jit), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText('Mono AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $tcStyle->header->header->cellStyle)->addText('Color AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col6Width, $tcStyle->header->header->cellStyle)->addText('Life Page Count', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col7Width, $tcStyle->header->header->cellStyle)->addText('Device Age', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col8Width, $tcStyle->header->header->cellStyle)->addText('Mono CPP', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col9Width, $tcStyle->header->header->cellStyle)->addText('Color CPP', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col10Width, $tcStyle->header->header->cellStyle)->addText('Monthly Cost', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

// Begin with data rows
    foreach ($retiredDeviceInstances as $deviceInstance)
    {
        $style = ($this->cycle(array($tcStyle->body->cell1->odd, $tcStyle->body->cell1->even))->next()->current());

        $table->addRow($tcStyle->body->rowheight, $this->styles->tables->tablestyle->rowstyle);
        $cell = $table->addCell($tcStyle->collWidth, $style);
        $cell->addText($deviceInstance->getMasterDevice()->getManufacturer()->fullname, $tcStyle->body->cell1->manufacturerName->fontStyle, $tcStyle->body->cell1->manufacturerName->paragraphStyle);
        $cell->addText($deviceInstance->getMasterDevice()->modelName, $tcStyle->body->cell1->modelName->fontStyle, $tcStyle->body->cell1->modelName->paragraphStyle);

        $cell2 = $table->addCell($tcStyle->col2Width, $style);
        $cell2->addText($deviceInstance->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
        $cell2->addText($deviceInstance->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);

        $table->addCell($tcStyle->col3Width, $style)->addText(($deviceInstance->isCapableOfReportingTonerLevels) ? 'Yes' : 'No', $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);

        $table->addCell($tcStyle->col4Width, $style)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell6->fontStyle, $tcStyle->body->cell6->paragraphStyle);

        $table->addCell($tcStyle->col5Width, $style)->addText(($deviceInstance->getMasterDevice()->isColor()) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : ' - ', $tcStyle->body->cell7->fontStyle, $tcStyle->body->cell7->paragraphStyle);

        $table->addCell($tcStyle->col6Width, $style)->addText(number_format($deviceInstance->getMeter()->endMeterLife), $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);

        $table->addCell($tcStyle->col7Width, $style)->addText(number_format($deviceInstance->getAge()) . 'y', $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);

        $table->addCell($tcStyle->col8Width, $style)->addText($this->formatCostPerPage($deviceInstance->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->getCostPerPage()->monochromeCostPerPage), $tcStyle->body->cell8->fontStyle, $tcStyle->body->cell8->paragraphStyle);

        $table->addCell($tcStyle->col9Width, $style)->addText(($deviceInstance->getMasterDevice()->isColor()) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($optimization->getCostPerPageSettingForDealer())->getCostPerPage()->colorCostPerPage) : ' - ', $tcStyle->body->cell9->fontStyle, $tcStyle->body->cell9->paragraphStyle);

        $table->addCell($tcStyle->col10Width, $style)->addText($this->currency($deviceInstance->calculateMonthlyCost($optimization->getCostPerPageSettingForDealer())), $tcStyle->body->cell10->fontStyle, $tcStyle->body->cell10->paragraphStyle);
    }
}
else
{
    $section->addText("There are no devices currently targeted for retirement.", 'italic_subheading');
}