<?php
/**
 * Leased - Header information
 *
 * This scripts will show the appropriate graphs for HWO Leased devices
 * as well as related devices information
 */


/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

$leasedDeviceInstances = $optimization->getDevices()->leasedDeviceInstances->getDeviceInstances();

$costPerPageSetting = $optimization->getCostPerPageSettingForDealer();

$section->addTextBreak();
$headerTextRun = $section->addTextRun();
$headerTextRun->addText('Leased Devices', 'titlepageHeaderFont');
$headerTextRun->addText(sprintf(' (%1$s)', number_format(count($leasedDeviceInstances))));
$section->addText("The following devices have been deemed productive and fall within the target costs per pages.");

// Table with values
$tcStyle = $this->styles->tables->leased;
$table   = $section->addTable($tcStyle->tablestyle);

// Table header
$table->addRow($tcStyle->body->rowheight,$this->styles->tables->tablestyle->rowheader);
$table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText('Device Name', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText('Serial Number', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText('IP Address', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText('Mono AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col5Width, $tcStyle->header->header->cellStyle)->addText('Color AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

// Begin with data rows
foreach ($leasedDeviceInstances as $deviceInstance)
{
    $table->addRow($tcStyle->body->rowheight,$this->styles->tables->tablestyle->rowstyle);
    $style = ($this->cycle(array($tcStyle->body->cell1->odd, $tcStyle->body->cell1->even))->next()->current());

    $table->addCell($tcStyle->col1Width, $style)->addText($deviceInstance->getDeviceName(), $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $style)->addText($deviceInstance->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $style)->addText($deviceInstance->ipAddress, $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $style)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $style)->addText(($deviceInstance->getMasterDevice()->isColor()) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : 'N/A', $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);
}