<?php
/**
 * excluded - Header information
 *
 * This scripts will show the appropriate graphs for HWO excluded devices
 * as well as related devices information
 */

/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

$excludedDeviceInstances = $optimization->getDevices()->excludedDeviceInstances->getDeviceInstances();

$unmappedInstances = $optimization->getDevices()->unmappedDeviceInstances->getDeviceInstances();

$totalNumberOfDevices = $optimization->getDevices()->excludedDeviceInstances->getCount() + $optimization->getDevices()->unmappedDeviceInstances->getCount();


$section->addTextBreak();
$headerTextRun = $section->createTextRun(array("spaceAfter" => 0));
$headerTextRun->addText('Excluded Devices', 'titlepageHeaderFont');
$headerTextRun->addText(sprintf(' (%1$s)', number_format($totalNumberOfDevices)));
$section->addText("Devices that have either been manually excluded or haven't been mapped during previous steps.");

// Table with values
$tcStyle = $this->styles->tables->excluded;
$table   = $section->addTable($tcStyle->tablestyle);
// Table header
$table->addRow($tcStyle->body->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText('Device Name', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText('Serial Number', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText('IP Address', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText('Mono AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col5Width, $tcStyle->header->header->cellStyle)->addText('Color AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
$table->addCell($tcStyle->col6Width, $tcStyle->header->header->cellStyle)->addText('Reason', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);

// Begin with data rows
foreach ($excludedDeviceInstances as $deviceInstance)
{
    $table->addRow($tcStyle->body->rowheight);
    $style = ($this->cycle(array($tcStyle->body->cell1->odd, $tcStyle->body->cell1->even))->next()->current());

    $table->addRow($tcStyle->body->rowheight);
    $table->addCell($tcStyle->col1Width, $style)->addText($deviceInstance->getDeviceName(), $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $style)->addText($deviceInstance->serialNumber, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $style)->addText($deviceInstance->ipAddress, $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $style)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $style)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()), $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);
    $table->addCell($tcStyle->col6Width, $style)->addText("Manually Excluded", $tcStyle->body->cell6->fontStyle, $tcStyle->body->cell6->paragraphStyle);
}

foreach ($unmappedInstances as $deviceInstance)
{
    $table->addRow($tcStyle->body->rowheight);
    $style = ($this->cycle(array($tcStyle->body->cell1->odd, $tcStyle->body->cell1->even))->next()->current());

    $table->addRow($tcStyle->body->rowheight);
    $table->addCell($tcStyle->col1Width, $style)->addText($deviceInstance->getDeviceName(), $tcStyle->body->cell1->fontStyle, $tcStyle->body->cell1->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $style)->addText($deviceInstance->ipAddress, $tcStyle->body->cell2->fontStyle, $tcStyle->body->cell2->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $style)->addText($deviceInstance->serialNumber, $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $style)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $style)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()), $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);
    $table->addCell($tcStyle->col6Width, $style)->addText("Not Mapped", $tcStyle->body->cell6->fontStyle, $tcStyle->body->cell6->paragraphStyle);

}