<?php
/* @var $proposal Assessment_ViewModel_Assessment */
$proposal = $this->proposal;
/**
	REPLACEMENT DEVICE VARIABLES
 */
$replacementTypes[Proposalgen_Model_ReplacementDevice::REPLACEMENT_BW] = 'MONOCHROME';
$replacementTypes[Proposalgen_Model_ReplacementDevice::REPLACEMENT_BWMFP] = 'MONOCHROME MFP';
$replacementTypes[Proposalgen_Model_ReplacementDevice::REPLACEMENT_COLOR] = 'COLOR';
$replacementTypes[Proposalgen_Model_ReplacementDevice::REPLACEMENT_COLORMFP] = 'COLOR MFP';

$printerTypes[Proposalgen_Model_ReplacementDevice::REPLACEMENT_BW] = 'Monochrome printer(s)';
$printerTypes[Proposalgen_Model_ReplacementDevice::REPLACEMENT_BWMFP] = 'Monochrome MFP(s)';
$printerTypes[Proposalgen_Model_ReplacementDevice::REPLACEMENT_COLOR] = 'Color printer(s)';
$printerTypes[Proposalgen_Model_ReplacementDevice::REPLACEMENT_COLORMFP] = 'Color MFP(s)';

$replacementDevices = $proposal->getReplacementDevices();

$devicesToBeReplaced[Proposalgen_Model_ReplacementDevice::REPLACEMENT_BW] = $proposal->getDevicesToBeReplaced()->BlackAndWhite;
$devicesToBeReplaced[Proposalgen_Model_ReplacementDevice::REPLACEMENT_BWMFP] = $proposal->getDevicesToBeReplaced()->BlackAndWhiteMFP;
$devicesToBeReplaced[Proposalgen_Model_ReplacementDevice::REPLACEMENT_COLOR] = $proposal->getDevicesToBeReplaced()->Color;
$devicesToBeReplaced[Proposalgen_Model_ReplacementDevice::REPLACEMENT_COLORMFP] = $proposal->getDevicesToBeReplaced()->ColorMFP;


$reportHasDevicesToReplace = false;
foreach ($devicesToBeReplaced as $deviceList)
{
    if (count($deviceList) > 0)
    {
        $reportHasDevicesToReplace = true;
        break;
    }
}
if ($reportHasDevicesToReplace) : // See "endif; // $reportHasDevicesToReplace"  for the end
?>
		<div class="h1">Solution 2: Hybrid Program of PrintIQ&reg; and PrintIQ Plus&reg;</div>
		<p style="margin-bottom: 10pt;">There is no need to invest in expensive printing hardware. Our PrintIQ Plus program provides you with an economical flat-rate
		option to replace your old, expensive hardware with equipment that has the features and functionality you need. Remaining devices can be managed under our PrintIQ program.</p>
		
		<div class="pheader">Program Components</div>
		<p style="margin-bottom: 8pt;">Get new printing equipment on a flat monthly rate with the PrintIQ&reg; Plus program:</p>
		<ul class="bold">
			<li>Starting at $99/month</li>
			<li>Includes hardware and all related supplies and service</li>
			<li>Equipment you are keeping can be transferred to PrintIQ&reg;</li>
		</ul>
		
		<div class="pheader">Recommended Hardware Replacements</div>
		<p>Based on our assessment of your printing environment, we have determined which devices are costing
		you the most on a monthly basis. The following recommendations maintain your current levels of copy,
		scan and fax functionality, but you may choose to upgrade your hardware to add more of these
		productivity-enhancing features.</p>

<?php foreach ($replacementDevices as $ctr => $replacementDevice) :
	$printIQCost = 0; $replacementSavings = 0; $currentCost = 0;?>
	<?php if (count($devicesToBeReplaced[$ctr]) > 0) :?>
        <?php echo $this->noBreakStart; ?>
			<p style="margin-bottom: 10pt;">We recommend replacing the following <strong><?php echo count($devicesToBeReplaced[$ctr]); ?></strong> <?php echo $printerTypes[$ctr]?> listed below with the <strong><?php echo $replacementDevice->getMasterDevice()->getFullDeviceName(); ?></strong>,which offers the following benefits:</p>
    		<ul>
    			<li><strong>Flat monthly rate of $<?php echo number_format($replacementDevice->monthlyRate)?> for up to 10,000 pages</strong></li>
    			<li>Prints up to <?php echo $replacementDevice->printSpeed; ?> pages per minute in monochrome</li>
    			<li>Up to <?php echo $replacementDevice->resolution; ?> resolution</li>
    			<?php if($replacementDevice->getMasterDevice()->isDuplex) :?>
    					<li>Standard duplexing</li>
    			<?php endif; ?>
    			<li>ENERGY STAR qualified</li>
    		</ul>
    		<table class="genericTable">
    			<thead>
    				<tr class="center">
    					<th width="160">Device Name</th>
    					<th width="120">Serial No.</th>
    					<th width="70">Monthly <br />Volume</th>
    					<th width="60">Current <br/>Annual <br/>Cost*</th>
    					<th width="60">PrintIQ&reg; Plus <br/>Annual Cost</th>
    					<th width="70">Annual <br/>Replacement <br/>Savings</th>
    				</tr>
    			</thead>
    			<tbody>
    
    				<?php foreach ($devicesToBeReplaced[$ctr] as $deviceInstance) : /* @var $deviceInstance Proposalgen_Model_DeviceInstance */ ?>
    				<?php $SerialNo = ($deviceInstance->serialNumber === "") ? 'Unknown' : $deviceInstance->serialNumber; ?>
    				<?php $modelName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getUploadDataCollectorRow()->modelName) ?>
    				<tr class="center">
    					<td class="left"><?php echo $deviceInstance->getMasterDevice()->getManufacturer()->fullname; ?><br/><?php echo $modelName ?></td>
    					<td><?php echo $SerialNo ?></td>
    					<td><?php echo number_format($deviceInstance->getAverageMonthlyPageCount()); ?></td>
    					<td>$<?php echo number_format($deviceInstance->getMonthlyRate() * 12); ?></td>
    					<td>$<?php echo number_format($replacementDevice->monthlyRate * 12); ?></td>
    					<td class="red">$<?php echo number_format(($deviceInstance->getMonthlyRate() * 12) - ($replacementDevice->monthlyRate * 12)); ?></td>
    				</tr>
    				<?php
                            $replacementSavings += ($deviceInstance->getMonthlyRate() * 12) - ($replacementDevice->monthlyRate * 12);
    					    $currentCost += $deviceInstance->getMonthlyRate() * 12;
    					    $printIQCost += $replacementDevice->monthlyRate * 12;
    				endforeach; ?>
    				<tr class="bold center">
    					<td colspan="3" class="right">TOTAL</td>
    					<td>$<?php echo number_format($currentCost); ?></td>
    					<td>$<?php echo number_format($printIQCost); ?></td>
    					<td class="red">$<?php echo number_format($replacementSavings); ?></td>
    				</tr>
    			</tbody>
    		</table>
    		<em>* Monthly cost includes both toner and non-toner expenses such as service, hardware and administration.</em>
        <?php echo $this->noBreakEnd; ?>
    	<br />
    	<br />
    <?php endif; ?>
<?php endforeach; ?>
		
	<?php echo $this->noBreakStart; ?>
		<?php if ($proposal->getDevicesToBeReplaced()->LeftOver > 0) : ?>
			<p>We recommend transferring the remaining <strong><?php echo count($proposal->getDevicesToBeReplaced()->LeftOver); ?></strong> printing devices to the PrintIQ&reg; program:</p>
			<table style="font-size: 10.5pt;">
				<tbody>
					<tr>
						<td style="width: 575px;">Monochrome cost per page</td>
						<td class="right">$<?php echo number_format($proposal->getMPSBlackAndWhiteCPP(),3); ?></td>
					</tr>
					<tr>
						<td>Color cost per page</td>
						<td class="right">$<?php echo number_format($proposal->getMPSColorCPP(),3); ?></td>
					</tr>
					<tr>
						<td>Estimated monochrome pages</td>
						<td class="right"><?php echo number_format($proposal->getLeftOverBlackAndWhitePageCount()); ?></td>
					</tr>
					<tr>
						<td>Estimated color pages</td>
						<td class="right"><?php echo number_format($proposal->getLeftOverColorPageCount()); ?></td>
					</tr>
					<tr>
						<td>Estimated cost of monochrome pages</td>
						<td class="right">$<?php echo number_format(($proposal->getLeftOverBlackAndWhitePageCount() * $proposal->getMPSBlackAndWhiteCPP()),0);?></td>
					</tr>
					<tr>
						<td>Estimated cost of color pages</td>
						<td class="right">$<?php echo number_format(($proposal->getLeftOverColorPageCount() * $proposal->getMPSColorCPP()),0)?></td>
					</tr>
					<tr>
						<td>Processing 1 invoice/month @ <?php echo $this->currency($proposal->report->getSurvey()->costToExecuteSuppliesOrder); ?></td>
						<td class="right">$<?php echo number_format($proposal->getInternalAdminCost()); ?></td>
					</tr>
					<tr>
						<td>External service</td>
						<td class="right">Included</td>
					</tr>
					<tr>
						<td>Internal IT support for printers</td>
						<td class="right">$<?php echo number_format($proposal->getAnnualITCost() * 0.5); ?></td>
					</tr>
					<tr>
						<td>Additional hardware purchases</td>
						<td class="right">$0</td>
					</tr>
					<tr>
						<td style="width: 575px;"><em>With our recommended replacements, you are unlikely to require other new hardware this year. If you do, it can be obtained through Office Depot and may result in additional savings.</em></td>
						<td class="right"></td>
					</tr>
					<tr class="bold">
						<td>Total annual cost under PrintIQ&reg;</td>
						<td class="right">$<?php echo number_format($proposal->getLeftOverPrintIQCost()); ?></td>
					</tr>
					<tr class="bold">
						<td>Current annual cost of these devices</td>
						<td class="right">$<?php echo number_format($proposal->getCostOfRemainingDevices()); ?></td>
					</tr>
					<tr class="bold red">
						<td>Total annual savings for PrintIQ&reg;</td>
						<td class="right">$<?php echo number_format($proposal->getCostOfRemainingDevices() - $proposal->getLeftOverPrintIQCost()); ?></td>
					</tr>
				</tbody>
			</table>
			<br />
		<?php endif; ?>
		<table class="genericTable right" style="line-height: 11pt;">
			<thead>
				<tr>
					<th width="340" class="left">Summary</th>
					<th width="80">Current <br/>Annual Cost</th>
					<th>Proposed Annual <br/>Cost</th>
					<th>Estimated <br/>Annual Savings</th>
				</tr>
			</thead>
				<tbody>
				    <?php if (count($proposal->getDevicesToBeReplaced()->BlackAndWhite) > 0) : ?>
					<tr>
						<td class="left">PrintIQ&reg; Plus&reg; - Monochrome Devices </td>
						<td>$<?php echo number_format($proposal->getCurrentCostOfReplacedBlackAndWhitePrinters()); ?></td>
						<td>$<?php echo number_format($proposal->getProposedCostOfReplacedBlackAndWhitePrinters()); ?></td>
						<td class="red">$<?php echo number_format($proposal->getCurrentCostOfReplacedBlackAndWhitePrinters() - $proposal->getProposedCostOfReplacedBlackAndWhitePrinters()); ?></td>
					</tr>
					<?php endif; ?>
					<?php if (count($proposal->getDevicesToBeReplaced()->BlackAndWhiteMFP) > 0) : ?>
					<tr>
						<td class="left">PrintIQ&reg; Plus&reg; - Monochrome MFP Devices </td>
						<td>$<?php echo number_format($proposal->getCurrentCostOfReplacedBlackAndWhiteMFPPrinters()); ?></td>
						<td>$<?php echo number_format($proposal->getProposedCostOfReplacedBlackAndWhiteMFPPrinters()); ?></td>
						<td class="red">$<?php echo number_format($proposal->getCurrentCostOfReplacedBlackAndWhiteMFPPrinters() - $proposal->getProposedCostOfReplacedBlackAndWhiteMFPPrinters()); ?></td>
					</tr>
					<?php endif; ?>
					<?php if (count($proposal->getDevicesToBeReplaced()->Color) > 0) : ?>
					<tr>
						<td class="left">PrintIQ&reg; Plus&reg; - Color Devices </td>
						<td>$<?php echo number_format($proposal->getCurrentCostOfReplacedColorPrinters()); ?></td>
						<td>$<?php echo number_format($proposal->getProposedCostOfReplacedColorPrinters()); ?></td>
						<td class="red">$<?php echo number_format($proposal->getCurrentCostOfReplacedColorPrinters() - $proposal->getProposedCostOfReplacedColorPrinters()); ?></td>
					</tr>
					<?php endif; ?>
					<?php if (count($proposal->getDevicesToBeReplaced()->ColorMFP) > 0) : ?>
					<tr>
						<td class="left">PrintIQ&reg; Plus&reg; - Color MFP Devices </td>
						<td>$<?php echo number_format($proposal->getCurrentCostOfReplacedColorMFPPrinters()); ?></td>
						<td>$<?php echo number_format($proposal->getProposedCostOfReplacedColorMFPPrinters()); ?></td>
						<td class="red">$<?php echo number_format($proposal->getCurrentCostOfReplacedColorMFPPrinters() - $proposal->getProposedCostOfReplacedColorMFPPrinters()); ?></td>
					</tr>
					<?php endif; ?>
					
					<?php if (count($proposal->getDevicesToBeReplaced()->LeftOver) > 0) : ?>
					<tr>
						<td class="left">PrintIQ&reg; - Remaining print devices</td>
						<td>$<?php echo number_format($proposal->getCostOfRemainingDevices()); ?></td>
						<td>$<?php echo number_format($proposal->getLeftOverPrintIQCost()); ?></td>
						<td class="red">$<?php echo number_format($proposal->getCostOfRemainingDevices() - $proposal->getLeftOverPrintIQCost()); ?></td>
					</tr>
					<?php endif; ?>
					<tr class="bold">
						<td>TOTAL</td>
						<td>$<?php echo number_format($proposal->getTotalPurchasedAnnualCost()); ?></td>
						<td>$<?php echo number_format($proposal->getTotalProposedAnnualCost()); ?></td>
						<td class="red">$<?php echo number_format($proposal->getTotalAnnualSavings()); ?></td>
					</tr>
				</tbody>
		</table>
		<br /> <br />
		<div class="annualSavings">
			<table>
				<tbody>
					<tr>
						<td width="500" class="left"><strong>Total annual savings with PrintIQ&reg;</strong></td>
						<td width="125" class="right"><strong>$<?php echo number_format($proposal->getTotalAnnualSavings()); ?></strong></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br />
		
		<?php endif; // end if($reportHasDevicesToReplace) ?>
		<p>This quote is valid for 7 days from the date on the cover of this document. Depending on your requirements, you may be subject to additional charges for installation, insurance, and documentation fees. Please review the contract for details.</p>
	<?php if (count($proposal->getDevicesToBeReplaced()->OverMaxLeasedCapacity) > 0) : ?>
	<br/><br/>
	<div class="pheader">Additional Replacement Suggestions</div>
	<p>The following devices should also be considered for replacement because they print more than 7,000 pages per month and require further discussion to determine the best replacement device.</p>
    		<table class="genericTable">
    			<thead>
    				<tr class="center">
    					<th width="160">Device Name</th>
    					<th width="120">Serial No.</th>
    					<th width="140">Monthly Volume</th>
    					<th width="120">Current Annual Cost*</th>
    				</tr>
    			</thead>
    			<tbody>
    				<?php foreach ($proposal->getDevicesToBeReplaced()->OverMaxLeasedCapacity as $deviceInstance) :?>
    				<?php $SerialNo = ($deviceInstance->serialNumber === "") ? 'Unknown' : $deviceInstance->serialNumber; ?>
    				<?php $modelName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getMasterDevice()->getFullDeviceName()) ?>
    				<tr class="center">
    					<td class="left"><?php echo $modelName ?></td>
    					<td><?php echo $SerialNo ?></td>
    					<td><?php echo number_format($deviceInstance->getAverageMonthlyPageCount()); ?></td>
    					<td>$<?php echo number_format($deviceInstance->getMonthlyRate() * 12); ?></td>
    				</tr>
    				<?php endforeach; ?>
    			</tbody>
    		</table>
    		<em>* Monthly cost includes both toner and non-toner expenses such as service, hardware and administration.</em>
	<?php endif; ?>
	
	
	<?php if (count($proposal->getDevicesToBeReplaced()->NoTonerLevels) > 0) : ?>
	<br/><br/>
	<p>The following devices should also be considered for replacement because they do not report toner levels and cannot be accommodated by a just-in-time supplies fulfillment program.</p>
    		<table class="genericTable">
    			<thead>
    				<tr class="center">
    					<th width="160">Device Name</th>
    					<th width="120">Serial No.</th>
    					<th width="140">Monthly Volume</th>
    					<th width="120">Current Annual Cost*</th>
    				</tr>
    			</thead>
    			<tbody>
                <?php foreach ($proposal->getDevicesToBeReplaced()->NoTonerLevels as $deviceInstance) :?>
                <?php $SerialNo = ($deviceInstance->serialNumber =="") ? 'Unknown' : $deviceInstance->serialNumber; ?>
   				<?php $modelName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getMasterDevice()->getFullDeviceName()); ?>
    				<tr class="center">
    					<td class="left"><?php echo $modelName ?></td>
    					<td><?php echo $SerialNo ?></td>
    					<td><?php echo number_format($deviceInstance->getAverageMonthlyPageCount()); ?></td>
    					<td>$<?php echo number_format($deviceInstance->getMonthlyRate() * 12); ?></td>
    				</tr>
    				<?php endforeach; ?>
    			</tbody>
    		</table>
    		<em>* Monthly cost includes both toner and non-toner expenses such as service, hardware and administration.</em>
		
<?php endif;
    echo $this->noBreakEnd;
    echo $this->pageEnd; ?>