<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->healthcheck->proposal;
?>
<div class="h1">Your PrintIQ&reg; Health Check</div>
<p>Does your fleet of printing hardware deliver your users and business the greatest return on investment?
    How many trees and how much water is consumed by the paper you use every year? This free PrintIQ Health Check
    will break down your current fleet and show you how you can <strong>lower your supplies costs</strong>,
    which devices are <strong>printing too much</strong> and which devices are <strong>printing too little</strong>, and the <strong>environmental impact</strong> of your fleet.</p>
    <p>
        Data used in this Health Check is compiled using remote monitoring software, from the past 30 days.
    </p>
<br />
<div class="pheader">Score Card</div>
<p style="margin: 10pt 0pt;">Your office printing environment was graded across five categories on a scale of 1 to 10. A score of 1 indicates a low-efficiency or high-cost scenario. A score of 10 indicates a high-efficiency or low-cost scenario. Your results are below:</p>
<table cellspacing="0" class="gradesTable">
    <tr>
        <td class="gradeDescription">
            <h4>Supplies and Service Logistics</h4>
            <p>Printing device management, number of various printer device models, and compatibility with Office Depot™ ATR (Auto Toner Replenishment).</p>
        </td>

        <td class="gradeNumber"><?php echo number_format($proposal->getRanking()->getSuppliesAndServiceLogistics()->Rank, 1); ?></td>
    </tr>
    <tr>
        <td class="gradeDescription">
            <h4>Printing Hardware Usage</h4>
            <p>Total number of printing devices, average print volumes, underused and overused equipment, and color print usage.</p>
        </td>
        <td class="gradeNumber"><?php echo number_format($proposal->getRanking()->getPrintingHardwareUsage()->Rank, 1); ?></td>
    </tr>
    <tr>
        <td class="gradeDescription">
            <h4>Technology Reliability and User Productivity</h4>
            <p>Age of printing devices, IT time spent managing printers, and availability of technology features that improve workflow and productivity.</p>
        </td>
        <td class="gradeNumber"><?php echo number_format($proposal->getRanking()->getTechnologyReliabilityAndUserProductivity()->Rank, 1); ?></td>
    </tr>
    <tr>
        <td class="gradeDescription">
            <h4>Environmental Impact</h4>
            <p>Energy consumption from printing hardware, forest and water consumption from paper used in printing, availability of green print technology features.</p>
        </td>
        <td class="gradeNumber"><?php echo number_format($proposal->getRanking()->getEnvironmentalFriendliness()->Rank, 1); ?></td>
    </tr>
</table>