<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <?php echo $this->headTitle($this->App()->title); ?>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta name="author" content="Tangent MTW"><?php echo $this->headLink(); ?>

    <script src="<?php echo $this->baseUrl("/js/libs/modernizr-2.5.3.min.js"); ?>"></script>

</head>
<body>
<!-- Prompt to upgrade browsers/install chrome frame if IE 6 -->
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or
    <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->


<!-- Start of main container -->
<div class="container" id="authContent">
    <header class="authHeader"></header>
    <section>
        <div class="well well-small">
            <?php echo $this->flashMessenger("info", '<div class="alert alert-%s">%s</div>'); ?>
            <?php echo $this->layout()->content ?>
        </div>
    </section>
</div>
<!-- End of main container -->


<?php echo $this->jQuery()->enable(); ?>

<script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>');</script>
<?php echo $this->headScript(); ?>
</body>
</html>
