<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
    <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width" />
    <meta name="viewport" content="initial-scale=1.0" />
    <meta charset="utf-8" />
    <?= $this->headTitle($this->App()->title)->setSeparator(' - '); ?>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="author" content="Tangent MTW">
    <?= $this->headLink(); ?>

    <script src="<?= $this->baseUrl('js/lib/require/require.min.js') ?>"></script>
</head>
<body>
<?= $this->partial('partials/browser-upgrade.phtml') ?>
<div class="container">
    <?= $this->layout()->content ?>
</div>

<?= $this->partial('partials/php-errors.phtml', array('exceptions' => $this->exceptions, 'request' => $this->request)) ?>

<script type="text/javascript">
    var TMTW_BASEURL = '<?= $this->serverUrl('/'); ?>';
</script>

<?= $this->headScript(); ?>
<?= ($this->App()->useAnalytics && APPLICATION_ENV == 'production') ? $this->partial('google-analytics.phtml') : ""; ?>
</body>
</html>
