<?php
$this->headLink()->prependStylesheet($this->theme("/css/styles.css"));
$this->headLink()->prependStylesheet($this->theme("/jquery/ui/jquery-ui-1.8.20.custom.css"));
$this->headLink()->prependStylesheet($this->theme("/bootstrap/css/bootstrap.css"));

$this->headScript()->prependFile($this->baseUrl("/js/script.js"));
$this->headScript()->prependFile($this->baseUrl("/js/plugins.js"));
$this->headScript()->prependFile($this->theme("/bootstrap/js/bootstrap.min.js"));
$this->headScript()->prependFile($this->baseUrl("/js/libs/jquery-ui-1.8.20.custom.min.js"));
?>
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
    <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <title><?php echo $this->App()->title; ?></title>

        <!-- Use the .htaccess and remove these lines to avoid edge case issues. More info: h5bp.com/i/378 -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <!-- Mobile viewport optimized: h5bp.com/viewport -->
        <meta name="viewport" content="width=device-width">
        <meta name="author" content="Tangent MTW">

        <?php echo $this->headLink(); ?>

        <!-- All JavaScript at the bottom, except this Modernizr build.
        Modernizr enables HTML5 elements & feature detects for optimal performance.
        Create your own custom Modernizr build: www.modernizr.com/download/ -->
        <script src="<?php echo $this->baseUrl("/js/libs/modernizr-2.5.3.min.js"); ?>"></script>

    </head>
    <body>
        <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
                   chromium.org/developers/how-tos/chrome-frame-getting-started -->
        <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                    </a> <a class="brand" href="<?php echo $this->baseUrl("/"); ?>"><?php echo $this->App()->title; ?></a>
                    <div class="nav-collapse">
                        <?php echo $this->navigation()->menu()->setUlClass('nav')->setMaxDepth(1)->render(); ?>
                        <?php //echo $this->navigation()->menu()->setUlClass('nav')->setPartial(array('menus/horizontal.phtml', 'default'))->render(); ?>
                        <div class="pull-right"><?php echo $this->GetLoggedInUser();?></div>
                        
                    </div>
                    
                </div>
                
            </div>
        </div>
        <div class="container">
            <?php echo $this->navigation()->menu()->setUlClass('nav nav-pills')->setPartial(array('menus/submenu.phtml', 'default'))->render(); ?>

            <?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setRenderInvisible(true)->setLinkLast(true)->setSeparator('/')->setPartial(array('menus/breadcrumbs.phtml', 'default'))->render(); ?>
            <div class="row">
                <div class="span12">
                    <?php echo $this->flashMessenger("info", '<div class="alert alert-%s">%s</div>'); ?>
                    <?php echo $this->layout()->content ?>
                </div>
                
                <!--/span-->
            </div>
            <hr>
            <footer>Copyright Tangent MTW &copy; <?php echo date("Y"); ?>. All Rights Reserved.</footer>
        </div>


        <!-- JavaScript at the bottom for fast page loading -->
        <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>');</script>
        <!-- Scripts concatenated and minified via build script -->
        <?php echo $this->headScript(); ?>
        <!-- end scripts -->
    </body>
</html>
