<?php
/**
 * This is the layout used to render portrait sized reports
 */
$auth = Zend_Auth::getInstance();
// CSS
$this->headLink()->prependStylesheet($this->theme("/proposalgenerator/htmlreports.css"));
$this->headLink()->prependStylesheet($this->theme("/proposalgenerator/pageBreaks.css"));
$this->headLink()->prependStylesheet($this->theme("/css/styles.css"));
$this->headLink()->prependStylesheet($this->theme("/jquery/ui/jquery-ui-1.8.16.custom.css"));
$this->headLink()->prependStylesheet($this->theme("/bootstrap/css/bootstrap.min.css"));
// JavaScript
$this->headScript()->prependFile($this->theme("/bootstrap/js/bootstrap.min.js"));
$this->headScript()->prependFile($this->baseUrl("/js/htmlReport.js"));
$this->headScript()->prependFile($this->baseUrl("/js/libs/jquery-ui-1.8.20.custom.min.js"));
$this->headScript()->prependFile($this->baseUrl("/js/libs/jquery-1.7.1.min.js"));

?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->App()->title; ?></title>
	<?php echo $this->headLink() . "\n"; ?>
    <?php echo $this->headScript() . "\n"; ?>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></a>
                <div class="brand"><?php echo $this->App()->title; ?></div>
                <div class="pull-left divider-vertical"></div>
                <div class="nav-collapse clear">
                <div class="navbar-form pull-left">
                    <select id="reportNavigator" style='margin-top: 5px;'>
                        <?php foreach ($this->availableReports as $report) : ?>
                        <option value='<?php echo $report->url; ?>' <?php echo ($report->active) ? "selected='selected'" : "";?>><?php echo $report->pagetitle; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                
                <div class="pull-right divider-vertical"></div>
                <div class="navbar-form pull-right">
                    
                        <?php if (count($this->formats) > 0) :?>
                        <div class="btn-group">
                            <span class="btn ">Download As:</span>
                            <?php foreach ($this->formats as $url => $format) : ?>
                             <a class="btn btn-<?php echo $format->btnstyle; ?> downloadButton" href="<?php echo $this->baseUrl($url); ?>" data-ext="<?php echo $format->extension; ?>" data-loadingmessage="<?php echo $format->loadingmessage; ?>"><?php echo $format->name; ?> <i class="icon-download icon-white"></i></a>
                            <?php endforeach; ?>
                        </div>
                        <?php endif;?>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
	<?php echo $this->layout()->content; ?>
</body>
</html>