<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
    <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle($this->App()->title); ?>

        <!-- Use the .htaccess and remove these lines to avoid edge case issues. More info: h5bp.com/i/378 -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <!-- Mobile viewport optimized: h5bp.com/viewport -->
        <meta name="viewport" content="width=device-width">
        <meta name="author" content="Tangent MTW">

        <?php echo $this->headLink(); ?>
        <!-- All JavaScript at the bottom, except this Modernizr build.
        Modernizr enables HTML5 elements & feature detects for optimal performance.
        Create your own custom Modernizr build: www.modernizr.com/download/ -->
        <script src="<?php echo $this->baseUrl("/js/libs/modernizr-2.5.3.min.js"); ?>"></script>
    </head>
    <body>
        <!-- Prompt to upgrade browsers/install chrome frame if IE 6 -->
        <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
        <!-- Start of Navbar -->
        <div class="navbar">
            <div class="navbar-inner">
                <div class="sidebar pull-right">
                    <div class="pull-right">
                        <?php if (Zend_Auth::getInstance()->hasIdentity()) : ?>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="#"><i class="icon-user icon-white"></i> <?php echo $this->Username(); ?></a>
                            <a class="pull-right btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'logout');?>">Logout</a></li>
                            </ul>
                        </div>
                        <?php else : ?>
                            <a class="btn btn-danger" href="<?php echo $this->url(array(), 'login');?>"><i class="icon-user icon-white"></i> Login</a>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="container">
                    <?php echo $this->navigation()->menu()->setUlClass('nav nav-pills')->setMinDepth(0)->setMaxDepth(0)->render(); ?>
                </div>
            </div>
        </div>
        <!-- End of Navbar -->
        <div class="subnav">
            <div class="container">
        <?php 
        // Find the active branch, at a depth of one
        $nav2Container = null;
        $rootPage = $this->navigation()->getContainer()->getPages();
        foreach($rootPage as $page) { 
        	if($page->isActive(true)) { 
        		$nav2Container = $page;
        		break;
        	}
        }
        
        if ($nav2Container && $nav2Container->hasPages())
        {
        ?>

                <?php echo $this->navigation()->menu()->setUlClass('nav nav-pills')->setMaxDepth(2)->render($nav2Container); ?>

        <?php 
        }                    
        ?>
            </div>
        </div>        
        
        <div class="wrapper" id="eminem">
            <header class="pageHeader">
                <div class="headerSpace"></div>
                <div class="container">
                <!-- Start of Breadcrumbs -->
                    <?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setRenderInvisible(true)->setLinkLast(true)->setSeparator('/')->setPartial(array('menus/breadcrumbs.phtml', 'default'))->render(); ?>
                <!-- End of Breadcrumbs -->
                </div>
            </header>
            <div class="innerWrapper">
                <!-- Start of main container -->
                <div class="container">
                    <div class="row">
                        <div class="span12">
                            <?php echo $this->flashMessenger("info", '<div class="alert alert-%s">%s</div>'); ?>
                            <?php echo $this->layout()->content ?>
                        </div>
                        
                        <!--/span-->
                    </div>
                    <hr>
                </div>
                <!-- End of main container -->
            </div>
        </div>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="span6">Copyright Tangent MTW &copy; <?php echo date("Y"); ?>. All Rights Reserved.</div>
                    <div class="span6" id="footerLinks">About | Eula | Terms of Service</div>
                </div>
            </div>
        </footer>

        <?php echo $this->partial('phpErrorPartial.phtml', array('exceptions' => $this->exceptions, 'request' => $this->request)); ?>
        
        <!-- JavaScript at the bottom for fast page loading -->
        <?php echo $this->jQuery()->enable(); ?>
        <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
        <!--  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script> -->
        <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>');</script>
        <!-- Scripts concatenated and minified via build script -->
        <?php echo $this->headScript(); ?>
        <!-- end scripts -->
    </body>
</html>