<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
    <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width" />
    <meta name="viewport" content="initial-scale=1.0" />
    <meta charset="utf-8" />
    <?= $this->headTitle($this->App()->title)->setSeparator(' - '); ?>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="author" content="Tangent MTW">
    <?= $this->headLink(); ?>

    <script src="<?= $this->baseUrl('js/lib/require/'.(file_exists('c:')?'require.js':'require.min.js')) ?>"></script>
    <script src="<?= $this->baseUrl('js/common.js') ?>"></script>
</head>
<body>
<?= $this->partial('partials/main-navigation.phtml') ?>
<?= $this->partial('partials/sub-navigation.phtml') ?>

<div class="body-container" id="meat">
    <!-- Page Header -->
    <div class="page-header">
        <div class="container">
            <h1><?= $this->placeholder('page-header') ?></h1>
        </div>
    </div>
    <!-- /Page Header -->

    <?= $this->partial('partials/progression-navigation.phtml') ?>
    <?= $this->partial('partials/report-navigation.phtml') ?>
    <div class="container">
        <?= $this->partial('partials/flash-messages.phtml') ?>
    </div>

    <!-- Main content -->
    <?= $this->layout()->content; ?>
    <!-- End main content -->
</div>
<!-- End of main container -->

<!-- Footer -->

<div class="page-copyright-background"></div>
<div class="page-copyright container">
    Copyright <?= $this->App()->copyright; ?> &copy; 2013-<?= date("Y"); ?>. All Rights Reserved.
    <button type="button" class="btn btn-primary pull-right" style="margin-top:-20px;margin-right:20px" onclick="$('#support-form').fadeIn();">
        Support
    </button>
</div>

<div id="support-form" class="" style="display:none;position: fixed;right:0;bottom:0;border:1px solid #ccc;border-radius:3px;padding:10px;background-color:white;width:400px;z-index:6">
    <p>
        <a href="javascript:;" onclick="$('#support-form').hide();" class="btn btn-default pull-right" style="min-width:25px">X</a>
    </p>
    <form id="form123" onsubmit="submitSupport(this); return false;" action="#">
        <input type="hidden" name="emailTitle" value="MPSToolbox Support Request">
        <input type="hidden" name="emailSubject" value="MPSToolbox Support Request">
        <input type="hidden" name="emailTo" value="support">
        <div class="form-group">
            <label>Company</label>
            <input type="text" class="form-control" required="required" name="Company" placeholder="Company">
        </div>
        <div class="form-group">
            <label>Your name</label>
            <input type="text" class="form-control" required="required" name="Name" placeholder="Contact name">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" required="required" name="Email" placeholder="Email address">
        </div>
        <div class="form-group">
            <label>Message</label>
            <textarea class="form-control" placeholder="How can we help?" name="Message" ></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-primary">
                Submit
            </button>
        </div>
    </form>
</div>

<script>// <![CDATA[
    function submitSupport(form) {
        $.post('/api/index/support', $(form).serialize(), function(r) {
            $('#form123').html('<p>Thank you for your message. We will contact you shortly.</p>');
        }, 'json');
    }
    // ]]></script>

<?= $this->partial('partials/php-errors.phtml', ['exceptions' => $this->exceptions, 'request' => $this->request]) ?>

<script type="text/javascript">
    var TMTW_BASEURL = '<?= $this->serverUrl('/'); ?>';
</script>

<?= $this->headScript(); ?>
<?= ($this->App()->useAnalytics && APPLICATION_ENV == 'production') ? $this->partial('google-analytics.phtml') : ""; ?>

<?php /** ?>
<?= ($this->App()->useChatTab && APPLICATION_ENV == 'production') ? $this->partial('zopim-chat.phtml') : ""; ?>
<?= ($this->App()->useFeedbackTab) ? $this->partial('zendesk-support.phtml') : ""; ?>
<?php /**/ ?>

<script>
    function notifyTodo(item, n) {
        if (n>99) {
            $('#todo-'+item).html('&nbsp;<span style="display:inline-block;width:25px;height:25px;background:transparent url(/img/icons/dot-25.png) no-repeat;text-align:center;line-height:25px">99<sup>+</sup></span>');
        } else {
            $('#todo-'+item).html('&nbsp;<span style="display:inline-block;width:20px;height:20px;background:transparent url(/img/icons/dot-20.png) no-repeat;text-align:center;line-height:20px">'+n+'</span>');
        }
        if (item=='all') {
            window.document.title = '('+n+') ' + $(window.document).attr('data-title');
        }
    }
    require(['jquery'], function ($) {
        $(document).ready(function() {
            try {
                $(window.document).attr('data-title', window.document.title);
                $('.span-todo').each(function (i, e) {
                    var $el = $(e);
                    notifyTodo($el.attr('data-item'), $el.attr('data-n'));
                });
            } catch (err) {
                //noop
            }
        });
    });
</script>

</body>
</html>