<?php
$errors = My_Error_Handler::$errors;
$hasExceptions = isset($this->exceptions);
/* @var $exceptions Exception[] */
$exceptions = $this->exceptions;
$hasPHPErrors = (count($errors) > 0);

if ($hasExceptions || $hasPHPErrors) :
    $this->headScript()->captureStart(); ?>
    $(document).ready(function() { $('#errorModal').modal(); });
    <?php $this->headScript()->captureEnd(); ?>
    <a href="#errorModal" data-toggle="modal" class="btn btn-danger" style="position: fixed; bottom: 0; left: 0;">Errors Occured! Click to view.</a>
    <div class="modal" id="errorModal" style="width: 940px; margin-left: -470px;">
        <div class="modal-header">
            <button class="close" data-dismiss="modal">&times;</button>
            <h3>Errors Occured!</h3>
        </div>
        <div class="modal-body">
            <div class="tabbable">
                <ul class="nav nav-tabs ">
                    <?php if ($hasPHPErrors) : ?>
                        <li <?php echo ($hasExceptions) ? '' : 'class="active"'; ?>><a href="#PHPErrors" data-toggle="tab">PHP Errors</a></li>
                    <?php endif; ?>
                    <?php if ($hasExceptions) : ?>
                        <li class="active"><a href="#ExceptionTabs" data-toggle="tab">Application Exception</a></li>
                    <?php endif; ?>
                </ul>
                <div class="tab-content">
                    <?php if ($hasPHPErrors) : ?>
                        <div class="tab-pane <?php echo ($hasExceptions) ? '' : 'active' ?>" id="PHPErrors">
                            <?php foreach ($errors as $error) : ?>
                                <div class="alert <?php echo $error->color; ?>"><?php echo $error->message; ?></div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($hasExceptions): ?>
                        <div class="tab-pane active" id="ExceptionTabs">
                            <div class="tabbable tabs-left">
                                <ul class="nav nav-tabs ">
                                    <li><a href="#RequestParams" data-toggle="tab">Request Parameters</a></li>
                                    <?php for ($exceptionCount = 0; $exceptionCount < count($exceptions); $exceptionCount++) : ?>
                                        <li <?php echo ($exceptionCount === 0) ? 'class="active"' : '' ?>>
                                            <a href="#Exception<?php echo $exceptionCount + 1; ?>" data-toggle="tab">Exception
                                                #<?php echo $exceptionCount + 1; ?></a></li>
                                    <?php endfor; ?>

                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane" id="RequestParams">
                                        <h3>Request Parameters:</h3>

                                        <div class="well">
            						<pre><?php
                                        var_dump($this->request->getParams());
                                        ?></pre>
                                        </div>
                                    </div>
                                    <?php for ($exceptionCount = 0; $exceptionCount < count($exceptions); $exceptionCount++) : ?>
                                        <div class="tab-pane <?php echo ($exceptionCount === 0) ? 'active' : '' ?>" id="Exception<?php echo $exceptionCount + 1; ?>">
                                            <h3>Exception #<?php echo $exceptionCount + 1; ?>:</h3>

                                            <div class="well">
                                                <pre><b>Message:</b> <?php echo $exceptions[$exceptionCount]->getMessage(); ?></pre>
                                                <h3>Stack trace:</h3>
                                                <pre><?php echo $exceptions[$exceptionCount]->getTraceAsString(); ?></pre>
                                            </div>
                                        </div>
                                    <?php endfor; ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <a href="#" data-dismiss="modal" class="btn btn-primary">Close</a>
        </div>
    </div>
<?php endif; ?>