<script type="text/javascript" src="//assets.zendesk.com/external/zenbox/v2.6/zenbox.js"></script>
<style type="text/css" media="screen, projection">
    @import url(//assets.zendesk.com/external/zenbox/v2.6/zenbox.css);
</style>
<script type="text/javascript">
    if (typeof(Zenbox) !== "undefined")
    {
        Zenbox.init({
            dropboxID  : "20170114",
            url        : "https://tangentmtw.zendesk.com",
            tabTooltip : "Support",
            tabImageURL: "https://p2.zdassets.com/external/zenbox/images/tab_support.png",
            tabColor   : "black",
            tabPosition: "Left"
        });
    }
</script>