<?php

use MPSToolbox\Legacy\Models\Acl\AppAclModel;
use MPSToolbox\Legacy\Models\Acl\ProposalgenAclModel;
use MPSToolbox\Legacy\Models\Acl\QuoteGeneratorAclModel;

$this->headScript()->appendFile($this->baseUrl('js/app/legacy/hardware-library/toner/ManageToners.js'));
?>
<script>
    <?php $this->headScript()->captureStart('append', 'text/javascript'); ?>
    var isSaveAndApproveAdmin = <?=($this->IsAllowed(ProposalgenAclModel::RESOURCE_PROPOSALGEN_ADMIN_SAVEANDAPPROVE, AppAclModel::PRIVILEGE_ADMIN) ? 'true' : 'false'); ?>,
        canDelete             = <?=($this->IsAllowed(QuoteGeneratorAclModel::RESOURCE_QUOTEGEN_DEVICESETUP_DELETE, AppAclModel::PRIVILEGE_VIEW) ? 'true' : 'false'); ?>,
        dealerSkuName         = '<?= My_Brand::$dealerSku; ?>';
    <?php $this->headScript()->captureEnd(); ?>
</script>
<div class="container">
    <!-- Toner Filter Form -->
    <form class="form-horizontal">
        <fieldset>
            <div class="form-group">
                <label class="control-label col-lg-2 col-md-3 col-sm-4" for="toner-manufacturer-filter">Manufacturer</label>

                <div class="col-lg-10 col-md-9 col-sm-8">
                    <input class="form-control js-filter-manufacturer" id="assign-toners-manufacturer-filter" name="assign-toners-manufacturer-filter" type="text" title="Select Manufacturer" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2 col-md-3 col-sm-4" for="assign-toners-filter-sku">VPN/SKU</label>

                <div class="col-lg-10 col-md-9 col-sm-8">
                    <input class="form-control js-filter-toner-sku" id="assign-toners-filter-sku" name="assign-toners-filter-sku" type="text" title="Filter SKU" placeholder="Any VPN/SKU" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2 col-md-3 col-sm-4" for="assign-toners-filter-color">Toner Color</label>

                <div class="col-lg-10 col-md-9 col-sm-8">
                    <input class="form-control js-filter-toner-color" id="assign-toners-filter-color" name="assign-toners-filter-color" type="text" title="Toner Color">
                </div>
            </div>

            <div class="form-group">
                <div class="col-lg-10 col-lg-push-2 col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
                    <button class="btn btn-xs btn-default js-reset-filter" id="assign-toners-reset-filter" type="reset">
                        <i class="fa fa-fw fa-times"></i> Reset
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
    <!-- /Toner Filter Form -->

    <table id="toners-grid"></table>
    <div id='toners-grid-pager'></div>
</div>


<!-- Modals -->

<!-- Alert Message Modal (Please Select Row) -->
<div class="modal fade" id="alertMessageModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a class="close" data-dismiss="modal">&times;</a>
                <h4>Please select a row</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div>
                        <input type="button" class="btn btn-primary" value="Ok" data-dismiss="modal" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Alert Message Modal (Please Select Row) -->


<!-- /Modals -->