<?php

use MPSToolbox\Legacy\Models\Acl\AppAclModel;
use MPSToolbox\Legacy\Models\Acl\ProposalgenAclModel;
use MPSToolbox\Legacy\Models\Acl\QuoteGeneratorAclModel;

$this->headScript()->appendFile($this->baseUrl('js/app/legacy/hardware-library/toner/InfiniteToners.js'));

$currencyService = \MPSToolbox\Services\CurrencyService::getInstance();
$currencyJs = '';
if (!$currencyService->is_usd()) {
    $currencyJs = "window.currencySymbol = '{$currencyService->get_symbol()}';\n";
}

?>
<script>
    <?php $this->headScript()->captureStart('append', 'text/javascript'); ?>
    var isSaveAndApproveAdmin = <?=($this->IsAllowed(ProposalgenAclModel::RESOURCE_PROPOSALGEN_ADMIN_SAVEANDAPPROVE, AppAclModel::PRIVILEGE_ADMIN) ? 'true' : 'false'); ?>,
        canDelete             = <?=($this->IsAllowed(QuoteGeneratorAclModel::RESOURCE_QUOTEGEN_DEVICESETUP_DELETE, AppAclModel::PRIVILEGE_VIEW) ? 'true' : 'false'); ?>,
        dealerSkuName         = '<?= My_Brand::$dealerSku; ?>';
    <?= $currencyJs ?>
    <?php $this->headScript()->captureEnd(); ?>
</script>

<style>
    .toner-item {
        padding-bottom:1em;
        margin-bottom:1em;
        border-bottom:1px solid #ccc;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <!-- Toner Filter Form -->
                    <form class="form-horizontal" id="filter-form">
                        <fieldset>
                            <legend>Filters</legend>
                            <div class="form-group">
                                <label class="control-label col-lg-2 col-md-3 col-sm-4" for="toner-manufacturer-filter">Manufacturer</label>

                                <div class="col-lg-10 col-md-9 col-sm-8">
                                    <select class="form-control js-filter-manufacturer" type="text" id="assign-toners-manufacturer-filter" name="assign-toners-manufacturer-filter"><option></option>
<?php
$db=Zend_Db_Table::getDefaultAdapter();
foreach ($db->query('select manufacturers.id, fullname, count(*) as c from manufacturers join toners on manufacturers.id = toners.manufacturerId group by manufacturers.id order by fullname')->fetchAll() as $line) { ?>
                                        <option value="<?php echo $line['id'] ?>"><?php echo $line['fullname'].' ('.$line['c'].')' ?></option>
<?php } ?>
                                    </select>
                                    <script> require(['jquery', 'select2'], function ($) { $('#assign-toners-manufacturer-filter').select2({allowClear: true, placeholder:'select' }); }); </script>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-2 col-md-3 col-sm-4" for="assign-toners-filter-sku">VPN/SKU</label>

                                <div class="col-lg-10 col-md-9 col-sm-8">
                                    <input class="form-control js-filter-toner-sku" id="assign-toners-filter-sku" name="assign-toners-filter-sku" type="text" title="Filter SKU" placeholder="Any VPN/SKU" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-2 col-md-3 col-sm-4" for="assign-toners-filter-color">Toner Color</label>

                                <div class="col-lg-10 col-md-9 col-sm-8">
                                    <input class="form-control js-filter-toner-color" id="assign-toners-filter-color" name="assign-toners-filter-color" type="text" title="Toner Color">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-lg-10 col-lg-push-2 col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
                                    <button class="btn btn-xs btn-default js-reset-filter" id="assign-toners-reset-filter" type="reset">
                                        <i class="fa fa-fw fa-times"></i> Reset
                                    </button>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                    <!-- /Toner Filter Form -->
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <p class="text-right"><a href="javascript:" onclick="addToner()" class="btn btn-primary" style="margin:5px;">Add toner</a></p>
                <div class="panel-body" id="result-panel">
                </div>
            </div>
        </div>
    </div>
</div>
