<?php if ($this->pageCount): ?>
    <ul class="pager">
        <?php if (isset($this->previous)): ?>
            <li class="previous">
                <a href="<?php echo $this->url(['page' => $this->previous]); ?>">Prev</a>
            </li>
        <?php else: ?>
            <li class="disabled"><a href="#">Prev</a></li>
        <?php endif; ?>


        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li>
                    <a href="<?php echo $this->url(['page' => $page]); ?>"><?php echo $page; ?></a>
                </li>
            <?php else: ?>
                <li class="active"><a href="#"><?php echo $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>


        <?php if (isset($this->next)): ?>
            <li class="next">
                <a href="<?php echo $this->url(['page' => $this->next]); ?>">Next</a>
            </li>
        <?php else: ?>
            <li class="disabled"><a href="#">Next</a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>