<?php
/* @var $form Proposalgen_Form_Fleet_AddDevice */
$form = $this->element;
?>

<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
    <?php echo $form->getDisplayGroup('deviceDetails')->render(); ?>

    <?php foreach ($form->tonerElements as $partTypeName => $partType) : ?>
    <fieldset id="<?php echo $partTypeName; ?>TonerFieldset">
        <legend><?php echo $partTypeName; ?> Toners</legend>
        <?php foreach ($partType as $tonerElementSets) :
        $hasErrors = false;
        ?>
        <?php foreach ($tonerElementSets as $element) : ?>
        <?php $hasErrors = ($element->hasErrors()) ? true : $hasErrors; ?>
        <?php endforeach; ?>
        <div class="control-group <?php echo ($hasErrors) ? "error" : ""; ?> <?php echo $tonerElementSets[0]->getAttrib('data-tonerColor') . "TonerSet" ?>">
            <label><?php echo $tonerElementSets[0]->getLabel() ?></label>
            <?php foreach ($tonerElementSets as $element) : ?>
            <?php echo $element; ?>
            <?php endforeach; ?>
            <?php if ($hasErrors) : ?>
            <span class="help-block">Hover over the fields above to see the errors.</span>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </fieldset>
    <?php endforeach; ?>
    <?php echo $form->getDisplayGroup('actions')->render(); ?>
</form>