<div class="page-header">
        <h1>Hardware Quote Devices - <small>Toners</small></h1>
</div>
<div class="clearfix">
    <a class="btn btn-success pull-right btn-small create-button" href="<?php echo $this->url(array('action' => 'create')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
</div>
<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th>SKU</th>
            <th>Manufacturer</th>
            <th>Type</th>
            <th>Color</th>
            <th>Yield</th>
            <th>Cost</th>
            <th style="width: 120px;">Action</th>
        </tr>
    </thead>
    <tbody>
    	
        <?php foreach ($this->paginator->getCurrentItems() as $toner) : /* @var $toner Proposalgen_Model_Toner */ ?>
        <tr>
            <td><?php echo $toner->sku; ?></td>
            <td><?php echo $toner->getManufacturer()->displayname; ?></td>
            <td><?php echo $toner->getPartType()->typeName; ?></td>
            <td style="text-transform: capitalize;"><?php echo strToLower($toner->getTonerColor()->tonerColorName); ?></td>
            <td style="text-align: right;"><?php echo number_format($toner->yield, 0, '', ','); ?></td>
            <td style="text-align: right;"><?php echo "$" . number_format($toner->cost, 2, '.', ','); ?></td>
            <td>
                <div class="btn-group">
	                <a class="btn btn-info" title="View" href="<?php echo $this->url( array ( 'action' => 'view', 'id' => $toner->id)); ?>"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-warning" title="Edit" href="<?php echo $this->url( array ( 'action' => 'edit', 'id' => $toner->id)); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-danger" title="Delete" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' => $toner->id)); ?>"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
    <h1>There are no toners</h1>
<?php endif; ?>