<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>

<h1>All Toners</h1>

<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th>SKU</th>
            <th>Manufacturer</th>
            <th>Type</th>
            <th>Color</th>
            <th>Yield</th>
            <th>Price</th>
            <th style="width: 120px;">Action</th>
        </tr>
    </thead>
    <tbody>
    	
        <?php foreach ($this->paginator->getCurrentItems() as $toner) : /* @var $toner Admin_Model_Toner */ ?>
        <tr>
            <td><?php echo $toner->getSku(); ?></td>
            <td><?php echo $toner->getManufacturerId(); ?></td>
            <td><?php echo $toner->getPartTypeId(); ?></td>
            <td><?php echo $toner->getTonerColorId(); ?></td>
            <td><?php echo $toner->getYield(); ?></td>
            <td><?php echo $toner->getPrice(); ?></td>
            <td>
                <div class="btn-group">
	                <a class="btn btn-info" title="View" href="<?php echo $this->url( array ( 'action' => 'view', 'id' => $toner->getId())); ?>"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-warning" title="Edit" href="<?php echo $this->url( array ( 'action' => 'edit', 'id' => $toner->getId())); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-danger" title="Delete" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' => $toner->getId())); ?>"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
    <h1>There are no toners</h1>
<?php endif; ?>

