<?php

use MPSToolbox\Legacy\Models\Acl\AppAclModel;
use MPSToolbox\Legacy\Models\Acl\HardwareLibraryAclModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\MasterDeviceModel;

?>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h1 class="modal-title text-center">Device Management</h1>
        </div>
        <div class="modal-body">


            <div id="alertMessage"></div>
            <!-- Device Details -->
            <form class="form-horizontal">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label col-md-3" for="manufacturerId">Manufacturer</label>
                            <div class="col-md-9">
                                <select class="form-control" type="text" id="manufacturerId" name="manufacturerId" <?= (!$this->isAllowed ? 'disabled="disabled"' : "") ?> value="<?= $this->manufacturerId ?>"><option></option><?php foreach ($this->manufacturers as $line) { ?><option value="<?php echo $line->id ?>" <?= $this->manufacturerId==$line->id?'selected="selected"':'' ?>><?php echo $line->fullname==$line->displayname?$line->fullname:$line->displayname." ({$line->fullname})" ?></option><?php } ?></select>
                                <script> $(document).ready(function() { $('#manufacturerId').select2({}); }); </script>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3" for="modelName">Model Name</label>
                            <div class="col-md-9">
                                <input class="form-control" type="text" id="modelName" value="<?= $this->modelName; ?>" name="modelName" <?= (!$this->isAllowed ? 'disabled="disabled"' : "") ?>>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3" for="modelName">Technology</label>
                            <div class="col-md-9">
                                <select class="form-control" name="tech" id="tech" onchange="updateMainSupplyHeader()">
                                    <option value="Other">Other</option>
                                    <option <?= $this->masterDevice && $this->masterDevice->tech=='Laser'?'selected="selected"':'' ?> value="Laser">Laser</option>
                                    <option <?= $this->masterDevice && $this->masterDevice->tech=='Ink'?'selected="selected"':'' ?> value="Ink">Ink</option>
                                    <option <?= $this->masterDevice && $this->masterDevice->tech=='LED'?'selected="selected"':'' ?> value="LED">LED</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label col-md-3" for="sku">OEM SKU</label>
                            <div class="col-md-9">
                                <input class="form-control" type="text" id="sku" value="<?= $this->masterDevice ? $this->masterDevice->sku : ''; ?>" name="sku" <?= (!$this->isAllowed ? 'disabled="disabled"' : "") ?>>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3" for="UPC">UPC</label>
                            <div class="col-md-9">
                                <input class="form-control" type="text" id="UPC" value="<?= $this->masterDevice ? $this->masterDevice->UPC : ''; ?>" name="UPC" <?= (!$this->isAllowed ? 'disabled="disabled"' : "") ?>>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3" for="weight">Weight (Kg)</label>
                            <div class="col-md-9">
                                <input class="form-control" type="text" id="weight" value="<?= $this->masterDevice ? $this->masterDevice->weight : ''; ?>" name="weight" <?= (!$this->isAllowed ? 'disabled="disabled"' : "") ?>>
                            </div>
                        </div>

                    </div>
                </div>
            </form>
        </div>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <?php $first = true; ?>

                        <?php if ($this->suppliesAndService) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#suppliesAndServiceTab" id="suppliesAndServiceTopTab" data-toggle="tab">Supplies &amp; Service</a>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->deviceAttributes) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#deviceAttributesTab" id="deviceAttributesTopTab" data-toggle="tab">Attributes</a>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->hardwareQuote) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#hardwareQuoteTab" id="hardwareQuoteTopTab" data-toggle="tab">Quote Attributes</a>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->hardwareOptimization) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#hardwareOptimizationTab" id="hardwareOptimizationTopTab" data-toggle="tab">Swap Attributes</a>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->availableOptions) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#availableOptionsTab" id="availableOptionsTopTab" data-toggle="tab">Options</a>
                            </li>
                        <?php endif; ?>

                        <?php if ($this->addons) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#addonsTab" id="addonsTopTab" data-toggle="tab">Add-ons</a>
                            </li>
                        <?php endif; ?>

                        <?php if (false && $this->hardwareConfigurations) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#hardwareConfigurationsTab" id="hardwareConfigurationsTopTab" data-toggle="tab">Favorite Configurations</a>
                            </li>
                        <?php endif; ?>

                        <?php if ($this->deviceImage) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#deviceImageTab" id="deviceImageTopTab" data-toggle="tab">Images</a>
                            </li>
                        <?php endif; ?>

                        <?php if ($this->history) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#historyTab" id="historyTopTab" data-toggle="tab">History</a>
                            </li>
                        <?php endif; ?>

                        <?php if ($this->distributors) : ?>
                            <li <?= ($first) ? 'class="active"' : '' ?>>
                                <?php $first = ($first) ? false : $first ?>
                                <a href="#distributorsTab" id="distributorsTopTab" data-toggle="tab">Distributors</a>
                            </li>
                        <?php endif; ?>

                    </ul>
                </div>
            </div>
        </nav>
        <div class="modal-body">

            <!-- End Of Device Details -->


            <div class="tab-content">
                <?php $first = true; ?>

                <?php if ($this->suppliesAndService) : ?>
                    <div class="tab-pane <?= ($first) ? ' active ' : '' ?>" id="suppliesAndServiceTab">
                        <?php $first = ($first) ? false : $first ?>
                        <?= $this->suppliesAndService; ?>

                        <div class="clearfix">
                            <?php if ($this->isAllowed || $this->IsAllowed(HardwareLibraryAclModel::RESOURCE_HARDWARE_LIBRARY_QUOTEINDEX_INDEX, AppAclModel::PRIVILEGE_VIEW)) : ?>
                                <div class="pull-right">
                                    <button type="button" class="btn btn-success btn-xs js-assign-toners-button" onclick="$(this).hide(); $('#search-supply-div').show()">
                                        <i class="fa fa-fw fa-plus-circle"></i> Assign Supply
                                    </button>
                                    <div id="search-supply-div" style="display:none">
                                        SKU: <input id="search-supply" style="width:500px;" />
                                        <script>
                                            require(['jquery', 'select2'], function ($) {
                                                $('#search-supply').select2({
                                                    minimumInputLength: 3,
                                                    dropdownCssClass: "bigdrop",
                                                    formatResult: function(line) {
                                                        var markup = '<div class="row" style="border-bottom:1px solid #ccc">' +
                                                            '<div class="col-sm-3">' +
                                                                line.text+
                                                            '</div>' +
                                                            '<div class="col-sm-3">' +
                                                                line.type+
                                                            '</div>' +
                                                            '<div class="col-sm-3">' +
                                                                line.color+
                                                            '</div>' +
                                                                line.yield+
                                                            '</div>';
                                                        return markup;
                                                    },
                                                    escapeMarkup: function (m) { return m; },
                                                    ajax: {
                                                        url: "/hardware-library/manage-devices/search-supply",
                                                        dataType: 'json',
                                                        quietMillis: 250,
                                                        cache: true,
                                                        data: function (term, page) { return { q: term, page: page, mfg:$('#manufacturerId').val() }; },
                                                        results: function (data, page) { return data; }
                                                    }
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <h3>
                                Supplies
                            </h3>
                        </div>

                        <div class="form-group">
                            <div>
                                <input name="assignedTonersMistakes" value="undefined" type="hidden">
                            </div>
                        </div>

                        <div>
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active"><a href="#supplies1" aria-controls="supplies1" role="tab" data-toggle="tab" id="main-supply-header">Main OEM Cartridges</a></li>
                                <li role="presentation"><a href="#supplies2" aria-controls="supplies2" role="tab" data-toggle="tab">Other OEM Supplies</a></li>
                                <li role="presentation"><a href="#supplies3" aria-controls="supplies3" role="tab" data-toggle="tab">Compatible Supplies</a></li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="supplies1" style="padding:10px">
                                    <table id="main-supplies-table" class="table table-hover table-bordered">
                                        <colgroup>
                                            <col width="15%" />
                                            <col width="10%" />
                                            <col width="30%" />
                                            <col width="15%" />
                                            <col width="10%" />
                                            <col width="20%" />
                                        </colgroup>
                                        <thead>
                                            <th>Color</th>
                                            <th>SKU</th>
                                            <th>Machine Compatibility</th>
                                            <th>Yield</th>
                                            <th>Your Cost</th>
                                            <th>Action</th>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="supplies2" style="padding:10px">
                                    <table id="other-supplies-table" class="table table-hover table-bordered">
                                        <colgroup>
                                            <col width="15%" />
                                            <col width="10%" />
                                            <col width="10%" />
                                            <col width="25%" />
                                            <col width="10%" />
                                            <col width="10%" />
                                            <col width="20%" />
                                        </colgroup>
                                        <thead>
                                            <th>Type</th>
                                            <th>Color</th>
                                            <th>SKU</th>
                                            <th>Machine Compatibility</th>
                                            <th>Yield</th>
                                            <th>Your Cost</th>
                                            <th>Action</th>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="supplies3" style="padding:10px">
                                    <table id="compatible-supplies-table" class="table table-hover table-bordered">
                                        <colgroup>
                                            <col width="15%" />
                                            <col width="15%" />
                                            <col width="15%" />
                                            <col width="15%" />
                                            <col width="10%" />
                                            <col width="10%" />
                                            <col width="20%" />
                                        </colgroup>
                                        <thead>
                                            <th>Manufacturer</th>
                                            <th>Type</th>
                                            <th>Color</th>
                                            <th>SKU</th>
                                            <th>Yield</th>
                                            <th>Your Cost</th>
                                            <th>Action</th>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>
                <?php endif; ?>

                <?php if ($this->deviceAttributes) : ?>
                    <div class="tab-pane <?= ($first) ? 'active' : '' ?>" id="deviceAttributesTab">
                        <?php $first = ($first) ? false : $first ?>
                        <?= $this->deviceAttributes ?>
                    </div>
                <?php endif ?>

                <?php if ($this->hardwareOptimization) : ?>
                    <div class="tab-pane <?= ($first) ? 'active' : '' ?>" id="hardwareOptimizationTab">
                        <?php $first = ($first) ? false : $first ?>
                        <?= $this->hardwareOptimization ?>
                    </div>
                <?php endif; ?>

                <?php if ($this->hardwareQuote) : ?>
                    <div class="tab-pane <?= ($first) ? 'active' : '' ?>" id="hardwareQuoteTab">
                        <?php $first = ($first) ? false : $first ?>
                        <?= $this->hardwareQuote ?>
                    </div>
                <?php endif; ?>

                <?php if ($this->availableOptions) : ?>
                    <div class="tab-pane <?= ($first) ? 'active' : '' ?>" id="availableOptionsTab">
                        <?php $first = ($first) ? false : $first ?>

                        <form class="form-horizontal">
                            <fieldset>
                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label class="control-label col-md-4" for="assign-options-filter-sku">VPN/SKU</label>

                                            <div class="col-md-8">
                                                <input class="form-control js-filter-options-sku" id="assign-options-filter-sku" name="assign-options-filter-sku" type="text" title="Filter SKU" placeholder="Any VPN/SKU" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-5">

                                        <div class="form-group">
                                            <label class="control-label col-md-4" for="assign-options-filter-text">Name/Description</label>

                                            <div class="col-md-8">
                                                <input class="form-control js-filter-options-text" id="assign-options-filter-text" name="assign-options-filter-text" type="text" title="Filter Name/Description" placeholder="Text to find in the name or description" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <div class="col-lg-10 col-lg-push-2 col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
                                                <button class="btn btn-xs btn-default js-reset-filter" type="reset">
                                                    <i class="fa fa-fw fa-times"></i> Reset
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-5">
                                        <label class="control-label col-md-4">Show</label>
                                        <div class="col-md-8">
                                            <select class="form-control js-filter-options-assigned" name="assign-options-filter-assigned">
                                                <option value="">all options</option>
                                                <option value="1">only assigned options</option>
                                                <option value="2">only unassigned options</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                        </form>

                        <hr>

                        <!-- Available Options Table -->
                        <div class="js-available-options-grid"></div>

                    </div>
                <?php endif; ?>

                <?php if (false && $this->hardwareConfigurations) : ?>
                    <div class="tab-pane <?= ($first) ? 'active' : '' ?>" id="hardwareConfigurationsTab">
                        <?php $first = ($first) ? false : $first ?>
                        <table id="hardwareConfigurations"></table>
                        <div id="hardwareConfigurations_Pager"></div>
                        <div class="modal fade" id="hardwareConfigurationsModal">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <a class="close" data-dismiss="modal">&times;</a>

                                        <h3>
                                            <span id="hardwareConfigurationsTitle"></span>
                                        </h3>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-horizontal">
                                            <form id="hardwareConfigurationsForm" class="form-horizontal form-center-actions">
                                            </form>
                                            <div class="modal-footer">
                                                <input type="button" class="btn btn-primary" value="Save" id="hardwareConfigurationFormBtn" onclick="createOrEdit('hardwareConfigurationsForm');" />
                                                <input type="button" class="btn btn-default" value="Cancel" data-dismiss='modal' />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal fade" id="deleteModal">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Confirm Delete Configuration</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you want to delete this configuration?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <form id="deleteForm" class="form-horizontal form-center-actions">
                                            <?= $this->delete ?>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if ($this->addons) : ?>
                    <div class="tab-pane <?= ($first) ? 'active' : '' ?>" id="addonsTab">
                        <?php $first = ($first) ? false : $first ?>
                        <?= $this->addons ?>
                    </div>
                <?php endif ?>

                <?php if ($this->deviceImage) : ?>
                    <div class="tab-pane <?= ($first) ? 'active' : '' ?>" id="deviceImageTab">
                        <?php $first = ($first) ? false : $first ?>
                        <?= $this->deviceImage ?>
                    </div>
                <?php endif ?>

                <?php if ($this->history) : ?>
                    <div class="tab-pane <?= ($first) ? 'active' : '' ?>" id="historyTab">
                        <?php $first = ($first) ? false : $first ?>
                        <?= $this->history ?>
                    </div>
                <?php endif ?>

                <?php if ($this->distributors) : ?>
                    <div class="tab-pane <?= ($first) ? 'active' : '' ?>" id="distributorsTab">
                        <?php $first = ($first) ? false : $first ?>
                        <?= $this->distributors ?>
                    </div>
                <?php endif ?>

                <div id="loadingDiv" class="modal" data-backdrop="static" data-keyboard="false">
                    <div class="spinner64"></div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <ul class="pager">
                <li class="next">
                    <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                    <span class="divider-vertical"></span>
                    <button class="btn btn-primary js-save-device-modal" type="button">Save</button>
                    <?php if ($this->isMasterDeviceAdministrator && $this->masterDevice instanceof MasterDeviceModel && $this->masterDevice->isSystemDevice == 0) : ?>
                        <span class="divider-vertical"></span>
                        <button class="btn btn-success js-save-and-approve-device-modal" type="button">Save and Approve</button>
                    <?php endif; ?>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="modal fade" id="alertMessageModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a class="close" data-dismiss="modal">&times;</a>
                <h4>Please select a row</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div>
                        <input type="button" class="btn btn-primary" value="Ok" data-dismiss="modal" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="alertCannotDelete">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">You do not have permission to delete this toner.</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div>
                        <input type="button" class="btn btn-primary" value="Ok" data-dismiss="modal" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function updateMainSupplyHeader() {
        var $h = $('#main-supply-header');
        switch ($('#tech').val()) {
            case 'Laser': $h.text('Main OEM Toner Cartridges'); break;
            case 'LED': $h.text('Main OEM Toner Cartridges'); break;
            case 'Ink': $h.text('Main OEM Ink Cartridges'); break;
            case 'Other': $h.text('Main OEM Cartridges'); break;
        }
    }
    updateMainSupplyHeader();
</script>
