<?php
echo $this->titlePageStart;
?>
    <?php echo $this->noBreakStart; ?>
<div class="titlepage">
	<div class="header">
		<h3>Prepared for:
            	<?php
            if (strlen($this->proposal->Report->CustomerCompanyName) > 26)
                echo "<br/>";
            
            echo $this->proposal->Report->CustomerCompanyName;
            ?>
            	</h3>
		<h3><?php echo $this->proposal->DateReportPrepared; ?></h3>
	</div>
	<div class="customerdetails">
		<p><?php echo nl2br($this->proposal->CustomerAddress); ?></p>
	</div>
</div>
<?php echo $this->noBreakEnd; ?>
<?php

echo $this->pageEnd;
?>