<?php
echo $this->pageStart;
?>
    <?php echo $this->noBreakStart; ?>
<div class="h1">Analysis: Environmental Impact</div>
<table cellspacing="0" class="gradesTable">
	<tr>
		<td class="gradeDescription">
			<p><?php echo $this->proposal->Ranking->EnvironmentalFriendliness->RankingText; ?></p>
		</td>
		<td class="gradeNumber"><?php echo number_format($this->proposal->Ranking->EnvironmentalFriendliness->Rank, 1); ?></td>
	</tr>
</table>
<br />
<div class="pheader">Energy Consumption</div>
<?php if ($this->proposal->PercentageOfDevicesReportingPower > $this->proposal->DevicesReportingPowerThreshold) {?>
<p>
	You are currently using an estimated average of <strong><?php echo number_format($this->proposal->getAveragePowerUsagePerMonth()); ?> kWh</strong>
	per month to operate printing devices at an estimated monthly cost of <strong>$<?php echo number_format($this->proposal->getAveragePowerCostPerMonth()); ?></strong>, assuming a cost of $<?php echo number_format($this->proposal->Report->ReportKilowattsPerHour, 2); ?> per kWh.</p>
<p>The following lists the devices with the highest average power
	consumption per month.</p>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
	<thead>
		<tr>
			<th style="width: 160px;">Model</th>
			<th style="width: 110px;" class="center">Serial No.</th>
			<th style="width: 170px;" class="center">Avg. kWh Consumption<br />Per
				Month Count
			</th>
			<th style="width: 145px;" class="center">Avg. Power<br />Cost per
				Month
			</th>
		</tr>
	</thead>
	<tbody>
            	<?php $ctr = 0; foreach ($this->proposal->getHighPowerConsumptionDevices() as $device): ?>
            	<?php $deviceName = str_replace("Hewlett-Packard", "HP", $device->getDeviceName())?>
                <tr>
			<td><div style="width: 160px; padding: 0px;"><?php echo $deviceName; ?></div></td>
			<td class="center"><?php if($device->getSerialNumber()) echo $device->getSerialNumber(); else echo 'Unknown';?></td>
			<td class="center"><?php echo number_format($device->getAverageMonthlyPowerConsumption()); ?> kWh</td>
			<td class="center">$<?php echo number_format($device->getAverageMonthlyPowerCost(), 2); ?></td>
		</tr>
        	    <?php $ctr++; if ($ctr > 2) break; endforeach; ?>
            </tbody>
</table>
<br />
<?php } else echo "<p>".$this->proposal->NumberOfDevicesReportingPower." of your ".$this->proposal->getDeviceCount()." printer(s) report power usage.  Not enough information is available to accurately calculate energy consumption for your fleet.</p>";?>
<div class="pheader">Green Features: Duplexing and Scanning</div>
<p>If you printed every document on both sides of the page, you could
	use up to 50% less paper than you would by only printing on one side.
	You could further reduce your paper consumption by using a scanner to
	e-mail documents instead of printing copies for distribution. The
	following charts show how many of your printing devices have duplexing
	and scanning capabilities:</p>
<div class="center">
        <?php if ($this->isPDF):?>
            <img src="<?php echo $this->proposal->graphs[13]; ?>" /> <img
		src="<?php echo $this->proposal->Graphs[14]; ?>" />
        <?php else: ?>
            <img src="<?php echo $this->proposal->graphs[13]; ?>"
		style="width: 270px; height: 175px;" /> <img
		src="<?php echo $this->proposal->Graphs[14]; ?>"
		style="width: 270px; height: 175px;" />
        <?php endif; ?>
        </div>
<?php echo $this->noBreakEnd; ?>
<?php

echo $this->pageEnd;
?>