<?php

    echo $this->pageStart;
?>
    <?php echo $this->noBreakStart; ?>
        <div class="h1">Analysis: Expense</div>
        <table cellspacing="0" class="gradesTable">
            <tr>
                <td class="gradeDescription">
                    <p><?php echo htmlentities($this->proposal->Ranking->Expense->RankingText); ?></p>
                </td>
                <td class="gradeNumber"><?php echo number_format($this->proposal->Ranking->Expense->Rank, 1); ?></td>
            </tr>
        </table>
        <br />
        <p>Gartner Group called office printing the last great hidden expense in the office. They estimate the companies spend 1% to 3% of their revenue on office printing. Based on data collected from your printing devices and your questionnaire responses, we have estimated your annual printing expenses. We have separated your expenses into the cost of your leased printing devices and the cost of your purchased devices. Your leased devices are typically large multifunction devices and are assumed to be on an existing service contract. Your purchased devices are ones that can typically be transferred to our PrintIQ&reg; program and be managed by Office Depot.</p>
        <br />
    <?php echo $this->noBreakEnd; ?>
    <?php echo $this->noBreakStart; ?>
        <div class="pheader">Total Estimated Annual Printing Costs</div>
        <p>Combining all costs, your current estimated annual printing expenses are as follows. Please note that our estimated costs may not match your actual purchases, due to factors including inventory on hand, returns, timing of the assessment, etc., but our estimates should be a good representation of your average costs since they are based on actual observed usage.</p>
        <br />
        <table cellspacing="0" style="font-size: 10.5pt;">
            <tr>
                <td style="width: 565px;">Annual cost of hardware on leases</td>
                <td style="width: 80px;" class="right">$<?php echo number_format($this->proposal->EstimatedAnnualCostOfLeaseMachines); ?></td>
            </tr>
            <tr>
                <td class="bottomborder">Annual cost of hardware not on leases</td>
                <td class="right bottomborder">$<?php echo number_format($this->proposal->TotalPurchasedAnnualCost); ?></td>
            </tr>
            <tr>
                <td class="bold">TOTAL ESTIMATED ANNUAL PRINTING COSTS</td>
                <td class="right bold">$<?php echo number_format($this->proposal->EstimatedAnnualCostOfLeaseMachines + $this->proposal->TotalPurchasedAnnualCost); ?></td>
            </tr>
        </table>
        <br />
    <?php echo $this->noBreakEnd; ?>
    <?php echo $this->noBreakStart; ?>
        <div class="pheader">Cost of Hardware Assumed to be Leased</div>
        <p>To calculate your cost of leased printing devices, we assumed that you are paying a monthly lease rate in addition to a per-page cost, which includes supplies and service for each device.</p>
        <br />
        <table cellspacing="0" style="font-size: 10.5pt">
            <tr>
                <td style="width: 565px;">Number of printing devices assumed to be on a lease</td>
                <td style="width: 80px;" class="right"><?php echo count($this->proposal->getLeasedDevices()); ?></td>
            </tr>
            <tr>
                <td>Predicted average annual monochrome prints on leased machines</td>
                <td class="right"><?php echo number_format($this->proposal->getPageCounts()->Leased->BlackAndWhite->Yearly); ?></td>
            </tr>
            <tr>
                <td>    </td>
                <td class="right"><?php echo number_format($this->proposal->getPageCounts()->Leased->Color->Yearly); ?></td>
            </tr>
            <tr>
                <td>Estimated annual total lease payments<br/><em>Based on $<?php echo number_format($this->proposal->report->ReportMonthlyLeasePayment); ?> per month per device</em></td>
               
                <td class="right">$<?php echo number_format($this->proposal->CombinedAnnualLeasePayments); ?></td>
            </tr>
            <tr>
                <td class="bold topborder">Estimated per-page lease cost</td>
                <td class="right bold topborder">$<?php echo number_format($this->proposal->PerPageLeaseCost, 4); ?></td>
            </tr>
            <tr>
                <td>Estimated monochrome per-page charge</td>
                <td class="right">$<?php echo number_format($this->proposal->LeasedBlackAndWhiteCharge, 4); ?></td>
            </tr>
            <tr>
                <td>Estimated color per-page charge</td>
                <td class="right">$<?php echo number_format($this->proposal->LeasedColorCharge, 4); ?></td>
            </tr>
            <tr>
                <td class="bold topborder">Estimated all-in cost for a monochrome page</td>
                <td class="right bold topborder">$<?php echo number_format($this->proposal->LeasedEstimatedBlackAndWhiteCPP, 4); ?></td>
            </tr>
            <tr>
                <td class="bold">Estimated all-in cost for a color page</td>
                <td class="right bold">$<?php echo number_format($this->proposal->LeasedEstimatedColorCPP, 4); ?></td>
            </tr>
            <tr>
                <td class="bold topborder">TOTAL ESTIMATED ANNUAL COST</td>
                <td class="right bold topborder">$<?php echo number_format($this->proposal->EstimatedAnnualCostOfLeaseMachines); ?></td>
            </tr>
        </table>
        <br />
    <?php echo $this->noBreakEnd; ?>
    <?php echo $this->noBreakStart; ?>
        <div class="pheader">Cost of Hardware Suitable for Transfer to a Managed Print Solution</div>
        <p>Your <strong><?php echo count($this->proposal->getPurchasedDevices()); ?></strong> print devices that are assumed to not be attached to leases may be suitable for transfer to a managed print program. Currently, you are paying for supplies and service separately for these devices and your internal IT staff spends time servicing them when they break down.</p>
        <p>The costs below are based on data collected using remote monitoring software and your questionnaire responses. It also assumes a monochrome page coverage of <strong><?php echo number_format($this->proposal->PageCoverageBlackAndWhite); ?>%</strong> and color coverage of <strong><?php echo number_format($this->proposal->PageCoverageColor); ?>%</strong>.</p>
        <table cellspacing="0" style="font-size: 10pt;">
            <tr>
                <td style="width: 565px;" class="bold red">Supplies</td>
                <td style="width: 80px;" class="right">&nbsp;</td>
            </tr>
            <tr>
                <td>Annual cost of ink and toner<br/><em>Based on data collected by Office Depot.</em></td>
                <td class="right">$<?php echo number_format($this->proposal->CostOfInkAndToner); ?></td>
            </tr>
            <tr>
                <td>Annual administration cost of executing supplies orders<br/><em>Based on your questionnaire responses.</em></td>
                <td class="right">$<?php echo number_format($this->proposal->CostOfExecutingSuppliesOrders); ?></td>
            </tr>
            <tr>
                <td class="bold topborder">Total estimated annual supplies-related expense</td>
                <td class="right bold topborder">$<?php echo number_format($this->proposal->EstimatedAnnualSupplyRelatedExpense); ?></td>
            </tr>
        </table>
        <table cellspacing="0" style="font-size: 10pt;">
            <tr>
                <td class="bold red">Service</td>
                <td class="right">&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 565px;">Annual cost of sourcing outside service organizations<br/><em>Based on your questionnaire responses.</em></td>
                <td style="width: 80px;"class="right">$<?php echo number_format($this->proposal->AnnualCostOfOutSourcing); ?></td>
            </tr>
            <tr>
                <td>Annual cost of internal IT servicing and supporting printing devices<br/><em>Based on your questionnaire responses.</em></td>
                <td class="right">$<?php echo number_format($this->proposal->AnnualITCost); ?></td>
            </tr>
            <tr>
                <td class="bold topborder">Total estimated annual cost of service</td>
                <td class="right bold topborder">$<?php echo number_format($this->proposal->EstimatedAnnualCostOfService); ?></td>
            </tr>
        </table>
        <table cellspacing="0" style="font-size: 10pt;">
            <tr>
                <td class="bold red">Hardware</td>
                <td class="right">&nbsp;</td>
            </tr>
             <tr>
                <td style="width: 565px;"><strong>Total estimated annual cost of hardware purchases</strong><br/><em>Based on the age of your devices and an average purchase price of $<?php echo number_format($this->proposal->Report->ReportAverageNonLeasePrinterCost)?>.</em></td>
                <td style="width: 80px;" class="right bold">$<?php echo number_format($this->proposal->AnnualCostOfHardwarePurchases); ?></td>
            </tr>
             <tr>
                <td class="bold topborder">TOTAL ESTIMATED ANNUAL COST</td>
                <td class="right bold topborder">$<?php echo number_format($this->proposal->TotalPurchasedAnnualCost); ?></td>
            </tr>
            <tr>
                <td>Predicted average annual monochrome prints</td>
                <td class="right"><?php echo number_format($this->proposal->getPageCounts()->Purchased->BlackAndWhite->Yearly); ?></td>
            </tr>
            <tr>
                <td>Predicted average annual color prints</td>
                <td class="right"><?php echo number_format($this->proposal->getPageCounts()->Purchased->Color->Yearly); ?></td>
            </tr>
            <tr>
                <td class="bold">Estimated all-in cost for a monochrome page</td>
                <td class="right bold">$<?php echo number_format($this->proposal->EstimatedAllInBlackAndWhiteCPP,4); ?></td>
            </tr>
            <tr>
                <td class="bold">Estimated all-in cost for a color page</td>
                <td class="right bold">$<?php echo number_format($this->proposal->EstimatedAllInColorCPP,4); ?></td>
            </tr>
        </table>
    <?php echo $this->noBreakEnd; ?>
    <?php echo $this->noBreakStart; ?>
    	<br />
        <p>Through our PrintIQ program, we can wrap supplies and service for these machines into a single cost-per-page rate. By partnering with Office Depot as your single-source provider, your printing devices will be efficiently managed and your staff can get back to concentrating on their core responsibilities. Out of these devices, below are the top three most expensive to operate:</p>
        <br />
        <table cellspacing="0" class="genericTable">
            <thead>
                <tr>
                    <th style="width: 225px;">Printing Device</th>
                    <th style="width: 125px;" class="center">Serial No.</th>
                    <th style="width: 125px;" class="center">Monthly Volume</th>
                    <th style="width: 115px;" class="center">Monthly Cost</th>
                </tr>
            </thead>
            <tbody>
            	<?php $ctr = 0; foreach ($this->proposal->getMostExpensiveDevices() as $device) : $ctr++; if ($ctr > 3) { break; } ?>
                <tr>
                	<td><div style="width: 225px; padding: 0px;"><?php echo $device->getDeviceName(); ?></div></td>
                	<td class="center"><?php if ($device->getSerialNumber()) echo $device->getSerialNumber(); else echo 'Unknown'; ?></td>
                	<td class="center"><?php echo number_format($device->getAverageMonthlyPageCount()); ?> pages</td>
                	<td class="center">$<?php echo number_format($device->getMonthlyRate()); ?></td>
            	</tr>
            	<?php endforeach; ?>
            </tbody>
        </table>
    <?php echo $this->noBreakEnd; ?>
<?php
    echo $this->pageEnd;
?>