<?php
use MPSToolbox\Legacy\Modules\Admin\Forms\ClientForm;

/* @var $form ClientForm */
$form = $this->element;
$action = $form->getAction();
if (isset($_GET['select'])) $action .= '?select';

$client_id = intval($form->getElement('id')->getValue());

?>
<form class="form-horizontal" method="<?= $form->getMethod() ?>" accept-charset="UTF-8" action="<?= $action ?>">
    <div class="row">
        <div class="col-sm-6">
            <?php if ($form->getElement('dealerId') instanceof Zend_Form_Element) : ?>
                <fieldset>
                    <legend>Contact Belongs To</legend>
                    <div class="form-group <?= ($form->getElement('dealerId')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('dealerId'), ['col-md-3']) ?>

                        <div class="col-md-9">
                            <?= $this->RenderFormText($form->getElement('dealerId'), ['js-select-dealer']) ?>
                            <?= $this->RenderFormDescription($form->getElement('dealerId')) ?>
                            <?= $this->RenderFormElementErrors($form->getElement('dealerId')) ?>
                        </div>
                    </div>
                </fieldset>
            <?php endif; ?>
            <fieldset>
                <legend>Company Details</legend>
                <div class="form-group <?= ($form->getElement('accountNumber')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('accountNumber'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('accountNumber')) ?>
                        <?= $this->RenderFormDescription($form->getElement('accountNumber')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('accountNumber')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('companyName')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('companyName'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('companyName')) ?>
                        <?= $this->RenderFormDescription($form->getElement('companyName')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('companyName')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('legalName')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('legalName'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('legalName')) ?>
                        <?= $this->RenderFormDescription($form->getElement('legalName')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('legalName')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('employeeCount')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('employeeCount'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('employeeCount')) ?>
                        <?= $this->RenderFormDescription($form->getElement('employeeCount')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('employeeCount')) ?>
                    </div>
                </div>
            </fieldset>
<?php if ($client_id && \MPSToolbox\Settings\Entities\DealerSettingsEntity::hasShopify()) { ?>
            <fieldset>
                <legend>Shopify</legend>

                <div class="form-group <?= ($form->getElement('deviceGroup')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('deviceGroup'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('deviceGroup')) ?>
                        <?= $this->RenderFormDescription($form->getElement('deviceGroup')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('deviceGroup')) ?>
                    </div>
                </div>

<?php
        $email=$form->getElement('email')->getValue();
        if (empty($email)) {
            echo '<button class="btn" disabled="disabled" type="button">Synchronize with Shopify</button><p><em>Shopify requires an e-mail address.</em></p>';
        } else {
            echo '<button id="btn-shopifySync" class="btn btn-primary" type="button" onclick="shopifySync(this)">Synchronize with Shopify</button>';
        }
?>
                <hr>
                <p><b>Export to Shopify supply cupboard</b></p>
                <table class="table table-striped table-hover">
<?php

$notSupportedMasterDevices = explode(',', $form->getElement('notSupportedMasterDevices')->getValue());

/** @var Zend_Db_Adapter_Abstract $db */
$db = Zend_Db_Table::getDefaultAdapter();
foreach ($db->fetchAll("
  select md.id, concat(displayname,' ',modelName) as n
  from master_devices md
    join manufacturers mf on md.manufacturerId=mf.id
    join device_instance_master_devices dimd on md.id=dimd.masterDeviceId
    join device_instances di on dimd.deviceInstanceId=di.id
    join rms_uploads ru on di.rmsUploadId=ru.id
  where ru.clientId={$client_id}
  group by md.id
  order by n
") as $line) {
?>
                    <tr>
                        <td><?= $line['n'] ?></td>
                        <td>
                            <select name="notSupportedMasterDevices[]" class="form-control">
                                <option value="" <?= in_array($line['id'], $notSupportedMasterDevices)?'':'selected="selected"' ?>>Yes</option>
                                <option value="<?= $line['id'] ?>" <?= in_array($line['id'], $notSupportedMasterDevices)?'selected="selected"':'' ?>> - No - </option>
                            </select>
                        </td>
                    </tr>
<?php
}
?>
                </table>
            </fieldset>
            <script>
                function sync_customer_done() {
                    $('#btn-shopifySync').replaceWith('<h6 style="color:green">Synchronized</h6>');
                }
                function shopifySync(btn) {
                    $(btn).attr('disabled','disabled').text('Busy...');
                    var url = 'http://proxy.mpstoolbox.com/shopify/sync_customer.php?id=<?= $client_id ?>&dealerId=<?= \MPSToolbox\Entities\DealerEntity::getDealerId() ?>&origin=<?= $_SERVER['HTTP_HOST'] ?>';
                    //$.getScript(url, function() {});
                    $('body').append('<img style="display:none" src="'+url+'">');
                    window.setTimeout(sync_customer_done, 1000);
                }
            </script>
<?php } ?>
        </div>

        <div class="col-sm-6">
            <fieldset>
                <legend>Primary Contact Details</legend>
                <div class="form-group <?= ($form->getElement('firstName')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('firstName'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('firstName')) ?>
                        <?= $this->RenderFormDescription($form->getElement('firstName')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('firstName')) ?>
                    </div>
                </div>
                <div class="form-group <?= ($form->getElement('lastName')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('lastName'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('lastName')) ?>
                        <?= $this->RenderFormDescription($form->getElement('lastName')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('lastName')) ?>
                    </div>
                </div>
                <div class="form-group <?= ($form->getElement('phoneNumber')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('phoneNumber'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('phoneNumber')) ?>
                        <?= $this->RenderFormDescription($form->getElement('phoneNumber')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('phoneNumber')) ?>
                    </div>
                </div>
                <div class="form-group <?= ($form->getElement('email')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('email'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('email')) ?>
                        <?= $this->RenderFormDescription($form->getElement('email')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('email')) ?>
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>Company Address</legend>
                <div class="form-group <?= ($form->getElement('addressLine1')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('addressLine1'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('addressLine1')) ?>
                        <?= $this->RenderFormDescription($form->getElement('addressLine1')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('addressLine1')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('addressLine2')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('addressLine2'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('addressLine2')) ?>
                        <?= $this->RenderFormDescription($form->getElement('addressLine2')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('addressLine2')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('city')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('city'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('city')) ?>
                        <?= $this->RenderFormDescription($form->getElement('city')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('city')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('region')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('region'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('region')) ?>
                        <?= $this->RenderFormDescription($form->getElement('region')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('region')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('postCode')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('postCode'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('postCode')) ?>
                        <?= $this->RenderFormDescription($form->getElement('postCode')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('postCode')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('countryId')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('countryId'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('countryId'), ['js-select-country']) ?>
                        <?= $this->RenderFormDescription($form->getElement('countryId')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('countryId')) ?>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>

    <fieldset>

        <hr>
        <ul class="pager">
            <li><?= $this->RenderFormSubmit($form->getElement('Save'), ['btn', 'btn-primary']) ?></li>
            <li><?= $this->RenderFormSubmit($form->getElement('Cancel'), ['btn', 'btn-default']) ?></li>
        </ul>
    </fieldset>
</form>

