<?php

use MPSToolbox\Legacy\Modules\Admin\Forms\DealerForm;

/* @var $form DealerForm */
$form = $this->element;

$dealerSettings = \MPSToolbox\Settings\Entities\DealerSettingsEntity::getDealerSettings($form->dealerId);

?>


<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>
    <div class="row">
        <div class="col-sm-6">
            <?php if ($form->getElement('dealerName') instanceof Zend_Form_Element) : ?>
                <fieldset>
                    <legend>Dealer Profile</legend>
                    <div class="form-group <?= ($form->getElement('dealerName')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('dealerName'), ['col-md-3']) ?>

                        <div class="col-md-9">
                            <?= $this->RenderFormText($form->getElement('dealerName')) ?>
                            <?= $this->RenderFormDescription($form->getElement('dealerName')) ?>
                            <?= $this->RenderFormElementErrors($form->getElement('dealerName')) ?>
                        </div>
                    </div>
                </fieldset>
            <?php endif; ?>
            <fieldset>
                <div class="form-group <?= ($form->getElement('currency')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('currency'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('currency')) ?>
                        <?= $this->RenderFormDescription($form->getElement('currency')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('currency')) ?>
                    </div>
                </div>
                <div class="form-group <?= ($form->getElement('userLicenses')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('userLicenses'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormText($form->getElement('userLicenses')) ?>
                        <?= $this->RenderFormDescription($form->getElement('userLicenses')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('userLicenses')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('dealerLogoImage')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('dealerLogoImage'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormFile($form->getElement('dealerLogoImage')) ?>
                        <?= $this->RenderFormDescription($form->getElement('dealerLogoImage')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('dealerLogoImage')) ?>
                    </div>
                </div>

                <div class="form-group <?= ($form->getElement('dealerFeatures')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('dealerFeatures'), ['col-md-3']) ?>

                    <div class="col-md-9">
                        <?= $this->RenderFormCheckbox($form->getElement('dealerFeatures')) ?>
                        <?= $this->RenderFormDescription($form->getElement('dealerFeatures')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('dealerFeatures')) ?>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <fieldset>
        <hr>
        <?= $this->RenderFormSubmit($form->getElement('submit'), ['btn', 'btn-primary']) ?>
        <?= $this->RenderFormSubmit($form->getElement('cancel'), ['btn', 'btn-default']) ?>
    </fieldset>
<?= $this->RenderFormClose($form) ?>

<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            $('input[value="ecommerce"]').parent().parent().append('<label style="display:none" id="label_shopify_subdomain"><input type="text" value="<?= $dealerSettings->shopSettings->shopifyName ?>" placeholder="Shopify Subdomain" name="shopifyName"></label>');
            $('input[value="ecommerce"]').on('click', function() {
                if (this.checked) $('#label_shopify_subdomain').show();
                else $('#label_shopify_subdomain').hide();
            });
            if ($('input[value="ecommerce"]')[0].checked) {
                $('#label_shopify_subdomain').show();
            }
        });
    });
</script>