<?php
use MPSToolbox\Legacy\Modules\Admin\Forms\FixTonerForm;

/* @var $form FixTonerForm */
$form = $this->element;
?>

<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>
<fieldset>
    <div class="form-group <?= ($form->getElement('dealerId')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('dealerId'), ['col-sm-3']) ?>

        <div class="col-sm-10 col-md-6 col-lg-6">
            <div class="col-md-8"><?= $this->RenderFormSelect($form->getElement('dealerId')) ?></div>
            <?= $this->RenderFormDescription($form->getElement('dealerId')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('dealerId')) ?>
        </div>
    </div>

    <div class="form-group <?= ($form->getElement('uploadFile')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('uploadFile'), ['col-sm-3']) ?>

        <div class="col-sm-10 col-md-6 col-lg-6">
            <?= $this->RenderFormFile($form->getElement('uploadFile')) ?>
            <?= $this->RenderFormDescription($form->getElement('uploadFile')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('uploadFile')) ?>
        </div>
    </div>
</fieldset>
<fieldset>
    <hr>
    <?= $this->RenderFormSubmit($form->getElement('performUpload'), ['btn', 'btn-primary']) ?>
    <?= $this->RenderFormSubmit($form->getElement('cancel'), ['btn', 'btn-default']) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>
