<?php
use MPSToolbox\Legacy\Modules\Admin\Forms\OnboardingForm;

/* @var $form OnboardingForm */
$form = $this->element;
?>

<?= $this->RenderFormOpen($form, array('form-horizontal')) ?>
<fieldset>
    <legend>Upload Onboarding Pricing Files</legend>
    <div class="form-group <?= ($form->getElement('dealerId')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('dealerId'), array('col-sm-3')) ?>
        <div class="col-sm-6 col-md-5 col-lg-4">
            <?= $this->RenderFormSelect($form->getElement('dealerId')) ?>
            <?= $this->RenderFormDescription($form->getElement('dealerId')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('dealerId')) ?>
        </div>
    </div>

    <div class="form-group <?= ($form->getElement('oemPricing')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('oemPricing'), array('col-sm-3')) ?>
        <div class="col-sm-6 col-md-5 col-lg-4">
            <?= $this->RenderFormFile($form->getElement('oemPricing')) ?>
            <?= $this->RenderFormDescription($form->getElement('oemPricing')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('oemPricing')) ?>
        </div>
    </div>

    <div class="form-group <?= ($form->getElement('compPricing')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('compPricing'), array('col-sm-3')) ?>
        <div class="col-sm-6 col-md-5 col-lg-4">
            <?= $this->RenderFormFile($form->getElement('compPricing')) ?>
            <?= $this->RenderFormDescription($form->getElement('compPricing')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('compPricing')) ?>
        </div>
    </div>
</fieldset>

<fieldset>
    <hr>
    <?= $this->RenderFormSubmit($form->getElement('upload'), array('btn', 'btn-primary')) ?>
    <?= $this->RenderFormSubmit($form->getElement('cancel'), array('btn', 'btn-default')) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>

