<?php 
$quote = $this->quote; /* @var $quote Quotegen_Model_Quote */
$this->activePage = 'settings';
echo $this->render('_partials/quoteHeading.phtml');
 
?>
<div class="row">
    <div class="span9">
        <div class="alert alert-warning">Please note that this section may not be ready for normal use yet.</div>
        <div class="well">
            <p>Under Construction</p>
            <p>Under Construction</p>
            <p>Under Construction</p>
            <p>Under Construction</p>
            <p>Under Construction</p>
            <p>Under Construction</p>
        </div>
    </div>
    <div class="span3"><?php echo $this->render('_partials/quoteSidebar.phtml'); ?></div>
</div>