<?php 
$quote = $this->Quote(); /* @var $quote Quotegen_Model_Quote */
$this->activePage = 'settings';
echo $this->render('_partials/quoteHeading.phtml');
 
?>
<div class="row">
    <div class="span12">
        <div class="alert alert-warning">Please note that this section may not be ready for normal use yet. And the cake is a lie.</div>
        <div class="well">
			<?php echo $this->form; ?>
        </div>
    </div>
</div>