<?php
$leasingSchemaTerms = $this->leasingSchemaTerms;
?>

<form name="leasingSchemaTerm" id="leasingSchemaTerm" class="form-horizontal" action="<?php echo $this->element->getAction() ?>" method="<?php echo $this->element->getMethod() ?>">

    <div class="control-group <?php echo ($this->element->getElement("range")->hasErrors()) ? 'error' : '' ?>">
        <label class="control-label pull-left" for="range">Range Value: </label>

        <div class="controls">
            <div class="input-prepend">
                <?php if ($this->element->getElement("range")->hasErrors())
                {
                    $this->element->getElement("range")->setAttrib('style', 'border-color: #B94A48; color: #B94A48;');
                } ?>
                <span class="add-on">$</span><?php echo trim($this->element->getElement("range")->renderViewHelper()); ?>
                <?php echo $this->element->getElement("range")->renderErrors(); ?>
            </div>
        </div>
    </div>

    <div class="controls">
        <div style="overflow: auto; overflow-y: hidden; -ms-overflow-y: hidden; margin: 20px 0px 0px 0px;">
            <table class="table table-stripped table-bordered" style="width: auto;">
                <thead>
                <tr>
                    <th style="text-align: left;">Term</th>
                    <th style="text-align: center;">Rate</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($leasingSchemaTerms as $term)
                { ?>
                    <tr>
                        <td style="text-align: left;"><?php echo $term->months; ?></td>
                        <td style="text-align: center;">
                            <?php if ($this->element->getElement("rate{$term->id}")->hasErrors())
                            {
                                $this->element->getElement("rate{$term->id}")->setAttrib('style', 'border-color: #B94A48; color: #B94A48;');
                            } ?>
                            <?php echo $this->element->getElement("rate{$term->id}")->renderViewHelper(); ?>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>

    <div>
        <?php echo $this->element->submit; ?>
        <?php echo $this->element->cancel; ?>
    </div>

</form>
