<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\QuoteModel;

?>
<div class="container">
    <?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
        <table class="table table-striped table-condensed table-bordered">
            <thead>
            <tr>
                <th style="width: 30px;">ID</th>
                <th>Client Name</th>
                <th>Address</th>
                <th>Date Created</th>
                <th>Date Modified</th>
                <th>Quote Date</th>
                <th>User ID</th>
                <th style="width: 80px;">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $quote QuoteModel */ ?>
            <?php foreach ($this->paginator->getCurrentItems() as $quote) : ?>
                <tr>
                    <td><?= $quote->id; ?></td>
                    <td><?= $quote->getClient()->companyName; ?></td>
                    <td><?= nl2br($quote->getClient()->getAddress()->getFullAddressMultipleLines()); ?></td>
                    <td><?= $quote->dateCreated; ?></td>
                    <td><?= $quote->dateModified; ?></td>
                    <td><?= $quote->quoteDate; ?></td>
                    <td><?= $quote->userId; ?></td>
                    <td>
                        <div class="btn-group btn-group-justified btn-group-xs">
                            <a class="btn btn-warning" title="Edit Quote" href="<?= $this->url(array('quoteId' => $quote->id), 'quotes'); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                            <a class="btn btn-danger" title="Delete Quote" href="<?= $this->url(array('id' => $quote->id), 'quotes.add-hardware.delete'); ?>"><i class="glyphicon glyphicon-trash"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?= $this->paginationControl($this->paginator); ?>
    <?php else : ?>
        <h1>There are no quotes</h1>
    <?php endif; ?>
</div>