<div class="page-header">
    <h1>Quote Management</h1>
</div>

<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th style="width: 30px;">ID</th>
            <th>Client Name</th>
            <th>Address</th>
            <th>Date Created</th>
            <th>Date Modified</th>
            <th>Quote Date</th>
            <th>User ID</th>
            <th style="width: 80px;">Action</th>
        </tr>
    </thead>
    <tbody>
    	
        <?php foreach ($this->paginator->getCurrentItems() as $quote) : /* @var $quote Quotegen_Model_Quote */ ?>
        <tr>
        <td><?php echo $quote->id; ?></td>
            <td><?php echo $quote->getClient()->companyName; ?></td>
            <td><?php echo nl2br($quote->getClient()->getAddress()->getFullAddressMultipleLines()); ?></td>
            <td><?php echo $quote->dateCreated; ?></td>
            <td><?php echo $quote->dateModified; ?></td>
            <td><?php echo $quote->quoteDate; ?></td>
            <td><?php echo $quote->userId; ?></td>
            <td>
                <div class="btn-group">
                    <a class="btn btn-warning" title="Edit Quote" href="<?php echo $this->url( array ( 'action' => 'index', 'controller' => 'quote_devices', 'quoteId' => $quote->id)); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-danger" title="Delete Quote" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' => $quote->id)); ?>"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
<div class='well'>
    <h1>There are no quotes</h1>
</div>
<?php endif; ?>

