<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <h2>&nbsp;</h2>
            <div id="categories-div">
                <img src="/img/spinner_32.gif">
            </div>
            <div>
                <br><br><br>
                <a href="javascript:" onclick="$(this).hide();$('#addCategory').show()">+ add category</a>
                <div id="addCategory" style="display:none">
                    <form method="post">
                        <select class="form-control" name="add" required="required">
                            <?= $this->addCategory ?>
                        </select>
                        <p class="text-right">
                            <button type="submit" class="btn btn-primary">Add</button>
                        </p>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-9">

            <div id="main-loading" style="display:none"><img src="/img/spinner_32.gif"></div>
            <div id="main-div" style="display:none;">

                <p class="alert" id="p-alert" style="display:none"></p>

                <h2 id="main-h2"></h2>

                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active" id="category-li"><a id="category-btn" href="#category-tab" role="tab" data-toggle="tab">Category properties</a></li>
                    <li role="presentation" id="products-li"><a id="products-btn" href="#products-tab" role="tab" data-toggle="tab">Products</a></li>
                </ul>

                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="category-tab" style="border:1px solid #ccc;padding:15px;">
                        <form action="#" onsubmit="submitCategory(this); return false;">

                            <input type="hidden" name="id" id="category-id">

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label>Name: </label>
                                        <input required="required" type="text" class="form-control" value="" id="category-name" name="name">
                                    </div>
                                    <div class="form-group">
                                        <label>Order priority: </label>
                                        <input required="required" type="number" step="1" min="0" class="form-control" value="" id="category-orderBy" name="orderBy">
                                    </div>
                                    <div class="form-group">
                                        <label>Taxable:</label>
                                        <select class="form-control" name="taxable" id="category-taxable">
                                            <option value="0">No</option>
                                            <option value="1">Yes</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label>Margins: </label>

                                        <div class="row">
                                            <div class="col-sm-3">
                                                <label>Manufacturer:</label>
                                            </div>
                                            <div class="col-sm-9">
                                                <select id="category-margin-manufacturer" name="manufacturer" class="form-control" onchange="mfgOrTypeChanged()"></select>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-sm-3">
                                                <label>Type:</label>
                                            </div>
                                            <div class="col-sm-9">
                                                <select id="category-margin-type" name="type" class="form-control" onchange="mfgOrTypeChanged()"></select>
                                            </div>
                                        </div>

                                        <hr>

                                        <div class="row" id="use-category-margins" style="display:none">
                                            <div class="col-sm-3">
                                            </div>
                                            <div class="col-sm-9 checkbox">
                                                <label>
                                                    <input type="checkbox" name="useDefaultMargins" id="useDefaultMargins" onclick="useDefaultMarginsClick()" value="1">
                                                    Use category margins
                                                </label>
                                            </div>
                                        </div>

                                        <table class="table">
                                            <colgroup>
                                                <col width="50%">
                                                <col width="50%">
                                            </colgroup>
                                            <thead>
                                                <tr>
                                                    <th>Name</th>
                                                    <th>Margin %</th>
                                                </tr>
                                            </thead>
                                            <tbody id="category-margins">

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="products-tab" style="border:1px solid #ccc;padding:15px;">
                        <div id="add-btn" class="row" style="display:none">
                            <div class="btn-group pull-right">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Add <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="javascript:;" onclick="addFromSupplier()">Search Distributor SKU</a></li>
                                    <li><a href="javascript:;" onclick="editSku(0 ,'')">Add From Scratch</a></li>
                                </ul>
                            </div>
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>VPN</th>
                                    <th>Manufacturer</th>
                                    <th>Name</th>
                                    <th>Your SKU</th>
                                    <th>Your Cost</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="products-tbody">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="addFromSupplier" style="width:600px;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Add Product From Distributor</h4>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label>Search by VPN or description</label>
                    <input type="text" class="form-control" id="supplier-search">
                </div>

                <table id="supplier-results" class="table table-hover">
                    <thead>
                        <tr>
                            <th>VPN</th>
                            <th>Description</th>
                            <th>UPC</th>
                            <th class="text-right">Price</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="4">no results</td>
                        </tr>
                    </tbody>
                </table>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>

    var dealerSkuName         = '<?= My_Brand::$dealerSku; ?>';
    var selectedCategory      = false;

    require(['jquery', 'jquery.typewatch'], function ($) {
        require(['bootstrap.treeview'], function ($) {
            loadTree();
        });

        $('#supplier-search').typeWatch({
            callback     : function (value)
            {
                $('#supplier-search').trigger('change');
            },
            wait         : 750,
            highlight    : true,
            captureLength: 3
        }).change(supplierSearchChange);
    });

    function loadTree() {
        $.get('/ecommerce/catalog/categories', [], function(r) { showTree(r); }, 'json');
    }
    var last_parent = false;
    function showTree(data) {
        var $c = $("#categories-div");
        $c.treeview({data:data, levels:99, showCheckbox:false});
        $c.on('nodeSelected',function (event, node) {
            if (node.nodes) {
                if (last_parent) $('#categories-div').treeview('collapseNode', [ last_parent, {} ]);
                $c.treeview('expandNode', [ node.nodeId, { levels: 2 } ]);
                last_parent = node.nodeId;
            } else {
                window.selectedCategory = node.href;

                $('#p-alert').hide();
                $('#main-div').hide();
                $('#main-loading').show();
                $.get('/ecommerce/catalog/category', {id: window.selectedCategory}, function(r) {
                    $('#main-h2').text(r.name);
                    $('#category-id').val(node.href);
                    $('#category-name').val(r.name);
                    $('#category-orderBy').val(r.orderBy);
                    $('#category-taxable').val(r.taxable);
                    $('#category-margins').html(r.margins);
                    $('#category-margins input').removeAttr('disabled');

                    if (r.showProducts) {
                        $('#products-li').show();
                        $('#products-tbody').html(r.products);
                    } else {
                        $('#products-li').hide();
                        $('#category-btn').tab('show');
                    }

                    if (r.showAdd) {
                        $('#add-btn').show();
                    } else {
                        $('#add-btn').hide();
                    }

                    $('#category-margin-manufacturer').html(r.mfgSelect);
                    $('#category-margin-type').html(r.typeSelect);
                    $('#use-category-margins').hide();

                    $('#main-div').show();
                    $('#main-loading').hide();
                }, 'json');
            }
        });
    }

    function reloadProducts() {
        $.get('/ecommerce/catalog/reload', {category: window.selectedCategory}, function(r) {
            $('#products-tbody').html(r);
        }, 'html');
    }

    function submitCategory(form) {
        $('#p-alert').hide();
        var data = $(form).serialize();
        $.post('/ecommerce/catalog/category', data, function(r) {
            if (r.ok) {
                $('#category-name').val($('#category-name').val());
                $('#p-alert').addClass('alert-success').html('Changes saved').show();
            } else {
                $('#p-alert').addClass('alert-error').html('Saving failed').show();
            }
        }, 'json');
    }

    function editPrinter(id) {
        require(['app/legacy/hardware-library/manage-devices/DeviceModal'], function (DeviceModal) {
            var deviceModal = new DeviceModal({ isAllowed: <?= \MPSToolbox\Legacy\Services\NavigationService::$userId==1?'true':'false' ?>, deviceId  : id });
            deviceModal.show();
        });
    }

    function addFromSupplier() {
        //$('#supplier-search').val('');
        //$('#supplier-results tbody').html('<tr><td colspan="4">no results</td></tr>');
        $('#addFromSupplier').modal();
        $('#addFromSupplier').css('margin-top','-150px');
        window.lastSearch = '';
    }

    var lastSearch = '';

    function supplierSearchChange() {
        var q = $('#supplier-search').val();
        if (lastSearch==q) return;
        lastSearch = q;

        $('#supplier-results tbody').html('<tr><td colspan="4">loading...</td></tr>');
        $.post('/ecommerce/catalog/search-sku', {q:q}, function(response) {
            if (response.length>0) {
                var tr='';
                var count=0;
                var more=0;
                $.each(response, function(i,e) {
                    if (++count>10) {
                        more++;
                    } else {
                        var baseProductId = e.baseProductId ? e.baseProductId : 0;
                        var fromSupplier = baseProductId ? 0 : e.id;
                        tr += '<tr>' +
                        '<td>' + e.vpn + '</td>' +
                        '<td>' + e.description + '</td>' +
                        '<td>' + e.upc + '</td>' +
                        '<td class="text-right">$' + e.price + '</td>' +
                        '<td><a href="javascript:;" class="btn btn-primary" onclick="$(\'#addFromSupplier\').modal(\'hide\');editSku('+baseProductId+',\''+ fromSupplier +'\')">Select</a></td>' +
                        '<tr>';
                    }
                });
                if (more>0) {
                    tr += '<tr><td colspan="5" class="text-center"><b>'+more+' additional results found, be more specific please.</b></td><tr>';
                }
                $('#supplier-results tbody').html(tr);
            } else {
                $('#supplier-results tbody').html('<tr><td colspan="4">no results found for: '+q+'</td></tr>');
            }
        }, 'json');
    }

    function editSku(id, fromSupplier) {
        require(['app/legacy/hardware-library/SkuModal'], function (SkuModal) {
            var skuModal = new SkuModal({ isAllowed: <?= \MPSToolbox\Legacy\Services\NavigationService::$userId==1?'true':'false' ?>, skuId  : id, fromSupplier: fromSupplier, categoryId : window.selectedCategory });
            skuModal.show();
            if (!window.skuSaveSuccessBound) {
                window.skuSaveSuccessBound = true;
                $(window).on("skuSaveSuccess", function(event, skuId) {
                    reloadProducts();
                    $('body').append('' +
                        '<img ' +
                        'style="display:none" ' +
                        'src="http://proxy.mpstoolbox.com/shopify/sync_sku.php?origin='+window.location.hostname+'&id='+skuId+'&dealerId=<?= \MPSToolbox\Legacy\Entities\DealerEntity::getDealerId() ?>&_='+$.now()+'">'
                    );
                });
            }
        });
    }

    function deleteSku(id) {
        if (!window.confirm('Delete this SKU?')) return;
        $.post('/ecommerce/catalog/delete', {id:id, category:selectedCategory }, function(r) {
            $('#products-tbody').html(r);
        }, 'html');
    }

    function mfgOrTypeChanged() {
        var mfg = $('#category-margin-manufacturer').val();
        var type = $('#category-margin-type').val();
        $.get('/ecommerce/catalog/mfg-or-type', {id: window.selectedCategory, mfg:mfg, type:type}, function(r) {
            $('#category-margins').html(r.margins);
            if ((mfg!='') || (type!='')) {
                if (r.useDefaultMargins) {
                    $('#useDefaultMargins')[0].checked = true;
                    $('#category-margins input').attr('disabled','disabled');
                } else {
                    $('#useDefaultMargins')[0].checked = false;
                    $('#category-margins input').removeAttr('disabled');
                }
                $('#use-category-margins').show();
            } else {
                $('#use-category-margins').hide();
                $('#category-margins input').removeAttr('disabled');
            }
        });
    }
    function useDefaultMarginsClick() {
        var checked = $('#useDefaultMargins')[0].checked;
        if (checked) {
            $('#category-margins input').attr('disabled','disabled');
            $('#category-margins input').each(function(i,e) { var $e = $(e); $e.val($e.attr('data-default')); });
        } else {
            $('#category-margins input').removeAttr('disabled');
            $('#category-margins input').each(function(i,e) { var $e = $(e); $e.val($e.attr('data-actual')); });
        }
    }

</script>