<?php
/* @var $optimization OptimizationViewModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

$optimization = $this->optimization;
/* @var $hardwareOptimization HardwareOptimizationModel */
$hardwareOptimization = $this->hardwareOptimization;

$customerOptimization = new OptimizationCustomerModel($hardwareOptimization);

$graphs = $customerOptimization->getGraphs();

/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

// Initialize some properties
$properties = $phpWord->getDocumentProperties();
$properties->setCreator('MPS Assessment Software');
$properties->setTitle(My_Brand::getDealerBranding()->customerOptimizationTitle);
$properties->setDescription('MPS Assessment Software');
$properties->setCategory('Customer Report');
$properties->setLastModifiedBy('MPS Assessment Software');

$section          = $phpWord->addSection([
    'orientation'  => null,
    'marginLeft'   => 375,
    'marginRight'  => 375,
    'marginTop'    => 375,
    'marginBottom' => 375
]);
$titlepageSection = $section;

/* Tables for the device layouts */
$widthTwips       = 11490;
$header_color     = $this->wordStyles->default->tableHeaderBackgroundColor;
$sub_header_color = $this->wordStyles->default->tableSubHeaderBackgroundColor;
$even_color       = "EFEFEF";
$odd_color        = "FCFCFC";
$footer_color     = "b8cce3";
$highlight_color  = "ebc7a4";

$titlePageBackgroundColor  = My_Brand::getDealerBranding()->titlePageTitleBackgroundColor;
$titlePageBackgroundColor2 = My_Brand::getDealerBranding()->titlePageInformationBackgroundColor;
$titlePageTextColor        = My_Brand::getDealerBranding()->titlePageTitleFontColor;
$titlePageTextColor2       = My_Brand::getDealerBranding()->titlePageInformationFontColor;
$headingColor              = My_Brand::getDealerBranding()->h1FontColor;
$h2Background              = My_Brand::getDealerBranding()->h2BackgroundColor;
$h2Color                   = My_Brand::getDealerBranding()->h2FontColor;
$h3Color                   = My_Brand::getDealerBranding()->h1FontColor;


/**
 * Paragraph styles
 */
// H2 Style #5881BC
// Title page
$phpWord->addTitleStyle(1, [
    'size'  => 12,
    'color' => $h2Background,
    'bold'  => true,
]);

$phpWord->addTitleStyle(2, [
    'size'   => 12,
    'color'  => My_Brand::getDealerBranding()->h2FontColor,
    'bold'   => true,
    'italic' => true
], [
    'shading' => [
        'fill' => $h2Background,
    ]
]);


$phpWord->addParagraphStyle('titleStyle1', [
    'align'      => 'center',
    'spaceAfter' => 100,
    'shading'    => [
        'fill' => $titlePageBackgroundColor,
    ]
]);
$phpWord->addParagraphStyle('titleStyle2', [
    'spaceAfter'  => 50,
    'spaceBefore' => 50,
    'bgColor'     => $titlePageBackgroundColor2
]);
$phpWord->addParagraphStyle('titleStyle3', [
    'spaceAfter' => 100,
    'tabs'       => [
        new \PhpOffice\PhpWord\Style\Tab('left', 350)
    ],
    'shading'    => [
        'fill' => $titlePageBackgroundColor2,
    ]
]);
$phpWord->addFontStyle('titlepage_title', [
    'size'  => 24,
    'bold'  => true,
    'color' => $titlePageTextColor
]);

$phpWord->addFontStyle('titlepage_subtitle', [
    'size'  => 16,
    'bold'  => true,
    'color' => $titlePageTextColor
]);

$phpWord->addFontStyle('titlepage_address', [
    'size'  => 12,
    'color' => $titlePageTextColor
]);

$styles = (object)[
    "tables" => (object)[
        "rowheader"          => [
            'tblHeader' => true,
            'cantSplit' => true,
        ],
        "rowstyle"           => [
            "cantSplit" => true,
        ],
        "singleimage"        => (object)[
            "tablestyle" => [],
            "cell1"      => [
                "valign" => "center"
            ]
        ],
        "doubleimage"        => (object)[
            "tablestyle" => [],
            "cell1"      => [
                "valign" => "center"
            ],
            "cell2"      => [
                "valign" => "center"
            ]
        ],
        "tripleimage"        => (object)[
            "tablestyle" => [],
            "cell1"      => [
                "valign" => "center"
            ],
            "cell2"      => [
                "valign" => "center"
            ],
            "cell3"      => [
                "valign" => "center"
            ]
        ],
        "twoColumnDataTable" => (object)[
            "tablestyle" => [
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ],

            "rowheight"  => null,
            "cell1"      => [
                "valign" => "center"
            ],
            "cell2"      => [
                "valign" => "center"
            ]
        ],
    ],
    "images" => (object)[
        "center" => [
            "align" => "center"
        ]
    ],

];

$standard_cell = (object)[
    "even"           => [
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
    ],
    "odd"            => [
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ],
    "fontStyle"      => null,
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'right'
    ]
];

$standard_cell_vcenter = (object)[
    "even"           => [
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
        "valign"           => 'center'
    ],
    "odd"            => [
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20,
        "valign"           => 'center'
    ],
    "fontStyle"      => null,
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'center',
    ]
];

$standard_cell_vcenter_no_right_border = (object)[
    "even"           => [
        "bgColor" => $even_color,
        "valign"  => 'center'
    ],
    "odd"            => [
        "bgColor" => $odd_color,
        "valign"  => 'center'
    ],
    "fontStyle"      => null,
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'center',
    ]
];

$standard_cell_right = (object)[
    "even"           => [
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ],
    "odd"            => [
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ],
    "fontStyle"      => null,
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'right'
    ],
];

$standard_cell_left = (object)[
    "even"             => [
        "bgColor"          => $even_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ],
    "odd"              => [
        "bgColor"          => $odd_color,
        "borderRightColor" => 'FFFFFF',
        "borderRightSize"  => 20
    ],
    "fontStyle"        => null,
    "paragraphStyle"   => [
        'spaceAfter' => 0,
        'align'      => 'left'
    ],
    "manufacturerName" => (object)[
        "fontStyle"      => ['italic' => true],
        "paragraphStyle" => [
            'spaceAfter' => 0,
            'align'      => 'left'
        ],
    ],
    "modelName"        => (object)[
        "fontStyle"      => [],
        "paragraphStyle" => [
            'spaceAfter' => 0,
            'align'      => 'left'
        ],
    ],
];

$standard_cell_no_right_border = (object)[
    "even"           => [
        "bgColor" => $even_color,
    ],
    "odd"            => [
        "bgColor" => $odd_color,
    ],
    "fontStyle"      => null,
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'right'
    ]
];

$standard_header = (object)[
    "cellStyle"      => [
        'bgColor' => $header_color
    ],
    "fontStyle"      => [
        'bold' => true
    ],
    "paragraphStyle" => [
        'spaceAfter' => 0,
        'align'      => 'center'
    ]
];

$acceptableDevices = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "col1Width"  => $widthTwips * 0.30,
    "col2Width"  => $widthTwips * 0.20,
    "col3Width"  => $widthTwips * 0.10,
    "col4Width"  => $widthTwips * 0.10,
    "col5Width"  => $widthTwips * 0.15,
    "col6Width"  => $widthTwips * 0.15,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell_right,
        "cell4"     => $standard_cell_right,
        "cell5"     => $standard_cell_right,
        "cell6"     => $standard_cell_no_right_border,
    ],
    "header"     => (object)[
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ],
];

$suggestedDevices = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "col1Width"  => $widthTwips * 0.20,
    "col2Width"  => $widthTwips * 0.20,
    "col3Width"  => $widthTwips * 0.10,
    "col4Width"  => $widthTwips * 0.10,
    "col5Width"  => $widthTwips * 0.05,
    "col6Width"  => $widthTwips * 0.10,
    "col7Width"  => $widthTwips * 0.25,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell_right,
        "cell4"     => $standard_cell_right,
        "cell5"     => $standard_cell_right,
        "cell6"     => $standard_cell_right,
        "cell7"     => $standard_cell_left
    ],
    "header"     => (object)[
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ],
];

$upgradedDevices = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "col1Width"  => $widthTwips * 0.20,
    "col2Width"  => $widthTwips * 0.20,
    "col3Width"  => $widthTwips * 0.10,
    "col4Width"  => $widthTwips * 0.10,
    "col5Width"  => $widthTwips * 0.05,
    "col6Width"  => $widthTwips * 0.10,
    "col7Width"  => $widthTwips * 0.25,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell_right,
        "cell4"     => $standard_cell_right,
        "cell5"     => $standard_cell_right,
        "cell6"     => $standard_cell_right,
        "cell7"     => $standard_cell_left
    ],
    "header"     => (object)[
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ],
];

$retiredDevices = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "col1Width"  => $widthTwips * 0.30,
    "col2Width"  => $widthTwips * 0.20,
    "col3Width"  => $widthTwips * 0.10,
    "col4Width"  => $widthTwips * 0.10,
    "col5Width"  => $widthTwips * 0.15,
    "col6Width"  => $widthTwips * 0.15,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell_right,
        "cell4"     => $standard_cell_right,
        "cell5"     => $standard_cell_right,
        "cell6"     => $standard_cell_no_right_border,
    ],
    "header"     => (object)[
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ],
];

$flaggedDevices = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 50,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 50,
        'cellMarginLeft'   => 50
    ],
    "col1Width"  => $widthTwips * 0.25,
    "col2Width"  => $widthTwips * 0.20,
    "col3Width"  => $widthTwips * 0.10,
    "col4Width"  => $widthTwips * 0.10,
    "col5Width"  => $widthTwips * 0.05,
    "col6Width"  => $widthTwips * 0.10,
    "col7Width"  => $widthTwips * 0.20,
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => $standard_cell_left,
        "cell2"     => $standard_cell_left,
        "cell3"     => $standard_cell_right,
        "cell4"     => $standard_cell_right,
        "cell5"     => $standard_cell_right,
        "cell6"     => $standard_cell_right,
        "cell7"     => $standard_cell_left,
    ],
    "header"     => (object)[
        'header'     => $standard_header,
        'sub_header' => $standard_sub_header,
    ],
];

$deviceTables = (object)[
    "tables" => (object)[
        "replacement" => $suggestedDevices,
        "upgraded"    => $upgradedDevices,
        "acceptable"  => $acceptableDevices,
        "retire"      => $retiredDevices,
        "flagged"     => $flaggedDevices,
    ]];

$doubleCenterTable = (object)[
    "tablestyle" => [],
    "col1Width"  => $widthTwips * 0.50,
    "col2Width"  => $widthTwips * 0.50,
    "body"       => (object)[
        "cell1" => [
            "valign" => "center"
        ],
        "cell2" => [
            "valign" => "center"
        ]
    ],
    "image"      => (object)[
        "cell1" => [
            'align' => 'right'
        ],
        "cell2" => [
            'align' => 'left'
        ],
    ]
];

$titleData = [
    "phpword"              => $phpWord,
    "section"              => $titlepageSection,
    "hardwareOptimization" => $hardwareOptimization,
    "styles"               => $styles,
    "dealerLogoFile"       => $this->dealerLogoFile,
    "companyName"          => My_Brand::getDealerBranding()->shortDealerName,
];

$profitabilityDevices = new OptimizationCustomerModel($hardwareOptimization);

$data = [
    "phpword"              => $phpWord,
    "section"              => $section,
    "hardwareOptimization" => $hardwareOptimization,
    "optimization"         => $optimization,
    "styles"               => $styles,
    "graphs"               => $this->graphs,
    "devicetables"         => $deviceTables,
    "profitabilityDevices" => $profitabilityDevices,
    "twocenter"            => $doubleCenterTable,
    "companyName"          => My_Brand::getDealerBranding()->shortDealerName,

];
// Actual document pages
$this->partial("report/customer/optimization/docx/01_titlepage.phtml", $titleData);
$this->partial("report/customer/optimization/docx/02_optimizationsummary.phtml", $data);
$this->partial("report/customer/optimization/docx/03_hardware_utilization.phtml", $data);
$this->partial("report/customer/optimization/docx/04_technology_features.phtml", $data);
$this->partial("report/customer/optimization/docx/05_age_of_fleet.phtml", $data);
$this->partial("report/customer/optimization/docx/06_fleet_diversity.phtml", $data);
$this->partial("report/customer/optimization/docx/07_color_usage.phtml", $data);
$this->partial("report/customer/optimization/docx/08_device_appendix.phtml", $data);
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save($this->savePath);

echo $this->baseUrl($this->publicFileName);
