<?php
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $graphs array */
$graphs = $this->graphs;

$section->addPageBreak();
$section->addTitle('Current Fleet Statistics', 2);

$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($graphs [0], array('align' => 'center'));
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($graphs [1], array('align' => 'center'));
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell3)->addImage($graphs [2], array('align' => 'center'));

$section->addTitle('Optimization Summary', 2);
$section->addText($this->translate('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut semper rutrum nunc sed condimentum. Praesent id justo a enim sagittis sodales vitae in mauris. Nunc id eros vel
urna laoreet feugiat. Quisque vitae lorem ligula, et porta felis. Suspendisse potenti. Maecenas viverra, arcu vel tempor accumsan, neque tellus facilisis ligula, sed posuere ipsum odio eget est.
Duis venenatis sodales nisi ut congue. '));

$section->addImage($graphs[3], $this->styles->images->center);
$section->addTextBreak();