<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Customer */
$customerOptimization = $this->customerOptimization;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $graphs array */
$graphs = $this->graphs;

$section->addTitle('Technology Features and Functionality', 2);
$section->addText($this->translate('If you printed every document on both sides of the page, you could use up to 50% less paper than you would by only printing on one side. You could further reduce your paper consumption
by using a scanner to e-mail documents instead of printing copies for distribution. The following charts show how many of your printing devices have duplex and scanning capabilities.'));

$tcStyle    = $this->twocenter;
$imageTable = $section->addTable($tcStyle->tablestyle);
$imageTable->addRow();
$imageTable->addCell($tcStyle->col1Width)->addImage($graphs [8], $tcStyle->image->cell1);
$imageTable->addCell($tcStyle->col2Width)->addImage($graphs [9], $tcStyle->image->cell2);
$section->addTextBreak();