<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $customerOptimization OptimizationCustomerModel */
$customerOptimization = $this->customerOptimization;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $graphs array */
$graphs = $this->graphs;

$section->addTitle('Technology Features and Functionality', 2);
$section->addText($this->translate('If you printed every document on both sides of the page, you could use up to 50% less paper than you would by printing only on one side. You could further reduce your paper consumption
by using a scanner to email documents instead of printing copies for distribution. The following charts show how many of your printing devices have duplex and/or scanning capabilities.'));

$tcStyle    = $this->twocenter;
$imageTable = $section->addTable($tcStyle->tablestyle);
$imageTable->addRow();
$imageTable->addCell($tcStyle->col1Width)->addImage($graphs [8], $tcStyle->image->cell1);
$imageTable->addCell($tcStyle->col2Width)->addImage($graphs [9], $tcStyle->image->cell2);
$section->addTextBreak();