<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $customerOptimization OptimizationCustomerModel */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

$section->addTitle('Age of Printing Devices', 2);
$section->addText('A breakdown of the ages of your printing devices is shown below.');
$tcStyle    = $this->twocenter;
$imageTable = $section->addTable($tcStyle->tablestyle);
$imageTable->addRow();
$imageTable->addCell($tcStyle->col1Width)->addImage($graphs[10], $tcStyle->image->cell1);
$imageTable->addCell($tcStyle->col2Width)->addImage($graphs[11], $tcStyle->image->cell2);
$section->addTextBreak();