<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $customerOptimization OptimizationCustomerModel */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

$section->addTitle('Number of Printing Device Models and Supply Types', 2);
$section->addText(sprintf('Out of your %1$s networked printing devices, you have %2$s unique %3$s. Each section of the chart below represents a single model type. We estimate that %4$s of your printing devices %5$s leased %6$s, for which supplies are included in your contract. The %7$s remaining %8$s of %9$s %10$s and %11$s %12$s %13$s. If you hold two of each supply in inventory, you have an estimated $%14$s in operating cash held in printer supplies inventory at any given time.',
    number_format($optimization->getDevices()->allIncludedDeviceInstances->getCount()), //1
    number_format($optimization->getNumberOfUniqueModels()), //2
    (number_format($optimization->getNumberOfUniqueModels()) == 1) ? 'model' : 'models', //3
    number_format($optimization->getDevices()->leasedDeviceInstances->getCount()), //4
    (number_format($optimization->getDevices()->leasedDeviceInstances->getCount()) == 1) ? 'is a' : 'are', //5
    (number_format($optimization->getDevices()->leasedDeviceInstances->getCount()) == 1) ? 'machine' : 'machines', //6
    number_format($optimization->getDevices()->purchasedDeviceInstances->getCount()), //7
    (number_format($optimization->getDevices()->purchasedDeviceInstances->getCount()) == 1) ? 'machine consists' : 'machines consist', //8
    number_format($optimization->getNumberOfUniquePurchasedModels()), //9
    (number_format($optimization->getNumberOfUniquePurchasedModels()) == 1) ? 'model' : 'models', //10
    (number_format($optimization->getNumberOfUniquePurchasedModels()) == 1) ? 'uses' : 'use', //11
    number_format($optimization->getNumberOfUniquePurchasedToners()), //12
    (number_format($optimization->getNumberOfUniquePurchasedToners()) == 1) ? 'supply type' : 'different supply types', //13
    number_format($optimization->getCashHeldInInventory()))); //14
$section->addTextBreak();

$section->addImage($graphs [12], array('align' => 'center'));
$section->addImage($graphs [13], array('align' => 'center'));
$section->addTextBreak();

$section->addText($this->translate('By using printing devices with supplies in common, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space required.
%1$s can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.', $this->companyName));

$section->addTextBreak();