<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Customer */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

$deviceInstances = $optimization->getDevicesGroupedByAction();

$totalNumberOfDevices = $optimization->getDevices()->purchasedDeviceInstances->getCount();

$section->addPageBreak();

$section->addTitle(sprintf('Device Appendix (%1$s devices)', number_format($totalNumberOfDevices), 1));

$this->partial('report/customer/optimization/docx/device_table.phtml',
    array(
        "section"                  => $section,
        "title"                    => "Acceptable Devices",
        "description"              => "The following devices have been deemed productive and we suggest keeping these devices.",
        "descriptionIfZeroDevices" => "There are no devices deemed productive and that we suggest keeping.",
        "deviceInstances"          => (isset($deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_KEEP])) ? $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_KEEP] : array(),
        "showReplacementDevices"   => false,
        "hardwareOptimization"     => $hardwareOptimization,
        "totalNumberOfDevices"     => $totalNumberOfDevices,
        "showReason"               => false,
        "tcStyle"                  => $this->devicetables->tables->acceptable,
        "tableStyle"               => $this->styles->tables,
    )
);

$section->addTextBreak();

$this->partial('report/customer/optimization/docx/device_table.phtml',
    array(
        "section"                  => $section,
        "title"                    => "Suggested Replacement Devices",
        "description"              => "The following devices have been targeted for replacement.",
        "descriptionIfZeroDevices" => "There are no devices currently targeted for replacement.",
        "deviceInstances"          => (isset($deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_REPLACE])) ? $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_REPLACE] : array(),
        "showReplacementDevices"   => true,
        "hardwareOptimization"     => $hardwareOptimization,
        "totalNumberOfDevices"     => $totalNumberOfDevices,
        "showReason"               => true,
        "tcStyle"                  => $this->devicetables->tables->replacement,
        "tableStyle"               => $this->styles->tables,
    )
);

$section->addTextBreak();

$this->partial('report/customer/optimization/docx/device_table.phtml',
    array(
        "section"                  => $section,
        "title"                    => "Devices Eligible for Retirement and Migration",
        "description"              => "Devices with both low volume and age of over " . Proposalgen_Model_DeviceInstance::RETIREMENT_AGE . " years have been targeted for retirement. We suggest migrating page volumes to other devices.",
        "descriptionIfZeroDevices" => "There are no devices currently targeted for retirement.",
        "deviceInstances"          => (isset($deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_RETIRE])) ? $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_RETIRE] : array(),
        "showReplacementDevices"   => false,
        "hardwareOptimization"     => $hardwareOptimization,
        "totalNumberOfDevices"     => $totalNumberOfDevices,
        "showReason"               => false,
        "tcStyle"                  => $this->devicetables->tables->retire,
        "tableStyle"               => $this->styles->tables,
    )
);

$section->addTextBreak();

$this->partial('report/customer/optimization/docx/device_table.phtml',
    array(
        "section"                  => $section,
        "title"                    => "Devices Flagged as Do Not Repair",
        "description"              => "These devices have been flagged for replacement upon breakdown based on operational reliability.",
        "descriptionIfZeroDevices" => "There are no devices currently flagged for replacement upon breakdown.",
        "deviceInstances"          => (isset($deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_DNR])) ? $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_DNR] : array(),
        "showReplacementDevices"   => false,
        "hardwareOptimization"     => $hardwareOptimization,
        "totalNumberOfDevices"     => $totalNumberOfDevices,
        "showReason"               => true,
        "tcStyle"                  => $this->devicetables->tables->flagged,
        "tableStyle"               => $this->styles->tables,
    )
);
?>