<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Customer */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;

/* @var $section PHPWord_Section */
$section = $this->section;

$deviceInstances = $optimization->getDevicesGroupedByAction();

$totalNumberOfDevices = $optimization->getDevices()->purchasedDeviceInstances->getCount();

$section->addTitle('Device Appendix (' . number_format($totalNumberOfDevices) . " devices)", 2);

$this->partial('report/customer/optimization/docx/device_table.phtml',
    array(
        "section"                => $section,
        "title"                  => "Acceptable Devices",
        "description"            => "The following devices have been deemed productive and we suggest keeping these devices.",
        "deviceInstances"        => $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_KEEP],
        "showReplacementDevices" => false,
        "hardwareOptimization"   => $hardwareOptimization,
        "totalNumberOfDevices"   => $totalNumberOfDevices,
        "showReason"             => false,
        "tcStyle"                => $this->devicetables->tables->acceptable,
    )
);

$this->partial('report/customer/optimization/docx/device_table.phtml',
    array(
        "section"                => $section,
        "title"                  => "Suggested Replacement Devices",
        "description"            => "The following devices have been targeted for replacement.",
        "deviceInstances"        => $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_REPLACE],
        "showReplacementDevices" => true,
        "hardwareOptimization"   => $hardwareOptimization,
        "totalNumberOfDevices"   => $totalNumberOfDevices,
        "showReason"             => true,
        "tcStyle"                => $this->devicetables->tables->replacement,
    )
);

$this->partial('report/customer/optimization/docx/device_table.phtml',
    array(
        "section"                => $section,
        "title"                  => "Devices Eligible for Retirement",
        "description"            => "Devices with both low volume and age of over " . Proposalgen_Model_DeviceInstance::RETIREMENT_AGE . " years have been target for retirement. We suggest migrating the page volume into another device.",
        "deviceInstances"        => $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_RETIRE],
        "showReplacementDevices" => false,
        "hardwareOptimization"   => $hardwareOptimization,
        "totalNumberOfDevices"   => $totalNumberOfDevices,
        "showReason"             => false,
        "tcStyle"                => $this->devicetables->tables->retire,
    )
);

$this->partial('report/customer/optimization/docx/device_table.phtml',
    array(
        "section"                => $section,
        "title"                  => "Devices flagged as Do Not Repair",
        "description"            => "These devices have been flagged for replacement on breakdown based on operation reliability.",
        "deviceInstances"        => $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_DNR],
        "showReplacementDevices" => false,
        "hardwareOptimization"   => $hardwareOptimization,
        "totalNumberOfDevices"   => $totalNumberOfDevices,
        "showReason"             => true,
        "tcStyle"                => $this->devicetables->tables->flagged,
    )
);
?>