<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationDealerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\TonerConfigModel;

$hardwareOptimization = $this->hardwareOptimization;


/* @var $profitabiltyDevices OptimizationDealerModel */
$profitabiltyDevices = $this->profitabilityDevices;


/* @var $section \PhpOffice\PhpWord\Element\Section */
$section                = $this->section;
$title                  = $this->title;
$description            = $this->description;
$descriptionIfZero      = $this->descriptionIfZeroDevices;
$totalNumberOfDevices   = $this->totalNumberOfDevices;
$showReplacementDevices = $this->showReplacementDevices;
$showReason             = $this->showReason;
$cellStyle              = $this->cellStyle;

/* @var $deviceInstances DeviceInstanceModel[] */
$deviceInstances = $this->deviceInstances;

$section->addTitle($title . " (" . number_format(count($deviceInstances)) . " out of " . number_format($totalNumberOfDevices) . " devices)", 2);
$tcStyle = $this->tcStyle;

if (count($deviceInstances) > 0)
{
    $section->addText($description);
    $table = $section->addTable($tcStyle->tablestyle);

// Table header
    $table->addRow($tcStyle->body->rowheight, $this->tableStyle->rowheader);
    $table->addCell($tcStyle->col1Width, $tcStyle->header->header->cellStyle)->addText('Device Name', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col2Width, $tcStyle->header->header->cellStyle)->addText('Serial / IP Address', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col3Width, $tcStyle->header->header->cellStyle)->addText('Mono AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col4Width, $tcStyle->header->header->cellStyle)->addText('Color AMPV', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col5Width, $tcStyle->header->header->cellStyle)->addText('Life Page Count', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    $table->addCell($tcStyle->col6Width, $tcStyle->header->header->cellStyle)->addText('Device Age', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    if ($showReplacementDevices)
    {
        if (!$showReason)
        {
            $table->addCell($tcStyle->col7Width, $tcStyle->header->header->cellStyle)->addText('Replacement Device', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
        }
        else
        {
            $table->addCell($tcStyle->col7Width, $tcStyle->header->header->cellStyle)->addText(htmlspecialchars('Replacement Device & Reason'), $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
        }

    }
    elseif ($showReason)
    {
        $table->addCell($tcStyle->col7Width, $tcStyle->header->header->cellStyle)->addText('Reason', $tcStyle->header->header->fontStyle, $tcStyle->header->header->paragraphStyle);
    }

    foreach ($deviceInstances as $deviceInstance)
    {
        $masterDevice            = $deviceInstance->getMasterDevice();
        $replacementMasterDevice = $deviceInstance->getHardwareOptimizationDeviceInstance($hardwareOptimization->id)->getMasterDevice();
        $isColor                 = ($masterDevice->tonerConfigId !== TonerConfigModel::BLACK_ONLY) ? true : false;
        $cycle                   = ($this->cycle(array(true, false))->next()->current());
        if ($cycle)
        {
            $ampvStyle = $tcStyle->body->cell5->even;
            $style     = $tcStyle->body->cell1->even;
        }
        else
        {
            $ampvStyle = $tcStyle->body->cell5->odd;
            $style     = $tcStyle->body->cell1->odd;
        }

        $table->addRow($tcStyle->body->rowheight, $this->tableStyle->rowstyle);
        // Device Name
        $cell = $table->addCell($tcStyle->col1Width, $style);
        $cell->addText($masterDevice->getManufacturer()->fullname, $tcStyle->body->cell1->manufacturerName->fontStyle, $tcStyle->body->cell1->manufacturerName->paragraphStyle);
        $cell->addText($masterDevice->modelName, $tcStyle->body->cell1->modelName->fontStyle, $tcStyle->body->cell1->modelName->paragraphStyle);

        // Serial and IP
        $cell = $table->addCell($tcStyle->col2Width, $style);
        $cell->addText($deviceInstance->serialNumber, $tcStyle->body->cell2->manufacturerName->fontStyle, $tcStyle->body->cell2->manufacturerName->paragraphStyle);
        $cell->addText($deviceInstance->ipAddress, $tcStyle->body->cell2->modelName->fontStyle, $tcStyle->body->cell2->modelName->paragraphStyle);

        // Monthly Statistics
        //// Mono AMPV
        $table->addCell($tcStyle->col3Width, $style)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->body->cell3->fontStyle, $tcStyle->body->cell3->paragraphStyle);

        //// Color AMPV
        $cell = $table->addCell($tcStyle->col4Width, $style);
        if ($isColor)
        {
            $cell->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()), $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
        }
        else
        {
            $cell->addText(" - ", $tcStyle->body->cell4->fontStyle, $tcStyle->body->cell4->paragraphStyle);
        }
        // Life Page Count
        $table->addCell($tcStyle->col5Width, $style)->addText($this->formatPageVolume($deviceInstance->getMeter()->endMeterLife), $tcStyle->body->cell5->fontStyle, $tcStyle->body->cell5->paragraphStyle);

        // Device Age
        $table->addCell($tcStyle->col6Width, $style)->addText($deviceInstance->getAge() . 'y', $tcStyle->body->cell6->fontStyle, $tcStyle->body->cell6->paragraphStyle);


        if ($showReplacementDevices && $replacementMasterDevice)
        {
            $cell = $table->addCell($tcStyle->col7Width, $style);
            // Replacement Device & Reason
            $cell->addText($replacementMasterDevice->getManufacturer()->fullname, $tcStyle->body->cell7->manufacturerName->fontStyle, $tcStyle->body->cell7->manufacturerName->paragraphStyle);
            $cell->addText($replacementMasterDevice->modelName, $tcStyle->body->cell7->modelName->fontStyle, $tcStyle->body->cell7->modelName->paragraphStyle);

            $cell->addText($deviceInstance->getHardwareOptimizationDeviceInstance($hardwareOptimization->id)->getDeviceSwapReason()->reason, $tcStyle->body->cell7->paragraphStyle, $tcStyle->body->cell7->paragraphStyle);

        }
        elseif ($showReplacementDevices)
        {
            if ($showReason)
            {
                $cell = $table->addCell($tcStyle->col7Width, $style);
                $cell->addText($deviceInstance->getHardwareOptimizationDeviceInstance($hardwareOptimization->id)->getDeviceSwapReason()->reason, $tcStyle->body->cell7->paragraphStyle, $tcStyle->body->cell7->paragraphStyle);
            }
        }
        else
        {
            if ($showReason)
            {
                $cell = $table->addCell($tcStyle->col7Width, $style);
                $cell->addText($deviceInstance->getHardwareOptimizationDeviceInstance($hardwareOptimization->id)->getDeviceSwapReason()->reason, $tcStyle->body->cell7->paragraphStyle, $tcStyle->body->cell7->paragraphStyle);
            }
        }
    }
}
else
{
    $section->addText($descriptionIfZero);
}