<div class="span-24 center">
    <h1>Pricing Import</h1>
</div>
<hr />
<div class="span-24">
    <div class="notice"><strong>WARNING:</strong> Uploading a pricing import is destructive! Deleted data will include, but is not limited to:
        <ul>
            <li>Master Devices</li>
            <li>PrintFleet Devices</li>
            <li>PrintFleet Mappings</li>
            <li>Toners</li>
            <li>Reports</li>
        </ul>
    </div>
</div>
<hr />
<div class="span-24">
    <?php
    echo $this->uploadFileForm;
    ?>
</div>