<?php
/* @var $form SelectOptionsForm */
use MPSToolbox\Legacy\Modules\QuoteGenerator\Forms\SelectOptionsForm;

$availableOptions = $this->availableOptions;
$form             = $this->element;
?>

<?= $this->RenderFormOpen($form, array('form-horizontal')) ?>
<fieldset>
    <div class="form-group <?= ($form->getElement('options')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('options'), array('col-md-3')) ?>

        <div class="col-md-9">
            <?= $this->RenderFormCheckbox($form->getElement('options')) ?>
            <?= $this->RenderFormDescription($form->getElement('options')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('options')) ?>
        </div>
    </div>
</fieldset>

<fieldset>
    <hr>
    <?= $this->RenderFormSubmit($form->getElement('submit'), array('btn', 'btn-primary')) ?>
    <?= $this->RenderFormSubmit($form->getElement('cancel'), array('btn', 'btn-default')) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>
