<?php
/* @var $form DeviceConfigurationForm */
use MPSToolbox\Legacy\Modules\QuoteGenerator\Forms\DeviceConfigurationForm;

$form = $this->element;
?>
<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>

<fieldset>
    <div class="form-group <?= ($form->getElement('deviceName')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('deviceName'), ['col-md-3']) ?>

        <div class="col-md-6">
            <?= $this->RenderFormText($form->getElement('deviceName')) ?>
            <?= $this->RenderFormDescription($form->getElement('deviceName')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('deviceName')) ?>
        </div>
    </div>

    <h3>
        Options
    </h3>
    <br>

    <?php if (count($form->getOptionElements()) > 0) : ?>
        <?php foreach ($form->getOptionElements() as $element) : ?>
            <?php echo $element ?>
            <?= $this->RenderFormSubmit($form->getElement('add'), ['btn', 'btn-primary']) ?>
        <?php endforeach; ?>
    <?php else : ?>
        <p>There are no options added to this device yet.</p>
    <?php endif; ?>

</fieldset>

<fieldset>
    <hr>
    <?= $this->RenderFormSubmit($form->getElement('submit'), ['btn', 'btn-primary']) ?>
    <?= $this->RenderFormSubmit($form->getElement('cancel'), ['btn', 'btn-default']) ?>
</fieldset>
<?= $this->RenderFormClose($form) ?>


