<div class="container health-check" id="htmlReportContainer">
    <?php
    $this->reportName = My_Brand::getDealerBranding()->mpsProgramName;
    $this->jit = My_Brand::$jit;
    $this->jitName = My_Brand::getDealerBranding()->shortJitProgramName;
    $this->jitFullName = My_Brand::getDealerBranding()->jitProgramName;

    echo $this->render('report/healthcheck/html/01_Title.phtml');
    echo $this->render('report/healthcheck/html/02_Scorecard.phtml');
    echo $this->render('report/healthcheck/html/03_ServiceAndSuppliesLogistics.phtml');
    echo $this->render('report/healthcheck/html/04_OemVsCompatible.phtml');
    echo $this->render('report/healthcheck/html/05_PrintingHardwareUsage.phtml');
    echo $this->render('report/healthcheck/html/06_TechnologyReliabilityAndUserProductivity.phtml');
    echo $this->render('report/healthcheck/html/07_EnvironmentalImpact.phtml');
    echo $this->render('report/healthcheck/html/08_Summary.phtml');
    echo $this->render('report/healthcheck/html/09_FleetAttributes.phtml');
    ?>
</div>