<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
?>
<div class="h1">Your <?php echo $this->reportName ?> Health Check</div>
<p>Does your fleet of printing hardware deliver your users and business the greatest return on investment?
    How many trees and how much water is consumed by the paper you use every year? This free <?php echo $this->reportName ?> Health Check
    will break down your current fleet and show you how you can <strong>lower your supplies costs</strong>,
    which devices are <strong>printing too much</strong> and which devices are <strong>printing too little</strong>, and the
    <strong>environmental impact</strong> of your fleet.</p>
<p>
    Data used in this Health Check is compiled using remote monitoring software, from the past 30 days.
</p>