<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs = $healthcheckViewModel->getGraphs();
?>
<div class="h1">Analysis: Service and Supplies Logistics</div>
<div class="pheader">Printing Device Management Breakdown</div>
<p>Different types of printing devices are managed in different ways: newer networked printers can be managed with remote monitoring software; leased multifunction devices are typically managed by the vendor who sold the machine; devices not connected to the network, such as inkjets and some older printers, are difficult to manage because you cannot monitor them with software.</p>
<br />
<div class="center">
    <table>
        <tbody>
        <tr>
            <td><img src="<?php echo $graphs['UnmanagedVsManagedDevices']; ?>" /></td>
            <!-- Devices leased/Devices Purchased -->
            <td><img src="<?php echo $graphs['PagesWithOrWithoutJIT']; ?>" /></td>
            <!-- Monthly pages on leased MFPs/Monthly pages on devices not leased -->
        </tr>
        </tbody>
    </table>
</div>
<div class="pheader">Number of Printing Device Models and Supply Types</div>
<p>Out of your
    <strong><?php echo $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount(); ?></strong> networked printing devices, you have of
    <strong><?php echo $healthcheckViewModel->getNumberOfUniqueModels(); ?></strong> different models. Each section of the chart below represents a single model type. Models with less than or equal to 0.7% of the total device count are put into the "Other" group.
</p>
<div class="center">
    <img src="<?php echo $graphs['UniqueDevicesGraph'] ?>" /> <!--  Giant pie chart -->
</div>
<?php
$uniqueDeviceArray = $healthcheckViewModel->getUniqueDeviceCountArray();
$totalAmount = $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount();
$amountOfRows = ceil(count($uniqueDeviceArray) / 2);

//FirstHalf is whether we are writing to the left side of the table or the right side.
$firstColumn = true;
$colorCounter = 0;

$tableData = array();

?>
<table class="table-bordered" style="border-collapse: collapse;">
    <?php

    $counter = 0;
    foreach ($uniqueDeviceArray as $key => $value)
    {
        if ($counter < $amountOfRows)
        {
            $tableData[$counter]["column1"] = array(
                "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
                "name"    => $key,
                "percent" => number_format(($value / $totalAmount) * 100, 1) . "%",
            );
        }
        else
        {
            $tableData[$counter - $amountOfRows]["column2"] = array(
                "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
                "name"    => $key,
                "percent" => number_format(($value / $totalAmount) * 100, 1) . "%",
            );

        }
        $counter++;
    }
    ?>
    <?php foreach ($tableData as $row) : ?>
        <tr>
            <?php if (array_key_exists("column1", $row)) : ?>
                <td style="border:1px solid">
                    <div style="width:20px;height:20px;margin: auto;background-color:#<?= $row["column1"]["color"]; ?>"></div>
                </td>
                <td style="border:1px solid"><?= $row["column1"]["name"]; ?></td>
                <td style="border:1px solid"><?= $row["column1"]["percent"] ?></td>
            <?php else : ?>
                <td colspan="3">&nbsp;</td>
            <?php endif; ?>


            <?php if (array_key_exists("column2", $row)) : ?>
                <td style="border:1px solid">
                    <div style="width:20px;height:20px;margin: auto;background-color:#<?= $row["column2"]["color"]; ?>"></div>
                </td>
                <td style="border:1px solid"><?= $row["column2"]["name"]; ?></td>
                <td style="border:1px solid"><?= $row["column2"]["percent"] ?></td>
            <?php else : ?>
                <td colspan="3">&nbsp;</td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
</table>
<p>By using printing devices that use the same supplies, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space required. <?php echo $this->reportName ?> can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.</p>

<div class="pheader">Number of Printing Device Vendors</div>
<p>Out of your <?php echo count($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getDeviceInstances()) ?>
    networked printing devices, you have <strong>
        <?php echo count($healthcheckViewModel->getDeviceVendorCount());
        ?></strong> different vendors. Each section of the chart below represents a single vendor name.

<div class="center">
    <img src="<?php echo $graphs['PercentPerDeviceBrand']; ?>" />
</div>

<div class="pheader">Number of Printing Devices Compatible with <?php echo $this->jitName ?></div>
<p>Out of your <?php echo $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount(); ?>
    networked printing devices, you have
    <strong><?php echo count($healthcheckViewModel->getIncludedDevicesReportingTonerLevels()); ?></strong> that are compatible with <?php echo $this->jitFullName ?> and <?php echo count($healthcheckViewModel->getIncludedDevicesNotReportingTonerLevels()) ?>
    devices that are not compatible. These non-compatible devices are shown in the fleet attributes section below. A complete list of all devices and their JIT compatibility can be found in the Appendix.
</p>
<br />
<div class="center">
    <table>
        <tbody>
        <tr>
            <td><img src="<?php echo $graphs['CompatibleJITBarGraph']; ?>" /></td>
            <!-- Devices leased/Devices Purchased -->
            <td><img src="<?php echo $graphs['PagesPrinterJITPieGraph']; ?>" /></td>
            <!-- Monthly pages on leased MFPs/Monthly pages on devices not leased -->
        </tr>
        </tbody>
    </table>
</div>

<div class="pheader">Estimated OEM Toner Costs vs. Estimated Compatible Toner Costs</div>
<p>You are saving money by moving to private brand toner for the machines that are on your JIT Program.</p>
<p>MPSToolbox.com analyzed your usage on your ink and toner spend and you can save an additional <?php echo $this->currency($healthcheckViewModel->calculateHalfDifferenceBetweenOemTotalCostAnnuallyAndCompAnnually(), array('precision' => 2)) ?> over the next 6 months by moving to the suggested items on the attached analysis.</p>