<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs = $healthcheckViewModel->getGraphs();
?>
<div class="h1">Analysis: Printing Hardware Usage</div>
<table cellspacing="0" class="gradesTable">
    <tr>
        <td class="gradeDescription">
            <p><?php echo $healthcheckViewModel->getRanking()->getPrintingHardwareUsage()->RankingText; ?></p>
        </td>
        <td class="gradeNumber"><?php echo number_format($healthcheckViewModel->getRanking()->getPrintingHardwareUsage()->Rank, 1); ?></td>
    </tr>
</table>
<br />
<div class="pheader">Print Volume and Number of Printing Devices</div>
<p>You currently have <strong><?php echo $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount(); ?></strong> networked printing devices that print an average of <strong><?php echo number_format($healthcheckViewModel->calculateAveragePagesPerDeviceMonthly()); ?>
</strong> pages each per month, for an average total monthly print volume of <strong><?php echo number_format($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombined()->getMonthly()); ?></strong> pages.
Ideally, you should have the minimum amount of printing hardware required to meet your print demand while maintaining user productivity.</p>
<br /> <br />
<div class="center">
    <img src="<?php echo $graphs[4]; ?>" style="width: 30%; height: 30%;" /> <!-- Average monthly pages per networked printer -->
    <img src="<?php echo $graphs[5]; ?>" style="width: 30%; height: 30%;" /> <!-- Average monthly pages per employee -->
    <img src="<?php echo $graphs[6]; ?>" style="width: 30%; height: 30%;" /> <!-- Employees per printing device -->
</div>
<br /> <br />
<div class="pheader">Hardware Utilization and Capacity</div>
<p>Based on information collected with our monitoring software, we detected the following number of networked printers and have estimated your average page volumes:</p>
    <br />
<table cellspacing="0" class="genericTable">
    <tr>
        <td width="400px">Number of networked printing devices</td>
        <td width="400px" style="text-align:right"><?php echo $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount() ?></td>
    </tr>
    <tr>
        <td width="400px">Average number of total printed pages per month</td>
        <td width="400px" style="text-align:right"><?php echo number_format($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombined()->getMonthly()); ?></td>
    </tr>
        <tr>
        <td width="400px">Average number of pages per device, per month</td>
        <td width="400px" style="text-align:right"><?php echo number_format($healthcheckViewModel->calculateAveragePagesPerDeviceMonthly()); ?></td>
    </tr>
</table>
    <br />
<p>A good measure of the recommended maximum monthly page volume for a printing device is the manufacturer's stated yield of a single print cartridge. In essence, you should not have to change the same toner cartridge more than once per month.</p>
<p>Using this definition of maximum monthly page volume, the total capacity of your printing fleet is the sum of the maximum page volumes for all of your printing devices.  As a guide we suggest that total company printing should range between 30 and 50% of maximum  fleet capacity. The closer you are to printing at maximum capacity, the more return you are getting on your printing assets. Most companies find that they have more printing hardware than they need. The following chart displays your estimated monthly page volume compared to your maximum monthly page capacity.</p>
<div class="center">
<img src="<?php echo $graphs['HardwareUtilizationCapacityBar']; ?>"  /> <!-- Monthly Usage compared to maximum fleet capacity -->
<img src="<?php echo $graphs['HardwareUtilizationCapacityPercent']; ?>"  /> <!-- Monthly Usage compared to optimal fleet capacity -->
</div>
<div class="pheader">Underused and Overused Printing Devices</div>
<p>Currently, <strong><?php echo number_format($healthcheckViewModel->getPercentDevicesUnderused()); ?>%</strong> of your printing devices are printing less than one quarter of our recommended monthly print volume, and <strong><?php echo number_format($healthcheckViewModel->getPercentDevicesOverused());?>%</strong> are printing above our recommended monthly print volume. Our recommended monthly print volumes are equal to the manufacturer's stated yield for a single print cartridge (for monochrome devices, the black cartridge, and for color devices, a single color cartridge unless the device is not being used for color).</p>
<p>Underused printing devices can be consolidated or retired to free up floor and desk space, reduce the amount of cash held in unused supplies inventory, and reduce the energy costs associated with powering underused machines. Devices printing fewer than 250 pages per month are likely performing less than 3 print jobs per day, and that volume can easily be accommodated by any nearby device. </p>
<p>Overused printing devices risk having more frequent breakdowns and should have a portion of their print volumes moved to underused printers or they can be replaced with higher-capacity machines. As an example, small print devices can have paper trays of fewer than 250 pages, and may result in several paper tray changes per day which can lead to user frustration and machine failure.</p>
<br/>
<table cellspacing="0" class="genericTable" id="LeastUsedDevicesTable" >
    <thead>
        <tr class="shaded">
            <th class="column1">Lowest Utilization</th>
            <th class="column2 center">Serial No.</th>
            <th class="column3 center">Avg. Monthly<br/>Volume</th>
            <th class="column4 center">Recommended <br />Max. Volume</th>
            <th class="column5 center">% of Recommended Max. Volume</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($healthcheckViewModel->getLeastUsedDevices() as $deviceInstance) : ?>
        <tr >
            <td class="column1"><div ><?php echo $deviceInstance->getDeviceName() ?></div></td>
            <td class="column2"><div class=" center"><?php echo ($deviceInstance->serialNumber) ?: 'Unknown'; ?></div></td>
            <td class="column3"><div class=" center"><?php echo number_format($deviceInstance->getPageCounts()->getCombined()->getMonthly()) ?></div></td>
            <td class="column4"><div class=" center"><?php echo number_format($deviceInstance->getMasterDevice()->getMaximumMonthlyPageVolume($healthcheckViewModel->getCostPerPageSettingForCustomer())) ?></div></td>
            <td class="column5"><div class=" center"><?php echo number_format($deviceInstance->calculatePercentOfMaximumRecommendedMaxVolume($healthcheckViewModel->getCostPerPageSettingForCustomer()), 1) ?>%</div></td>

        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<em>Only takes into account devices for which expected cartridge yields are known.</em>
<table cellspacing="0" class="genericTable" style="margin-top: 10px;" id="MostUsedDevicesTable">
    <thead>
        <tr class="shaded">
            <th class="column1">Highest Utilization</th>
            <th class="column2 center">Serial No.</th>
            <th class="column3 center">Avg. Monthly<br/>Volume</th>
            <th class="column4 center">Recommended <br />Max. Volume</th>
            <th class="column5 center">% of Recommended Max. Volume</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($healthcheckViewModel->getMostUsedDevices() as $deviceInstance) : ?>
        <tr>
            <td class="column1"><div ><?php echo $deviceInstance->getDeviceName() ?></div></td>
            <td class="column2"><div class=" center"><?php echo ($deviceInstance->serialNumber) ?: 'Unknown' ?></div></td>
            <td class="column3"><div class=" center"><?php echo number_format($deviceInstance->getPageCounts()->getCombined()->getMonthly()) ?></div></td>
            <td class="column4"><div class=" center"><?php echo number_format($deviceInstance->getMasterDevice()->getMaximumMonthlyPageVolume($healthcheckViewModel->getCostPerPageSettingForCustomer())) ?></div></td>
            <td class="column5"><div class=" center"><?php echo number_format($deviceInstance->calculatePercentOfMaximumRecommendedMaxVolume($healthcheckViewModel->getCostPerPageSettingForCustomer()), 1) ?>%</div></td>

        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<em>Only takes into account devices for which expected cartridge yields are known.</em>
<br /> <br />

<div class="pheader">Color Usage</div>
<p>You currently have <strong><?php echo $healthcheckViewModel->getNumberOfColorCapablePurchasedDevices(); ?></strong> color printing devices(excluding leased devices) that print a monthly average of <strong><?php echo number_format($healthcheckViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->color->getMonthly()); ?></strong> color pages per month, which is <strong><?php echo number_format($healthcheckViewModel->calculatePercentOfTotalVolumePurchasedColorMonthly(),2); ?>%</strong> of your total monthly print volume.</p>
<br />
    <div class="center">
    <table>
        <tbody>
            <tr>
                <td><img src="<?php echo $graphs['ColorCapablePrintingDevices']; ?>" /></td> <!-- Devices Purchased -->
                <td><img src="<?php echo $graphs['ColorVSBWPagesGraph']; ?>" /></td> <!-- Monthly pages on devices not leased -->
            </tr>
        </tbody>
    </table>
    </div>
<br />
<p>The following are the most expensive color devices currently in your fleet:</p>
    <?php
    ?>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
        <tr class="shaded">
            <th style="width: 160px;">Device Name</th>
            <th style="width: 110px;" class="center">Serial No.</th>
            <th style="width: 170px;" class="center">% of Monthly Cost</th>
            <th style="width: 145px;" class="center">Monthly Color Volume</th>
            <th style="width: 145px;" class="center">Color CPP</th>
            <th style="width: 145px;" class="center">Estimated Monthly Cost</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $ctr = 0;
        foreach ($healthcheckViewModel->getMonthlyHighCostPurchasedColorDevices($healthcheckViewModel->getCostPerPageSettingForCustomer()) as $deviceInstance): ?>
            <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName());?>
        <tr>
            <td><?php echo $deviceName?>
            <td class="center"><?php if($deviceInstance->serialNumber) echo $deviceInstance->serialNumber; else echo 'Unknown';?></td>
            <td class="center"><?php echo number_format(($deviceInstance->getMonthlyRatePercentage($healthcheckViewModel->calculateTotalMonthlyCost(), $healthcheckViewModel->getCostPerPageSettingForCustomer(),$healthcheckViewModel->getHealthcheckMargin())), 2) ?>
                %</td>
            <td class="center"><?php echo number_format($deviceInstance->getPageCounts()->color->getMonthly()); ?></td>
            <td><?php echo $this->currency($deviceInstance->getColorCostPerPageWithMargin($healthcheckViewModel->getCostPerPageSettingForCustomer(),$healthcheckViewModel->getHealthcheckMargin()),array('precision' => 4)); ?></td>
            <td><?php echo $this->currency($deviceInstance->getCostOfColorInkAndToner($healthcheckViewModel->getCostPerPageSettingForCustomer(),$healthcheckViewModel->getHealthcheckMargin()),array('precision' => 2)) ?></td>
        </tr>
            <?php $ctr++; if ($ctr > 2) break; endforeach; ?>
    </tbody>
</table>
<p>In general, printing in color is more expensive than printing in monochrome. The ideal amount of color usage depends on your printing needs, but the use of color in important documents can enhance your company's professional image, improve comprehension and increase readership.</p>
<p><?php echo $this->reportName ?> can help you track your color printing and provide low-cost color hardware options.</p>