<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
?>
<div class="h1">Fleet Attributes</div>
<p>The following provides a summary of your existing printing devices.</p>
<p>Leased devices are shown in gray.</p>
<div class="pheader">Optimized Devices - No Changes Necessary</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 170px;vertical-align: middle"><strong>Device Name</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Total Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Monthly Cost</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Comp. with JIT</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to JIT Program</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($healthcheckViewModel->getOptimizedDevices() as $deviceInstance): ?>
        <?php
        $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }
        ?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) ?>%</td>
            <td class="right"><?php echo number_format(($deviceInstance->isLeased ? $deviceInstance->getLeasedMonthlyRatePercentage($healthcheckViewModel->healthcheck->getHealthcheckSettings()->monthlyLeasePayment, $healthcheckViewModel->getLeasedBlackAndWhiteCharge(), $healthcheckViewModel->getLeasedColorCharge(), $healthcheckViewModel->calculateTotalMonthlyCost()) : $deviceInstance->getMonthlyRatePercentage($healthcheckViewModel->calculateTotalMonthlyCost(), $healthcheckViewModel->getCostPerPageSettingForCustomer(), $healthcheckViewModel->getHealthcheckMargin())), 2) ?>%</td>
            <td class="center"> <?php echo($deviceInstance->reportsTonerLevels ? 'Y' : 'N') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'N' : ($deviceInstance->isManaged ? 'Y' : 'N')) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Underutilized Devices</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 30px;vertical-align: middle"><strong>Device Name</th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Suggested Max. Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Suggested Max. Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Monthly Cost</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Comp. with JIT</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to JIT Program</strong></th>
        <th style="vertical-align: middle" class="center"><strong>Suggested Action</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php

    foreach ($healthcheckViewModel->getUnderutilizedDevices() as $deviceInstance):
        ?>
        <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getMasterDevice()->getMaximumMonthlyPageVolume($healthcheckViewModel->getCostPerPageSettingForCustomer()), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculatePercentOfMaximumRecommendedMaxVolume($healthcheckViewModel->getCostPerPageSettingForCustomer()), 2) ?>%</td>
            <td class="right"><?php echo number_format(($deviceInstance->isLeased ? $deviceInstance->getLeasedMonthlyRatePercentage($healthcheckViewModel->healthcheck->getHealthcheckSettings()->monthlyLeasePayment, $healthcheckViewModel->getLeasedBlackAndWhiteCharge(), $healthcheckViewModel->getLeasedColorCharge(), $healthcheckViewModel->calculateTotalMonthlyCost()) : $deviceInstance->getMonthlyRatePercentage($healthcheckViewModel->calculateTotalMonthlyCost(), $healthcheckViewModel->getCostPerPageSettingForCustomer(), $healthcheckViewModel->getHealthcheckMargin())), 2) ?>%</td>
            <td class="center"> <?php echo($deviceInstance->reportsTonerLevels ? 'Y' : 'N') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'N' : ($deviceInstance->isManaged ? 'Y' : 'N')) ?></td>
            <td>Migrate all page volume to JIT compatible device.</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Overutilized Devices</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 170px;vertical-align: middle"><strong>Device Name</th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Suggested Max. Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Suggested Max. Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Monthly Cost</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Comp. with JIT</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to JIT Program</strong></th>
        <th style="width: 220px;vertical-align: middle" class="center"><strong>Suggested Action</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($healthcheckViewModel->getOverutilizedDevices() as $deviceInstance):
        ?>
        <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getMasterDevice()->getMaximumMonthlyPageVolume($healthcheckViewModel->getCostPerPageSettingForCustomer()), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculatePercentOfMaximumRecommendedMaxVolume($healthcheckViewModel->getCostPerPageSettingForCustomer()), 2) ?>%</td>
            <td class="right"><?php echo number_format(($deviceInstance->isLeased ? $deviceInstance->getLeasedMonthlyRatePercentage($healthcheckViewModel->healthcheck->getHealthcheckSettings()->monthlyLeasePayment, $healthcheckViewModel->getLeasedBlackAndWhiteCharge(), $healthcheckViewModel->getLeasedColorCharge(), $healthcheckViewModel->calculateTotalMonthlyCost()) : $deviceInstance->getMonthlyRatePercentage($healthcheckViewModel->calculateTotalMonthlyCost(), $healthcheckViewModel->getCostPerPageSettingForCustomer(), $healthcheckViewModel->getHealthcheckMargin())), 2) ?>%</td>
            <td class="center"> <?php echo($deviceInstance->reportsTonerLevels ? 'Y' : 'N') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'N' : ($deviceInstance->isManaged ? 'Y' : 'N')) ?></td>
            <td>Migrate excess page volume to an JIT compatible device.</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Old Devices</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 170px;vertical-align: middle"><strong>Device Name</th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Total Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Monthly Cost</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Comp. with JIT</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to JIT Program</strong></th>
        <th style="width: 220px;vertical-align: middle" class="center"><strong>Suggested Action</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($healthcheckViewModel->getOldDevices() as $deviceInstance): ?>
        <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) ?>%</td>
            <td class="right"><?php echo number_format(($deviceInstance->isLeased ? $deviceInstance->getLeasedMonthlyRatePercentage($healthcheckViewModel->healthcheck->getHealthcheckSettings()->monthlyLeasePayment, $healthcheckViewModel->getLeasedBlackAndWhiteCharge(), $healthcheckViewModel->getLeasedColorCharge(), $healthcheckViewModel->calculateTotalMonthlyCost()) : $deviceInstance->getMonthlyRatePercentage($healthcheckViewModel->calculateTotalMonthlyCost(), $healthcheckViewModel->getCostPerPageSettingForCustomer(), $healthcheckViewModel->getHealthcheckMargin())), 2) ?>%</td>
            <td class="center"> <?php echo($deviceInstance->reportsTonerLevels ? 'Y' : 'N') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'N' : ($deviceInstance->isManaged ? 'Y' : 'N')) ?></td>
            <td>Migrate all page volume to a newer JIT compatible device.</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Devices Not Reporting Toner Levels</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 170px;vertical-align: middle"><strong>Device Name</th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Total Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Monthly Cost</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Comp. with JIT</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to JIT Program</strong></th>
        <th style="width: 220px;vertical-align: middle" class="center"><strong>Suggested Action</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($healthcheckViewModel->getDevicesNotReportingTonerLevels() as $deviceInstance):
        ?>
        <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly(), 0) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) ?>%</td>
            <td class="right"><?php echo number_format(($deviceInstance->isLeased ? $deviceInstance->getLeasedMonthlyRatePercentage($healthcheckViewModel->healthcheck->getHealthcheckSettings()->monthlyLeasePayment, $healthcheckViewModel->getLeasedBlackAndWhiteCharge(), $healthcheckViewModel->getLeasedColorCharge(), $healthcheckViewModel->calculateTotalMonthlyCost()) : $deviceInstance->getMonthlyRatePercentage($healthcheckViewModel->calculateTotalMonthlyCost(), $healthcheckViewModel->getCostPerPageSettingForCustomer(), $healthcheckViewModel->getHealthcheckMargin())), 2) ?>%</td>
            <td class="center"> <?php echo($deviceInstance->reportsTonerLevels ? 'Y' : 'N') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'N' : ($deviceInstance->isManaged ? 'Y' : 'N')) ?></td>
            <td>Migrate all page volume to JIT compatible device.</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>