<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
?>
<div class="h1">Next Steps</div>
<ol>
    <li>
        <strong>Financial:</strong> Review your toner usage and costs, and whether you can switch any of your OEM toners to <?php echo My_Brand::getDealerBranding()->shortDealerName ?>
        compatible toners.
    </li>
    <li><strong>Environmental:</strong> Review how many pages you are printing on both sides of the paper, and consider how much you could decrease your
        environmental impact by printing more on both sides.
    </li>
    <li><strong>Hardware Usage:</strong> Review your devices to see where some of your page volumes could be shifted to other devices, and which devices could
        be replaced or removed from your fleet.
    </li>
    <li><strong>MPS:</strong> Consider a managed print program that will allow your printing devices to be remotely managed with a set cost per page, saving you
        time and money and allowing you to focus more on your business.
    </li>
</ol>
<p>Whether you are looking for a comprehensive managed print services plan that includes new equipment, or are looking for assistance in maintaining your
    existing printer fleet, we can design a solution that meets your specific business needs. Let us take care of your print so you can get back to
    business.</p>