<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
?>
<div class="h1">Fleet Attributes</div>
<p>The following provides a summary of your existing printing devices.</p>
<p class="italic-message">Leased devices are shown in gray.</p>
<div class="pheader">Optimized Devices - No Changes Necessary</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 170px;vertical-align: middle"><strong>Device Name</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Fleet's Total Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Suggested Max. Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Life Page Count</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>A3</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Color</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Duplex</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>MFP</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Fax</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Reports Toner Levels</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to <?php echo $this->jit; ?> Program</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($healthcheckViewModel->getOptimizedDevices() as $deviceInstance): ?>
        <?php
        $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }
        ?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly()) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) ?>%</td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->calculateEstimatedMaxLifeCount()) ?></td>
            <td class="center"> <?php echo($deviceInstance->getMeter()->endMeterLife) ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isA3 ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isColor() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isDuplex ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isMfp() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isFax ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->isCapableOfReportingTonerLevels() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'No' : ($deviceInstance->isManaged ? 'Yes' : 'No')) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Underutilized Devices</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 30px;vertical-align: middle"><strong>Device Name</th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Fleet's Total Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Suggested Max. Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Life Page Count</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>A3</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Color</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Duplex</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>MFP</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Fax</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Reports Toner Levels</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to <?php echo $this->jit; ?> Program</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php

    foreach ($healthcheckViewModel->getUnderutilizedDevices() as $deviceInstance):
        ?>
        <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly()) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()),2)?>%</td>
            <td class="right"><?php echo number_format($deviceInstance->getMasterDevice()->calculateEstimatedMaxLifeCount()) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getMeter()->endMeterLife) ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isA3 ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isColor() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isDuplex ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isMfp() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isFax ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->isCapableOfReportingTonerLevels() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'No' : ($deviceInstance->isManaged ? 'Yes' : 'No')) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Overutilized Devices</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 170px;vertical-align: middle"><strong>Device Name</th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Fleet's Total Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Suggested Max. Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Life Page Count</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>A3</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Color</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Duplex</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>MFP</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Fax</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Reports Toner Levels</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to <?php echo $this->jit; ?> Program</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($healthcheckViewModel->getOverutilizedDevices() as $deviceInstance):
        ?>
        <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly()) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) ?>%</td>
            <td class="right"><?php echo number_format($deviceInstance->getMasterDevice()->calculateEstimatedMaxLifeCount()) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getMeter()->endMeterLife) ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isA3 ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isColor()? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isDuplex) ? 'Yes' : 'No'?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isMfp()) ? 'Yes' : 'No'?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isFax) ? 'Yes' : 'No'?></td>
            <td class="center"> <?php echo($deviceInstance->isCapableOfReportingTonerLevels() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'No' : ($deviceInstance->isManaged ? 'Yes' : 'No')) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Old Devices</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 170px;vertical-align: middle"><strong>Device Name</th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Fleet's Total Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Monthly Cost</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Suggested Max. Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Life Page Count</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>A3</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Color</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Duplex</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>MFP</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Fax</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Reports Toner Levels</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to <?php echo $this->jit; ?> Program</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($healthcheckViewModel->getOldDevices() as $deviceInstance): ?>
        <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly()) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) ?>%</td>
            <td class="right"><?php echo ($deviceInstance->isLeased)
                    ? number_format($deviceInstance->getLeasedMonthlyRatePercentage(
                        $healthcheckViewModel->healthcheck->getHealthcheckSettings()->monthlyLeasePayment,
                        $healthcheckViewModel->getLeasedBlackAndWhiteCharge(),
                        $healthcheckViewModel->getLeasedColorCharge(),
                        $healthcheckViewModel->calculateTotalMonthlyCost()
                    )*100,2)
                    : number_format($deviceInstance->getMonthlyRatePercentage(
                        $healthcheckViewModel->calculateTotalMonthlyCost(),
                        $healthcheckViewModel->getCostPerPageSettingForCustomer()
                    )*100,2) ?>%</td>
            <td class="center"> <?php echo number_format($deviceInstance->getMasterDevice()->calculateEstimatedMaxLifeCount()) ?></td>
            <td class="center"> <?php echo number_format($deviceInstance->getMeter()->endMeterLife) ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isA3 ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isColor() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isDuplex ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isMfp() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->getMasterDevice()->isFax ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->isCapableOfReportingTonerLevels() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'No' : ($deviceInstance->isManaged ? 'Yes' : 'No')) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="pheader">Devices Not Reporting Toner Levels</div>
<table cellspacing="0" class="genericTable" style="font-size: 10pt;">
    <thead>
    <tr class="shaded">
        <th style="width: 170px;vertical-align: middle"><strong>Device Name</th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Device Age (Years)</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Percent of Fleet's Total Monthly Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Suggested Max. Page Volume</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Life Page Count</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>A3</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Color</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Duplex</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>MFP</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Fax</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Reports Toner Levels</strong></th>
        <th style="width: 51px;vertical-align: middle" class="center"><strong>Linked to <?php echo $this->jit; ?> Program</strong></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($healthcheckViewModel->getDevicesNotReportingTonerLevels() as $deviceInstance):
        ?>
        <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
        <tr class="<?php
        if ($deviceInstance->isLeased)
        {
            echo ' shaded';
        }?>">
            <td><?php echo $deviceName ?>
                <br /> <?php echo (strlen($deviceInstance->serialNumber) > 14) ? substr($deviceInstance->serialNumber, 0, 11) . '...' : $deviceInstance->serialNumber; ?>
                <br /> <?php echo $deviceInstance->ipAddress; ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getAge(), 0) ?></td>
            <td class="right"><?php echo $this->formatPageVolume($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly()) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) ?>%</td>
            <td class="right"><?php echo number_format($deviceInstance->getMasterDevice()->calculateEstimatedMaxLifeCount()) ?></td>
            <td class="right"><?php echo number_format($deviceInstance->getMeter()->endMeterLife) ?></td>
            <td class="right"><?php echo ($deviceInstance->getMasterDevice()->isA3 ? 'Yes' : 'No') ?></td>
            <td class="right"><?php echo ($deviceInstance->getMasterDevice()->isColor() ? 'Yes' : 'No') ?></td>
            <td class="right"><?php echo ($deviceInstance->getMasterDevice()->isDuplex ? 'Yes' : 'No') ?></td>
            <td class="right"><?php echo ($deviceInstance->getMasterDevice()->isMfp() ? 'Yes' : 'No') ?></td>
            <td class="right"><?php echo ($deviceInstance->getMasterDevice()->isFax ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->isCapableOfReportingTonerLevels() ? 'Yes' : 'No') ?></td>
            <td class="center"> <?php echo($deviceInstance->isLeased ? 'No' : ($deviceInstance->isManaged ? 'Yes' : 'No')) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
