<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;

?>
<div class="pheader">Printing Device Management Breakdown</div>
<p>Different types of printing devices are managed in different ways. Newer networked printers can be managed with remote monitoring software; leased multifunction devices are typically managed by the vendor who sold the machine; devices not connected to the network, such as inkjets and some older printers, are difficult to manage because you cannot monitor them with software.</p>
<br />
<div class="center">
    <table>
        <tbody>
        <tr>
            <td><img src="?png=UnmanagedVsManagedDevices" /></td>
            <!-- Devices leased/Devices Purchased -->
            <td><img src="?png=PagesWithOrWithoutJIT" /></td>
            <!-- Monthly pages on leased MFPs/Monthly pages on devices not leased -->
        </tr>
        </tbody>
    </table>
</div>
<div class="pheader">Number of Printing Device Models and Supply Types</div>
<p>Out of your
    <strong><?= $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount(); ?></strong> networked printing devices, you have of
    <strong><?= $healthcheckViewModel->getNumberOfUniqueModels(); ?></strong> unique models. Each section of the chart below represents a single model type. Models with less than or equal to 0.7% of the total device count are put into the "Other" group.
</p>
<div class="center">
    <img src="?png=UniqueDevicesGraph" /> <!--  Giant pie chart -->
</div>
<?php
$uniqueDeviceArray = $healthcheckViewModel->getUniqueDeviceCountArray();
$totalAmount       = $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount();
$amountOfRows      = ceil(count($uniqueDeviceArray) / 2);

//FirstHalf is whether we are writing to the left side of the table or the right side.
$firstColumn  = true;
$colorCounter = 0;

$tableData = [];

?>
<table class="table-bordered" style="border-collapse: collapse; width:100%">
    <?php

    $counter = 0;
    foreach ($uniqueDeviceArray as $key => $deviceCount)
    {
        if ($counter < $amountOfRows)
        {
            $tableData[$counter]["column1"] = [
                "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
                "name"    => $key . " (" . $deviceCount . ")",
                "percent" => number_format(($deviceCount / $totalAmount) * 100, 1) . "%",
            ];
        }
        else
        {
            $tableData[$counter - $amountOfRows]["column2"] = [
                "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
                "name"    => $key . " (" . $deviceCount . ")",
                "percent" => number_format(($deviceCount / $totalAmount) * 100, 1) . "%",
            ];

        }
        $counter++;
    }
    ?>
    <?php foreach ($tableData as $row) : ?>
        <tr>
            <?php if (array_key_exists("column1", $row)) : ?>
                <td style="border:1px solid">
                    <div style="width:20px;height:20px;margin: auto;background-color:#<?= $row["column1"]["color"]; ?>"></div>
                </td>
                <td style="border:1px solid"><?= $row["column1"]["name"]; ?></td>
                <td style="border:1px solid"><?= $row["column1"]["percent"] ?></td>
            <?php else : ?>
                <td colspan="3">&nbsp;</td>
            <?php endif; ?>


            <?php if (array_key_exists("column2", $row)) : ?>
                <td style="border:1px solid">
                    <div style="width:20px;height:20px;margin: auto;background-color:#<?= $row["column2"]["color"]; ?>"></div>
                </td>
                <td style="border:1px solid"><?= $row["column2"]["name"]; ?></td>
                <td style="border:1px solid"><?= $row["column2"]["percent"] ?></td>
            <?php else : ?>
                <td colspan="3">&nbsp;</td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
</table>
<p>By using printing devices that use the same supplies, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space required. The <?= My_Brand::getDealerBranding()->mpsProgramName ?> program can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.</p>
<div class="pheader">Number of Printing Device Vendors</div>
<p>Out of your <?= count($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getDeviceInstances()) ?>
    networked printing devices, you have <strong>
        <?= count($healthcheckViewModel->getDeviceVendorCount());
        ?></strong> unique vendors. Each section of the chart below represents a single vendor name.

<div class="center">
    <img src="?png=PercentPerDeviceBrand" />
</div>

<?php
$deviceVendorCount = $healthcheckViewModel->getDeviceVendorCount();
$totalAmount       = $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount();
$amountOfRows      = ceil(count($deviceVendorCount) / 2);

//FirstHalf is whether we are writing to the left side of the table or the right side.
$firstColumn  = true;
$colorCounter = 0;

$tableData = [];

?>
<table class="table-bordered" style="border-collapse: collapse; width:100%">
    <?php

    $counter = 0;
    foreach ($deviceVendorCount as $key => $deviceCount)
    {
        if ($counter < $amountOfRows)
        {
            $tableData[$counter]["column1"] = [
                "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
                "name"    => $key . " (" . $deviceCount . ")",
                "percent" => number_format(($deviceCount / $totalAmount) * 100, 1) . "%",
            ];
        }
        else
        {
            $tableData[$counter - $amountOfRows]["column2"] = [
                "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
                "name"    => $key . " (" . $deviceCount . ")",
                "percent" => number_format(($deviceCount / $totalAmount) * 100, 1) . "%",
            ];

        }
        $counter++;
    }
    ?>
    <?php foreach ($tableData as $row) : ?>
        <tr>
            <?php if (array_key_exists("column1", $row)) : ?>
                <td style="border:1px solid">
                    <div style="width:20px;height:20px;margin: auto;background-color:#<?= $row["column1"]["color"]; ?>"></div>
                </td>
                <td style="border:1px solid"><?= $row["column1"]["name"]; ?></td>
                <td style="border:1px solid"><?= $row["column1"]["percent"] ?></td>
            <?php else : ?>
                <td colspan="3">&nbsp;</td>
            <?php endif; ?>


            <?php if (array_key_exists("column2", $row)) : ?>
                <td style="border:1px solid">
                    <div style="width:20px;height:20px;margin: auto;background-color:#<?= $row["column2"]["color"]; ?>"></div>
                </td>
                <td style="border:1px solid"><?= $row["column2"]["name"]; ?></td>
                <td style="border:1px solid"><?= $row["column2"]["percent"] ?></td>
            <?php else : ?>
                <td colspan="3">&nbsp;</td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
</table>

<div class="pheader">Number of Printing Devices Compatible with <?= My_Brand::getDealerBranding()->shortDealerName; ?></div>
<p>Out of your <?= $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount(); ?> networked printing devices, you have
    <strong><?= $healthcheckViewModel->getDevices()->isManagedDeviceInstances->getCount(); ?></strong> devices that are managed,  <?= $healthcheckViewModel->getDevices()->unmanagedDeviceInstances->getCount(); ?> devices that are not compatible and <?= $healthcheckViewModel->getDevices()->compatibleDeviceInstances->getCount() ?> devices compatible with <?= $this->jitFullName ?>. These non compatible devices are shown in the fleet attributes section below. A complete list of all devices and their <?= $this->jit ?> compatibility can be found in the Appendix.
</p>
<br />
<div class="center">
    <table>
        <tbody>
        <tr>
            <td><img src="?png=ManagedVsNotJitVsJitDevices" />
            </td>
            <td>
                <img src="?png=PagesPrintedManagedVsJitVsCompVsLeased" />
            </td>
        </tr>
        </tbody>
    </table>
</div>