<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs               = $healthcheckViewModel->getGraphs();
?>
<div class="h1">Analysis: Technology Reliability and User Productivity</div>
<div class="pheader">Age of Printing Devices</div>
<p>We estimate the average age of your printing devices is <?= number_format($healthcheckViewModel->getAverageAgeOfDevices(), 1) ?> years(s); a good industry average is 3 years. Devices over 5 years old receive, on average, one repair per year.</p>
<div class="center">
    <img src="<?= $graphs['AgePieGraph']; ?>" />
</div>
<p>A breakdown of the ages of your printing devices is shown above.</p>
<br />
<br />
<?= $this->noBreakEnd; ?>
<?= $this->noBreakStart; ?>
<div class="pheader">Technology Features and Functionality</div>
<p>The ability to scan and fax documents from convenient locations helps to improve document workflow and productivity, and scanning can also help reduce the number of pages printed. Color printing capabilities are important if you are generating client-facing or other important documents in-house.</p>
<p>The charts below show the number of your printing devices that are capable of copying, duplex printing, and color printing.</p>
<br />
<img src="?png=CopyCapableDevicesGraph" style="width: 190px; height: 150px;" /> <!-- Copy capable devices -->
<img src="?png=DuplexCapableDevicesGraph" style="width: 190px; height: 150px;" /> <!-- Duplex capable devices -->
<img src="?png=ColorCapablePieChart" style="width: 190px; height: 150px;" /> <!-- Color capable devices -->
<br />
<br />
<p>If you are in need of additional features and functionality to improve workflow and print quality, <?= $this->reportName ?> has a variety of printing devices that can meet your specific business needs. If you already have everything you need, we can manage the printing assets you have.</p>
