<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
?>
<div class="titlepage">
    <div class="header">
        <div class="title-page-logo-box-wrapper">
            <div class="title-page-logo-box">
                <img class="title-page-logo" src="<?= $this->serverUrl($this->dealerLogoFile) ?> " />
            </div>
        </div>
    </div>
    <div class="title-page-report-title">
        <h2><?= My_Brand::getDealerBranding()->healthCheckTitle ?></h2>
    </div>
    <div class="title-page-customer-details">
        <h3>Prepared for:
            <?php if (strlen($healthcheckViewModel->healthcheck->getClient()->companyName) > 26) : ?>
                <br>
            <?php endif; ?>
            <?= $healthcheckViewModel->healthcheck->getClient()->companyName; ?>
        </h3>

        <p><?= nl2br($healthcheckViewModel->healthcheck->getClient()->getAddress()); ?></p>
        <br />

        <p>Date: <?= $healthcheckViewModel->getDateReportPrepared(); ?></p>
    </div>
</div>