<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
  	echo $this->pageStart;
?>
	<?php echo $this->noBreakStart; ?>
		<div class="h1">Solution 1: PrintIQ&reg;</div>
		<p>Get the most out of your existing printing assets with the PrintIQ&reg; program. Office Depot will take over the management of your current printing equipment
		and wrap your supplies and service into a single invoice.</p>
		
		<div class="pheader">Program Components</div>
		<p>Pay by the page with the PrintIQ&reg; program:</p>
		<ul class="bold" style="margin-bottom: 0pt;">			
			<li>$<?php echo $this->NumberFormat($proposal->getMPSBlackAndWhiteCPP(),8); ?> for monochrome pages</li>
			<li>$<?php echo $this->NumberFormat($proposal->getMPSColorCPP(),8); ?> for color pages</li>
			<li>Includes supplies and service for your existing equipment</li>
		</ul>
		<p style="margin-top: 0pt;">The PrintIQ&reg; program uses remote monitoring software to provide you with:</p>
		<ul>
			<li>Just-in-time supplies fulfillment</li>
			<li>Efficient maintenance and break-fix service</li>
			<li>Monthly business intelligence reports</li>
		</ul>
		
		<div class="pheader">Estimated Annual Savings</div>
		<p style="margin: 10pt 0pt;">Based on information from your PrintIQ&reg; Smart Assessment, we have estimated your annual cost savings:</p>
		<table class="genericTable" style="font-size: 9.5pt">
			<thead>
				<tr>
					<th colspan="2">Current Scenario</th>
					<th colspan="2">Proposed Scenario</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Ink and toner</td>
					<td class="right">$<?php echo number_format($proposal->getCostOfInkAndToner()); ?></td>

					<td>Monochrome cost per page</td>
					<td class="right">$<?php echo number_format($proposal->getMPSBlackAndWhiteCPP(),4); ?></td>
				</tr>
				<tr>
					<td>Executing supplies orders</td>
					<td class="right">$<?php echo number_format($proposal->getCostOfExecutingSuppliesOrder()); ?></td>

					<td>Color cost per page</td>
					<td class="right">$<?php echo number_format($proposal->getMPSColorCPP(),4); ?></td>
				</tr>
				<tr>
					<td>External service</td>
					<td class="right">$<?php echo number_format($proposal->getAnnualCostOfOutSourcing()); ?></td>

					<td>Estimated monochrome pages</td>
					<td class="right"><?php echo number_format($proposal->getPageCounts()->Purchased->BlackAndWhite->Yearly); ?></td>
				</tr>
				<tr>
					<td>Internal IT support for printers</td>
					<td class="right">$<?php echo number_format($proposal->getAnnualITCost()); ?></td>

					<td>Estimated color pages</td>
					<td class="right"><?php echo number_format($proposal->getPageCounts()->Purchased->Color->Yearly); ?></td>
				</tr>
				<tr>
					<td>Hardware purchases</td>
					<td class="right">$<?php echo number_format($proposal->getAnnualCostOfHardwarePurchases()); ?></td>

					<td width="233">Cost of monochrome pages</td> <!-- Simply stretched table to width of page (temp workaround) -->
					<td width="60" class="right">$<?php echo number_format($proposal->getPageCounts()->Purchased->BlackAndWhite->Yearly * $proposal->getMPSBlackAndWhiteCPP()); ?></td>
				</tr>
				<tr>
					<td width="233"></td> <!-- Stretched table to width of page (temp workaround) -->
					<td width="60"></td>
					
					<td>Cost of color pages</td>
					<td class="right">$<?php echo number_format($proposal->getPageCounts()->Purchased->Color->Yearly * $proposal->getMPSColorCPP()); ?></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					
					<td>Processing 1 invoice/month @ <?php echo $this->currency($proposal->report->getSurvey()->costToExecuteSuppliesOrder); ?></td>
					<td class="right">$<?php echo number_format($proposal->getInternalAdminCost()); ?></td>
				</tr>
				<tr>
					<td></td>
					<td></td>

					<td>External service</td>
					<td class="right">Included</td>
				</tr>
				<tr>
					<td></td>
					<td></td>

					<td>Internal IT support for printers</td>
					<td class="right">$<?php echo number_format($proposal->getAnnualITCost() * 0.5); ?></td>
				</tr>
				<tr>
					<td></td>
					<td></td>

					<td>Hardware purchases</td>
					<td class="right">$<?php echo number_format($proposal->getAnnualCostOfHardwarePurchases()); ?></td>
				</tr>
				<tr class="bold">
					<td>Total Cost</td>
					<td class="right">$<?php echo number_format($proposal->getTotalPurchasedAnnualCost()); ?></td>

					<td>Total Cost</td>
					<td class="right">$<?php echo number_format($proposal->getPrintIQTotalCost()); ?></td>
				</tr>
			</tbody>
		</table>
		
		<p style="margin: 15pt 0pt;">Note that although the page volumes from all of your purchased devices were included in our savings calculations, not all of them may qualify for our managed print services program or just-in-time supplies fulfillment. Volumes from unqualified devices would have to be merged to an existing or new qualified device to be included in the program. Please see the Appendix for a complete printing device list with details on compatibility with the PrintIQ&reg; program.</p>
		
		<div class="annualSavings">
			<table>
				<tbody>
					<tr>
						<td width="490" class="left""><strong>Total annual savings with PrintIQ&reg;</strong></td>
						<td width="125" class="right""><strong>$<?php echo number_format($proposal->getPrintIQSavings()); ?></strong></td>
					</tr>
				</tbody>
			</table>
		</div>
	<?php echo $this->noBreakEnd; ?>
<?php
    // Page End is handled in 04_PrintIQPlus_Replacements.phtml since if that file is not displayed, a disclaimer is added to the end of this page
?>