<div class="well">
    <?php echo $this->form; ?>
</div>

<h1>--- Development ---</h1>
<div class="well">
    <p>Device Name Here</p>
    <form method="POST" class="form-inline">
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th style="width: 180px">Sku</th>
                <th>Option Name</th>
                <th style="width: 80px">Qty</th>
            </tr>
            <tr>
                <td>PRPTRY500</td>
                <td>250 Sheet Paper Tray</td>
                <td><input type="text" value="1" class="span1" /></td>
            </tr>
        </table>
        <button type="submit" class="btn btn-success">Add Options</button>
    </form>
    <form method="POST">
    
    </form>
</div>