<?php $deviceConfiguration = $this->deviceConfiguration; /* @var $deviceConfiguration Quotegen_Model_DeviceConfiguration */?>
<div class="well">
    
    <?php echo $this->form; ?>
    <?php if (count($deviceConfiguration->getOptions()) > 0) : ?>
    <div class="row">
        <div class="span6 offset2">
            <h3>Options <a href="<?php echo $this->url(array('action' => 'addoptions')); ?>" class="btn btn-success btn-mini"><i class="icon-plus-sign icon-white"></i> Add</a></h3>
            <table class="table table-bordered table-striped table-condensed">
                <tr>
                    <th>Option</th>
                    <th style="width: 30px;"></th>
                </tr>
                <?php foreach ($deviceConfiguration->getOptions() as $option) : /* @var $option Quotegen_Model_Option */ ?>
                <tr>
                    <td><?php echo $option->getName(); ?></td>
                    <td><a href="<?php echo $this->url(array('action' => 'deleteoption', 'optionId' => $option->getId()));?>" class="btn btn-mini btn-danger"><i class="icon-trash"></i></a></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <?php else : ?>
    <h4>There are no options currently associated with this deviceConfiguration. Please click the add button above to associate options with this deviceConfiguration.</h4>
    <?php endif;?>
    
</div>