<?php
/**
 * Cost Analysis - Header information
 *
 * This script contains everything that comes before the big table of
 * information in the cost analysis.
 */
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

/**
 * Variables
 */
// Add any variables that are needed throughout the page here.


/**
 * Section starts here
 */

$section->addTitle('Gross Margin Report');
$textRun = $section->createTextRun();
$textRun->addText('AMPV = Average Monthly Page Volume', 'italic_text');

// Table with values
$tcStyle = $this->styles->tables->settings;
$table   = $section->addTable($tcStyle->tablestyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText(sprintf('%1$s Black And White CPP:', $this->brandName), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText($this->formatCostPerPage($assessmentViewModel->getMPSBlackAndWhiteCPP()), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText('Total Cost:', $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText($this->currency($assessmentViewModel->getGrossMarginTotalMonthlyCost()->Combined), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText(sprintf('%1$s Color CPP:', $this->brandName), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText($this->formatCostPerPage($assessmentViewModel->getMPSColorCPP()), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText('Total Revenue:', $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText($this->currency($assessmentViewModel->getGrossMarginTotalMonthlyRevenue()->Combined), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText('Weighted Black And White CPP:', $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText($this->formatCostPerPage($assessmentViewModel->getGrossMarginWeightedCPP()->BlackAndWhite), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText('Monthly Profit:', $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText($this->currency($assessmentViewModel->getGrossMarginMonthlyProfit($assessmentViewModel->getCostPerPageSettingForDealer())), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText('Weighted Color CPP:', $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText($this->formatCostPerPage($assessmentViewModel->getGrossMarginWeightedCPP()->Color), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText('Overall Margin:', $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText(number_format($assessmentViewModel->getGrossMarginOverallMargin($assessmentViewModel->getCostPerPageSettingForDealer())) . '%', $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText('Black And White Margin:', $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText(number_format($assessmentViewModel->getGrossMarginBlackAndWhiteMargin()) . '%', $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText('Color Margin:', $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText(number_format($assessmentViewModel->getGrossMarginColorMargin()) . '%', $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$textRun = $section->createTextRun();
$textRun = $section->createTextRun();
$textRun->addText('Yellow highlighted rows indicate devices that have not been assigned toners matching your selected first toner vendor preference. For these devices the system has selected the best available alternative based on your preference.', 'italic_text', 'nospacing_centeralign');

