<?php
/**
 * Cost Analysis - Header information
 *
 * This script contains everything that comes before the big table of
 * information in the cost analysis.
 */
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

/**
 * Variables
 */
// Add any variables that are needed throughout the page here.


/**
 * Section starts here
 */

$section->addTitle($this->translate('Gross Margin Report'));
$textRun = $section->createTextRun();
$textRun->addText($this->translate('AMPV = Average Monthly Page Volume'), 'italic_text');

// Table with values
$tcStyle = $this->styles->tables->settings;
$table = $section->addTable($tcStyle->tablestyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText(sprintf($this->translate('%1$s Black And White CPP:'),$this->brandName), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText('$' . number_format($assessmentViewModel->getMPSBlackAndWhiteCPP(), 4), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle );
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText($this->translate('Total Cost:'), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText('$' . number_format($assessmentViewModel->getGrossMarginTotalMonthlyCost()->Combined, 2), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText(sprintf($this->translate('%1$s Color CPP:'),$this->brandName), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText('$' . number_format($assessmentViewModel->getMPSColorCPP(), 4), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText($this->translate('Total Revenue:'), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText('$' . number_format($assessmentViewModel->getGrossMarginTotalMonthlyRevenue()->Combined, 2), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText($this->translate('Weighted Black And White CPP:'), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText('$' . number_format($assessmentViewModel->getGrossMarginWeightedCPP()->BlackAndWhite, 4), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText($this->translate('Monthly Profit:'), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText('$' . number_format($assessmentViewModel->getGrossMarginMonthlyProfit(), 2), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText($this->translate('Weighted Color CPP:'), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText('$' . number_format($assessmentViewModel->getGrossMarginWeightedCPP()->Color, 4), $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText($this->translate('Overall Margin:'), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText(number_format($assessmentViewModel->getGrossMarginOverallMargin()) . '%', $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$table->addRow($tcStyle->row->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->row->labelcell->cellStyle)->addText($this->translate('Black And White Margin:'), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col2Width, $tcStyle->row->valuecell->cellStyle)->addText(number_format($assessmentViewModel->getGrossMarginBlackAndWhiteMargin()) . '%', $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);
$table->addCell($tcStyle->col3Width, $tcStyle->row->labelcell->cellStyle)->addText($this->translate('Color Margin:'), $tcStyle->row->labelcell->fontStyle, $tcStyle->row->labelcell->paragraphStyle);
$table->addCell($tcStyle->col4Width, $tcStyle->row->valuecell->cellStyle)->addText(number_format($assessmentViewModel->getGrossMarginColorMargin()) . '%', $tcStyle->row->valuecell->fontStyle, $tcStyle->row->valuecell->paragraphStyle);

$textRun = $section->createTextRun();
$textRun = $section->createTextRun();
$textRun->addText($this->translate('Yellow highlighted rows indicate devices that have not been assigned toners matching your selected preference of ' . $assessmentViewModel->assessment->getAssessmentSettings()->getGrossMarginPricingConfig()->getNiceConfigName() . '. For these devices the system has selected the best available alternative.'), 'italic_text', 'nospacing_centeralign');

