<?php
/**
 * Cost Analysis - Main Table
 *
 * This script contains everything for the main table of the cost analysis.
 */
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;

/**
 * Variables
 */
// Add any variables that are needed throughout the page here.


/**
 * Section starts here
 */
// You would normally put this here if you needed it but in the cost analysis we do not need it.
// $section->addPageBreak();

$tcStyle = $this->styles->tables->grossMargin;
$table   = $section->addTable($tcStyle->tablestyle);

// Table header
$table->addRow($tcStyle->header->rowheight, $tcStyle->header->fontStyle);
$table->addCell($tcStyle->col1Width, $tcStyle->header->nobottomborder)->addText(null, $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->colSpanWidth, $tcStyle->header->cell, 5)->addText($this->translate('Black And White'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->colSpanWidth, $tcStyle->header->cell, 5)->addText($this->translate('Color'), $tcStyle->header->fontStyle, $tcStyle->centeralign);

$table->addRow($tcStyle->header->rowheight, $tcStyle->header->fontStyle);

$column1 = $table->addCell($tcStyle->col1Width, $tcStyle->header->notopborder);
$column1->addText($this->translate('Device Name'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$column1->addText($this->translate('(IP Address - Serial Number)'), $tcStyle->header->fontStyle, $tcStyle->centeralign);

$table->addCell($tcStyle->col2Width, $tcStyle->header->cell)->addText($this->translate('AMPV'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col3Width, $tcStyle->header->cell)->addText($this->translate('Toner Cost'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col4Width, $tcStyle->header->cell)->addText($this->translate('Toner Yield'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col5Width, $tcStyle->header->cell)->addText($this->translate('CPP'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col6Width, $tcStyle->header->cell)->addText($this->translate('Total Printing Cost'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col7Width, $tcStyle->header->cell)->addText($this->translate('AMPV'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col8Width, $tcStyle->header->cell)->addText($this->translate('Toner Cost'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col9Width, $tcStyle->header->cell)->addText($this->translate('Toner Yield'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col10Width, $tcStyle->header->cell)->addText($this->translate('CPP'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col11Width, $tcStyle->header->cell)->addText($this->translate('Total Printing Cost'), $tcStyle->header->fontStyle, $tcStyle->centeralign);


foreach ($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances() as $deviceInstance)
{
    $dealerCostPerPageSettings = $assessmentViewModel->getCostPerPageSettingForDealer();
    $completeMonoToners        = $deviceInstance->getMasterDevice()->getHasValidMonoGrossMarginToners($assessmentViewModel->getCostPerPageSettingForDealer());
    $completeColorToners       = $deviceInstance->getMasterDevice()->getHasValidColorGrossMarginToners($assessmentViewModel->getCostPerPageSettingForDealer());
    $blackToner                = null;
    $colorToner                = null;
    $toners                    = $deviceInstance->getMasterDevice()->getCheapestTonerSetByVendor($assessmentViewModel->getCostPerPageSettingForDealer());

    foreach ($toners as $toner)
    {
        switch ($toner->tonerColorId)
        {
            case Proposalgen_Model_TonerColor::BLACK:
                $blackToner = $toner;
                break;
            case Proposalgen_Model_TonerColor::CYAN:
            case Proposalgen_Model_TonerColor::MAGENTA:
            case Proposalgen_Model_TonerColor::YELLOW:
                $colorToner = $toner;
                break;
            case Proposalgen_Model_TonerColor::THREE_COLOR:
                $colorToner = $toner;
                break;
            case Proposalgen_Model_TonerColor::FOUR_COLOR:
                $blackToner = $toner;
                $colorToner = $toner;
                break;
            default:
                break;
        }
    }

    // Black Toner
    $blackCost  = "$" . number_format($blackToner->cost, 2);
    $blackYield = number_format($blackToner->yield);

    // Color Toner
    $colorCost  = "-";
    $colorStyle = "style='text-align: center;'";
    $colorYield = "-";
    $isColor    = false;
    if ($colorToner)
    {
        $colorCost  = "$" . number_format($colorToner->cost, 2);
        $colorYield = number_format($colorToner->yield);
        $colorStyle = 'right';
        $isColor    = true;
    }

    // Row Colors
    $mono_toner_class  = ($completeMonoToners) ? $tcStyle->row->cell : $tcStyle->row->highlightcell;
    $color_toner_class = ($completeColorToners) ? $tcStyle->row->cell : $tcStyle->row->highlightcell;

    $table->addRow($tcStyle->cell->rowheight);
    $column1 = $table->addCell($tcStyle->col1Width, $tcStyle->row->cell);
    $column1->addText($this->translate(str_ireplace("hewlett-packard", "HP", $deviceInstance->getDeviceName())), $tcStyle->row->fontStyle, $tcStyle->leftalign);
    $column1->addText("(" . $deviceInstance->ipAddress . " - " . $deviceInstance->serialNumber . ")", $tcStyle->row->fontStyle, $tcStyle->leftalign);

    // Mono
    $table->addCell($tcStyle->col2Width, $mono_toner_class)->addText(number_format($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col3Width, $mono_toner_class)->addText($blackCost, $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col4Width, $mono_toner_class)->addText($blackYield, $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col5Width, $mono_toner_class)->addText(number_format($deviceInstance->calculateCostPerPage($assessmentViewModel->getCostPerPageSettingForDealer())->monochromeCostPerPage, 4), $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col6Width, $mono_toner_class)->addText("$" . number_format($deviceInstance->getMonthlyBlackAndWhiteCost($assessmentViewModel->getCostPerPageSettingForDealer()), 2), $tcStyle->row->fontStyle, $tcStyle->rightalign);

    // Color
    $table->addCell($tcStyle->col7Width, $color_toner_class)->addText(($isColor) ? number_format($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : "-", $tcStyle->row->fontStyle, ($isColor) ? $tcStyle->rightalign : $tcStyle->centeralign);
    $table->addCell($tcStyle->col8Width, $color_toner_class)->addText($colorCost, $tcStyle->row->fontStyle, (trim($colorCost) != "-") ? $tcStyle->rightalign : $tcStyle->centeralign);
    $table->addCell($tcStyle->col9Width, $color_toner_class)->addText($colorYield, $tcStyle->row->fontStyle, (trim($colorYield) != "-") ? $tcStyle->rightalign : $tcStyle->centeralign);
    $table->addCell($tcStyle->col10Width, $color_toner_class)->addText(($isColor) ? number_format($deviceInstance->calculateCostPerPage($assessmentViewModel->getCostPerPageSettingForDealer())->colorCostPerPage, 4) : "-", $tcStyle->row->fontStyle, ($isColor ? $tcStyle->rightalign : $tcStyle->centeralign));
    $table->addCell($tcStyle->col11Width, $color_toner_class)->addText(($isColor) ? "$" . number_format($deviceInstance->calculateMonthlyColorCost($assessmentViewModel->getCostPerPageSettingForDealer()), 2) : "-", $tcStyle->row->fontStyle, ($isColor ? $tcStyle->rightalign : $tcStyle->centeralign));

}

// Table footer (totals row)
$table->addRow($tcStyle->footer->rowheight);
$table->addCell($tcStyle->col1Width, $tcStyle->footer->cell)->addText($this->translate('Totals for ' . $assessmentViewModel->getDevices()->purchasedDeviceInstances->getCount() . ' devices:'), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col2Width, $tcStyle->footer->cell)->addText(number_format($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col3Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col4Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col5Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col6Width, $tcStyle->footer->cell)->addText('$' . number_format($assessmentViewModel->getGrossMarginTotalMonthlyCost()->BlackAndWhite, 2), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col7Width, $tcStyle->footer->cell)->addText(number_format($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly()), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col8Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col9Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col10Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col11Width, $tcStyle->footer->cell)->addText('$' . number_format($assessmentViewModel->getGrossMarginTotalMonthlyCost()->Color, 2), $tcStyle->footer->fontStyle, $tcStyle->rightalign);