<?php
/**
 * Cost Analysis - Main Table
 *
 * This script contains everything for the main table of the cost analysis.
 */
/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$dealerId            = Zend_Auth::getInstance()->getIdentity()->dealerId;

/**
 * Variables
 */
// Add any variables that are needed throughout the page here.


/**
 * Section starts here
 */
// You would normally put this here if you needed it but in the cost analysis we do not need it.
// $section->addPageBreak();

$tcStyle = $this->styles->tables->grossMargin;
$table   = $section->addTable($tcStyle->tablestyle);

// Table header
$table->addRow($tcStyle->header->rowheight,$tcStyle->rowheader);
$table->addCell($tcStyle->col1Width, $tcStyle->header->nobottomborder)->addText(null, $tcStyle->header->fontStyle, $tcStyle->centeralign);

$blackAndWhite = $table->addCell($tcStyle->colSpanWidth, $tcStyle->header->headercelllarge, 5);
$blackAndWhite->addText('Black And White', $tcStyle->header->fontStyle, $tcStyle->centeralign);

$color = $table->addCell($tcStyle->colSpanWidth, $tcStyle->header->headercelllarge, 5);
$color->addText('Color', $tcStyle->header->fontStyle, $tcStyle->centeralign);

$tonerSkus = $table->addCell($tcStyle->colSpanWidth, $tcStyle->header->headercellsmall, 2);
$tonerSkus->addText('Toner SKUs', $tcStyle->header->fontStyle, $tcStyle->centeralign);

$table->addRow($tcStyle->header->rowheight,$tcStyle->rowheader);

$column1 = $table->addCell($tcStyle->col1Width, $tcStyle->header->notopborder);
$column1->addText('Device Name', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$column1->addText('(IP Address - Serial Number)', $tcStyle->header->fontStyle, $tcStyle->centeralign);

$table->addCell($tcStyle->col2Width, $tcStyle->header->cell)->addText('AMPV', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col3Width, $tcStyle->header->cell)->addText('Toner Cost', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col4Width, $tcStyle->header->cell)->addText('Toner Yield', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col5Width, $tcStyle->header->cell)->addText('CPP', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col6Width, $tcStyle->header->cell)->addText('Total Printing Cost', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col7Width, $tcStyle->header->cell)->addText('AMPV', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col8Width, $tcStyle->header->cell)->addText('Toner Cost', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col9Width, $tcStyle->header->cell)->addText('Toner Yield', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col10Width, $tcStyle->header->cell)->addText('CPP', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col11Width, $tcStyle->header->cell)->addText('Total Printing Cost', $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col11Width, $tcStyle->header->cell)->addText(sprintf('%1$ss', My_Brand::$dealerSku), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col11Width, $tcStyle->header->cell)->addText('OEM SKUs', $tcStyle->header->fontStyle, $tcStyle->centeralign);


foreach ($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances() as $deviceInstance)
{
    $dealerCostPerPageSettings = $assessmentViewModel->getCostPerPageSettingForDealer();
    $completeMonoToners        = $deviceInstance->getMasterDevice()->getHasValidMonoGrossMarginToners($assessmentViewModel->getCostPerPageSettingForDealer());
    $completeColorToners       = $deviceInstance->getMasterDevice()->getHasValidColorGrossMarginToners($assessmentViewModel->getCostPerPageSettingForDealer());
    $blackToner                = null;
    $colorToner                = null;
    $toners                    = $deviceInstance->getMasterDevice()->getCheapestTonerSetByVendor($assessmentViewModel->getCostPerPageSettingForDealer());
    $tonerSkus                 = array();
    foreach ($toners as $toner)
    {
        $dealerTonerAttribute = Proposalgen_Model_Mapper_Dealer_Toner_Attribute::getInstance()->findTonerAttributeByTonerId($toner->id, $dealerId);
        $dealerSku            = null;

        if ($dealerTonerAttribute instanceof Proposalgen_Model_Dealer_Toner_Attribute)
        {
            $dealerSku = $dealerTonerAttribute->dealerSku;
        }

        switch ($toner->tonerColorId)
        {
            case Proposalgen_Model_TonerColor::BLACK:
                $blackToner                      = $toner;
                $tonerSkus['black']['sku']       = $toner->sku;
                $tonerSkus['black']['dealerSku'] = $dealerSku;
                break;
            case Proposalgen_Model_TonerColor::CYAN:
                $colorToner                     = $toner;
                $tonerSkus['cyan']['sku']       = $toner->sku;
                $tonerSkus['cyan']['dealerSku'] = $dealerSku;
                break;
            case Proposalgen_Model_TonerColor::MAGENTA:
                $tonerSkus['magenta']['sku']       = $toner->sku;
                $tonerSkus['magenta']['dealerSku'] = $dealerSku;
                $colorToner                        = $toner;
                break;
            case Proposalgen_Model_TonerColor::YELLOW:
                $tonerSkus['yellow']['sku']       = $toner->sku;
                $tonerSkus['yellow']['dealerSku'] = $dealerSku;
                $colorToner                       = $toner;
                break;
            case Proposalgen_Model_TonerColor::THREE_COLOR:
                $tonerSkus['threeColor']['sku']       = $toner->sku;
                $tonerSkus['threeColor']['dealerSku'] = $dealerSku;
                $colorToner                           = $toner;
                break;
            case Proposalgen_Model_TonerColor::FOUR_COLOR:
                $tonerSkus['fourColor']['sku']       = $toner->sku;
                $tonerSkus['fourColor']['dealerSku'] = $dealerSku;
                $blackToner                          = $toner;
                $colorToner                          = $toner;
                break;
            default:
                break;
        }
    }

    // Black Toner
    $blackCost  = $this->currency($blackToner->cost);
    $blackYield = number_format($blackToner->yield);

    // Color Toner
    $colorCost  = "-";
    $colorStyle = "style='text-align: center;'";
    $colorYield = "-";
    $isColor    = false;
    if ($colorToner)
    {
        $colorCost  = $this->currency($colorToner->cost);
        $colorYield = number_format($colorToner->yield);
        $colorStyle = 'right';
        $isColor    = true;
    }

    // Row Colors
    $mono_toner_class  = ($completeMonoToners) ? $tcStyle->row->cell : $tcStyle->row->highlightcell;
    $color_toner_class = ($completeColorToners) ? $tcStyle->row->cell : $tcStyle->row->highlightcell;

    $table->addRow($tcStyle->rowheight->cell,$tcStyle->rowstyle);
    $column1 = $table->addCell($tcStyle->col1Width, $tcStyle->row->cell);
    $column1->addText($this->translate(str_ireplace("hewlett-packard", "HP", $deviceInstance->getDeviceName())), $tcStyle->row->fontStyle, $tcStyle->leftalign);
    $column1->addText("(" . $deviceInstance->ipAddress . " - " . $deviceInstance->serialNumber . ")", $tcStyle->row->fontStyle, $tcStyle->leftalign);

    // Mono
    $table->addCell($tcStyle->col2Width, $mono_toner_class)->addText($this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col3Width, $mono_toner_class)->addText($blackCost, $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col4Width, $mono_toner_class)->addText($blackYield, $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col5Width, $mono_toner_class)->addText($this->formatCostPerPage($deviceInstance->calculateCostPerPage($assessmentViewModel->getCostPerPageSettingForDealer())->getCostPerPage()->monochromeCostPerPage), $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col6Width, $mono_toner_class)->addText($this->formatCostPerPage($deviceInstance->getMonthlyBlackAndWhiteCost($assessmentViewModel->getCostPerPageSettingForDealer())), $tcStyle->row->fontStyle, $tcStyle->rightalign);

    // Color
    $table->addCell($tcStyle->col7Width, $color_toner_class)->addText(($isColor) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : "-", $tcStyle->row->fontStyle, ($isColor) ? $tcStyle->rightalign : $tcStyle->centeralign);
    $table->addCell($tcStyle->col8Width, $color_toner_class)->addText($colorCost, $tcStyle->row->fontStyle, (trim($colorCost) != "-") ? $tcStyle->rightalign : $tcStyle->centeralign);
    $table->addCell($tcStyle->col9Width, $color_toner_class)->addText($colorYield, $tcStyle->row->fontStyle, (trim($colorYield) != "-") ? $tcStyle->rightalign : $tcStyle->centeralign);
    $table->addCell($tcStyle->col10Width, $color_toner_class)->addText(($isColor) ? $this->formatCostPerPage($deviceInstance->calculateCostPerPage($assessmentViewModel->getCostPerPageSettingForDealer())->getCostPerPage()->colorCostPerPage) : "-", $tcStyle->row->fontStyle, ($isColor ? $tcStyle->rightalign : $tcStyle->centeralign));
    $table->addCell($tcStyle->col11Width, $color_toner_class)->addText(($isColor) ? $this->currency($deviceInstance->calculateMonthlyColorCost($assessmentViewModel->getCostPerPageSettingForDealer())) : "-", $tcStyle->row->fontStyle, ($isColor ? $tcStyle->rightalign : $tcStyle->centeralign));

    $column1 = $table->addCell($tcStyle->col1Width, $tcStyle->row->cell);
    foreach ($tonerSkus as $tonerSku)
    {
        if (isset($tonerSku['dealerSku']))
        {
            $column1->addText($tonerSku['dealerSku'], $tcStyle->row->fontStyle, $tcStyle->rightalign);
        }
        else
        {
            $column1->addText('-', $tcStyle->row->fontStyle, $tcStyle->rightalign);
        }
    }

    $column1 = $table->addCell($tcStyle->col1Width, $tcStyle->row->cell);
    foreach ($tonerSkus as $tonerSku)
    {
        $column1->addText($tonerSku['sku'], $tcStyle->row->fontStyle, $tcStyle->rightalign);
    }
}

// Table footer (totals row)
$table->addRow($tcStyle->footer->rowheight,$tcStyle->rowstyle);
$table->addCell($tcStyle->col1Width, $tcStyle->footer->cell)->addText('Totals for ' . number_format($assessmentViewModel->getDevices()->purchasedDeviceInstances->getCount()) . ' devices:', $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col2Width, $tcStyle->footer->cell)->addText($this->formatPageVolume($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getBlackPageCount()->getMonthly()), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col3Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col4Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col5Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col6Width, $tcStyle->footer->cell)->addText($this->currency($assessmentViewModel->getGrossMarginTotalMonthlyCost()->BlackAndWhite), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col7Width, $tcStyle->footer->cell)->addText($this->formatPageVolume($assessmentViewModel->getDevices()->purchasedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly()), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col8Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col9Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col10Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col11Width, $tcStyle->footer->cell)->addText($this->currency($assessmentViewModel->getGrossMarginTotalMonthlyCost()->Color), $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col10Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);
$table->addCell($tcStyle->col10Width, $tcStyle->footer->cell)->addText(null, $tcStyle->footer->fontStyle, $tcStyle->rightalign);