<?php 
/* @var $form Quotegen_Form_QuoteSetting */
$form = $this->element;

$percentageElements = array();
$percentageElements[] = $form->getElement('pageCoverageMonochrome');
$percentageElements[] = $form->getElement('pageCoverageColor');
$noDefaultsElements = array();
$noDefaultsElements[] = $form->getElement('clientDisplayName');
$noDefaultsElements[] = $form->getElement('leasingSchemaId');
$noDefaultsElements[] = $form->getElement('leasingSchemaTermId');
$noDefaultsElements[] = $form->getElement('quoteDate');
$pricingConfigId = $form->getElement('pricingConfigId');
?>
<?php $this->headScript()->captureStart(); ?>
$(function() 
{
	$('#leasingSchema').change(function()
	{
		var value = this.value;
		$('#leasingSchemaTermId').empty().attr('disabled', 'disabled');
		if (value != 0)
		{
    		$.ajax(
    		{
    		    url:'<?php echo $this->url(array('format' => 'json', 'action' => 'leasing-schema-terms')); ?>/leasingSchemaId/' + value,
    		    success: function(data) 
    		    {
    		         var terms = data['leasingSchemaTerms'];
    		         var html = '';
    		         var len = terms.length;
    		         for (var i = 0; i < len; i++)
    		         {
    		             html += '<option value="' + terms[i].id + '">' + terms[i].months + ' Months</option>';
    		         }
    		         $('#leasingSchemaTermId').append(html);
    		         $('#leasingSchemaTermId').removeAttr('disabled');
    		    },
    		    error: function (data) 
    		    {
                    alert('Error Occured!');
    		    }
    		});
		}
	});
});
<?php $this->headScript()->captureEnd(); ?>

<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">

<!-- Show all noDefaultElements -->
<?php foreach ($noDefaultsElements as $element) :?>
	<?php echo $element; ?>
<?php  endforeach?>

<!-- Show all percentElements -->

<?php foreach ($percentageElements as $element) : ?>
<div class="control-group <?php echo ($element->hasErrors()) ? 'error' : '' ?>">
	<?php echo $element->renderLabel(); ?>
	<div class="controls">
		<div class="input-append">
			<?php echo $element->renderViewHelper()?><span class="add-on"><strong>System Default: </strong><?php echo number_format($element->getDescription(), 2); ?>%</span>
		</div>
		<?php echo $element->renderErrors(); ?>
	</div>
</div>
<?php endforeach; ?>


<!-- Show all pricingConfigs choices-->
<div class="control-group <?php echo ($pricingConfigId->hasErrors()) ? 'error' : '' ?>">
	<?php echo $pricingConfigId->renderLabel()?>
	<div class="controls">
		<div class="input-append">
		<?php /* @var $princingConfig Proposalgen_Model_Mapper_PricingConfig */ $pricingConfig = Proposalgen_Model_Mapper_PricingConfig::getInstance()->find($pricingConfigId->getDescription()); ?>
			<?php echo $pricingConfigId->renderViewHelper(); ?><span class="add-on"><strong>System Default: </strong><?php echo $pricingConfig->getConfigName(); ?></span>			
		</div>
		<?php echo $element->renderErrors(); ?>
	</div>
</div>

<div class="form-actions">
	<input type="submit" name="back" value="Go Back" class="btn"/>
	<input type="submit" name="save" value="Save" class="btn btn-success"/>
	<input type="submit" name="saveAndContinue" value="Save &amp; Continue" class="btn btn-primary"/>
</div>
</form>