<?php

/* @var $form \MPSToolbox\Forms\ComputersAttributesForm */
$form = $this->element;

if (!function_exists('output_ComputersAttributesForm_col')) {
    function output_ComputersAttributesForm_col($that, $col) {
        $form = $that->element;
        $booleans = ['webcam','mediaDrive','hdDisplay'];
        $selects = ['os','usb','displayType'];
        $isBool = in_array($col,$booleans);
        $isSelect = in_array($col,$selects);
?>
        <div class="form-group <?= ($form->getElement($col)->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $that->RenderFormLabel($form->getElement($col), ['col-md-4']) ?>
            <div class="col-md-6">
                <?php
                    if ($isBool) echo $that->RenderFormBootstrapSwitch($form->getElement($col), ['js-yes-no-switch']);
                    else if ($isSelect) echo $that->RenderFormSelect($form->getElement($col));
                    else echo $that->RenderFormText($form->getElement($col));
                ?>
                <?= $that->RenderFormDescription($form->getElement($col)) ?>
                <?= $that->RenderFormElementErrors($form->getElement($col)) ?>
            </div>
        </div>

    <?php
    }
}

?>

<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>

<div class="clearfix">
    <fieldset class="col-md-12">
        <div class="row">
            <!-- -->
            <div class="col-md-4">
                <div class="form-group <?= ($form->getElement('launchDate')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                    <?= $this->RenderFormLabel($form->getElement('launchDate'), ['col-md-4']) ?>

                    <div class="col-md-6">
                        <?= $this->RenderFormDatePicker($form->getElement('launchDate'), ['js-date-picker']) ?>
                        <?= $this->RenderFormDescription($form->getElement('launchDate')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('launchDate')) ?>
                    </div>
                </div>

            </div>
            <!-- -->
            <div class="col-md-4">
            </div>
            <!-- -->
            <div class="col-md-4">
            </div>
            <!-- -->
        </div>
    </fieldset>
</div>

<?= $this->RenderFormClose($form) ?>
