<?php

use MPSToolbox\Legacy\Modules\HardwareLibrary\Forms\DeviceManagement\DeviceImageForm;

/* @var $form DeviceAttributesForm */
$form = $this->element;

$id = $form->getElement('id')->getValue();
$filename = $form->getElement('imageFile')->getValue();

$form->getElement('imageUrl')->setValue('');

?>

<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>
<div class="clearfix">
    <fieldset class="col-md-10 col-md-offset-1">
<?php if ($id) { ?>

        <div class="row">
            <div class="col-md-6">

            <table class="table" id="images-table">
                <?php foreach ($form->images as $image_id=>$url) { ?>
                    <tr>
                        <td>
                            <img src="<?= $url ?>" style="width:150px;max-height:150px">
                            <a href="javascript:;" onclick="deleteImage(<?= $image_id ?>)" style="color:red">delete</a>
                        </td>
                    </tr>
                <?php } ?>
            </table>

                </div><div class="col-md-6">
            <p>
                <label>Add from URL:</label>
                <input type="text" class="form-control" id="image-url">
                <a href="javascript:;" onclick="addImage()" class="btn btn-primary">Add</a>
            </p>
                </div>
            </div>


<script>
    function deleteImage(id) {
        $.post('/hardware-library/sku/delete-image', {baseProductId:<?= $id ?> ,id:id}, function(response) {
            if (response.error) {
                alert(response.error);
            }
            if (response.tr) {
                $('#images-table').html(response.tr);
            }
        }, 'json');
    }
    function addImage() {
        var url = $('#image-url').val();
        $.post('/hardware-library/sku/add-image', {baseProductId:<?= $id ?> ,url:url}, function(response) {
            if (response.error) {
                alert(response.error);
            } else {
                $('#image-url').val('');
            }
            if (response.tr) {
                $('#images-table').html(response.tr);
            }
        }, 'json');
    }
</script>

<?php } else { ?>
        <div class="row">
            <div class="col-md-6">
    <div class="form-group <?= ($form->getElement('imageUrl')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <?= $this->RenderFormLabel($form->getElement('imageUrl'), ['col-md-4']) ?>
        <div class="col-md-8">
            <?= $this->RenderFormText($form->getElement('imageUrl')) ?>
            <?= $this->RenderFormDescription($form->getElement('imageUrl')) ?>
            <?= $this->RenderFormElementErrors($form->getElement('imageUrl')) ?>
        </div>
    </div>
                </div>
            </div>
<?php } ?>
    </fieldset>
</div>
<?= $this->RenderFormClose($form) ?>

<script>
    $(function () {
        $('#fileupload').fileupload({
            dataType: 'json',
            done: uploadDone
        });
    });
</script>
