<?php

use MPSToolbox\Forms\SkuDistributorsForm;

/* @var $form \MPSToolbox\Forms\SkuDistributorsForm */
$form = $this->element;

if (!$form->getView()->skuId) {
    return;
}
$distributors = SkuDistributorsForm::getDistributors($form->getView()->skuId);

?>
<div class="row">
    <div class="col-md-3">
        <h5>Distributor price and availability</h5>
    </div>
    <div class="col-md-9">
        <table class="table">
            <colgroup>
                <col width="40%" />
                <col width="20%" />
                <col width="20%" />
                <col width="20%" />
            </colgroup>
            <thead>
            <tr>
                <th>Distributor</th>
                <th>Distributor SKU</th>
                <th>Price</th>
                <th>Stock</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($distributors as $line) { ?>
                <tr>
                    <td><?= $line['name'] ?></td>
                    <td><?= $line['sku'] ?></td>
                    <td><?= $line['price'] ?></td>
                    <td><?= $line['stock'] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>



