<?php

/* @var $form \MPSToolbox\Forms\SkuAttributesForm */
$form = $this->element;

$properties = $form->getProperties();
$n = ceil(count($properties)/3);

function outputField($that, $prop, $form) {
    $el = $form->getElement($prop['name']);
    if (empty($el)) {
?>
    <div class="form-group has-error has-feedback">
        Error: <?= json_encode($prop); ?>
    </div>
<?php
        return;
    }
?>
<div class="form-group <?= ($el->hasErrors()) ? 'has-error has-feedback' : '' ?>">
    <?= $that->RenderFormLabel($el, ['col-md-6']) ?>

    <div class="col-md-6">
        <?php
    switch ($prop['type']) {
        case 'multiCheckbox': echo $that->RenderFormCheckbox($el); break;
        case 'checkbox': echo $that->RenderFormBootstrapSwitch($el, ['js-yes-no-switch']); break;
        case 'select': echo $that->RenderFormSelect($el); break;
        case 'date': echo $that->RenderFormDatePicker($el, ['js-date-picker']); break;
        default: echo $that->RenderFormText($el); break;
    }
    echo $that->RenderFormDescription($el);
    echo $that->RenderFormElementErrors($el);

        ?>
    </div>
</div>
<?php
}
?>

<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>

<div class="clearfix">
    <fieldset class="col-md-12">
        <div class="row">
            <!-- -->
            <div class="col-md-4">
<?php for ($i=0;$i<$n;$i++) if (isset($properties[$i])) outputField($this, $properties[$i], $form) ?>
            </div>
            <!-- -->
            <div class="col-md-4">
<?php for ($i=$n;$i<$n+$n;$i++) if (isset($properties[$i])) outputField($this, $properties[$i], $form) ?>
            </div>
            <!-- -->
            <div class="col-md-4">
<?php for ($i=$n+$n;$i<$n+$n+$n;$i++) if (isset($properties[$i])) outputField($this, $properties[$i], $form) ?>
            </div>
            <!-- -->
        </div>
    </fieldset>
</div>

<?= $this->RenderFormClose($form) ?>
