<?php 
/*
 * import.phtml - import leasing schema from .csv
 * @author	John Sadler
 */
?>

<?php $this->headScript()->captureStart('append','text/javascript') ?>
	var grid_width = 940;
	
	$(document).ready(function() {
		tableToGrid("#results_list", {
			width:grid_width,
			height:300,
			rowNum: -1,
			shrinkToFit:false
		});
		
		$("#confirm_container").html('<p class="warning">Your import will override the existing schema values. Click "Confirm Import" to continue?</p>');
				
    });

	function do_action(action) {
		$("#message_container").html('');
	}
	
<?php $this->headScript()->captureEnd() ?>

<div class="page-header">
    <h1>Leasing Schema Management (Beta)</h1>
</div>
<div class="well">

	<form class="form-horizontal button-styled" name="import" id="import" action="" method="post" enctype="multipart/form-data">
	
		<p>Insert any instructional text here.</p>
		
	    <div id="upload_container">
	        <div>
				<span class="pull-left">
	        		Choose a <span style="color: red">.CSV</span> file to upload: 
	        		<input type="file" name="uploadedfile" id="uploadedfile" accept="application/csv, text/csv" size="60" class="upload_file" />
	        	</span>
				<span class="">
			      	<a class="btn" title="Import" onclick="javascript: do_action('upload');">
						<i class="icon-upload"></i> Upload
					</a>
				</span>
	        </div>
	    </div>
	    
	    <div class="form-actions">
			<input id="submit" class="btn btn-primary" type="submit" value="Save" name="submit">
			<input id="cancel" class="btn" type="submit" value="Cancel" name="cancel">
		</div>
						
	</form>

</div>