
<?php $this->headScript()->captureStart('append','text/javascript') ?>
	
	$(document).ready(function() {
	
	});
	
	function add_term() {
		var num_columns = $("#leasingSchemaTable").find('tr')[0].cells.length;
		var num_rows = $('#leasingSchemaTable tr').length;
		
		var new_row_html = '';
		new_row_html += '<tr id="term-'+num_rows+'">';
		for (i=0; i < num_columns; i++) {
			if (i == 0) {
				new_row_html += '<td style="text-align: center;">';
				new_row_html += '<span class="pull-left"><a class="btn btn-danger btn-mini" title="Delete Term" onclick="javascript: cancel_term('+num_rows+');" href="#"><i class="icon-remove"></i></a></span>';
				new_row_html += '<input type="text" name="term-'+num_rows+'" id="term-'+num_rows+'" class="span1" value="" />';
				new_row_html += '</td>';
			} else {
				new_row_html += '<td style="text-align: center;">';
				new_row_html += '<input type="text" name="term-'+num_rows+'-range-'+i+'" id="term-'+num_rows+'-range-'+i+'" class="span1" value="" />';
				new_row_html += '</td>';
			}
		}
		new_row_html += '</tr>';
		
		$('#leasingSchemaTable tbody:last').append(new_row_html);
	}
	
	function remove_term(id) {
	}
	
	function cancel_term(id) {
		var row = document.getElementById('term-'+id);
		row.parentElement.removeChild(row);
	}
	
	function add_range() {
		var num_columns = $("#leasingSchemaTable").find('tr')[0].cells.length;
		var num_rows = $('#leasingSchemaTable tr').length;
		
		$('#leasingSchemaTable').find('tr').each(function(i) {
			
		    if (i == 0) {
				var new_col_header = '';
				new_col_header += '<th name="col-range-'+(num_columns+1)+'" width="50px" style="text-align: center;">';
				new_col_header += '<input type="text" name="range-'+(num_columns+1)+'" id="range-'+(num_columns+1)+'" class="span1" value="" />';
				new_col_header += '<span class="pull-right"><a class="btn btn-danger btn-mini" title="Delete Range" onclick="javascript: cancel_range(\'col-range-'+(num_columns+1)+'\');" href="#"><i class="icon-remove"></i></a></span>';
				new_col_header += '</th>';
		       	$(this).append(new_col_header);  
		    }
		    else {
				var new_col_html = '';
				new_col_html += '<td name="col-range-'+(num_columns+1)+'" style="text-align: center;">';
				new_col_html += '<input type="text" name="term-'+i+'-range-'+(num_columns+1)+'" id="term-'+i+'-range-'+(num_columns+1)+'" class="span1" value="" />';
				new_col_html += '</td>';
		        $(this).append(new_col_html);
		    }
		});
				
	}
	
	function remove_range(id) {
	}
	
	function cancel_range(id) {
		$('th[name='+id+'], td[name='+id+']').remove();
	}
	
<?php $this->headScript()->captureEnd() ?>

<div class="well">

	<form name="leasingSchemas" id="leasingSchemas" class="form-horizontal" action="" method="post" enctype="application/x-www-form-urlencoded">
		<p>Click on a value to edit it.</p>
		
		<div id="lease-terms-container" style="overflow: auto; overflow-y: hidden; -ms-overflow-y: hidden;">
		  <table id="leasingSchemaTable" class="table table-striped table-bordered">
		    <thead id="leadingSchemaHeaders">
				<tr>
					<th width="" nowrap="nowrap" style="text-align: center;">Term (months) </th>
					<th width="" style="text-align: center;">$0 </th>
					<th width="" style="text-align: center;">$100 <span class="pull-right"><a class="btn btn-danger btn-mini" title="Delete Interval" onclick="javascript: delete_range(1);" href="#"><i class="icon-trash"></i></a></span> </th>
					<th width="" style="text-align: center;">$1,000 <span class="pull-right"><a class="btn btn-danger btn-mini" title="Delete Interval" onclick="javascript: delete_range(2);" href="#"><i class="icon-trash"></i></a></span> </th>
					<th width="" style="text-align: center;">$10,000+ <span class="pull-right"><a class="btn btn-danger btn-mini" title="Delete Interval" onclick="javascript: delete_range(3);" href="#"><i class="icon-trash"></i></a></span> </th>
				</tr>
		    </thead>
		    <tbody id="leasingSchemaData">
		      <!-- LOOP THROUGH TERMS AND DISPLAY ROWS -->
		      <tr id="term-1">
		        <td style="text-align: center;">
		        	<span class="pull-left"><a class="btn btn-danger btn-mini" title="Delete Term" onclick="javascript: delete_term(1);" href="#"><i class="icon-trash"></i></a></span> 12 months 
		        </td>
		        <td style="text-align: center;">
		        	<input type="text" name="term1-range1" id="term1-range1" class="span1" value="0.0990" />
		        </td>
		        <td style="text-align: center;">
	        		<input type="text" name="term1-range2" id="term1-range2" class="span1" value="0.0965" />
		        </td>
		        <td style="text-align: center;">
	        		<input type="text" name="term1-range3" id="term1-range3" class="span1" value="0.0954" />
		        </td>
		        <td style="text-align: center;">
	        		<input type="text" name="term1-range4" id="term1-range4" class="span1" value="0.0944" />
		        </td>
		      </tr>
		      <!-- END LOOP THROUGH TERMS AND DISPLAY ROWS -->
		    </tbody>
		  </table>
		</div>
		
		<div id="buttons_container">
			<span class="pull-left">
		      	<a class="btn btn-success" title="Add Term" onclick="javascript: add_term();" href="#">
					<i class="icon-plus icon-white"></i> Add Term
				</a>
		      	<a class="btn btn-success" title="Add Range" onclick="javascript: add_range();" href="#">
					<i class="icon-plus icon-white"></i> Add Range
				</a>
			</span>
			<span class="pull-right">
	      		<a class="btn btn-primary" title="Save" href="#">
					<i class="icon-ok icon-white"></i> Save
				</a>
			</span>
		</div>
		
		<div style="clear: both;"></div>
		
	</form>
	
</div>