<?php $leasingSchema = $this->leasingSchema; /* @var $leasingSchema Quotegen_Model_LeasingSchema */ ?>

<?php $this->headScript()->captureStart('append','text/javascript') ?>
	
	$(document).ready(function() {
	
	});
	
	function manage_term(mode, id) {
	}
	
	function manage_range(mode, id) {
	}
	
<?php $this->headScript()->captureEnd() ?>

<div class="well">

	<form name="leasingSchemas" id="leasingSchemas" class="form-horizontal" action="" method="post" enctype="application/x-www-form-urlencoded">
		<p>Insert any instructional text here.</p>
		
		<div id="lease-terms-container" style="overflow: auto; overflow-y: hidden; -ms-overflow-y: hidden;">
		  <table id="leasingSchemaTable" class="table table-striped table-bordered">
		    <thead id="leadingSchemaHeaders">
				<tr>
					<th width="10%" nowrap="nowrap" style="text-align: center;">Term (months) </th>
					<?php foreach ($leasingSchema->getRanges() as $range ) {
					    $rangeid = $range->getId();
					    $startRange = $range->getStartRange();
					
						if ($startRange == 0) { ?>
							<th width="10%" style="text-align: center;">$0 </th>
						<?php } else { ?>
							<th width="10%" style="text-align: center;"><?php echo $this->currency($startRange); ?> </th>
						<?php } ?>
					<?php } ?>
					<th width="10%" nowrap="nowrap" style="text-align: center;">Action</th>
				</tr>
		    </thead>
		    <tbody id="leasingSchemaData">
		      <!-- LOOP THROUGH TERMS AND DISPLAY ROWS -->
		      <?php $colcount = 1; ?>
		      <?php $rates = $leasingSchema->getRates(); ?>
		      <?php foreach ( $leasingSchema->getTerms() as $term ) {
		          $termid = $term->getId();
		          $month = $term->getMonths();
		      ?>
		      <tr id="term-<?php echo $termid; ?>">
		        <td style="text-align: center;">
		        	<?php echo $month; ?> months
		        </td>
		        <?php foreach ( $leasingSchema->getRanges() as $range ) {
		            $colcount += 1;
	            	$rangeid = $range->getId();
		        ?>
		        <td style="text-align: center;"><?php echo $rates[$termid][$rangeid]->getRate(); ?></td>
		        <?php } ?>
		        <td style="text-align: center;">
			      	<a class="btn btn-warning btn-mini" title="Edit Term" onclick="javascript: manage_term('edit', <?php echo $termid; ?>);">
						<i class="icon-pencil icon-white"></i> Edit
					</a>
			      	<a class="btn btn-danger btn-mini" title="Delete Term" onclick="javascript: manage_term('delete', <?php echo $termid; ?>);">
						<i class="icon-trash icon-white"></i>
					</a>
		        </td>
		      </tr>
		      <?php } ?>
		      <!-- END LOOP THROUGH TERMS AND DISPLAY ROWS -->
		      <tr>
		      	<td>&nbsp;</td>
				<?php foreach ($leasingSchema->getRanges() as $range ) { 
					$rangeid = $range->getId();
					$startRange = $range->getStartRange();

					if ($startRange == 0) { ?>
		      			<td>&nbsp;</td>
					<?php } else { ?>
				        <td style="text-align: center;">
					      	<a class="btn btn-warning btn-mini" title="Edit Range" onclick="javascript: manage_range('edit', <?php echo $rangeid; ?>);">
								<i class="icon-pencil icon-white"></i> Edit
							</a>
					      	<a class="btn btn-danger btn-mini" title="Delete Range" onclick="javascript: manage_range('delete', <?php echo $rangeid; ?>);">
								<i class="icon-trash icon-white"></i>
							</a>
				        </td>
					<?php } ?>
		        <?php } ?>
		      	<td>&nbsp;</td>
		      </tr>
		    </tbody>
		  </table>
		</div>
		
		<div id="buttons_container">
			<span class="pull-right">
		      	<a class="btn btn-success" title="Add Term" onclick="javascript: manage_term('add', 0);" href="#">
					<i class="icon-plus icon-white"></i> Add Term
				</a>
		      	<a class="btn btn-success" title="Add Range" onclick="javascript: manage_range('add', 0);" href="#">
					<i class="icon-plus icon-white"></i> Add Range
				</a>
			</span>
		</div>
		
		<div style="clear: both;"></div>
		
	</form>
	
</div>