<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Forms\AddFavoriteDeviceForm;

/* @var $form AddFavoriteDeviceForm */
$form = $this->element;
?>

<?= $this->RenderFormOpen($form) ?>
<fieldset>
    <div class="form-group <?= ($form->getElement('deviceConfigurationId')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
        <div class="input-group input-group-sm">
            <?= $this->RenderFormSelect($form->getElement('deviceConfigurationId')) ?>
            <span class="input-group-btn"><?= $this->RenderFormSubmit($form->getElement('addDeviceConfiguration'), array('btn btn-success')) ?></span>
        </div>
        <?= $this->RenderFormElementErrors($form->getElement('deviceConfigurationId')) ?>
    </div>
</fieldset>

<?= $this->RenderFormClose($form) ?>

