
<div class="container solution" id="htmlReportContainer">
    <?php echo $this->render('report/solution/html/01_Title.phtml'); ?>
    <?php echo $this->render('report/solution/html/02_Description.phtml'); ?>
    <?php echo $this->render('report/solution/html/03_PrintIQ.phtml'); ?>
    <?php echo $this->render('report/solution/html/04_Assumptions.phtml'); ?>
    <?php echo $this->render('report/solution/html/05_Summary.phtml'); ?>
</div>