<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
?>
<div class="titlepage">
    <div class="header">
        <div class="title-page-logo-box-wrapper">
            <div class="title-page-logo-box">
                <img class="title-page-logo" src="<?= $this->serverUrl($this->dealerLogoFile) ?>" />
            </div>
        </div>
    </div>
    <div class="title-page-report-title">
        <h2>Solution</h2>
    </div>
    <div class="title-page-customer-details">
        <h3>Prepared for:
            <?php if (strlen($assessmentViewModel->assessment->getClient()->companyName) > 26) : ?>
                <br>
            <?php endif; ?>
            <?= $assessmentViewModel->assessment->getClient()->companyName; ?>
        </h3>

        <p><?= nl2br($assessmentViewModel->assessment->getClient()->getAddress()); ?></p>
        <br>
        <p>Date: <?= $assessmentViewModel->getDateReportPrepared(); ?></p>
    </div>
</div>