<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$this->brandName = My_Brand::getDealerBranding()->mpsProgramName;
$this->companyName = My_Brand::getDealerBranding()->shortDealerName;
?>
<div class="h1">Let <?= $this->companyName; ?> Take Care of Your Business Print</div>
<p>With <?= $this->companyName; ?> as your single point of contact for your office printing needs, your business will be taken
    care of.</p>

<div class="pheader" style="margin: 10pt 0pt;">Just-in-Time Supplies</div>
<p><?= $this->companyName; ?> monitors your supplies levels and ships toner immediately through our world class logistics and distribution network. This
    allows you to reduce
    the amount of cash held in supplies inventory, and increase uptime by always having the right supplies when you need them. Remember, sourcing and delivering
    supplies
    is our core business.</p>

<div class="pheader" style="margin: 10pt 0pt;">Proactive Maintenance and Service</div>
<p><?= $this->companyName; ?> provides same-day support for service and printer maintenance, and under the <?= $this->brandName; ?>, all
    of your parts and labor are included (maintenance kits, fusers, etc.).
    We provide next-day repair for all printing devices under your managed print services contract so your IT staff will be free from handling printer-related
    issues.</p>

<div class="pheader" style="margin: 10pt 0pt;">Cost Control and Business Intelligence Reporting</div>
<p>Under the <?= $this->brandName; ?>
    <?php if ($this->App()->theme == 'printiq'): ?> and <?= $this->brandname; ?> Plus programs<?php endif; ?>
    , you'll have a single contact and receive one monthly invoice for all of your managed print services. Now you can easily predict and budget for your printing expenses.</p>

<div class="pheader" style="margin: 10pt 0pt;">Eco Smart Solutions</div>
<p><?php if ($this->App()->theme == 'printiq'): ?>
        <?= $this->companyName; ?> was recognized by Newsweek as the No. 1 Green Retailer. Our eco-preferable initiatives
        include recycling programs for supplies and equipment, and product lines of refurbished printers and
        remanufactured supplies.
    <?php endif; ?> Through our managed print services program, we can help you determine
    which inefficient devices should be removed and if duplex, scanning and secure-print features should be
    implemented to reduce paper waste.</p>

<?php if ($this->App()->theme == 'printiq'): ?>
    <div class="pheader" style="margin: 10pt 0pt;">Your Total Print Solution</div>
    <p>With <?= $this->companyName; ?>, you get more than managed print services. Leverage our Copy & Print Depot locations for large or multiple print jobs.
        E-mail files to Copy & Print Depot for
        same-day pickup, delivery, or to ship to multiple locations. Use our digital file cabinet to store files on our secure server for staff or customers to
        access and print on demand.
        We also offer commercial printing, large format printing, banner printing, custom printing, and have a variety of finishing capabilities for all of your
        office printing needs.</p>
<?php endif; ?>

<div class="pheader" style="margin: 10pt 0pt;">Flexible Options</div>
<p>From day-to-day management of your office print to leveraging your existing assets or choosing to obtain new hardware on a flat-rate
    program, <?= $this->companyName; ?> provides a variety of options that enable
    you to maintain your flexibility as your needs change.</p>

<div class="h1">Next Steps</div>
<p>We recommend the following implementation plan for your managed print services program:</p>

<br />

<table class="genericTable" style="width: 100%;" width="530">
    <tbody>
    <tr>
        <td class="bold verticalTop">Today:</td>
        <td>
            <ul>
                <li>Remote monitoring software is already installed.</li>
                <li>Select a department or floor for initial migration to managed print services.</li>
            </ul>
        </td>
    </tr>
    <tr>
        <td class="bold verticalTop">Within 30 days:</td>
        <td>
            <ul>
                <li>Migrate the selected department or floor to managed print services.</li>
            </ul>
        </td>
    </tr>
    <tr>
        <td class="bold verticalTop">Within 90 days:</td>
        <td>
            <ul>
                <li>Migrate all other desired locations to managed print services.</li>
            </ul>
        </td>
    </tr>
    <tr>
        <td class="bold verticalTop">Every six months:</td>
        <td>
            <ul>
                <li>Evaluation and adjustment of recommendations as needed.</li>
            </ul>
        </td>
    </tr>
    </tbody>
</table>

<br />

<p>Whether you are looking for a comprehensive managed print services plan that includes new equipment,
    or are looking for assistance in maintaining your existing printer fleet, we can design a solution that meets
    your specific business needs.</p>

<p>Let us take care of your print so you can get back to business.</p>
<p id="copyright">&copy; 2011 <?= $this->companyName; ?>, Inc. All Rights Reserved. <br />
    The <?= $this->companyName; ?> name and logo are the registered trademarks of The Office Club, Inc.</p>
