<div class="container">
    <div class="col-sm-6">
    <form method="post">
        <div class="form-group">
            <label>Category Parent:</label>
            <select name="parent" class="form-control">
                <option></option>
<?php foreach ($this->base_category as $line) if (empty($line['parent'])) echo '<option value="'.$line['id'].'">'.$line['name'].'</option>'; ?>
            </select>
        </div>
        <div class="form-group">
            <label>Category Name:</label>
            <input type="text" name="name" class="form-control" required="required">
        </div>
        <div class="form-group">
            <a href="/admin/categories">Cancel</a>
            &nbsp;&nbsp;&nbsp;
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
    </form>
    </div>
</div>