<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
$customerOptimization = new Proposalgen_Model_Optimization_Customer($proposal);
$graphs = $customerOptimization->getGraphs();
?>

<img src="<?php echo $graphs[0]; ?>" />
<img src="<?php echo $graphs[1]; ?>" />
<br/><br/>
<img src="<?php echo $graphs[2]; ?>" />
<img src="<?php echo $graphs[3]; ?>" />
<br/><br/>
<img src="<?php echo $graphs[4]; ?>" />
<br/><br/>
<img src="<?php echo $graphs[5]; ?>" />
<img src="<?php echo $graphs[6]; ?>" />
<br/><br/>
<img src="<?php echo $graphs[7]; ?>" />
<img src="<?php echo $graphs[8]; ?>" />
<br/><br/>
<img src="<?php echo $graphs[9]; ?>" />
<img src="<?php echo $graphs[10]; ?>" />
<br/><br/>
<h3>Placeholder </h3>
<br/>
<img src="<?php echo $graphs[11]; ?>" />
<br/>
<br/>
<img src="<?php echo $graphs[12]; ?>" />
