<?php
/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;

/**
 * Styles
 */
$titlePageBackgroundColor  = My_Brand::getDealerBranding()->titlePageTitleBackgroundColor;
$titlePageBackgroundColor2 = My_Brand::getDealerBranding()->titlePageInformationBackgroundColor;
$titlePageTextColor        = My_Brand::getDealerBranding()->titlePageTitleFontColor;
$titlePageTextColor2       = My_Brand::getDealerBranding()->titlePageInformationFontColor;
$h1Color                   = My_Brand::getDealerBranding()->h1FontColor;
$h1Background              = My_Brand::getDealerBranding()->h1BackgroundColor;
$h2Background              = My_Brand::getDealerBranding()->h2BackgroundColor;
$h2Color                   = My_Brand::getDealerBranding()->h2FontColor;
$h3Color                   = My_Brand::getDealerBranding()->h1FontColor;

/**
 * Document Properties
 */
$properties = $phpWord->getDocumentProperties();
$properties->setCreator('MPS Assessment Software');
$properties->setCompany('MPS Assessment Software');
$properties->setTitle(My_Brand::getDealerBranding()->healthCheckTitle);
$properties->setCategory('Dealer Report');
$properties->setLastModifiedBy('MPS Assessment Software');
$properties->setCreated(time());
$properties->setModified(time());
$properties->setSubject('MPS Assessment Software');
$pageWidth        = 9428;
$titlePageSection = $phpWord->addSection([
    'orientation'  => null,
    'marginLeft'   => 1420,
    'marginRight'  => 1420,
    'marginTop'    => 1420,
    'marginBottom' => 1420
]);
$section          = $phpWord->addSection();

/**
 * Paragraph styles
 */
// Title page
$this->phpword->addParagraphStyle('titleStyle1', [
    'align'      => 'center',
    'spaceAfter' => 100,
    'shading'    => [
        'fill' => $titlePageBackgroundColor,
    ]
]);
$this->phpword->addParagraphStyle('titleStyle2', [
    'spaceAfter'  => 50,
    'spaceBefore' => 50,
    'bgColor'     => $titlePageBackgroundColor2
]);
$this->phpword->addParagraphStyle('titleStyle3', [
    'spaceAfter' => 100,
    'tabs'       => [
        new \PhpOffice\PhpWord\Style\Tab('left', 350)],
    'shading'    => [
        'fill' => $titlePageBackgroundColor2,
    ]
]);
$this->phpword->addFontStyle('titlepage_title', [
    'size'  => 24,
    'bold'  => true,
    'color' => $titlePageTextColor
]);

$this->phpword->addFontStyle('titlepage_subtitle', [
    'size'  => 16,
    'bold'  => true,
    'color' => $titlePageTextColor
]);

$this->phpword->addFontStyle('titlepage_address', [
    'size'  => 12,
    'color' => $titlePageTextColor
]);

$phpWord->addFontStyle('small_cell_heading', [
    'size' => 8.5,
    'bold' => true
]);

$phpWord->addParagraphStyle('titlepageHeaderParagraph', [
    'spaceAfter' => 200
]);
$phpWord->addParagraphStyle('titlepageHeader1', [
    'spaceAfter' => 0,

]);

$phpWord->addParagraphStyle('nospacing', [
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpWord->addParagraphStyle('nospacing_rightalign', [
    'align'       => 'right',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpWord->addParagraphStyle('nospacing_centeralign', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpWord->addParagraphStyle('rightalign', [
    'align' => 'right'
]);

$phpWord->addParagraphStyle('gradeParagraph', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpWord->addParagraphStyle('savingsParagraph', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

/**
 * Font Styles
 */
$phpWord->addFontStyle('titlepageHeaderFont', [
    'bold' => true,
    'size' => 16
]);
$phpWord->addFontStyle('titlepageHeaderFont1', [
    'bold'  => true,
    'size'  => 16,
    'color' => 'FFFFFF'
]);

$phpWord->addFontStyle('bold_text', [
    'bold' => true
]);
$phpWord->addFontStyle('text_align_right', [
    'textalign' => 'right'
]);

$phpWord->addFontStyle('bold_highlight_text', [
    'bold'  => true,
    'color' => $h3Color
]);

$phpWord->addFontStyle('gradeFont', [
    'bold' => true,
    'size' => 18
]);

$phpWord->addFontStyle('gradeTitleFont', [
    'bold' => true,
    'size' => 12
]);

$phpWord->addFontStyle('savingsFont', [
    'bold' => true,
    'size' => 11
]);
$phpWord->addFontStyle('forestWaterFont', [
    'bold'      => true,
    'size'      => 14,
    'textalign' => 'center'
]);

$phpWord->addFontStyle('savingsAmountFont', [
    'color' => $h3Color,
    'bold'  => true,
    'size'  => 11
]);

$phpWord->addFontStyle('small_italic_text', [
    'italic' => true,
    'size'   => 9
]);

/**
 * Header/Title Styles
 * TODO: fix color settings - wasn't recognizing variables-didn't show up in doc
 */
// H1 Style
$phpWord->addTitleStyle(1, [
    'size'  => 15,
    'color' => $h1Color,
    'bold'  => true
], [
    'shading' => [
        'fill' => $h1Background,
    ],
]);
// H2 Style #5881BC
$phpWord->addTitleStyle(2, [
    'size'   => 12,
    'color'  => $h2Color,
    'bold'   => true,
    'italic' => true
], [
    'shading' => [
        'fill' => $h2Background,
    ]
]);
// H3 Style #5881BC
$phpWord->addTitleStyle(3, [
    'size'  => 10,
    'color' => $h3Color,
    'bold'  => true
], [
    'spaceBefore' => 100,
    'spaceAfter'  => 100
]);

// H3 Style #5881BC
$phpWord->addFontStyle('heading3', [
    'size'  => 10,
    'color' => $h3Color,
    'bold'  => true
]);

$shaded_color = "EFEFEF";
/**
 * Setup some styles to be used across the report
 */
$styles = (object)[
    "tables" => (object)[
        "grades"              => (object)[
            "tablestyle" => [
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ],
            "cell1"      => [
                "bgColor"          => "F0F0F0",
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1
            ],
            "cell2"      => [
                "bgColor"          => "F0F0F0",
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ]
        ],
        "singleimage"         => (object)[
            "tablestyle" => [],
            "cell1"      => [
                "valign" => "center"
            ]
        ],
        "doubleimage"         => (object)[
            "tablestyle" => [],
            "cell1"      => [
                "valign" => "center"
            ],
            "cell2"      => [
                "valign" => "center"
            ]
        ],
        "tripleimage"         => (object)[
            "tablestyle" => [],
            "cell1"      => [
                "valign" => "center",
                'align'  => "center"
            ],
            "cell2"      => [
                "valign" => "center",
                'align'  => "center"
            ],
            "cell3"      => [
                "valign" => "center",
                'align'  => "center"
            ]
        ],
        "savings"             => (object)[
            "tablestyle" => [
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ],
            "cell1"      => [
                "bgColor"          => "F0F0F0",
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ]
        ],
        "uniqueDevices"       => (object)[
            "tablestyle" => [
                'cellMarginTop'     => 30,
                'cellMarginRight'   => 30,
                'cellMarginBottom'  => 30,
                'cellMarginLeft'    => 30,
                'borderBottomSize'  => 10,
                'borderBottomColor' => 'black',
            ],
            "rowheight"  => 200,
            "firstCell"  => [
                "borderTopSize"    => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "middleCell" => [
                "borderTopSize"    => 1,
                "borderBottomSize" => 1,
                "valign"           => "center"
            ],
            "lastCell"   => [
                "borderTopSize"    => 1,
                "borderBottomSize" => 1,
                "borderRightSize"  => 1,
                "valign"           => "center"
            ]],
        "utilization"         => (object)[
            "tablestyle" => [
                'cellMarginTop'     => 100,
                'cellMarginRight'   => 100,
                'cellMarginBottom'  => 100,
                'cellMarginLeft'    => 100,
                'borderBottomSize'  => 10,
                'borderBottomColor' => 'black',
            ],
            "rowheight"  => 400,
            "cellHeader" => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center",
                "bgColor"          => "F0F0F0",
            ],
            "cell1"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell2"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell3"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell4"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ]
        ],
        "highriskdevices"     => (object)[
            "tablestyle" => [
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ],
            "rowheight"  => 400,
            "cell1"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell2"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell3"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell4"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell5"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell6"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ]
        ],
        "highenergy"          => (object)[
            "tablestyle" => [
                'cellMarginTop'     => 100,
                'cellMarginRight'   => 100,
                'cellMarginBottom'  => 100,
                'cellMarginLeft'    => 100,
                'borderBottomSize'  => 10,
                'borderBottomColor' => '#000000'
            ],
            "rowheight"  => 400,
            "cell1"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell2"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell3"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell4"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ]
        ],
        "twoColumnDataTable"  => (object)[
            "tablestyle" => [
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ],
            "rowheight"  => null,
            "cell1"      => [
                "valign" => "center"
            ],
            "cell2"      => [
                "valign" => "center"
            ]
        ],
        "expenseSummaryTable" => (object)[
            "tablestyle"  => [
                'cellMarginTop'    => 50,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 50,
                'cellMarginLeft'   => 100
            ],
            "rowheight"   => null,
            "col1Width"   => 7500,
            "col2Width"   => 1528,
            "cell1"       => [
                "valign" => "center"
            ],
            "cell2"       => [
                "valign" => "center"
            ],
            "cell1Border" => [
                "valign"           => "center",
                'borderBottomSize' => 1
            ],
            "cell2Border" => [
                "valign"           => "center",
                'borderBottomSize' => 1
            ]
        ],
        "mostexpensive"       => (object)[
            "tablestyle" => [
                'cellMarginTop'     => 100,
                'cellMarginRight'   => 100,
                'cellMarginBottom'  => 100,
                'cellMarginLeft'    => 100,
                'borderBottomSize'  => 10,
                'borderBottomColor' => 'black',
            ],
            "rowheight"  => 400,
            "col1Width"  => 3611.2,
            "col2Width"  => 1805.6,
            "col3Width"  => 1805.6,
            "col4Width"  => 1805.6,
            "cell1"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell2"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell3"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell4"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
        ],
        "estimatedTonerCosts" => (object)[
            "tablestyle" => [
                'cellMarginTop'    => 100,
                'cellMarginRight'  => 100,
                'cellMarginBottom' => 100,
                'cellMarginLeft'   => 100
            ],
            "rowheight"  => 400,
            "cell1"      => [
                "valign" => "center"
            ],
            "cell2"      => [
                "valign" => "center"
            ],
            "cell3"      => [
                "valign" => "center",
            ],
            "cell4"      => [
                "valign"  => "center",
                "bgColor" => $shaded_color
            ],
            "cell5"      => [
                "valign" => "center"
            ],
            "cell6"      => [
                "valign"  => "center",
                "bgColor" => $shaded_color
            ]
        ],
        "twoColumnHeader"     => (object)[
            "tablestyle" => [
                'cellMarginRight' => 50,
                'cellMarginLeft'  => 50
            ],
            'cell1Width' => $pageWidth / 2,
            //            'cell1Width' => 4514,
            'cell2Width' => $pageWidth / 2,
            'rowheight'  => 200,
            'cell1'      => (object)[
                'fontStyle'      => [
                    'size'   => 12,
                    'color'  => $h2Color,
                    'bold'   => true,
                    'italic' => true
                ],
                'paragraphStyle' => [
                    'align'      => 'left',
                    'spaceAfter' => 0
                ],
                'cellStyle'      => [
                    'bgColor' => $h2Background
                ]

            ],
            'cell2'      => (object)[
                'fontStyle'      => [
                    'size'   => 12,
                    'color'  => $h2Color,
                    'bold'   => true,
                    'italic' => true
                ],
                'paragraphStyle' => [
                    'align'      => 'right',
                    'spaceAfter' => 0
                ],
                'cellStyle'      => [
                    'bgColor' => $h2Background
                ]
            ],

        ],
        "fleetattributes"     => (object)[
            "tablestyle"      => [
                'cellMarginTop'    => 50,
                'cellMarginRight'  => 50,
                'cellMarginBottom' => 50,
                'cellMarginLeft'   => 50,
                'borderBottomSize' => 1,
            ],
            "rowheader"       => [
                'tblHeader' => true,
                'cantSplit' => true,
            ],
            "rowstyle"        => [
                "cantSplit" => true,
            ],
            "rowheight"       => 100,
            "cellHeader"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center",
                "bgColor"          => "F0F0F0",
            ],
            "cell1"           => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell2"           => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center",
            ],
            "cell3"           => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cell4"           => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center"
            ],
            "cellshaded"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center",
                "bgColor"          => "F0F0F0"
            ],

            "cellshadedright" => (object)[
                'fontStyle'      => [
                    'size'   => 12,
                    'color'  => 'FFFFFF',
                    'bold'   => true,
                    'italic' => true
                ],
                'paragraphStyle' => [
                    'align'      => 'right',
                    'spaceAfter' => 0
                ],
                'cellStyle'      => [
                    'bgColor' => 'F0F0F0'
                ]
            ],

            "cellshadedleft"  => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => "center",
                "align"            => "left",
                "bgColor"          => "F0F0F0"
            ]

        ],
        'assumptions'         => (object)[
            "tablestyle"  => [
                'cellMarginTop'    => 50,
                'cellMarginRight'  => 50,
                'cellMarginBottom' => 50,
                'cellMarginLeft'   => 50
            ],
            "leftalign"   => "nospacing",
            "centeralign" => "nospacing_centeralign",
            "rightalign"  => "nospacing_rightalign",
            "col1Width"   => 9000,
            "col2Width"   => 2400,
            "header"      => (object)[
                "rowheight" => null,
                "fontStyle" => "table_header",
                "cell"      => [
                    "borderTopSize"   => 1,
                    "borderRightSize" => 1,
                    "borderLeftSize"  => 1,
                    "bgColor"         => "F0F0F0",
                    "valign"          => "center"
                ],
            ],
            "row"         => (object)[
                "rowheight" => null,
                "fontStyle" => 'table_body',
                "cell"      => [
                    "borderTopSize"    => 1,
                    "borderRightSize"  => 1,
                    "borderBottomSize" => 1,
                    "borderLeftSize"   => 1,
                    "valign"           => "center"
                ],
            ],
            "footer"      => (object)[
                "rowheight" => null,
                "fontStyle" => 'table_footer',
                "cell"      => [
                    "borderTopSize"    => 1,
                    "borderRightSize"  => 1,
                    "borderBottomSize" => 1,
                    "borderLeftSize"   => 1,
                    "valign"           => "center"
                ]
            ]
        ]
    ],
];


$titledata = [
    "phpword"              => $phpWord,
    "section"              => $titlePageSection,
    "healthcheckViewModel" => $this->healthcheckViewModel,
    "styles"               => $styles,
    "dealerLogoFile"       => $this->dealerLogoFile,
];

$data = [
    "phpword"              => $phpWord,
    "section"              => $section,
    "healthcheckViewModel" => $healthcheckViewModel,
    "styles"               => $styles,
    "brandName"            => My_Brand::getDealerBranding()->mpsProgramName,
    "companyName"          => My_Brand::getDealerBranding()->shortDealerName,
    "jit"                  => My_Brand::$jit,
    "jitName"              => My_Brand::getDealerBranding()->shortJitProgramName,
    "jitFullName"          => My_Brand::getDealerBranding()->jitProgramName
];

// Actual document pages
$this->partial("report/healthcheck/docx/title-page.phtml", $titledata);
$this->partial("report/healthcheck/docx/score-card.phtml", $data);
$this->partial("report/healthcheck/docx/service-and-supplies-logistics.phtml", $data);
$this->partial("report/healthcheck/docx/oem-vs-compatible.phtml", $data);
$this->partial("report/healthcheck/docx/printing-hardware-usage.phtml", $data);
$this->partial("report/healthcheck/docx/technology-reliability-and-user-productivity.phtml", $data);
$this->partial("report/healthcheck/docx/environmental-impact.phtml", $data);

/**
 * Only show the fleet attributes page if we have less than 200 devices in the fleet.
 */
if ($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount() < 100)
{
    $this->partial('report/healthcheck/docx/fleet-attributes.phtml', $data);
}

$this->partial("report/healthcheck/docx/summary-page.phtml", $data);

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save($this->savePath);

if (Zend_Controller_Front::getInstance()->getRequest()->isXmlHttpRequest()) echo $this->baseUrl($this->publicFileName);
else header('Location: '.$this->baseUrl($this->publicFileName));

