<?php
/** Healthcheck - Report Card */

/* @var $phpword \PhpOffice\PhpWord\PhpWord */
$phpword = $this->phpword;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;

$section->addTitle(sprintf('Your %1$s', My_Brand::getDealerBranding()->healthCheckTitle), 1);

$section->addText(sprintf('Does your fleet of printing hardware deliver your users and business the greatest return on investment? How many trees and how much water is consumed by the paper you use every year? This free %1$s will break down your current fleet and show you how you can lower your supply costs, which devices are printing too much and which devices are printing too little, and the environmental impact of your fleet.', My_Brand::getDealerBranding()->healthCheckTitle));
$section->addText("Data used in this review is collected by the remote monitoring software installed on site.");