<?php
/**
 * Healthcheck - Analysis: Expense
 */
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;

/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $phpWord->addSection([
    'orientation'  => null,
    'marginLeft'   => 720,
    'marginRight'  => 720,
    'marginTop'    => 720,
    'marginBottom' => 720,
]);

/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs = $this->graphs;

$section->addTitle("Fleet Attributes", 1);

$section->addText("The following provides a summary of your existing printing devices.");
$section->addText("Leased devices are shown in gray.", 'small_italic_text');

$cellWidths = [
    4500,
    1500,
    1500,
    1500,
    1500,
    1500,
    1500,
    1500,
    1500,
    1500,
    1500,
    1500,
    1500,
];
$tcStyle    = $this->styles->tables->fleetattributes;
/**
 * Optimized Devices
 * TODO: fix column widths - same as underutilized, but formats differently
 */
$section->addTitle("Optimized Devices - No Changes Necessary", 2);

$optimizedDevicesTable = $section->addTable($tcStyle->tablestyle);
$optimizedDevicesTable->addRow($tcStyle->rowheight, $tcStyle->rowheader);
$optimizedDevicesTable->addCell($cellWidths [0], $tcStyle->cellHeader)->addText('Device Name', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [1], $tcStyle->cellHeader)->addText('Device Age (Years)', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [2], $tcStyle->cellHeader)->addText('Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [3], $tcStyle->cellHeader)->addText('Percent of Fleet\'s Total Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [4], $tcStyle->cellHeader)->addText('Suggested Max. Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [5], $tcStyle->cellHeader)->addText('Life Page Count', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [6], $tcStyle->cellHeader)->addText('A3', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [7], $tcStyle->cellHeader)->addText('Color', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [8], $tcStyle->cellHeader)->addText('Duplex', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [9], $tcStyle->cellHeader)->addText('MFP', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [10], $tcStyle->cellHeader)->addText('Fax', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [11], $tcStyle->cellHeader)->addText('Reports Toner Levels', 'small_cell_heading', 'nospacing_centeralign');
$optimizedDevicesTable->addCell($cellWidths [12], $tcStyle->cellHeader)->addText(sprintf('Linked to %1$s Program', $this->jit), 'small_cell_heading', 'nospacing_centeralign');
foreach ($healthcheckViewModel->getOptimizedDevices() as $device)
{
    $deviceName = str_replace("Hewlett-Packard", "HP", $device->getDeviceName());

    $optimizedDevicesTable->addRow(null, $tcStyle->rowstyle);
    $cell = $optimizedDevicesTable->addCell($cellWidths [0], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell1));
    $cell->addText($deviceName, null, ['spaceAfter' => 0]);
    $cell->addText($device->serialNumber, null, ['spaceAfter' => 0]);
    $cell->addText($device->ipAddress, null, ['spaceAfter' => 0]);
    $optimizedDevicesTable->addCell($cellWidths [1], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText(number_format($device->getAge(), 0), null, 'nospacing_rightalign');
    $optimizedDevicesTable->addCell($cellWidths [2], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell3))->addText($this->formatPageVolume($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_rightalign');
    $optimizedDevicesTable->addCell($cellWidths [3], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($this->translate(number_format($device->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) . '%'), null, 'nospacing_rightalign');
    $optimizedDevicesTable->addCell($cellWidths [4], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->formatPageVolume($device->getMasterDevice()->calculateEstimatedMaxLifeCount()), null, 'nospacing_rightalign');
    $optimizedDevicesTable->addCell($cellWidths [5], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->formatPageVolume($device->getMeter()->endMeterLife), null, 'nospacing_rightalign');
    $optimizedDevicesTable->addCell($cellWidths [6], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isA3 ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $optimizedDevicesTable->addCell($cellWidths [7], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isColor() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $optimizedDevicesTable->addCell($cellWidths [8], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isDuplex ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $optimizedDevicesTable->addCell($cellWidths [9], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isMfp() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $optimizedDevicesTable->addCell($cellWidths [10], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isFax ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $optimizedDevicesTable->addCell($cellWidths [11], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isCapableOfReportingTonerLevels() ? 'Yes' : 'No')), null, 'nospacing_centeralign');
    $optimizedDevicesTable->addCell($cellWidths [12], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isLeased ? 'No' : ($device->isManaged ? 'Yes' : 'No'))), null, 'nospacing_centeralign');
}
$section->addPageBreak();


/**
 * Underutilized Devices
 */
$section->addTitle("Underutilized Devices", 2);

$UnderutilizedDevicesTable = $section->addTable($tcStyle->tablestyle);
$UnderutilizedDevicesTable->addRow($tcStyle->rowheight, $tcStyle->rowheader);
$UnderutilizedDevicesTable->addCell($cellWidths [0], $tcStyle->cellHeader)->addText('Device Name', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [1], $tcStyle->cellHeader)->addText('Device Age (Years)', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [2], $tcStyle->cellHeader)->addText('Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [3], $tcStyle->cellHeader)->addText('Percent of Fleet\'s Total Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [4], $tcStyle->cellHeader)->addText('Suggested Max. Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [5], $tcStyle->cellHeader)->addText('Life Page Count', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [6], $tcStyle->cellHeader)->addText('A3', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [7], $tcStyle->cellHeader)->addText('Color', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [8], $tcStyle->cellHeader)->addText('Duplex', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [9], $tcStyle->cellHeader)->addText('MFP', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [10], $tcStyle->cellHeader)->addText('Fax', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [11], $tcStyle->cellHeader)->addText('Reports Toner Levels', 'small_cell_heading', 'nospacing_centeralign');
$UnderutilizedDevicesTable->addCell($cellWidths [12], $tcStyle->cellHeader)->addText(sprintf('Linked to %1$s Program', $this->jit), 'small_cell_heading', 'nospacing_centeralign');
foreach ($healthcheckViewModel->getUnderutilizedDevices() as $device)
{
    $deviceName = str_replace("Hewlett-Packard", "HP", $device->getDeviceName());

    $UnderutilizedDevicesTable->addRow(null, $tcStyle->rowstyle);
    $cell = $UnderutilizedDevicesTable->addCell($cellWidths [0], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell1));
    $cell->addText($deviceName, null, ['spaceAfter' => 0]);
    $cell->addText($device->serialNumber, null, ['spaceAfter' => 0]);
    $cell->addText($device->ipAddress, null, ['spaceAfter' => 0]);
    $UnderutilizedDevicesTable->addCell($cellWidths [1], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText(number_format($device->getAge(), 0), null, 'nospacing_rightalign');
    $UnderutilizedDevicesTable->addCell($cellWidths [2], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell3))->addText($this->formatPageVolume($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_rightalign');
    $UnderutilizedDevicesTable->addCell($cellWidths [3], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($this->translate(number_format($device->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) . '%'), null, 'nospacing_rightalign');
    $UnderutilizedDevicesTable->addCell($cellWidths [4], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText(number_format($device->getMasterDevice()->calculateEstimatedMaxLifeCount()), null, 'nospacing_rightalign');
    $UnderutilizedDevicesTable->addCell($cellWidths [5], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText(number_format($device->getMeter()->endMeterLife), null, 'nospacing_rightalign');
    $UnderutilizedDevicesTable->addCell($cellWidths [6], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isA3 ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $UnderutilizedDevicesTable->addCell($cellWidths [7], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isColor() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $UnderutilizedDevicesTable->addCell($cellWidths [8], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isDuplex ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $UnderutilizedDevicesTable->addCell($cellWidths [9], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isMfp() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $UnderutilizedDevicesTable->addCell($cellWidths [10], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isFax ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $UnderutilizedDevicesTable->addCell($cellWidths [11], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isCapableOfReportingTonerLevels() ? 'Yes' : 'No')), null, 'nospacing_centeralign');
    $UnderutilizedDevicesTable->addCell($cellWidths [12], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isLeased ? 'No' : ($device->isManaged ? 'Yes' : 'No'))), null, 'nospacing_centeralign');
}
$section->addPageBreak();

/**
 * Overutilized Devices
 */
$section->addTitle("Overutilized Devices", 2);

$OverutilizedDevicesTable = $section->addTable($tcStyle->tablestyle);
$OverutilizedDevicesTable->addRow($tcStyle->rowheight, $tcStyle->rowheader);
$OverutilizedDevicesTable->addCell($cellWidths [0], $tcStyle->cellHeader)->addText('Device Name', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [1], $tcStyle->cellHeader)->addText('Device Age (Years)', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [2], $tcStyle->cellHeader)->addText('Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [3], $tcStyle->cellHeader)->addText('Percent of Fleet\'s Total Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [4], $tcStyle->cellHeader)->addText('Suggested Max. Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [5], $tcStyle->cellHeader)->addText('Life Page Count', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [6], $tcStyle->cellHeader)->addText('A3', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [7], $tcStyle->cellHeader)->addText('Color', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [8], $tcStyle->cellHeader)->addText('Duplex', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [9], $tcStyle->cellHeader)->addText('MFP', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [10], $tcStyle->cellHeader)->addText('Fax', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [11], $tcStyle->cellHeader)->addText('Reports Toner Levels', 'small_cell_heading', 'nospacing_centeralign');
$OverutilizedDevicesTable->addCell($cellWidths [12], $tcStyle->cellHeader)->addText(sprintf('Linked to %1$s Program', $this->jit), 'small_cell_heading', 'nospacing_centeralign');

/* @var $device DeviceInstanceModel */
foreach ($healthcheckViewModel->getOverutilizedDevices() as $device)
{
    $deviceName = str_replace("Hewlett-Packard", "HP", $device->getDeviceName());

    $OverutilizedDevicesTable->addRow(null, $tcStyle->rowstyle);
    $cell = $OverutilizedDevicesTable->addCell($cellWidths [0], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell1));
    $cell->addText($deviceName, null, ['spaceAfter' => 0]);
    $cell->addText($device->serialNumber, null, ['spaceAfter' => 0]);
    $cell->addText($device->ipAddress, null, ['spaceAfter' => 0]);
    $OverutilizedDevicesTable->addCell($cellWidths [1], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText(number_format($device->getAge(), 0), null, 'nospacing_rightalign');
    $OverutilizedDevicesTable->addCell($cellWidths [2], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell3))->addText($this->formatPageVolume($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_rightalign');
    $OverutilizedDevicesTable->addCell($cellWidths [3], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText(number_format($device->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) . '%', null, 'nospacing_rightalign');
    $OverutilizedDevicesTable->addCell($cellWidths [4], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText(number_format($device->getMasterDevice()->calculateEstimatedMaxLifeCount()), null, 'nospacing_rightalign');
    $OverutilizedDevicesTable->addCell($cellWidths [5], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText(number_format($device->getMeter()->endMeterLife), null, 'nospacing_rightalign');
    $OverutilizedDevicesTable->addCell($cellWidths [6], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isA3 ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $OverutilizedDevicesTable->addCell($cellWidths [7], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isColor() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $OverutilizedDevicesTable->addCell($cellWidths [8], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isDuplex ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $OverutilizedDevicesTable->addCell($cellWidths [9], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isMfp() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $OverutilizedDevicesTable->addCell($cellWidths [10], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isFax ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $OverutilizedDevicesTable->addCell($cellWidths [11], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isCapableOfReportingTonerLevels() ? 'Yes' : 'No')), null, 'nospacing_centeralign');
    $OverutilizedDevicesTable->addCell($cellWidths [12], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isLeased ? 'No' : ($device->isManaged ? 'Yes' : 'No'))), null, 'nospacing_centeralign');
}

$section->addPageBreak();
/**
 * Old Devices
 */
$section->addTitle("Old Devices", 2);

$oldDevicesTable = $section->addTable($tcStyle->tablestyle);
$row             = $oldDevicesTable->addRow($tcStyle->rowheight, $tcStyle->rowheader);
$row->getStyle()->setCantSplit(true);
$oldDevicesTable->addCell($cellWidths [0], $tcStyle->cellHeader)->addText('Device Name', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [1], $tcStyle->cellHeader)->addText('Device Age (Years)', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [2], $tcStyle->cellHeader)->addText('Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [3], $tcStyle->cellHeader)->addText('Percent of Fleet\'s Total Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [4], $tcStyle->cellHeader)->addText('Percent of Monthly Cost', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [5], $tcStyle->cellHeader)->addText('Suggested Max. Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [6], $tcStyle->cellHeader)->addText('Life Page Count', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [7], $tcStyle->cellHeader)->addText('A3', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [8], $tcStyle->cellHeader)->addText('Color', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [9], $tcStyle->cellHeader)->addText('Duplex', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [10], $tcStyle->cellHeader)->addText('MFP', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [11], $tcStyle->cellHeader)->addText('Fax', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [12], $tcStyle->cellHeader)->addText('Reports Toner Levels', 'small_cell_heading', 'nospacing_centeralign');
$oldDevicesTable->addCell($cellWidths [13], $tcStyle->cellHeader)->addText(sprintf('Linked to %1$s Program', $this->jit), 'small_cell_heading', 'nospacing_centeralign');

/* @var $device DeviceInstanceModel */
foreach ($healthcheckViewModel->getOldDevices() as $device)
{
    $deviceName = str_replace("Hewlett-Packard", "HP", $device->getDeviceName());

    $oldDevicesTable->addRow(null, $tcStyle->rowstyle);
    $cell = $oldDevicesTable->addCell($cellWidths [0], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell1));
    $cell->addText($deviceName, null, ['spaceAfter' => 0]);
    $cell->addText($device->serialNumber, null, ['spaceAfter' => 0]);
    $cell->addText($device->ipAddress, null, ['spaceAfter' => 0]);
    $oldDevicesTable->addCell($cellWidths [1], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText(number_format($device->getAge(), 0), null, 'nospacing_rightalign');
    $oldDevicesTable->addCell($cellWidths [2], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell3))->addText($this->formatPageVolume($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_rightalign');
    $oldDevicesTable->addCell($cellWidths [3], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($this->translate(number_format($device->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) . '%'), null, 'nospacing_rightalign');
    $oldDevicesTable->addCell($cellWidths [4], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText(($device->isLeased)
        ? number_format($device->getLeasedMonthlyRatePercentage(
                $healthcheckViewModel->healthcheck->getHealthcheckSettings()->monthlyLeasePayment,
                $healthcheckViewModel->getLeasedBlackAndWhiteCharge(),
                $healthcheckViewModel->getLeasedColorCharge(),
                $healthcheckViewModel->calculateTotalMonthlyCost()
            ) * 100, 2)
        : number_format($device->getMonthlyRatePercentage(
                $healthcheckViewModel->calculateTotalMonthlyCost(),
                $healthcheckViewModel->getCostPerPageSettingForCustomer()
            ) * 100, 2) . '%', null, 'nospacing_rightalign');

    $oldDevicesTable->addCell($cellWidths [5], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText(number_format($device->getMasterDevice()->calculateEstimatedMaxLifeCount()), null, 'nospacing_rightalign');
    $oldDevicesTable->addCell($cellWidths [6], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText(number_format($device->getMeter()->endMeterLife), null, 'nospacing_rightalign');
    $oldDevicesTable->addCell($cellWidths [7], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isA3 ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $oldDevicesTable->addCell($cellWidths [8], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isColor() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $oldDevicesTable->addCell($cellWidths [9], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isDuplex ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $oldDevicesTable->addCell($cellWidths [10], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isMfp() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $oldDevicesTable->addCell($cellWidths [11], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($device->getMasterDevice()->isFax ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $oldDevicesTable->addCell($cellWidths [12], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isCapableOfReportingTonerLevels() ? 'Yes' : 'No')), null, 'nospacing_centeralign');
    $oldDevicesTable->addCell($cellWidths [13], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isLeased ? 'No' : ($device->isManaged ? 'Yes' : 'No'))), null, 'nospacing_centeralign');
}
$section->addTextBreak();

$section->addPageBreak();
/**
 * Devices Not Reporting Toner Levels
 */
$section->addTitle("Devices Not Reporting Toner Levels", 2);

$notReportingTonerDevicesTable = $section->addTable($tcStyle->tablestyle);
$notReportingTonerDevicesTable->addRow($tcStyle->rowheight, $tcStyle->rowheader);
$notReportingTonerDevicesTable->addCell($cellWidths [0], $tcStyle->cellHeader)->addText('Device Name', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [1], $tcStyle->cellHeader)->addText('Device Age (Years)', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [2], $tcStyle->cellHeader)->addText('Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [3], $tcStyle->cellHeader)->addText('Percent of Fleet\'s Total Monthly Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [4], $tcStyle->cellHeader)->addText('Suggested Max. Page Volume', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [5], $tcStyle->cellHeader)->addText('Life Page Count', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [6], $tcStyle->cellHeader)->addText('A3', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [7], $tcStyle->cellHeader)->addText('Color', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [8], $tcStyle->cellHeader)->addText('Duplex', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [9], $tcStyle->cellHeader)->addText('MFP', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [10], $tcStyle->cellHeader)->addText('Fax', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [11], $tcStyle->cellHeader)->addText('Reports Toner Levels', 'small_cell_heading', 'nospacing_centeralign');
$notReportingTonerDevicesTable->addCell($cellWidths [12], $tcStyle->cellHeader)->addText(sprintf('Linked to %1$s Program', $this->jit), 'small_cell_heading', 'nospacing_centeralign');

/* @var $device DeviceInstanceModel */
foreach ($healthcheckViewModel->getDevicesNotReportingTonerLevels() as $device)
{
    $deviceName = str_replace("Hewlett-Packard", "HP", $device->getDeviceName());

    $notReportingTonerDevicesTable->addRow(null, $tcStyle->rowstyle);
    $cell = $notReportingTonerDevicesTable->addCell($cellWidths [0], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell1));
    $cell->addText($deviceName, null, ['spaceAfter' => 0]);
    $cell->addText($device->serialNumber, null, ['spaceAfter' => 0]);
    $cell->addText($device->ipAddress, null, ['spaceAfter' => 0]);
    $notReportingTonerDevicesTable->addCell($cellWidths [1], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText(number_format($device->getAge(), 0), null, 'nospacing_rightalign');
    $notReportingTonerDevicesTable->addCell($cellWidths [2], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell3))->addText($this->formatPageVolume($device->getPageCounts()->getCombinedPageCount()->getMonthly()), null, 'nospacing_rightalign');
    $notReportingTonerDevicesTable->addCell($cellWidths [3], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($this->translate(number_format($device->calculateMonthlyPercentOfTotalVolume($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly()), 2) . '%'), null, 'nospacing_rightalign');
    $notReportingTonerDevicesTable->addCell($cellWidths [4], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText(number_format($device->getMasterDevice()->calculateEstimatedMaxLifeCount()), null, 'nospacing_rightalign');
    $notReportingTonerDevicesTable->addCell($cellWidths [5], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText(number_format($device->getMeter()->endMeterLife), null, 'nospacing_rightalign');
    $notReportingTonerDevicesTable->addCell($cellWidths [6], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isA3 ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $notReportingTonerDevicesTable->addCell($cellWidths [7], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isColor() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $notReportingTonerDevicesTable->addCell($cellWidths [8], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isDuplex ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $notReportingTonerDevicesTable->addCell($cellWidths [9], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isMfp() ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $notReportingTonerDevicesTable->addCell($cellWidths [10], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell4))->addText($device->getMasterDevice()->isFax ? 'Yes' : 'No', null, 'nospacing_centeralign');
    $notReportingTonerDevicesTable->addCell($cellWidths [11], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isCapableOfReportingTonerLevels() ? 'Yes' : 'No')), null, 'nospacing_centeralign');
    $notReportingTonerDevicesTable->addCell($cellWidths [12], ($device->isLeased ? $tcStyle->cellshaded : $tcStyle->cell2))->addText($this->translate(($device->isLeased ? 'No' : ($device->isManaged ? 'Yes' : 'No'))), null, 'nospacing_centeralign');
}
$section->addTextBreak();