<?php
/**
 * Healthcheck - Analysis: Technology Reliability and User Productivity
 */

/* @var $phpWord \PhpOffice\PhpWord\PhpWord */
$phpWord = $this->phpword;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;

/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs               = $healthcheckViewModel->getGraphs();

$section->addPageBreak();
$section->addTitle("Analysis: Technology Reliability and User Productivity", 1);

$section->addTitle('Age of Printing Devices', 2);

$section->addText(sprintf('We estimate the average age of your printing devices is %1$s %2$s; a good industry average is 3 years. Devices over 5 years old require, on average, one repair per year.',
    number_format($healthcheckViewModel->getAverageAgeOfDevices(), 1),
    (number_format($healthcheckViewModel->getAverageAgeOfDevices()) == 1) ? 'year' : 'years'
));

$imageTable = $section->addTable();
$imageTable->addRow();
$cell = $imageTable->addCell(9028.8, array(
    'valign' => 'center'
));

$cell->addImage($graphs ['AgePieGraph'], array(
    'align' => 'center'
));
$section->addText('A breakdown of the ages of your printing devices is shown above.');
$section->addTextBreak();

$section->addTitle('Technology Features and Functionality', 2);

$section->addText('The ability to scan and fax documents from convenient locations helps to improve document workflow and productivity, and scanning can also help reduce the number of pages printed. Color printing capabilities are important if you are generating client-facing or other important documents in-house.');
$section->addText('The charts below show the number of your printing devices that are capable of copying, duplex printing, and color printing.');

$imageTable = $section->addTable($this->styles->tables->tripleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell1)->addImage($graphs ['CopyCapableDevicesGraph']);
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell2)->addImage($graphs ['DuplexCapableDevicesGraph']);
$imageTable->addCell(3010, $this->styles->tables->tripleimage->cell3)->addImage($graphs ['colorCapablePieChart']);

$section->addTextBreak();
$section->addText(sprintf('If you are in need of additional features and functionality to improve workflow and print quality, %1$s has a variety of printing devices that can meet your specific business needs. If you already have everything you need, we can manage the printing assets you have.', $this->companyName));