<?php 
$quote = $this->Quote(); /* @var $quote Quotegen_Model_Quote */
$this->activePage = 'reports';
echo $this->render('_partials/quoteHeading.phtml');
$this->headScript()->captureStart();
?>
$(function () {
    $(".downloadButton").click(function(e)
	{
	    e.preventDefault();

    	var extension = "." + $(this).data('ext');
    	var loadingMessage = $(this).data('loadingmessage');
    	if (loadingMessage == null || loadingMessage.length < 1)
    	{
    		loadingMessage = "Please be patient while we generate your document. This normally takes a minute or two.";
    	}
    	var cancelled = false;
    	var xhr;


        $("<div id='loading' style='text-align: center'></div>").append("<p>" + loadingMessage + "</p>").append("<div class='AjaxLoadingIcon'></div>").dialog({
            height: 200,
            width: 400,
            modal: true,
            draggable: false,
            resizable: false,
            title: "Generating Document...",
            closeOnEscape: false,
        	close: function(event, ui) {
        		if (xhr != null)
    			{
        			cancelled = true;
        			xhr.abort();
    			}
        	}
        });

        xhr = $.ajax({
            url: this.href,
            success: function(data) {
            	if (data.indexOf(extension) < 0 || data.length > 100)
            	{
            		// Debug Info for extension:
            		//.append("<p>IndexOf Returned: " + data.indexOf(extension) + " for the extension " + extension +"</p>")
            		$("<div id='errorMessage'></div>").append(data).dialog({
            			height: 300,
            			width: 900,
            			modal: true,
            			draggable: true,
            			resizeable: true,
            			title: "Error",
        				buttons: {
        					Ok: function() {
        						$( this ).dialog( "close" );
        					}
        				}
            		});
            	}
            	else
            	{
            	    window.location.href = data;
            	}
            },
            error: function(data) {
            	if (!cancelled)
        		{
		        	$("<div id='errorMessage'></div>").append(data).dialog({
		    			height: 500,
		    			width: 900,
		    			modal: true,
		    			draggable: true,
		    			resizeable: true,
		    			title: "Error"

		    		});
        		}
            },
            complete: function(data) {
            	$("#loading").remove();
            	xhr = null;
            	cancelled = false;
            }
        });
    });
});
<?php $this->headScript()->captureEnd();?>
<div class='row-fluid'>
	<ul class="thumbnails">
		<li class='span4'>
	 		<h3>Download Quote</h3>
			<p>Download a .docx version of this quote.</p>
    		<a class="downloadButton btn btn-primary" data-ext="docx" href="<?php echo $this->url(array('action' => (($quote->isLeased()) ? 'lease' : 'purchase') . '-quote', 'format' => 'docx')); ?>"><i class='icon-download-alt icon-white'></i> Download Quote</a>
    		<br/>
    		<br/>
    		<a class="downloadButton btn btn-primary" data-ext="docx" href="<?php echo $this->url(array('action' => 'contract', 'format' => 'docx')); ?>"><i class='icon-download-alt icon-white'></i> Download Contract</a>
		</li>
		<li class='span4'>
			<h3>Download Order List</h3>
			<p>Download a .XLSX file for the items in this quote.</p>
			<a class="downloadButton btn btn-success" data-ext="xlsx" href="<?php echo $this->url(array('action' => 'order-list', 'format' => 'xlsx')); ?>"><i class='icon-download-alt icon-white'></i> Download Order List</a>
		</li>
		<li class='span4'>
			<?php echo $this->form; ?>
		</li>
	</ul>
</div>
<?php if ($quote->isLeased()) : ?>
	<?php echo $this->render('quote/reports/lease-quote.phtml'); ?>
<?php else : ?>
	<?php echo $this->render('quote/reports/purchase-quote.phtml'); ?>
<?php endif; ?>
<?php echo $this->navigationForm; ?>
