<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Mappers\ContractTemplateMapper;
use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\QuoteModel;

/* @var $quote QuoteModel */
$quote = $this->Quote();

$this->activePage = 'reports';
echo $this->render('_partials/quoteHeading.phtml');
$this->headScript()->appendFile($this->baseUrl('/js/app/legacy/HtmlReport.js?'.date('Ymd')));

$contractTemplates = ContractTemplateMapper::getInstance()->fetchAllForDealer($this->Identity()->dealerId);
?>
<div class="container">
    <?= $this->navigationForm ?>
    <div class="row">

        <!-- Final Quote Settings -->
        <div class='col-md-6'>
            <div class="panel panel-primary">
                <div class="panel-heading">Settings - Report</div>
                <div class="panel-body">
                    <?= $this->form ?>
                </div>
            </div>
        </div>
        <div class='col-md-6'>

            <!-- Download Quote -->
            <div class="panel panel-primary">
                <div class="panel-heading">Document - Quote</div>
                <div class="panel-body">
                    <p>Client facing document outlining the quoted devices</p>

                </div>
                <div class="panel-footer text-right">
                    <a class="downloadButton btn btn-primary btn-xs" title="Download quote in DOCX format" data-ext="docx" href="<?= $this->url(['format' => 'docx', 'quoteId' => $quote->id], 'quotes.reports.' . (($quote->isLeased()) ? 'lease' : 'purchase')); ?>">
                        <i class='fa fa-fw fa-download'></i>
                        Download (DOCX)
                    </a>
                </div>
            </div>

            <!-- Download Contract -->
            <div class="panel panel-primary">
                <div class="panel-heading">Document - Contract</div>
                <div class="panel-body">
                    <p>This is a supporting contract based on either the default template or a template provided by your administrator.</p>

                </div>
                <div class="panel-footer">
                    <div class="input-group input-group-sm">
                        <label class="sr-only" for="contractTemplateId">Contract Template</label>
                        <select class="form-control" id="contractTemplateId" name="contractTemplateId">
                            <?php foreach ($contractTemplates as $contractTemplate) : ?>
                                <option value="<?= $contractTemplate->id ?>"><?= $contractTemplate->templateName ?></option>
                            <?php endforeach; ?>
                        </select>

                        <span class="input-group-btn">
                            <a class="downloadButton btn btn-primary" title="Download contract in DOCX format" data-ext="docx" data-extra-parameter="contractTemplateId" href="<?= $this->url(['format' => 'docx', 'quoteId' => $quote->id], 'quotes.reports.contract'); ?>">
                                <i class='fa fa-fw fa-download'></i>
                                Download (DOCX)
                            </a>
                        </span>
                    </div>
                </div>
            </div>

            <!-- Order List -->
            <div class="panel panel-primary">
                <div class="panel-heading">Document - Order List</div>
                <div class="panel-body">
                    <p>An order list meant for internal consumption. It lists all the SKUs that need to be ordered to fulfill the quote.</p>
                </div>
                <div class="panel-footer text-right">
                    <a class="downloadButton btn btn-success btn-xs" title="Download order list in XLSX format" data-ext="xlsx" href="<?= $this->url(['format' => 'xlsx', 'quoteId' => $quote->id], 'quotes.reports.order-list'); ?>">
                        <i class='fa fa-fw fa-download'></i>
                        Download (XLSX)
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Quote Preview -->
    <div class="panel panel-default">
        <div class="panel-heading"><h2>Quote Details - Preview</h2></div>
        <div class="panel-body">
            <?php if ($quote->isLeased()) : ?>
                <?= $this->render('quote/reports/lease-quote.phtml'); ?>
            <?php else : ?>
                <?= $this->render('quote/reports/purchase-quote.phtml'); ?>
            <?php endif; ?>
        </div>
    </div>
    <?= $this->navigationForm ?>
</div>