<?php 
$quote = $this->Quote(); /* @var $quote Quotegen_Model_Quote */
echo $this->render('_partials/quoteHeading.phtml');

$this->headScript()->appendScript("$('i').popover();");

?>
<div class="page-header">
    <h1>Leased Quote</h1>
</div>
<div class="row">
    <div class="span12">
        <?php foreach ($quote->getQuoteDeviceGroups() as $quoteDeviceGroup) : /* @var $quoteDeviceGroup Quotegen_Model_QuoteDeviceGroup */ ?>
        <table class="table table-condensed table-bordered table-striped quoteDeviceTable">
                <tr class="header-row">
                    <th style="width: 220px;">Item</th>
                    <th style="width: 140px;">Sku</th>
                    <th>Description</th>
                    <th style="width: 80px;">Price</th>
                    <th style="width: 40px;">Qty</th>
                    <th style="width: 70px;">Subtotal</th>
                </tr>
                
                <?php foreach ($quoteDeviceGroup->getQuoteDeviceGroupDevices() as $quoteDeviceGroupDevice) : /* @var $quoteDeviceGroupDevice Quotegen_Model_QuoteDeviceGroupDevice */ ?>
                <tr class="deviceRow">
                    <th><h5><?php echo $quoteDeviceGroupDevice->getQuoteDevice()->getName(); ?></h5></th>
                    <td><?php echo $quoteDeviceGroupDevice->getQuoteDevice()->getSku(); ?></td>     
                    <td></td>           
                    <td style="text-align: right;"></td>
                    <td style="text-align: right;"><?php echo number_format($quoteDeviceGroupDevice->getQuantity()); ?></td>
                    <td style="text-align: right;"></td>
                </tr>
                <?php if (count($quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions()) > 0) : ?>
                
                <?php foreach ($quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions() as $quoteDeviceOption) : /* @var $quoteDeviceOption Quotegen_Model_QuoteDeviceOption */ ?>
                <tr class="optionRow">
                    <td><?php echo $quoteDeviceOption->getName(); ?></td>
                    <td><?php echo $quoteDeviceOption->getSku(); ?></td>
                    <td><?php echo $quoteDeviceOption->getDescription(); ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>
        <?php endforeach; ?>
        <tr class="pagesRow">
            <td>Monochrome</td>
            <td></td>
            <td></td>
            <td>Pages Included</td>
            <td><?php echo number_format($quoteDeviceGroupDevice->getMonochromePagesQuantity()); ?></td>
            <td></td>
        </tr>
        <tr class="pagesRow">
            <td>Color</td>
            <td></td>
            <td></td>
            <td>Pages Included</td>
            <td><?php echo number_format($quoteDeviceGroupDevice->getColorPagesQuantity()); ?></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="5"></td>
            <th style="text-align: right;"><?php echo $this->currency($quoteDeviceGroup->calculateGroupMonthlyLeasePrice()); ?></th>
        </tr>
        <tr class="pagesRow">
            <td style="text-align: right;" colspan="5">Monochrome overage price</td>
            <td style="text-align: right;"><?php echo $this->currency($quote->getMonochromeOverageRatePerPage()); ?></td>
        </tr>
        <tr class="pagesRow">
            <td style="text-align: right;" colspan="5">Color overage price</td>
            <td style="text-align: right;"><?php echo $this->currency($quote->getColorOverageRatePerPage()); ?></td>
        </tr>
        </table>
        <?php endforeach; ?>
        <h3>Quote Monthly Total: <?php echo $this->currency($quote->calculateQuoteMonthlyLeaseSubtotal()); ?></h3>
    </div>
</div>