<?php 
$quote = $this->Quote(); /* @var $quote Quotegen_Model_Quote */
//$this->placeholder('ProgressionNav')->set($this->render('_partials/quoteHeading.phtml'));

$this->headScript()->appendScript("$('i').popover();");

?>
<div class="page-header">
    <h1>Leased Quote</h1>
</div>
<div class="row">
    <div class="span12">
        <?php foreach ($quote->getQuoteDeviceGroups() as $quoteDeviceGroup) : /* @var $quoteDeviceGroup Quotegen_Model_QuoteDeviceGroup */ ?>
        <table class="table table-condensed table-bordered table-striped quoteDeviceTable">
                <tr class="header-row">
                    <th style="width: 220px;">Item</th>
                    <th style="width: 140px;">Sku</th>
                    <th>Description</th>
                    <th style="width: 80px;">Price</th>
                    <th style="width: 40px;">Qty</th>
                    <th style="width: 70px;">Subtotal</th>
                </tr>
                
                <?php foreach ($quoteDeviceGroup->getQuoteDeviceGroupDevices() as $quoteDevice) : /* @var $quoteDevice Quotegen_Model_QuoteDevice */ ?>
                <tr class="deviceRow">
                    <th><h5><?php echo $quoteDevice->getName(); ?></h5></th>
                    <td><?php echo $quoteDevice->getSku(); ?></td>     
                    <td></td>           
                    <td style="text-align: right;"></td>
                    <td style="text-align: right;"><?php echo number_format($quoteDevice->getQuantity()); ?></td>
                    <td style="text-align: right;"></td>
                </tr>
                <?php if (count($quoteDevice->getQuoteDeviceOptions()) > 0) : ?>
                
                <?php foreach ($quoteDevice->getQuoteDeviceOptions() as $quoteDeviceOption) : /* @var $quoteDeviceOption Quotegen_Model_QuoteDeviceOption */ ?>
                <tr class="optionRow">
                    <td><?php echo $quoteDeviceOption->getName(); ?></td>
                    <td><?php echo $quoteDeviceOption->getSku(); ?></td>
                    <td><?php echo $quoteDeviceOption->getDescription(); ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <?php endforeach; ?>
                
                <?php endif; ?>
                
                
            
        <?php endforeach; ?>
        
        <?php if (count($quoteDeviceGroup->getPages()) > 0) : ?>
                
        <?php foreach ($quoteDeviceGroup->getPages() as $quoteDeviceGroupPage) : /* @var $quoteDeviceGroupPage Quotegen_Model_QuoteDeviceGroupPage */ ?>
        <tr class="pagesRow">
            <td><?php echo $quoteDeviceGroupPage->getName(); ?> Pages</td>
            <td><?php echo $quoteDeviceGroupPage->getSku(); ?></td>
            <td></td>
            <td></td>
            <td><?php echo number_format($quoteDeviceGroupPage->getIncludedQuantity()); ?></td>
            <td></td>
        </tr>
        <?php endforeach; ?>
        
        <?php endif; ?>
        
        <tr>
            <td colspan="5"></td>
            <th style="text-align: right;"><?php echo $this->currency($quoteDeviceGroup->calculateGroupMonthlyLeasePrice()); ?></th>
        </tr>
        <?php if (count($quoteDeviceGroup->getPages()) > 0) : ?>
        <?php foreach ($quoteDeviceGroup->getPages() as $quoteDeviceGroupPage) : /* @var $quoteDeviceGroupPage Quotegen_Model_QuoteDeviceGroupPage */ ?>
        <tr class="pagesRow">
            <td style="text-align: right;" colspan="5"><?php echo $quoteDeviceGroupPage->getName(); ?> overage price</td>
            <td style="text-align: right;"><?php echo $this->currency($quoteDeviceGroupPage->getPricePerPage()); ?></td>
        </tr>
        <?php endforeach; ?>
        
        <?php endif; ?>
        </table>
        <?php endforeach; ?>
        <h3>Quote Monthly Total: <?php echo $this->currency($quote->calculateQuoteMonthlyLeaseSubtotal()); ?></h3>
    </div>
</div>