<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\QuoteModel;

/* @var $quote QuoteModel */
$quote = $this->Quote();
?>
<div class="col-sm-12">
    <?php foreach ($quote->getQuoteDeviceGroups() as $quoteDeviceGroup) : ?>
        <?php if ($quoteDeviceGroup->calculateTotalQuantity() > 0) : ?>
            <h3><?= $this->escape($quoteDeviceGroup->name); ?></h3>
            <table class="table table-condensed table-bordered table-striped">
                <tr class="header-row">
                    <th style="width: 220px;">Item</th>
                    <th style="width: 140px;">SKU</th>
                    <th>Description and Features</th>
                    <th style="width: 80px;">Price</th>
                    <th style="width: 65px;">Quantity</th>
                    <th style="width: 70px;">Subtotal</th>
                </tr>
                <?php foreach ($quoteDeviceGroup->getQuoteDeviceGroupDevices() as $quoteDeviceGroupDevice) : ?>
                    <?php if ($quoteDeviceGroupDevice->quantity > 0) : ?>
                        <tr class="deviceRow">
                            <th>
                                <h5><?= $quoteDeviceGroupDevice->getQuoteDevice()->name; ?></h5>
                            </th>
                            <td><?= $quoteDeviceGroupDevice->getQuoteDevice()->oemSku; ?></td>
                            <td></td>
                            <td style="text-align: right;"></td>
                            <td style="text-align: right;"><?= number_format($quoteDeviceGroupDevice->quantity); ?></td>
                            <td style="text-align: right;"></td>
                        </tr>
                        <?php if (count($quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions()) > 0) : ?>
                            <?php foreach ($quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions() as $quoteDeviceOption) : ?>
                                <tr class="optionRow">
                                    <td><?= $quoteDeviceOption->name; ?></td>
                                    <td><?= $quoteDeviceOption->oemSku; ?></td>
                                    <td><?= $quoteDeviceOption->description; ?></td>
                                    <td></td>
                                    <td style="text-align: right"><?= number_format($quoteDeviceOption->quantity); ?></td>
                                    <td></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($quoteDeviceGroup->calculateTotalMonochromePages() > 0) : ?>
                    <tr class="pagesRow">
                        <td>Monochrome Pages</td>
                        <td></td>
                        <td>Pages Included</td>
                        <td></td>
                        <td style="text-align: right;"><?= $this->formatPageVolume($quoteDeviceGroup->calculateTotalMonochromePages()); ?> </td>
                        <td></td>
                    </tr>
                <?php endif ?>
                <?php if ($quoteDeviceGroup->calculateTotalColorPages() > 0) : ?>
                    <tr class="pagesRow">
                        <td>Color Pages</td>
                        <td></td>
                        <td>Pages Included</td>
                        <td></td>
                        <td style="text-align: right;"><?= $this->formatPageVolume($quoteDeviceGroup->calculateTotalColorPages()); ?> </td>
                        <td></td>
                    </tr>
                <?php endif ?>
                <tr>
                    <td colspan="5"></td>
                    <th style="text-align: right;"><?= $this->currency($quoteDeviceGroup->calculateMonthlyLeasePrice()); ?></th>
                </tr>
            </table>
        <?php endif; ?>
    <?php endforeach; ?>
    <table class="table table-condensed table-bordered table-striped">
        <tr class="pagesRow">
            <td style="text-align: right;" colspan="5">Monochrome overage price</td>
            <td style="text-align: right; width: 70px;"><?= $this->formatCostPerPage($quote->calculateMonochromeOverageRatePerPage()); ?></td>
        </tr>
        <tr class="pagesRow">
            <td style="text-align: right;" colspan="5">Color overage price</td>
            <td style="text-align: right; width: 70px"><?= $this->formatCostPerPage($quote->calculateColorOverageRatePerPage()); ?></td>
        </tr>
    </table>
    <div class='pull-right'>
        <h3>Quote Monthly Total: <?= $this->currency($quote->calculateQuoteMonthlyLeaseSubtotal()); ?></h3>
    </div>
</div>