<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\QuoteModel;
use MPSToolbox\Settings\Service\DealerSettingsService;

$filename = $this->filename;
$savePath = PUBLIC_PATH . "/downloads/client/{$this->clientId}/quote/{$this->quoteId}/";

if (!is_dir($savePath))
{
    if (!mkdir($savePath, 0777, true))
    {
        throw new Exception("Could not open cache folder! PATH:" . $savePath, 0);
    }
}
$savePath   = $savePath . $filename;
$linkToFile = $this->baseUrl("/downloads/client/{$this->clientId}/quote/{$this->quoteId}/{$filename}");

// This may not need to be removed from here
// Base path to the files used to render the document
$basePath            = 'quote/reports/purchase-quote/docx';
$commonPartsBasePath = 'quote/reports/common/' . $this->App()->theme;

$quote = $this->Quote();
/* @var $quote QuoteModel */

/* @var $phpword \PhpOffice\PhpWord\PhpWord */
$phpword = $this->phpword;

/**
 * Document Properties
 */
$properties = $phpword->getDocumentProperties();
$properties->setCreator('Demo Report');
$properties->setCompany('Demo Report');
$properties->setTitle('Demo Report');
$properties->setDescription('Demo Report');
$properties->setCategory('Demo Report');
$properties->setLastModifiedBy('Demo Report');
$properties->setCreated(time());
$properties->setModified(time());
$properties->setSubject('Demo Report');
$properties->setKeywords('demo, assessment, report');

$titlepageSection = $phpword->addSection([
    'orientation'  => null,
    'marginLeft'   => 720,
    'marginRight'  => 720,
    'marginTop'    => 720,
    'marginBottom' => 720
]);
$section          = $phpword->addSection();

$this->render("{$commonPartsBasePath}/styles.phtml");


$phpword->addParagraphStyle('titleStyle1', [
    'align'      => 'center',
    'spaceAfter' => 100,
    'bgColor'    => '004990'
]);
$phpword->addParagraphStyle('titleStyle2', [
    'spaceAfter'  => 100,
    'spaceBefore' => 100,
    'shading'     => [
        'fill' => '4C4C4C',
    ],
    'align'       => 'center',
]);
$phpword->addParagraphStyle('titleStyle3', [
    'spaceAfter' => 200,
    'tabs'       => [
        new \PhpOffice\PhpWord\Style\Tab('left', 350)
    ],
    'shading'    => [
        'fill' => '7F7F7F',
    ]
]);
$phpword->addFontStyle('titlepage_title', [
    'size'  => 24,
    'bold'  => true,
    'color' => 'FFFFFF'
]);

$phpword->addFontStyle('titlepage_subtitle', [
    'size'  => 16,
    'bold'  => true,
    'color' => 'FFFFFF'
]);

$phpword->addFontStyle('titlepage_address', [
    'size'  => 12,
    'color' => 'FFFFFF'
]);
$phpword->addParagraphStyle('titlepageHeaderParagraph', [
    'spaceAfter' => 200
]);
$phpword->addParagraphStyle('titlepageHeader1', [
    'spaceAfter' => 0,

]);


/**
 * Paragraph styles
 */
$phpword->addParagraphStyle('titlepageHeaderParagraph', [
    'spaceAfter' => 200
]);

$phpword->addParagraphStyle('nospacing', [
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('nospacing_rightalign', [
    'align'       => 'right',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('nospacing_centeralign', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('rightalign', [
    'align' => 'right'
]);

$phpword->addParagraphStyle('gradeParagraph', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

$phpword->addParagraphStyle('savingsParagraph', [
    'align'       => 'center',
    'spaceBefore' => 0,
    'spaceAfter'  => 0
]);

/**
 * Font Styles
 */
$phpword->addFontStyle('titlepageHeaderFont', [
    'bold' => true,
    'size' => 16
]);

$phpword->addFontStyle('bold_text', [
    'bold' => true
]);

$phpword->addFontStyle('bold_red_text', [
    'bold'  => true,
    'color' => 'F00001'
]);

$phpword->addFontStyle('gradeFont', [
    'bold' => true,
    'size' => 18
]);

$phpword->addFontStyle('gradeTitleFont', [
    'bold' => true,
    'size' => 12
]);

$phpword->addFontStyle('savingsFont', [
    'bold' => true,
    'size' => 11
]);

$phpword->addFontStyle('savingsAmountFont', [
    'color' => $this->docStyles->brandBaseColor,
    'bold'  => true,
    'size'  => 11
]);

$phpword->addFontStyle('italic_text', [
    'italic' => true,
]);

$phpword->addFontStyle('small_italic_text', [
    'color'  => '333333',
    'italic' => true,
    'size'   => 9
]);

/**
 * Header/Title Styles
 */
// H1 Style
$phpword->addTitleStyle(1, [
    'size'  => 15,
    'color' => My_Brand::getDealerBranding()->h1FontColor,
    'bold'  => true
], [
    'shading' => [
        'fill' => My_Brand::getDealerBranding()->h1BackgroundColor,
    ],
]);

// H2 Style #5881BC
$phpword->addTitleStyle(2, [
    'size'   => 12,
    'color'  => My_Brand::getDealerBranding()->h2FontColor,
    'bold'   => true,
    'italic' => true
], [
    'shading' => [
        'fill' => My_Brand::getDealerBranding()->h2BackgroundColor,
    ],
]);

// H3 Style #5881BC
$phpword->addTitleStyle(3, [
    'size'  => 10,
    'color' => 'FF0000',
    'bold'  => true
], [
    'spaceBefore' => 100,
    'spaceAfter'  => 100
]);

// H3 Style #5881BC
$phpword->addFontStyle('heading3', [
    'size'  => 10,
    'color' => 'FF0000',
    'bold'  => true
]);

/**
 * True costs table styles
 */
$trueCostsTable = (object)[
    "tablestyle" => [
        'cellMarginTop'    => 90,
        'cellMarginRight'  => 50,
        'cellMarginBottom' => 90,
        'cellMarginLeft'   => 50
    ],
    "col1Width"  => 2347.38,
    "col2Width"  => 3764.88,
    "col3Width"  => 4042.71,
    "header"     => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => 'bold_text',
            "paragraphStyle" => 'nospacing_centeralign'
        ]
    ],
    "body"       => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'bold' => true
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => null,
            "paragraphStyle" => 'nospacing'
        ]
    ]
];

$purchaseQuoteTable = (object)[
    "tablestyle"          => [
        'cellMarginTop'     => 25,
        'cellMarginRight'   => 100,
        'cellMarginBottom'  => 25,
        'cellMarginLeft'    => 100,
        'borderColor'       => 'BFBFBF',
        'borderBottomSize'  => 1,
        'borderBottomColor' => 'BFBFBF',
    ],
    "col1Width"           => 2257,
    "col2Width"           => 1986,
    "col3Width"           => 3702,
    "col4Width"           => 1083,
    "span123Width"        => 7945,
    "span23Width"         => 5688,
    "header"              => (object)[
        "rowheight" => null,
        "rowStyle"  => [
            'tblHeader' => true,
        ],
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "bgColor"          => $this->docStyles->brandBaseColor,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'color' => 'FFFFFF',
                'bold'  => true,
                'name'  => 'Calibri',
                'size'  => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'spaceAfter' => 0
            ]
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "bgColor"          => $this->docStyles->brandBaseColor,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'color' => 'FFFFFF',
                'bold'  => true,
                'name'  => 'Calibri',
                'size'  => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'spaceAfter' => 0
            ]
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "bgColor"          => $this->docStyles->brandBaseColor,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'color' => 'FFFFFF',
                'bold'  => true,
                'name'  => 'Calibri',
                'size'  => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'spaceAfter' => 0
            ]
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "bgColor"          => $this->docStyles->brandBaseColor,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'right',
                'spaceAfter' => 0
            ]
        ]
    ],
    "signatureTableStyle" => [
        'cellMarginTop'    => 25,
        'cellMarginRight'  => 100,
        'cellMarginBottom' => 25,
        'cellMarginLeft'   => 100,
    ],
    "device"              => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => null,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'bold' => true,
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => null,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => null,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => null,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'right',
                'spaceAfter' => 0
            ]
        ]
    ],
    "option"              => (object)[
        "rowheight" => 75,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => null,
                "borderRightSize"  => 1,
                "borderBottomSize" => null,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => null,
                "borderRightSize"  => 1,
                "borderBottomSize" => null,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => null,
                "borderRightSize"  => 1,
                "borderBottomSize" => null,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell4"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => null,
                "borderRightSize"  => 1,
                "borderBottomSize" => null,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing' => true,
                'align'     => 'right'
            ]
        ]
    ],
    "subtotal"            => (object)[
        "rowheight" => 500,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "bgColor"          => 'D9D9D9',
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "bgColor"          => 'D9D9D9',
                "valign"           => 'center',
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "cell2Span3"     => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "bgColor"          => 'D9D9D9',
                "valign"           => 'center',
                "borderColor"      => 'BFBFBF',
                "gridSpan"         => 3,
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'bold' => true,
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'right',
                'spaceAfter' => 0
            ]
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "bgColor"          => 'D9D9D9',
                "valign"           => 'center',
                "borderColor"      => 'BFBFBF'
            ],

            "fontStyle"      => [
                'bold' => true,
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'right',
                'spaceAfter' => 0
            ]
        ]
    ],
    "cpp"                 => (object)[
        "rowheight" => null,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => 'nospacing'
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => 'center',
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'right',
                'spaceAfter' => 0
            ]
        ],
        "cell3"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "valign"           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'right',
                'spaceAfter' => 0
            ]
        ]
    ],
    'monthlyTotal'        => (object)[
        "rowheight" => 500,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                "bgColor"          => 'D9D9D9',
                "align"            => 'right',
                "valign"           => "center",
            ],
            "purchaseTotal"  => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "bgColor"          => 'D9D9D9',
                "valign"           => 'center',
                "borderColor"      => 'BFBFBF',
            ],
            "fontStyle"      => [
                "bold" => true,
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                "align"      => 'right',
                'spaceAfter' => 0
            ]
        ],
        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "valign"           => 'center',
                "borderColor"      => 'BFBFBF',
                "bgColor"          => 'D9D9D9'
            ],
            "fontStyle"      => [
                "bold" => true,
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'right',
                'spaceAfter' => 0
            ]
        ]
    ],
    "pages"               => (object)[
        "rowheight" => 500,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                'valign'           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'right',
                'spaceAfter' => 0
            ]
        ],

        "cell2"     => (object)[
            "cellStyle"      => [
                "borderTopSize"    => 1,
                "borderRightSize"  => 1,
                "borderBottomSize" => 1,
                "borderLeftSize"   => 1,
                "borderColor"      => 'BFBFBF',
                'valign'           => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'right',
                'spaceAfter' => 0
            ]
        ]
    ],
    "signature"           => (object)[
        "rowheight" => 500,
        "cell1"     => (object)[
            "cellStyle"      => [
                "borderTopSize" => 1,
                'valign'        => 'center',
            ],
            "fontStyle"      => [
                'name' => 'Calibri',
                'size' => 11,
            ],
            "paragraphStyle" => [
                'nospacing'  => true,
                'align'      => 'center',
                'spaceAfter' => 0
            ]
        ],
        "cell2"     => (object)[
            "cellStyle"       => [
                'valign' => 'bottom',
            ],
            "fontStyle"       => [
                'name' => 'Calibri',
                'size' => 11,
                'bold' => true,
            ],
            "paragraphStyle"  => [
                'nospacing'  => true,
                'align'      => 'center',
                'spaceAfter' => 0
            ],
            "paragraphStyle2" => [
                'nospacing'  => true,
                'align'      => 'left',
                'spaceAfter' => 0
            ]
        ]
    ]
];

/**
 * Setup some styles to be used across the report
 */
$styles = (object)[
    "tables" => (object)[
        "truecosts"  => $trueCostsTable,
        "quoteTable" => $purchaseQuoteTable
    ]
];

$titledata = [
    "phpword"        => $phpword,
    "section"        => $titlepageSection,
    "quote"          => $quote,
    "styles"         => $styles,
    "dealerLogoFile" => $this->dealerLogoFile,
];

$data = [
    "phpword" => $phpword,
    "section" => $section,
    "quote"   => $quote,
    "styles"  => $styles,
];

$dealerSettingsService = new DealerSettingsService();
$dealerSettings = $dealerSettingsService->getDealerSettings(Zend_Auth::getInstance()->getIdentity()->dealerId);
if ($dealerSettings->quoteCustom) {
    $path=dirname(__FILE__).'/purchase-quote/custom/purchase-quote-'.$dealerSettings->quoteCustom.'.php';
    require ($path);
} else {
    // Actual document pages
    $this->partial("{$commonPartsBasePath}/docx/titlepage.phtml", $titledata);
    $this->partial("{$basePath}/purchasequote.phtml", $data);
    $this->partial("{$basePath}/signatures.phtml", $data);
}

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpword, 'Word2007');

try
{
    $objWriter->save($savePath);
}
catch (Exception $e)
{
    echo '<pre>';
    var_dump($e);
    die();
}
echo $this->baseUrl($linkToFile);
