<?php $quote = $this->Quote(); /* @var $quote Quotegen_Model_Quote */ ?>
<div class="row">
    <div class="span12">
        <?php foreach ($quote->getQuoteDeviceGroups() as $quoteDeviceGroup) : /* @var $quoteDeviceGroup Quotegen_Model_QuoteDeviceGroup */ ?>
            <?php if($quoteDeviceGroup->calculateTotalQuantity() > 0 ) : ?>
            <table class="table table-condensed table-bordered table-striped quoteDeviceTable">
                <tr class="header-row">
                    <th style="width: 220px;">Item</th>
                    <th style="width: 140px;">Sku</th>
                    <th>Description</th>
                    <th style="width: 80px;">Price</th>
                    <th style="width: 40px;">Qty</th>
                    <th style="width: 70px;">Subtotal</th>
                </tr>
                <?php foreach ($quoteDeviceGroup->getQuoteDeviceGroupDevices() as $quoteDeviceGroupDevice) : /* @var $quoteDeviceGroupDevice Quotegen_Model_QuoteDeviceGroupDevice */ ?>
                	<?php if($quoteDeviceGroupDevice->getQuantity() > 0) :?>
	                    <tr class="deviceRow">
							<th><h5><?php echo $quoteDeviceGroupDevice->getQuoteDevice()->name; ?></h5></th>
	                    	<td><?php echo $quoteDeviceGroupDevice->getQuoteDevice()->oemSku; ?></td>
	                    	<td></td>           
	                    	<td style="text-align: right;"><?php echo $this->currency($quoteDeviceGroupDevice->getQuoteDevice()->calculatePackagePrice()); ?></td>
	                    	<td style="text-align: right;"><?php echo number_format($quoteDeviceGroupDevice->getQuantity()); ?></td>
	                    	<td style="text-align: right;"><?php echo $this->currency($quoteDeviceGroupDevice->getQuoteDevice()->calculateTotalPrice()); ?></td>
	                    </tr>
	                    <?php if (count($quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions() > 0)) : ?>
	                        <?php foreach ($quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions() as $quoteDeviceOption) : /* @var $quoteDeviceOption Quotegen_Model_QuoteDeviceOption */ ?>
	                            <tr class="optionRow">
	                                <td><?php echo $quoteDeviceOption->getName(); ?></td>
	                                <td><?php echo $quoteDeviceOption->getOemSku(); ?></td>
	                                <td><?php echo $quoteDeviceOption->getDescription(); ?></td>
	                                <td></td>
	                                <td></td>
	                                <td></td>
	                            </tr>
	                        <?php endforeach; ?>
	                    <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <tr>
                    <td colspan="5"></td>
                    <th style="text-align: right;"><?php echo $this->currency($quoteDeviceGroup->calculateGroupSubtotal()); ?></th>
                </tr>
            </table>
			<?php endif; ?>
        <?php endforeach; ?>
        <div class='pull-right'>
        	<h3>Quote Total: <?php echo $this->currency($quote->calculateQuoteSubtotal()); ?></h3>
        </div>
    </div>
</div>
