<?php
/* @var $assessmentViewModel Assessment_ViewModel_Assessment */
$assessmentViewModel = $this->assessmentViewModel;
$costPerPageSettings = $assessmentViewModel->getCostPerPageSettingForCustomer();
$reportMargin = $assessmentViewModel->assessment->getAssessmentSettings()->assessmentReportMargin;
$totalDeviceCount = number_format(count($assessmentViewModel->getDevices()->allIncludedDeviceInstances));
?>
<style>

    .debugReportTable {
        font-size : 12px;
    }

    .debugTable thead tr {
        background-color : #333;
        color            : #fff;
    }

    .debugNumber {
        vertical-align : middle ! important;
        text-align     : right ! important;
    }
</style>
<h1>Report Parameters</h1>
<table class="table-striped table-bordered debugTable debugReportTable">
    <thead>
    <tr>
        <th style="width: 200px">Parameter</th>
        <th style="width: 100px">Value</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Report Margin</td>
        <td><?php echo number_format($assessmentViewModel->assessment->getAssessmentSettings()->assessmentReportMargin); ?>%</td>
    </tr>
    <tr>
        <td>Monochrome Page Coverage</td>
        <td><?php echo number_format($assessmentViewModel->assessment->getSurvey()->pageCoverageMonochrome); ?>%</td>
    </tr>
    <tr>
        <td>Color Page Coverage</td>
        <td><?php echo number_format($assessmentViewModel->assessment->getSurvey()->pageCoverageColor); ?>%</td>
    </tr>

    <tr>
        <td>Cost Of Ink And Toner (Monthly)</td>
        <td><?php echo $this->currency($assessmentViewModel->getCostOfInkAndTonerMonthly($assessmentViewModel->getCostPerPageSettingForCustomer())); ?></td>
    </tr>
    <tr>
        <td>Cost Of Ink And Toner (Yearly)</td>
        <td><?php echo $this->currency($assessmentViewModel->getCostOfInkAndToner($assessmentViewModel->getCostPerPageSettingForCustomer())); ?></td>
    </tr>
    </tbody>
</table>
<h1>Purchased Devices
    <small><?php echo number_format(count($assessmentViewModel->getDevices()->purchasedDeviceInstances)) ?> out of <?php echo $totalDeviceCount; ?>devices
    </small>
</h1>
<table class="table table-striped table-bordered debugTable debugReportTable">
    <thead>
    <tr>
        <th style="width: 100px;">Device</th>
        <th style="width: 70px;">AMPV Mono</th>
        <th style="width: 70px;">AMPV Color</th>
        <th style="width: 60px;">Base Black CPP</th>
        <th style="width: 60px;">Base Black CPP w/ Margin</th>
        <th style="width: 60px;">Base Color CPP</th>
        <th style="width: 60px;">Base Color CPP w/ Margin</th>
        <th style="width: 70px;">Monthly Cost Of Ink And Toner</th>
        <th style="">Toners</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $totalBlackPages = 0;
    $totalColorPages = 0;
    $totalMonthlyInkAndToner = 0;
    ?>
    <?php foreach ($assessmentViewModel->getDevices()->purchasedDeviceInstances->getDeviceInstances() as $deviceInstance) : ?>
        <?php
        $totalBlackPages += $deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly();
        $totalColorPages += $deviceInstance->getPageCounts()->getColorPageCount()->getMonthly();
        $totalMonthlyInkAndToner += $deviceInstance->getCostOfInkAndToner($costPerPageSettings);
        ?>
        <tr>
            <td><?php echo $deviceInstance->getDeviceName(); ?></td>
            <td class="debugNumber"><?php echo number_format($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td class="debugNumber"><?php echo ($deviceInstance->getMasterDevice()->isColor()) ? number_format($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : ""; ?></td>
            <td class="debugNumber"><?php echo $this->currency((float)$deviceInstance->calculateCostPerPage($costPerPageSettings)->getCostOfInkAndTonerPerPage()->monochromeCostPerPage, array("precision" => 4)); ?></td>
            <td class="debugNumber"><?php echo $this->currency((float)Tangent_Accounting::applyMargin($deviceInstance->calculateCostPerPage($costPerPageSettings)->getCostOfInkAndTonerPerPage()->monochromeCostPerPage, $reportMargin), array("precision" => 4)); ?></td>
            <td class="debugNumber"><?php echo ($deviceInstance->getMasterDevice()->isColor()) ? $this->currency((float)$deviceInstance->calculateCostPerPage($costPerPageSettings)->getCostOfInkAndTonerPerPage()->colorCostPerPage, array("precision" => 4)) : ""; ?></td>
            <td class="debugNumber"><?php echo ($deviceInstance->getMasterDevice()->isColor()) ? $this->currency((float)Tangent_Accounting::applyMargin($deviceInstance->calculateCostPerPage($costPerPageSettings)->getCostOfInkAndTonerPerPage()->colorCostPerPage, $reportMargin), array("precision" => 4)) : ""; ?></td>
            <td class="debugNumber"><?php echo $this->currency((float)$deviceInstance->getCostOfInkAndToner($costPerPageSettings), array("precision" => 2)); ?></td>
            <td>
                <table class="table-bordered table-condensed debugTable">
                    <thead>
                    <tr>
                        <th style="width: 50px;">Color</th>
                        <th style="width: 40px;">Yield</th>
                        <th style="width: 60px;">Price</th>
                        <th style="width: 60px;">Black CPP</th>
                        <th style="width: 60px;">Color CPP</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($deviceInstance->getMasterDevice()->getTonersForAssessment($assessmentViewModel->getCostPerPageSettingForCustomer()) as $tonerColor => $toner) : ?>
                        <tr>
                            <td><?php echo Proposalgen_Model_TonerColor::$ColorNames[$tonerColor]; ?></td>
                            <td class="debugNumber"><?php echo number_format($toner->yield); ?></td>
                            <td class="debugNumber"><?php echo $this->currency((float)$toner->cost); ?></td>
                            <td class="debugNumber"><?php echo $this->currency((float)$toner->calculateCostPerPage($costPerPageSettings)->monochromeCostPerPage, array("precision" => 4)); ?></td>
                            <td class="debugNumber"><?php echo $this->currency((float)$toner->calculateCostPerPage($costPerPageSettings)->colorCostPerPage, array("precision" => 4)); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tbody>
    <tr>
        <th></th>
        <th class="debugNumber"><?php echo number_format((float)$totalBlackPages); ?></th>
        <th class="debugNumber"><?php echo number_format((float)$totalColorPages); ?></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th class="debugNumber"><?php echo $this->currency((float)$totalMonthlyInkAndToner); ?></th>
        <th></th>
    </tr>
    </tbody>
</table>
<h1>Leased Devices
    <small><?php echo number_format(count($assessmentViewModel->getDevices()->leasedDeviceInstances)) ?> out of <?php echo $totalDeviceCount; ?> devices</small>
</h1>

<table class="table table-striped table-bordered debugTable debugReportTable">
    <thead>
    <tr>
        <th style="width: 250px;">Device</th>
        <th style="width: 70px;">AMPV Mono</th>
        <th style="width: 70px;">AMPV Color</th>
        <th>N/A</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $totalBlackPages = 0;
    $totalColorPages = 0;
    $totalMonthlyInkAndToner = 0;
    ?>
    <?php foreach ($assessmentViewModel->getDevices()->leasedDeviceInstances as $deviceInstance) : ?>
        <?php
        $totalBlackPages += $deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly();
        $totalColorPages += $deviceInstance->getPageCounts()->getColorPageCount()->getMonthly();
        ?>
        <tr>
            <td><?php echo $deviceInstance->getDeviceName(); ?></td>
            <td class="debugNumber"><?php echo number_format($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()); ?></td>
            <td class="debugNumber"><?php echo ($deviceInstance->getMasterDevice()->isColor()) ? number_format($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : ""; ?></td>
            <td></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tbody>
    <tr>
        <th></th>
        <th class="debugNumber"><?php echo number_format((float)$totalBlackPages); ?></th>
        <th class="debugNumber"><?php echo number_format((float)$totalColorPages); ?></th>
        <th></th>
    </tr>
    </tbody>
</table>