<?php
/* @var $form Quotegen_Form_Quote_Group */
$form = $this->element;
$addDeviceToGroupSubform = $form->getSubForm('addDeviceToGroup');
$deviceQuantitySubform = $form->getSubForm('deviceQuantity');
$addGroupSubform = $form->getSubForm('addGroup');

$deleteDeviceButton = $deviceQuantitySubform->getElement('deleteDeviceFromGroup');

// Get elements in the form
$deviceElement = $addDeviceToGroupSubform->getElement('quoteDeviceId');
$quantityElement = $addDeviceToGroupSubform->getElement('quantity');
$groupElement = $addDeviceToGroupSubform->getElement('quoteDeviceGroupId');
?>

<form id="<?php echo $form->getId(); ?>" class='<?php echo $form->getAttrib('class') ?>' action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>" name="<?php echo $form->getName() ?>">
    <table>
        <tr>
            <td><?php echo $addDeviceToGroupSubform->getElement('addDevice'); ?></td>
            <td><?php echo $quantityElement; ?></td>
            <td> of the</td>
            <td><?php echo $deviceElement; ?></td>
            <td> device to the</td>
            <td><?php echo $groupElement; ?></td>
            <td> group.</td>
        </tr>
    </table>
    <br />
    <?php echo $addGroupSubform->getElement('addGroup'); ?>
    <?php echo $addGroupSubform->getElement('name'); ?>
    <br />

    <?php /* @var $deviceGroup Quotegen_Model_QuoteDeviceGroup */
    $deviceGroups = $form->getQuote()->getQuoteDeviceGroups(); ?>
    <?php foreach ($deviceGroups as $deviceGroup) : ?>
        <h3><?php echo $form->getElement("groupName_{$deviceGroup->id}") ?>
            <?php if (!$deviceGroup->isDefault) : ?>
                <small>
                    <button type="submit" name="deleteGroup" class="btn btn-danger btn-mini" value="<?php echo $deviceGroup->id ?>">
                        <i class="icon-trash"></i>
                    </button>
                </small>
            <?php endif; ?>
        </h3>
        <table class='table table-bordered table-striped table-condensed'>
            <tr>
                <th style='width: 200px'>Device</th>
                <th>SKU</th>
                <th> Option SKU's</th>
                <th style='width: 150px'>Quantity</th>
                <th style='width: 30px'></th>
            </tr>
            <?php $quoteDeviceGroupDevices = $deviceGroup->getQuoteDeviceGroupDevices(); ?>
            <?php /* @var $quoteDeviceGroupDevice Quotegen_Model_QuoteDeviceGroupDevice */
            foreach ($quoteDeviceGroupDevices as $quoteDeviceGroupDevice) : ?>
                <tr>
                    <td><?php echo $quoteDeviceGroupDevice->getQuoteDevice()->name ?></td>
                    <td><?php echo $quoteDeviceGroupDevice->getQuoteDevice()->oemSku ?></td>
                    <td>
                        <?php if (count($quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions()) > 0) : ?>
                            <?php
                            $optionList = array();
                            /* @var $quoteDeviceOption Quotegen_Model_QuoteDeviceOption */
                            foreach ($quoteDeviceGroupDevice->getQuoteDevice()->getQuoteDeviceOptions() as $quoteDeviceOption)
                            {
                                $optionList [] = "{$quoteDeviceOption->oemSku} (x{$quoteDeviceOption->quantity})";
                            }
                            echo implode($optionList, ", ");
                            ?>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $deviceQuantitySubform->getElement("quantity_{$quoteDeviceGroupDevice->quoteDeviceGroupId}_{$quoteDeviceGroupDevice->quoteDeviceId}"); ?></td>
                    <td>
                        <button type="submit" name="deleteDeviceFromGroup" value="<?php echo "{$quoteDeviceGroupDevice->quoteDeviceId}_{$quoteDeviceGroupDevice->quoteDeviceGroupId}" ?>" class="btn btn-danger btn-mini">
                            <i class="icon-trash"></i></button>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
    <?php endforeach ?>

    <?php echo $form->getDisplayGroup('actions')->render(); ?>
</form>