<?php $this->headScript()->captureStart('append','text/javascript'); ?>

    var adminEdit                   = '<?php echo $this->adminEdit; ?>';
    var callOnChangePrinterModel    = '<?php echo $this->changePrinterModel ?>';
    var colorList                   = "<?php echo $this->tonerColorList; ?>";
    var form_mode                   = '<?php echo $this->form_mode; ?>';
    var partTypeList                = '<?php echo $this->partTypeList; ?>';
    var repop                       = '<?php echo $this->repop; ?>';
    var selectedPrinterModel        = '<?php echo $this->printer_model; ?>';
    var manufacturerList            = "<?php echo $this->escape($this->manufacturers); ?>";
    var partTypeList                = '<?php echo $this->partTypeList; ?>';

<?php $this->headScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/proposalgen/managedevices/managemappingdevices.js')); ?>
<div class="page-header">
    <h1>Manage Printers and Toners</h1>
</div>
<div id="form_container">
	
		<div id="lightbox-panel" class="new_manufacturer_container">
		
			<div id="toners_form" style="display: block;">
    			<form name="frmToners" id="frmToners" action="" method="post">
    				<input type="hidden" name="replace_mode" id="replace_mode" value="" />
    				<input type="hidden" name="replace_toner_id" id="replace_toner_id" value="" />
    				<input type="hidden" name="with_toner_id" id="with_toner_id" value="" />
    				
    				<h3 id="replacement_title" style="display: inline;"></h3>
    				<p id="replacement_toners_statement" style="margin: 20px 0 10px 0;"></p>
    				<div id="replacement_message" class="warning"></div>
    				
    				<div id="replacement_toners_container">
        				<div style="text-align: center; margin: 20px 0 10px 0;">

                			<div id="replacement_filter_container">
                				<div id="replacement_criteria_container" style="display: inline; padding: 0;">
                					<label for="replacement_criteria_filter" class="details_label">Filter:</label>
                					<select name="replacement_criteria_filter" id="replacement_criteria_filter" class="filter_dropdown" style="width: 100px; margin: 0px 0px 0px 10px;">
                						<option value="toner_SKU">SKU</option>
                						<option value="manufacturer_name">Manufacturer</option>
                						<option value="type_name">Type</option>
                						<option value="toner_color_name">Color</option>
                						<option value="toner_yield">Yield</option>
                					</select>
                					<label for="replacement_txtCriteria" class="details_label" style="padding: 0 3px 0 5px;">for</label>
                					<span id="replacement_text_criteria"><input type="text" name="replacement_txtCriteria" id="replacement_txtCriteria" style="width: 100px;" /></span>
                					<span id="replacement_list_criteria" style="display: none;"><select name="replacement_cboCriteria" id="replacement_cboCriteria" style="width: 100px;"></select></span>
                					<input type="button" name="replacement_btnSearch" id="replacement_btnSearch" value="Search" onclick=" update_replacement('search');" />
                					<input type="button" name="replacement_btnClearSearch" id="replacement_btnClearSearch" value="Clear" onclick=" update_replacement('clear');" />
                				</div>
                			</div>
            			
                			<table id="replacement_toners_list"></table>
                			<div id="replacement_toners_pager"></div>
        				</div>
        				<div id="replace_all_container" style="text-align: center; margin: 10px 0 10px 0;">
        					<input type="checkbox" name="chkAllToners" id="chkAllToners" value="1" />
        					<label for="chkAllToners">Apply to all devices using this toner.</label>
        				</div>
        			</div>
        			
    				<div style="text-align: center; margin: 20px 0 0 0;">
            			<input type="button" name="btnReplaceToner" id="btnReplaceToner" value="Submit" onclick="do_action('replace_toner');" />
            			<input type="button" name="btnClose" id="btnClose" value="Cancel" onclick="$('#replacement_toners_statement').html(''); lightbox('hide');" />
    				</div>
    			</form>
			</div>
			
		</div>
		
		<div id="message_container" style="margin: 10px 0 20px 0;">
			<p><?php echo $this->message; ?></p>
		</div>
		
		<div id="device_container">
			<h3 style="display: inline;">Printer:</h3>
			<br /><br />
			<p><strong>* indicates a required field</strong><p>
			<div class="well">
			<?php echo $this->deviceform; ?>
			</div>
		</div>
			
		<div id="applied_toners_container">
			<h3 class="margined"><span id="devicename">Toner Assignment:</span></h3>
			<p id="toner_instruction" style="display: none;">
				You may only have <span id="toner_instruction_config"></span> assigned to this device.
			</p>
			<table id="applied_toners_list"></table>
			<div id="applied_toners_pager"></div>
		</div>
			
		<br />
		
		<div id="available_toners_container" style="margin-top: 20px;">
			<h3 class="margined">Available Toners:</h3>
			
			<div id="filter_container" class="well">
				<div id="criteria_container" style="display: inline; padding: 0; margin: 0;">
					<label for="criteria_filter" class="details_label" style="display: inline; padding: 0; margin: 0 10px 0 0;">Filter:</label>
					<select name="criteria_filter" id="criteria_filter" class="filter_dropdown" style="width: 180px; margin: 0;">
						<option value="toner_SKU">SKU</option>
						<option value="manufacturer_name">Manufacturer</option>
						<option value="type_name">Type</option>
						<option value="toner_color_name">Color</option>
						<option value="toner_yield">Yield</option>
					</select>
					<label for="txtCriteria" class="details_label" style="display: inline; padding: 0; margin: 0 10px 0 10px;">for</label>
					<span id="text_criteria"><input type="text" name="txtCriteria" id="txtCriteria" style="width: 180px; margin: 0 0 0 0;" /></span>
					<span id="list_criteria" style="display: none;"><select name="cboCriteria" id="cboCriteria" style="width: 180px;"></select></span>
					<input type="button" name="btnSearch" id="btnSearch" value="Search" onclick="update_available('search');" class="btn" />
					<input type="button" name="btnClearSearch" id="btnClearSearch" value="Clear" onclick=" update_available('clear');" class="btn" />
				</div>
			</div>
			
			<div id="modal_message_container" style="margin: 10px 0 20px 0;">
				<?php echo $this->message; ?>
			</div>
			<table id="available_toners_list"></table>
			<div id="available_toners_pager"></div>
		</div>	
		
		<br />
		
		<div id="submitBtns" class="submitBar">
			<input type="button" name="btnSave" id="btnSave" value="Save" onclick="do_action('save');" class="btn btn-primary" />
			<input type="button" name="btnDone" id="btnDone" value="Done" onclick="do_action('done');" class="btn" />
		</div>
	<br />
</div>