<?php
/**
 * Cost Analysis - Main Table
 *
 * This script contains everything for the main table of the cost analysis.
 */
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $proposal Assessment_ViewModel_Assessment */
$proposal = $this->proposal;

/**
 * Variables
 */
// Add any variables that are needed throughout the page here.


/**
 * Section starts here
 */
// You would normally put this here if you needed it but in the cost analysis we do not need it.
// $section->addPageBreak();

$tcStyle = $this->styles->tables->includeTable;

// Included Table header
$table = $section->addTable($tcStyle->tablestyle);
$table->addRow($tcStyle->header->rowheight, $tcStyle->header->fontStyle);
$table->addCell($tcStyle->col1Width, $tcStyle->header->cell)->addText($this->translate('Manufacturer'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col2Width, $tcStyle->header->cell)->addText($this->translate('Model'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col3Width, $tcStyle->header->cell)->addText($this->translate('IP Address'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col3Width, $tcStyle->header->cell)->addText($this->translate('Serial No.'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col4Width, $tcStyle->header->cell)->addText($this->translate('Purchased or Leased'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col5Width, $tcStyle->header->cell)->addText($this->translate('AMPV'), $tcStyle->header->fontStyle, $tcStyle->centeralign);
$table->addCell($tcStyle->col6Width, $tcStyle->header->cell)->addText($this->translate('JIT Compatible'), $tcStyle->header->fontStyle, $tcStyle->centeralign);

foreach($proposal->getDevices()->allIncludedDeviceInstances as $deviceInstance) /* @var $deviceInstance Proposalgen_Model_DeviceInstance */ {
    $table->addRow($tcStyle->cell->rowheight);
    $table->addCell($tcStyle->col2Width, $tcStyle->row->cell)->addText($deviceInstance->getMasterDevice()->getManufacturer()->fullname, $tcStyle->row->fontStyle, $tcStyle->leftalign);
    $table->addCell($tcStyle->col2Width, $tcStyle->row->cell)->addText($deviceInstance->getMasterDevice()->modelName, $tcStyle->row->fontStyle, $tcStyle->leftalign);
    $table->addCell($tcStyle->col2Width, $tcStyle->row->cell)->addText(($deviceInstance->ipAddress) ? $deviceInstance->ipAddress : "Unknown", $tcStyle->row->fontStyle, $tcStyle->centeralign);
    $table->addCell($tcStyle->col2Width, $tcStyle->row->cell)->addText(($deviceInstance->serialNumber) ? $deviceInstance->serialNumber : "Unknown", $tcStyle->row->fontStyle, $tcStyle->centeralign);
    $table->addCell($tcStyle->col2Width, $tcStyle->row->cell)->addText(($deviceInstance->getMasterDevice()->isLeased) ? "Leased" : "Purchased", $tcStyle->row->fontStyle, $tcStyle->centeralign);
    $table->addCell($tcStyle->col2Width, $tcStyle->row->cell)->addText(number_format($deviceInstance->getAverageMonthlyPageCount()), $tcStyle->row->fontStyle, $tcStyle->rightalign);
    $table->addCell($tcStyle->col2Width, $tcStyle->row->cell)->addText(($deviceInstance->isCapableOfReportingTonerLevels()) ? "Yes" : "No", $tcStyle->row->fontStyle, $tcStyle->centeralign);
}

