<div class="page-header">
    <h1>Hardware Quote Devices -
        <small>Option Categories</small>
    </h1>
</div>
<div class="clearfix">
    <a class="btn btn-success pull-right btn-small create-button" href="<?php echo $this->url(array('action' => 'create')) ?>">
        <i class="icon-white icon-plus-sign"></i> Create new</a>
</div>
<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
    <table class="table table-striped table-condensed table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th style="width: 120px;">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($this->paginator->getCurrentItems() as $categories) : /* @var $categories Quotegen_Model_Category */ ?>
            <tr>
                <td><?php echo $categories->name; ?></td>
                <td><?php echo $categories->description; ?></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-info" title="View" href="<?php echo $this->url(array('action' => 'view', 'id' => $categories->id)); ?>"><i class="icon-eye-open"></i></a>
                        <a class="btn btn-warning" title="Edit" href="<?php echo $this->url(array('action' => 'edit', 'id' => $categories->id)); ?>"><i class="icon-pencil"></i></a>
                        <a class="btn btn-danger" title="Delete" href="<?php echo $this->url(array('action' => 'delete', 'id' => $categories->id)); ?>"><i class="icon-trash"></i></a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
    <div class='well'>
        <h1>There are no categories</h1>
    </div>
<?php endif; ?>

