<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
<h1> Category Settings </h1>
<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th style="width: 120px;">Action</th>
        </tr>
    </thead>
    <tbody>
    	
        <?php foreach ($this->paginator->getCurrentItems() as $categories) : /* @var $categories Quotegen_Model_Category */ ?>
        <tr>
            <td><?php echo $categories->getName(); ?></td>
            <td><?php echo $categories->getDescription(); ?></td>
            <td>
                <div class="btn-group">
                	<a class="btn btn-info" title="View Client" href="<?php echo $this->url( array ( 'action' => 'view', 'id' => $categories->getId())); ?>"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-warning" title="Edit Client" href="<?php echo $this->url(array ( 'action' => 'edit', 'id' => $categories->getId())); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-danger" title="Delete Client" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' => $categories->getId())); ?>"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
<div class='well'>
    <h1>There are no categories</h1>
</div>
<?php endif; ?>

