<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\CategoryModel;

?>
<div class="container">
    <div class="clearfix">
        <a class="btn btn-success pull-right btn-sm create-button" href="<?= $this->url([], 'quotes.category-options.create') ?>">
            <i class="glyphicon glyphicon-plus-sign"></i> Create new</a>
    </div>
    <?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
        <table class="table table-striped table-condensed table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th style="width: 120px;">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $categories CategoryModel */ ?>
            <?php foreach ($this->paginator->getCurrentItems() as $categories) : ?>
                <tr>
                    <td><?= $categories->name; ?></td>
                    <td><?= $categories->description; ?></td>
                    <td>
                        <div class="btn-group btn-group-justified btn-group-xs">
                            <a class="btn btn-info" title="View" href="<?= $this->url(['id' => $categories->id], 'quotes.category-options.view'); ?>"><i class="glyphicon glyphicon-eye-open"></i></a>
                            <a class="btn btn-warning" title="Edit" href="<?= $this->url(['id' => $categories->id], 'quotes.category-options.edit'); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                            <a class="btn btn-danger" title="Delete" href="<?= $this->url(['id' => $categories->id], 'quotes.category-options.delete'); ?>"><i class="glyphicon glyphicon-trash"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?= $this->paginationControl($this->paginator); ?>
    <?php else : ?>
        <div class='well'>
            <h1>There are no categories</h1>
        </div>
    <?php endif; ?>
</div>