<?php
/**
 * Solution - Let Office Depot Take Care of Your Business Print
 */
/* @var $section PHPWord_Section */
$section = $this->section;

/* @var $proposal Assessment_ViewModel_Assessment */
$proposal = $this->proposal;

$section->addPageBreak();
$section->addTitle($this->translate('Let Office Depot Take Care of Your Business Print'), 1);
$section->addText($this->translate('With Office Depot as your single point of contact for your office printing needs, your business will be taken care of:'));

$section->addTitle($this->translate('Just-in-Time Supplies'), 2);
$section->addText($this->translate('Office Depot monitors your supplies levels and ships toner immediately through our world class logistics and distribution network. This allows you to reduce the amount of cash held in supplies inventory, and increase uptime by always having the right supplies when you need them. Remember, sourcing and delivering supplies is our core business.'));

$section->addTitle($this->translate('Proactive Maintenance and Service'), 2);
$section->addText($this->translate('Office Depot provides same-day support for service and printer maintenance, and under the PrintIQ program, all of your parts and labor are included (maintenance kits, fusers, etc.). We provide next-day repair for all printing devices under your managed print services contract so your IT staff will be free from handling printer-related issues.'));

$section->addTitle($this->translate('Cost Control and Business Intelligence Reporting'), 2);
$section->addText($this->translate('Under the PrintIQ and PrintIQ Plus programs, you\'ll have a single contact and receive one monthly invoice for all of your managed print services. Now you can easily predict and budget for your printing expenses.'));

$section->addTitle($this->translate('Eco Smart Solutions'), 2);
$section->addText($this->translate('Office Depot was recognized by Newsweek as the No. 1 Green Retailer. Our eco-preferable initiatives include recycling programs for supplies and equipment, and product lines of refurbished printers and remanufactured supplies. Through our managed print services program, we can help you determine which inefficient devices should be removed and if duplex, scanning and secure-print features should be implemented to reduce paper waste.'));

$section->addTitle($this->translate('Your Total Print Solution'), 2);
$section->addText($this->translate('With Office Depot, you get more than managed print services. Leverage our Copy & Print Depot locations for large or multiple print jobs. E-mail files to Copy & Print Depot for same-day pickup, delivery, or to ship to multiple locations. Use our digital file cabinet to store files on our secure server for staff or customers to access and print on demand. We also offer commercial printing, large format printing, banner printing, custom printing, and have a variety of finishing capabilities for all of your office printing needs.'));

$section->addTitle($this->translate('Flexible Options'), 2);
$section->addText($this->translate('From day-to-day management of your office print to leveraging your existing assets or choosing to obtain new hardware on a flat-rate program, Office Depot provides a variety of options that enable you to maintain your flexibility as your needs change.'));
