<?php
/* @var $phpword \PhpOffice\PhpWord\PhpWord */
use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\QuoteModel;

$phpword = $this->phpword;

/* @var $quote QuoteModel */
$quote = $this->quote;

/* @var $section \PhpOffice\PhpWord\Element\Section */
$section = $this->section;
$client  = $quote->getClient();

// Table to fix the issue of images being different sizes
$imageTable = $section->addTable([]);
$imageTable->addRow(5760);
$cell = $imageTable->addCell(9028.8, [
    'valign' => 'center'
]);

$cell->addImage(PUBLIC_PATH . $this->dealerLogoFile, [
    'align' => 'center'
]);

/**
 * Main title
 */
$section->addTextBreak();
$section->addText($this->translate(''), null, 'titleStyle2');
$section->addText($this->translate(My_Brand::getDealerBranding()->shortDealerName . ' Hardware Quote'), 'titlepage_title', 'titleStyle2');
$section->addText($this->translate(''), null, 'titleStyle2');

/**
 * Prepared For: Company Name
 */
$section->addTextBreak();
$section->addText('', 'titlepage_address', 'titleStyle3');
$section->addText("\t" . sprintf($this->translate('Prepared For: %1$s'), $client->companyName), 'titlepage_subtitle', 'titleStyle3');

/**
 * Address
 */
$addressLines = explode("\n", $client->getAddress()->getFullAddressMultipleLines());
$addressCount = 1;
foreach ($addressLines as $line)
{
    $section->addText("\t" . $line, 'titlepage_address', 'titleStyle3');
    $addressCount++;
}

// Add blank lines to fill up the page with yummy greyness
if ($addressCount < 11)
{
    for ($i = 0; $i < 11 - $addressCount; $i++)
    {
        $section->addText('', 'titlepage_address', 'titleStyle3');
    }
}
