<?php
/**
 * Assessment Title Page
 */
/* @var $phpword PHPWord */
$phpword = $this->phpword;
/* @var $quote Quotegen_Model_Quote */
$quote = $this->quote;

/* @var $section PHPWord_Section */
$titlepage       = $this->section;
$titleImageStyle = array(
    'align' => 'center'
);

// Table to fix the issue of images being different sizes
$imageTable = $titlepage->addTable(array(
                                        'borderBottomSize' => 1
                                   ));
$imageTable->addRow(5760);
$cell = $imageTable->addCell(9028.8, array(
                                          'valign' => 'center'
                                     ));
$cell->addImage(PUBLIC_PATH . "/themes/default/proposalgenerator/reports/images/mpstoolbox_logo.jpg", array(
                                                                                                           'align' => 'center'
                                                                                                      ));

$titlepage->addTextBreak();
// Assessment Title
$titlepage->addText($this->translate(''), null, 'titleStyle2');
$titlepage->addText($this->translate('  MPSToolbox.com Hardware Quote'), 'titlepage_title', 'titleStyle2');
$titlepage->addText($this->translate(''), null, 'titleStyle2');


$client = $quote->getClient();

$titlepage->addTextBreak();

$titlepage->addText(' ', 'titlepage_address', 'titleStyle3');
$titlepage->addText(sprintf($this->translate('Prepared For: %1$s'), $client->companyName), 'titlepage_subtitle', 'titleStyle3');

// Parse the address
$addressLines = explode("\n", $client->getAddress()->getFullAddressMultipleLines());
$addressCount = 1;
foreach ($addressLines as $line)
{
    $titlepage->addText($line, 'titlepage_address', 'titleStyle3');
    $addressCount++;
}