<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>

<div class="clearfix">
    <h1>Device Configurations</h1>
    <a class="btn btn-success btn-small pull-right create-button" href="<?php echo $this->url(array('action' => 'create')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
</div>

<div>
	<table class="table table-striped table-condensed table-bordered">
	    <thead>
	        <tr>
	            <th style="width: 200px;">Master Device</th>
	            <th style="width: 150px;">Configuration</th>
	            <th style="">Description</th>
	            <th style="width: 100px; text-align: center;">Action</th>
	        </tr>
	    </thead>
	    <tbody>
	        <?php foreach ($this->paginator->getCurrentItems() as $deviceConfiguration) : /* @var $deviceConfiguration Quotegen_Model_DeviceConfiguration */ ?>
	        <tr>
	            <td><?php echo $deviceConfiguration->getDevice()->getMasterDevice()->getFullDeviceName(); ?></td>
	            <td><?php echo $deviceConfiguration->getName(); ?></td>
	            <td><?php echo $deviceConfiguration->getDescription(); ?></td>
	            <td>
	                <div class="" style="text-align: center;">
	                    <a class="btn btn-warning btn-mini" title="Edit Configuration" href="<?php echo $this->url( array ( 'action' => 'edit', 'configurationid' => $deviceConfiguration->getId())); ?>"><i class="icon-pencil icon-white"></i></a>
	                    <a class="btn btn-danger btn-mini" title="Delete Configuration" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' => $deviceConfiguration->getId())); ?>"><i class="icon-trash icon-white"></i></a>
	                </div>
	            </td>
	        </tr>
	        <?php endforeach; ?>
	    </tbody>
	</table>
	<?php echo $this->paginationControl($this->paginator); ?>
</div>

<?php else : ?>

<div class='well'>
	<a class="btn btn-success btn-small pull-right" href="<?php echo $this->url(array('action' => 'create')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
	<h4>There are no device configurations</h4>	
</div>

<?php endif; ?>
