<?php

use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\DeviceConfigurationModel;

?>
<div class="container">
    <?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>

        <div class="clearfix">
            <a class="btn btn-success btn-sm pull-right create-button" href="<?= $this->url([], 'quotes.configurations.create') ?>">
                <i class="glyphicon glyphicon-plus-sign"></i> Create new</a>
        </div>

        <div>
            <table class="table table-striped table-condensed table-bordered">
                <thead>
                <tr>
                    <th style="width: 200px;">Master Device</th>
                    <th style="width: 150px;">Configuration</th>
                    <th>Description</th>
                    <th style="width: 100px; text-align: center;">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php /* @var $deviceConfiguration DeviceConfigurationModel */ ?>
                <?php foreach ($this->paginator->getCurrentItems() as $deviceConfiguration) : ?>
                    <tr>
                        <td><?= $deviceConfiguration->getDevice()->getMasterDevice()->getFullDeviceName(); ?></td>
                        <td><?= $deviceConfiguration->name; ?></td>
                        <td><?= $deviceConfiguration->description; ?></td>
                        <td>
                            <div class="" style="text-align: center;">
                                <a class="btn btn-warning btn-xs" title="Edit Configuration" href="<?= $this->url(['configurationid' => $deviceConfiguration->id], 'quotes.configurations.edit'); ?>">
                                    <i class="glyphicon glyphicon-pencil icon-white"></i></a>
                                <a class="btn btn-danger btn-xs" title="Delete Configuration" href="<?= $this->url(['configurationid' => $deviceConfiguration->id], 'quotes.configurations.delete'); ?>">
                                    <i class="glyphicon glyphglyphicon glyphicon-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?= $this->paginationControl($this->paginator); ?>
        </div>

    <?php else : ?>
        <a class="btn btn-success btn-sm pull-right" href="<?= $this->url([], 'quotes.configurations.create') ?>">
            <i class="glyphicon glyphicon-plus-sign"></i> Create new</a>
        <h4>There are no device configurations</h4>
    <?php endif; ?>
</div>