<div class="page-header">
        <h1>Clients - <small>Client Management</small></h1>
</div>
<div class="clearfix">
    <a class="btn btn-success pull-right btn-small create-button" href="<?php echo $this->url(array('action' => 'create')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
</div>
<?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>
            <th style="width: 30px;">ID</th>
            <th>Company Name</th>
            <th>Legal Name</th>
            <th>Dealer Name</th>
            <th style="width: 120px;">Action</th>
        </tr>
    </thead>
    <tbody>
    	
        <?php foreach ($this->paginator->getCurrentItems() as $client) : /* @var $client Quotegen_Model_Client */ ?>
        <tr>
            <td><?php echo $this->escape($client->id); ?></td>
            <td><?php echo $this->escape($client->companyName); ?></td>
            <td><?php echo $this->escape($client->legalName); ?></td>
            <td><?php echo $this->escape(Admin_Model_Mapper_Dealer::getInstance()->find($client->dealerId)->dealerName); ?></td>
            <td>
                <div class="btn-group">
	                <a class="btn btn-info" title="View" href="<?php echo $this->url( array ( 'action' => 'view', 'id' => $client->id)); ?>"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-warning" title="Edit" href="<?php echo $this->url( array ( 'action' => 'edit', 'id' => $client->id)); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-danger" title="Delete" href="<?php echo $this->url(array ( 'action' => 'delete', 'id' => $client->id)); ?>"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator); ?>
<?php else : ?>
<div class='well'>
    <h1>There are no clients</h1>
</div>
<?php endif; ?>

