<?php

use MPSToolbox\Legacy\Mappers\DealerMapper;
use MPSToolbox\Legacy\Modules\QuoteGenerator\Models\ClientModel;

?>
<div class="container">
    <div class="clearfix">
        <a class="btn btn-success pull-right btn-sm create-button" href="<?= $this->url(array(), 'admin.clients.create') ?>">
            <i class="glyphicon glyphicon-plus-sign"></i> Create new</a>
    </div>
    <?php if (isset($this->paginator) && $this->paginator->count() > 0) : ?>
        <table class="table table-striped table-condensed table-bordered">
            <thead>
            <tr>
                <th style="width: 30px;">ID</th>
                <th>Company Name</th>
                <th>Legal Name</th>
                <th>Dealer Name</th>
                <th style="width: 75px;">Action</th>
            </tr>
            </thead>
            <tbody>

            <?php /* @var $client ClientModel */ ?>
            <?php foreach ($this->paginator->getCurrentItems() as $client) : ?>
                <tr>
                    <td><?= $this->escape($client->id); ?></td>
                    <td><?= $this->escape($client->companyName); ?></td>
                    <td><?= $this->escape($client->legalName); ?></td>
                    <td><?= $this->escape(DealerMapper::getInstance()->find($client->dealerId)->dealerName); ?></td>
                    <td>
                        <div class="btn-group btn-group-justified">
                            <a class="btn btn-xs btn-warning" title="Edit" href="<?= $this->url(array('id' => $client->id), 'admin.clients.edit'); ?>">
                                <i class="glyphicon glyphicon-pencil"></i>
                            </a>
                            <a class="btn btn-xs btn-danger" title="Delete" href="<?= $this->url(array('id' => $client->id), 'admin.clients.delete'); ?>">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?= $this->paginationControl($this->paginator); ?>
    <?php else : ?>
        <h1>There are no clients</h1>
    <?php endif; ?>

</div>