<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
    echo $this->titlePageStart;
?>
    <?php echo $this->noBreakStart; ?>
        <div class="titlepage">
        	<div class="header">
            	<h3>Prepared for:
            	<?php
            		if(strlen($proposal->getReport()->customerCompanyName) > 26)
            			echo "<br/>";
            		echo $proposal->getReport()->customerCompanyName;
            	?>
            	</h3>
            	<h3><?php echo $proposal->getDateReportPrepared(); ?></h3>
            </div> <!-- End div header -->
            <div class="customerdetails">
                <p><?php echo nl2br($proposal->getCustomerAddress()); ?></p>
            </div>
        </div> <!-- End div titlepage -->
    <?php echo $this->noBreakEnd; ?>
<?php
    echo $this->pageEnd;
?>