<?php
echo $this->pageStart;
?>
<?php echo $this->noBreakStart; ?>
<div class="h1">Your PrintIQ&reg; Solution</div>
<p>Based on your PrintIQ&reg; Smart Assessment, we have developed a
	choice of managed print solutions to meet your specific business needs.</p>
<br />

<div class="pheader">Managed Print Solution Objectives</div>
<p style="margin-bottom: 10pt;">Your managed print solution is designed
	to meet the following objectives:</p>
<ul>
	<li>Allow your printing costs to be accurately measured, controlled and
		budgeted</li>
	<li>Free your working capital tied to excess printer supplies inventory</li>
	<li>Reduce the time your IT staff spends dealing with multiple vendors
		and print related issues</li>
	<li>Improve printer uptime, employee efficiency and employee
		satisfaction</li>
	<li>Maximize the value of the hardware assets you already own</li>
	<li>Reduce your environmental impact from office printing</li>
</ul>

<div class="pheader">Solution Recommendations</div>
<div style="width: 580px;">
	<p style="margin-top: 10pt;">To achieve the above objectives, we make
		the following recommendations:</p>
	<ol>
		<li><strong>Continue remote print management</strong>
			<ul>
				<li>Software is provided free of charge so we can monitor the status
					of your printing devices. and supply levels</li>
				<li>Meters are collected automatically for accurate invoicing</li>
			</ul></li>
		<li><strong>Start receiving just-in-time supplies and proactive
				maintenance and service</strong>
			<ul>
				<li>Just-in-time supplies fulfillment means we will know when you
					are running low on supplies and will ship you the correct items
					when you need them.</li>
				<li>Printer maintenance ensures your hardware stays in the best
					condition possible and next-day service is available for break-fix
					issues.</li>
			</ul></li>
		<li><strong>Consolidate managed print expenses into a single invoice</strong>
			<ul>
				<li>Pay a per-page rate that includes supplies and service for
					existing printer hardware.</li>
				<li>Pay a flat monthly rate for new printer hardware and related
					supplies and service.</li>
			</ul></li>
		<li><strong>Consider migrating new printing hardware to a flat-rate
				program</strong>
			<ul>
				<li>Your printing hardware will no longer be your responsibility to
					maintain.</li>
				<li>We will work with you to provide the exact hardware you need,
					when and where you need it, and eliminate old, expensive and
					unnecessary printing devices.</li>
			</ul></li>
		<li><strong>Take advantage of our smart eco solutions</strong>
			<ul>
				<li>Your energy consumption will be monitored and inefficient
					printing hardware can be removed or replaced.</li>
				<li>We offer free recycling programs for supplies and equipment and
					can provide you with refurbished printers and remanufactured
					supplies to reduce waste.</li>
			</ul></li>
	</ol>
</div>
<?php echo $this->noBreakEnd; ?>
 
<?php
echo $this->pageEnd;
echo $this->pageStart;
?>

<?php echo $this->noBreakStart; ?>
<div class="h1">Evaluating the True Cost of MPS Contracts and Copier
	Leases</div>
<p>Before you choose the hardware and managed print program that best
	meets your needs, make sure you are comparing apples to apples. Many
	contracts can be confusing or misleading. We recommend asking any
	vendor the following questions so you are equipped with the necessary
	information.</p>

<br />

<table class="genericTable" id="DescriptionQuestionTable"
	style="width: 100%;">
	<thead>
		<tr>
			<th style="width: 100px;">Question</th>
			<th style="width: 250px;">Why It's Important to Ask</th>
			<th style="width: 250px;">How Office Depot MPS Works</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="column1 red bold"><div>What happens at the end of the
					contract?</div></td>
			<td class="column2"><div>Copier leases may carry a large residual at
					the end of the contract. While this can decrease the monthly
					payment, it may cost you thousands of dollars at the end of the
					contract if you want to own the hardware.</div></td>
			<td class="column3"><div>Office Depot provides a wide range of
					options at the end of our hardware contracts. You can upgrade to
					new equipment, or continue on with the current hardware as is.</div></td>
		</tr>
		<tr>
			<td class="column1 red bold"><div>Who in the area can service and
					supply the hardware?</div></td>
			<td class="column2"><div>Many copier dealers sell hardware that can
					only be serviced and supplied by a limited number of authorized
					dealers. If you decide to purchase the hardware at the end of the
					lease, you may find that supplies, parts and service are not widely
					available from other vendors.</div></td>
			<td class="column3"><div>Office Depot offers hardware from channel
					friendly manufacturers, such as HP and Xerox, which means you will
					have many options for acquiring supplies and service. While we hope
					you continue with one of our managed print options, you are free to
					have another vendor service and supply your device at the end of
					the contract.</div></td>
		</tr>
		<tr>
			<td class="column1 red bold"><div>How long is the lease term?</div></td>
			<td class="column2"><div>Longer lease terms decrease the monthly
					payment but increase the amount you pay over the life of the
					contract. If the monthly payment seems small, it is likely that the
					lease term is long or the residual is high.</div></td>
			<td class="column3"><div>Office Depot typically recommends a 3-year
					contract term, but we can customize an agreement to meet your
					specific needs.</div></td>
		</tr>
		<tr>
			<td class="column1 red bold"><div>What is included and not included
					in the contract?</div></td>
			<td class="column2"><div>Many contracts have a variety of hidden
					charges. Does your rate include toner, maintenance kits, parts,
					service and labor? Can fuel surcharges be billed separately? Are
					there are minimum page charges or overage rates? Do rates increase
					over the lease term? Ask these questions to determine the total
					cost of the contract.</div></td>
			<td class="column3"><div>Our PrintIQ Plus program includes hardware,
					supplies, parts, service and labor for a flat monthly rate. If you
					want us to manage your existing hardware, our PrintIQ program
					includes supplies, parts, service and labor for a standard per-page
					rate. There are no minimum page charges, overage rates or fuel
					surcharges, and our rates do not increase over the contract term.</div></td>
		</tr>
		<tr>
			<td class="column1 red bold"><div>What features are included in the
					hardware?</div></td>
			<td class="column2"><div>Hardware with many features, such as tabloid
					printing and stapling, drive up the cost. While some businesses may
					require these features, many do not. Know what features you require
					and do not pay for anything additional that you do not need.</div></td>
			<td class="column3"><div>Office Depot works with you to determine
					your hardware needs, so you do not end up paying for unnecessary
					features.</div></td>
		</tr>
	</tbody>
</table>
<p>We want you to be fully informed before choosing hardware or a
	managed print program. If you have any questions about our programs or
	contracts, please ask your Account Manager.</p>
<br />
<?php echo $this->noBreakEnd; ?>

<?php
echo $this->pageEnd;
?>