<?php
    //echo $this->pageStart;
?>
<?php echo $this->noBreakStart; ?>
	<h4 class="paraHeader">Other Printing Devices Not Included in Assessment:</h4>
	<?php if (count($this->proposal->getExcludedDevices()) > 0) :?>
    	<table class="genericTable" id="ExcludedDevicesTable" style="font-size: 9pt;">
    		<thead>
    			<tr>
    				<th class="left">Manufacturer</th>
    				<th class="left">Model</th>
    				<th class="center">Serial Number</th>
    				<th class="center">IP Address</th>
    				<th class="center">Exclusion Reason</th>
    			</tr>
    		</thead>
    		<tbody>
    		<?php foreach($this->proposal->getExcludedDevices() as $device): 
    			/* @var $device Proposalgen_Model_DeviceInstance */ ?>
    			<?php $SerialNumber = (strlen($device->SerialNumber) == 0) ? 'Unknown Serial' : $device->SerialNumber; ?>
    				<tr>
    					<td><div class=" left"><?php echo $device->getMasterDevice()->getManufacturer()->getManufacturerName(); ?></div></td>
    					<td><div class=" left"><?php echo $device->getMasterDevice()->getPrinterModel(); ?></div></td>
    					<td><div class=" center"><?php echo $SerialNumber; ?></div></td>
    					<td><div class=" left"><?php if ($device->IpAddress) echo $device->IpAddress; else echo 'Unknown IP';?></div></td>
    					<td><div class=" left"><?php echo $device->ExclusionReason; ?></div></td>
    				</tr>
    		<?php endforeach; ?>
    		</tbody>
    	</table>
	<?php else: ?>
		<br/><p><em>No devices were excluded from this report.</em></p>
	<?php endif?>

	
<?php echo $this->noBreakEnd; ?>
<?php
    echo $this->pageEnd;
?>