<?php
$this->placeholder('extraNavbar')->set($this->render('_partials/reportMenu.phtml'));

$data = array(
    "proposal"       => $this->proposal,
    "isPDF"          => $this->isPDF,
    "backleft"       => $this->backleft,
    "backright"      => $this->backright,
    "backtop"        => $this->backtop,
    "backbottom"     => $this->backbottom,
    "footer"         => $this->footer,
    "pagestyle"      => $this->pagestyle,
    "titlePageStart" => $this->titlePageStart,
    "pageStart"      => $this->pageStart,
    "pageEnd"        => $this->pageEnd,
    "noBreakStart"   => $this->noBreakStart,
    "noBreakEnd"     => $this->noBreakEnd,
    "orientation"    => $this->orientation
);

?>
<?php
echo $this->partial('report/solution/' . $this->App()->theme . '/html/00_Render.phtml', $data);
?>
