<?php
/**
 * Assessment - Analysis: Service and Supplies Logistics
 */

/* @var $phpword PHPWord */
$phpword = $this->phpword;

/* @var $section PHPWord_Section */
$section = $this->section;
$section->addPageBreak();

/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;

$section->addTitle($this->translate('Analysis: Service and Supplies Logistics'), 1);
$gradeTable = $section->addTable($this->styles->tables->grades->tablestyle);
$gradeTable->addRow();
$gradeTable->addCell(8028, $this->styles->tables->grades->cell1)->addText($proposal->Ranking->SuppliesAndServiceLogistics->RankingText, null, 'nospacing');
$gradeTable->addCell(1000, $this->styles->tables->grades->cell2)->addText(number_format($proposal->Ranking->SuppliesAndServiceLogistics->Rank, 1), 'gradeFont', 'gradeParagraph');
$section->addTextBreak();
$section->addTitle('Printing Device Management Breakdown', 2);
$section->addText($this->translate('Different types of printing devices are managed in different ways-newer networked printers can be managed with remote monitoring software; leased multifunction devices are typically managed by the vendor who sold the machine; devices not connected to the network, such as inkjets and some older printers, are difficult to manage because you cannot monitor them with software.'));

$section->addTextBreak(2);
$imageTable = $section->addTable($this->styles->tables->doubleimage->tablestyle);
$imageTable->addRow();
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell1)->addImage($proposal->Graphs [1]);
$imageTable->addCell(4514, $this->styles->tables->doubleimage->cell2)->addImage($proposal->Graphs [2]);
$section->addTextBreak(2);

$inkjetString = $this->translate('less than 10%');
if ($proposal->PercentPrintingDoneOnInkjet == 50)
{
    $inkjetString = $this->translate('more than 50%');
}
else if ($proposal->PercentPrintingDoneOnInkjet == 38)
{
    $inkjetString = $this->translate('26% to 50%');
}
else if ($proposal->PercentPrintingDoneOnInkjet == 18)
{
    $inkjetString = $this->translate('10% to 25%');
}

$textRun = $section->createTextRun();
$textRun->addText($this->translate('Based on your questionnaire, '));
$textRun->addText(sprintf($this->translate('%1$s of your printing is done on inkjet devices. '), $inkjetString), array (
    'bold' => true 
));
$textRun->addText($this->translate('We did not monitor inkjet machines that are not connected to the network, and on average, pages printed to inkjet printers cost three times more than pages printed to laser devices. Without being on the network, users also cannot share these devices. There are some instances where desktop printers are appropriate, for instance, if a single user requires confidential, high-convenience printing. We can help you consolidate desktop hardware where appropriate, and where desktop printing is required, we can help you select network-capable equipment so your desktop printing can be managed with the rest of your office print.'));
$excludedDeviceCount = count($proposal->ExcludedDevices);
if ($excludedDeviceCount > 0)
{
    $section->addTextBreak();
    $section->addText(sprintf($this->translate('%1$s devices were not included in the analysis due to lack of data or model information. See the Appendix in the PrintIQ Your Solution document for the list of excluded device(s).'), number_format($excludedDeviceCount)));
}

$section->addPageBreak();

$section->addTitle('Efficiency of Break-Fix Service', 2);
$section->addText($this->translate('Based on your questionnaire responses, we discovered the following:'));
// Efficiency of Break-Fix Service table
$cellWidths = array (
    7500, 
    1528 
);
$table = $section->addTable($this->styles->tables->twoColumnDataTable->tablestyle);
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText($this->translate('Number of printer repairs per month'), 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($this->proposal->NumberOfRepairs), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText($this->translate('Average time between printer breaking down and printer being fixed'), 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($this->proposal->AverageTimeBetweenBreakdownAndFix) . 'day(s)', 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$cell = $table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1);
$cell->addText($this->translate('Annual downtime resulting from printer breakdowns'), 'bold_text', 'nospacing');
$cell->addText($this->translate('(Based on an 8 hour work day)'), 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($this->proposal->AnnualDowntimeFromBreakdowns), 'bold_text', 'nospacing_rightalign');

$section->addText($this->translate('Office Depot can provide next-day service for your printer fleet.'), 'small_italic_text');


$section->addTitle('Number of Vendors', 2);
$section->addText($this->translate('Based on your questionnaire responses, we discovered the following:'));

// Number of Vendors table
$cellWidths = array (
    7500, 
    1528 
);

$table = $section->addTable($this->styles->tables->twoColumnDataTable->tablestyle);
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText($this->translate('Number of vendors used to source printing hardware, supplies and service'), 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($this->proposal->NumberOfVendors), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText($this->translate('Number of orders for ink and toner executed annually'), 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText(number_format($this->proposal->NumberOfAnnualInkTonerOrders), 'bold_text', 'nospacing_rightalign');
$table->addRow($this->styles->tables->twoColumnDataTable->rowheight);
$table->addCell($cellWidths [0], $this->styles->tables->twoColumnDataTable->cell1)->addText($this->translate('Estimated annual cost to execute ink and toner orders'), 'bold_text', 'nospacing');
$table->addCell($cellWidths [1], $this->styles->tables->twoColumnDataTable->cell2)->addText('$' . number_format($this->proposal->CostOfExecutingSuppliesOrders), 'bold_text', 'nospacing_rightalign');
$section->addText($this->translate('Time spent dealing with multiple vendors could be better spent focusing on your core business tasks. Office Depot can bundle your supplies and service into a single invoice - and if you need new hardware, that can be included too.'), 'small_italic_text');



$section->addTitle('Number of Printing Device Models and Supply Types', 2);
$section->addText(sprintf($this->translate('Out of your %1$s networked printing devices, you have of %2$s different models. Each section of the chart below represents a single model type. We estimate that %3$s of your printing devices are leased machines, for which supplies are included in your contract. The %4$s remaining machines consist of %5$s different models and use %6$s different supply types. If you hold two of each supply in inventory, you have an estimated $%7$s in operating cash held in printer supplies inventory at any given time.'), number_format(count($this->proposal->getDevices())), number_format($this->proposal->NumberOfUniqueModels), number_format(count($this->proposal->getLeasedDevices())), number_format(count($this->proposal->getPurchasedDevices())), number_format($this->proposal->NumberOfUniquePurchasedModels), number_format($this->proposal->NumberOfUniquePurchasedToners), number_format($this->proposal->CashHeldInInventory)));

$imageTable = $section->addTable(array (
    'borderBottomSize' => 1 
));
$imageTable->addRow();
$cell = $imageTable->addCell(9028.8, array (
    'valign' => 'center' 
));

$cell->addImage($this->proposal->Graphs [3], array (
    'align' => 'center' 
));

$section->addText($this->translate('By using printing devices with the same supplies, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space required. Office Depot can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.'));