<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
echo $this->pageStart;
$this->brandName  = "MPSToolbox.com";
$this->companyName = "MPSToolbox.com";
?>
<?php echo $this->noBreakStart; ?>
<div class="h1">Old Device List</div>
<p>Below is a list of your printing device models and whether or not they are qualified for just-in-time supplies fulfillment. For devices not qualified for just-in-time supplies
		fulfillment, you can call into our office to order supplies for next-day delivery. Consider upgrading these devices to be on a 100% just-in-time supplies fulfillment model.
		Devices not included in the report are listed in a subsequent table. These devices are typically older models that are not compatible with remote monitoring software or do not
		qualify for the <?php echo $this->brandName ?> program.</p>
<br />
<?php echo $this->noBreakEnd; ?>
<table class="genericTable" id="AppendixDeviceTable">
		<thead>
			<tr class="center">
				<th class="left">Manufacturer</th>
				<th class="left">Model</th>
				<th>IP Address</th>
				<th>Serial No.</th>
				<th>Age <br />(In Years)</th>
			</tr>
		</thead>
		<tbody>
        <?php foreach($proposal->getIncludedDevicesSortedAscendingByAge() as $deviceInstance) : /* @var $deviceInstance Proposalgen_Model_DeviceInstance */ ?>
            <tr>
				<td class="column1"><div><?php echo $deviceInstance->getMasterDevice()->getManufacturer()->displayname; ?></div></td>
				<td class="column2"><div><?php echo $deviceInstance->getMasterDevice()->modelName; ?></div></td>
				<td class="column3"><div class="center"><?php echo ($deviceInstance->ipAddress) ?: "Unknown"; ?></div></td>
				<td class="column3"><div class="center"><?php echo ($deviceInstance->serialNumber) ?: "Unknown"; ?></div></td>
				<td class="column6"><div class="center"><?php echo $deviceInstance->getAge(); ?></div></td>
			</tr>
            <?php endforeach; ?>
		</tbody>
	</table>
<br/>
<br/>