<?php

$is_root = \MPSToolbox\Legacy\Entities\DealerEntity::getDealerId() == 1;

/** @var \MPSToolbox\Legacy\Modules\QuoteGenerator\Models\ClientModel $selectedClient */
$selectedClient = null;
$selectedClientId = null;
$clientOptions = [];
$s = new \MPSToolbox\Services\RmsDeviceInstanceService();
foreach($this->clients as $client) {
    if ($this->clientId==$client->id) {
        $selectedClient = $client;
        $selectedClientId = $client->id;
    }
    $clientName = $client->companyName;
    $n = count($s->getIncomplete($client->id));
    if ($n>0) $clientName .= " ({$n})";
    $clientOptions[$client->id] = $clientName;
}

if ($is_root) $selectedClientId = 0;

?>

<script>
    var isSaveAndApproveAdmin = <?=($this->IsAllowed(\MPSToolbox\Legacy\Models\Acl\ProposalgenAclModel::RESOURCE_PROPOSALGEN_ADMIN_SAVEANDAPPROVE, \MPSToolbox\Legacy\Models\Acl\AppAclModel::PRIVILEGE_ADMIN) ? 'true' : 'false'); ?>,
        dealerSkuName         = '<?= My_Brand::$dealerSku; ?>';
</script>

<div class="container">

<?php if (!$is_root) { ?>
    <div class="row">
        <div class="col-sm-4">
            <p>Select a client</p>
        </div>
        <div class="col-sm-8">
            <select class="form-control" onchange="window.location.href='?client='+this.value">
                <option></option>
                <?php foreach($clientOptions as $id=>$client) { ?><option <?= $this->clientId==$id?'selected="selected"':'' ?> value="<?= $id ?>"><?= $client ?></option><?php } ?>
            </select>
        </div>
    </div>
<?php } ?>

    <hr>

<?php if ($selectedClient || $is_root) { ?>

    <table class="table table-striped table-hover" id="my-table">
        <colgroup>

        </colgroup>
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th>Raw Device Name</th>
                <th>Model</th>
                <th>IP Address</th>
                <th>Serial Number</th>
                <th>Location</th>
                <th>Last Reported</th>
                <th>Template</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>

    <table class="table">
        <thead><tr><th colspan="2">Legend</th></tr></thead>
        <tbody>
        <tr><td><i class="fa fa-fw fa-check text-success"></i></td><td>Device is successfully mapped and monitored</td><td>No action required</td></tr>
        <tr><td><i class="fa fa-fw fa-warning text-warning"></i></td><td>Device is mapped but no monitoring data has been received for a week or longer</td><td>Investigate why this device is stale</td></tr>
        <tr><td><i class="fa fa-fw fa-wrench text-danger"></i></td><td>Device is not mapped to a device model</td><td>Map the device</td></tr>
        <tr><td><i class="fa fa-fw fa-bars text-danger"></i></td><td>Device is mapped but there is no cost available for at least one of the supplies, or no supplies are defined</td><td>Enter your costs for the supplies</td></tr>
        <tr><td><i class="fa fa-fw fa-remove"></i></td><td>Device is ignored (supply monitoring is off)</td><td>No action required</td></tr>
        <tr><td><i class="fa fa-fw fa-eye"></i></td><td>Device is visible in the Supply Cupboard</td><td>No action required</td></tr>
        <tr><td><i class="fa fa-fw fa-eye-slash" style="color:red"></i></td><td>Device is hidden from the Supply Cupboard</td><td>No action required</td></tr>
        <tr><td><i class="fa fa-fw fa-info-circle text-info"></i></td><td>Click this icon for more information about the device</td><td></td></tr>
        </tbody>
    </table>



    <script>
        function reloadMe() {
            window.dt_table.ajax.reload();
            $.get('/ecommerce/device/ajax-todo', [], function(response) {
                $.each(response, function(i,e) {
                    notifyTodo(e.item, e.n);
                });
            }, 'json');
        }
        function doMap(id, name) {
            var tr = '<tr>';
            tr+= '<td colspan="3"><i class="fa fa-fw"></i>&nbsp;'+name+'</td>';
            tr+= '<td colspan="3">' +
                '<table style="width:100%">' +
                    '<tr>' +
                        '<td><input type="text" id="select-'+id+'" style="width:100%"></td>' +
                        '<td>&nbsp;</td>' +
                        '<td>' +
                            '<button disabled="disabled" id="ok-btn-'+id+'" data-value="" onclick="modelSelected('+id+',this)" class="btn btn-primary">OK</button>' +
                            '&nbsp;&nbsp;&nbsp;<a href="javascript:;" onclick="window.dt_table.ajax.reload();">Cancel</a>' +
                            '&nbsp;&nbsp;&nbsp;<a href="javascript:;" onclick="if (window.confirm(\'Ignore this model?\')) ignore('+id+')">Ignore</a>' +
                        '</td>' +
                    '</tr>' +
                '</table>' +
            '</td>';
            tr+= '<td></td>';
            tr+= '<td><a href="javascript:;" onclick="newDeviceModel('+id+')" class="btn btn-primary">New Device Model</a></td>';
            tr+= '</tr>';
            $('#tr-'+id).replaceWith(tr);
            require(['app/components/Select2/MasterDevice'], function () {
                $('#select-'+id).on('change', function ()
                {
                    var $this = $(this);
                    // Only update if there's an actual change
                    if ($this.data('device-id') != $this.val())
                    {
                        $('#ok-btn-'+id).removeAttr('disabled');
                        $('#ok-btn-'+id).attr('data-value', $this.val());
                    }
                }).selectMasterDevice();
            });
        }
        function modelSelected(id, btn) {
            var value = $(btn).attr('data-value');
            $.post('/ecommerce/device/ajax-map', {client:<?= $selectedClientId ?>, instance:id, model:value}, function(response) {
                reloadMe();
            }, 'json');
        }
        function ignore(id) {
            $.post('/ecommerce/device/ajax-ignore', {client:<?= $selectedClientId ?>, instance:id}, function(response) {
                reloadMe();
            }, 'json');
        }
        function ignoreSingle(id) {
            $.post('/ecommerce/device/ajax-ignore-single', {client:<?= $selectedClientId ?>, instance:id}, function(response) {
                reloadMe();
            }, 'json');
        }
        function hide(id) {
            $.post('/ecommerce/device/ajax-hide', {client:<?= $selectedClientId ?>, instance:id}, function(response) {
                reloadMe();
            }, 'json');
        }
        function unhide(id) {
            $.post('/ecommerce/device/ajax-hide', {client:<?= $selectedClientId ?>, instance:id, reverse:true}, function(response) {
                reloadMe();
            }, 'json');
        }
        function unignore(id) {
            $.post('/ecommerce/device/ajax-ignore', {client:<?= $selectedClientId ?>, instance:id, reverse:true}, function(response) {
                reloadMe();
            }, 'json');
        }
        function unignoreSingle(id) {
            $.post('/ecommerce/device/ajax-ignore-single', {client:<?= $selectedClientId ?>, instance:id, reverse:true}, function(response) {
                reloadMe();
            }, 'json');
        }
        function unmap(id) {
            $.post('/ecommerce/device/ajax-map', {client:<?= $selectedClientId ?>, instance:id, reverse:true}, function(response) {
                reloadMe();
            }, 'json');
        }
        function newDeviceModel(rmsDeviceInstanceId) {
            require(['app/legacy/hardware-library/manage-devices/DeviceModal'], function (DeviceModal)
            {
                var editDeviceModal = new DeviceModal({
                    "deviceId"      : null,
                    "isAllowed"     : isSaveAndApproveAdmin,
                    "rmsDeviceInstanceId" : rmsDeviceInstanceId
                });
                $(editDeviceModal).on('DeviceModal.saved', function (event, masterDeviceId) {
                    $.post('/ecommerce/device/ajax-map', {client:<?= $selectedClientId ?>, instance:rmsDeviceInstanceId, model:masterDeviceId}, function(response) {
                        reloadMe();
                    }, 'json');
                });
                editDeviceModal.show();
            });
        }
        function selectTemplate(id) {
            var $el = $('#template-'+id);
            var value = $el.attr('data-value');
            $el.html('<select onchange="templateSelected('+id+',this.value)"><option '+(value==0?'selected="selected"':'')+' value="0">Client</option><option '+(value==1?'selected="selected"':'')+' value="1">1</option><option '+(value==2?'selected="selected"':'')+' value="2">2</option><option '+(value==3?'selected="selected"':'')+' value="3">3</option></select> <a href="javascript:;" onclick="templateSelected('+id+','+value+')">cancel</a>');
        }
        function templateSelected(id,value) {
            var $el = $('#template-'+id);
            var old_value = $el.attr('data-value');
            $el.attr('data-value', value);
            $el.html('<span onclick="selectTemplate('+id+')" style="cursor:pointer">'+(value>0?value:'Client')+'</span>');
            if (old_value!=value) {
                $.post('/ecommerce/device/template-selected', {id:id, value:value}, function(response) {}, 'json');
            }
        }
        function showDetailsModal(id) {
            $.post('/ecommerce/device/details', {id:id}, function(response) {
                $('#details-modal-body').html(response);
                var $modal = $('#details-modal');
                $modal.modal({backdrop: 'static'}).css('margin-top',(-1 * ($modal.height()/2))).css('margin-left',(-1 * ($modal.width()/2)));
            }, 'html');
        }
        function showModelModal(deviceId) {
            require(['app/legacy/hardware-library/manage-devices/DeviceModal'], function (DeviceModal)
            {
                var editDeviceModal = new DeviceModal({
                    "deviceId"      : deviceId,
                    "isAllowed"     : isSaveAndApproveAdmin
                });
                $(editDeviceModal).on('DeviceModal.saved', function (event, masterDeviceId) {
                    reloadMe();
                });
                editDeviceModal.show();
            });
        }
        require(['jquery','datatables', 'datatables.bootstrap'], function ($) {

            require(['bootstrap.contextmenu'], function() {

            });

            window.dt_table = $('#my-table').DataTable({
                "columns": [
                    {data: 'icon'},
                    {data: 'hidden'},
                    {data: 'raw'},
                    {data: 'model'},
                    {data: 'ipAddress'},
                    {data: 'serialNumber'},
                    {data: 'location'},
                    {data: 'reportDate'},
                    {data: 'template'}
                ],
                "ajax": {
                    "url": "/ecommerce/device/ajax-table?client=<?= $selectedClientId ?>"
                },
                "pageLength": 100
            }).on( 'draw.dt', function () {
                $('.context').contextMenu({});
            });

        });

    </script>

<?php } ?>

</div>

<div class="modal fade" id="details-modal" style="width:800px">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Device Details</h4>
            </div>
            <div class="modal-body" id="details-modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
