<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $customerOptimization OptimizationCustomerModel */
$customerOptimization = $this->customerOptimization;

?>
<div class="titlepage" id="title-page">
    <div class="header">
        <div class="title-page-logo-box-wrapper">
            <div class="title-page-logo-box">
                <img class="title-page-logo" src="<?= $this->serverUrl($this->dealerLogoFile) ?> " />
            </div>
        </div>
    </div>
    <div class="title-page-report-title">
        <h2><?= My_Brand::getDealerBranding()->customerOptimizationTitle ?></h2>
    </div>
    <div class="title-page-customer-details">
        <h3>Prepared for:
            <?php if (strlen($hardwareOptimization->getClient()->companyName) > 26) : ?>
                <br>
            <?php endif; ?>
            <?= $hardwareOptimization->getClient()->companyName; ?>
        </h3>

        <p><?= nl2br($hardwareOptimization->getClient()->getAddress()); ?></p>
        <br>

        <p>Date: <?= $hardwareOptimization->getFormattedDatePrepared(); ?></p>
    </div>
</div>