<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Customer */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;
?>
<div class="pheader" id="current-fleet-statistics">
    Current Fleet Statistics (before replacements)
</div>

<table class='center'>
    <tr>
        <td><img src="<?php echo $graphs[0]; ?>" /></td>
        <td><img src="<?php echo $graphs[1]; ?>" /></td>
        <td><img src="<?php echo $graphs[2]; ?>" /></td>
    </tr>
</table>

<div class="pheader" id="optimization-summary">
    Optimization Summary
</div>
<p>All fleets vary in age and functionality. This report sorts the devices in your fleet into four categories, based on page count, functionality, and device optimal age. For the purposes of this report, the categories are as follows:</p>
<p>Keep: Devices are being used within their specifications.</p>
<p>Replace: Refer to the Appendix for reasons for device replacements.</p>
<p>Do Not Repair: These devices may remain in place but we don't recommend repairs if they are needed. The reasons can be any one of the following: the device is older than 10 years, it has printed more than its recommended maximum lifetime page count, or it is incompatible with an MPS program.</p>
<p>Retire/Migrate: The device prints fewer than 200 pages per month; you may choose to migrate pages from these devices to other nearby devices to save on supply and electrical costs.</p>


<br />
<table class='center'>
    <tr>
        <td><img src="<?php echo $graphs[3]; ?>" /></td>
    </tr>
</table>
<br /><br />