<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $customerOptimization OptimizationCustomerModel */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;
?>
<div class="pheader" id="current-fleet-statistics">
    Current Fleet Statistics
</div>

<table class='center'>
    <tr>
        <td><img src="<?= $graphs[0]; ?>" /></td>
        <td><img src="<?= $graphs[1]; ?>" /></td>
        <td><img src="<?= $graphs[2]; ?>" /></td>
    </tr>
</table>

<div class="pheader" id="optimization-summary">
    Optimization Summary
</div>
<p>All fleets vary in age and functionality. This report sorts the devices in your fleet into four categories, based on page count, functionality, and optimal device age. For the purposes of this report, the categories are as follows:</p>
<p>Keep: Devices are being used within their specifications.</p>
<p>Replace: Refer to the Appendix for reasons for device replacements.</p>
<p>Do Not Repair: These devices may remain in place but we don't recommend repairs if they are needed. The reasons can be any one of the following: the device is older than 10 years, it has printed more than its recommended maximum lifetime page count, or it is incompatible with an MPS program.</p>
<p>Retire/Migrate: The device prints fewer than 200 pages per month; you may choose to migrate pages from these devices to other nearby devices to save on supply and electrical costs.</p>


<br />
<table class='center'>
    <tr>
        <td><img src="<?= $graphs[3]; ?>" /></td>
    </tr>
</table>
<br /><br />