<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Customer */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;
?>
<div class="pheader">
    Technology Features and Functionality
</div>
<p>If you printed every document on both sides of the page, you could use up to 50% less paper than you would by only printing on one side. You could further
    reduce your paper consumption by using a scanner to e-mail documents instead of printing copies for distribution. The following charts show how many of your
    printing devices have duplexing and scanning capabilities:</p>
<table class='center'>
    <tr>
        <td><img src="<?php echo $graphs[8]; ?>" /></td>
        <td><img src="<?php echo $graphs[9]; ?>" /></td>
    </tr>
</table>