<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $customerOptimization OptimizationCustomerModel */
$customerOptimization = $this->customerOptimization;

?>
<div class="pheader" id="technology">
    Technology Features and Functionality
</div>
<p>If you printed every document on both sides of the page, you could use up to 50% less paper than you would by printing only on one side. You could further
    reduce your paper consumption by using a scanner to email documents instead of printing copies for distribution. The following charts show how many of your
    printing devices have duplex and/or scanning capabilities.</p>
<table class='center'>
    <tr>
        <td><img src="?png=TechnologyFeatures" /></td>
        <td><img src="?png=TechnologyFeaturesOptimized" /></td>
    </tr>
</table>