<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $customerOptimization OptimizationCustomerModel */
$customerOptimization = $this->customerOptimization;

?>
<div class="pheader" id="age-of-devices">
    Age of Printing Devices
</div>
<p>A breakdown of the ages of your printing devices is shown below.</p>
<table class='center'>
    <tr>
        <td><img src="?png=AgeOfDevices" /></td>
        <td><img src="?png=AgeOfDevicesOptimized" /></td>
    </tr>
</table>
<br />