<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\OptimizationCustomerModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\HardwareOptimization\ViewModels\OptimizationViewModel;

$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization OptimizationViewModel */
$optimization = $this->optimization;

/* @var $customerOptimization OptimizationCustomerModel */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;
?>
<div class="pheader" id="supply-types">
    Number of Printing Device Models and Supply Types
</div>

<p>Out of your
    <strong><?= $optimization->getDevices()->allIncludedDeviceInstances->getCount(); ?></strong> networked printing devices, you have of
    <strong><?= $optimization->getNumberOfUniqueModels(); ?></strong> unique
    <?= (count($optimization->getNumberOfUniqueModels()) > 1 ? 'model ' : 'models '); ?>.
    Each section of the chart below represents a single model type.
    We estimate that
    <strong><?= count($optimization->getDevices()->leasedDeviceInstances->getDeviceInstances()); ?></strong> of your printing devices
    <?= (count($optimization->getDevices()->leasedDeviceInstances->getDeviceInstances()) == 1 ? ' is a leased machine' : ' are leased machines '); ?>
    , for which supplies are included in your contract. The
    <strong><?= number_format($optimization->getDevices()->purchasedDeviceInstances->getCount()); ?></strong> remaining
    <?= ($optimization->getDevices()->purchasedDeviceInstances->getCount() == 1 ? ' machine consists ' : 'machines consist '); ?>
    of
    <strong><?= $optimization->getNumberOfUniquePurchasedModels(); ?></strong>
    <?= (count($optimization->getNumberOfUniquePurchasedModels()) > 1 ? ' model and uses' : ' models and use '); ?>
    <strong><?= $optimization->getNumberOfUniquePurchasedToners(); ?></strong>
    <?= (count($optimization->getNumberOfUniquePurchasedToners()) > 1 ? ' supply type' : ' different supply types'); ?>.
    If you hold two of each supply in inventory, you
    have an estimated
    <strong>$<?= number_format($optimization->getCashHeldInInventory()); ?> in operating cash held in printer supplies
        inventory</strong> at any given time.</p>
<table class='center'>
    <tr>
        <td><img src="<?= $graphs[12]; ?>" /></td>
    </tr>
</table>
<table class='center'>
    <tr>
        <td><img src="<?= $graphs[13]; ?>" /></td>
    </tr>
</table>
<p>By using printing devices with supplies in common, you can minimize the amount of operating cash held up in supplies inventory and the amount of storage space
    required. <?= My_Brand::getDealerBranding()->shortDealerName; ?> can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply
    orders.</p>