<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Customer */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;
?>
<div class="pheader" id="color-usage">
    Color Usage
</div>
<p>You currently have <strong><?php echo number_format($optimization->getNumberOfColorCapableDevices()); ?></strong> color printing devices that print a monthly average of
    <strong><?php echo $this->formatPageVolume($optimization->getDevices()->allIncludedDeviceInstances->getPageCounts()->getColorPageCount()->getMonthly()); ?></strong> color pages per
    month, which is <strong><?php echo number_format(($optimization->getPercentages()->TotalColorPercentage * 100), 2); ?>%</strong> of your total monthly print
    volume.</p>
<table class='center'>
    <tr>
        <td><img src="<?php echo $graphs[14]; ?>" /></td>
        <td><img src="<?php echo $graphs[15]; ?>" /></td>
    </tr>
</table>
<p>Overall, printing in color is more expensive than printing in monochrome. The ideal amount of color usage depends on your printing needs, but the use of
    color in important documents can enhance your company's professional image, improve comprehension and increase readership.
    <?php echo My_Brand::getDealerBranding()->mpsProgramName; ?> can help you track your color printing and provide low-cost color hardware options.</p>
<br />