<?php
/* @var $hardwareOptimization Hardwareoptimization_Model_Hardware_Optimization */
$hardwareOptimization = $this->hardwareOptimization;

/* @var $optimization Hardwareoptimization_ViewModel_Optimization */
$optimization = $this->optimization;

/* @var $customerOptimization Hardwareoptimization_Model_Optimization_Customer */
$customerOptimization = $this->customerOptimization;

/* @var $graphs array */
$graphs = $this->graphs;

$deviceInstances = $optimization->getDevicesGroupedByAction();

$totalNumberOfDevices = $optimization->getDevices()->purchasedDeviceInstances->getCount();
?>
    <div class="h1" id="device-appendix">
        Device Appendix<em> (<?php echo number_format($totalNumberOfDevices) ?> devices)</em>
    </div>

<?php
echo $this->partial('report/customer/optimization/html/device_table.phtml',
    array("title"                  => "Acceptable Devices",
          "description"            => "The following devices have been deemed productive and we suggest keeping these devices.",
          "deviceInstances"        => (isset($deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_KEEP])) ? $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_KEEP] : array(),
          "showReplacementDevices" => false,
          "hardwareOptimization"   => $hardwareOptimization,
          "totalNumberOfDevices"   => $totalNumberOfDevices,
          "showReason"             => false,
          "scrollSpyId"            => "device-appendix-acceptable",
    )
);

echo $this->partial('report/customer/optimization/html/device_table.phtml',
    array("title"                  => "Suggested Replacement Devices",
          "description"            => "The following devices have been targeted for replacement.",
          "deviceInstances"        => (isset($deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_RETIRE])) ? $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_RETIRE] : array(),
          "showReplacementDevices" => true,
          "hardwareOptimization"   => $hardwareOptimization,
          "totalNumberOfDevices"   => $totalNumberOfDevices,
          "showReason"             => true,
          "scrollSpyId"            => "device-appendix-replaced",
    )
);

echo $this->partial('report/customer/optimization/html/device_table.phtml',
    array("title"                  => "Devices eligible for retirement",
          "description"            => "Devices with both low volume and age of over " . Proposalgen_Model_DeviceInstance::RETIREMENT_AGE . " years have been target for retirement. We suggest migrating the page volume into another device.",
          "deviceInstances"        => (isset($deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_RETIRE])) ? $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_RETIRE] : array(),
          "showReplacementDevices" => false,
          "hardwareOptimization"   => $hardwareOptimization,
          "totalNumberOfDevices"   => $totalNumberOfDevices,
          "showReason"             => false,
          "scrollSpyId"            => "device-appendix-retire",
    )
);

echo $this->partial('report/customer/optimization/html/device_table.phtml',
    array("title"                  => "Devices flagged as Do Not Repair",
          "description"            => "These devices have been flagged for replacement on breakdown based on operation reliability.",
          "deviceInstances"        => (isset($deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_DNR])) ? $deviceInstances[Hardwareoptimization_Model_Hardware_Optimization_DeviceInstance::ACTION_DNR] : array(),
          "showReplacementDevices" => false,
          "hardwareOptimization"   => $hardwareOptimization,
          "totalNumberOfDevices"   => $totalNumberOfDevices,
          "showReason"             => true,
          "scrollSpyId"            => "device-appendix-dnr",
    )
);
?>