<?php
/* @var $hardwareOptimization HardwareOptimizationModel */
use MPSToolbox\Legacy\Modules\HardwareOptimization\Models\HardwareOptimizationModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\DeviceInstanceModel;
use MPSToolbox\Legacy\Modules\ProposalGenerator\Models\TonerConfigModel;

$hardwareOptimization = $this->hardwareOptimization;

$title                  = $this->title;
$description            = $this->description;
$descriptionIfZero      = $this->descriptionIfZeroDevices;
$totalNumberOfDevices   = $this->totalNumberOfDevices;
$showReplacementDevices = $this->showReplacementDevices;
$showReason             = $this->showReason;
$scrollSpyId            = $this->scrollSpyId;

/* @var $deviceInstances DeviceInstanceModel[] */
$deviceInstances = $this->deviceInstances;
?>
<div class="pheader" id="<?= $scrollSpyId; ?>">
    <?= $title; ?>
    <em> (<?= number_format(count($deviceInstances)) ?> out of <?= number_format($totalNumberOfDevices) ?> devices)</em>
</div>

<?php if (count($deviceInstances)): ?>
    <p><?= $description; ?></p>

    <table class="rDevices">
        <thead>
        <tr class="header">
            <th style="width:175px;">Device Name</th>
            <th>Serial<br />IP Address</th>
            <th>Mono AMPV</th>
            <th>Color AMPV</th>
            <th>Life Page Count</th>
            <th>Device Age</th>
            <?php if ($showReplacementDevices) : ?>
                <th style="width:175px;">Replacement Device<?= ($showReason) ? " & Reason" : "" ?></th>
            <?php else : ?>
                <?php if ($showReason) : ?>
                    <th>Reason</th>
                <?php endif; ?>
            <?php endif; ?>

        </tr>
        </thead>
        <?php foreach ($deviceInstances as $deviceInstance) :
            $masterDevice            = $deviceInstance->getMasterDevice();
            $replacementMasterDevice = $deviceInstance->getHardwareOptimizationDeviceInstance($hardwareOptimization->id)->getMasterDevice();
            $isColor                 = ($masterDevice->tonerConfigId !== TonerConfigModel::BLACK_ONLY) ? true : false;
            ?>
            <tr>
                <td class="deviceName">
                    <em><?= $masterDevice->getManufacturer()->fullname ?></em>
                    <br>
                    <strong><?= $masterDevice->modelName ?></strong>
                </td>
                <td class="serialNumber">
                    <?= $deviceInstance->serialNumber ?>
                    <br>
                    <?= $deviceInstance->ipAddress; ?>
                </td>
                <!-- Monthly Statistics -->
                <td class="pageVolume"><?= $this->formatPageVolume($deviceInstance->getPageCounts()->getBlackPageCount()->getMonthly()) ?></td>
                <td class="pageVolume"><?= ($isColor) ? $this->formatPageVolume($deviceInstance->getPageCounts()->getColorPageCount()->getMonthly()) : ' - ' ?></td>
                <td class="pageVolume"><?= $this->formatPageVolume($deviceInstance->getMeter()->endMeterLife) ?></td>
                <td class="deviceAge"><?= $deviceInstance->getAge() ?>y</td>
                <?php if ($showReplacementDevices && $replacementMasterDevice) : ?>
                    <td>
                        <em><?= $replacementMasterDevice->getManufacturer()->fullname ?></em>
                        <br>
                        <strong><?= $replacementMasterDevice->modelName ?></strong>
                        <br>
                        <?= $deviceInstance->getHardwareOptimizationDeviceInstance($hardwareOptimization->id)->getDeviceSwapReason()->reason ?>
                    </td>
                <?php elseif ($showReplacementDevices) : ?>
                    <?php if ($showReason) : ?>
                        <td class="optimizationReason"><?= $deviceInstance->getHardwareOptimizationDeviceInstance($hardwareOptimization->id)->getDeviceSwapReason()->reason ?></td>
                    <?php endif; ?>
                <?php
                else : ?>
                    <?php if ($showReason) : ?>
                        <td class="optimizationReason"><?= $deviceInstance->getHardwareOptimizationDeviceInstance($hardwareOptimization->id)->getDeviceSwapReason()->reason ?></td>
                    <?php endif; ?>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else : ?>
    <p><?= $descriptionIfZero; ?></p>
<?php endif; ?>
<br>