<?php

use MPSToolbox\Legacy\Modules\HardwareLibrary\Forms\DeviceManagement\AvailableTonersForm;

/* @var $form AvailableTonersForm */
$form = $this->element;

$id = $form->getElement('id')->getValue();
$filename = $form->getElement('imageFile')->getValue();

$form->getElement('imageUrl')->setValue('');

?>

<?= $this->RenderFormOpen($form) ?>
    <div class="clearfix">
        <fieldset>
            <div class="row">
                <div class="col-md-4 col-md-push-1">
                    <div class="form-group <?= ($form->getElement('manufacturerId')->hasErrors()) ? 'has-error has-feedback' : '' ?>">

                        <?= $this->RenderFormLabel($form->getElement('manufacturerId')) ?>

                        <select class="form-control" type="text" id="manufacturerId" name="manufacturerId"><option></option><?php foreach (\MPSToolbox\Legacy\Modules\ProposalGenerator\Mappers\ManufacturerMapper::getInstance()->fetchAllAvailableManufacturers() as $line) { ?><option value="<?= $line->id ?>" <?= $form->getElement('manufacturerId')->getValue()==$line->id?'selected="selected"':'' ?>><?php echo $line->fullname==$line->displayname?$line->fullname:$line->displayname." ({$line->fullname})" ?></option><?php } ?></select>
                        <script> require(['jquery', 'select2'], function ($) { $('#manufacturerId').select2(); }); </script>

                        <?= $this->RenderFormDescription($form->getElement('manufacturerId')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('manufacturerId')) ?>
                    </div>


                </div>
                <div class="col-md-4 col-md-push-3">
                    <div class="form-group <?= ($form->getElement('tonerColorId')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('tonerColorId')) ?>
                        <?= $this->RenderFormText($form->getElement('tonerColorId')) ?>
                        <?= $this->RenderFormDescription($form->getElement('tonerColorId')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('tonerColorId')) ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10 col-md-push-1">
                    <div class="form-group <?= ($form->getElement('yield')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('yield')) ?>
                        <?= $this->RenderFormText($form->getElement('yield'), [], null, 'pages') ?>
                        <?= $this->RenderFormDescription($form->getElement('yield')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('yield')) ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-push-1">
                    <div class="form-group <?= ($form->getElement('sku')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('sku')) ?>
                        <?= $this->RenderFormText($form->getElement('sku')) ?>
                        <?= $this->RenderFormDescription($form->getElement('sku')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('sku')) ?>
                    </div>

                    <div class="form-group <?= ($form->getElement('cost')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('cost')) ?>
                        <?= $this->RenderFormText($form->getElement('cost'), [], '$') ?>
                        <?= $this->RenderFormDescription($form->getElement('cost')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('cost')) ?>
                    </div>

                    <div class="form-group <?= ($form->getElement('name')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('name')) ?>
                        <?= $this->RenderFormText($form->getElement('name')) ?>
                        <?= $this->RenderFormDescription($form->getElement('name')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('name')) ?>
                    </div>
                </div>
                <div class="col-md-4 col-md-push-3">
                    <div class="form-group <?= ($form->getElement('dealerSku')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('dealerSku')) ?>
                        <?= $this->RenderFormText($form->getElement('dealerSku')) ?>
                        <?= $this->RenderFormDescription($form->getElement('dealerSku')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('dealerSku')) ?>
                    </div>

                    <div class="form-group <?= ($form->getElement('dealerCost')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('dealerCost')) ?>
                        <?= $this->RenderFormText($form->getElement('dealerCost'), [], '$') ?>
                        <?= $this->RenderFormDescription($form->getElement('dealerCost')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('dealerCost')) ?>
                    </div>

                    <div class="form-group <?= ($form->getElement('dealerSrp')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('dealerSrp')) ?>
                        <?= $this->RenderFormText($form->getElement('dealerSrp'), [], '$') ?>
                        <?= $this->RenderFormDescription($form->getElement('dealerSrp')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('dealerSrp')) ?>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-push-1">
                    <div class="form-group <?= ($form->getElement('imageUrl')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                        <?= $this->RenderFormLabel($form->getElement('imageUrl')) ?>
                        <?= $this->RenderFormText($form->getElement('imageUrl')) ?>
                        <?= $this->RenderFormDescription($form->getElement('imageUrl')) ?>
                        <?= $this->RenderFormElementErrors($form->getElement('imageUrl')) ?>
                    </div>

<?php if ($id) { ?>
                    <div class="form-group">
                        <?= $this->RenderFormLabel($form->getElement('imageFile')) ?>
                        <input id="fileupload" type="file" name="imageFile" data-url="<?= $this->url(['id' => $id], 'hardware-library.toners.image'); ?>">
                    </div>
<?php } ?>
                </div>
                <div class="col-md-4 col-md-push-3">
                    <div id="imageDiv">
                        <?php if ($filename) { ?>
                            <a href="/img/toners/<?php echo $filename ?>" target="_blank" class="thumbnail">
                                <img src="/img/toners/<?php echo $filename ?>" style="max-width:250px;max-height:250px">
                            </a>
                        <?php } ?>
                    </div>
                </div>
            </div>

        </fieldset>
    </div>
    <fieldset>
        <?= $this->RenderFormHidden($form->getElement('saveAndApproveHdn')) ?>
        <?= $this->RenderFormHidden($form->getElement('id')) ?>
    </fieldset>
<?= $this->RenderFormClose($form) ?>

<script>
    $(function () {
        $('#fileupload').fileupload({
            dataType: 'json',
            done: uploadDone
        });
    });
</script>