<?php

use MPSToolbox\Legacy\Modules\HardwareLibrary\Forms\DeviceManagement\DistributorsForm;

/* @var $form DistributorsForm */
$form = $this->element;

if (!$form->getView()->masterDevice || !$form->getView()->masterDevice->id) {
    return;
}

$distributors = DistributorsForm::getDistributors($form->getView()->masterDevice);
$services = DistributorsForm::getServices($form->getView()->masterDevice);

?>
<div class="row">
    <div class="col-md-3">
        <h5>Distributor price and availability</h5>
    </div>
    <div class="col-md-9">
        <table class="table">
            <colgroup>
                <col width="40%" />
                <col width="20%" />
                <col width="20%" />
                <col width="20%" />
            </colgroup>
            <thead>
            <tr>
                <th>Distributor</th>
                <th>Distributor SKU</th>
                <th>Price</th>
                <th>Stock</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($distributors as $line) { ?>
                <tr>
                    <td><?= $line['name'] ?></td>
                    <td><?= $line['sku'] ?></td>
                    <td><?= $line['price'] ?></td>
                    <td><?= $line['stock'] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-3">
        <h5>Service</h5>
    </div>
    <div class="col-md-9">
        <table class="table">
            <colgroup>
                <col width="40%" />
                <col width="20%" />
                <col width="20%" />
                <col width="10%" />
                <col width="10%" />
            </colgroup>
            <thead>
            <tr>
                <th>Distributor</th>
                <th>Vendor SKU</th>
                <th>Distributor SKU</th>
                <th>Price</th>
                <th></th>
            </tr>
            </thead>
            <tbody id="service-tbody">
            <?php foreach ($services as $line) { ?>
                <tr>
                    <td><?= $line['supplier'] ?></td>
                    <td><?= $line['sku'] ?></td>
                    <td><?= $line['part_number'] ?></td>
                    <td><?= $line['price'] ?></td>
                    <td><a href="javascript:" onclick="deleteService(<?= $line['id'] ?>)">delete</a></td>
                </tr>
            <?php } ?>
            </tbody>
            <tfoot id="service-tfoot" style="display:none">
                <tr>
                    <td><select class="form-control" id="service-supplier">
<?php
$db = Zend_Db_Table::getDefaultAdapter();
foreach ($db->query('select * from suppliers order by name')->fetchAll() as $line) {
    echo '<option value="'.$line['id'].'">'.$line['name'].'</option>';
}
?>
                        </select></td>
                    <td><input class="form-control" type="text" id="service-sku"></td>
                    <td colspan="2">
                        <button type="button" class="btn btn-primary" onclick="addService()">Add</button>
                        &nbsp;&nbsp;
                        <a href="javascript:;" onclick="$('#service-tfoot').hide()">cancel</a>
                    </td>
                </tr>
            </tfoot>
        </table>
        <a href="javascript:;" class="btn btn-default" onclick="$('#service-tfoot').show()">+ Add</a>
    </div>
</div>
<script>
    function updateServices(response) {
        var tr = '';
        $.each(response, function(i,e) {
            tr += '<tr>';
            tr += '<td>'+e.supplier+'</td>';
            tr += '<td>'+e.sku+'</td>';
            tr += '<td>'+e.part_number+'</td>';
            tr += '<td>'+e.price+'</td>';
            tr += '<td><a href="javascript:" onclick="deleteService('+ e.id+')">delete</a></td>';
            tr += '</tr>';
        });
        $('#service-tbody').html(tr);
    }
    function deleteService(id) {
        $.post('/hardware-library/manage-devices/delete-service', {id:id, masterDeviceId:<?= $form->getView()->masterDevice->id ?>}, updateServices, 'json');
    }
    function addService() {
        var supplier = $('#service-supplier').val();
        var sku = $.trim($('#service-sku').val());
        if (sku=='') {
            alert('Enter a SKU');
            return;
        }
        $.post('/hardware-library/manage-devices/add-service', {supplier:supplier, sku:sku, masterDeviceId:<?= $form->getView()->masterDevice->id ?>}, updateServices, 'json');
        $('#service-supplier').val('');
        $('#service-sku').val('');
        $('#service-tfoot').hide();
    }
</script>


