<?php

use MPSToolbox\Legacy\Modules\HardwareLibrary\Forms\DeviceManagement\DistributorsForm;

/* @var $form DistributorsForm */
$form = $this->element;
$distributors = DistributorsForm::getDistributors($form->getView()->masterDevice);

?>
<div class="row">
    <div class="col-md-10 col-md-push-1">
        <table class="table">
            <colgroup>
                <col width="40%" />
                <col width="20%" />
                <col width="20%" />
                <col width="20%" />
            </colgroup>
            <thead>
            <tr>
                <th>Distributor</th>
                <th>Distributor SKU</th>
                <th>Price</th>
                <th>Stock</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($distributors as $line) { ?>
                <tr>
                    <td><?= $line['name'] ?></td>
                    <td><?= $line['sku'] ?></td>
                    <td><?= $line['price'] ?></td>
                    <td><?= $line['stock'] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>


