<?php

use MPSToolbox\Legacy\Modules\HardwareLibrary\Forms\DeviceManagement\HardwareQuoteForm;

/* @var $form HardwareQuoteForm */
$form = $this->element;

$dealerSettings = \MPSToolbox\Settings\Entities\DealerSettingsEntity::with('ShopSettings')->find(Zend_Auth::getInstance()->getIdentity()->dealerId);
$shopSettings = $dealerSettings->shopSettings;

?>

<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>
<div class="clearfix">
    <fieldset class="col-md-10 col-md-offset-1">
        <div class="form-group <?= ($form->getElement('isSelling')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('isSelling'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormBootstrapSwitch($form->getElement('isSelling'), ['js-yes-no-switch']) ?>
                <?= $this->RenderFormDescription($form->getElement('isSelling')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('isSelling')) ?>
            </div>
        </div>

        <div class="form-group <?= ($form->getElement('oemSku')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('oemSku'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormText($form->getElement('oemSku')) ?>
                <?= $this->RenderFormDescription($form->getElement('oemSku')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('oemSku')) ?>
            </div>
        </div>

        <div class="form-group <?= ($form->getElement('dealerSku')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('dealerSku'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormText($form->getElement('dealerSku')) ?>
                <?= $this->RenderFormDescription($form->getElement('dealerSku')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('dealerSku')) ?>
            </div>
        </div>

        <div class="form-group <?= ($form->getElement('cost')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('cost'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormText($form->getElement('cost'), null, '$') ?>
                <?= $this->RenderFormDescription($form->getElement('cost')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('cost')) ?>
            </div>
        </div>

        <?php if ($shopSettings->shopifyName!='') { ?>
            <div class="form-group <?= ($form->getElement('srp')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                <?= $this->RenderFormLabel($form->getElement('srp'), ['col-md-4']) ?>

                <div class="col-md-6">
                    <?= $this->RenderFormText($form->getElement('srp'), null, '$') ?>
                    <?= $this->RenderFormDescription($form->getElement('srp')) ?>
                    <?= $this->RenderFormElementErrors($form->getElement('srp')) ?>
                </div>
            </div>

            <div class="form-group <?= ($form->getElement('rent')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                <?= $this->RenderFormLabel($form->getElement('rent'), ['col-md-4']) ?>

                <div class="col-md-6">
                    <?= $this->RenderFormText($form->getElement('rent'), null, '$') ?>
                    <?= $this->RenderFormDescription($form->getElement('rent')) ?>
                    <?= $this->RenderFormElementErrors($form->getElement('rent')) ?>
                </div>
            </div>

            <div class="form-group <?= ($form->getElement('pagesPerMonth')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                <?= $this->RenderFormLabel($form->getElement('pagesPerMonth'), ['col-md-4']) ?>

                <div class="col-md-6">
                    <?= $this->RenderFormText($form->getElement('pagesPerMonth')) ?>
                    <?= $this->RenderFormDescription($form->getElement('pagesPerMonth')) ?>
                    <?= $this->RenderFormElementErrors($form->getElement('pagesPerMonth')) ?>
                </div>
            </div>

            <div class="form-group <?= ($form->getElement('dataSheetUrl')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                <?= $this->RenderFormLabel($form->getElement('dataSheetUrl'), ['col-md-4']) ?>

                <div class="col-md-6">
                    <?= $this->RenderFormText($form->getElement('dataSheetUrl')) ?>
                    <?= $this->RenderFormDescription($form->getElement('dataSheetUrl')) ?>
                    <?= $this->RenderFormElementErrors($form->getElement('dataSheetUrl')) ?>
                </div>
            </div>

            <div class="form-group <?= ($form->getElement('reviewsUrl')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                <?= $this->RenderFormLabel($form->getElement('reviewsUrl'), ['col-md-4']) ?>

                <div class="col-md-6">
                    <?= $this->RenderFormText($form->getElement('reviewsUrl')) ?>
                    <?= $this->RenderFormDescription($form->getElement('reviewsUrl')) ?>
                    <?= $this->RenderFormElementErrors($form->getElement('reviewsUrl')) ?>
                </div>
            </div>
        <?php } ?>

        <div class="form-group <?= ($form->getElement('description')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('description'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormTextArea($form->getElement('description')) ?>
                <?= $this->RenderFormDescription($form->getElement('description')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('description')) ?>
            </div>
        </div>
    </fieldset>
</div>
<?= $this->RenderFormClose($form) ?>
