<?php

use MPSToolbox\Legacy\Modules\HardwareLibrary\Forms\DeviceManagement\HardwareQuoteForm;

/* @var $form HardwareQuoteForm */
$form = $this->element;
?>

<?= $this->RenderFormOpen($form, ['form-horizontal']) ?>
<div class="clearfix">
    <fieldset class="col-md-10 col-md-offset-1">
        <div class="form-group <?= ($form->getElement('isSelling')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('isSelling'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormBootstrapSwitch($form->getElement('isSelling'), ['js-yes-no-switch']) ?>
                <?= $this->RenderFormDescription($form->getElement('isSelling')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('isSelling')) ?>
            </div>
        </div>

        <div class="form-group <?= ($form->getElement('oemSku')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('oemSku'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormText($form->getElement('oemSku')) ?>
                <?= $this->RenderFormDescription($form->getElement('oemSku')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('oemSku')) ?>
            </div>
        </div>

        <div class="form-group <?= ($form->getElement('dealerSku')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('dealerSku'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormText($form->getElement('dealerSku')) ?>
                <?= $this->RenderFormDescription($form->getElement('dealerSku')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('dealerSku')) ?>
            </div>
        </div>

        <div class="form-group <?= ($form->getElement('cost')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('cost'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormText($form->getElement('cost')) ?>
                <?= $this->RenderFormDescription($form->getElement('cost')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('cost')) ?>
            </div>
        </div>

        <div class="form-group <?= ($form->getElement('description')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
            <?= $this->RenderFormLabel($form->getElement('description'), ['col-md-4']) ?>

            <div class="col-md-6">
                <?= $this->RenderFormTextArea($form->getElement('description')) ?>
                <?= $this->RenderFormDescription($form->getElement('description')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('description')) ?>
            </div>
        </div>
    </fieldset>
</div>
<?= $this->RenderFormClose($form) ?>
