<?php

use MPSToolbox\Legacy\Modules\HardwareLibrary\Forms\DeviceManagement\HardwareConfigurationsForm;

/* @var $form HardwareConfigurationsForm */
$form           = $this->element;
$masterDeviceId = $this->masterDeviceId;

?>

<?= $this->RenderFormOpen($form) ?>
    <div class="clearfix">
        <fieldset class="col-md-10 col-md-offset-1">
            <div class="form-group <?= ($form->getElement('hardwareConfigurationsname')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                <?= $this->RenderFormLabel($form->getElement('hardwareConfigurationsname')) ?>
                <?= $this->RenderFormText($form->getElement('hardwareConfigurationsname')) ?>
                <?= $this->RenderFormDescription($form->getElement('hardwareConfigurationsname')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('hardwareConfigurationsname')) ?>
            </div>

            <div class="form-group <?= ($form->getElement('hardwareConfigurationsdescription')->hasErrors()) ? 'has-error has-feedback' : '' ?>">
                <?= $this->RenderFormLabel($form->getElement('hardwareConfigurationsdescription')) ?>
                <?= $this->RenderFormTextArea($form->getElement('hardwareConfigurationsdescription')) ?>
                <?= $this->RenderFormDescription($form->getElement('hardwareConfigurationsdescription')) ?>
                <?= $this->RenderFormElementErrors($form->getElement('hardwareConfigurationsdescription')) ?>
            </div>
            <?php $form->getDisplayGroup('optionsGroup') ?>
            <?= $this->formHidden($form->getElement('hardwareConfigurationsid')) ?>
        </fieldset>
    </div>
<?= $this->RenderFormClose($form) ?>