<?php

use MPSToolbox\Legacy\Modules\HardwareLibrary\Forms\DeviceManagement\HistoryForm;

/* @var $form HistoryForm */
$form = $this->element;
$history = HistoryForm::getHistory($form->getView()->masterDevice);

?>
<div class="clearfix" style="max-height:600px;overflow:auto;">
            <table class="table">
                <colgroup>
                    <col width="25%" />
                    <col width="25%" />
                    <col width="50%" />
                </colgroup>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>User</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
<?php foreach ($history as $line) { ?>
                    <tr>
                        <td><?= $line['date'] ?></td>
                        <td><?= $line['user'] ?></td>
                        <td><?= $line['action'] ?></td>
                    </tr>
<?php } ?>
                </tbody>
            </table>
</div>


