<div class="page-header">
    <a class="btn btn-success btn-small pull-right create-button" href="<?php echo $this->url(array('action' => 'create')) ?>"> <i class="icon-white icon-plus-sign"></i> Create new</a>
    <h1>Role Management (Beta)</h1>
</div>
<div class="well">
    <table class="table table-bordered table-condensed table-striped">
        <tr>
            <th>Role Name</th>
            <th style="width: 60px;">Actions</th>
        </tr>
        <?php foreach ($this->roles as $role) : /* @var $role Admin_Model_Role */?>
        <tr>
            <td><?php echo $role->getName(); ?></td>
            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'roleId' => $role->getId())); ?>" class="btn btn-warning btn-mini" title="Edit Role"><i class="icon-pencil"></i></a>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'roleId' => $role->getId())); ?>" class="btn btn-danger btn-mini" title="Delete Role"><i class="icon-trash"></i></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>