<div class="page-header">
    <h1>Role Management (Beta)</h1>
</div>
<div class="well">
<?php echo $this->form; ?>
</div>
<hr>
<?php if (count($this->roles) > 0) : ?>
<?php foreach ($this->roles as $role) : /* @var $role Admin_Model_Role */?>
<h3><?php echo $role->getName(); ?></h3>
<div class="well">
<h4>Permissions</h4>
    <?php foreach ($role->getPrivileges() as $privilege) : /* @var $privilege Admin_Model_Privilege */ ?>
    <ul>
        <li><?php echo $privilege->getModule();?>__<?php echo $privilege->getController();?>__<?php echo $privilege->getAction();?></li>
    </ul>
    <?php endforeach; ?>
</div>
<?php endforeach; ?>
<?php else :?>
<h3>Sorry, no roles could be found in the system!</h3>
<?php endif; ?>