<?php

/**
 * Companies Form: Used for Adding / Editing Companies
 *
 * @author John Sadler
 * @version v1.0
 */
class Proposalgen_Form_Companies extends Zend_Form
{

    /**
     * Constructor builds the form
     * 
     * @param $options -
     *            not used (required)
     * @param $type -
     *            can be set to 'edit', or null. Differnt form elements are added for editing an instructor and adding a
     *            new instructor.
     * @return HTML markup for the from is automatically returned by zend_form
     */
    public function __construct ($options = null, $type = null)
    {
        //call parent contsructor
        parent::__construct($options);
        $elements = array ();
        $elementCounter = 0;
        
        $this->setName('companies_form');
        $this->setAttrib('id', 'companies_form');
        
        //company selection list
        $select_company = new Zend_Form_Element_Select('select_company');
        $select_company->setLabel('Select Company:')
            ->setOrder($elementCounter)
            ->setAttrib('style', 'width:300px')
            ->setAttrib('class', 'select_company')
            ->setAttrib('id', 'select_company');
        array_push($elements, $select_company);
        $elementCounter ++;
        
        //company name
        $company_name = new Zend_Form_Element_Text('company_name');
        $company_name->setLabel('* Company Name:')
            ->setRequired(true)
            ->setAttrib('size', 50)
            ->setAttrib('maxlength', 50)
            ->setOrder($elementCounter)
            ->setAttrib('id', 'company_name');
        array_push($elements, $company_name);
        $elementCounter ++;
        
        //pricing margin
        $pricing_margin = new Zend_Form_Element_Text('pricing_margin');
        $pricing_margin->setLabel('* Pricing Margin:')
            ->addValidator(new Zend_Validate_Float())
            ->addValidator(new Zend_Validate_NotEmpty())
            ->setRequired(true)
            ->setValue('25')
            ->setAttrib('size', 2)
            ->setAttrib('maxlength', 10)
            ->setAttrib('style', 'text-align: right')
            ->setOrder($elementCounter)
            ->setAttrib('id', 'pricing_margin')
            ->setAttrib('onkeypress', 'javascript: return numbersonly(this, event)')
            ->setDescription('%')
            ->setDecorators(array (
                'ViewHelper', 
                array (
                        'Description', 
                        array (
                                'escape' => false, 
                                'tag' => false 
                        ) 
                ), 
                'Errors', 
                array (
                        'HtmlTag', 
                        array (
                                'tag' => 'dd', 
                                'id' => 'pricing_margin-element' 
                        ) 
                ), 
                array (
                        'Label', 
                        array (
                                'tag' => 'dt' 
                        ) 
                ) 
        ));
        $pricing_margin->getValidator('NotEmpty')->setMessage('Must not be empty.');
        $pricing_margin->getValidator('Float')->setMessage('Please enter a number.');
        array_push($elements, $pricing_margin);
        $elementCounter ++;
        
        //save button
        $save_company = new Zend_Form_Element_Submit('save_company', array (
                'disableLoadDefaultDecorators' => true 
        ));
        $save_company->setLabel('Save')
            ->setOrder($elementCounter)
            ->setDecorators(array (
                'ViewHelper', 
                'Errors', 
                array (
                        array (
                                'dd' => 'HtmlTag' 
                        ), 
                        array (
                                'tag' => 'dd', 
                                'class' => 'botMenu' 
                        ) 
                ) 
        ));
        array_push($elements, $save_company);
        $elementCounter ++;
        
        //delete button
        $delete_company = new Zend_Form_Element_Submit('delete_company', array (
                'disableLoadDefaultDecorators' => true 
        ));
        $delete_company->setLabel('Delete')
            ->setOrder($elementCounter)
            ->setAttrib('onclick', 'javascript: return confirm("Deleting a company will also delete any users assigned to the company and any reports generated by those users. Are you sure you want to delete this company?");')
            ->setDecorators(array (
                'ViewHelper', 
                'Errors', 
                array (
                        array (
                                'dd' => 'HtmlTag' 
                        ), 
                        array (
                                'tag' => 'dd', 
                                'class' => 'botMenu' 
                        ) 
                ) 
        ));
        array_push($elements, $delete_company);
        $elementCounter ++;
        
        //back button
        $back_button = new Zend_Form_Element_Button('back_button');
        $back_button->setLabel('Done')
            ->setOrder($elementCounter)
            ->setAttrib('onClick', 'javascript: document.location.href="../admin";')
            ->setDecorators(array (
                'ViewHelper', 
                'Errors', 
                array (
                        array (
                                'dd' => 'HtmlTag' 
                        ), 
                        array (
                                'tag' => 'dd', 
                                'class' => 'botMenu' 
                        ) 
                ) 
        ));
        array_push($elements, $back_button);
        $elementCounter ++;
        
        //add all defined elements to the form
        $this->addElements($elements);
    } //end function __construct
}
?>

