<div class="row">
    <div class="span10">
        <div class="well">
            <?php echo $this->form ?>
        </div>
    </div>
    <div class="span2">
        <div id="surveyNavbar" data-spy="affix" data-offset-top="122" >
            <ul id="surveyNav" class="nav nav-list">
                <li class="active"><a href="#surveyFinanceSection">Finance</a></li>
                <li><a href="#surveyPurchasingSection">Purchasing</a></li>
                <li><a href="#surveyItSection">IT</a></li>
                <li><a href="#surveyUsersSection">Users</a></li>
            </ul>
        </div>
    </div>
</div>