<?php
if ($this->isPDF)
{
    echo '<link rel="stylesheet" type="text/css" href="' . $this->FullUrl($this->theme("proposalgenerator/reports/common_all.css")) . '" />';
    echo '<link rel="stylesheet" type="text/css" href="' . $this->FullUrl($this->theme("proposalgenerator/reports/assessment/assessment_pdf.css")) . '" />';
}
else
{
    $this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/common_all.css"));
    $this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/common_html.css"));
    $this->headLink()->appendStylesheet($this->theme("proposalgenerator/reports/assessment/assessment_html.css"));
    // Title page image
    echo '<style type="text/css">
			div.titlepage {
				height: 500px;
				padding-left: 300px;
				padding-top: 350px;
				background-image: url(' . $this->FullUrl($this->theme("proposalgenerator/reports/images/assessment.jpg")) . ');
				background-repeat: no-repeat;
			}
		 </style>';
}
$data = array (
        "proposal" => $this->proposal, 
        "isPDF" => $this->isPDF, 
        "backleft" => $this->backleft, 
        "backright" => $this->backright, 
        "backtop" => $this->backtop, 
        "backbottom" => $this->backbottom, 
        "footer" => $this->footer, 
        "pagestyle" => $this->pagestyle, 
        "titlePageStart" => $this->titlePageStart, 
        "pageStart" => $this->pageStart, 
        "pageEnd" => $this->pageEnd, 
        "noBreakStart" => $this->noBreakStart, 
        "noBreakEnd" => $this->noBreakEnd, 
        "orientation" => $this->orientation 
);
echo $this->partial('report/assessment/01_Title.phtml', $data);
echo $this->partial('report/assessment/02_Scorecard.phtml', $data);
echo $this->partial('report/assessment/03_ServiceAndSuppliesLogistics.phtml', $data);
echo $this->partial('report/assessment/04_PrintingHardwareUsage.phtml', $data);
echo $this->partial('report/assessment/05_TechnologyReliabilityAndUserProductivity.phtml', $data);
echo $this->partial('report/assessment/06_EnvironmentalImpact.phtml', $data);
echo $this->partial('report/assessment/07_Expense.phtml', $data);
echo $this->partial('report/assessment/08_Summary.phtml', $data);

?>