<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
?>

<br>
<br>
<p style="text-align: left">
	<em>Please select a report from the list below. After verifying the
		contents of your reports, you may download <br> a copy by selecting
		your desired output format from top right corner of each report.
	</em>
</p>

<br />

<div style='margin-left: 145px;'>
	<select id="availableReports" style='margin-top: 5px;'>
    <?php foreach ($this->availableReports as $report) : ?>
    <option value='<?php echo $report->url; ?>'
			<?php echo ($report->active) ? "selected='selected'" : "";?>><?php echo $report->pagetitle; ?></option>
    <?php endforeach; ?>
</select>
	<button id='viewReportButton'>View Report</button>
</div>
