<?php 
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->proposal;
?>
<table style="width: 100%;border-collapse: collapse; table-layout: fixed">
	<tr>
		<td class = "Title"><u><?php echo $this->formTitle?></u></td>
		<?php if ($this->companyName) :?>
		<td class = "PreparedFor"><i>Prepared For:</i></td>
		<td class = "PreparedForText"><i><?php echo $this->companyName; ?></i></td>
		<?php endif?>
	</tr>
</table>

<br>
<p style="text-align: left">
<em>Please select a report from the list below.  After verifying the contents of your reports, you may download <br>
a copy by selecting your desired output format from top right corner of each report. </em>
</p>

<div class="well">
	<select id="availableReports" style='margin-top: 5px;'>
	    <?php foreach ($this->availableReports as $report) : ?>
	    <option value='<?php echo $report->url; ?>' <?php echo ($report->active) ? "selected='selected'" : "";?>><?php echo $report->pagetitle; ?></option>
	    <?php endforeach; ?>
	</select>
	<button id='viewReportButton'>View Report</button>
</div>