<div class="page-header">
    <h1>Hardware Library</h1>
</div>

<?php if ($this->isAllowed(Quotegen_Model_Acl::RESOURCE_QUOTEGEN_DEVICESETUP_INDEX)) : ?>
    <a class="btn" href="<?php echo $this->url(array("action" => "index", "controller" => "devicesetup", "module" => "quotegen")); ?>"><i class="icon-print icon-4x"></i><br /><br />
        All Devices<br /><br /> </a>
<?php endif; ?>

<?php if ($this->isAllowed(Quotegen_Model_Acl::RESOURCE_QUOTEGEN_CONFIGURATION_WILDCARD)) : ?>
    <a class="btn" href="<?php echo $this->url(array("action" => "index", "controller" => "configuration", "module" => "quotegen")); ?>"><i class="icon-print icon-4x"></i><br /><br />
        Hardware Quote <br /> Device Configurations</a>
<?php endif; ?>

<?php if ($this->isAllowed(Quotegen_Model_Acl::RESOURCE_QUOTEGEN_OPTION_WILDCARD)) : ?>
    <a class="btn" href="<?php echo $this->url(array("action" => "index", "controller" => "option", "module" => "quotegen")); ?>"><i class="icon-print icon-4x"></i><br /><br />
        Hardware Quote <br /> Device Options</a>
<?php endif; ?>

<?php if ($this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_COSTS_BULKDEVICEPRICING)) : ?>
    <a class="btn" href="<?php echo $this->url(array("action" => "bulkdevicepricing", "controller" => "admin", "module" => "proposalgen")); ?>"><i class="icon-money icon-4x"></i><br /><br />
        Bulk Pricing Updates<br /> <br /> </a>
<?php endif; ?>

<?php if ($this->isAllowed(Proposalgen_Model_Acl::RESOURCE_PROPOSALGEN_ADMIN_MANAGEREPLACEMENTS)) : ?>
    <a class="btn" href="<?php echo $this->url(array("action" => "managereplacements", "controller" => "admin", "module" => "proposalgen")); ?>"><i class="icon-print icon-4x"></i><br /><br />
        Replacement Devices<br /> <br /> </a>
<?php endif; ?>