<?php
/* @var $proposal Proposalgen_Model_Proposal_OfficeDepot */
$proposal = $this->healthcheck->proposal;
?>
<div class="titlepage">
    <div class="header">
        <img class="title-page-logo" src="<?php echo $this->serverUrl($this->theme("proposalgenerator/reports/images/595x300.gif")) ?> " />
        <h3>Prepared for:
            <?php
            if (strlen($proposal->report->getClient()->companyName) > 26)
            {
                echo "<br/>";
            }

            echo $proposal->report->getClient()->companyName;
            ?>
        </h3>
        <h3><?php echo $proposal->getDateReportPrepared(); ?></h3>
    </div>
    <div class="customerdetails">
        <p><?php echo nl2br($proposal->report->getClient()->getAddress()); ?></p>
    </div>
</div>