<div class="container health-check" id="htmlReportContainer">
    <?php
    $this->reportName = My_Brand::$companyName;
    $this->jitName = My_Brand::$jitName;
    $this->jitFullName = My_Brand::$jitFullName;

    $this->headLink()->appendStylesheet($this->baseUrl("css/reports/reports.css"));
    echo $this->render('report/printiq/healthcheck/html/01_Title.phtml');
    echo $this->render('report/printiq/healthcheck/html/02_Scorecard.phtml');
    echo $this->render('report/printiq/healthcheck/html/03_ServiceAndSuppliesLogistics.phtml');
    echo $this->render('report/printiq/healthcheck/html/04_OemVsCompatible.phtml');
    echo $this->render('report/printiq/healthcheck/html/05_PrintingHardwareUsage.phtml');
    echo $this->render('report/printiq/healthcheck/html/06_TechnologyReliabilityAndUserProductivity.phtml');
    echo $this->render('report/printiq/healthcheck/html/07_EnvironmentalImpact.phtml');
    echo $this->render('report/printiq/healthcheck/html/08_FleetAttributes.phtml');
    echo $this->render('report/printiq/healthcheck/html/09_Summary.phtml');
    ?>
</div>