<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs = $healthcheckViewModel->getGraphs();
?>
<div class="h1">Analysis: Service and Supplies Logistics</div>
<div class="pheader">Printing Device Management Breakdown</div>
<p>Printing devices can be managed in different ways; networked printers can be managed with remote monitoring software; leased multifunction devices can be managed by a dealer who sold the machine; and devices not connected to the network, such as inkjets and some older printers, are difficult to manage because they may not be capable for remote monitoring.</p>
<br />
<p>See below for results in your environment:</p>
<div class="center">
    <table>
        <tbody>
        <tr>
            <td><img src="<?php echo $graphs['UnmanagedVsManagedDevices']; ?>" /></td>
            <!-- Devices leased/Devices Purchased -->
            <td><img src="<?php echo $graphs['PagesWithOrWithoutJIT']; ?>" /></td>
            <!-- Monthly pages on leased MFPs/Monthly pages on devices not leased -->
        </tr>
        </tbody>
    </table>
</div>
<div class="pheader">Number of Printing Device Models and Supply Types</div>
<p>Out of your
    <strong><?php echo $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount(); ?></strong> networked printing devices, you have of
    <strong><?php echo $healthcheckViewModel->getNumberOfUniqueModels(); ?></strong> different models. Each section of the chart below represents a single model type.
</p>
<div class="center">
    <img src="<?php echo $graphs['UniqueDevicesGraph'] ?>" /> <!--  Giant pie chart -->
</div>
<?php
$uniqueDeviceArray = $healthcheckViewModel->getUniqueDeviceCountArray();
$totalAmount = $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount();
$amountOfRows = ceil(count($uniqueDeviceArray) / 2);

//FirstHalf is whether we are writing to the left side of the table or the right side.
$firstColumn = true;
$colorCounter = 0;

$tableData = array();

?>
<table class="table-bordered" style="border-collapse: collapse;">
    <?php

    $counter = 0;
    foreach ($uniqueDeviceArray as $key => $deviceCount)
    {
        if ($counter < $amountOfRows)
        {
            $tableData[$counter]["column1"] = array(
                "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
                "name"    => $key . " (" . $deviceCount . ")",
                "percent" => number_format(($deviceCount / $totalAmount) * 100, 1) . "%",
            );
        }
        else
        {
            $tableData[$counter - $amountOfRows]["column2"] = array(
                "color"   => Healthcheck_ViewModel_Healthcheck::$COLOR_ARRAY[$counter],
                "name"    => $key . " (" . $deviceCount . ")",
                "percent" => number_format(($deviceCount / $totalAmount) * 100, 1) . "%",
            );

        }
        $counter++;
    }
    ?>
    <?php foreach ($tableData as $row) : ?>
        <tr>
            <?php if (array_key_exists("column1", $row)) : ?>
                <td style="border:1px solid">
                    <div style="width:20px;height:20px;margin: auto;background-color:#<?= $row["column1"]["color"]; ?>"></div>
                </td>
                <td style="border:1px solid"><?= $row["column1"]["name"]; ?></td>
                <td style="border:1px solid"><?= $row["column1"]["percent"] ?></td>
            <?php else : ?>
                <td colspan="3">&nbsp;</td>
            <?php endif; ?>


            <?php if (array_key_exists("column2", $row)) : ?>
                <td style="border:1px solid">
                    <div style="width:20px;height:20px;margin: auto;background-color:#<?= $row["column2"]["color"]; ?>"></div>
                </td>
                <td style="border:1px solid"><?= $row["column2"]["name"]; ?></td>
                <td style="border:1px solid"><?= $row["column2"]["percent"] ?></td>
            <?php else : ?>
                <td colspan="3">&nbsp;</td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
</table>
<p>By using printing devices that use the same supplies, you can reduce the amount of cash tied up in supplies inventory and the amount of storage space required. <?php echo My_Brand::$companyName; ?> can provide you with just-in-time supplies fulfillment, which can further reduce your inventory requirements and emergency supply orders.</p>

<div class="pheader">Number of Printing Vendors</div>
<p>Out of your <?php echo count($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getDeviceInstances()) ?>
    networked printing devices, you have <strong>
        <?php echo count($healthcheckViewModel->getDeviceVendorCount());
        ?></strong> different vendors. Each section of the chart below represents a single vendor name.

<div class="center">
    <img src="<?php echo $graphs['PercentPerDeviceBrand']; ?>" />
</div>

<div class="pheader">Number of Printing Devices Compatible with <?php echo My_Brand::$companyNameFull; ?></div>
<p>Out of your <?php echo $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount(); ?>
    networked printing devices, you have
    <strong><?php echo count($healthcheckViewModel->getIsManagedDevices()); ?></strong> devices that are managed,  <?php echo count($healthcheckViewModel->getUnManagedDevices()); ?> devices that are not compatible and <?php echo count($healthcheckViewModel->getUnmanagedJitCompatibleDevices()) ?> devices compatible with <?php echo $this->jitFullName ?>. These non compatible devices are shown in the fleet attributes section below. A complete list of all devices and their <?php echo $this->jit ?> compatibility can be found in the Appendix.
</p>
<br />
<div class="center">
    <table>
        <tbody>
        <tr>
            <td><img src="<?php echo $graphs['UnmanagedVsManagedDevices']; ?>" /></td>
            <!-- Devices leased/Devices Purchased -->
            <td><img src="<?php echo $graphs['PagesWithOrWithoutJIT']; ?>" /></td>
            <!-- Monthly pages on leased MFPs/Monthly pages on devices not leased -->
        </tr>
        </tbody>
    </table>
</div>

<div class="pheader">Estimated OEM Toner Costs vs. Compatible Toner Costs</div>
<p>From the review of your toner purchases, you are saving <?php echo $this->currency($healthcheckViewModel->calculateDifferenceBetweenOemTotalCostMonthlyAndCompMonthly());?> a month by moving from OEM to a compatible toner. Over the next 12 months you can save approximately <?php echo $this->currency($healthcheckViewModel->calculateDifferenceBetweenOemTotalCostAnnuallyAndCompAnnually())?>. That is a <?php echo number_format($healthcheckViewModel->calculateDifferencePercentageBetweenOemTotalCostAnnuallyAndCompAnnually() * 100);?>% savings for that time period.</p>