<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs = $healthcheckViewModel->getGraphs();
?>
<div class="h1">Analysis: Technology Reliability and User Productivity</div>
<div class="pheader">Age of Printing Devices</div>
<p>We estimate the average age of your printing devices is <?php echo number_format($healthcheckViewModel->getAverageAgeOfDevices(), 1) ?> years(s); a good industry average is 3 years. Devices over 5 years old receive, on average, one repair per year.</p>
<p>The breakdown of the age of your printing devices is shown below.</p>
<div class="center">
    <img src="<?php echo $graphs['PrintIQAgePieGraph']; ?>" />
    <img src="<?php echo $graphs['PrintIQPagesPrintedByAgeBarGraph']; ?>" />
</div>
<br />
<br />
<?php echo $this->noBreakEnd; ?>
<?php echo $this->noBreakStart; ?>
<div class="pheader">Technology Features and Functionality</div>
<p>The ability to scan and fax documents from convenient locations helps to improve document workflow and productivity, and scanning can also help reduce the number of pages printed. Color printing capabilities are important if you are generating client-facing or other important documents in-house.</p>
<p>The charts below show the percentage of your printing devices that are capable of copying, duplex printing, and color printing.</p>
<br />
<img src="<?php echo $graphs['CopyCapableDevicesGraph']; ?>" style="width: 190px; height: 150px;" /> <!-- Copy capable devices -->
<img src="<?php echo $graphs['DuplexCapableDevicesGraph']; ?>" style="width: 190px; height: 150px;" /> <!-- Duplex capable devices -->
<img src="<?php echo $graphs['colorCapablePieChart']; ?>" style="width: 190px; height: 150px;" /> <!-- Color capable devices -->
<br />
<br />
<p>If you are in need of additional features and functionality to improve workflow and print quality, <?php echo $this->reportName ?> has a variety of printing devices that can meet your specific business needs. If you already have everything you need, we can manage the printing assets you have.</p>
<br />
<div class="pheader">A3 Functionality</div>
<p>Do you have too much invested in larger, more expensive hardware? Many centralized MFP's are built for large volumes, in excess of 10,000 pages per month. In addition, they can print on larger paper sizes such as A3 (11 x 17 inch) formats. This section outlines the number of A3 Compatible devices you have.</p>

<p>You currently have <?php echo $healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getCount(); ?> devices in your fleet, and of those, <?php echo count($healthcheckViewModel->getDevices()->a3DeviceInstances->getDeviceInstances()) ?> are A3 Compatible. Of the <?php echo number_format($healthcheckViewModel->getDevices()->allIncludedDeviceInstances->getPageCounts()->getCombinedPageCount()->getMonthly(), 0); ?> total pages printed, <?php echo number_format($healthcheckViewModel->getDevices()->a3DeviceInstances->getPageCounts()->getPrintA3CombinedPageCount()->getMonthly(), 0); ?> are A3 pages, or <?php echo number_format($healthcheckViewModel->calculatePercentageA3Pages() * 100, 0) ?>%. You should also consider A3 devices where AMPV's are low as candidates for replacement or movement.</p>

<p>While analyzing your paper usage we noted that you have purchased <?php echo number_format($healthcheckViewModel->calculatePercentageA3Pages() * 100, 0) ?>% of A3 paper over the past month.</p>

<p>The following are A3 designated devices with a low page volume. Going forward we can look at moving from A3 back to A4 to save you money.</p>

<table class="table table-bordered">
    <tr>
        <th>Device Name</th>
        <th>Serial No.</th>
        <th>Average Monthly Volume</th>
        <th>Average Monthly A3 Volume</th>
    </tr>
    <?php foreach ($healthcheckViewModel->getUnderutilizedA3Devices() as $deviceInstance) : ?>
        <tr>
            <?php $deviceName = str_replace("Hewlett-Packard", "HP", $deviceInstance->getDeviceName()) ?>
            <td><?php echo $deviceName; ?></td>
            <td><?php echo $deviceInstance->serialNumber; ?></td>
            <td><?php echo number_format($deviceInstance->getPageCounts()->getCombinedPageCount()->getMonthly(), 0); ?></td>
            <td><?php echo number_format($deviceInstance->getPageCounts()->getPrintA3CombinedPageCount()->getMonthly(), 0); ?></td>
        </tr>
    <?php endforeach; ?>
</table>
<div class="center">
    <table>
        <tr>
            <td><img src="<?php echo $graphs['a3CapablePieChart']; ?>" /></td>
            <td><img src="<?php echo $graphs['a3PagePercent']; ?>" /></td>
        </tr>
    </table>
</div>
