<?php
/* @var $healthcheckViewModel Healthcheck_ViewModel_Healthcheck */
$healthcheckViewModel = $this->healthcheckViewModel;
$graphs               = $healthcheckViewModel->getGraphs();
?>
<div class="pheader">Estimated OEM Toner Costs vs. Compatible Toner Costs</div>

<p>You can save an additional <?= $this->currency($healthcheckViewModel->calculateOptimizedTonerOrderSavings()); ?> over the first month and approximately <?= $this->currency($healthcheckViewModel->calculateOptimizedTonerOrderSavings() * 12); ?> over 12 months by moving to the suggested products on the analysis below. That is a total savings of <?= number_format($healthcheckViewModel->calculateOptimizedTonerOrderSavingPercentage()); ?>% going forward.</p>
<br />
<table class="genericTable" id="oemVsCompTable">
    <thead>
    <tr class="shaded">
        <th>SKU</th>
        <th>VPN</th>
        <th>Qty</th>
        <th>Price</th>
        <th>New SKU</th>
        <th>New VPN</th>
        <th>New Price</th>
        <th>Net Savings</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $totalNetSavings = 0;
    foreach ($healthcheckViewModel->getClientTonerOrders() as $clientTonerOrder) :
        ?>
        <tr>
            <td><?= $clientTonerOrder->dealerSku; ?></td>
            <td><?= $clientTonerOrder->oemSku; ?></td>
            <td class="text-right"><?= number_format($clientTonerOrder->quantity); ?></td>
            <td class="text-right"><?= $this->currency($clientTonerOrder->cost); ?></td>
            <?php if ($clientTonerOrder->replacementTonerId > 0) : ?>
                <td><?= ($clientTonerOrder->getReplacementToner()->getDealerTonerAttribute($healthcheckViewModel->healthcheck->dealerId)) ? $clientTonerOrder->getReplacementToner()->getDealerTonerAttribute($healthcheckViewModel->healthcheck->dealerId)->dealerSku : '-'; ?></td>
                <td><?= $clientTonerOrder->getReplacementToner()->sku; ?></td>
                <td class="text-right"><?= $this->currency($clientTonerOrder->getReplacementTonerCost($healthcheckViewModel->healthcheck->getClient()->getClientSettings()->genericSettings->tonerPricingMargin)); ?></td>
                <td class="text-right"><?= $this->currency($clientTonerOrder->getReplacementTonerSavings($healthcheckViewModel->healthcheck->getClient()->getClientSettings()->genericSettings->tonerPricingMargin)); ?></td>
                <?php $totalNetSavings += $clientTonerOrder->getReplacementTonerSavings($healthcheckViewModel->healthcheck->getClient()->getClientSettings()->genericSettings->tonerPricingMargin); ?>
            <?php else : ?>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            <?php endif; ?>
        </tr>

    <?php endforeach; ?>
    <tr class="shaded">
        <td colspan="7"></td>
        <td class="text-right"><?= $this->currency($totalNetSavings); ?></td>
    </tr>
    </tbody>
</table>